### ISSUE TITLE
RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054 

### ISSUE THREAD

**Issue by sunnyggadekar** [dotnet-architecture/eShopOnContainers#1006]
Tried increasing git buffer , disabling firewall , installed latest git, unshallow fetch nothing seems to work any suggestions 

Getting this error while cloning the dev branch

**Comment by mvelosop** [comment]
Hi @sunnyggadekar, first time ever 🙁

But this SO questions seems just like your issue, and there are several possible solutions.

https://stackoverflow.com/questions/46232906/git-clone-error-rpc-failed-curl-56-openssl-ssl-read-ssl-error-syscall-errno

Hope this helps.

**Comment by brunodcastilho** [comment]
I solved the problem just by undoing the commits, creating another branch, and trying again.

**Comment by StarDev930** [comment]
I have the same issue. How to solve the problem. Please tell me about how to solve the problem. Thank you.

error: RPC failed; curl 56 OpenSSL SSL_read: Connection was reset, errno 10054
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: index-pack failed
