### ISSUE TITLE
[ebook] consider jpeg instead of tiff image format

### ISSUE THREAD

**Issue by vintzl** [dotnet-architecture/eShopOnContainers#1007]
A lot of images in tiff format are not visible in epub and mobi readers—among other Kindle…
Consider to use jpeg instead of tiff format…

**Comment by mvelosop** [comment]
Hi @vintzl, 

That's definitely weird, perhaps there's something in the conversion process, since all source images are PNGs.

Can you post some details of your setup, including ebook version and specific sample images, to investigate, please?

**Comment by vintzl** [comment]
hi @mvelosop 

I hope this should be better. Here what you get when you extract the ebook:
```
.
├── META-INF
│   ├── calibre_bookmarks.txt
│   └── container.xml
├── content.opf
├── cover.jpeg
├── images
│   ├── Screen_Shot_2019-01-15_at_1.39.08_PM.png
│   ├── Screen_Shot_2019-01-15_at_1.43.47_PM.png
│   ├── Screen_Shot_2019-01-15_at_1.45.44_PM.png
│   ├── Screen_Shot_2019-01-15_at_1.46.47_PM.png
│   ├── Screen_Shot_2019-01-15_at_1.47.27_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.09.14_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.10.18_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.10.43_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.11.10_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.13.36_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.13.43_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.14.31_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.15.04_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.15.13_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.16.04_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.16.36_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.17.17_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.18.04_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.18.42_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.19.23_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.19.59_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.20.32_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.20.58_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.21.40_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.22.17_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.22.45_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.22.54_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.23.06_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.24.18_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.24.25_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.24.34_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.25.36_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.25.43_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.29.43_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.30.31_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.30.49_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.33.38_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.35.47_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.35.55_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.37.25_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.37.31_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.37.38_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.37.45_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.38.54_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.39.02_PM.png
│   ├── Screen_Shot_2019-01-15_at_6.39.10_PM.png
│   ├── Screen_Shot_2019-01-16_at_11.32.36_AM.png
│   ├── Screen_Shot_2019-01-16_at_11.36.19_AM.png
│   ├── Screen_Shot_2019-01-16_at_11.38.19_AM.png
│   ├── Screen_Shot_2019-01-16_at_11.49.44_AM.png
│   ├── Screen_Shot_2019-01-16_at_11.50.21_AM.png
│   ├── Screen_Shot_2019-01-16_at_11.58.18_AM.png
│   ├── Screen_Shot_2019-01-16_at_12.01.54_PM.png
│   ├── Screen_Shot_2019-01-16_at_12.04.39_PM.png
│   ├── Screen_Shot_2019-01-16_at_12.04.44_PM.png
│   ├── Screen_Shot_2019-01-16_at_12.14.00_PM.png
│   ├── Screen_Shot_2019-01-16_at_12.24.38_PM.png
│   ├── Screen_Shot_2019-01-16_at_12.24.53_PM.png
│   ├── Screen_Shot_2019-01-16_at_12.30.21_PM.png
│   ├── Screen_Shot_2019-01-16_at_12.33.36_PM.png
│   ├── Screen_Shot_2019-01-16_at_12.42.08_PM.png
│   ├── Screen_Shot_2019-01-16_at_12.42.15_PM.png
│   ├── Screen_Shot_2019-01-16_at_12.45.37_PM.png
│   ├── Screen_Shot_2019-01-16_at_12.47.26_PM.png
│   ├── image-1.png
│   ├── image-10.png
│   ├── image-100.png
│   ├── image-101.png
│   ├── image-102.png
│   ├── image-103.png
│   ├── image-104.png
│   ├── image-105.png
│   ├── image-106.png
│   ├── image-107.png
│   ├── image-108.png
│   ├── image-109.png
│   ├── image-11.png
│   ├── image-110.png
│   ├── image-111.png
│   ├── image-112.png
│   ├── image-113.png
│   ├── image-114.png
│   ├── image-115.png
│   ├── image-116.png
│   ├── image-117.png
│   ├── image-118.png
│   ├── image-119.png
│   ├── image-12.png
│   ├── image-120.png
│   ├── image-121.png
│   ├── image-122.png
│   ├── image-123.png
│   ├── image-124.png
│   ├── image-125.png
│   ├── image-126.png
│   ├── image-127.png
│   ├── image-128.png
│   ├── image-129.png
│   ├── image-13.png
│   ├── image-14.png
│   ├── image-15.png
│   ├── image-16.png
│   ├── image-17.png
│   ├── image-18.png
│   ├── image-19.png
│   ├── image-2.png
│   ├── image-20.png
│   ├── image-21.png
│   ├── image-22.png
│   ├── image-23.png
│   ├── image-24.png
│   ├── image-25.png
│   ├── image-26.png
│   ├── image-27.png
│   ├── image-28.png
│   ├── image-29.png
│   ├── image-3.png
│   ├── image-30.png
│   ├── image-31.png
│   ├── image-32.png
│   ├── image-33.png
│   ├── image-34.png
│   ├── image-35.png
│   ├── image-36.png
│   ├── image-37.png
│   ├── image-38.png
│   ├── image-39.png
│   ├── image-4.png
│   ├── image-40.png
│   ├── image-41.png
│   ├── image-42.png
│   ├── image-43.png
│   ├── image-44.png
│   ├── image-45.png
│   ├── image-46.png
│   ├── image-47.png
│   ├── image-48.png
│   ├── image-49.png
│   ├── image-5.png
│   ├── image-50.png
│   ├── image-51.png
│   ├── image-52.png
│   ├── image-53.png
│   ├── image-54.png
│   ├── image-55.png
│   ├── image-56.png
│   ├── image-57.png
│   ├── image-58.png
│   ├── image-59.png
│   ├── image-6.png
│   ├── image-60.png
│   ├── image-61.png
│   ├── image-62.png
│   ├── image-63.png
│   ├── image-64.png
│   ├── image-65.png
│   ├── image-66.png
│   ├── image-67.png
│   ├── image-68.png
│   ├── image-69.png
│   ├── image-7.png
│   ├── image-70.png
│   ├── image-71.png
│   ├── image-72.png
│   ├── image-73.png
│   ├── image-74.png
│   ├── image-75.png
│   ├── image-76.png
│   ├── image-77.png
│   ├── image-78.png
│   ├── image-79.png
│   ├── image-8.png
│   ├── image-80.png
│   ├── image-81.png
│   ├── image-82.png
│   ├── image-83.png
│   ├── image-84.png
│   ├── image-85.png
│   ├── image-86.png
│   ├── image-87.png
│   ├── image-88.png
│   ├── image-89.png
│   ├── image-9.png
│   ├── image-90.png
│   ├── image-91.png
│   ├── image-92.png
│   ├── image-93.png
│   ├── image-94.png
│   ├── image-95.png
│   ├── image-96.png
│   ├── image-97.png
│   ├── image-98.png
│   ├── image-99.png
│   ├── image101.tiff
│   ├── image115.tiff
│   ├── image116.tiff
│   ├── image117.tiff
│   ├── image118.tiff
│   ├── image120.tiff
│   ├── image123.tiff
│   ├── image125.tiff
│   ├── image126.tiff
│   ├── image128.tiff
│   ├── image130.tiff
│   ├── image133.tiff
│   ├── image134.tiff
│   ├── image136.tiff
│   ├── image137.tiff
│   ├── image139.tiff
│   ├── image140.tiff
│   ├── image141.tiff
│   ├── image143.tiff
│   ├── image144.tiff
│   ├── image145.tiff
│   ├── image146.tiff
│   ├── image147.tiff
│   ├── image152.tiff
│   ├── image153.tiff
│   ├── image154.tiff
│   ├── image155.tiff
│   ├── image157.tiff
│   ├── image159.tiff
│   ├── image161.tiff
│   ├── image164.tiff
│   ├── image165.tiff
│   ├── image173.tiff
│   ├── image174.tiff
│   ├── image175.tiff
│   ├── image176.tiff
│   ├── image177.tiff
│   ├── image184.tiff
│   ├── image185.tiff
│   ├── image186.tiff
│   ├── image187.tiff
│   ├── image194.tiff
│   ├── image197.tiff
│   ├── image198.tiff
│   ├── image199.tiff
│   ├── image203.tiff
│   ├── image205.tiff
│   ├── image206.tiff
│   ├── image207.tiff
│   ├── image210.tiff
│   ├── image211.tiff
│   ├── image212.tiff
│   ├── image213.tiff
│   ├── image214.tiff
│   ├── image215.tiff
│   ├── image218.tiff
│   ├── image219.tiff
│   ├── image220.tiff
│   ├── image221.tiff
│   ├── image223.tiff
│   ├── image224.tiff
│   ├── image227.tiff
│   ├── image228.tiff
│   ├── image229.tiff
│   ├── image230.tiff
│   ├── image231.tiff
│   ├── image232.tiff
│   ├── image234.tiff
│   ├── image235.tiff
│   ├── image236.tiff
│   ├── image237.tiff
│   ├── image238.tiff
│   ├── image239.tiff
│   ├── image240.tiff
│   ├── image241.tiff
│   ├── image243.tiff
│   ├── image247.tiff
│   ├── image248.tiff
│   ├── image249.tiff
│   ├── image250.tiff
│   ├── image251.tiff
│   ├── image252.tiff
│   ├── image254.tiff
│   ├── image255.tiff
│   ├── image256.tiff
│   ├── image260.tiff
│   ├── image261.tiff
│   ├── image264.tiff
│   ├── image265.tiff
│   ├── image266.tiff
│   ├── image267.tiff
│   ├── image268.tiff
│   ├── image269.tiff
│   ├── image271.tiff
│   ├── image273.tiff
│   ├── image274.tiff
│   ├── image275.tiff
│   ├── image279.tiff
│   ├── image280.tiff
│   ├── image281.tiff
│   ├── image282.tiff
│   ├── image284.tiff
│   ├── image287.tiff
│   ├── image288.tiff
│   ├── image289.tiff
│   ├── image290.tiff
│   ├── image291.tiff
│   ├── image292.tiff
│   ├── image293.tiff
│   ├── image294.tiff
│   ├── image295.tiff
│   ├── image299.tiff
│   ├── image301.tiff
│   ├── image303.tiff
│   ├── image304.tiff
│   ├── image307.tiff
│   ├── image308.tiff
│   ├── image311.tiff
│   ├── image312.tiff
│   ├── image313.tiff
│   ├── image314.tiff
│   ├── image316.tiff
│   ├── image317.tiff
│   ├── image318.tiff
│   ├── image319.tiff
│   ├── image320.tiff
│   ├── image321.tiff
│   ├── image322.tiff
│   ├── image323.tiff
│   ├── image324.tiff
│   └── image325.tiff
├── index_split_000.html
├── index_split_001.html
├── index_split_002.html
├── index_split_003.html
├── index_split_004.html
├── index_split_005.html
├── index_split_006.html
├── index_split_007.html
├── index_split_008.html
├── index_split_009.html
├── index_split_010.html
├── index_split_011.html
├── index_split_012.html
├── index_split_013.html
├── index_split_014.html
├── index_split_015.html
├── index_split_016.html
├── mimetype
├── page_styles.css
├── stylesheet.css
├── titlepage.xhtml
└── toc.ncx

```

**Comment by mvelosop** [comment]
Thanks @vintzl, this is kind of a mistery to me now!

Could you paste here a couple of the .tiff images with their image numbers to check, please?

@nishanil, I don't have the source of the mobile versions can you take a look at this?

**Comment by nishanil** [comment]
Hey @vintzl Thank you for bringing this to our attention. I have reached out to the vendors who help us with the Mobile format conversion. I will keep you posted.

**Comment by vintzl** [comment]
@mvelosop @nishanil 
Take a look at this:
https://github.com/vintzl/-EBOOK-NET-Microservices-Architecture-for-Containerized-NET-Applications--Microsoft-for-eReader-

**Comment by mvelosop** [comment]
Thanks @vintzl! 

@nishanil didn't check all files, but FWIW, 10 out of 10 images I checked were code!

**Comment by vintzl** [comment]
Hi, you're welcome!

Most tiff images are code, others are configuration files (like docker config files).
Another problem seems only related to tiff files. The code shown in these tiff is always? displayed above their mentions, like this:

https://github.com/vintzl/-EBOOK-NET-Microservices-Architecture-for-Containerized-NET-Applications--Microsoft-for-eReader-/blob/6aa15d7dab5a79ed7a6a8147ed6d9b8f599cafe8/NET-Microservices-Architecture-for-Containerized-NET-Applications-(Microsoft-for-eReader)/index_split_010.html#L102

 `<p class="block_27"><span class="text_8"><img src="images/image184.tiff" alt="Image" class="calibre173"/>As shown in the following code, a </span><span class="text_9">ViewModel</span><span class="text_8"> can be directly returned by the queries by just returning a </span><span class="text_21">dynamic</span><span class="text_8"> type that internally is based on the attributes returned by a query. That means that the subset of attributes to be returned is based on the query itself. Therefore, if you add a new column to the query or join, that data is dynamically added to the returned </span><span class="text_9">ViewModel</span><span class="text_8">. </span></p>`

As an aside, seems there is a mistake in file _index_split_010.html_, line 538:

https://github.com/vintzl/-EBOOK-NET-Microservices-Architecture-for-Containerized-NET-Applications--Microsoft-for-eReader-/blob/6aa15d7dab5a79ed7a6a8147ed6d9b8f599cafe8/NET-Microservices-Architecture-for-Containerized-NET-Applications-(Microsoft-for-eReader)/index_split_010.html#L538

> …allows you to add as many domain rules **without as needed**, without affecting current code.

**Comment by nishanil** [comment]
@vintzl What reader are you using? Is the problem specific to .epub or .mobi? 
I verified the .mobi version on a Kindle device and it is rendering those images on my device. I checked the .epub on Edge on Windows and it works too.

**Comment by vintzl** [comment]
@nishanil
Just to be sure, I have downloaded the latest version of the ebook from [here](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/).
**Both format, meaning .epub and .mobi, embed** tiff files.
I tried with

- E-book viewer (the one provided with Calibre, the same software that is used, at least, to generate your epub version).
- Kindle Paper White, with up to date firmware.

**Comment by nishanil** [comment]
Yes, the links to [MOBI](https://www.microsoft.com/net/download/thank-you/microservices-architecture-ebook-mobi) | [EPUB](https://www.microsoft.com/net/download/thank-you/microservices-architecture-ebook-epub) mentioned there are correct.
And, here's the code file that is being rendered on my Kindle Paper White
![IMG_0374](https://user-images.githubusercontent.com/3107766/56607534-602f1700-6626-11e9-9130-f904a8709219.jpeg)

**Comment by vintzl** [comment]
If I am not mistaken, **this file is not a tiff**, is it a png, the _Screen_Shot_2019-01-15_at_6.14.31_PM.png_

**Comment by nishanil** [comment]
Ah, I see. That's strange then. Some code files are in png.

**Comment by vintzl** [comment]
Yes. Take a look at the repo. You will see that some are tiff…

**Comment by nishanil** [comment]
Got it! I will check with the vendors if they can standardize the images to .pngs. Thanks again!

**Comment by mvelosop** [comment]
Well... I know that page as I wrote that detail 😞, and in one of the first revisions that specific code was actually an image (png), but it was later changed to text.

However, as I remember, that was an exception, and all of the TIFF images in @vintzl's repo were code, so there seems to be something else here.

**Comment by vintzl** [comment]
@mvelosop you talk about this?

> …allows you to add as many domain rules **without as needed, without affecting** current code.

Anyway, I had forgotten, there is a glitch there:

https://github.com/vintzl/-EBOOK-NET-Microservices-Architecture-for-Containerized-NET-Applications--Microsoft-for-eReader-/blob/6aa15d7dab5a79ed7a6a8147ed6d9b8f599cafe8/NET-Microservices-Architecture-for-Containerized-NET-Applications-(Microsoft-for-eReader)/index_split_011.html#L477

> Implement idempotent Commands
> In eShopOnContainers, a more advanced example than the above is submitting a CreateOrderCommand object from the Ordering microservice. But since the Ordering business process is a bit more complex and, in our case, it actually starts in the Basket microservice, this action of submitting the CreateOrderCommand object is performed from an integration-event handler named >UserCheckoutAcceptedIntegrationEvent.cs](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.API/Application/IntegrationEvents/EventHandling/UserCheckoutAcceptedIntegrationEventHandler.cs) instead of a simple WebAPI controller called from the client App as in the previous simpler example.
>

**Comment by vintzl** [comment]
@mvelosop 
You can see another glitch, in image318.tiff (duplicated line with case variation for _configuration/Configuration_).

https://github.com/vintzl/-EBOOK-NET-Microservices-Architecture-for-Containerized-NET-Applications--Microsoft-for-eReader-/blob/master/NET-Microservices-Architecture-for-Containerized-NET-Applications-(Microsoft-for-eReader)/images/image318.tiff?raw=true

Now, I am not sure to understand this, as I have already did this—SPA + Cookies with ASP.NET Core + ASP.NET Core Identity, **and it works**:
> For example, in an ASP.NET Core Web API that exposes RESTful endpoints that might be accessed by Single Page Applications (SPAs), by native clients, or even by other Web APIs, you typically want to use bearer token authentication instead. **These types of applications _do not work_ with cookies,** but can easily retrieve a bearer token and include it in the authorization header of subsequent requests.

Finally, it could be great to have the sources available in a repo to clean/review the ebook codes.
- I know, even if it is a "bug", tiff files are heavier than png/jpg
- remove empty tags like
```	<p class="block_15"> </p>
	<p class="block_15"> </p>
	<p class="block_15"> </p>
	<p class="block_15"> </p>
	<p class="block_15"> </p>
	<p class="block_15"> </p>
```
- remove unnecessary "code" like `alt="C:\Users\Miguel\source\repos\dotnet\docs\docs\standard\microservices-architecture\docker-application-development-process\media\image19.png"`
- better styling (some list are too much indented);
- etc…

**Comment by mvelosop** [comment]
@vintzl, you can read, and submit corrections too, on line, just go to https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/ 

On any page, you can click the edit icon:

![image](https://user-images.githubusercontent.com/7357806/57098772-c563c600-6d12-11e9-9b46-34d9b422e853.png)

**And then click on the edit icon again:**

![image](https://user-images.githubusercontent.com/7357806/57098841-efb58380-6d12-11e9-83b4-bbec163e9ecd.png)

**To fix anything:**

![image](https://user-images.githubusercontent.com/7357806/57099358-2c35af00-6d14-11e9-866c-8d59fb68195e.png)

You'll need a GitHub account and the edition is in markdown.

Once you submit a PR it goes through a review process and publishing pipeline, so it takes a while to view the updates on line at docs.microsoft.com, but they get there.

There's a longer delay for PDF and mobile version.

The next PDF versions are going to be generated right from docs.microsoft.com version.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now, but feel free to comment, will reopen if needed.
