### ISSUE TITLE
Error of Installing eShopOnContainers with Helm thru Powershell 

### ISSUE THREAD

**Issue by wely** [dotnet-architecture/eShopOnContainers#1015]
Hi guys,

I'm following the steps here: https://github.com/dotnet-architecture/eShopOnContainers/wiki/10.-Deploying-to-Kubernetes-(AKS-and-local)-using-Helm-Charts, executing:

.\deploy-all.ps1 -externalDns aks -aksName eshoptest -aksRg eshoptest -imageTag dev

but encountered the following error:

![image](https://user-images.githubusercontent.com/1658657/56713954-dc7c4400-6765-11e9-9434-f014345cb9cd.png)

Wondering if you have a clue?

**Comment by nishanil** [comment]
@eiximenis I get the same error executing this script locally (Kubernetes on Docker Desktop).

**Comment by wely** [comment]
I'm running this command from my local machine Powershell against an AKS cluster with Helm already installed.

**Comment by DanielLarsenNZ** [comment]
Hi @wely I had the same issue. Try changing these three lines until this gets fixed/merged: https://github.com/dotnet-architecture/eShopOnContainers/pull/1020/files

**Comment by wely** [comment]
Awesome @DanielLarsenNZ . Works now after adding the quotes.

**Comment by doggy8088** [comment]
@wely This issue is not solved yet, but there is a PR not merged yet. Can you can re-open this issue again so that this issue can be tracked.
