### ISSUE TITLE
[BUG] PublishEventsThroughEventBusAsync() published duplicates on concurrent requests

### ISSUE THREAD

**Issue by stoubia** [dotnet-architecture/eShopOnContainers#1022]
I've run into a problem with the approach of publishing events as part of the command pipeline.  in my particular scenario, I'm uploading multiple files at the same time using one request per file.  

Multiple requests coming in simultaneously are producing many events that are pending publishing.  The first request to complete begins publishing events to the event bus by getting all the events that are status 'pending'.  Then the events are iterated through and marked as in process individually right before being published to the event log.  This means that there is a gap of time between retrieving the pending events and marking them as 'InProcess'.  So, if during that time another thread queries for all of the pending events, those events are going to be duplicated.  The problem gets exponentially worse the bigger the number of requests x pending events are.

Is my understanding of this correct?

```

public async Task PublishEventsThroughEventBusAsync()
        {
// multiple threads can get all the pending events
            var pendindLogEvents = await _eventLogService.RetrieveEventLogsPendingToPublishAsync();

            foreach (var logEvt in pendindLogEvents)
            {
               
                _logger.LogInformation("----- Publishing integration event: {IntegrationEventId} from {AppName} - ({@IntegrationEvent})", logEvt.EventId, Program.AppName, logEvt.IntegrationEvent);

                try
                {
                    // each event is marked as in process one at a time
                    await _eventLogService.MarkEventAsInProgressAsync(logEvt.EventId);
                    // publishing may take some time, 
                    // all the while the rest of my unpublished events are still 'unpublished' status
                    _eventBus.Publish(logEvt.IntegrationEvent);
                    await _eventLogService.MarkEventAsPublishedAsync(logEvt.EventId);
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "ERROR publishing integration event: {IntegrationEventId} from {AppName}", logEvt.EventId, Program.AppName);

                    await _eventLogService.MarkEventAsFailedAsync(logEvt.EventId);
                }
            }
        }
```

My first thought was to pull them out one by one while at the same time updating their status.  It didn't really improve the situation enough.  Maybe the EventLogService needs to be made a concurrency save singleton?  What can be done to improve this process?  

Another thought I had was to change the database fetching strategy to be more or less like this: 
```
begin transaction

update EventLog  
	set status = 'InProcess' 
output inserted.*
where status = 'Pending' 

commit transaction
```
At least this updates the status to InProcess while fetching, as well as preventing any concurrent reads while also allowing concurrent inserts.  Any other threads may be blocked while the first one is running, but it would be for a very short time.

It really seems like the issue just comes down to publishing events as part of the mediator command pipeline.  I saw in some other tickets mention of using a separate microservice for watching and publishing events, but that would pretty much add another event publishing service per microservice.  What would be a reasonable way to improve publishing process?

**Comment by mvelosop** [comment]
Hi @stoubia,

I think you're right in you appreciation!

This approach was taken to ensure transactional atomicity so all chained commands deriving from an integration event are queued and published once the "main" transaction completes, but then what you mention can happen.

The first solution that comes to my mind is saving the transaction id to the event log, so we can query for the pending integration events of the current transaction only.

That way, we'd only publish the integration events created in the current TransactionBehavior scope, so there wouldn't be any clash between incoming integration events.

The strategy you mention could be a way to do it but I think it'd still not be enough, because there'd still the possibility for a thread to pick to-publish integration events from another incoming integration event, which is kind your situation, if if got it right.

Perhaps the best solution would be to have a single background thread, publishing the derived integration events. But then again, that would only work when running one container per service.

Thoughts?

**Comment by stoubia** [comment]
@mvelosop, apologies for the delay.  
 Seems to me that your solution solves the issue.  I ended up going with the solution I proposed by creating a new integration event log service (IntegrationEventLogDapper) that implements IIntegrationEventLog.  This also prevents duplicate publications, but as you pointed out, one thread can still grab events from other threads, so one thread may end up doing most of the work there.  Just to clarify, this still prevents duplicate publishes because it is using the DB in a concurrency safe way since only one of those update commands can run at once.

I'm also not using a DB transaction in my MediatR pipeline.  Instead of having two DB contexts in my service (service context, event log context), I made my service contexts inherit the event log context so all event log changes naturally get captured in the UoW.

In the end, I do agree that the best solution would probably be a separate publishing service of some sort, especially because there are other use cases that would need to be handled (republishing failed events?  republishing events stuck in 'publishing' status?).  For me, I'm not using docker, so the extra overhead of each new service isn't small.  Should be much more manageable with docker.

**Comment by mvelosop** [comment]
Hi @stoubia, no worries! that was a nice issue you realized 😊

I'd say there are many good solutions, it's just important that whatever you choose works in your context, which may not in some other, but that's OK.

Hey, come back any time if you find something else!

Good luck! 😊
