### ISSUE TITLE
[BUG] Health Checks UI (webstatus) shows empty health checks page

### ISSUE THREAD

**Issue by bennettfactor** [dotnet-architecture/eShopOnContainers#1024]
Running commit latest commit as of writing (ab94afdd) off dev branch.

I followed all the setup instructions, running locally using VS 2019 and just hit F5.

Everything seems to work fine except the webstatus / health checks page.

The health checks UI page shows up, but no checks appear in the grid when I visit http://localhost:5107/hc-ui

**Comment by mvelosop** [comment]
Hi @bennettfactor, yep it looks like a bug, I get just the same!

In the meantime you can try running the app from the CLI, is should run fine.

Hope this helps!

**Comment by bennettfactor** [comment]
Thank you!
