### ISSUE TITLE
Multi-role App map in App Insight

### ISSUE THREAD

**Issue by wely** [dotnet-architecture/eShopOnContainers#1027]
https://github.com/dotnet-architecture/eShopOnContainers/wiki/14.-Using-Application-Insights-in-eShopOnContainers#create-an-app-insights-service

can't find the Preview tab for setting the multi-role app

**Comment by mvelosop** [comment]
Hi @wely,

That's currently an old documentation (that's being updated), in the meantime you might want to take a look at the [Azure Monitor for containers](https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-overview)

Hope this helps.
