### ISSUE TITLE
Catalog.WebForms missing almost all files cant be compiled

### ISSUE THREAD

**Issue by eliassal** [dotnet-architecture/eShopOnContainers#1037]
Hi, I am reading the chapter 

> Migrating Legacy Monolithic .NET Framework Applications to Windows Containers

 in the book 

> NET-Microservices-Architecture-for-Containerized-NET-Applications

Opening the app, the at 

> eShopOnContainers/src/Web/Catalog.WebForms/

 
is completely corrupt, when opening the project in VS is different than what we see in the image on page 97, 1st of all, here a lot of directories and  files are missing such as scrips & services directory, then almost all files (Contact, dockerfile, Appinsight.........).
Can you please update 

> eShopOnContainers/src/Web/Catalog.WebForms/

with the right files?

**Comment by eliassal** [comment]
![CatalogForms](https://user-images.githubusercontent.com/8447864/57469953-0d8d6600-7288-11e9-8b1c-98358a2fa8c9.jpg)
![CatalogForms_002](https://user-images.githubusercontent.com/8447864/57469970-15e5a100-7288-11e9-9568-d55d8f69ecaa.jpg)

**Comment by eliassal** [comment]
I double checked the zip file I downloaded and your source cod files on this GitHub there is a  huge mismatch

**Comment by eliassal** [comment]
in the book it shows this
![CatalogForms_003](https://user-images.githubusercontent.com/8447864/57470135-7248c080-7288-11e9-8dd4-2092b2ef7fcf.jpg)

**Comment by mvelosop** [comment]
Hi @eliassal, you are looking at a quite old version of the e-book!

You should download the latest version from the [Microsoft Architecture Guides](https://dotnet.microsoft.com/learn/dotnet/architecture-guides), which is the same one pointed out to by the [README in this repo](https://github.com/dotnet-architecture/eShopOnContainers#related-documentation-and-guidance). The e-book is actually served from the [docs folder in this repo](https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/docs), where you can also find the previous versions.

You can also see the [guide on line](https://docs.microsoft.com/dotnet/standard/microservices-architecture/), for the latest and most up-to-date content.

That project hasn't been maintained for a long time, so it should probably be archived, along with WebMonolithic.

Hope this helps.

**Comment by mvelosop** [comment]
I confirmed this was a draft WebForms project, so I just removed it, along with WebMonolithic, which was continued in https://github.com/dotnet-architecture/eShopOnWeb
