### ISSUE TITLE
The Xamarin Previewer is not working

### ISSUE THREAD

**Issue by epomeranz** [dotnet-architecture/eShopOnContainers#1038]
Hi 
I can't get the Xamarin previewer to work. Instead of seeing a preview of the XAML code I get a gray screen with the message "AndroidFormsPreviewerRenderer"...

A bit more info below:
I'm trying this amazing github example in VS2017 running in windows with everything up to date (I also tried it on VS2019).
I'm only trying the Android app (I don't have a mac)
Building and debugging works fine with the out of the box code, and also if I update the nuget packages. Everything except for the Xamarin previewer.  The previewer does not work in 2017 or 2019, with the original code or after updating the nuget packages. However the Xamarin previewer works for other projects so it's something about this project...

As far as I can tell I followed all the installation instructions step by step.

I'm relatively new to Xamarin development so I was wondering if:
-Is there is something not so obvious - for Xamarin newbies - I should check or setup to get the previewer working?
-Is there a way to troubleshoot this? All the feedback I get is the "AndroidFormsPreviewerRenderer" message which is completely useless.
-Does the previewer have a log somewhere?
-Anything I should try/do?

Thank you,
Eric

**Comment by epomeranz** [comment]
Update:
After reinstalling Visual Studio and spending 3 days trying to figure out the problem I'm still nowhere closer. The Xamarin Design Previewer works for other projects but not this one...
I have the community version and here is the activity log...
https://drive.google.com/file/d/19q3HhMrx_EXyxo8KjhPHgj3yfzLDA-Ug/view?usp=sharing

Does anybody have a suggestion on what to do?

Thanks,
Eric

**Comment by conceptdev** [comment]
@epomeranz if the previewer is failing on a project that otherwise builds and runs successfully, it sounds like an issue that should be [reported in Visual Studio](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio).

You could also check the [Previewer troubleshooting info](https://docs.microsoft.com/xamarin/xamarin-forms/xaml/xaml-previewer/?pivots=macos#troubleshooting).
