### ISSUE TITLE
Docker cannot be installed on Windows Home Edition

### ISSUE THREAD

**Issue by bofcarbon1** [dotnet-architecture/eShopOnContainers#1039]
Docker cannot be installed on Windows Home Edition
But you said anyone can run this on their laptop.

**Comment by mvelosop** [comment]
Hi @bofcarbon1, this is just what happens with any software, there are always some system requirements, some are related to hardware and others to software.

You can see the whole requirements in the wiki: https://github.com/dotnet-architecture/eShopOnContainers/wiki#setting-up-your-development-environment-for-eshoponcontainers

I regret I can't be any more helpful 😔 

This is a large application, that's currently running 25 Linux containers so it's a bit tough on system requirements.

**Comment by bofcarbon1** [comment]
Well I reached out to Microsoft about offering some free space to developers that just want to learn by doing on Azure. This is a good example of where things breakdown for us. I use a free dyno on Heroku to host my web resume. Why doesn't Microsoft offer a limited free space on Azure for learning. One without a credit card. Just set up a VM machine to work off with limits on data and data transfer?

**Comment by mvelosop** [comment]
Well @bofcarbon1, there's actually a free offer where you can use some services free for ever, some others free for 12 months and even use any service in the first 30 days with a limit of 200 US$ total consumption.

You do need a credit (or debit) card to register, but it'll only be charged when/if you authorize it.

You can get more information and all the details in https://azure.microsoft.com/free/

Hope this helps.

**Comment by bofcarbon1** [comment]
Awesome I will check that out.

Thanks,

**Comment by bofcarbon1** [comment]
Sadly I did use this before.
I used very little resources and despite the $200 free tier credits
which I barely put a dent in got charged $7 for incidentals.
I can't put a credit card on Azure.

Brian
