### ISSUE TITLE
Error on Installing eShopOnContainers with Helm through powershell

### ISSUE THREAD

**Issue by ahsangee88** [dotnet-architecture/eShopOnContainers#1046]
I am getting the following error while trying to install through helm.
![image](https://user-images.githubusercontent.com/1209470/57965202-79f11f00-7984-11e9-8713-432cf2e585a0.png)

When i run the command to _kubectl get deployment_, following is the result. This obviously shows that the items mentioned in the above screenshot have failed.

![image](https://user-images.githubusercontent.com/1209470/57965214-ac028100-7984-11e9-9b99-9b0882679980.png)

**Comment by antonabyzov** [comment]
I also experience an issue running it, though I get error below and no deployments created
![image](https://user-images.githubusercontent.com/44438816/57990755-414f6380-7ab2-11e9-9b4a-a1b8394818dc.png)

**Comment by antonabyzov** [comment]
In my case this PR fixes it - https://github.com/dotnet-architecture/eShopOnContainers/pull/1020

**Comment by ahsangee88** [comment]
I had this issue as well earlier. But, as you have mentioned 1020 solved that one. And now I am stuck on the one I have posted above.

**Comment by ahsangee88** [comment]
@antonabyzov is it possible for you to assign this issue to someone so that I can get an answer on this?

**Comment by antonabyzov** [comment]
> @antonabyzov is it possible for you to assign this issue to someone so that I can get an answer on this?

unfortunately, it's not allowed with my permissions 
![image](https://user-images.githubusercontent.com/44438816/58063338-55fd2b80-7b86-11e9-8942-95847dcbfda6.png)

**Comment by ahsangee88** [comment]
@mvelosop  can you please provide some help on this.

**Comment by mvelosop** [comment]
Hi @ahsangee88, @antonabyzov,

I'm resuming the work with this, I found the same issue last week, will check the PR too!

**Comment by antonabyzov** [comment]
From the error message it looks like it's a validation of instrumentation_key. But I've added value for INSTRUMENTATION_KEY in my .env file from my Azure account (create app in Application Insights) and it still doesn't work keeping the same error. Please advise.

**Comment by mvelosop** [comment]
Hi @antonabyzov, could you try update your local repo now? 

The PR wasn't merged because the pipeline validation was running!

Just finished 45 minutes after you tried, so it wasn't really "fixed" in **dev** by then 😉

BTW, you have to set the instrumentation key in the `k8s/helm/inf.yaml` file for k8s to use it. But don't use it now, just to check it's OK.

Hope this helps.

**Comment by antonabyzov** [comment]
It did help, now script runs without errors and looks like everything is created as needed! Thank you so much!

**Comment by mvelosop** [comment]
Great!

It's not 100% yet, but I'm working on it. I'll publish a new wiki page when ready!
