### ISSUE TITLE
Health checks UI shows all unhealthy but everything is working fine

### ISSUE THREAD

**Issue by steveabel** [dotnet-architecture/eShopOnContainers#1048]
I'm using VS2019 and when I run the sample everything runs fine. The MVC website load and functions correctly and the individual endpoints all report 'Healthy'.

However, viewing the Health Checks UI displays all end points as 'Unhealthy' and the error message 'Cannot assign requested address'.

Looking at the debug output I get the following:

[14:43:52 ERR] GetHealthReport threw an exception when trying to get report from http://localhost:5121/hc configured with name Web Shopping Aggregator HTTP Check.
System.Net.Http.HttpRequestException: Cannot assign requested address ---> System.Net.Sockets.SocketException: Cannot assign requested address
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)

A similar error is raised for each end point configured.

Is the problem that the Health Checks UI container can't access the other containers for some reason?

**Comment by mvelosop** [comment]
Hi @steveabel,

I just tested and have no problem with this. 

What's the latest commit for the the branch you're working on?

**Comment by mvelosop** [comment]
Closing this issue now, but feel free to comment. Will reopen if needed.

**Comment by joergjo** [comment]
See [https://docs.docker.com/docker-for-windows/networking/](https://docs.docker.com/docker-for-windows/networking/). Replace `localhost` with `host.docker.internal` in `appsettings.json`.

**Comment by mvelosop** [comment]
Thanks @joergjo, that shouldn't be necessary, but will explore this option to try connecting to a "local" SQL Database. If it worked it'd mean we could reduce Docker memory assignment and more people would be able to try eShopOnContainers 😊

**Comment by joergjo** [comment]
My understanding of the article above and and experience is that neither localhost nor 127.0.0.1 can be resolved from within a container, so you either have to use the special moniker mentioned above, or actual DNS names provided by the container runtime's DNS. Try curling any service URL on localhost from one of eShop's containers to see.
