### ISSUE TITLE
Kubernetes deploy.sh not working on Mac

### ISSUE THREAD

**Issue by antonabyzov** [dotnet-architecture/eShopOnContainers#1053]
When I try to deploy all into my k8s cluster I get this error - 
![helm  devdev-kubernetes-slave  -bash  173×98 2019-05-29 01-47-06](https://user-images.githubusercontent.com/44438816/58517876-9a577f80-81b5-11e9-8f3b-7d8748203eb3.png)

Please advise.

**Comment by PureKrome** [comment]
What error?

**Comment by sughosneo** [comment]
Hi @antonabyzov , we have recently updated our scripts to support latest versions of helm and k8s. 
Could you please refer the updated [wiki page](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes) and try out the steps again ?

Please feel free to write back if you have any questions. 

Thanks.

**Comment by sughosneo** [comment]
Hi @antonabyzov, considering the latest changes are working fine for you, I am closing this issue. If you have any further questions please feel free to reopen it.

Thank you.
