### ISSUE TITLE
Error building solution following Wiki 02 - VS 2017

### ISSUE THREAD

**Issue by kimoerum** [dotnet-architecture/eShopOnContainers#1056]
Hi,
Trying to follow instructions in Wiki 02 - I get this error message:
_Error		(Line: 218, Col: 9, Idx: 5557) - (Line: 218, Col: 9, Idx: 5557): Expected 'MappingStart', got 'SequenceStart' (at Line: 218, Col: 9, Idx: 5557).	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2017 Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	291	Build_	

Using VS2017 ver. 15.9.9 - .NET Core 2.2 - and the DEV branch of eShopOnContainers.

I also tried to use a the alternative format for the environment:
    key1: "value1"
    key2: "value2"
in the docker-compose file - but this had no effect.
Any suggestions on what to do?

**Comment by mvelosop** [comment]
Hi @kimoerum,

Yep, there's a problem with the app, I'll check on it.

In the meantime, you might want to create a branch in your local repo from commit f87ae19bcacdd9df03b38d339e83bac665aaabbc on 24-MAY-2019, so you can try the app, it works fine up to that point.

Hope that helps.

**Comment by DaveBlack93** [comment]
Hi,
I create a local branch aligned with commit ID: f87ae19b.
When I run the docker-compose in debug mode, as suggested in the startup guide, I get an error depending from these messages:

The INSTRUMENTATION_KEY variable is not set. Defaulting to a blank string.
The ORCHESTRATOR_TYPE variable is not set. Defaulting to a blank string.
The ESHOP_SERVICE_BUS_USERNAME variable is not set. Defaulting to a blank string.
The ESHOP_SERVICE_BUS_PASSWORD variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_CATALOG_KEY variable is not set. Defaulting to a blank string.
The ESHOP_AZUREFUNC_CAMPAIGN_DETAILS_URI variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_MARKETING_NAME variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_MARKETING_KEY variable is not set. Defaulting to a blank string.

I notice that in the docker-compose there is no debug config file (docker-compose.debug.yml).
I can create one but which value I have to assign for a first setup?

Thank you for your time,
Davide.

**Comment by inthegarden** [comment]
> Hi @kimoerum,
> 
> Yep, there's a problem with the app, I'll check on it.
> 
> In the meantime, you might want to create a branch in your local repo from commit [f87ae19](https://github.com/dotnet-architecture/eShopOnContainers/commit/f87ae19bcacdd9df03b38d339e83bac665aaabbc) on 24-MAY-2019, so you can try the app, it works fine up to that point.
> 
> Hope that helps.

Is there an ETA on when this issue might be rectified?

Thx

**Comment by mvelosop** [comment]
> Hi,
> I create a local branch aligned with commit ID: [f87ae19](https://github.com/dotnet-architecture/eShopOnContainers/commit/f87ae19bcacdd9df03b38d339e83bac665aaabbc).
> When I run the docker-compose in debug mode, as suggested in the startup guide, I get an error depending from these messages:
> 
> The INSTRUMENTATION_KEY variable is not set. Defaulting to a blank string.
> The ORCHESTRATOR_TYPE variable is not set. Defaulting to a blank string.
> The ESHOP_SERVICE_BUS_USERNAME variable is not set. Defaulting to a blank string.
> The ESHOP_SERVICE_BUS_PASSWORD variable is not set. Defaulting to a blank string.
> The ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not set. Defaulting to a blank string.
> The ESHOP_AZURE_STORAGE_CATALOG_KEY variable is not set. Defaulting to a blank string.
> The ESHOP_AZUREFUNC_CAMPAIGN_DETAILS_URI variable is not set. Defaulting to a blank string.
> The ESHOP_AZURE_STORAGE_MARKETING_NAME variable is not set. Defaulting to a blank string.
> The ESHOP_AZURE_STORAGE_MARKETING_KEY variable is not set. Defaulting to a blank string.
> 
> I notice that in the docker-compose there is no debug config file (docker-compose.debug.yml).
> I can create one but which value I have to assign for a first setup?
> 
> Thank you for your time,
> Davide.

Hi @DaveBlack93 Those values are needed to configure Applications Insight, Azure Service Bus, an container orchestrator like Kubernetes and/or deploying eShop to Azure.

It's just fine when running locally.

Anyway, those environment variables are configured in the **.env** file on the project root folder.

Hope this helps!

**Comment by DaveBlack93** [comment]
Hi @mvelosop ,
thank you for your explaination.
My question is why if I run the docker-compose locally in Debug mode I get errors on those values needed only for Azure configuration when Solution will be deployed on Azure platform?
I'm not able to run the eCommerce solution like described in the startup guide.
Thank you for your time,
Davide.

**Comment by mvelosop** [comment]
@DaveBlack93, those are not really errors, just warnings and don't stop you from running eShop.

If your installation doesn't run it's because of something else.

Did you set up Docker with the 4 GB RAM specified in the setup guide? that's a must!

You could also try running the app from the CLI, it usually runs better/faster:
https://github.com/dotnet-architecture/eShopOnContainers/wiki/03.-Setting-the-eShopOnContainers-solution-up-in-a-Windows-CLI-environment-(dotnet-CLI,-Docker-CLI-and-VS-Code)

**Comment by BeemsAr** [comment]
Hi, I get the same error message:
Error	(Line: 218, Col: 9, Idx: 5557) - (Line: 218, Col: 9, Idx: 5557): Expected 'MappingStart', got 'SequenceStart' (at Line: 218, Col: 9, Idx: 5557).	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2017 Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	291 Build

There is any solution?

Thanks and regards

**Comment by djvruio** [comment]
Hi @kimoerum and all, 
I solved that issue changing line 218 inside docker-compose.yml on docker-compose solution:
line 218 says:
`- NODE_IMAGE=${NODE_IMAGE:-node:8.11}`
I changed for this:
`"NODE_IMAGE": "${NODE_IMAGE:-node:8.11}"`
and it works!!! I hope it works for you too.
Regards to all.

**Comment by dnelly** [comment]
> Hi @kimoerum and all,
> I solved that issue changing line 218 inside docker-compose.yml on docker-compose solution:
> line 218 says:
> `- NODE_IMAGE=${NODE_IMAGE:-node:8.11}`
> I changed for this:
> `"NODE_IMAGE": "${NODE_IMAGE:-node:8.11}"`
> and it works!!! I hope it works for you too.
> Regards to all.

That works, but breaks docker-compose from the command-line.

**Comment by mvelosop** [comment]
Hi,

This seems to be a VS issue, I just created a [new issue for this](https://developercommunity.visualstudio.com/content/problem/608808/docker-compose-project-fails-to-build-when-it-incl.html)

Anyway it was fixed by @eiximenis in commit 33fb3a735ffd77641fed05cc573e875ba492f416

So you just have to refresh your local repo.

Cheers,
