### ISSUE TITLE
Doubts about the use of containers.

### ISSUE THREAD

**Issue by pabloandrei** [dotnet-architecture/eShopOnContainers#1057]
Hello!
In the Docker configuration file (docker-compose.yml), the images used are from the "-eshop" registry.

For example:
identity.api:
    image: ${REGISTRY:-eshop}/identity.api:${PLATFORM:-linux}-${TAG:-latest}

I have the curiosity to know, if it is necessary to use "-eshop"?
Is there any special configuration for each container hosting application in .Net Core?
Which others could you use in Linux environment?

Tks

**Comment by mvelosop** [comment]
Hi @pabloandrei,

That parameter actually configures the use of the "**eshop**" registry if the REGISTRY envinronment variable is not defined, the "-" is just part of the syntax.

The **image:** line above is used to build the parameter `-t eshop/ordering.api:linux-latest` for the **docker build** command, so it gives the resulting image a name and tags.

It's not really necessary to use the "registry" part of the name (or the name at all, for that matter), but it makes it easier to reference the images, for example, to list all **eshop** images or reference the **ordering.api** image. You'd have to use the image Id hash if your didn't tagged an image.

I found a nice article about this subject: https://windsock.io/referencing-docker-images/

You can find each specific container runtime configuration in the docker-compose.override.yml file. Those are plain environment variables, that you can use to configure whatever in your app, when you use  this line in program configuration:

https://github.com/dotnet-architecture/eShopOnContainers/blob/2de66ba6827d6f6f164efccc075a8c460f4920ff/src/Services/Ordering/Ordering.API/Program.cs#L91

You might have seen something like that in `Startup.cs`.

Hope this helps.

**Comment by pabloandrei** [comment]
Tks
