### ISSUE TITLE
Error running docker-compose first time

### ISSUE THREAD

**Issue by DaveBlack93** [dotnet-architecture/eShopOnContainers#1058]
Hi team,
I have clonedfor the first time the solution.
I follow all the steps for the first setup but when I run the eShopOnContainers-ServicesAndWebApps -> docker-compose I get this error: "Error	(Line: 218, Col: 9, Idx: 5557) - (Line: 218, Col: 9, Idx: 5557): Expected 'MappingStart', got 'SequenceStart' (at Line: 218, Col: 9, Idx: 5557).	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	300" and I'm not able to run the solution.
I'm using VS2019 16.1.1 and Docker Desktop Version 2.0.0.3 (31259) on Windows 10 Enterprise.
I'm on dev branch as suggested.
I didn't change nothing just follow the step in the tutorial for the first set up.
Could you help me?
Thank you,
Davide.

**Comment by DaveBlack93** [comment]
It's the same of this issue 1056.
I will close and follow these suggestions.

Regards,
Davide.

**Comment by djvruio** [comment]
Hi @DaveBlack93 
I solved that issue changing line 218 inside docker-compose.yml on docker-compose solution:
line 218 says:
`- NODE_IMAGE=${NODE_IMAGE:-node:8.11}`
I changed for this:
`"NODE_IMAGE": "${NODE_IMAGE:-node:8.11}"`
and it works!!! I hope it works for you too.
Regards to all.
