### ISSUE TITLE
Cannot login from SPA

### ISSUE THREAD

**Issue by rkaralkin** [dotnet-architecture/eShopOnContainers#1061]
Using Chrome and Firefox browsers. When click login button in SPA app there is redirect to http://localhost:5105 happen, and login form doesn't works. Spotted content security policy errors in browser console. Screenshot attached. Is there a way to fix this with configuration changes?

![login-error](https://user-images.githubusercontent.com/4501116/58804192-ed985a80-8619-11e9-98bf-89f4d13126e3.png)

**Comment by eiximenis** [comment]
Hi @rkaralkin 

I think that is due to a CORS update policies in browsers. Give me a couple of days to look at it and try to come with a solution for all the environments...

**Comment by mvelosop** [comment]
Hi @rkaralkin, can you confirm if this still happening to you, please?

I can't reproduce this with the latest version (commit 5cd8fd8c917d4e745e46f1c085a74e450ed68122)

Thanks.

**Comment by mvelosop** [comment]
Closing this issue now as it seems to be solved, but feel free to comment, will reopen if needed
