### ISSUE TITLE
eShopOnContainers.sln - Devspaces.Support.csproj not in solution

### ISSUE THREAD

**Issue by inthegarden** [dotnet-architecture/eShopOnContainers#1062]
I've just done a fresh clone of DEV; tried to build on VS 2017 Professional 15.9.12 and get the following: -

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1105	Unable to find project information for 'C:\Users\aheys\Source\Repos\eShopOnContainers\src\BuildingBlocks\Devspaces.Support\Devspaces.Support.csproj'. Inside Visual Studio, this may be because the project is unloaded or not part of current solution. Otherwise the project file may be invalid or missing targets required for restore.	Mobile.Shopping.HttpAggregator	C:\Users\aheys\Source\Repos\eShopOnContainers\src\ApiGateways\Mobile.Bff.Shopping\aggregator\Mobile.Shopping.HttpAggregator.csproj	1	
Error	NU1105	Unable to find project information for 'C:\Users\aheys\Source\Repos\eShopOnContainers\src\BuildingBlocks\Devspaces.Support\Devspaces.Support.csproj'. Inside Visual Studio, this may be because the project is unloaded or not part of current solution. Otherwise the project file may be invalid or missing targets required for restore.	Web.Shopping.HttpAggregator	C:\Users\aheys\Source\Repos\eShopOnContainers\src\ApiGateways\Web.Bff.Shopping\aggregator\Web.Shopping.HttpAggregator.csproj	1	
Error	NU1105	Unable to find project information for 'C:\Users\aheys\Source\Repos\eShopOnContainers\src\BuildingBlocks\Devspaces.Support\Devspaces.Support.csproj'. Inside Visual Studio, this may be because the project is unloaded or not part of current solution. Otherwise the project file may be invalid or missing targets required for restore.	Basket.FunctionalTests	C:\Users\aheys\Source\Repos\eShopOnContainers\src\Services\Basket\Basket.FunctionalTests\Basket.FunctionalTests.csproj	1	
Error	NU1105	Unable to find project information for 'C:\Users\aheys\Source\Repos\eShopOnContainers\src\BuildingBlocks\Devspaces.Support\Devspaces.Support.csproj'. Inside Visual Studio, this may be because the project is unloaded or not part of current solution. Otherwise the project file may be invalid or missing targets required for restore.	Basket.UnitTests	C:\Users\aheys\Source\Repos\eShopOnContainers\src\Services\Basket\Basket.UnitTests\Basket.UnitTests.csproj	1	
Error	NU1105	Unable to find project information for 'C:\Users\aheys\Source\Repos\eShopOnContainers\src\BuildingBlocks\Devspaces.Support\Devspaces.Support.csproj'. Inside Visual Studio, this may be because the project is unloaded or not part of current solution. Otherwise the project file may be invalid or missing targets required for restore.	Catalog.UnitTests	C:\Users\aheys\Source\Repos\eShopOnContainers\src\Services\Catalog\Catalog.UnitTests\Catalog.UnitTests.csproj	1	
Error	NU1105	Unable to find project information for 'C:\Users\aheys\Source\Repos\eShopOnContainers\src\BuildingBlocks\Devspaces.Support\Devspaces.Support.csproj'. Inside Visual Studio, this may be because the project is unloaded or not part of current solution. Otherwise the project file may be invalid or missing targets required for restore.	Ordering.FunctionalTests	C:\Users\aheys\Source\Repos\eShopOnContainers\src\Services\Ordering\Ordering.FunctionalTests\Ordering.FunctionalTests.csproj	1	
Error	NU1105	Unable to find project information for 'C:\Users\aheys\Source\Repos\eShopOnContainers\src\BuildingBlocks\Devspaces.Support\Devspaces.Support.csproj'. Inside Visual Studio, this may be because the project is unloaded or not part of current solution. Otherwise the project file may be invalid or missing targets required for restore.	Application.FunctionalTests	C:\Users\aheys\Source\Repos\eShopOnContainers\test\ServicesTests\Application.FunctionalTests\Application.FunctionalTests.csproj	1	
Error	NU1105	Unable to find project information for 'C:\Users\aheys\Source\Repos\eShopOnContainers\src\BuildingBlocks\Devspaces.Support\Devspaces.Support.csproj'. Inside Visual Studio, this may be because the project is unloaded or not part of current solution. Otherwise the project file may be invalid or missing targets required for restore.	WebMVC	C:\Users\aheys\Source\Repos\eShopOnContainers\src\Web\WebMVC\WebMVC.csproj	1	

If I then add the project to the solution and build the solution I get the issue mentioned in https://github.com/dotnet-architecture/eShopOnContainers/issues/1056.

Any reason why that project isn't already in the solution?

Thx

**Comment by mvelosop** [comment]
Hi @inthegarden, 

What branch ans solution gives you this error?

**Comment by pabloandrei** [comment]
Item is not associated with project solving, but the project exists.

**Comment by mvelosop** [comment]
@inthegarden, yep I just verified it's missing from the complete solution, it's just most, if not all, of the work is going to the backend, so the solution eShopOnContainers-ServicesAndWebApps.sln is updated first,

As for issue #1056, it's caused by VS extension for Docker, but it has already been "worked around" in the latest commit, so you can refresh your clone.

I'll add the project to the solution shortly.

Hope this helps.
