### ISSUE TITLE
[Question] JSON:API specification instead of REST API

### ISSUE THREAD

**Issue by DanDrix8391** [dotnet-architecture/eShopOnContainers#1064]
Hello there!
I am thinking why eShopOnContainers don't use  [JSON:API](https://jsonapi.org) Spec since it is a great design to avoid repeating all the typical mistakes and forces all responses on the same format. Also you can retrieve exactly what you need, including relationships with a single request instead of making a bundle of requests in order to get all the relationships you need.

Here is an article about the comparison the Typical REST vs JSON:API vs Graph
https://dri.es/headless-cms-rest-vs-jsonapi-vs-graphql
It is using another framework, but the idea is the same.

I don't see any CON implementing JSON:API on eShopOnContainers

I am willing to fork the repo and start doing myself, but I just need to hear your thoughts. If it is a good idea.

**Comment by DanDrix8391** [comment]
Here there is a [video](https://www.youtube.com/watch?v=3jBJOga4e2Y&t=987s) (20min) at Nordic API Summit talking about the typical problems with REST API and how it was solved just implementing the JSON:API specification.

**Comment by CESARDELATORRE** [comment]
It would be great if you want to fork and start experimenting eShopOnContainers with JSON:API spec.
We’re also planning on scenarios for gRPC, so if you provide feedback on JSON:API we could plan for the right evolution in the upcoming weeks where we’ll be also migrating to new features in .NET Core 3.0. 
Thank you! :)

**Comment by mvelosop** [comment]
Closing this issue now as it was included as a candidate in the [road map](https://github.com/dotnet-architecture/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases)
