### ISSUE TITLE
Doubt about which branch to use for study

### ISSUE THREAD

**Issue by pabloandrei** [dotnet-architecture/eShopOnContainers#1068]
In front of several existing branches, I would like to know which branch has the following characteristics: Use of ApiGateways + API + microservices + Web MVC or SPA, without mobile, with stable version!

Sincereley, Pablo

**Comment by mvelosop** [comment]
Hi @pabloandrei, 

I think you'll find what you're looking for in the dev branch, using the eShopOnContainers-ServicesAndWebApps.sln solution.

Hope this helps.

**Comment by pabloandrei** [comment]
Tks
