### ISSUE TITLE
Error docker-compose!

### ISSUE THREAD

**Issue by pabloandrei** [dotnet-architecture/eShopOnContainers#1070]
Good afternoon.

Could you help with the problem with docker?

"_Error (Line: 218, Col: 9, Idx: 5557) - (Line: 218, Col: 9, Idx: 5557): Expected 'MappingStart', got 'SequenceStart' (at Line: 218, Col: 9, Idx: 5557).
docker-compose
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	291_"

My cenario:
- VSTS Enterprise 2017 (version 15.9.12)
- Docker Desktop Version 2.0.0.3 (31259) / Engine: 18.09.2
- Branch: DEV

**Comment by eiximenis** [comment]
Hi,
To discard a problem with compose file. Can you type:

```
docker-compose config
```` 

From the root path of the repo?

If this work, the compose file is OK and the problem could be in Visual Studio itself...

**Comment by pabloandrei** [comment]
hi follow below...and now?

![image](https://user-images.githubusercontent.com/16004192/59443290-149d1c00-8dd2-11e9-9b94-c71ac24e9caa.png)

**Comment by pabloandrei** [comment]
HI,
now testing through cmd is working ...
Pablo

**Comment by eiximenis** [comment]
Hi @pabloandrei 

I was able to repro the error using VS2019. Seems **to be an issue with VS extension**.

According to compose documentation, `build/args` can be specified as a list or a object (https://docs.docker.com/compose/compose-file/#args), but the extension seems is not supporting `args` specified as a list. I switched to object syntax.

Let me know if this solves the issue for you!
