### ISSUE TITLE
Build Error while connecting to Docker 

### ISSUE THREAD

**Issue by maulinshah1015** [dotnet-architecture/eShopOnContainers#1072]
I got the error of "visual studio container tools requires docker to be running before building, debugging or running a containerized project". I have my Docker enabled with Linux Container default and run as admin as well. I have run my VS2017 as admin. Can anyone please help me?

**Comment by VinickGold** [comment]
Don't know why this happens, but are you able to run containers from dockerhub through comand line? I think this information is important.

**Comment by mvelosop** [comment]
Hi @maulinshah1015,

Can you post the output from the `docker info` command from the command line?

**Comment by mvelosop** [comment]
Closing this issue as stale, but fell free to comment, will reopen if needed.
