### ISSUE TITLE
Can't Run Fresh clone

### ISSUE THREAD

**Issue by sarthakvijayvergiya** [dotnet-architecture/eShopOnContainers#1073]
**-1 (VS2019) on dev branch in Windows 10**

Severity Code Description Project File Line Suppression State
Error (Line: 218, Col: 9, Idx: 5557) - (Line: 218, Col: 9, Idx: 5557): Expected 'MappingStart', got 'SequenceStart' (at Line: 218, Col: 9, Idx: 5557). docker-compose C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets 300

**Comment by VinickGold** [comment]
Same issue here

**Comment by mvelosop** [comment]
Hi @sarthakvijayvergiya, @VinickGold,

This seems to be a Visual Studio issue. I just created a [new issue for this](https://developercommunity.visualstudio.com/content/problem/608808/docker-compose-project-fails-to-build-when-it-incl.html) for it.

However, it's been fixed as of now by @eiximenis (on 13-JUN), so you just have to refresh your local repo with the latest dev commit.

Cheers!
