### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by lloydmonteiro** [dotnet-architecture/eShopOnContainers#1074]
On VS 2019 community version, on debug mode , clicking the Login button throws up an Internal Server 500 error.
[internalerror.docx](https://github.com/dotnet-architecture/eShopOnContainers/files/3296148/internalerror.docx)

**Comment by mvelosop** [comment]
Hi @lloydmonteiro,

This error is usually due to networking configuration problems, please check issue #295

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue as stale, but feel free to comment, will reopen if needed.
