### ISSUE TITLE
[Question] Moving to Xamarin.Forms Shell Navigation

### ISSUE THREAD

**Issue by RedasP** [dotnet-architecture/eShopOnContainers#1076]
Xamarin.Forms 4 is out and it has Shell Navigation feature that introduces URI routing and enables us to pass query parameters. This reminds me of how the current implementation uses InitializeAsync method and NavigationService to navigate around.

Do you have any plans in the future on refactoring the app to use Shell? 

Since people would likely want to try out Shell, this project could be a good reference on how the transition to Shell should happen.

**Comment by conceptdev** [comment]
Thanks for your feedback @RedasP - for now we have no plans to use Shell in this application.

We are constantly expanding the [Shell docs](https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/shell/), so that's the best place to learn more.

**Comment by nishanil** [comment]
Closing this issue.
