### ISSUE TITLE
Not able to build project

### ISSUE THREAD

**Issue by mayankgaur** [dotnet-architecture/eShopOnContainers#1083]
![image](https://user-images.githubusercontent.com/5146368/60590508-c7511080-9db9-11e9-9441-bc7f7014211a.png)

**Comment by mvelosop** [comment]
Hi @mayankgaur,

Please make you've cloned the latest **dev** branch and follow the instructions in the Wiki page: https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup.

Hope this helps.

**Comment by mvelosop** [comment]
Closing issue as stale but feel free to comment, will reopen if needed.
