### ISSUE TITLE
InvalidOperationException: sub claim is missing

### ISSUE THREAD

**Issue by mayankgaur** [dotnet-architecture/eShopOnContainers#1084]
Whenever I am trying to SignIn under file In AccountController->Login.
I am having below issue:-   

<div class="titleerror">InvalidOperationException: sub claim is missing</div>
        <p class="location">IdentityServer4.Hosting.IdentityServerAuthenticationService.AssertRequiredClaims(ClaimsPrincipal principal) in

**Comment by mvelosop** [comment]
Hi @mayankgaur,

From what application are you trying to log in?

**Comment by mayankgaur** [comment]
> Hi @mayankgaur,
> 
> From what application are you trying to log in?

I have resolved this. Issue occured just because I haven't taken latest of code.
Thanks

**Comment by mvelosop** [comment]
Glad to know you could get it working! 😊
