### ISSUE TITLE
Replace deprecated sql server by latest sql server

### ISSUE THREAD

**Issue by ganesanarun** [dotnet-architecture/eShopOnContainers#1087]
Latest **dev** sometimes crash as sql server using `microsoft/mssql-server-linux:2017-latest` container failed to start with fatal error. Besides, aforementioned image is deprecated.

When I replace that image with `mcr.microsoft.com/mssql/server:2017-latest` it works like charm.

Please do let me know if you need more details.

**Comment by mvelosop** [comment]
Hi @ganesanarun,

That's a good point indeed 👍

Actually "all" base images in Dockerfiles were changed to mcr.microsoft.com.

Perhaps, you could even create a PR to fix that in the docker-compose file! 😉

**Comment by ganesanarun** [comment]
Sure, will do.

**Comment by mvelosop** [comment]
Closing this issue now, solved with commit 5b7ca5d75c6858501128468834c284ea4fdd823f
