### ISSUE TITLE
Send & receive different messages in different queues.

### ISSUE THREAD

**Issue by mmvohra** [dotnet-architecture/eShopOnContainers#1093]
Is it possible to send & receive message to multiple queues by setting queue name  in  the application

**Comment by mvelosop** [comment]
Hi @mmvohra, yes you can, although detailing more than that is out of the scope of this repo.

However, I recommend you try some [RabbitMQ tutorials](https://www.rabbitmq.com/getstarted.html), as they're pretty good for getting the fundamentals.

If you want to get a broader architectural overview, I suggest you explore [Microsoft's Messaging Patterns doc page](https://docs.microsoft.com/azure/architecture/patterns/category/messaging). It's obviously Azure oriented, but the concepts are very well explained and are also applicable to most products in this area.

Hope this helps.

Closing the issue as not related to eShopOnContainers.
