### ISSUE TITLE
Resources on how to deploy eShopOnContainers to Azure 

### ISSUE THREAD

**Issue by PingPongSet** [dotnet-architecture/eShopOnContainers#1096]
I am new to all these Docker, and AKS. I am able to run eShopOnContainers locally, and want to learn more on Docker and AKS.

I wonder how to deploy eShopOnContainers to Azure, ideally AKS (I guess it is the best).

Currently, DockerFile and DockerCompose are used, is it possible to deploy to AKS? Again, please provide links or info.

Sorry for the request, but I CANNOT find any good info from various MS Doc sites.

**Comment by saschagottfried** [comment]
Deployment with Azure DevOps to Azure AKS is covered extensively in the [Wiki pages of this repo](https://github.com/dotnet-architecture/eShopOnContainers/wiki) linking to resources in the `build\azure-devops` folder. 

- [Azure Devops pipelines](https://github.com/dotnet-architecture/eShopOnContainers/wiki/20.-Azure-Devops-pipelines)

**Comment by mvelosop** [comment]
Closing this issue now, but feel free to comment, will reopen if needed.
