### ISSUE TITLE
Unathorized: incorrect username or password

### ISSUE THREAD

**Issue by Urgen-Dorjee** [dotnet-architecture/eShopOnContainers#1099]
I have cloned your repo and tried to run :- eShopOnContainers.ServicesAndWebApps but i have been getting following error while tried to run docker compose: -

`3>Pulling nosql.data (mongo:)...
3>Get https://registry-1.docker.io/v2/library/mongo/manifests/latest: unauthorized: incorrect username or password`

Docker Desktop is running and i have checked docker-compose-override.yml in the project file but  did not find any clue about the username and password option to either change or replace etc..  docker could not pull the image from docker hub i guess but failed due to unauthorized. How to set permission or authorization in the docker hub or else in the docker compose file. Any help is appreciated..

**Comment by Urgen-Dorjee** [comment]
I got it fixed, this is outrageous how come  docker desktop login fine with xzy@example.com, however when you pull images from docker hub it does not seem to recognize user already signed in through desktop docker. I had to sign-out from desktop docker and sign in with user id from CLI which is being shown in the docker hub but not the one which is being picked by docker desktop itself. I don't get it...

**Comment by ardalis** [comment]
They email/user if issue with docker is a known issue outside of our control but agreed it is very annoying!
