### ISSUE TITLE
 Unable to cast object of type 'System.RuntimeType' to type 'EventBus.IDynamicIntegrationEventHandler'.

### ISSUE THREAD

**Issue by mmvohra** [dotnet-architecture/eShopOnContainers#1100]
I can not able to cast the IDynamicIntegrationEventHandler to Type Class on PublishEvent Method.
 
var handler = scope.ResolveOptional(subscription.HandlerType) as IDynamicIntegrationEventHandler;
handler gets null value. 

and without scope.ResolveOptional() it throws an exception of casting.

Please help.

**Comment by mvelosop** [comment]
Hi @mmvohra, Is this happening in eShopOnContainers?

If handler is null, it's because

1. The DI container can't resolve the handler type, because it isn't registered or 
2. It's registered but it isn't an `IDynamicIntegrationEventHandler`

Hope this helps.

**Comment by mvelosop** [comment]
Closing issue as stale but feel free to comment, will reopen if needed.
