### ISSUE TITLE
.NET SDK

### ISSUE THREAD

**Issue by waqar1502** [dotnet-architecture/eShopOnContainers#1101]
NETSDK1045	The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2.	Application.FunctionalTests	C:\Program Files\dotnet\sdk\2.1.508\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets

i got this issue when i build project. Anyone can help on this . 
is there need any specific SDK use for current project

**Comment by saschagottfried** [comment]
The project was [updated for .NET Core 2.2 "wave" of technologies](https://github.com/dotnet-architecture/eShopOnContainers#updated-for-net-core-22-wave-of-technologies).
Please pay attention to important notes for [Setting eShopOnContainers in a Visual Studio 2017 / 2019 environment](https://github.com/dotnet-architecture/eShopOnContainers/wiki/02.-Setting-eShopOnContainers-in-a-Visual-Studio-2017-environment#important-note-on-visual-studio-2017-version-needed).
A default installation of Visual Studio 2019 does not install .NET Core 2.2 SDK. Please install .NET Core SDK 2.2 with Visual Studio Installer (optional package '.NET Core 2.2 ... ' ) or download the latest `.NET Core 2.2 SDK` from: https://www.microsoft.com/net/download

I recommend a basic example to verify installation requirements: [Quickstart: Docker in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/container-tools?view=vs-2019#prerequisites)

**Comment by CESARDELATORRE** [comment]
@saschagottfried Thanks! 👍 
Closing the issue. Re-open if needed.
