### ISSUE TITLE
CreateContainerConfigError Status for Kiali Pod When Using Istio

### ISSUE THREAD

**Issue by bdschaap** [dotnet-architecture/eShopOnContainers#1102]
I am trying to configure a local Kubernetes cluster with Istio.  I followed the instructions [here](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/k8s/helm/istio/doc.md#using-helm-charts-to-deploy-eshoponcontainers-to-a-local-kubernetes-in-windows-with-docker-for-windows) but when I view the pod status it shows this error.
NAME                                     READY  STATUS                      RESTARTS  AGE
...
kiali-6b6fbc7f64-fsc7m                   0/1    CreateContainerConfigError  0         3m43s
...

I am using Kubernetes v1.14.3 on Docker Desktop on a Windows Server VM running in Azure.

**Comment by bdschaap** [comment]
I ran a kubectl describe pod and found this warning.

Events:
Type     Reason  Age                     From                     Message
----     ------  ----                    ----                     -------
Warning  Failed  7m28s (x3267 over 11h)  kubelet, docker-desktop  Error: secret "kiali" not found

I then looked back at the log output when running the deploy-all-istio.ps1 script and found this.
...
Generating Kiali Credentials
Error from server (NotFound): namespaces "istio-system" not found
...

I then ran the Powershell script again and the Kiali pod was running successfully because the namespace existed the second time through.

I believe there is a problem with the script in that it tries to create the kiali secret before the namespace exists.  Here is the line of code.

kubectl -n istio-system create secret generic kiali --from-literal=username=$kialiuser --from-literal=passphrase=$kialipasswrd

**Comment by mvelosop** [comment]
Hi @bdschaap,

While doing the migration to .NET Core 3.0 Istio was tried to implement the Mesh but it wasn't possible to get ir working so Linkerd was tried and it worked, so this is the one used now.

I know it's not too much help, besides delayed, but that's what the team found.

Closing this issue now as it's not used now in eShop, but feel free to comment, will reopen if needed.
