### ISSUE TITLE
[Feature Request] SonarQube for Microservices app

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#1106]
Hello,
I just want to discuss technical debt management for Application in Microservices style.

We are using SonarQube to manage our technical debt, but find some non-trivial moments applying it to Microservices app.

What we would like to have:
1- Have a view on the entire project
2- Have a view on each Microservice and/or nuget package

To address first point- we create single Dockerfile from .net sdk image, installed Java to this intermediate container image, copy all our code from meta repository (meta repository- is a repository with all microservcies added as git submodule), installing dotnet-sonarqube cli tool inside the container, run analyses for each project and than publish results.
As a result- we have really big image, but at least we can track dept across all microservices. To update data, we need to update submodules version in meta repository. 

To address second point - we created Dockerfiles from .net sdk for each microservice, again installed Java intermediate container image, copy code of this individual microservice, installed dotnet-sonarqube cli tool inside the container, run analyses only for this microservice as for BRANCH and finally publish results as a branch. 

As a result- we can track dept for the entire project and for each microservice. But what I would like is - understand how Microsoft in their reference documentation suggested to manage technical dept for microservices style app.

**Comment by SychevIgor** [comment]
We are running sonarqube analyses inside the docker image, because we don't want to install jave on dev machines to test locally. Here is an example for Service1

![image](https://user-images.githubusercontent.com/578954/61697635-565da280-ad40-11e9-9730-eb219a8b2746.png)

**Comment by SychevIgor** [comment]
@mvelosop @nishanil @eiximenis what do you think?

**Comment by mvelosop** [comment]
Hi @SychevIgor, thanks for the request/suggestion!

I haven't got into SonarQube, but I think it could add some important value from a development process point of view, not sure if that would be valuable for this project.

Will discuss this issue with @nishanil and comment back here, will take some days though.

Cheers.

**Comment by SychevIgor** [comment]
@mvelosop  did you discussed?

**Comment by SychevIgor** [comment]
Looks like I can close request.

**Comment by mvelosop** [comment]
Hi @SychevIgor, yes it's something we discussed and, actually, I just tried a couple of weeks ago on another project and it's pretty simple.

So I'd just leave the issue open, we're going to get to it.

Hope this helps.

**Comment by erjain** [comment]
Considering this issue is stale and not active, I am closing this issue, please feel free to reopen it if needed.

**Comment by SychevIgor** [comment]
nice... close after 3 years without any actions..
