### ISSUE TITLE
How locations.api reads configuration variables related to EventBus?

### ISSUE THREAD

**Issue by maulik-modi** [dotnet-architecture/eShopOnContainers#1107]
I see that startup file of Locations and Marketing API reads following configuration values:
- EventBusUserName
- EventBusPassword
- EventBusConnection
- EventBusRetryCount

However, I could not see them being declared in appsettings.json and https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/docker-compose.prod.yml.

From, where does it read values?

**Comment by clouddna-au** [comment]
They get set by docker-compose.override but because of using configuration[""], could be from KeyVault as well when running in production and using KeyVault with a setting like: "EventBusConnection"

**Comment by mvelosop** [comment]
Closing this issue as it was answered by @clouddna-au, but feel free to comment, will reopen if needed.
