### ISSUE TITLE
Questions on deployment of eShopOnContainers via Azure Dev Spaces

### ISSUE THREAD

**Issue by PingPongSet** [dotnet-architecture/eShopOnContainers#1109]
I have questions:

**Q1**: Below is the scripts to create AKS on Azure with RBAC enabled.
```
az group create --name MyResourceGroup --location eastus
az aks create -g MyResourceGroup -n MyAKS --location eastus --node-vm-size Standard_DS2_v2 --node-count 1 --enable-rbac --enable-addons http_application_routing monitoring --generate-ssh-keys
```

My queston is that is there an extra step that I need to setup considering the note below from 
> 
> If you are using an RBAC-enabled cluster, be sure to configure a service account for Tiller. Otherwise, helm commands will fail.
> https://helm.sh/docs/using_helm/#role-based-access-control
> https://docs.microsoft.com/en-gb/azure/dev-spaces/quickstart-team-development

**Q2**:  On "Deploy to a dev space", is it correct that running `azds up ` under `src ` folder will deploy ALL projects?

**Q3**: Is it correct that before I deploy the projects, I need to setup and deploy Azure Resouces from the link below?
https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploying-Azure-resources

https://github.com/dotnet-architecture/eShopOnContainers/wiki/Azure-Dev-Spaces

**Comment by asall915** [comment]
#

**Comment by sughosneo** [comment]
Hi @PingPongSet , we have recently updated our scripts to support latest version of helm and k8s in both local and AKS deployment. Could you please try out the steps from this [wiki page](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS)) and see if it could be of any help ?

Please feel free to write back if you have any questions. 

Thanks.

**Comment by sughosneo** [comment]
Hi @PingPongSet , just checking if you had a chance to try out the latest steps.

**Comment by sughosneo** [comment]
Hi @PingPongSet , I am closing this issue as of now. If you have any further questions please feel free to reopen it. 

Thank you.
