### ISSUE TITLE
Database Migration Issue

### ISSUE THREAD

**Issue by Urgen-Dorjee** [dotnet-architecture/eShopOnContainers#1110]
Please help me to understand, how following migration files have been added into the Identity.API PROJECT. I have gone through the project as well as e-Book but did not find any info about migration. However[ Identity server](http://docs.identityserver.io/en/latest/quickstarts/7_entity_framework.html) docs say about the add migration of these two files but it has its own Dbcontext file to execute the Add-Migration command:-

Migrations\ ConfigurationDb\Config
Migrations\PersistedGrandDb\Grants 

Following code does not recognize database migrations on project startup:-

```
try
     {
          Log.Information("Configuring web host ({ApplicationContext})...", AppName);
          var host = BuildWebHost(configuration, args);

                Log.Information("Applying migrations ({ApplicationContext})...", AppName);
                host.MigrateDbContext<PersistedGrantDbContext>((_, __) => { })
                    .MigrateDbContext<ApplicationDbContext>((context, services) =>
                    {
                        var env = services.GetService<IHostingEnvironment>();
                        var logger = services.GetService<ILogger<ApplicationDbContextSeed>>();
                        var settings = services.GetService<IOptions<AppSettings>>();

                        new ApplicationDbContextSeed()
                            .SeedAsync(context, env, logger, settings)
                            .Wait();
                    })
                    .MigrateDbContext<ConfigurationDbContext>((context, services) =>
                    {
                        new ConfigurationDbContextSeed()
                            .SeedAsync(context, configuration)
                            .Wait();
                    });

                Log.Information("Starting web host ({ApplicationContext})...", AppName);
                host.Run();
```
Add-Migration command does not run as per the Identity Server docs, since project does have configurationdbcontext and persistentdbcontext files to execute the migration. Adding these files getting an ambiguous error.

Thanks!

**Comment by mvelosop** [comment]
Hi @Urgen-Dorjee, this seems to be related to this issue https://github.com/dotnet-architecture/eShopOnContainers/issues/1080, could you take a look?

Hope this helps.

**Comment by Urgen-Dorjee** [comment]
Sorry for bothering you,  but I already gone through the thread #1080 before being opened this issue #1110.  I have gotten the idea of having those two folders in the project now, however I have been waiting for your anticipation into my reference thread to know why these two folders have been copied/pasted. I have upgraded Identity Server nuget package to latest and imported these two folders from the their Github page. The problem is if we make some changes in the schema of the table somehow down the line, then add-migration command would not work, since these two context files are not present in the project or any breaking changes in the nuget package in future would break the project. I mean shouldn't we introduce context files itself into the project then the current implementation approach. BTW I have resolved the issue but still if you can give some insight and also I would request you to update your eBook about the migration implementation in the Identity.API as I browsed all through the pages and did not find any information about it and then this thread #1080 stated the same problem but there was no information provided. 

Thanks!

**Comment by mvelosop** [comment]
Hi @Urgen-Dorjee,

I commented on issue #1080, that, currently, the only option to alter the Identity schema is by using  an `IDesignTimeDbContextFactory`, because of some changes made to improve program logging during startup.

If you're using Identity in your project and want to alter the Identity schema, I suggest you explore the [Using EntityFramework Core for configuration and operational data](http://docs.identityserver.io/en/latest/quickstarts/7_entity_framework.html) tutorial, that (I think) covers your scenario.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now, but feel free to comment, will reopen if needed.
