### ISSUE TITLE
Growing Size of Constructors in Aggregates

### ISSUE THREAD

**Issue by rahulrai-in** [dotnet-architecture/eShopOnContainers#1112]
Since aggregates and entities such as OrderAggregate/Order have properties with private setters (which is recommended), the size of its constructor keeps growing with additions of more properties. We have modelled aggregates and entities on this design scheme and have ended up with some entities that have 40 to 50 properties that need to be initialized from the constructor.

What is the guidance on solving the ever-growing constructor problem?

**Comment by ardalis** [comment]
The typical approach is to use a factory method when construction becomes difficult. You could have separate methods for the root and it’s children and have the root call the child factory methods. These could be static methods on the entities themselves. The constructors could this be simpler, allowing for unit tests and other cases to simply create instances, but real creation could use the factory methods. Alternately make the constructors private to force use of the factory methods.

**Comment by rahulrai-in** [comment]
Thanks for the reply. However, I fail to understand how are multiple factory methods going to fix the issue? In this case, I will have to create a new factory method based on which root properties and child properties i want created for an operation. There can be multiple combinations for it. Moreover, for EF I will still have to keep a constructor that can initialize all the properties if I don't want to make the setters of properties public.

Outlook for Android

________________________________

**Comment by ardalis** [comment]
Can you share some sample code?

You only need constructor (or factory) arguments for properties that must be set as part of new entity creation. Anything they can be null or defaulted at creation doesn’t need to be included. You should have methods on the entities for altering the state of the entity. You’re free to use these post-creation. Yes, you do need a (private if you like) default constructor for EF to use.

The scenario you’re describing in which you have different combinations of properties you might set indicates that not all of the properties are required. In that case, the optional ones shouldn’t be on the constructor. Only things that are required for the object to even exist should be required during construction.

**Comment by rahulrai-in** [comment]
Actually having a massive constructor in my class for EF is my problem. I have a default constructor that I use just for initlizing lists etc. I can't figure out a way to get rid of this constructor and without it I can't run my tests properly because I can't instantiate my entity class.

**Comment by ardalis** [comment]
Can you show some code to demonstrate the problem?

**Comment by rahulrai-in** [comment]
Here is one of the aggregates in my scenario. 

`
public class Drop : Activity
    {
        public Drop(int id, string orderId, string storeId, Customer customer, DropAddress address, bool isCollectionLocker,
                    string deliveryInstructions, DateTime deliveryWindowStartTime, DateTime deliveryWindowEndTime,
                     .... <around 40 properties>)
            : base(id, ActivityEntityType.Drop, routeId,... etc)
        {
            OrderId = orderId;
            StoreId = storeId;
            Customer = customer;
            Address = address;
            IsCollectionLocker = isCollectionLocker;
           
        }

        // ReSharper disable once UnusedMember.Local
        private Drop()
        {
        }

        public string OrderId { get; private set; }

        public string StoreId { get; private set; }

        public Customer Customer { get; private set; }
... properties that get initialized from constructor
`

The size of the Drop Aggregate increases with the properties that I add to this class. I have used value objects, and entities where appropriate but still there are properties that need to exist at the aggregate level. This looks quite odd in code where I have a 50 line constructor and also in tests where I have to initialize this class with the constructor.

**Comment by ardalis** [comment]
Ok, but what is compelling you to try to initialize literally every property of these entities in their constructor? Why isn't it OK to initialize them with a bare minimum of state (if any), and then use various methods to modify their state prior to persisting the aggregate? This is only needed when you are creating new records, since creating existing records is done for you by EF. When you create a new record, it's not unusual for it to require more than a single line of code (e.g. a constructor call). In fact, this offers benefits since there might be a problem somewhere along the way while you configure the instance, and knowing the specific line/operation that fails is much more helpful when it's not a single line 50-argument constructor call.

I'm obviously not an expert in your domain, but given what you've shared I could imagine creating a drop like so:

```
var myDrop = new Drop(orderId, storeId, customer);
myDrop.AddAddress(dropAddress);
myDrop.AddDeliveryWindow(startTime, endTime);
// etc. Flags like isCollectionLocker should just use their default and then only call a method to change the default. In this case the flag might belong on the DropAddress type.
dropRepository.Create(myDrop);
```
Is there a reason why this approach doesn't work for you?

**Comment by rahulrai-in** [comment]
Hi @ardalis, Thanks for going through this thread patiently. I completely understand the use of methods to initialize properties and I do have many methods in the entities that apply business logic before initializing the properties. However, since I anyways need to use this constructor for EF, I just reuse it to create new instance of the class as well.

I have tests written to validate the constructor so there shouldn't be many issues regarding wrongly initializing the constructor.

**Comment by ardalis** [comment]
EF doesn’t typically use anything but the parameterless constructor so I’m not sure what you mean by that.

**Comment by twsI** [comment]
Why not just have the bare minimum in the constructor and do the rest via [object initializers](https://docs.microsoft.com/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers), if you are concerned about the number of args?

**Comment by mvelosop** [comment]
Hi @rahulrai-in,

To just to add my two cents to this interesting conversation, and aligned to what @ardalis mentioned, I've found that having only the required properties as parameters in constructors makes it completely clear what's the minimum you need to create an instance and makes the API much easier to use.

I don't feel like saying that having all properties as constructor parameters is an anti-pattern, but it's probably pretty close. In fact you are already feeling the pain about this, right?

Hope this helps.

**Comment by rahulrai-in** [comment]
> EF doesn’t typically use anything but the parameterless constructor so I’m not sure what you mean by that.

Hi @ardalis and @mvelosop, According to this documentation: https://docs.microsoft.com/en-us/ef/core/modeling/constructors EF requires properties to either have public setters or be set by constructors. This leaves me with no other options except either exposing properties with public setters and accept the risk of letting methods set their values outside the aggregate or go through this ritual of adding a property and a constructor argument for each property.

Thanks for providing feedback on this.

**Comment by mvelosop** [comment]
@rahulrai-in, properties with private setters will also be populated by EF, as per [EF conventions](https://docs.microsoft.com/ef/core/modeling/included-properties#conventions).

Also, from the article you mentioned:

> Not all properties need to have constructor parameters. For example, the Post.Content property is not set by any constructor parameter, so EF Core will set it after calling the constructor in the normal way.

Constructor parameters allows you to have read-only ({get;}) properties and still have them populated through the constructor. Those would not be populated by default by EF (unless they have [backing fields](https://docs.microsoft.com/ef/core/modeling/backing-field))

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now, but feel free to comment, will reopen if needed.
