### ISSUE TITLE
Have issue implementing ocelot gateway

### ISSUE THREAD

**Issue by saitejaprattipati** [dotnet-architecture/eShopOnContainers#1114]
I have only one simple gateway without any authentication but reroute is not working. Please find my code below.

My configuration file:
{
"ReRoutes": [
{
"DownstreamPathTemplate": "/api/{everything}",
"DownstreamScheme": "http",
"DownstreamHostAndPorts": [
{
"Host": "authoradmin.command.api",
"Port": 80
}
],
"UpstreamPathTemplate": "/api/ad/{everything}",
"UpstreamHttpMethod": [ "POST", "PUT", "GET" ]
}
],
"GlobalConfiguration": {
"RequestIdKey": null,
"AdministrationPath": null
}
}

my Docker file is follows:

	authoradmin.command.api:
			image: ${DOCKER_REGISTRY-}authoradmincommandapi
			build:
  			context: .
  			dockerfile: CommandStack/AuthorAdmin.Command.API/Dockerfile
			depends_on:
  				- rabbitmq
			links: 
  				- rabbitmq
docker override is as follows:

		authoradmin.command.gateway:
			environment:
  				- ASPNETCORE_ENVIRONMENT=Development
  				- IdentityUrl=http://identity.api
			ports:
  				- "50106:80"
			volumes:
  				- ./CommandStack/AuthorAdmin.Command.API:/app/configuration

Output message when i run through postman is as follows:

 Request starting HTTP/1.1 POST http://authoradmin.command.api/api/Tags/CreateTagGroup1?command=%22sas%22  0
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 POST http://authoradmin.command.api/api/Tags/CreateTagGroup1?command=%22sas%22  0
Loaded '/usr/share/dotnet/shared/Microsoft.AspNetCore.App/2.2.5/Microsoft.AspNetCore.Http.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.AspNetCore.App/2.2.5/Microsoft.AspNetCore.WebUtilities.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 194.2303ms 307 
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 194.2303ms 307 
[40m[37mdbug[39m[22m[49m: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HLOPA3Q9VHVB:00000001, previousRequestId: no previous request id, message: setting http response message
Ocelot.Requester.Middleware.HttpRequesterMiddleware:Debug: requestId: 0HLOPA3Q9VHVB:00000001, previousRequestId: no previous request id, message: setting http response message
[40m[37mdbug[39m[22m[49m: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HLOPA3Q9VHVB:00000001, previousRequestId: no previous request id, message: no pipeline errors, setting and returning completed response
Ocelot.Responder.Middleware.ResponderMiddleware:Debug: requestId: 0HLOPA3Q9VHVB:00000001, previousRequestId: no previous request id, message: no pipeline errors, setting and returning completed response
[40m[37mdbug[39m[22m[49m: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      requestId: 0HLOPA3Q9VHVB:00000001, previousRequestId: no previous request id, message: ocelot pipeline finished

**Comment by saitejaprattipati** [comment]
@ardalis can you please help me regarding the issue.

**Comment by mvelosop** [comment]
Hi @saitejaprattipati, I'm closing this issue as not related to eShopOnContainers.

Perhaps you could get this working by going step by step with the [getting started documentation](https://ocelot.readthedocs.io/en/latest/introduction/gettingstarted.html).

Hope this helps.
