### ISSUE TITLE
Dynamic Domain excepiton message

### ISSUE THREAD

**Issue by gokhanfeali** [dotnet-architecture/eShopOnContainers#1117]
Hi All,

I have a question about ddd exception managment, I can see domain exception in offer service  and exception message is static, i want to add dynamic message for the exceptions, for example i want to get a message from redis for the exceptions how can i do this case in domain, can you share examples

Thank you

**Comment by mvelosop** [comment]
Hi @gokhanfeali,

There's nothing like that in eShopOnContainers.

I would actually say it seems a bit odd, as that looks more like validation errors that exceptions.

You might want to take a look at Microsoft's [Design Guidelines for Exceptions](https://docs.microsoft.com/dotnet/standard/design-guidelines/exceptions) for some nice guidance and recommendations about exceptions.

Closing this issue now as not related to eShopOnContainers.
