### ISSUE TITLE
Is it possible to install this application on Centos boxes?

### ISSUE THREAD

**Issue by jhahn1234** [dotnet-architecture/eShopOnContainers#1125]
Sorry for the newbie question. I successfully installed it in AKS, local Windows 10 machine, but was wondering if this app can be installed on Centos.

**Comment by mvelosop** [comment]
Hi @jhahn1234, 

I haven't heard of it running on Centos, but I have about Ubuntu, so it'd be great if you tried and told us back here 😉

Cheers!

**Comment by jhahn1234** [comment]
@mvelosop we got it deployed on Centos but there's issues with the cluster communicating with each other. Did you have to change anything on your end (e.g. Ingress) to get it working? Any gotchas when you ran it on Ubuntu? Any guidance would be greatly appreciated.

**Comment by mvelosop** [comment]
Hi @jhahn1234, I'm sorry for the delay 😔

I've personally just tried on Linux containers on Windows.

@eiximenis, any comments here?

**Comment by eiximenis** [comment]
It should be possible to install in Centos.
Things to check:

1. Ensure ingress controller is succesfully installed for your k8s
2. Ensure ingress class is OK (i. e. not `addon-http-application-routing` as this is AKS-only)

Which kind of problems do you have?

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
