### ISSUE TITLE
VueJS UI Version

### ISSUE THREAD

**Issue by hmuhdkamran** [dotnet-architecture/eShopOnContainers#1127]
Is it possible to develop VueJS UI

**Comment by mvelosop** [comment]
Hi @hmuhdkamran,

There are no plans to create a Vue client app at this point.

However there are plans to explore the [micro frontends](https://micro-frontends.org/) architectural style.

Personally, I'd like to explore Vue, and it looks quite easy to develop with, so I'll raise my hand to use it for micro frontends.

cc/ @nishanil

**Comment by hmuhdkamran** [comment]
Dear @mvelosop 

Hopefully that day come soon, I will be happy to contribute my self, [Toucan](https://github.com/mrellipse/toucan) is a great example of SOLID principal, it will help allot.

**Comment by mvelosop** [comment]
Good to know @hmuhdkamran!

Thanks 😊

**Comment by mvelosop** [comment]
Closing this issue now, but feel free to comment, will reopen if needed.
