### ISSUE TITLE
Not able to run project as per given commands using Docker

### ISSUE THREAD

**Issue by barcaraj** [dotnet-architecture/eShopOnContainers#1129]
![eshop](https://user-images.githubusercontent.com/46711676/63687318-e00dfd80-c821-11e9-9054-2a9851406451.JPG)
I am attaching the image for your reference please try to resolve my issue.

**Comment by mvelosop** [comment]
Hi @barcaraj, are you using the latest **dev** commit?

Let's see the logs for one of the failing services, let's get the marketing GW logs:

1. Identity the container:

   ```powershell
   docker ps --format "{{ .ID }}\t{{ .Names }}"
   ```

2. Find the complete name of the service, `eshoponcontainers_webmarketingapigw_1` in my case.

3. Save the logs to a file:

   ```powershell
   docker container logs eshoponcontainers_webmarketingapigw_1 > webmarketingapigw.log
   ```

4. Check the log file. You may get some clues there. Attach the log file here if you don't.

Hope this helps.

**Comment by barcaraj** [comment]
Yes @mvelosop, I am using the latest commit.
I am not getting any clue from log file. I am attaching the log file here please help me with the solution. 

[LogFile.zip](https://github.com/dotnet-architecture/eShopOnContainers/files/3558582/LogFile.zip)

Thank you.

**Comment by eiximenis** [comment]
Hard to say. Which command you run to start the containers?

**Comment by barcaraj** [comment]
Hello @eiximenis 
I used the commands provided in this link: https://github.com/dotnetarchitecture/eShopOnContainers/wiki/Windows-setup.

I also setup my system as per system requirements.

**Comment by mvelosop** [comment]
Hi @barcaraj, I'm sorry this has been open for so long!

It looks like there's a problem, at least, with the marketing service.

So we'll have to check the log for the marketing service.

Could you please repeat the process above to get the logs for the marketing service?

In my case it's named `eshoponcontainers_marketing.api_1`

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
