### ISSUE TITLE
Support "multiple redirect urls" in eShopOnContainers SPA for the STS container based on Identity Server 4

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#113]
Related to issue https://github.com/dotnet/eShopOnContainers/issues/112

Currently, eShopOnContainer's SPA app (not the IdentityServer container) does NOT support running the STS redirection from two different origins, like an external IP/DNS and localhost, depending on what you set at the browser's URL. It supports just one, either localhost or the external IP.

It would be good to support that, however, this is not a high priority improvement.

**Comment by mvelosop** [comment]
Closed as it was included in the [Roadmap (vNext)](https://github.com/dotnet-architecture/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases#vnext).
