### ISSUE TITLE
Xamarin Forms: How can I create a compare password validation rule?

### ISSUE THREAD

**Issue by kumarvikram** [dotnet-architecture/eShopOnContainers#1138]
Thanks for this great repository. It has really helped me simplifying my Xamarin Forms app and making it more extensible.

I was able to achieve all validations where validation rules are applied to single form element. How can I create compare password validation rule where two form elements/two values are involved with the validation rule mentioned in this repo?

**Comment by CmdrBeavis** [comment]
Just came looking for the same answer!

**Comment by FM1973** [comment]
Hey there.
I solved it this way:

I created the following rule:

```
public class CompareRule<T> : IValidationRule<T>
    {
        public string ValidationMessage { get; set; }
        public Func<T> CompareFunction { get; set; }

        public bool Check(T value)
        {
            if(CompareFunction == null)
                throw new ArgumentException();

            var compareValue = CompareFunction();

            if (value == null && compareValue == null)
                return true;

            if (value != null && compareValue == null)
                return false;

            if (value == null && compareValue != null)
                return false;

            return EqualityComparer<T>.Default.Equals(value, compareValue);
        }
    }
```
Then I create the rule like this:
```
_test.Validations.Add(new CompareRule<string>() { CompareFunction = () => _test2.Value, ValidationMessage = "Must match" });
```
I´m using a function so I can evaluate the value of "_test2" at runtime.

All the best, 
Florian

**Comment by kumarvikram** [comment]
Thanks a lot @FM1973. It worked like a charm.
