### ISSUE TITLE
MVC LOGIN REDIRECT

### ISSUE THREAD

**Issue by FrankDupree** [dotnet-architecture/eShopOnContainers#1139]
Hi @raimundoteixeira,

I ran curl from my computer's command prompt, not from the container's.

BTW, that's the way it should be, because that's a "redirect" address. That means it's not really a callback from identity.api to the webmvc microservice.

Let's go through the login process as seen with Fiddler (and use this to document the process later in the wiki 😉):

1. User tries to login into webmvc, but they are not autorized, so it's redirected to check authorization with identity.api:

![image](https://user-images.githubusercontent.com/7357806/58539434-449fc900-81ef-11e9-8762-8a3d89af1b95.png)

2. But they're not authorized either (not even uthenticated), so they are redirected, once again, to the login page:

![image](https://user-images.githubusercontent.com/7357806/58539635-ab24e700-81ef-11e9-9bd7-6b7ae9aa6db8.png)

3. So they are shown the login page:

![image](https://user-images.githubusercontent.com/7357806/58539756-ea533800-81ef-11e9-93f2-5daa3ae25c30.png)

4. When the user logs in, they are redirected to the /connect/authorize/callback (in identity.api):

![image](https://user-images.githubusercontent.com/7357806/58540049-88df9900-81f0-11e9-8d30-bfc11ae7a788.png)

5. The user is shown an intermediate login page (that you never get to see, unless you don't have JS enabled) that posts the necessary data as hidden inputs to http://localhost:5100/signin-oidc (**but this is done from the browser, not from identity.api**):

![image](https://user-images.githubusercontent.com/7357806/58540629-a95c2300-81f1-11e9-9b24-df2175d54c27.png)

You'd see this if JS were disabled:

![image](https://user-images.githubusercontent.com/7357806/58540703-d3154a00-81f1-11e9-9a0c-9d21e6e95dc1.png)

6. So after posting the login data, the user finally gets redirected directed, one again, to http://localhost/Account/SignIn (this is the MVC app):

![image](https://user-images.githubusercontent.com/7357806/58540954-5636a000-81f2-11e9-95a3-69c3bb9bb8f2.png)

7. Where they are redirected, finally, to the MVC home page:

![image](https://user-images.githubusercontent.com/7357806/58541059-9007a680-81f2-11e9-93e7-c705569ddebe.png)

So it's a pretty complex flow, but, as you can see, the sign in is done from the browser, in steps 5-6.

Just to be 100% sure, I added a SerilogLoggingMiddleware to the request pipeline, and the events correlate perfectly with the above:

![image](https://user-images.githubusercontent.com/7357806/58545950-42903700-81fc-11e9-9b26-985043745a20.png)

Hope this helps.

_Originally posted by @mvelosop in https://github.com/dotnet-architecture/eShopOnContainers/issues/1050#issuecomment-496872679_

**Comment by FrankDupree** [comment]
@mvelosop Thanks for the detailed fiddler workflow, its making more sense now. But i seem to have hit a snag, on visual studio with debugging turned on, I set a break point on the Account/Signin controller, for some strange reasons its not being hit. a look at the ClientRedirectUris table shows the entry is correct. any help please?

**Comment by FrankDupree** [comment]
I'm trying to access the token thats stored in the ViewData, if the endpoint doesn't get hit, i cant access it. Or is there another means of accessing it?
```
[Authorize]
        public async Task<IActionResult> SignIn(string returnUrl)
        {
            var user = User as ClaimsPrincipal;

            var token = await HttpContext.GetTokenAsync("access_token");
            _logger.LogInformation("----- User {@User} authenticated into {AppName}", user, Program.AppName);

            if (token != null)
            {
                ViewData["access_token"] = token;
            }

            // "Catalog" because UrlHelper doesn't support nameof() for controllers
            // https://github.com/aspnet/Mvc/issues/5853
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
```

**Comment by mvelosop** [comment]
Hi @FrankDupree,

That controller is probably from an old version, because currently the authentication is handled by the oidc handler in the request pipeline, so it never gets to reach the controller.

However, taking a look at the [Using the access token section in the IdentityServer documentation](http://docs.identityserver.io/en/aspnetcore2/quickstarts/5_hybrid_and_api_access.html#using-the-access-token) might help you.

I also pushed a the [explore/identity-server-login-flow](https://github.com/dotnet-architecture/eShopOnContainers/tree/explore/identity-server-login-flow) branch I used while exploring for issue #1050, so you can explore commit bcf7b7271010d2d9a1e91523c13eeb662766eba2 with the changes to peek into the request pipeline with logging.

Hope this helps.

**Comment by FrankDupree** [comment]
Hi @mvelosop 

Thank you for the quick response. Will check it out. I also noticed there is no **ordering.signalr** mapping in **ocelot**. any reasons why?

**Comment by mvelosop** [comment]
Great, let me know how it goes.

About SignalR, I've merely scratch the surface but, could this be what you're looking for?:
https://github.com/dotnet-architecture/eShopOnContainers/blob/86f7d536839ac80aa53d529f9e2520142b1287cf/src/ApiGateways/Web.Bff.Shopping/apigw/configuration.json#L76-L85

Hope this helps.

**Comment by FrankDupree** [comment]
@mvelosop Thanks for the link, i was able to get signalr up, but i keep getting a 401 unauthorized. Placing the authorize attribute on a controller works just fine as ocelot validates the request, but the same authorize attribute on  the signalr hub class throws 401.

I was able to get a stable connection after tweaking the following method in startup.cs:
```
private void ConfigureAuthService(IServiceCollection services)
        {
            // prevent from mapping "sub" claim to nameidentifier.
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Remove("sub");

            var identityUrl = Configuration.GetValue<string>("IdentityUrl");

            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;

            }).AddJwtBearer(options =>
            {
                options.Authority = identityUrl;
                options.RequireHttpsMetadata = false;
                options.Audience = "chats";

                options.Events = new JwtBearerEvents
                {
                    OnMessageReceived = context =>
                    {
                        var accessToken = context.Request.Query["access_token"];
                        // If the request is for our hub...
                        var path = context.HttpContext.Request.Path;
                        if (!string.IsNullOrEmpty(accessToken) &&
                            (path.StartsWithSegments("/hub")))
                        {
                            // Read the token out of the query string
                            context.Token = accessToken;
                        }
                        return Task.CompletedTask;
                    }
                };
            });
        }
```
How does the eshopOnContainer Ordering.SignalrHub service work around this?

**Comment by mvelosop** [comment]
Hi @FrankDupree, I'm a bit confused, is this happening in eShopOnContainers?

**Comment by FrankDupree** [comment]
@mvelosop i'm sorry, will be closing this issue now. figured it out. I'm actually running the project from visual studio.

**Comment by mvelosop** [comment]
Great @FrankDupree, it'd be nice if you could share some of your findings for the community 😉

**Comment by FrankDupree** [comment]
@mvelosop you know how these things are. could be specific problems related to different environments. but i did complain about my signalr client and i noticed something quite strange.

ocelot maps the "order-signalr" route well, but the connection always fails because the javascript signalr client decides to use "ws:localhost:xxxx" and ocelot isn't configured to listen to a web socket connection.  again, i am running the application outside docker but directly from visual studio.

I'm actively scanning through the issues and will be happy to share insights if i can. Nice work on the eshop project. learning alot.

**Comment by mvelosop** [comment]
Thanks for the insight @FrankDupree!

Anyway, it might be interesting for you to know that eShop is migrating to Envoy in the upcoming .NET Core 3 migration.

Cheers.
