### ISSUE TITLE
docker Up errors our

### ISSUE THREAD

**Issue by tramper15** [dotnet-architecture/eShopOnContainers#1141]
docker-compose up
WARNING: The INSTRUMENTATION_KEY variable is not set. Defaulting to a blank string.
WARNING: The ORCHESTRATOR_TYPE variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_SERVICE_BUS_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_SERVICE_BUS_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_CATALOG_KEY variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZUREFUNC_CAMPAIGN_DETAILS_URI variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_MARKETING_NAME variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_MARKETING_KEY variable is not set. Defaulting to a blank string.
Starting eshoponcontainers_nosql.data_1  ... error
Starting eshoponcontainers_webstatus_1  ...
Starting eshoponcontainers_webspa_1     ...
Starting eshoponcontainers_seq_1        ...
Starting eshoponcontainers_basket.data_1 ...
Starting eshoponcontainers_webspa_1      ... error
Starting eshoponcontainers_rabbitmq_1    ...

ERROR: for eshoponcontainers_nosql.data_1  Cannot start service nosql.data: driver failed programming external connectivity on endpoint eshoponcontainers_nosql.data_1 (626766dbee20dd771744f5be3f704dcc1e98edc74c454fd03d8b749e32f709a5): Bind for 0.0.0.0:27017 failed: port is already allocated
Starting eshoponcontainers_basket.data_1 ... error
ERROR: for eshoponcontainers_webspa_1  Cannot start service webspa: driver failed programming external connectivity on endpoint eshoponcontainers_webspa_1 (5038a01fa0596e42ca3da1aecf46dadd0afb5538f28df7aef83725b592f9d111): Bind for 0.0.0.0:5104 failed: port is already allocated

Starting eshoponcontainers_sql.data_1    ... error
Starting eshoponcontainers_seq_1         ... error
Starting eshoponcontainers_webstatus_1   ... error
ERROR: for eshoponcontainers_sql.data_1  Cannot start service sql.data: driver failed programming external connectivity on endpoint eshoponcontainers_sql.data_1 (3ca85b324208856ce956b969149a589c04d95b7076000b54c85757c45a4f5c66): Bind for 0.0.0.0:5433 failed: port is already allocated

ERROR: for eshoponcontainers_seq_1  Cannot start service seq: driver failed programming external connectivity on endpoint eshoponcontainers_seq_1 (e71608b85456ba6e030b69fb7de804268652db1ae5d937828833d1257aa7f459): Bind for 0.0.0.0:5340 failed: port is already allocated

ERROR: for eshoponcontainers_webstatus_1  Cannot start service webstatus: driver failed programming external connectivity on endpoint eshoponcontainers_webstatus_1 (ee1bd78974fc0ae7419Starting eshoponcontainers_rabbitmq_1    ... error

ERROR: for eshoponcontainers_rabbitmq_1  Cannot start service rabbitmq: driver failed programming external connectivity on endpoint eshoponcontainers_rabbitmq_1 (aa0cd7abd5213bf0c05ce1404c0c6c39c67a9ff7abfbb1c9dce73a74710ce315): Bind for 0.0.0.0:15672 failed: port is already allocated

ERROR: for nosql.data  Cannot start service nosql.data: driver failed programming external connectivity on endpoint eshoponcontainers_nosql.data_1 (626766dbee20dd771744f5be3f704dcc1e98edc74c454fd03d8b749e32f709a5): Bind for 0.0.0.0:27017 failed: port is already allocated

ERROR: for webspa  Cannot start service webspa: driver failed programming external connectivity on endpoint eshoponcontainers_webspa_1 (5038a01fa0596e42ca3da1aecf46dadd0afb5538f28df7aef83725b592f9d111): Bind for 0.0.0.0:5104 failed: port is already allocated

ERROR: for basket.data  Cannot start service basket.data: driver failed programming external connectivity on endpoint eshoponcontainers_basket.data_1 (f7f755e30399e36a6be8892d49646c8a76a447abf070ad00ed2cf6026f544e22): Bind for 0.0.0.0:6379 failed: port is already allocated

ERROR: for sql.data  Cannot start service sql.data: driver failed programming external connectivity on endpoint eshoponcontainers_sql.data_1 (3ca85b324208856ce956b969149a589c04d95b7076000b54c85757c45a4f5c66): Bind for 0.0.0.0:5433 failed: port is already allocated

**Comment by mvelosop** [comment]
Hi @tramper15,

I suggest that you check with [TCPView](https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview) which program is using those ports, so you can close them before starting up eShop.

I've even had port conflicts with Chrome! and have even had to reboot and start eShop before any other program, once Docker starts.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now, but feel free to comment, will reopen if needed.
