### ISSUE TITLE
Question - Deploying eShopOnContainers.Droid on Ubuntu

### ISSUE THREAD

**Issue by pabloandrei** [dotnet-architecture/eShopOnContainers#1143]
Hello.
I would like a tip on the subject.
What is the best Android emulator for Ubunt and what is the deployment process using the terminal for this project in question?
Regards,

**Comment by mvelosop** [comment]
Hi @pabloandrei, I'm not sure this is the best place to ask for this, there isn't really much Android development going on here.

Will leave the issue open a little longer, just in case someone can comment about this.

**Comment by pabloandrei** [comment]
Hello @mvelosop !
One question regarding the eShop solution, more out of curiosity.
Since the Linux with Visual Studio Code environment is not as integrated as VSTS on Windows, what would be the best practice for this scenario?

**Comment by pabloandrei** [comment]
Hi @mvelosop,
I see the project (eShop) as an example of integrating new technologies.

I'm using VS Code on other projects, and the eShop Android project got my attention. So from the question, what are the best practices for deploying this solution on an android simulator on Ubuntu.

Sincerely,

**Comment by sughosneo** [comment]
Hi @pabloandrei , thanks for reaching out. As @mvelosop mentioned in his earlier comment we might not able to recommend much on the android development as this not the right forum. 

But if you want to customize the implementation of eshopOnContainers on any way, please feel free to implement and send us a PR. We will be happy to take a look and merge in the changes 

As of now, I am closing this issue but if you still have any pending questions. Please feel free to reopen it.
