### ISSUE TITLE
[Question] How to do Unit Testing like in mobile app

### ISSUE THREAD

**Issue by francipvb** [dotnet-architecture/eShopOnContainers#1145]
Hello,

I'm trying to setup a mobile unit test library with XUnit like the ones in the mobile app, but I only got errors when trying to run from Visual Studio.

What I'm doing wrong?

Thanks,

**Comment by mvelosop** [comment]
Hi @francipvb, this is probably not the best repo to ask for this kind of guidance.

Will leave the issue open a little longer in case someone can comment on this, but, for sure, you'd need to add some more detail to get a useful comment.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now, but feel free to comment, will reopen if needed.
