### ISSUE TITLE
Move WebMVC or WebSPA to App Service

### ISSUE THREAD

**Issue by amhsalama** [dotnet-architecture/eShopOnContainers#1146]
I have EshopOnContainers running on AKS. I also managed to use Azure Sql Server for the application. Now, I am trying to utilize App Services for the front end applications, either WebMVC or WebSPA. 

WebSPA publishes to Azure from VS 2019, however a 404 error shows up with the following details in logstream.

_<div class="content-container"> 
<h3>HTTP Error 404.0 - Not Found</h3> 
<h4>The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.</h4> 
</div> 
<div class="content-container"> 
<fieldset><h4>Most likely causes:</h4> 
<ul> 	<li>The directory or file specified does not exist on the Web server.</li> 	<li>The URL contains a typographical error.</li> 	<li>A custom filter or module, such as URLScan, restricts access to the file.</li> </ul> 
</fieldset> 
</div> 
<div class="content-container"> 
<fieldset><h4>Things you can try:</h4> 
<ul> 	<li>Create the content on the Web server.</li> 	<li>Review the browser URL.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code and see which module is calling SetStatus. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul> 
</fieldset> 
</div> 
 
<div class="content-container"> 
<fieldset><h4>Detailed Error Information:</h4> 
<div id="details-left"> 
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;ManagedPipelineHandler</td></tr> 
<tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr> 
<tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;System.Web.Http.WebHost.HttpControllerHandler</td></tr> 
<tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x00000000</td></tr> 
 
</table> 
</div> 
<div id="details-right"> 
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;https://~1WebSPAeShop:80/api/siteextensions/Microsoft.ApplicationInsights.AzureWebSites?api-version=2014-11-01</td></tr> 
<tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;D:\Program Files (x86)\SiteExtensions\Kudu\84.10924.4104\api\siteextensions\Microsoft.ApplicationInsights.AzureWebSites</td></tr> 
<tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
<tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
 
</table> 
<div class="clear"></div> 
</div> 
</fieldset> 
</div> 
 
<div class="content-container"> 
<fieldset><h4>More Information:</h4> 
This error means that the file or directory does not exist on the server. Create the file or directory and try the request again. 
<p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=404,0,0x00000000,14393">View more information &raquo;</a></p> 
<p>Microsoft Knowledge Base Articles:</p>_ 

**WebMVC doesn't even publish as build fails showing the below message:**

"_dotnet bundle
    Could not execute because the specified command or file was not found.
    Possible reasons for this include:
      * You misspelled a built-in dotnet command.
      * You intended to execute a .NET Core program, but dotnet-bundle does not exist.
      * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
    /Users/xxxxxxxxx/Documents/GitHub/eShopOnContainersAppService/src/Web/WebMVC/WebMVC.csproj(51,5): error MSB3073: The command "dotnet bundle" exited with code 1.
Done building target "PrepublishScript" in project "WebMVC.csproj" -- FAILED.

Done building project "WebMVC.csproj" -- FAILED._
"

I need to get either one of them published to App Service, so any help is much appreciated

**Comment by mvelosop** [comment]
Hi @amhsalama,

I just tried building and deploying to a Web App service and the build and deploy worked just fine (couldn't run because everything else is missing, but that's another story)

Please check you're building from dev, commit 86f7d536839ac80aa53d529f9e2520142b1287cf.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now, but feel free to comment, will reopen if needed.
