### ISSUE TITLE
Error Loading Application

### ISSUE THREAD

**Issue by Akinnagbe** [dotnet-architecture/eShopOnContainers#1154]
Hello,

Whenever I lunch the eshoponcontainers application in Visual Studio, I get this error:

![image](https://user-images.githubusercontent.com/8270012/67196624-15366680-f3f3-11e9-85a1-bf930d915fae.png)

Meanwhile, after clicking okay,  I still can't run the application
error:  Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error		Visual Studio Container Tools requires Docker to be running before building, debugging or running a containerized project.

For more info, please see: https://aka.ms/DockerToolsTroubleshooting	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	

Please note that Docker is already running

![image](https://user-images.githubusercontent.com/8270012/67197191-2a5fc500-f3f4-11e9-87e8-a82343b65eb1.png)

**Comment by nishanil** [comment]
That is very strange. Try resetting Docker and restart PC.

**Comment by Akinnagbe** [comment]
Hello, 
I have been able to build the solution, I had to uninstall docker, restart my PC, install Docker and restart my PC before I got it working.
How can I set the Message Broker to user Azure Service Bus?

**Comment by mvelosop** [comment]
Hi @Akinnagbe,

The wiki contains the [Using Azure resources](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Using-Azure-resources) article, that should help you get started.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
