### ISSUE TITLE
how to connect  mssql server of eshop  by sql operation studio 

### ISSUE THREAD

**Issue by bluetianx** [dotnet-architecture/eShopOnContainers#1157]
I want to connect mssql server of eshop by sql operation studio  on mac, but i can not do it
my connection as follows
![image](https://user-images.githubusercontent.com/29353661/67498302-ccf89c00-f6b1-11e9-8a23-18dedad2e11a.png)

**Comment by pabloandrei** [comment]
Hello.

Use the comma in place of the colon.

Server: IP,Port

Regards
Pablo

**Comment by bluetianx** [comment]
thank you  very much
