### ISSUE TITLE
Unused member variable _eventLogContext in OrderingIntegrationEventService.cs

### ISSUE THREAD

**Issue by jsangco** [dotnet-architecture/eShopOnContainers#1162]
Looks like the `_eventLogContext` member value is passed in the CTOR of the [OrderingIntegrationEventService.cs](https://github.com/dotnet-architecture/eShopOnContainers/blob/0e8d07dd0153cb08c6b29e1d88dd3c542a324803/src/Services/Ordering/Ordering.API/Application/IntegrationEvents/OrderingIntegrationEventService.cs), but is otherwise never used. Am I overlooking something or should this member be removed?

**Comment by mvelosop** [comment]
Hi @jsangco, thanks for the heads up!

I'm not sure if it's OK to call this a bug, but it's certainly useless now.

Would you like to submit a PR to fix this?

**Comment by mvelosop** [comment]
Just removed the unused variable, pushed within the dotnet3 migration branch.

Closing now.
