### ISSUE TITLE
Is there a Core 3.0 version of this?  

### ISSUE THREAD

**Issue by freeborn5** [dotnet-architecture/eShopOnContainers#1165]
Is there a Core 3.0 version or would you recommend upgrading the code yourself.  It seems like many moving parts that could be affected ?

**Comment by freeborn5** [comment]
I now see the 3.0 code base in Beta.  Why is the OcelotApiGw not in there.  I was under the impression this is needed to make Ocelot work

**Comment by nishanil** [comment]
Yes, we're working on the migrations to 3.0 right now. We will merge them as soon as we complete testing all scenarios. We're moving away from Ocelot and making use of Envoy Proxy to do exactly what Ocelot was doing before. The new code will also come in with Service Mesh implementation with Linkerd for production scenarios.

**Comment by freeborn5** [comment]
So How Complete is the Beta ? is it OK to take it as a starting point for our Micro service Env

**Comment by mvelosop** [comment]
Hi @freeborn5,

I just pushed a preliminary merge of the .NET Core 3.0 branch into dev ([dotnet3-migration/dev-dotnet3](https://github.com/dotnet-architecture/eShopOnContainers/tree/dotnet3-migration/dev-dotnet3)) that you can take out for a spin.

There are some details to fix, but the core changes are already in place.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
