### ISSUE TITLE
Question: How do multiple microservice integration events ensure transactional consistency?

### ISSUE THREAD

**Issue by lctk** [dotnet-architecture/eShopOnContainers#1166]
`using (var transaction = _catalogContext.Database.BeginTransaction())
        {
           _catalogContext.CatalogItems.Update(catalogItem);
           await _catalogContext.SaveChangesAsync();

           // Save to EventLog only if product price changed
           if(raiseProductPriceChangedEvent)
               await _integrationEventLogService.SaveEventAsync(priceChangedEvent);

           transaction.Commit();
        }

      // Publish the integration event through the event bus
      _eventBus.Publish(priceChangedEvent);

      integrationEventLogService.MarkEventAsPublishedAsync(
                                                priceChangedEvent);`

> The above code guarantees the atomicity of events and database changes in a microservice. If the event fails to submit to the second microservice, the database of the first microservice has changed. How should this problem be solved?

>

**Comment by dmitribodiu** [comment]
Have a look at this question:
https://stackoverflow.com/questions/43436458/is-it-safe-to-publish-domain-event-before-persisting-the-aggregate

**Comment by mvelosop** [comment]
Hi @lctk, that's a good question!

You might want to take a look at the section on [Designing atomicity and resiliency when publishing to the event bus](https://docs.microsoft.com/dotnet/architecture/microservices/multi-container-microservice-net-applications/subscribe-events#designing-atomicity-and-resiliency-when-publishing-to-the-event-bus), from the [microservices guide](https://docs.microsoft.com/dotnet/architecture/microservices/) that goes along with this repo.

Hope this helps.

**Comment by lctk** [comment]
> Hi @lctk, that's a good question!
> 
> You might want to take a look at the section on [Designing atomicity and resiliency when publishing to the event bus](https://docs.microsoft.com/dotnet/architecture/microservices/multi-container-microservice-net-applications/subscribe-events#designing-atomicity-and-resiliency-when-publishing-to-the-event-bus), from the [microservices guide](https://docs.microsoft.com/dotnet/architecture/microservices/) that goes along with this repo.
> 
> Hope this helps.

Hello, the example on the documentation shows the atomicity of database changes and event publishing in one microservice, not the atomicity of databases in multiple microservices.

**Comment by mvelosop** [comment]
Oh, I'm sorry, I was taking eventual consistency for granted.

One of the key concepts behind a microservices architecture is the [CAP theorem](https://en.wikipedia.org/wiki/CAP_theorem). This theorem basically states that, for a distributed database system, you can pick any two of these:

- Consistency
- Availability
- Partition tolerance

A microservices architecture focuses on system escalablility and availability in general (the last two), so we have to go the route of [eventual consistency](https://en.wikipedia.org/wiki/Eventual_consistency).

The article I mentioned explains how to solve the issue you mention in an eventual consistency scenario.

If you need transaction atomicity between distributed databases, then [two phase commit](https://en.wikipedia.org/wiki/Two-phase_commit_protocol) is the way to go. However, that creates a link or dependency between the two databases and if one of them fails then the whole system fails. And that's what we try to avoid with microservices.

So the best practice regarding microservices is using eventual consistency, based on integration events delivered through messaging queues.

Hope this helps.

**Comment by mvelosop** [comment]
You might also find this article on [Challenges and solutions for distributed data management](https://docs.microsoft.com/dotnet/architecture/microservices/architect-microservice-container-applications/distributed-data-management) interesting.

**Comment by lctk** [comment]
> Oh, I'm sorry, I was taking eventual consistency for granted.
> 
> One of the key concepts behind a microservices architecture is the [CAP theorem](https://en.wikipedia.org/wiki/CAP_theorem). This theorem basically states that, for a distributed database system, you can pick any two of these:
> 
> * Consistency
> * Availability
> * Partition tolerance
> 
> A microservices architecture focuses on system escalablility and availability in general (the last two), so we have to go the route of [eventual consistency](https://en.wikipedia.org/wiki/Eventual_consistency).
> 
> The article I mentioned explains how to solve the issue you mention in an eventual consistency scenario.
> 
> If you need transaction atomicity between distributed databases, then [two phase commit](https://en.wikipedia.org/wiki/Two-phase_commit_protocol) is the way to go. However, that creates a link or dependency between the two databases and if one of them fails then the whole system fails. And that's what we try to avoid with microservices.
> 
> So the best practice regarding microservices is using eventual consistency, based on integration events delivered through messaging queues.
> 
> Hope this helps.

Hello, I understand that saga can achieve final consistency, and there are compensation transactions for failed transactions. Is this a better way?

**Comment by mvelosop** [comment]
Hi @lctk, 

Yes, a saga would be the way to go if you need to handle compensatory actions.

Hope this helps.
