### ISSUE TITLE
How commands and events are processed

### ISSUE THREAD

**Issue by vlapenkov** [dotnet-architecture/eShopOnContainers#1168]
Hi, i'm new to CQRS and event sourcing, i worked with REST. Please explain how this working in this project, for instance  create or cancel order.
Additional questions are: 
1. When Handle() of commands is triggered
2.  What is purpose of IMediator
3. Where CancelOrderCommandHandler is assigned as command to execute (don't see inject)
Thanks in advance!

**Comment by mvelosop** [comment]
Hi @vlapenkov,

That's quite an explanation! 😉

Luckily enough there's a whole (long) section dedicated to the [DDD & CQRS topic](https://docs.microsoft.com/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/) in the [Microservices architecture guide](https://docs.microsoft.com/dotnet/architecture/microservices/).

As for **MediatR**, it receives the domain events and invokes the corresponding handler, as explained in the article [Domain events: design and implementation](https://docs.microsoft.com/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation), included in the DDD & CQRS section mentioned above.

The link between a command and its handler is established in the declaration of the handler as shown here:

https://github.com/dotnet-architecture/eShopOnContainers/blob/5c143f834dd300dbc02091abc8ea397ae2ffbf0e/src/Services/Ordering/Ordering.API/Application/Commands/CancelOrderCommandHandler.cs#L12

When MediatR receives a `CancelOrderCommand`, it looks for a class that implements `IRequestHandler<CancelOrderCommand, bool>` where `bool` is the expected return type of the `CancelOrderCommand` handler, as declared here:

https://github.com/dotnet-architecture/eShopOnContainers/blob/5c143f834dd300dbc02091abc8ea397ae2ffbf0e/src/Services/Ordering/Ordering.API/Application/Commands/CancelOrderCommand.cs#L10

Finally you can also take a look at the [Serilog and Seq](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Serilog-and-Seq) article in the [wiki](https://github.com/dotnet-architecture/eShopOnContainers/wiki) to see detailed traces of the inner workings of the event handling code.

There's a bunch to read here, but it's a very interesting topic, that you'll probably enjoy!

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
