### ISSUE TITLE
ERROR: Service 'webstatus' failed to build 

### ISSUE THREAD

**Issue by dev-e-loper** [dotnet-architecture/eShopOnContainers#1169]
On the [Step 3 of the setup](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#3-build-the-application), I get the following error:

Step 47/52 : RUN dotnet publish --no-restore -c Release -o /app
 ---> Running in 37bdca8848f8
Microsoft (R) Build Engine version 16.2.32702+c4012a063 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Restore operation started...
libman.json : error LIB002: The "jquery@3.4.1" library could not be resolved by the "cdnjs" provider [/src/src/Web/WebStatus/WebStatus.csproj]
libman.json : error LIB002: The "bootstrap@4.1.3" library could not be resolved by the "unpkg" provider [/src/src/Web/WebStatus/WebStatus.csproj]

  One or more libraries failed to restore

**ERROR**: Service 'webstatus' failed to build: The command '/bin/sh -c dotnet publish --no-restore -c Release -o /app' returned a non-zero code: 1

-----

Any ideas on what I can try to make this work?

**Comment by mvelosop** [comment]
Hi @dev-e-loper,

That kind of errors are usually related to a transient failure to get the dependency from the provider (cdnjs and unpkg in this case) you shouldn't get this problem if you tried after a while.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.

**Comment by dev-e-loper** [comment]
@mvelosop Thank you for your response.  I guessed it was a transient failure as well so I tried multiple times (x5 times) at a different time of day and I get the same error, I guess the solution is to keep trying?

**Comment by dev-e-loper** [comment]
@mvelosop You are correct. I switched from my workplace connection and I was able to get the dependencies.

**Comment by mvelosop** [comment]
Glad to know you could solve this 😊

**Comment by pedy711** [comment]
I had the same issue but managed to solve it by switching to Linux Containers on Docker Desktop. I hope it helps someone.

**Comment by brSaif** [comment]
I had the  same issue recently which was blocking solution rebuild, and i was able to get around it by :
1_ right click libman.json -> Disable Client-Side Libraries on Build
2_ right click proj.csproj -> Add -> Client-Side Library -> install jquery 
then restore libman packages, just as explained in the following answer.

https://stackoverflow.com/questions/56748429/libman-error-lib002-during-build-application
hope this helps resolve the issue and save your time.
