### ISSUE TITLE
Nuget Error During Build

### ISSUE THREAD

**Issue by tonydantona** [dotnet-architecture/eShopOnContainers#1172]
Hi.

I've tried this from behind a firewall at work with proxies configured and from home with no proxies.  I am using PowerShell as admin to do this.  I get the same error:

Step 50/59 : RUN dotnet restore eShopOnContainers-ServicesAndWebApps.sln
 ---> Running in db58a64c8f68
/usr/share/dotnet/sdk/2.2.402/NuGet.targets(123,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/src/eShopOnContainers-ServicesAndWebApps.sln]
/usr/share/dotnet/sdk/2.2.402/NuGet.targets(123,5): error :   The SSL connection could not be established, see inner exception. [/src/eShopOnContainers-ServicesAndWebApps.sln]
/usr/share/dotnet/sdk/2.2.402/NuGet.targets(123,5): error :   The remote certificate is invalid according to the validation procedure. [/src/eShopOnContainers-ServicesAndWebApps.sln]
ERROR: Service 'webspa' failed to build: The command '/bin/sh -c dotnet restore eShopOnContainers-ServicesAndWebApps.sln' returned a non-zero code: 1

I've been stuck on this for two days, any help is appreciated.

**Comment by mvelosop** [comment]
Hi @tonydantona,

Hummm, the remote certificate is seen as invalid, that means there's something between you and the server that's compromising (decrypting) the SSL communication and showing you a certificate that doesn't correspond to the NuGet server.

This can happen if, for example, you have Fiddler running in your computer with the option to inspect SSL traffic.

That would be the best case scenario.

The worst case is that you are being the subject of a Man In The Middle attack. 

In-between, could be your're using a company laptop with a very high security restrictions and they inspect all traffic.

Can you try from a personal "clean" computer or something like that?

Hope this helps.

**Comment by tonydantona** [comment]
Hi @mvelosop.

Thank you for the reply.  Yes, the company firewall and restrictions are presenting a problem.
I tried building the project using VS 2019 instead of PowerShell.  Offline with no proxies I am able to build it and run it - yay.
I am almost able to build it behind the firewall as well - the only problem I'm having is loading some libraries all of a similar nature,  eg.:
The "jquery@3.4.1" library could not be resolved by the "cdnjs" provider
The "bootstrap@4.3.1" library could not be resolved by the "unpkg" provider

I feel like I'm so close.

**Comment by mvelosop** [comment]
Hi @tonydantona,

I guess it probably has to do with downloading js files from the Internet!

A workaround I can quickly think of right now is creating your own file provider behind the firewall, using something like [http-server](https://github.com/http-party/http-server) and update the [libman.json](https://github.com/aspnet/LibraryManager/wiki/libman.json-reference) file to use that provider.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
