### ISSUE TITLE
Why remove CAP link?

### ISSUE THREAD

**Issue by yang-xiaodong** [dotnet-architecture/eShopOnContainers#1178]
Hello, @mvelosop 

In the latest readme update, the CAP link has been removed. Can I know more why?

https://github.com/dotnet-architecture/eShopOnContainers/commit/a4ef680e04e97f6a287a563c87a68e2952a3e3c5#diff-04c6e90faac2675aa89e2176d2eec7d8L113

**Comment by mvelosop** [comment]
Hi @yang-xiaodong,

The whole repo has been streamlined, including the README file.

There's a new [page in the wiki with links to several asynchronous messaging](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Asynchronous-messaging) offerings, including CAP.

Hope this helps.

Closing this issue now but feel free to comment, will reopen if needed.
