### ISSUE TITLE
Dev Spaces builds no longer work due to File path changes

### ISSUE THREAD

**Issue by MrBliz** [dotnet-architecture/eShopOnContainers#1179]
Due to directory changes in [this](https://github.com/dotnet-architecture/eShopOnContainers/commit/759c061822e7ae2a9d2c63c6f0f03733e8d7fa7e) commit, the `prepare-devspaces.ps1` no longer finds the correct paths,  and when performing `azds up` the following error message  is displayed `Build context directory not found: /Users/<username>/eShopOnContainers/src/Web/WebMVC/..\..\..\`

**Comment by sughosneo** [comment]
Hi @MrBliz, sorry for the delay in reaching out. We have recently updated our scripts to work with latest versions of docker/k8s/helm. Could you please take the latest from `dev` branch and try out ?

I am closing this issue as of now, please feel free to reopen and create a new one if you face any challenges. 

Thank you.
