### ISSUE TITLE
Cannot open database marketingDB-check

### ISSUE THREAD

**Issue by damiandar** [dotnet-architecture/eShopOnContainers#1180]
Unhealthy 
Cannot open database "Microsoft.eShopOnContainers.Services.MarketingDb" requested by the login. The login failed. Login failed for user 'sa'. 

Thanks.

**Comment by mvelosop** [comment]
Hi @damiandar, 

That's probably a transient error.

Anyway, to check execute `docker ps`, you should get something like this:

![image](https://user-images.githubusercontent.com/7357806/70452602-51a34c00-1a9f-11ea-95d5-17d15cfd44ef.png)

Find the name of the sql data microservice, it should be like `src_sqldata_1` and execute:

```powershell
docker logs src_sqldata_1
```

And post the result to see what's happening.

Hope this helps.

**Comment by mundij01** [comment]
I'm having a similar error, and it didn't seem to be transient.  All of the database connection attempts were failing.  Attached is the output of the "docker logs" command.  Thank you for your help. 
[src_sqldata_1.log](https://github.com/dotnet-architecture/eShopOnContainers/files/3951096/src_sqldata_1.log)

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.

**Comment by sa3036** [comment]
I had similar issues for most of the services. Make sure the mssql server is up as suggested [above](https://github.com/dotnet-architecture/eShopOnContainers/issues/1180#issuecomment-563314666). I checked and found that databases for those services did not exist. Restarting those services <docker-compose restart service_name> fixed the issues.

**Comment by baijdzm** [comment]
See this : https://github.com/dotnet-architecture/eShopOnContainers/issues/1239
