### ISSUE TITLE
APIs / Swagger not working on some services

### ISSUE THREAD

**Issue by AdrianoAE** [dotnet-architecture/eShopOnContainers#1181]
Hello, I'm having some issues with the sample. 
![image](https://user-images.githubusercontent.com/20192335/69917467-5abc6980-145e-11ea-9a11-ec22e7638192.png)
All containers are running and working
![image](https://user-images.githubusercontent.com/20192335/69917473-6c057600-145e-11ea-8a00-84b5de43e14f.png)
But when I try to go to pages like the localhost:5102 (ordering api) I get HTTP ERROR 405. 
Other issue is with the APIs that require authentication like localhost:5103 (Basket), the page loads, I can fill the form and press login (and it clears the form). The console logs the following
![image](https://user-images.githubusercontent.com/20192335/69917546-2d23f000-145f-11ea-8997-3f4cbb4b904e.png)
Best regards, 
AdrianoAE.

**Comment by nishanil** [comment]
@eiximenis  Can you verify this?
