### ISSUE TITLE
Solution seems to be missing new projects and files.

### ISSUE THREAD

**Issue by freeborn5** [dotnet-architecture/eShopOnContainers#1183]
When I open the eShopOnContainers-ServicesAndWebApps.sln solution it seems that it points to many files and projects that have been removed.  

Is there a new SLN that is up to date ?

**Comment by mvelosop** [comment]
Hi @freeborn5,

The repo was revamped in the latest release and, as mentioned in the [release notes](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Release-notes), the folder structure was changed and simplified.

You can now find the solution in the [src folder](https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src)

Hope this helps.

**Comment by freeborn5** [comment]
OK It loads and complies.  Thanks.  - is there a way to debug the services directly - like using swagger.  

When I launch the service I get a browser http://localhost:55102 but nothing is being debugged.  Sorry for the easy question I find this architecture very complex.

**Comment by mvelosop** [comment]
If you want to debug the application with VS you have to run the eShopOnContainers from VS, using F5, just as explained in the [VS section in the wiki](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#optional---use-visual-studio).

Just realized the swagger UI is not working now, even though the endpoint for the json (<http://localhost:5102/swagger/v1/swagger.json>) is working just fine. Will work on that.

Hope this helps.

**Comment by nishanil** [comment]
Closing this as the original issue is addressed. Feel free to reopen if required.
