### ISSUE TITLE
Issues with "Deploy to Local Kubernetes" guide.

### ISSUE THREAD

**Issue by zaheershk** [dotnet-architecture/eShopOnContainers#1184]
Hi
Thanks for sharing the latest updates and guides! However, there are some areas on the "Deploy to Local Kubernetes" guide that perhaps need review/correction. 

1. In the [Helm](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes#install-helm-client) section, its perhaps best to mention v2.16.1 because Helm 3.0 is out now, and it does not need Tiller set-up. [Reference](https://github.com/helm/helm/issues/7052). So now, using the "choco" command tends to install Helm 3.0 and the subsequent instructions don't work.

2. In the [Explore](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes#explore-internal-services) section, the **deploy-nodeports.ps1** file is missing in the Dev branch. 

3. In the [Kubernetes Dashboard](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes#optional---install-kubernetes-dashboard-ui) section, the "deploy" command has an updated URL. [Reference](https://github.com/kubernetes/dashboard). The one specified does not work. Also, the following files are missing from Dev branch:
  - k8s\dashboard-adminuser.yaml
  - k8s\dashboard-bind-adminrole.yml

I'm still running through some issues getting this deployed as instructed, could be related to my machine, will share any other findings i come across...

**Comment by mvelosop** [comment]
Hi @zaheershk,  Thanks for the feedback.

Will review the Helm issue and update the other issues in short!

**Comment by mvelosop** [comment]
Closing this issue, as this was just fixed in commit b5ab54afbcd3898c5125fd857bf5fdb05012dbea
