### ISSUE TITLE
Why result of ChangeUriPlaceholder method is assigned again to items variable?

### ISSUE THREAD

**Issue by iHamzaKhanzada** [dotnet-architecture/eShopOnContainers#1185]
https://github.com/dotnet-architecture/eShopOnContainers/blob/8cc680847a4005ca41b26f537b68500f7d2738f9/src/Services/Catalog/Catalog.API/Controllers/CatalogController.cs#L93

Hello, This is my first time opening an issue on Github, I just wanted to ask if the type of `items` is a reference type which is List of CatalogItem, and its passed as a reference to ChangeUriPlaceholder, then why we are assigning the result back to that variable `items`? Is that necessary? as its not passing by value so whatever modification we do on `items` variable, it will be reflected everywhere.

**Comment by mvelosop** [comment]
Hi @iHamzaKhanzada, thsnks for the feedback.

You're right, it's not necessary. It's just a matter of API design preferences. 

I don't know what the original intention was, but there a couple of reasons I can think of right now:

1. It makes it easier to compose method calls.
2. It makes it clear that the method is returning a modified version of items.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
