### ISSUE TITLE
Run WebSPA with NG Serve

### ISSUE THREAD

**Issue by pabloandrei** [dotnet-architecture/eShopOnContainers#1186]
Hello, I would like to run the WebSPA project through NG Serve, with the goal of consuming the services in APIs and editing the WebSPA without the need for a new build to the container.

Run NG SERVER:

> ** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
>                                                                                           
> Date: 2019-12-04T18:54:03.966Z
> Hash: 8a3815049282d2f9c241
> Time: 16926ms
> chunk {main} main.js, main.js.map (main) 254 kB [initial] [rendered]
> chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 259 kB [initial] [rendered]
> chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
> chunk {styles} styles.js, styles.js.map (styles) 854 kB [initial] [rendered]
> chunk {vendor} vendor.js, vendor.js.map (vendor) 5.73 MB [initial] [rendered]
> ℹ ｢wdm｣: Compiled successfully.
> ℹ ｢wdm｣: Compiling...
> 

But the property "this.serverSettings" of file "configuration.service.ts" is null.

What would be the suggestion to go up the entire docker-compose infrastructure, and edit the SPA without rebuild?

![image](https://user-images.githubusercontent.com/16004192/70173812-6b651d80-16b2-11ea-826c-19420b4c7dad.png)

SIncreley,

**Comment by w00519772** [comment]
I had this issue.  I believe you have to do this:

1) Open DOS and change directory to: eShopOnContainers/src/Web/WebSPA 
2) Run this command: npm install
3) Run this command: npm run build:prod

**Comment by w00519772** [comment]
Are you able to use breakpoints in the typescript files? The are all ignored for me i.e. I see the message: "the breakpoint will not be hit".

**Comment by pabloandrei** [comment]
Hello @w00519772 .

I believe I was not correct in describing my problem.
In my understanding the WebSPA project has a "leg" that runs with C #. Within other points it processes the generation of configuration points as API endPoints consumption.

![image](https://user-images.githubusercontent.com/16004192/70462423-93c98f00-1a99-11ea-9146-698b5d226099.png)


![image](https://user-images.githubusercontent.com/16004192/70462259-4d743000-1a99-11ea-893b-3cbaf6284e93.png)


![image](https://user-images.githubusercontent.com/16004192/70462062-d6d73280-1a98-11ea-9cf8-7e36e4551dee.png)


![image](https://user-images.githubusercontent.com/16004192/70462160-0f770c00-1a99-11ea-8264-eb063e7ea6d4.png)

**Comment by craniodev** [comment]
For now it's working for me.
I changed the service that gets the settings

WebSPA\Client\modules\shared\services\configuration.service.ts
```
@Injectable()
export class ConfigurationService {
    serverSettings: IConfiguration;
    // observable that is fired when settings are loaded from server
    private settingsLoadedSource = new Subject();
    settingsLoaded$ = this.settingsLoadedSource.asObservable();
    isReady: boolean = false;

    constructor(private http: HttpClient, private storageService: StorageService) { }
    
    load() {

        const baseURI = document.baseURI.endsWith('/') ? document.baseURI : `${document.baseURI}/`;
        let url = `${baseURI}Home/Configuration`;

        if (!environment.production) {

            url = `http://localhost:5104/Home/Configuration`;
        }

        this.http.get(url).subscribe((response) => {
            console.log('server settings loaded');
            this.serverSettings = response as IConfiguration;
            console.log(this.serverSettings);
            this.storageService.store('identityUrl', this.serverSettings.identityUrl);
            this.storageService.store('marketingUrl', this.serverSettings.marketingUrl);
            this.storageService.store('purchaseUrl', this.serverSettings.purchaseUrl);
            this.storageService.store('signalrHubUrl', this.serverSettings.signalrHubUrl);
            this.storageService.store('activateCampaignDetailFunction', this.serverSettings.activateCampaignDetailFunction);
            this.isReady = true;
            this.settingsLoadedSource.next();
        });
    }
}
```
