### ISSUE TITLE
Breakpoints in the WebSPA project are ignored

### ISSUE THREAD

**Issue by w00519772** [dotnet-architecture/eShopOnContainers#1187]
I am trying to debug the WebSPA project, however I see the following warning when I add a breakpoint to the typescript (the breakpoints are all ignored): "The breakpoints will not currently be hit.  No symbols have been loaded for this document".  I can debug all of the other projects.

I have done my own research and I have come across this: https://stackoverflow.com/questions/50660725/error-on-typescript-instruction-breakpoints-set-but-not-yet-bound-in-vs2017.  Guerillas' answer suggests that renaming the ClientApp folder to Client can cause problems.  Should I be able to debug this project i.e. should breakpoints work? So far I have tried:

1) Debugging in Visual Studio 2017 and Visual Studio 2019.
2) Debugging on two separate PCs.
3) Disable in options the following setting: 'Enable Just My Code'.
4) Rename the Client folder to ClientApp then rebuild.
5) Rebuild i.e. clean and build.

However, the typescript breakpoints are always ignored.  The C# controller breakpoints (in the WebSPA project) are not ignored.

How can I debug the Typescript? Please note that I have created a new Angular project on my PC and I am able to debug the Typescript.

**Comment by mvelosop** [comment]
Hi @w00519772, thanks for the feedback.

Investigating on this/calling a friend, I'm not too keen on front end. 🙁

**Comment by sughosneo** [comment]
Related to https://github.com/dotnet-architecture/eShopOnContainers/issues/1740
Please refer to the steps mentioned [WebSPA project doesn't come up on debug mode in Visual Studio 2019](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Frequent-errors#webspa-project-doesnt-come-up-on-debug-mode-in-visual-studio-2019)

I am closing this issue as of now, but please feel free to reopen if you have any further questions. Thank you.
