### ISSUE TITLE
Application architecture diagrams/(e-book?)

### ISSUE THREAD

**Issue by pgromanov** [dotnet-architecture/eShopOnContainers#1190]
Is there a reference somewhere of how all of the components included hang together, how each of them is structured internally and how they communicate to each other - UML or any other sort of diagrammed/detailed description?

I have it deployed fine, it all works as far as that part goes, but it would be much easier to get into the detail by following some documentation than to figure it all out straight from code.

Many thanks!

**Comment by mvelosop** [comment]
Hi @pgromanov, thanks for the feedback.

There are some high-level architecture diagrams in the [Architecture wiki page in this repo](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Architecture). And there you'll also find links to other relevant resources.

You can also take deep a look at the [.NET Microservices: Architecture for Containerized .NET Applications](https://docs.microsoft.com/dotnet/architecture/microservices/) guide. You can read the guide on-line there, or you can download it in several e-book formats, from the guide's main page

For a broader view, you can take also a look at the [.NET Architecture Guides](https://dotnet.microsoft.com/learn/dotnet/architecture-guides) with plenty of interesting resources, including several e-books.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now, but feel free to comment, will reopen if needed.
