### ISSUE TITLE
Question: Why long polling here, why not WebSockets?

### ISSUE THREAD

**Issue by suadev** [dotnet-architecture/eShopOnContainers#1191]
https://github.com/dotnet-architecture/eShopOnContainers/blob/b5ab54afbcd3898c5125fd857bf5fdb05012dbea/src/Web/WebSPA/Client/modules/shared/services/signalr.service.ts#L46

**Comment by mvelosop** [comment]
Hi @suadev, thanks for the feedback.

That was needed back when using Ocelot, since it didn't support WebSockets.

Well, it wasn't actually needed, since SignalR would finally find the best protocol.

Removing the constraint for the next (ongoing) release.

Thanks!

**Comment by nishanil** [comment]
Thanks for the feedback. Miguel has fixed that in the code. Closing this issue.
