### ISSUE TITLE
typo https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#optional---use-visual-studio

### ISSUE THREAD

**Issue by TSoucek** [dotnet-architecture/eShopOnContainers#1192]
there is ia typo in HowTo, wrong folder
cd eShopOnContainers**\src**

**Comment by TSoucek** [comment]
Also (based on experience of 4 independent persons) 4GB RAM is not enough. Once we added more for Docker (which was restarted so it can be also side-effect) Application was successfully started.

**Comment by TSoucek** [comment]
file "add-firewall-rules-for-sts-auth-thru-docker.ps1" is not located in "cli-windows" folder but in "obsolete\cli-windows" folder.

**Comment by mvelosop** [comment]
Hi @TSoucek, thanks for the feedback.

I'll be updating the wiki today for the \src, as well as the script location, that will be become **deploy\windows**.

Regarding the required memory, I did check and it runs well with 4 GB RAM... with one caveat 😉

You have to [disable Kubernetes](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes#disable--stop-kubernetes).

When Kubernetes is enabled, eShop barely runs on docker-compose, as you mentioned.

The [Deploy to Local Kubernetes wiki page](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes#enable-kubernetes) does mention you need 6 GB to run eShop on Kubernetes, but I hadn't realized that 6 GB (perhaps 5 GB?) are needed also to run on docker-compose if K8s is enabled.

![image](https://user-images.githubusercontent.com/7357806/71009713-97d15e80-20e2-11ea-81b9-ec09d4d7a6e2.png)

Anyway, I'll also include this in the wiki!

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
