### ISSUE TITLE
[Docker][eShop] 503 error page occurs when debugging an eShop project

### ISSUE THREAD

**Issue by v-meren** [dotnet-architecture/eShopOnContainers#1194]
**OS Version:** Win10 19h2 1909
**Dev16 Build:** master-[29603.159] | Enterprise
**Workload:** Azure Development
 
**Reproduce Steps:**
1. Download the latest project on dev branch.
2. Switch Docker for windows to Linux container and configure the Docker engine to have 3 CPUs and 4096 MB memory. Make sure the drives are shared properly.
3. Make sure the executing policy is Bypass, then run the following Powershell script to set firewall rules.
.\cli-windows\add-firewall-rules-for-sts-auth-thru-docker.ps1.
4. Open eShopOnContainers-ServicesAndWebApps.sln in Visual Studio and wait for container warm up successfully.
5. F5/Ctrl +F5, check whether an error occurs or not.
 
**Expect:**
No error occurs and the web page can open successfully. 

**Actual:**
The 503 error displays in web page. 
![image](https://user-images.githubusercontent.com/54049350/82627507-219ad000-9c1d-11ea-9421-95b26e4bd564.png)

**More info:**
1. We can resolve the 503 error though refreshing the web page when the 503 error occurs.
2. The 503 error web page occurs after switching "Release" mode.
3. This issue reproduces on [16.3.9](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.3#16.3.9) build.

**Comment by mvelosop** [comment]
Hi @v-meren, thanks for the feedback.

As far as I can tell from the image, that error is related to the installation of some VSIX in Visual Studio, but that's not related to eShopOnContainers.

I'd suggest that you uninstall and reinstall the latest VS version (16.4.1 as of today).

Hope this helps.

**Comment by sughosneo** [comment]
Hi @v-meren, I am closing this item considering your issue has been resolved. But if you have any further questions, Please feel free to reopen it. 

Also, there have been few upgrades in the scripts. You may want to take a look at the latest `dev` branch.

Thanks.
