### ISSUE TITLE
Env: AKS deployment. After login Campaign's shows: "There are no results that match your search". 

### ISSUE THREAD

**Issue by jaycdave88** [dotnet-architecture/eShopOnContainers#1195]
When deploying to AKS via the deploy-all.sh script and having my images living within ACR. The campaign.api does not seem to be returning correct information - it seems that the ViewBag for campaigns might be empty... 

I tested this locally with docker-compose and it worked just fine - but when moving to AKS seems like the issue is that the resource is unable to stand its self up? If anyone has run into this in the past - how did you go about fixing it? 

Error from DOM: 

`main.4db56e4a2ac2cc3566b2.js:1 ERROR TypeError: Cannot read property 'activateCampaignDetailFunction' of undefined
    at t.ngOnInit (main.4db56e4a2ac2cc3566b2.js:1)
    at main.4db56e4a2ac2cc3566b2.js:1
    at main.4db56e4a2ac2cc3566b2.js:1
    at Ts (main.4db56e4a2ac2cc3566b2.js:1)
    at Ys (main.4db56e4a2ac2cc3566b2.js:1)
    at Object.updateDirectives (main.4db56e4a2ac2cc3566b2.js:1)
    at Object.updateDirectives (main.4db56e4a2ac2cc3566b2.js:1)
    at xs (main.4db56e4a2ac2cc3566b2.js:1)
    at Ns (main.4db56e4a2ac2cc3566b2.js:1)
    at Ms (main.4db56e4a2ac2cc3566b2.js:1)`

**Comment by sughosneo** [comment]
Hi @jaycdave88 - we have recently updated k8s related scripts for the [AKS deployment](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS)). Could you please take the latest from `dev` branch ?

I am closing this issue as of now. But if you still the face the issue please feel free to reopen it. 

Thank you.
