### ISSUE TITLE
Where Setup Guide new Release

### ISSUE THREAD

**Issue by armadeas** [dotnet-architecture/eShopOnContainers#1198]
hi i try this guide
github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup

but i think this guide now is not relevant to new version repositories

**Comment by mvelosop** [comment]
Hi @armadeas, thanks for your feedback,

It was updated to reflect the latest changes, but it has the typo pointed out in issue #1192, but other than that, it seem's to be working fine.

Did you find something else?

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
