### ISSUE TITLE
Updating to netcore3.1 

### ISSUE THREAD

**Issue by ghd258** [dotnet-architecture/eShopOnContainers#1199]
Updating to netcore3.1

**Comment by mvelosop** [comment]
Hi @ghd258, thanks for your feedback.

Working on it: [feature/3.1-upgrade](https://github.com/dotnet-architecture/eShopOnContainers/tree/feature/3.1-upgrade) 😁

Hope this helps.

**Comment by nishanil** [comment]
3.1 Code is merged. Closing this issue.
