### ISSUE TITLE
Microsoft.eShopOnContainers.Services.CatalogDb - Not Created

### ISSUE THREAD

**Issue by microsoftcode** [dotnet-architecture/eShopOnContainers#1200]
Hello,
I am able to run most of the services locally on Windows machine with Linux container but there seems some issue for Catalog service. As per my investigation, DB for the catalog is not created.
I was trying to run the update migration script but was not able to execute. 

I have attached the required screenshots for the same .

Kindly help.

Thanks in Advance 
![catalogDb_Error](https://user-images.githubusercontent.com/41111711/71087629-ac852380-21c2-11ea-8f68-b5ce9c96aecf.png)
![Health_Checks](https://user-images.githubusercontent.com/41111711/71087630-ad1dba00-21c2-11ea-91ea-fa182c1f5a94.png)
![SQL_Database](https://user-images.githubusercontent.com/41111711/71087631-ad1dba00-21c2-11ea-8e43-76d50e696720.png)

**Comment by microsoftcode** [comment]
The below command solved my issue. Thanks.
**docker restart src_catalog-api_1**

**Comment by andyle83** [comment]
That's very good fixing.
