### ISSUE TITLE
Usage of OrderApiClient | WebHttpAggregator Project

### ISSUE THREAD

**Issue by Shyam200408** [dotnet-architecture/eShopOnContainers#1202]
Hi,
I am following your project and found **OrderApiClient.cs** under Web.Shopping.HttpAggregator project. 
I tried to find out IOrderApiClient usage in whole solution, but could not find it, if any controller is using this.

I would like to understand it's usage

**Comment by mvelosop** [comment]
Hi @Shyam200408,

You're right, `IOrderApiClient` isn't being used anymore, it was replaced with `IOrderingService`. The new service achieves te same, but using gRPC.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
