### ISSUE TITLE
Error while deploying on CentOS

### ISSUE THREAD

**Issue by sa3036** [dotnet-architecture/eShopOnContainers#1204]
I was trying to deploy this application using ` sh deploy-all.sh --use-local-k8s $true` but I got the following error message:

> Error: release eshop-apigwms failed: ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects " or n, but found {, error found in #10 byte of ...|{"admin":{"access_lo|..., bigger context ...|{"apiVersion":"v1","data":{"admin":{"access_log_path":"/dev/null","address":{"socket_a|...

Did anyone face a similar problem during deployment?

**Comment by eiximenis** [comment]
Mmmm... check your `kubectl` version... It seems that your kubectl is too new/old for the cluster you are connecting to.

**Comment by Luthor36** [comment]
@sa3036 Did you ever find a solution for this issue?  I encounter this same issue when trying to deploy to AKS.

**Comment by sa3036** [comment]
@Luthor36  I did not find any solution. Did you check the pointer suggested above by @eiximenis ?  I am not using this application now but I plan to use it later. 

Do let me know if you find anything.

**Comment by Luthor36** [comment]
> @Luthor36 I did not find any solution. Did you check the pointer suggested above by @eiximenis ? I am not using this application now but I plan to use it later.
> 
> Do let me know if you find anything.

I did try both upgrading my kubectl versions (client & server) & downgrading them.  I made sure that both kubectl versions matched.  No change, I still get the same issue.

I couldn't update both to version 1.17.4 (While that is available for the client, AKS doesn't support it).  So I downgraded to v1.14.8.  I'm not sure if I need to go further.

<img width="520" alt="Screen Shot 2020-03-18 at 9 22 39 AM" src="https://user-images.githubusercontent.com/5376529/76970774-5b3c1b80-68fa-11ea-9e9e-1023e0fa04dd.png">

**Comment by noahjd** [comment]
I am having the same issue on cluster created with kops, using the install script. I have these kubectl versions...
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by sughosneo** [comment]
Hi @sa3036, we have recently updated our scripts to support latest version of helm and k8s in both local and AKS. Could you please give it a try and see if this could be of any help ?

Please find wiki references as per below : 

[Local k8s](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes)
[AKS](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS))

Thanks.

**Comment by sughosneo** [comment]
Hi @sa3036 , I am closing this issue as of now. If you have any further questions, please feel free to reopen it. 

Thank you.
