### ISSUE TITLE
Unit of work pattern approach

### ISSUE THREAD

**Issue by andreatosato** [dotnet-architecture/eShopOnContainers#1205]
Hi all, 
This Is not an issue but a simple question.
Unit of work, usually, have many repository. In order api there is unit of work insider repository. Why?
This approach isn't unit of work and repository pattern, correct?
@CESARDELATORRE

**Comment by mbobka** [comment]
Unit of work essentially is a part of storing logic of Repository. Repository relies on UoW, not the opposite. UoW is the way how Repository will store data. So, the way how repositories implemented in OrderAPI is almost perfect. =) But from my point of view, better way is not to expose UoW from Repository at all, it's should be private.

**Comment by erikpique** [comment]
Hi Andrea @Andreatosato

Adding on @mbobka's comment, the responsibility of UoW is committing all changes to the DB at once or perform a rollback if necessary. And the repository's responsibility is presenting objects to the application, hiding the persistance details (SQL, NoSQL, etc.).

UoW and repository pattern are usually used together and, in the DbContext implementation, they're pretty coupled, but actually they're independent, that is, you can have either one without the other.

Greetings
