### ISSUE TITLE
SF branch?

### ISSUE THREAD

**Issue by moldyseaswimmer** [dotnet-architecture/eShopOnContainers#1206]
There is a reference to a SF branch here:
https://github.com/dotnet-architecture/eShopOnContainers/wiki/Backlog#orchestrators

Where is the SF branch?

**Comment by Dolphinsimon** [comment]
Referring [here](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Release-notes).
SF & SF Mesh had been retired.

**Comment by nishanil** [comment]
That's right. We retired the support for SF. 
Thanks for the heads up. That backlog needs to be revamped. We will work on that. Closing this issue.
