### ISSUE TITLE
Login fails after moving WebSPA to App Services

### ISSUE THREAD

**Issue by amhsalama** [dotnet-architecture/eShopOnContainers#1209]
Hi,

I moved WebSPA to app services while keeping every other service running on Azure Kubernetes services. The first time I tried to click on login it tried to navigate to localhost:5105 for authentication and of course failed because there is no identity service running on the app service plan nodes(at least this is my understanding). 

I changed IdentityUrl in "appsettings.json" to the AKS API server address, i.e. http://AKS API Server Address:5105, but now it times out when I click on login. The message I received is below. 

_"This site can’t be reached AKS API Server Address took too long to respond."_

I am allowing all (ports, sources, protocols, destinations) inbound and outbound security rules for the NW security group in the AKS infrastructure Resource Group.   Outbound IP Addresses for the App Service itself is limited to 4 IPs though and I don't seem to be able to add other IP Addresses to this IP list. 
what could I be missing or doing wrong? TIA

**Comment by eiximenis** [comment]
Hi!
You **should not** enter the AKS API Server URL. The value of `IdentityUrl` that you should use is the value of the ingress endpoint associated to it.
You can view this value, by using `kubectl`:

```
kubectl get ing
```

Look for the `HOSTS` column of the value `eshop-identity-api`. The URL you have to use for `IdentityUrl` is:

```
http://[VALUE_OF_HOST_COLUMN]//identity
```

Hope this helps!

**Comment by amhsalama** [comment]
That was really helpful. Now that I have the WebSPA module running on an App Service. It forces me to use SSL. When I change the end points in app settings.json to start with HTTPS, I am getting some errors regarding invalid certificates and requests being blocked by CORS policy. I understand that I may need to change some settings on the Database, but I don't know where to start or if there is a guide I can use for this configuration. I appreciate any hint around SSL, endpoints, and DB configuration. TIA

**Comment by sughosneo** [comment]
Hi @amhsalama , closing this issue as of now. But feel free to comment, will reopen it if needed. Thank you.
