### ISSUE TITLE
WebSPA with ng serve not run

### ISSUE THREAD

**Issue by pabloandrei** [dotnet-architecture/eShopOnContainers#1211]
Hi, after I do pull the latest version, i have this new problem below...
The ng serve not running...

![image](https://user-images.githubusercontent.com/16004192/71910065-f8871080-314f-11ea-9b1c-4bca620891a9.png)

  I would like make changes in WebSPA projeto running in background full projeto com docker-compose, for consuming the api endpoint.

Notes:
-- OS Ubuntu 18
-- IDE VS Code

**Comment by sughosneo** [comment]
Hi @pabloandrei, thanks for reaching out.

Could you please share following information ? 

1) What's the deployment ? `docker-compose`, `local k8s` etc..
2) What's the docker version ?
3) Have you done any customization ? 
4) Are all the services up and running ?
5) What's the status of other projects ? For e.g - WebStatus

**Comment by sughosneo** [comment]
Hi @pabloandrei , I am closing this issue as of now but if you face any further challenges please feel free to reopen it.
