### ISSUE TITLE
Which the best strategy running e debug using Ubuntu with VsCode?

### ISSUE THREAD

**Issue by pabloandrei** [dotnet-architecture/eShopOnContainers#1212]
Which the best strategy running e debug using Ubuntu with VsCode?
The ideia is learning with this project, make ajusts e etc..

**Comment by sughosneo** [comment]
Hi @pabloandrei - Yes, you can debug .NET Core application with VSCode. For that you would require to attach one debugger with your VS code session. Please refer : https://code.visualstudio.com/docs/containers/debug-netcore for more details. 

Also, for learning you may want to check out the [Wiki](https://github.com/dotnet-architecture/eShopOnContainers/wiki). It has great deal of information on `eShopOnContainers`. For e.g : [architecture](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Architecture) and [code flow](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Code-Flow)

Thank you

**Comment by mvelosop** [comment]
Hi @pabloandrei, @sughosneo,

Some time ago I felt eShop was too complicated to learn debugging with VS Code, so I set up a small project to learn debugging containerized apps from VS Code: https://github.com/mvelosop/explore-docker-vscode

I haven't tried the same principles on eShop, but they **should** work.

Feedback would be appreciated 😊

**Comment by sughosneo** [comment]
Thanks @mvelosop for sharing. This could be a great reference for VS code users.

**Comment by sughosneo** [comment]
Hi @pabloandrei, I guess original question on this topic has already been answered. So closing this item as of now. If you have any question, please feel free to reopen it.

Thank you.
