### ISSUE TITLE
MacOs - Solution Login webmvc HttpRequestException don't work

### ISSUE THREAD

**Issue by FlyDogBR** [dotnet-architecture/eShopOnContainers#1213]
First of all, thank you for this awesome project and colaboration.

I followed all steps from this tutorial and have all services running helthy:
https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes

But when I try to apply solution described in **Known issues** don't work on MacOS Catalina.

I'm running in kubernetes (docker desktop). But how http://10.0.75.1/webmvc should be work? I patched ConfigMaps and restart services according tutorial.

Someone have any idea?

**Comment by erikpique** [comment]
Hi @FlyDogBR 

For identity to work on Mac with the mvc application, the identity url must be modified:

Here's a sample screenshot

![InkedScreenshot 2020-01-27 at 15 03 47_LI](https://user-images.githubusercontent.com/5609495/73181844-4623e700-4118-11ea-81da-0fe064f19b43.jpg)


Greetings.

**Comment by mvelosop** [comment]
Closing this issue now, but feel free to comment, will reopen if needed.
