### ISSUE TITLE
EventBus not resolved using ServiceProvider

### ISSUE THREAD

**Issue by harshaghanta** [dotnet-architecture/eShopOnContainers#1215]
Any specific reason why AddEventBus instance is not resolved using the ServiceProvider ?

 return new EventBusServiceBus(serviceBusPersisterConnection, logger,
                        eventBusSubcriptionsManager, subscriptionClientName, iLifetimeScope);

**Comment by erikpique** [comment]
Hi @harshaghanta

We're not using the default DI container but are using autofac instead.

Greetings

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
