### ISSUE TITLE
where are the connect services (Identity Services)?

### ISSUE THREAD

**Issue by sunil233** [dotnet-architecture/eShopOnContainers#1218]
where are the connect services (Identity Services)?

IdentityUrl/connect/authorize
IdentityUrl/connect/userinfo
IdentityUrl/connect/endsession

**Comment by pabloandrei** [comment]
Hello.
Look this documents, this framework used in this solution.

http://docs.identityserver.io/en/latest/

For exemple "connect/authorize": http://docs.identityserver.io/en/latest/endpoints/authorize.html

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
