### ISSUE TITLE
help with webspa project

### ISSUE THREAD

**Issue by nicoter1** [dotnet-architecture/eShopOnContainers#1220]
Health Checks status shows all green, but i am not able to run the webspa project

Error
This localhost page can’t be found
No webpage was found for the web address: http://localhost:5104/
HTTP ERROR 404

**Comment by ricrocha** [comment]
I am having the same problem with the webspa. I ran the npm commands (install and run prod:build) and I got some errors on the prod:build command run. Thank you

**Comment by erikpique** [comment]
Hi @nicoter1

Oh, BTW, how are trying to run the app? Did you follow the [Windows setup wiki page](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup)?

Greetings

**Comment by ricrocha** [comment]
I followed the instruction on the wiki. The MVC is working and all the docker containers are running (green status)

**Comment by gersondeveloper** [comment]
Hi, I'm having a problem with webspa service.

Error: Service 'webspa'failed to build: Get https://registry-1.docker.io/v2/library/node/manifests/8.11: unanthorizes: please user personal access token to login

**Comment by erikpique** [comment]
Hi @ricrocha 

Did you run the "docker-compose up-build webspa"? Does this give you any error?

Greetings

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
