### ISSUE TITLE
not really an issue 

### ISSUE THREAD

**Issue by nicoter1** [dotnet-architecture/eShopOnContainers#1221]
is there going to be a blazor version of the web project too?

**Comment by punkouter2018** [comment]
Would like also.. Not many Blazor reference apps yet.. Nice to compare that and the MVC version.

**Comment by mvelosop** [comment]
Hi @punkouter2018, it hasn't been decided yet, it might in the future.

It's probable that it gets a "facelift" though 😉, but with the same technologies for now.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
