### ISSUE TITLE
Update of Angular version

### ISSUE THREAD

**Issue by dmytrohridin** [dotnet-architecture/eShopOnContainers#1223]
Hi all,
I believe it make sense to upgrade WevSPA client to Angular 8 version, so project will contain latest UI version (Angular 9 is still in RC). 
What do you think about this? If you will approve I can take it.
Thank you 😊

**Comment by nishanil** [comment]
@dmytrohridin Sure. Feel free to send us a PR for us to review.

**Comment by dmytrohridin** [comment]
@nishanil Thanks a lot. Will work on it 👍

**Comment by erikpique** [comment]
Hi @dmytrohridin 

In order to be able to solve certain vulnerabilities, it has been necessary to upgrade from version 7 to 8 of Angular

Greetings
