### ISSUE TITLE
Question: Separate Service for Query / Command

### ISSUE THREAD

**Issue by MattHartz** [dotnet-architecture/eShopOnContainers#1226]
Hi all,

Thanks for create and maintaining this repo! I've recently started digging into CQRS as I am trying to help make my backend more robust, scalable, and testable.

I do have a question in regards to design, and if my idea is good or bad. So I've read one benefit to CQRS is that since we separate Query from Commands, we can have them in separate services and scale them out individually. I do not see an example of this in this repo and am curious if breaking out OrderingService into OrderingQueryService and OrderingCommandService makes sense or is overkill in most applications.

Anyways, thanks for this!

**Comment by dmytrohridin** [comment]
Hi,
Interesting idea 👍 
But CQRS it’s not only about infrastructure separation. You can also separate your business logic too.

**Comment by erikpique** [comment]
Hi @MattHartz 

For more information about cqrs in eshop you can read the following entry in the project wiki [CQRS-eShop](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Simplified-CQRS-and-DDD)

Greetings.

**Comment by MattHartz** [comment]
Looks fantastic. Thanks @erikpique

**Comment by erikpique** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
