### ISSUE TITLE
[Question] Why do the Dockerfiles copy and restore the entire solution instead of only copying the projects they need?

### ISSUE THREAD

**Issue by davidhenley** [dotnet-architecture/eShopOnContainers#1229]
For example: https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Basket/Basket.API/Dockerfile

This copies every csproj file and restores the entire solution.

Wouldn't it be a lot faster if it only copied and restored the projects that are referenced in the entry assembly for this specific Dockerfile's project?

Was this done for a specific reason?

**Comment by erikpique** [comment]
If you're absolutely right. 
Why this is so is because it's just an example to illustrate.

Greetings

**Comment by mvelosop** [comment]
Hi @davidhenley,

There's another reason for this too, that makes sense for local development.

Having the solution and all projects copied up front, allows you to do a package restore for the whole solution, so all packages are in the Docker build cache, and that speeds the build step for the whole project more than twice as fast, and down to a few seconds when building a single project.

The above is true provided you don't change the .csproj (which you don't most of the time).

Hope this helps.

**Comment by davidhenley** [comment]
@mvelosop @erikpique thanks for the info!
