### ISSUE TITLE
VS debugging experience fail after startup

### ISSUE THREAD

**Issue by wicharypawel** [dotnet-architecture/eShopOnContainers#1233]
Hi,
I have recently stopped on rather simple looking error while debugging eShopOnContainer. Visual Studio starts building solution, continues with docker images, start containers successfully and just after debugging session starts it detach itself and stops.

VS version: 2019 (version 16.4.4)
Docker desktop community version: 2.2.0.0 (42247)
CLI approach using docker-compose build and docker-compose up works without any problems.

Steps to reproduce
1. Pull commit 20238d536f9175ed3358ffbcf0b6d85a00e713e2
2. Assign extra memory for docker as well as access to shared drive, change firewall (more here: https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup)
3. Select docker-compose as startup
4. Open VS 
5. Start debugging session

Expected behaviour:
All containers alive and debugging session started. Application available.

Actual behaviour: 
All containers alive (which is ok, i see containers in up status) debugging session closed. Application unavailable.

Although, containers are reported as healthy (up status) i application is not responding. 

```
docker logs any-eshop-container-id-here
```
Prints:
```
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
```

I was trying to:
- restart machine
- restart docker
- restart docker credentials for shared drives
- ensured that SDK base image is in Dockerfile
- tried to list sdks inside of the container using docker exec -it ... which retuns 
- run VS as administrator

Command executed inside of the container created by VS.
```
dotnet --list-sdks
```
Prints:
```
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

I am not sure what I am missing. I would appreciate any help.
Regards
Paweł

**Comment by thesobercoder** [comment]
I'm facing the same issue on Visual Studio 2019 Version 16.4.4

**Comment by wicharypawel** [comment]
Today I have tried to find workaround one more time. What I have find out is that while creating new project ASP.NET Core Web Application with Docker support and docker-compose enabled. The same error occur. Moreover it is one of this nasty bugs that are votaile because sometimes it works sometimes crashes.

Reference to bug reported to VS community https://developercommunity.visualstudio.com/content/problem/905449/vs-debugging-experience-fail-after-startup.html

**Comment by wicharypawel** [comment]
Good news. Problem has been solved by VS team and/or Docker for windows team. Updates made the job:

- Visual Studio 2019 to version 16.4.5 (it didn't fixed an issue however this is my current setup)
- Docker desktop to version 2.2.0.3 (42716)

I hope it will work for others as well (let me know and we can close this issue).
