### ISSUE TITLE
webspa not found on 5104

### ISSUE THREAD

**Issue by loxx123** [dotnet-architecture/eShopOnContainers#1241]
I've followed the directions to get the project up and going. I've used all newer branches including both dev and master branches as well as 3.0 release. I've run all branches on both mac and windows machine both from terminal and command line, and in visual studio 2019 and visual studio code. No matter how I run the project, there is no webspa to be found on 5014.

**Comment by mvelosop** [comment]
Hi @loxx123, thanks for the feedback!

Please begin by cleaning you Docker installation:

1. Stop all containers:
   ```
   docker stop $(docker ps -q)
   ```
2. Delete all containers, images and volumes:
   ```
   docker system prune all --volumes
   ```
3. Start the app again as per the [setup page](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup)

4. Check the logs in the webspa container with:
   ```
   docker container logs src_webspa_1
   ```

Hope this helps.

**Comment by loxx123** [comment]
thanks for the response. still not working. i'm using VS2019 and docker 2.2. i've followed the instructions, still not working, nothing in logs showing anything is off.

**Comment by mvelosop** [comment]
Please send the output from the `docker container logs src_webspa_1` command, once the app is running.

**Comment by loxx123** [comment]
it's working now, but only when i build it with powershell, not when i build it with visual studio 2019. the webspa pulls up, but catalog is down, ill open a new issue for that one
