### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by KooshkakiH** [dotnet-architecture/eShopOnContainers#1242]
Hi 
When i want login get below error.

{"@t":"2020-02-18T09:14:38.4907084Z","@mt":"Invalid redirect_uri: {detail}\n{@requestDetails}","@m":"Invalid redirect_uri: http://localhost:5100/signin-oidc\n{\n  \"ClientId\": \"mvc\",\n  \"ClientName\": \"MVC Client\",\n  \"RedirectUri\": null,\n  \"AllowedRedirectUris\": [\n    \"http://docker.for.win.localhost:5100/signin-oidc\"\n  ],\n  \"SubjectId\": \"anonymous\",\n  \"ResponseType\": null,\n  \"ResponseMode\": null,\n  \"GrantType\": null,\n  \"RequestedScopes\": \"\",\n  \"State\": null,\n  \"UiLocales\": null,\n  \"Nonce\": null,\n  \"AuthenticationContextReferenceClasses\": null,\n  \"DisplayMode\": null,\n  \"PromptMode\": null,\n  \"MaxAge\": null,\n  \"LoginHint\": null,\n  \"SessionId\": null,\n  \"Raw\": {\n    \"client_id\": \"mvc\",\n    \"redirect_uri\": \"http://localhost:5100/signin-oidc\",\n    \"response_type\": \"code id_token\",\n    \"scope\": \"openid profile orders basket marketing locations webshoppingagg orders.signalrhub\",\n    \"response_mode\": \"form_post\",\n    \"nonce\": \"637176140781795503.ZGIyNzVlZDAtMTc4ZS00YThmLTkzNjItMjNiNTM1ZmE1NjNlZGRhZjcwMGMtZjJhOS00YWY0LWI0OGMtMTUxYmU1NTRlZWUy\",\n    \"state\": \"CfDJ8H0_oln3Gg1CkWc4e5ff7hBvclnH-PyVyWBc74bAYgwuLuM6YxrG53nk1QIiVlikftkBU1CZE9ti_RUJyFNCndszGV1ktHwTo3jICMavluwWNEomyMYipEmsVlwIQlVQdiyHGlpUPuaylWbD4_DLuuX7OYH-EgGrgYcHHUDE_6pRlIE6PpvIWaGNRekILTnZ78NVft0YWZdvbRHBl64d4jJmZYeDSDOn4mh9dqtlRXstdqKQcysr9n0O0yVd49p3vHXNizAMO2DBa-Lxqgqxw0nU4vrDMUjtpulAl3HHyvR0JxZlDbXzFfQi0XGlPo8QXQ\",\n    \"x-client-SKU\": \"ID_NETSTANDARD2_0\",\n    \"x-client-ver\": \"5.5.0.0\"\n  },\n  \"_typeTag\": \"AuthorizeRequestValidationLog\"\n}","@i":"e32e4900","@l":"Error","detail":"http://localhost:5100/signin-oidc","requestDetails":{"ClientId":"mvc","ClientName":"MVC Client","RedirectUri":null,"AllowedRedirectUris":["http://docker.for.win.localhost:5100/signin-oidc"],"SubjectId":"anonymous","ResponseType":null,"ResponseMode":null,"GrantType":null,"RequestedScopes":"","State":null,"UiLocales":null,"Nonce":null,"AuthenticationContextReferenceClasses":null,"DisplayMode":null,"PromptMode":null,"MaxAge":null,"LoginHint":null,"SessionId":null,"Raw":{"client_id":"mvc","redirect_uri":"http://localhost:5100/signin-oidc","response_type":"code id_token","scope":"openid profile orders basket marketing locations webshoppingagg orders.signalrhub","response_mode":"form_post","nonce":"637176140781795503.ZGIyNzVlZDAtMTc4ZS00YThmLTkzNjItMjNiNTM1ZmE1NjNlZGRhZjcwMGMtZjJhOS00YWY0LWI0OGMtMTUxYmU1NTRlZWUy","state":"CfDJ8H0_oln3Gg1CkWc4e5ff7hBvclnH-PyVyWBc74bAYgwuLuM6YxrG53nk1QIiVlikftkBU1CZE9ti_RUJyFNCndszGV1ktHwTo3jICMavluwWNEomyMYipEmsVlwIQlVQdiyHGlpUPuaylWbD4_DLuuX7OYH-EgGrgYcHHUDE_6pRlIE6PpvIWaGNRekILTnZ78NVft0YWZdvbRHBl64d4jJmZYeDSDOn4mh9dqtlRXstdqKQcysr9n0O0yVd49p3vHXNizAMO2DBa-Lxqgqxw0nU4vrDMUjtpulAl3HHyvR0JxZlDbXzFfQi0XGlPo8QXQ","x-client-SKU":"ID_NETSTANDARD2_0","x-client-ver":"5.5.0.0"},"_typeTag":"AuthorizeRequestValidationLog"},"SourceContext":"IdentityServer4.Validation.AuthorizeRequestValidator","RequestId":"0HLTKABT47F0S:00000001","RequestPath":"/connect/authorize","SpanId":"0c4ee9c7fc972f48","TraceId":"9e115cf49365d44d946b5ce7e247d8c9","ParentId":"0000000000000000","ConnectionId":"0HLTKABT47F0S","ApplicationContext":"Identity.API"}

**Comment by mvelosop** [comment]
Hi @KooshkakiH, thanks for the feedback.

If you're working from the last commit connecting from http://docker.for.win.localhost:5100/ for the MVC app should work.

The above is needed for Docker Desktop 2.2.

Will update the wiki to reflect that in short.

Hope this helps.

**Comment by KooshkakiH** [comment]
Thanks
My problem solved for you answer.

**Comment by KooshkakiH** [comment]
I am using eshoponcontainer on my project. This project is very big. 
No probelm?

**Comment by mvelosop** [comment]
Hi @KooshkakiH, 

Glad this could help you 😊

About:

>I am using eshoponcontainer on my project. My project is very big.
> No probelm?

Keep in mind that eShopOnContainers is a showcase for architectural patterns and, as complex as it may seem, it's just a simplified version suitable for learning purposes.

**eShopOnContainers is not a production-grade template for microservices applications**

I don't know what's your context, of course but, in general, the decision to adopt a microservices architecture should be well-thought about and business-driven, not technology-driven. That means, the business should have a need to scale beyond the limits of the technology that's currently being used. This means it should also be "pain-driven".

A microservices architecture is very complicated and, IMHO, eShopOnContainers is very useful to begin to understand how complicated it is.

Hope this helps.

**Comment by vid83** [comment]
> If you're working from the last commit, connecting from http://docker.for.win.localhost:5100/ for the MVC app should work.

Could you please give some more detail about the proposed solution? I don't understand how the symbolic name could help. I'm totally new to Docker , but as far as i know the DNS name docker.for.win.localhost should be used to connect FROM the container TO the host, and not vice versa, like in this case.

Btw, from what I can understand, docker.for.win.localhost was deprecated. The correct name now should be host.docker.internal, as per [Docker desktop for windows docs](https://docs.docker.com/docker-for-windows/networking/)

I am surely missing something here, could you please help me to understand? Thank you very much.
