### ISSUE TITLE
Docker file COPY not working

### ISSUE THREAD

**Issue by sumitkute** [dotnet-architecture/eShopOnContainers#1243]
I am trying to build the Azure DevOps pipeline for each service, to start with BastketAPI and facing the below issue in docker build.

COPY "eShopOnContainers-ServicesAndWebApps.sln" "eShopOnContainers-ServicesAndWebApps.sln"
COPY failed: stat /var/lib/docker/tmp/docker-builder176262335/eShopOnContainers-ServicesAndWebApps.sln:

Even tried to run docker build on SRC folder and one of the service (basketapi) folder. They give the same error. I am running it on windows 10 machine in Ubuntu Shell.

Seems WORKDIR is not working to set the docker context.  The copy command should run in the context of WORKDIR. Its not happening. The same happens on Azure DevOps build server to.

Any help

**Comment by mvelosop** [comment]
Hi @sumitkute, thanks for the feedback,

Please check this line:

https://github.com/dotnet-architecture/eShopOnContainers/blob/20238d536f9175ed3358ffbcf0b6d85a00e713e2/build/azure-devops/buildimages.yaml#L32

The build is done in an Ubuntu machine, not Windows with the Ubuntu shell.

That's the setup that's working right now in Azure DevOps, so it should work for you too.

BTW, the build for actual Windows images is currently disabled.

Hope this helps.

**Comment by sumitkute** [comment]
I tried on Ubuntu machine.. same error. 
I am running docker build from /src/Services/Basket/Basket.API.
I created a build publine from\eShopOnContainers\build\azure-devops\buildimages.yaml getting error
/build/azure-devops/buildimages.yaml (Line: 2, Col: 3): A mapping was not expected.

**Comment by mvelosop** [comment]
@sumitkute,

You should create the build pipeline from `build\azure-devops\basket-api\azure-pipelines.yml` and that template will use the `buildimages.yaml` as a template.

The `.yaml` files in `build\azure-devops` (**from DEV branch**) are being used right now to check every PR in this repo, so that should work for you too.

Hope this helps.

**Comment by sumitkute** [comment]
Thanks. It worked. I learned, it will only run via docker compose and not directly due to docker componse set the build context and DockerFile are written accordingly.
