### ISSUE TITLE
nuget restore problem

### ISSUE THREAD

**Issue by slopeWu** [dotnet-architecture/eShopOnContainers#1244]
![1](https://user-images.githubusercontent.com/28820187/74962975-e507de80-544b-11ea-98a9-ff5ff514297a.png)

请问怎么回事啊，还原不 了

**Comment by KooshkakiH** [comment]
What is version of visual studio and dotnet on your system?

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
