### ISSUE TITLE
Error requesting catalog products, please try later on

### ISSUE THREAD

**Issue by codenshare** [dotnet-architecture/eShopOnContainers#1245]
Hi, I followed the steps and deployed on AKS, but getting the error - "Error requesting catalog products, please try later on" on the main page. Please advise. Screenshot attached.

![eshoperror](https://user-images.githubusercontent.com/36931823/74963456-c1a74a00-53df-11ea-8339-88fcb1a071f7.jpg)

URL: http://eshop.97e2a7f4a6fb4dab913b.westeurope.aksapp.io/

PS > kubectl get deployment
NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
eshop-apigwmm                    1/1     1            1           3m43s
eshop-apigwms                    1/1     1            1           3m39s
eshop-apigwwm                    1/1     1            1           3m35s
eshop-apigwws                    1/1     1            1           3m31s
eshop-basket-api                 1/1     1            1           4m54s
eshop-basket-data                1/1     1            1           4m59s
eshop-catalog-api                1/1     1            1           4m51s
eshop-identity-api               1/1     1            1           4m47s
eshop-keystore-data              1/1     1            1           5m1s
eshop-locations-api              1/1     1            1           4m35s
eshop-marketing-api              1/1     1            1           4m31s
eshop-mobileshoppingagg          1/1     1            1           4m28s
eshop-nosql-data                 1/1     1            1           5m7s
eshop-ordering-api               1/1     1            1           4m25s
eshop-ordering-backgroundtasks   1/1     1            1           4m21s
eshop-ordering-signalrhub        1/1     1            1           4m18s
eshop-payment-api                1/1     1            1           4m15s
eshop-rabbitmq                   1/1     1            1           5m4s
eshop-sql-data                   1/1     1            1           5m10s
eshop-webhooks-api               1/1     1            1           3m50s
eshop-webhooks-web               1/1     1            1           3m46s
eshop-webmvc                     0/1     1            0           4m12s
eshop-webshoppingagg             1/1     1            1           4m8s
eshop-webspa                     1/1     1            1           4m5s
eshop-webstatus                  1/1     1            1           3m53s

**Comment by eiximenis** [comment]
Should check if the call reaches catalog-api or is stuck in apigwws.

- Are the ingresses enabled? (kubectl get ing)
- What are the logs of catalog api pod?

**Comment by codenshare** [comment]
NAME                 HOSTS                                             ADDRESS        PORTS   AGE
eshop-apigwmm        eshop.97e2a7f4a6fb4dab913b.westeurope.aksapp.io   51.137.1.152   80      62m
eshop-apigwms        eshop.97e2a7f4a6fb4dab913b.westeurope.aksapp.io   51.137.1.152   80      62m
eshop-apigwwm        eshop.97e2a7f4a6fb4dab913b.westeurope.aksapp.io   51.137.1.152   80      62m
eshop-apigwws        eshop.97e2a7f4a6fb4dab913b.westeurope.aksapp.io   51.137.1.152   80      62m
eshop-identity-api   eshop.97e2a7f4a6fb4dab913b.westeurope.aksapp.io   51.137.1.152   80      63m
eshop-webhooks-api   eshop.97e2a7f4a6fb4dab913b.westeurope.aksapp.io   51.137.1.152   80      62m
eshop-webhooks-web   eshop.97e2a7f4a6fb4dab913b.westeurope.aksapp.io   51.137.1.152   80      62m
eshop-webmvc         eshop.97e2a7f4a6fb4dab913b.westeurope.aksapp.io   51.137.1.152   80      63m
eshop-webspa         eshop.97e2a7f4a6fb4dab913b.westeurope.aksapp.io   51.137.1.152   80      63m
eshop-webstatus      eshop.97e2a7f4a6fb4dab913b.westeurope.aksapp.io   51.137.1.152   80      63m

**Comment by hpr112** [comment]
I have the same problem. Have you found a solution?

**Comment by nishanil** [comment]
@eiximenis @mvelosop I am able to reproduce this issue. As a workaround, the webmvc works if deployed with `linux-dev` image tag.

**Comment by hpr112** [comment]
do you know why it works with linux-dev but not any of the other imagetags?

**Comment by nishanil** [comment]
Yes, our DevOps pipeline is broken so the images were not being pushed to `dev` which is what we suggest everyone use. Other tags are used in parallel for testing and I guess @eiximenis used `linux-dev` while working on the 3.1 updates.
