### ISSUE TITLE
Where are the environment variables like REGISTRY defined?

### ISSUE THREAD

**Issue by rcholic** [dotnet-architecture/eShopOnContainers#1246]
In the docker-compose.yml, I am confused by the environment variables such as `REGISTRY`, `PLATFORM`. Where are they defined? what are the suffix -eshop, -linux? are they the default value if the environment variables not found?

```
${REGISTRY:-eshop}/identity.api:${PLATFORM:-linux}-${TAG:-latest}
```

**Comment by KooshkakiH** [comment]
In .env file. but REGISTRY and PLATFORM  no defined in this file but i defined for myself. suffixes are arbitrary for tagged image.

**Comment by mvelosop** [comment]
Hi @rcholic,

You can define those values as environment variables, just the usual way you do in the OS you're working on.

The `:-eshop` syntax, that looks like a tag, just as you is you thought is the default value that'll be used if the environment variable is not defined. In this case, the value would be `eshop` (without the dash).

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
