### ISSUE TITLE
[Question] Nginx locally

### ISSUE THREAD

**Issue by vany0114** [dotnet-architecture/eShopOnContainers#1247]
Hey guys, 

Is it possible to use Nginx locally on Windows w/o stop other services (such IIS) that use 80 port? What I'm doing is to stop those services using `net stop http` command.

Also, I'm adding a host name into the hosts file, but I suppossed I could use `localhost `or `kubernetes.docker.internal`, right?

Thanks in advance.

**Comment by vany0114** [comment]
Well, I managed to run `nginx` on 81 port, just changing the port on [ingress-nginx](https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/cloud-generic.yaml) service.

**Comment by nishanil** [comment]
Cool 😎. Closing this issue.
