### ISSUE TITLE
Authentication issue in Ocelot API Gateway

### ISSUE THREAD

**Issue by Bilal-Mubeen** [dotnet-architecture/eShopOnContainers#1250]
I am facing an issue i.e my application is working fine after successful login and after some time API gateway start sending the **Unauthorized** response. Where as if i try to call my API directly using the same token the request get validated and properly executed.

Create Token code in LoginService.cs:

    `private string GenerateToken(string userId,string userName)
        {
            var now = DateTime.UtcNow;
            var expireDateTime = now.Add(TimeSpan.FromMinutes(60));
            var claims = new[]
            {
                new System.Security.Claims.Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString()),
                new System.Security.Claims.Claim(JwtRegisteredClaimNames.Iat, now.ToUniversalTime().ToString(CultureInfo.InvariantCulture),
                    ClaimValueTypes.Integer64),
                new System.Security.Claims.Claim(ClaimTypes.Name, userName),
                new System.Security.Claims.Claim(ClaimTypes.Sid, userId),
            };

            var signingKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes(_settings.Value.AuthSecret));
            var jwt = new JwtSecurityToken(
                issuer: _settings.Value.Iss,
                audience: _settings.Value.Aud,
                claims: claims,
                notBefore: now,
                expires: expireDateTime,
                signingCredentials: new SigningCredentials(signingKey, SecurityAlgorithms.HmacSha256)
            );

            return new JwtSecurityTokenHandler().WriteToken(jwt);
        }`

Api gateway code for validation in Startup.cs file:

       `public static IServiceCollection AddCustomAuthentication(this IServiceCollection services,
            IConfiguration configuration)
        {
            var audienceConfig = configuration.GetSection("Audience");
            var authenticationProviderKey = audienceConfig["AuthKey"];

            var signingKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes(audienceConfig["AuthSecret"]));
            var tokenValidationParameters = new TokenValidationParameters
            {
                ValidateIssuerSigningKey = true,
                IssuerSigningKey = signingKey,
                ValidateIssuer = true,
                ValidIssuer = audienceConfig["Iss"],
                ValidateAudience = true,
                ValidAudience = audienceConfig["Aud"],
                ValidateLifetime = true,
                ClockSkew = TimeSpan.Zero,
                RequireExpirationTime = true,
            };

            services
                .AddAuthentication(x =>
                {
                    x.DefaultAuthenticateScheme = authenticationProviderKey;
                    x.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                })
                .AddJwtBearer(authenticationProviderKey, x =>
                {

                    x.RequireHttpsMetadata = false;
                    x.TokenValidationParameters = tokenValidationParameters;
                });

            return services;
        }`

configuration.json for Ocelot Gateway:

 `{
      "DownstreamPathTemplate": "/api/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 60005
        }
      ],
      "UpstreamPathTemplate": "/rating/api/{everything}",
      "UpstreamHttpMethod": [],
      "LoadBalancerOptions": {
        "Type": "LeastConnection"
      },
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "AuthKey",
        "AllowedScopes": []
      }
    }`

**Comment by mvelosop** [comment]
Hi @Bilal-Mubeen, this is probable not a good place to ask for this since it's not related to eShopOnContainers, even more so now that Ocelot is not being used as the base for the API gateway.

Anyway, the authentication when Ocelot was used wasn't done through the API gateway.

I'm sorry I can't be any more helpful here.

Closing the issue as not related to eShopOnContainers.
