### ISSUE TITLE
grpc can‘t gen code

### ISSUE THREAD

**Issue by angel6708** [dotnet-architecture/eShopOnContainers#1251]
when i build the solution with vs2019 , an error occured as bellow：
--grpc_out : error : protoc-gen-grpc: system cant find the  path.
i have read this issue:
https://github.com/dotnet-architecture/eShopOnContainers/wiki/gRPC#generating-server-or-client-stubs-from-proto-file-in-net-core-3

**Comment by angel6708** [comment]
when change the syntax from  [syntax = "proto3";] to [syntax = "proto2";]
error occured as bellow:
basket.proto(13,9): error : Expected "required", "optional", or "repeated".

**Comment by angel6708** [comment]
i temporary solve the problem following the steps bellow:
1. copy nuget packages to the root dir.
2.add  grpc tools  =>[  C:\.nuget\packages\grpc.tools\2.27.0\tools\windows_x64 ] to PATH ev.  (not needed ?)
3.copy proto files to C:\grpc 
4.run cmdline:   `protoc.exe --csharp_out=obj\Debug\netcoreapp3.1 --plugin="protoc-gen-grpc=C:\.nuget\packages\grpc.tools\2.27.0\tools\windows_x64\grpc_csharp_plugin.exe" --grpc_out=obj\Debug\netcoreapp3.1 --proto_path="C:\.nuget\packages\grpc.tools\2.27.0\build\native\include" --proto_path=.  basket.proto`

**Comment by makana** [comment]
I had the same problem and spent hours on this.

Saw this issue grpc/grpc/issues/17995 and figured out that is was the ß in my user folder.

Add 
```xml
<config>
  <add key="globalPackagesFolder" value=".\packages" />
</config>
```
or any non-special-character packages path to the Nuget.config and get the things running....

**Comment by sughosneo** [comment]
Hi @angel6708, thank you for reaching out. Is your cloned `eShopOnContainers` repository path contains any special character ?
And thanks @makana , for sharing that information. 

Please let us know if this issue still persist.

Thank you.

**Comment by sughosneo** [comment]
I am closing this issue as of now. Please feel free to reopen it if you have any further questions.

Thank you.
