### ISSUE TITLE
Ordering.API Dockerfile.develop invalid workpath? Orders API Dockerfile bug query....

### ISSUE THREAD

**Issue by dcs3spp** [dotnet-architecture/eShopOnContainers#1253]
Hi,

Does this [line](https://github.com/dotnet-architecture/eShopOnContainers/blob/c0e125f2bf32303b0c282b45f3ba029638177125/src/Services/Ordering/Ordering.API/Dockerfile.develop#L19) have an invalid path with src/src/ prefix in the Ordering.API Dockerfile.develop?

**Comment by sughosneo** [comment]
Hello @dcs3spp, yes it was like initially but has been changed in this [commit](https://github.com/dotnet-architecture/eShopOnContainers/commit/870363861f526e05433eb4e9bccbac4b1b4882c3#diff-6108a6e09181078530e70f3d662dbbe2). You can take the latest from `dev` branch. 

As of now, closing this issue. Please feel free to reopen if you have any pending questions. 

Thanks.

**Comment by dcs3spp** [comment]
Hi @sughosneo, 

Many thanks for responding and confirming
