### ISSUE TITLE
Envoy proxy connection refused

### ISSUE THREAD

**Issue by KooshkakiH** [dotnet-architecture/eShopOnContainers#1255]
Hi 
envoy proxy on production environment has connection refused.

**Comment by nishanil** [comment]
@KooshkakiH What's the production env? 
I was able to run the script and deploy the `linux-dev` images to AKS.
https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS)

**Comment by KooshkakiH** [comment]
I am using docker-compose on linux server with below text:
services:
  basket-api:
    container_name: basket-api
    depends_on:
    - basketdata
    - identity-api
    - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ApplicationInsights__InstrumentationKey: ''
      AzureServiceBusEnabled: "False"
      ConnectionString: basketdata
      EventBusConnection: rabbitmq
      EventBusPassword: ''
      EventBusUserName: ''
      GRPC_PORT: '81'
      IdentityUrlExternal: http://192.168.12.51:5105
      OrchestratorType: ''
      PATH_BASE: /basket-api
      PORT: '80'
      UseLoadTest: "False"
      identityUrl: http://identity-api
    image: 192.168.12.51:5000/basket.api:linux-latest
    ports:
    - published: 5103
      target: 80
    - published: 9103
      target: 81
  basketdata:
    container_name: basketdata
    image: redis:alpine
    ports:
    - published: 6379
      target: 6379
    volumes:
    - eshop-basketdata:/data:rw
  catalog-api:
    container_name: catalog-api
    depends_on:
    - rabbitmq
    - sqldata
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ApplicationInsights__InstrumentationKey: ''
      AzureServiceBusEnabled: "False"
      AzureStorageAccountKey: ''
      AzureStorageAccountName: ''
      AzureStorageEnabled: "False"
      ConnectionString: Server=sqldata;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User
        Id=sa;Password=Pass@word
      EventBusConnection: rabbitmq
      EventBusPassword: ''
      EventBusUserName: ''
      GRPC_PORT: '81'
      OrchestratorType: ''
      PATH_BASE: /catalog-api
      PORT: '80'
      PicBaseUrl: http://192.168.12.51:5202/c/api/v1/catalog/items/[0]/pic/
      UseCustomizationData: "True"
    image: 192.168.12.51:5000/catalog.api:linux-latest
    ports:
    - published: 5101
      target: 80
    - published: 9101
      target: 81
  identity-api:
    container_name: identity-api
    depends_on:
    - sqldata
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ApplicationInsights__InstrumentationKey: ''
      BasketApiClient: http://192.168.12.51:5103
      ConnectionString: Server=sqldata;Database=Microsoft.eShopOnContainers.Service.IdentityDb;User
        Id=sa;Password=Pass@word
      LocationApiClient: http://192.168.12.51:5109
      MarketingApiClient: http://192.168.12.51:5110
      MobileShoppingAggClient: http://192.168.12.51:5120
      MvcClient: http://192.168.12.51:5100
      OrchestratorType: ''
      OrderingApiClient: http://192.168.12.51:5102
      SpaClient: http://192.168.12.51:5104
      UseCustomizationData: "True"
      WebShoppingAggClient: http://192.168.12.51:5121
      WebhooksApiClient: http://192.168.12.51:5113
      WebhooksWebClient: http://192.168.12.51:5114
      XamarinCallback: http://192.168.12.51:5105/xamarincallback
    image: 192.168.12.51:5000/identity.api:linux-latest
    ports:
    - published: 5105
      target: 80
  locations-api:
    container_name: locations-api
    depends_on:
    - nosqldata
    - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ApplicationInsights__InstrumentationKey: ''
      AzureServiceBusEnabled: "False"
      ConnectionString: mongodb://nosqldata
      Database: LocationsDb
      EventBusConnection: rabbitmq
      EventBusPassword: ''
      EventBusUserName: ''
      IdentityUrlExternal: http://192.168.12.51:5105
      OrchestratorType: ''
      PATH_BASE: /locations-api
      UseLoadTest: "False"
      identityUrl: http://identity-api
    image: 192.168.12.51:5000/locations.api:linux-latest
    ports:
    - published: 5109
      target: 80
  marketing-api:
    container_name: marketing-api
    depends_on:
    - identity-api
    - nosqldata
    - rabbitmq
    - sqldata
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ApplicationInsights__InstrumentationKey: ''
      AzureServiceBusEnabled: "False"
      AzureStorageAccountKey: ''
      AzureStorageAccountName: ''
      AzureStorageEnabled: "False"
      CampaignDetailFunctionUri: ''
      ConnectionString: Server=sqldata;Database=Microsoft.eShopOnContainers.Services.MarketingDb;User
        Id=sa;Password=Pass@word
      EventBusConnection: rabbitmq
      EventBusPassword: ''
      EventBusUserName: ''
      IdentityUrlExternal: http://192.168.12.51:5105
      MongoConnectionString: mongodb://nosqldata
      MongoDatabase: MarketingDb
      OrchestratorType: ''
      PATH_BASE: /marketing-api
      PicBaseUrl: http://192.168.12.51:5110/api/v1/campaigns/[0]/pic/
      UseLoadTest: "False"
      identityUrl: http://identity-api
    image: 192.168.12.51:5000/marketing.api:linux-latest
    ports:
    - published: 5110
      target: 80
  mobilemarketingapigw:
    container_name: mobilemarketingapigw
    image: envoyproxy/envoy:v1.13.0
    ports:
    - published: 5201
      target: 80
    - published: 15201
      target: 8001
    volumes:
    - mobileshopping:/etc/envoy:rw
  mobileshoppingagg:
    container_name: mobileshoppingagg
    depends_on:
    - basket-api
    - catalog-api
    - identity-api
    - marketing-api
    - nosqldata
    - ordering-api
    - rabbitmq
    - sqldata
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      BasketUrlHC: http://basket-api/hc
      CatalogUrlHC: http://catalog-api/hc
      IdentityUrlExternal: http://192.168.12.51:5105
      IdentityUrlHC: http://identity-api/hc
      LocationUrlHC: http://locations-api/hc
      MarketingUrlHC: http://marketing-api/hc
      OrderingUrlHC: http://ordering-api/hc
      PaymentUrlHC: http://payment-api/hc
      urls__basket: http://basket-api
      urls__catalog: http://catalog-api
      urls__grpcBasket: http://basket-api:81
      urls__grpcCatalog: http://catalog-api:81
      urls__grpcOrdering: http://ordering-api:81
      urls__identity: http://identity-api
      urls__orders: http://ordering-api
    image: 192.168.12.51:5000/mobileshoppingagg:linux-latest
    ports:
    - published: 5120
      target: 80
  mobileshoppingapigw:
    container_name: mobileshoppingapigw
    image: envoyproxy/envoy:v1.13.0
    ports:
    - published: 5200
      target: 80
    - published: 15200
      target: 8001
    volumes:
    - mobilemarketing:/etc/envoy:rw
  nosqldata:
    container_name: nosqldata
    image: mongo
    ports:
    - published: 27017
      target: 27017
    volumes:
    - eshop-nosqldata:/data/db:rw
  ordering-api:
    container_name: ordering-api
    depends_on:
    - rabbitmq
    - sqldata
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ApplicationInsights__InstrumentationKey: ''
      AzureServiceBusEnabled: "False"
      CheckUpdateTime: '30000'
      ConnectionString: Server=sqldata;Database=Microsoft.eShopOnContainers.Services.OrderingDb;User
        Id=sa;Password=Pass@word
      EventBusConnection: rabbitmq
      EventBusPassword: ''
      EventBusUserName: ''
      GRPC_PORT: '81'
      IdentityUrlExternal: http://192.168.12.51:5105
      OrchestratorType: ''
      PATH_BASE: /ordering-api
      PORT: '80'
      Serilog__MinimumLevel__Override__Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ: Verbose
      Serilog__MinimumLevel__Override__ordering-api: Verbose
      UseCustomizationData: "True"
      UseLoadTest: "False"
      identityUrl: http://identity-api
    image: 192.168.12.51:5000/ordering.api:linux-latest
    ports:
    - published: 5102
      target: 80
    - published: 9102
      target: 81
  ordering-backgroundtasks:
    container_name: ordering-backgroundtasks
    depends_on:
    - rabbitmq
    - sqldata
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ApplicationInsights__InstrumentationKey: ''
      AzureServiceBusEnabled: "False"
      CheckUpdateTime: '30000'
      ConnectionString: Server=sqldata;Database=Microsoft.eShopOnContainers.Services.OrderingDb;User
        Id=sa;Password=Pass@word
      EventBusConnection: rabbitmq
      EventBusPassword: ''
      EventBusUserName: ''
      GracePeriodTime: '1'
      OrchestratorType: ''
      Serilog__MinimumLevel__Override__Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ: Verbose
      UseCustomizationData: "True"
      UseLoadTest: "False"
    image: 192.168.12.51:5000/ordering.backgroundtasks:linux-latest
    ports:
    - published: 5111
      target: 80
  ordering-signalrhub:
    container_name: ordering-signalrhub
    depends_on:
    - basket-api
    - catalog-api
    - identity-api
    - marketing-api
    - nosqldata
    - ordering-api
    - rabbitmq
    - sqldata
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ApplicationInsights__InstrumentationKey: ''
      AzureServiceBusEnabled: "False"
      EventBusConnection: rabbitmq
      EventBusPassword: ''
      EventBusUserName: ''
      OrchestratorType: ''
      identityUrl: http://identity-api
    image: 192.168.12.51:5000/ordering.signalrhub:linux-latest
    ports:
    - published: 5112
      target: 80
  payment-api:
    container_name: payment-api
    depends_on:
    - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ApplicationInsights__InstrumentationKey: ''
      AzureServiceBusEnabled: "False"
      EventBusConnection: rabbitmq
      EventBusPassword: ''
      EventBusUserName: ''
      OrchestratorType: ''
      Serilog__MinimumLevel__Override__Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ: Verbose
      Serilog__MinimumLevel__Override__payment-api.IntegrationEvents.EventHandling: Verbose
    image: 192.168.12.51:5000/payment.api:linux-latest
    ports:
    - published: 5108
      target: 80
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
    - published: 5672
      target: 5672
    - published: 15672
      target: 15672
  seq:
    container_name: seq
    environment:
      ACCEPT_EULA: "Y"
    image: datalust/seq:latest
    ports:
    - published: 5340
      target: 80
  sqldata:
    container_name: sqldata
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Pass@word
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
    - published: 5433
      target: 1433
    volumes:
    - eshop-sqldata:/var/opt/mssql:rw
  webhooks-api:
    container_name: webhooks-api
    depends_on:
    - sqldata
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionString: Server=sqldata;Database=Microsoft.eShopOnContainers.Services.WebhooksDb;User
        Id=sa;Password=Pass@word
      EventBusConnection: rabbitmq
      EventBusPassword: ''
      EventBusUserName: ''
      IdentityUrl: http://identity-api
      IdentityUrlExternal: http://192.168.12.51:5105
    image: 192.168.12.51:5000/webhooks.api:linux-latest
    ports:
    - published: 5113
      target: 80
  webhooks-client:
    container_name: webhooks-client
    depends_on:
    - webhooks-api
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:80
      CallBackUrl: http://192.168.12.51:5114
      IdentityUrl: http://192.168.12.51:5105
      SelfUrl: http://webhooks-client/
      Token: 6168DB8D-DC58-4094-AF24-483278923590
      WebhooksUrl: http://webhooks-api
    image: 192.168.12.51:5000/webhooks.client:linux-latest
    ports:
    - published: 5114
      target: 80
  webmarketingapigw:
    container_name: webmarketingapigw
    image: envoyproxy/envoy:v1.13.0
    ports:
    - published: 5203
      target: 80
    - published: 15203
      target: 8001
    volumes:
    - webmarketing:/etc/envoy:rw
  webmvc:
    container_name: webmvc
    depends_on:
    - webmarketingapigw
    - webshoppingagg
    - webshoppingapigw
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ApplicationInsights__InstrumentationKey: ''
      IdentityUrl: http://192.168.12.51:5105
      IdentityUrlHC: http://identity-api/hc
      MarketingUrl: http://webmarketingapigw
      OrchestratorType: ''
      PurchaseUrl: http://webshoppingapigw
      SignalrHubUrl: http://192.168.12.51:5202
      UseCustomizationData: "True"
      UseLoadTest: "False"
    image: 192.168.12.51:5000/webmvc:linux-latest
    ports:
    - published: 5100
      target: 80
  webshoppingagg:
    container_name: webshoppingagg
    depends_on:
    - basket-api
    - catalog-api
    - identity-api
    - marketing-api
    - nosqldata
    - ordering-api
    - rabbitmq
    - sqldata
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      BasketUrlHC: http://basket-api/hc
      CatalogUrlHC: http://catalog-api/hc
      IdentityUrlExternal: http://192.168.12.51:5105
      IdentityUrlHC: http://identity-api/hc
      LocationUrlHC: http://locations-api/hc
      MarketingUrlHC: http://marketing-api/hc
      OrderingUrlHC: http://ordering-api/hc
      PaymentUrlHC: http://payment-api/hc
      urls__basket: http://basket-api
      urls__catalog: http://catalog-api
      urls__grpcBasket: http://basket-api:81
      urls__grpcCatalog: http://catalog-api:81
      urls__grpcOrdering: http://ordering-api:81
      urls__identity: http://identity-api
      urls__orders: http://ordering-api
    image: 192.168.12.51:5000/webshoppingagg:linux-latest
    ports:
    - published: 5121
      target: 80
  webshoppingapigw:
    container_name: webshoppingapigw
    image: envoyproxy/envoy:v1.13.0
    ports:
    - published: 5202
      target: 80
    - published: 15202
      target: 8001
    volumes:
    - webshopping:/etc/envoy:rw
  webspa:
    container_name: webspa
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ApplicationInsights__InstrumentationKey: ''
      IdentityUrl: http://192.168.12.51:5105
      IdentityUrlHC: http://identity-api/hc
      MarketingUrl: http://192.168.12.51:5203
      OrchestratorType: ''
      PurchaseUrl: http://webshoppingapigw
      SignalrHubUrl: http://192.168.12.51:5202
      UseCustomizationData: "True"
    image: 192.168.12.51:5000/webspa:linux-latest
    ports:
    - published: 5104
      target: 80
  webstatus:
    container_name: webstatus
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ApplicationInsights__InstrumentationKey: ''
      HealthChecksUI__HealthChecks__0__Name: WebMVC HTTP Check
      HealthChecksUI__HealthChecks__0__Uri: http://webmvc/hc
      HealthChecksUI__HealthChecks__10__Name: Payments HTTP Check
      HealthChecksUI__HealthChecks__10__Uri: http://payment-api/hc
      HealthChecksUI__HealthChecks__11__Name: Ordering SignalRHub HTTP Check
      HealthChecksUI__HealthChecks__11__Uri: http://ordering-signalrhub/hc
      HealthChecksUI__HealthChecks__12__Name: Ordering HTTP Background Check
      HealthChecksUI__HealthChecks__12__Uri: http://ordering-backgroundtasks/hc
      HealthChecksUI__HealthChecks__1__Name: WebSPA HTTP Check
      HealthChecksUI__HealthChecks__1__Uri: http://webspa/hc
      HealthChecksUI__HealthChecks__2__Name: Web Shopping Aggregator GW HTTP Check
      HealthChecksUI__HealthChecks__2__Uri: http://webshoppingagg/hc
      HealthChecksUI__HealthChecks__3__Name: Mobile Shopping Aggregator HTTP Check
      HealthChecksUI__HealthChecks__3__Uri: http://mobileshoppingagg/hc
      HealthChecksUI__HealthChecks__4__Name: Ordering HTTP Check
      HealthChecksUI__HealthChecks__4__Uri: http://ordering-api/hc
      HealthChecksUI__HealthChecks__5__Name: Basket HTTP Check
      HealthChecksUI__HealthChecks__5__Uri: http://basket-api/hc
      HealthChecksUI__HealthChecks__6__Name: Catalog HTTP Check
      HealthChecksUI__HealthChecks__6__Uri: http://catalog-api/hc
      HealthChecksUI__HealthChecks__7__Name: Identity HTTP Check
      HealthChecksUI__HealthChecks__7__Uri: http://identity-api/hc
      HealthChecksUI__HealthChecks__8__Name: Marketing HTTP Check
      HealthChecksUI__HealthChecks__8__Uri: http://marketing-api/hc
      HealthChecksUI__HealthChecks__9__Name: Locations HTTP Check
      HealthChecksUI__HealthChecks__9__Uri: http://locations-api/hc
      OrchestratorType: ''
    image: 192.168.12.51:5000/webstatus:linux-latest
    ports:
    - published: 5107
      target: 80
version: '3.4'
volumes:
  eshop-basketdata:
    external: false
  eshop-nosqldata:
    external: false
  eshop-sqldata:
    external: false
  mobileshopping:
    external: false
  mobilemarketing:
    external: false
  webmarketing:
    external: false
  webshopping:
    external: false

**Comment by KooshkakiH** [comment]
Can anyone answer to this issue?
Because it's been opened a long time.
