### ISSUE TITLE
packageSources unavilable

### ISSUE THREAD

**Issue by angel6708** [dotnet-architecture/eShopOnContainers#1256]
the following 	packageSources unavilable:
  <add key="Preview-aspnetcore-tools" value="https://dotnet.myget.org/F/aspnetcore-tools/api/v3/index.json" />
    <add key="Preview-aspnetcore-dev" value="https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json" />
	  <add key="Preview-aspnetcore" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
