### ISSUE TITLE
Cannot get into login page 

### ISSUE THREAD

**Issue by Dudelsb** [dotnet-architecture/eShopOnContainers#1258]
I have setup the application as per the documentation .
I'm able to navigate till home page but as soon as i click on login button it gives me unauthorized client error attached in the screen-shot .
Could somebody please take a look on this .

Thanks 

![Error](https://user-images.githubusercontent.com/6405166/75733844-584b0380-5d1c-11ea-84c8-f68598c9b81b.png)

![healthSnapshot](https://user-images.githubusercontent.com/6405166/75734044-e1fad100-5d1c-11ea-98ed-8d8d1bfad6a1.png)

**Comment by KooshkakiH** [comment]
You must use http://docker.for.win.localhost:5100 url.

**Comment by nishanil** [comment]
Yes, tracking it here: https://github.com/dotnet-architecture/eShopOnContainers/issues/1236

**Comment by Dudelsb** [comment]
Thanks a lot  for help @KooshkakiH and @nishanil . I am able to navigate to login screen now .
Would it be possible for you guys to explain what's causing this.
