### ISSUE TITLE
Sample Identity Server Certificate idsrv3test expired on 20th January 2020 22:00

### ISSUE THREAD

**Issue by dcs3spp** [dotnet-architecture/eShopOnContainers#1265]
The sample identity server certificate at ```src/Services/Identity/Identity.API/Certificate/idsrv3test.pfx``` expired on 20th January 2020 at 22:00

``` bash
Certificate CN=idsrv3test has expired on 01/20/2020 22:00:00
```

**Comment by mvelosop** [comment]
Hi @dcs3spp, thanks for the feedback.

There's no need to update this for development so it'll be left that way, as a reminder that this is a demo version for learning.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.

**Comment by dcs3spp** [comment]
Cheers @mvelosop 

Including a script I used to regenerate a certificate....

``` bash
#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

PRIVATE_PEM=$DIR/private.pem
PUBLIC_PEM=$DIR/public.pem
PFX=$DIR/idsrv3test.pfx
PASSWD="idsrv3test"

echo "Creating Private Key"
openssl genrsa 2048 > $PRIVATE_PEM

echo "Creating Public Key"
echo """GB
State
City
Acme.org
Dev
dev@acme.org
""" | openssl req -x509 -days 1000 -new -key $PRIVATE_PEM -out $PUBLIC_PEM

echo ""
echo "Creating Certificate"

openssl pkcs12 -export -in $PUBLIC_PEM -inkey $PRIVATE_PEM -out $PFX -password pass:$PASSWD
rm "${PRIVATE_PEM}"
rm "${PUBLIC_PEM}"
```

**Comment by JohnGomes** [comment]
For posterity I had some issues with the above commands in openssl.
My primary issue was passing in the password. I had to use the "-passin" argument rather than the "-password" argument.

`- Create Private PEM
    - > touch private-idsrv3test.pem
    - > genrsa 2048 > private-idsrv3test.pem
    - Copy Generated text into file
- Generate public pem from private pem for 'idsrv3test' domain
    - > req -x509 -days 1024 -new -key private-idsrv3test.pem -out public-idsrv3test.pem -subj "/C=US/CN=idsrv3test" 
- Generate pfk from pem
    - > pkcs12 -export -in public-idsrv3test.pem -inkey private-idsrv3test.pem -out idsrv3test.pfx *-passin* pass:"idsrv3test"`
