### ISSUE TITLE
Problem with mvc login after latest fast-ring windows10 update

### ISSUE THREAD

**Issue by locsius** [dotnet-architecture/eShopOnContainers#1266]
Hello - 

I'm having trouble logging in via the standard login button on the main mvc page.  It goes to the login page, but after logging in it redirects back to the login page.  Going back to the main page shows the non-logged in content.  Is anyone else having this issue?  It started causing problems 2 days ago.  If I git-clone a new instance of this project and run it, I have the same problem.  

This happens with chrome, but if I use edge the login will work if I change the docker.for.win.localhost address on the login page to just localhost.  

Regards,
scott

**Comment by mvelosop** [comment]
Hi @locsius,

That issues has to do with Chrome recent release of v80, that handles the SameSite cookie extension.

As tested in another setup the issues should be solved by upgrading IdentityServer to 3.1.1 and adding this line:

![image](https://user-images.githubusercontent.com/7357806/77349922-abb8dc00-6d33-11ea-9ffc-1cb1c6e6efba.png)

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
