### ISSUE TITLE
Video/Wiki To understand Properly the Flow of Place Order Functionality - success and unsuccess scenarios

### ISSUE THREAD

**Issue by tarunaggarwal44** [dotnet-architecture/eShopOnContainers#1268]
I am trying to learn Microservices and this seems to be a good project to really learn well. I need some help to understand properly only 1 functionality i.e. Place Order.
I really want to understand all the events and Command Handlers associated sequentially/parallely to execute success and 1 failure case. I am finding it hard to understand via debugging code. Need help with wiki though 1 video on this will solve my issue!

Thanks in advance...!!!

**Comment by sughosneo** [comment]
Hi @tarunaggarwal44 , thanks for reaching out. 

We have recently added code flow in our wiki for better understanding of few scenarios in `eShopOnContainers`. You may want to take a look and share your feedback on that.  Here is the reference : [Code Flow](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Code-Flow) 

I am closing this issue as of now. If you have any questions or feedback please feel free to reopen it.
