### ISSUE TITLE
Certificate CN=idsrv3test has expired on 01/20/2020 22:00:00

### ISSUE THREAD

**Issue by SVronskiy** [dotnet-architecture/eShopOnContainers#1270]
Hello,

I get warnings `Certificate CN=idsrv3test has expired on 01/20/2020 22:00:00` in identity pod logs.

It looks like [Certificate](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Identity/Identity.API/Certificate/idsrv3test.pfx) expired.

Just run `certutil -dump idsrv3test.pfx` with password idsrv3test to get:

```
NotAfter: 21.01.2020 5:00
```

Please fix this.

**Comment by sughosneo** [comment]
Hi @SVronskiy , we have recently updated scripts for both local k8s and AKS related deployment. Could you please take the latest and see if the issue still persist ? Here are the links for your reference 

[Local k8s](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes)
[AKS](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS))

**Comment by sughosneo** [comment]
Hi @SVronskiy, I am closing this issue as of now. Please feel free to reopen it if you have any further question.

Thank you.
