### ISSUE TITLE
AKS Helm installation -  deploy-all.ps1 "Error: unknown flag: --name" 

### ISSUE THREAD

**Issue by cchoygithub** [dotnet-architecture/eShopOnContainers#1272]
Tried AKS Helm Installation but exhibit the following errors.

<img width="812" alt="Screen Shot 2020-03-17 at 10 40 24 pm" src="https://user-images.githubusercontent.com/30440097/76852909-75e1a680-68a0-11ea-80c3-d76b480bcf3f.png">

**Comment by ajaysingh77** [comment]
@cchoygithub I also faced this issue when I tried to deploy this on the machine where only helm3 installed.  The helm code on this repository is currently targeting to version 2. 

To deploy this, using helm3 you need to change deploy-all.ps1 file.
Also, deploy-all.ps1 is missing the namespace parameter as it is provided in "deploy-all.sh" file.

I am sharing the updated deploy-all.ps1 file for your reference. I will create the pull request later.

[deploy-all.ps1.zip](https://github.com/dotnet-architecture/eShopOnContainers/files/4580692/deploy-all.ps1.zip)

**Comment by sughosneo** [comment]
Hi @cchoygithub, we have recently updated our scripts to support latest version of helm and K8s in both local and aks related deployment. Here is the wiki links for your reference. 

- [Local k8s](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes)
- [AKS](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS)) 

Could you please give it a try and see if it resolves your issue ?

Thanks.

**Comment by sughosneo** [comment]
Hi @cchoygithub , I am closing this issue as of now. If you face any challenges please feel free to reopen it.

Thank you.
