### ISSUE TITLE
How to see edited code whiel docker is running?

### ISSUE THREAD

**Issue by neoAnkit** [dotnet-architecture/eShopOnContainers#1274]
The code takes 30-40 minutes to run. How can i ensure that any code changes are immediately reflected in docker container? I am running code from command prompt but editing is done via VS 2019.

**Comment by neoAnkit** [comment]
Any comments?

**Comment by mvelosop** [comment]
@neoAnkit, how much memory does you computer have and how much assigned to Docker? Compared to [this section in the wiki page](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#memory-and-cpu)?

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
