### ISSUE TITLE
Facing issue while running MVC application . Response status code does not indicate success: 500 (Internal Server Error).

### ISSUE THREAD

**Issue by neoAnkit** [dotnet-architecture/eShopOnContainers#1276]
An unhandled exception occurred while processing the request.
HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()

System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
System.Net.Http.HttpClient.GetStringAsyncCore(Task<HttpResponseMessage> getTask)
Microsoft.eShopOnContainers.WebMVC.Services.CatalogService.GetCatalogItems(int page, int take, Nullable<int> brand, Nullable<int> type) in CatalogService.cs
Microsoft.eShopOnContainers.WebMVC.Controllers.CatalogController.Index(Nullable<int> BrandFilterApplied, Nullable<int> TypesFilterApplied, Nullable<int> page, string errorMsg) in CatalogController.cs
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by rohinipangrikar** [comment]
I am facing the same issue. I am running on a Mac.

**Comment by mvelosop** [comment]
@neoAnkit how are you running the application?

**Comment by srajagopal1983** [comment]
I'm facing the same issue, running in window 10. I'm using Docker Desktop v2.2.0.3. I'm running the application from command line (Git Bash) following the [instructions](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#optional---use-visual-studio) on docker-compose build and docker-compose up. 

In heath check status UI page, the following three items are showing unhealthy status. 

1. Web Shopping Aggregator GW HTTP Check (catalogapi-check | errorUnhealthy | Discover endpoint #0 is not responding with code in 200...299 range, the current status is ServiceUnavailable.)
2. Mobile Shopping Aggregator HTTP Check (catalogapi-check | errorUnhealthy | Discover endpoint #0 is not responding with code in 200...299 range, the current status is ServiceUnavailable.)
3. Catalog HTTP Check (CatalogDB-check | errorUnhealthy | Cannot open database "Microsoft.eShopOnContainers.Services.CatalogDb" requested by the login. The login failed. Login failed for user 'sa'.)

**Comment by neoAnkit** [comment]
> I'm facing the same issue, running in window 10. I'm using Docker Desktop v2.2.0.3. I'm running the application from command line (Git Bash) following the [instructions](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#optional---use-visual-studio) on docker-compose build and docker-compose up.
> 
> In heath check status UI page, the following three items are showing unhealthy status.
> 
> 1. Web Shopping Aggregator GW HTTP Check (catalogapi-check | errorUnhealthy | Discover endpoint #0 is not responding with code in 200...299 range, the current status is ServiceUnavailable.)
> 2. Mobile Shopping Aggregator HTTP Check (catalogapi-check | errorUnhealthy | Discover endpoint #0 is not responding with code in 200...299 range, the current status is ServiceUnavailable.)
> 3. Catalog HTTP Check (CatalogDB-check | errorUnhealthy | Cannot open database "Microsoft.eShopOnContainers.Services.CatalogDb" requested by the login. The login failed. Login failed for user 'sa'.)

Run it from VS 2019. Even seeding does not happen many times from command prompt. Also you will have to wait for 30 minutes before accessing websites. Its this damn slow

**Comment by srajagopal1983** [comment]
Thanks @neoAnkit . When I run from VS2019, I get the below error **503**. 

HttpRequestException: Response status code does not indicate success: **503** (Service Unavailable).
System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
System.Net.Http.HttpClient.GetStringAsyncCore(Task<HttpResponseMessage> getTask)
Microsoft.eShopOnContainers.WebMVC.Services.CatalogService.GetCatalogItems(int page, int take, Nullable<int> brand, Nullable<int> type) in CatalogService.cs
Microsoft.eShopOnContainers.WebMVC.Controllers.CatalogController.Index(Nullable<int> BrandFilterApplied, Nullable<int> TypesFilterApplied, Nullable<int> page, string errorMsg) in CatalogController.cs
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by neoAnkit** [comment]
looks liek data is not seeded. Did you wait for 30 minutes before accessing website? if yes, then check data in sql server container. 

You may need to create database manually in many cases. attaching script file for your reference.
[Database backup.zip](https://github.com/dotnet-architecture/eShopOnContainers/files/4386760/Database.backup.zip)

also attaching document containing all the analysis i could do till now:-
[microservice snippets.docx](https://github.com/dotnet-architecture/eShopOnContainers/files/4386767/microservice.snippets.docx)

**Comment by srajagopal1983** [comment]
Thanks again @neoAnkit . Yes, i was trying immediately after the setup. Now, its working.

**Comment by mvelosop** [comment]
Hi @neoAnkit are you assigning 6 GB RAM to Docker?

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.

**Comment by dalianhank** [comment]
I got the same error on Mac for MVC and the health check got an error for Identityapi-check, SPA is run but not login. the sql data is seeded.

![image](https://user-images.githubusercontent.com/2449823/93930467-46d64280-fcd2-11ea-8077-10ab1a5b217a.png)
![image](https://user-images.githubusercontent.com/2449823/93935907-34600700-fcda-11ea-9562-bfb27de0938a.png)
![image](https://user-images.githubusercontent.com/2449823/93935958-50fc3f00-fcda-11ea-8ca5-c2516fbde5c9.png)
![image](https://user-images.githubusercontent.com/2449823/93936092-7d17c000-fcda-11ea-90fe-2db8c3f276de.png)



I try to Visual Studio to run and all Health checks are good, but the same problem for MVC and the SPA can't be found.


![image](https://user-images.githubusercontent.com/2449823/93930811-c82dd500-fcd2-11ea-8d5d-ddc79421a3ea.png)
![image](https://user-images.githubusercontent.com/2449823/93930840-d4b22d80-fcd2-11ea-9972-e25f4ad68526.png)

**Comment by dalianhank** [comment]
I set the chrome "SameSite by default cookie" to disable and SPA can login and run normal, MVC app still has same issue.
![Screen Shot 2020-09-24 at 11 50 25 AM](https://user-images.githubusercontent.com/2449823/94186952-2934e480-fe5c-11ea-92a0-7cd65f6dee05.png)

Meanwhile, I made my Mac run Win10 and everything is working.

**Comment by dalianhank** [comment]
I figured out the issue, the "_docker-compose.override.yml_"  -- webmvc part should be following:

webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PurchaseUrl=http://webshoppingapigw
      - IdentityUrl=http://docker.for.mac.localhost:5105
      - MarketingUrl=http://webmarketingapigw
      - SignalrHubUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5202
      - IdentityUrlHC=http://identity-api/hc
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "5100:80"

Meanwhile on the "chrome://flags" -- "SameSite by default cookies" should be **disabled**

**Comment by sughosneo** [comment]
> I figured out the issue, the "_docker-compose.override.yml_" -- webmvc part should be following:
> 
> webmvc:
> environment:
> - ASPNETCORE_ENVIRONMENT=Development
> - ASPNETCORE_URLS=http://0.0.0.0:80
> - PurchaseUrl=http://webshoppingapigw
> - IdentityUrl=http://docker.for.mac.localhost:5105
> - MarketingUrl=http://webmarketingapigw
> - SignalrHubUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5202
> - IdentityUrlHC=http://identity-api/hc
> - UseCustomizationData=True
> - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
> - OrchestratorType=${ORCHESTRATOR_TYPE}
> - UseLoadTest=${USE_LOADTEST:-False}
> ports:
> - "5100:80"
> 
> Meanwhile on the "chrome://flags" -- "SameSite by default cookies" should be **disabled**

Hi @dalianhank , thank you for reaching out.  SameSite related behavior is documented in our [wiki page](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Frequent-errors#login-page---exception-correlation-failed)

Thanks.

**Comment by dalianhank** [comment]
Hi @sughosneo 

Thanks for replying.

I am not sure the [wiki page](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Mac-setup) about **Mac setup** for "_**docker-compose.override.yml"**_  is right.
![Screen Shot 2020-09-25 at 9 28 26 AM](https://user-images.githubusercontent.com/2449823/94292242-8ccd1980-ff11-11ea-92f6-ec6f81df57b5.png)

I think the "- CatalogUrl=http://catalog.api" should be either "- CatalogUrl=http://catalog-api" or "- CatalogUrl=http://docker.for.mac.localhost:5101".

Could you check those YML file settings really working for Mac? If not, the instruction may need update.

My MacOS -Catalina Version 10.15.6
