### ISSUE TITLE
Refused to load the script 'http://host.docker.internal:5105/lib/jquery/jquery.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

### ISSUE THREAD

**Issue by neoAnkit** [dotnet-architecture/eShopOnContainers#1278]
Got this error after changing .env file and clientredirecturls to "host.docker.internal". This change I did was to fix "clieent_autherror" issue.

"Refused to load the script 'http://host.docker.internal:5105/lib/jquery/jquery.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback."

**Comment by Vampire2008** [comment]
I don't know why, but it isn't work for me.
Same error. Dev branch. No manual changes in code. Launch using Visual Studio 2019 (16.7.1).
Chrome: 84.0.4147.125
Docker for Windows: 2.3.0.4

Code from Pull Request on it's position.

**Comment by ronikurnia1** [comment]
Same issue here:

`Refused to load the script 'http://host.docker.internal:5105/lib/jquery/jquery.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
`
Dev branch
VS 2019 Version 16.8.0 Preview 2.1
MS Edge Version 85.0.564.44  
Docker Desktop 2.3.0.4

**Comment by ducanhdinh** [comment]
somebody help me to resolve error login

**Comment by sughosneo** [comment]
> Yesterday i have known project and pulled code lates version. somebody help me to resolve error login
> ![image](https://user-images.githubusercontent.com/42025857/95723076-ef0e7400-0c9e-11eb-99b7-a3229ea24fe1.png)

Hi @ducanhdinh , thank you for reaching out. 

Did you get a chance to look into the [unauthorized_client error on Login](https://github.com/dotnet-architecture/eShopOnContainers/wiki/unauthorized_client-error-on-login) ? Also, you need to use below urls while accessing the applications.

Web MVC : http://host.docker.internal:5100/
Web SPA : http://host.docker.internal:5104/

**Comment by ducanhdinh** [comment]
thank you for reply my comment, so i have done to your instruction, 
![image](https://user-images.githubusercontent.com/42025857/95739149-90ec8b80-0cb4-11eb-929a-0be918e11470.png) after program alert 
![image](https://user-images.githubusercontent.com/42025857/95739186-a2359800-0cb4-11eb-9b41-056715b93b54.png)
i hope you give me a hand!

**Comment by sughosneo** [comment]
> thank you for reply my comment, so i have done to your instruction,
> ![image](https://user-images.githubusercontent.com/42025857/95739149-90ec8b80-0cb4-11eb-929a-0be918e11470.png) after program alert
> ![image](https://user-images.githubusercontent.com/42025857/95739387-f8a2d680-0cb4-11eb-864c-f8bd628ec75f.png)
> 
> i hope you give me a hand!

Thanks for the update @ducanhdinh . Here is the link for [Login page - Exception: Correlation failed](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Frequent-errors#login-page---exception-correlation-failed)

Hope this helps !

**Comment by ducanhdinh** [comment]
Thank you very much! After configured on Chrome issue Cross domain, i was reset my pc and completed!
