### ISSUE TITLE
Login failed with default username and password

### ISSUE THREAD

**Issue by andyle83** [dotnet-architecture/eShopOnContainers#1280]
I have build and run the application successfully. The website can display list of items, and login page via address: http://docker.for.win.localhost:5100/ (Homepage) and http://docker.for.win.localhost:5105/Account/Login (Login page). Afterward, I was using default username and password (User: demouser@microsoft.com / Password: Pass@word1) to login. The authentication failed with error message returned "Invalid username or password.". Lookin the logs from service eshop/identity.api, I found this

[17:49:38 INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeEndpoint for /connect/authorize

[17:49:38 INF] Showing login: User is not authenticated
[17:49:38 ERR] An exception was thrown while deserializing the token.
[17:50:05 INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeEndpoint for /connect/authorize
[17:50:05 INF] Showing login: User is not authenticated
[17:50:05 ERR] An exception was thrown while deserializing the token.
[17:51:11 WRN] Invalid password for user d86a8ae5-547e-42c8-bfc4-85da9314c79c.

Anyone can suggest an idea about the fail reason and approach to fix this one?

**Comment by mvelosop** [comment]
Hi @andyle83,

Please try from an InPrivate browser window or clear all cookies.

Hope this helps.

**Comment by andyle83** [comment]
> Hi @andyle83,
> 
> Please try from an InPrivate browser window or clear all cookies.
> 
> Hope this helps.

Thanks you. I did use this one but no luck.

**Comment by mertker** [comment]
same error

![image](https://user-images.githubusercontent.com/24223180/77822309-901e4e80-7102-11ea-90cd-9a29fc51db0e.png)

![image](https://user-images.githubusercontent.com/24223180/77822314-98768980-7102-11ea-9cd0-90734dd5714b.png)

**Comment by andyle83** [comment]
I got the same error log as @mertker mentioned. Checked in the table and saw the account demouser is existed.

**Comment by mertker** [comment]
Open cmd

cd C:\Program Files (x86)\Google\Chrome\Application
chrome.exe --disable-web-security --user-data-dir=c:\my-chrome-data\data

I logged in from the opened browser
I think the problem is caused by cookies

does not allow to write samesite = none to chrome cookie without ssl

**Comment by mvelosop** [comment]
Hi @andyle83,

This is related to the recent Chrome 80 release, please take a look at [this comment](https://github.com/dotnet-architecture/eShopOnContainers/issues/1266#issuecomment-602776622), while the code is updated.

Hope this helps.

**Comment by aarondglover** [comment]
This works with Microsoft Edge Browser. I'm using Version 80.0.361.69 (Official build) (64-bit)
But I get the same error as described above if I use chrome. Also Incognito mode doesn't help.

**Comment by mvelosop** [comment]
Hi @aarondglover,

The issue is related to not using https for the Identity microservice.

One possible solution is the one I mentioned in the comment, that is Upgrading IdentityServer to 3.1.1 and add this line in Startup.cs:

![](https://user-images.githubusercontent.com/7357806/77349922-abb8dc00-6d33-11ea-9ffc-1cb1c6e6efba.png)

The other solution is installing a dev certificate in the identity microservice.

Just yesterday I was trying out the procedure described in the article: [Hosting ASP.NET Core images with Docker Compose over HTTPS](https://docs.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-3.1) and it looks like it could be a good solution for test/dev environment.

Hope this helps.

**Comment by j-dhall** [comment]
The following **worked for me**.

I tried the following in **Advanced REST Client by MuleSoft**:

**POST**: http://**localhost:5105**
Headers: Content-Type: **application/json**
Body:
{
  "email": "demouser@microsoft.com",
  "password": "**Pass@word1**"
}
