### ISSUE TITLE
Local Kubernetes deployment, WebStatus, WebMVC & WebSPA not accesible

### ISSUE THREAD

**Issue by sanjinbecirovic** [dotnet-architecture/eShopOnContainers#1281]
Hello, great work on the eShopOnContainers solution!

I ran in a bit of a trouble setting up the local kubernetes deployment. I am running a Windows 10, with docker-desktop instance running kubernetes. The deployment succeds, and all the pods & services are running correctly, according go the kubernetes dashboard. However, the status endpoint returns 404, mvc and spa endpoints cant be reached. (pinged). The logs from ingress controllers, and screenshots of the ingresses are attached. My guess is that something is wrong with the ingress networking.

[ingress-controllers-logs.txt](https://github.com/dotnet-architecture/eShopOnContainers/files/4397045/ingress-controllers-logs.txt)

<img width="548" alt="webstatus-ing" src="https://user-images.githubusercontent.com/7047868/77822286-a1129400-70f1-11ea-8dad-9027af6d58e4.png">
<img width="568" alt="webmvc-ing" src="https://user-images.githubusercontent.com/7047868/77822287-a1ab2a80-70f1-11ea-9121-9304d51d0063.png">
<img width="530" alt="webspa-ing" src="https://user-images.githubusercontent.com/7047868/77822288-a243c100-70f1-11ea-93f9-de6dd88b6155.png">
<img width="487" alt="ing-overview" src="https://user-images.githubusercontent.com/7047868/77822307-cacbbb00-70f1-11ea-858a-3289a4e09605.png">

I was able to access the webstatus and webspa by creating NodePorts, the screenshots are attached: 
<img width="749" alt="health-checks" src="https://user-images.githubusercontent.com/7047868/77822624-c5bc3b00-70f4-11ea-8d85-03509075e6fe.png">
<img width="899" alt="webspa" src="https://user-images.githubusercontent.com/7047868/77822627-cbb21c00-70f4-11ea-8e86-df3f57650517.png">

Help appreciated.
Thanks!

**Comment by amroSaad78** [comment]
I have same problem on **AKS** also.

**Comment by mvelosop** [comment]
Hi @sanjinbecirovic, @amroSaad78,

Can you check the requests using the devtools in the browser?

**Comment by sughosneo** [comment]
Hi @sanjinbecirovic , we have recently updated our scripts to support latest version of K8s in both local and aks related deployment.  If you could give that a try and see if that resolves your issue.

Here is the link of the [wiki page](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes)

Thanks.

**Comment by VuongTrinh** [comment]
Hi @sanjinbecirovic , have you figured out how to solve the problem yet or just about to give up like me?
Hi @sughosneo , i still have exactly problem on both local k8s and AKS, following [wiki page](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes)

**Comment by sughosneo** [comment]
Hi @VuongTrinh, thanks for the update. could you please share more information on following items ?

- **local k8s :**
    - Which urls are you using to browse WebSPA, WebStatus and WebMVC ?
    - Have you already followed the steps mentioned in [known behaviours](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes#known-behaviours) ?

- **AKS:**
    - What's the output of `kubectl get ing` ?
    - Which urls are you using to browse WebSPA, WebStatus and WebMVC ?
    - If you could confirm that if you have set `http_application_routing` for the cluster ?
    - Have you already followed the steps mentioned in [known behaviours](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS)#known-behaviours) ?

**Comment by sughosneo** [comment]
Hi @VuongTrinh , did you get a chance to look into the above information ?

**Comment by sughosneo** [comment]
Hello Everyone, I am closing this issue as of now. Please feel free to reopen if anyone has any further question.

Thank you.

**Comment by n-stefan** [comment]
If everything else fails, "Reset Kubernetes Cluster" in Docker settings might help.
