### ISSUE TITLE
 Release failed: ConfigMap in version "v1" cannot be handled as a ConfigMap

### ISSUE THREAD

**Issue by davliu82** [dotnet-architecture/eShopOnContainers#1295]
Follow the [guidance ](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS)) to deploy eShop on my AKS cluster.

**Kubectl version**:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"150f36044fe31bee3891b5a3fae69c17237e022c", GitTreeState:"clean", BuildDate:"2020-02-21T10:02:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Repro**: 

Running the below Powershell command on my PC:
_.\deploy-all.ps1 -externalDns eshop.xxx.eastasia.aksapp.io -aksName xxx -aksRg xxx -imageTag dev -useMesh $false_

**Error**: 

release eshop-apigwws failed: ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects " or n, but found {, error found in #10 byte of ...|{"admin":{"access_lo|..., bigger context ...|{"apiVersion":"v1","data":{"admin":{"access_log_path":"/dev/null","address":{"socket_a|...

release eshop-apigwms failed: ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects " or n, but found {, error found in #10 byte of ...|{"admin":{"access_lo|..., bigger context ...|{"apiVersion":"v1","data":{"admin":{"access_log_path":"/dev/null","address":{"socket_a|...

![image](https://user-images.githubusercontent.com/8144963/78812263-b6df5d80-79fd-11ea-8d8c-0c6d5ed48998.png)

![image](https://user-images.githubusercontent.com/8144963/78812330-d1193b80-79fd-11ea-8ae4-9b14a27ecd31.png)

**Comment by davliu82** [comment]
I just tried KubeCtl version 1.16.1. It doesn't work as well.

**Comment by arupmaity** [comment]
was this resolve already? I am encountering the same issue.

**Comment by ahladh** [comment]
I also encounter same issue.

**Comment by noahjd** [comment]
I am also encountering the same issue, what was the fix?
