### ISSUE TITLE
Login failed for user 'sa'.

### ISSUE THREAD

**Issue by riegelj** [dotnet-architecture/eShopOnContainers#1297]
I'm running windows 10 and new to dockers. I have 24GB of memory on my machine. I tried increasing the memory resources to 9 GB same issue. The dentityDB-check fails with:

Cannot open database "Microsoft.eShopOnContainers.Service.IdentityDb" requested by the login. The login failed. Login failed for user 'sa'.

I am able to login using SQL Server Management Studio with sa

**Comment by SamuelD28** [comment]
I had the same issue and endep up just restarting the containers with docker-compose. The issue fixed itself afterwards, im guessing maybe a seed or cache thing. I don't know if it helps you but give it a try.

**Comment by mvelosop** [comment]
Hi @riegelj, thanks for the feedback.

There might've been an issue creating and seeding the database and it might've ended in an corrupted state.

Try connecting to the DB in the container with SQL Server Management Studio, to `localhost,5433`:

![image](https://user-images.githubusercontent.com/7357806/79225015-01c10100-7e54-11ea-9105-5433dd35de4a.png)

And deleting the Identity DB, so it gets created the next time.

Hope this helps.

**Comment by riegelj** [comment]
There isn’t an IdentityDb in my list

**Comment by riegelj** [comment]
Thanks, tried that didn’t help.

**Comment by mvelosop** [comment]
Could you please post the output of the `docker info` command?

**Comment by riegelj** [comment]
Here you go. Thanks for your help.

 

PS C:\users\jriegel\Source\Repos\eShopOnContainers\src> docker info

Client:

Debug Mode: false

 

Server:

Containers: 25

  Running: 0

  Paused: 0

  Stopped: 25

Images: 133

Server Version: 19.03.8

Storage Driver: overlay2

  Backing Filesystem: <unknown>

  Supports d_type: true

  Native Overlay Diff: true

Logging Driver: json-file

Cgroup Driver: cgroupfs

Plugins:

  Volume: local

  Network: bridge host ipvlan macvlan null overlay

  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog

Swarm: inactive

Runtimes: runc

Default Runtime: runc

Init Binary: docker-init

containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429

runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd

init version: fec3683

Security Options:

  seccomp

   Profile: default

Kernel Version: 4.19.76-linuxkit

Operating System: Docker Desktop

OSType: linux

Architecture: x86_64

CPUs: 2

Total Memory: 5.809GiB

Name: docker-desktop

ID: 3TX3:HQZA:INHX:VTAR:6AME:O2AO:ETLX:R4FA:W654:ZXPM:QKFK:I74B

Docker Root Dir: /var/lib/docker

Debug Mode: true

  File Descriptors: 38

  Goroutines: 58

  System Time: 2020-04-14T15:52:23.79080487Z

  EventsListeners: 5

Registry: https://index.docker.io/v1/

Labels:

Experimental: false

Insecure Registries:

  127.0.0.0/8

Live Restore Enabled: false

Product License: Community Engine

**Comment by mvelosop** [comment]
hmmm, I don't get to see anything suspicious there.

Try starting up only the Identity service, to check if the DB gets created, with the command.

```
docker-compose up identity-api
```

**Comment by riegelj** [comment]
That created the identityDb. I no longer get the error with SA Thank You! 

 



 

I am now failing the health check for these areas. I can log a new issue if you like.

**Comment by riegelj** [comment]
I stopped and restarted everything. It’s all green now. Thanks for all your help.

 

From: Jeff Riegel <jeffr7792@gmail.com> On Behalf Of Jeff Riegel
Sent: Wednesday, April 15, 2020 5:43 AM
To: 'dotnet-architecture/eShopOnContainers' <reply@reply.github.com>; 'dotnet-architecture/eShopOnContainers' <eShopOnContainers@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [dotnet-architecture/eShopOnContainers] Login failed for user 'sa'. (#1297)

 

That created the identityDb. I no longer get the error with SA Thank You! 

 



 

I am now failing the health check for these areas. I can log a new issue if you like.

**Comment by riegelj** [comment]
I stopped and restarted everything. It’s all green now. Thanks for all your help.

**Comment by mvelosop** [comment]
Glad to know that helped 😊

Cheers.

**Comment by robertocg72** [comment]
I was having the same problem and executing `docker-compose up identity-api` before executing `docker-compose up` fixed the problem

Thanks!
