### ISSUE TITLE
Settings on domain or application level

### ISSUE THREAD

**Issue by HighRobot42** [dotnet-architecture/eShopOnContainers#1299]
Would it be safe to move MarketingSettings (or any of this kind) to the domain or application level in order to retrieve some of its properties at those levels?
In my case I would need the PicBaseUrl property value at application level.

**Comment by mvelosop** [comment]
Hi @HighRobot42,

I'm afraid I can't give a meaningful answer here, b/c it's a too general question not related to eShopOnContainers, so you'd have to give it a try.

Anyway, you can always duplicate the config to make sure nothing breaks, perhaps it's the safest.

Hope this helps.

**Comment by mvelosop** [comment]
Closing as not related to eShopOnContainers.
