### ISSUE TITLE
Configuration : Error with starting Envoy Proxy

### ISSUE THREAD

**Issue by SamuelD28** [dotnet-architecture/eShopOnContainers#1300]
Hi, I have been trying to start the entire cluster for a couple days now but i keep getting an error at startup with the Envoy Proxy service. Everything else is starting without a problem.

`mobilemarketingapigw_1      | [2020-04-14 15:31:21.571][1][info][main] [source/server/server.cc:560] exiting
mobilemarketingapigw_1      | Invalid path: /etc/envoy/envoy.yaml`

I am using Docker Toolbox since i don't have a Windows Pro license. The error is pretty straightforward yet i don't really know how to debug this. If somebody could just point me in a direction on how to approach the issue that would be great. 

Thanks in advance!

**Comment by sughosneo** [comment]
Hi @SamuelD28 , we have recently updated our scripts to support latest version of K8s in both local and aks related deployment.
Here is the [wiki](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes) reference for local **k8s** related deployment. Could you please give it a try and see if that helps ?

In case if you are using only docker environment then you can just run `docker-compose` up in the `src` directory for running all the containers with default setting. For more details, please refer this [link](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Docker-compose-deployment-files)

Thanks.

**Comment by sughosneo** [comment]
Hi @SamuelD28 , Closing this issue as of now but feel free to comment, will reopen if needed.

Thank you.
