### ISSUE TITLE
Set up and debug this application is VS code

### ISSUE THREAD

**Issue by vish02chouhan** [dotnet-architecture/eShopOnContainers#1301]
Hi,

I have faced a couple of problems while setting up and debugging this application. Could anyone please help me with that

1) Visual Studio 2017 - This application is now not supporting VS2017 because VS 2017 do not support  dotnet core > 3

2) Visual Studio Code -I am not able to debug this application in Visual Studio Code. Is there any detailed document how I could run and debug this application via VS code

Thanks,
Vishwajeet

**Comment by ArashSade** [comment]
Have you read this https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup

**Comment by mvelosop** [comment]
Hi, @vish02chouhan, thanks for the feedback.

Right now I'm working on documenting the process for using Docker with VS Code, not really for eShop now, but will use whatever I find to update the wiki.

At least I expect to be in much better position to help you during this week.

Cheers,

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
