### ISSUE TITLE
Content Security Policy error

### ISSUE THREAD

**Issue by riegelj** [dotnet-architecture/eShopOnContainers#1302]
Clicking the login link produces the following Content Security Policy error in Chrome Version 81.0.4044.92 (Official Build) (64-bit):

Refused to load the script 'http://docker.for.win.localhost:5105/lib/jquery/jquery.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

I tried IE and Edge which don't display images seems they don't like the http://docker.for.win. in front of the localost:5105 remove the docker.for.win on the login page url in Edge produce the same unauthorized_client error
![2020-04-15_8-14-53](https://user-images.githubusercontent.com/3922626/79336277-739b5800-7ef1-11ea-8f49-e482ae22c6fc.jpg)

**Comment by mvelosop** [comment]
Hi @riegelj,

That's something we are working on now.

However, the Edge browser should work just fine, even with the docker.for.win.localhost, that's the first one I use to test.

Anyway, you can try using http://host.docker.internal, but you'll have to drop and create the Identity DB, as explained in the [unauthorized_client error on Login
](https://github.com/dotnet-architecture/eShopOnContainers/wiki/unauthorized_client-error-on-login) wiki page.

Hope this helps.

**Comment by mvelosop** [comment]
BTW, the CSP issue should not stop you from logging in.

**Comment by riegelj** [comment]
Interesting, then I have another problem because login produces a Sorry, there was an error : unauthorized_client error. These all look to be CSP related, but I thought I would share just in case.

**Comment by mvelosop** [comment]
Please, let me know if the  [unauthorized_client error on Login
](https://github.com/dotnet-architecture/eShopOnContainers/wiki/unauthorized_client-error-on-login) wiki page is clear enough and helped you.

**Comment by riegelj** [comment]
Thanks for all your help!

 

I think I got it, but my request_uri is different than in the page however,mine has the sigin-oidc appended to it.

 

NOTE: I am running docker-compose up from  PS C:\users\jriegel\Source\Repos\eShopOnContainers\src> which is the location of the .env file

 

redirect_uri: http://localhost:5100/signin-oidc

 



 

 

I tried both http://docker.for.win.localhost:5110 and http://docker.for.win.localhost:5110/ signin-oidc for clientid 1 and neither worked.

 



 

Docker-compose.override.yml -> MvcClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5100

 



 

.env file

**Comment by riegelj** [comment]
I found this in the identity log. My question is why is my request http://localhost:5100/signin-oidc and not http://docker.for.win.localhost:5100/signin-oidc I clicked on the link this link from the github page to launch it:

 

At this point you should be able to navigate to  <http://localhost:5107/> http://localhost:5107/ and see the WebStatus microservice:

 

I guess I’m missing understanding how the docker.for.win. gets attached to the request.

 

[11:42:08 ERR] Invalid redirect_uri: http://localhost:5100/signin-oidc

{

                "ClientId" : "mvc",

                "ClientName" : "MVC Client",

                "RedirectUri" : null,

                "AllowedRedirectUris" : [

                                "http://docker.for.win.localhost:5100/signin-oidc"

                ],

                "SubjectId" : "anonymous",

                "ResponseType" : null,

                "ResponseMode" : null,

                "GrantType" : null,

                "RequestedScopes" : "",

                "State" : null,

                "UiLocales" : null,

                "Nonce" : null,

                "AuthenticationContextReferenceClasses" : null,

                "DisplayMode" : null,

                "PromptMode" : null,

                "MaxAge" : null,

                "LoginHint" : null,

                "SessionId" : null,

                "Raw" : {

                                "client_id" : "mvc",

                                "redirect_uri" : "http://localhost:5100/signin-oidc",

                                "response_type" : "code id_token",

                                "scope" : "openid profile orders basket marketing locations webshoppingagg orders.signalrhub",

                                "response_mode" : "form_post",

                                "nonce" : "637228069276452932.NWZiYjVjZmMtMGI3NS00Y2NjLWE3MWMtZmQ4NDlkMDJkMzgxZTcyZTllYzktYWM4NC00ZmVlLWI5OTYtOTU0MzkyYjAwZTA4",

                                "state" : "CfDJ8PKAFwiLWAlBhqP6rfRpSrsdv6SH1Epms-uHs1z88ay0y1xKZDQoYt7Mid237-1_YIFK11MHW9-znfAp2dG6tYDw6gdo9IabFHDSEx4p8ClBPPbYw2jqkoUiYplotNSGfBz6sLLYnlYRXOU6CJJdOxf5BiJGOYfBzuGt7mIhpqfwnbnimlmFq1---ntmuQoUu746yLbWxvPTlyDPjsl_f6-V4XOXP1aHvYvD-XJ0LWvGtUafhv0wOIY6GP-emqB10VtOtFNca7Z2CBCY6YBpOAkD60aJ2AxBZAcFPIWwgZVfoTeqkihmr-K1IKAlQBsHZg",

                                "x-client-SKU" : "ID_NETSTANDARD2_0",

                                "x-client-ver" : "5.5.0.0"

                },

                "$type" : "AuthorizeRequestValidationLog"

}

 

From: Jeff Riegel <jeffr7792@gmail.com> On Behalf Of Jeff Riegel
Sent: Friday, April 17, 2020 9:06 AM
To: 'dotnet-architecture/eShopOnContainers' <reply@reply.github.com>; 'dotnet-architecture/eShopOnContainers' <eShopOnContainers@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [dotnet-architecture/eShopOnContainers] Content Security Policy error (#1302)

 

Thanks for all your help!

 

I think I got it, but my request_uri is different than in the page however,mine has the sigin-oidc appended to it.

 

NOTE: I am running docker-compose up from  PS C:\users\jriegel\Source\Repos\eShopOnContainers\src> which is the location of the .env file

 

redirect_uri: http://localhost:5100/signin-oidc

 



 

 

I tried both http://docker.for.win.localhost:5110 and http://docker.for.win.localhost:5110/ signin-oidc for clientid 1 and neither worked.

 



 

Docker-compose.override.yml -> MvcClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5100

 



 

.env file

**Comment by riegelj** [comment]
I resolved my login problem by adding http://localhost:5100/signin-oidc to the ClientRedirectUris table with a ClientId value of 3 – Note sure if this was the correct way to fix it, but it worked for me.

 



 

From: Jeff Riegel <jeffr7792@gmail.com> On Behalf Of Jeff Riegel
Sent: Saturday, April 18, 2020 8:03 AM
To: 'dotnet-architecture/eShopOnContainers' <reply@reply.github.com>; 'dotnet-architecture/eShopOnContainers' <eShopOnContainers@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [dotnet-architecture/eShopOnContainers] Content Security Policy error (#1302)

 

I found this in the identity log. My question is why is my request http://localhost:5100/signin-oidc and not http://docker.for.win.localhost:5100/signin-oidc I clicked on the link this link from the github page to launch it:

 

At this point you should be able to navigate to  <http://localhost:5107/> http://localhost:5107/ and see the WebStatus microservice:

 

I guess I’m missing understanding how the docker.for.win. gets attached to the request.

 

[11:42:08 ERR] Invalid redirect_uri: http://localhost:5100/signin-oidc

{

                "ClientId" : "mvc",

                "ClientName" : "MVC Client",

                "RedirectUri" : null,

                "AllowedRedirectUris" : [

                                "http://docker.for.win.localhost:5100/signin-oidc"

                ],

                "SubjectId" : "anonymous",

                "ResponseType" : null,

                "ResponseMode" : null,

                "GrantType" : null,

                "RequestedScopes" : "",

                "State" : null,

                "UiLocales" : null,

                "Nonce" : null,

                "AuthenticationContextReferenceClasses" : null,

                "DisplayMode" : null,

                "PromptMode" : null,

                "MaxAge" : null,

                "LoginHint" : null,

                "SessionId" : null,

                "Raw" : {

                                "client_id" : "mvc",

                                "redirect_uri" : "http://localhost:5100/signin-oidc",

                                "response_type" : "code id_token",

                                "scope" : "openid profile orders basket marketing locations webshoppingagg orders.signalrhub",

                                "response_mode" : "form_post",

                                "nonce" : "637228069276452932.NWZiYjVjZmMtMGI3NS00Y2NjLWE3MWMtZmQ4NDlkMDJkMzgxZTcyZTllYzktYWM4NC00ZmVlLWI5OTYtOTU0MzkyYjAwZTA4",

                                "state" : "CfDJ8PKAFwiLWAlBhqP6rfRpSrsdv6SH1Epms-uHs1z88ay0y1xKZDQoYt7Mid237-1_YIFK11MHW9-znfAp2dG6tYDw6gdo9IabFHDSEx4p8ClBPPbYw2jqkoUiYplotNSGfBz6sLLYnlYRXOU6CJJdOxf5BiJGOYfBzuGt7mIhpqfwnbnimlmFq1---ntmuQoUu746yLbWxvPTlyDPjsl_f6-V4XOXP1aHvYvD-XJ0LWvGtUafhv0wOIY6GP-emqB10VtOtFNca7Z2CBCY6YBpOAkD60aJ2AxBZAcFPIWwgZVfoTeqkihmr-K1IKAlQBsHZg",

                                "x-client-SKU" : "ID_NETSTANDARD2_0",

                                "x-client-ver" : "5.5.0.0"

                },

                "$type" : "AuthorizeRequestValidationLog"

}

 

From: Jeff Riegel <jeffr7792@gmail.com <mailto:jeffr7792@gmail.com> > On Behalf Of Jeff Riegel
Sent: Friday, April 17, 2020 9:06 AM
To: 'dotnet-architecture/eShopOnContainers' <reply@reply.github.com <mailto:reply@reply.github.com> >; 'dotnet-architecture/eShopOnContainers' <eShopOnContainers@noreply.github.com <mailto:eShopOnContainers@noreply.github.com> >
Cc: 'Mention' <mention@noreply.github.com <mailto:mention@noreply.github.com> >
Subject: RE: [dotnet-architecture/eShopOnContainers] Content Security Policy error (#1302)

 

Thanks for all your help!

 

I think I got it, but my request_uri is different than in the page however,mine has the sigin-oidc appended to it.

 

NOTE: I am running docker-compose up from  PS C:\users\jriegel\Source\Repos\eShopOnContainers\src> which is the location of the .env file

 

redirect_uri: http://localhost:5100/signin-oidc

 



 

 

I tried both http://docker.for.win.localhost:5110 and http://docker.for.win.localhost:5110/ signin-oidc for clientid 1 and neither worked.

 



 

Docker-compose.override.yml -> MvcClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5100

 



 

.env file

**Comment by mvelosop** [comment]
Glad to know 😊

The key point here is that whatever way you start you app, be it localhost:5100, docker.for.win.localhost:5100, or host.docker.internal:5100, the redirect uri in Identity DB is referencing the same host.

All of the hosts above should be valid for running the app.

**Comment by riegelj** [comment]
Thanks, Now working on trying to figure out how to debug into services using visual studio code. I installed Docker and Remote-Containers. I’ve been able to start everything from VSCode if you know of any good sources for debugging .Net in containers for VS CODE let me know. I’ll share what I learn.

**Comment by mvelosop** [comment]
I'm working on using VS Code with Docker, will post whatever I find. 😊
