### ISSUE TITLE
[Question] Processing incoming API calls and Integration events on a seperate process

### ISSUE THREAD

**Issue by TheoMcCabe** [dotnet-architecture/eShopOnContainers#1306]
Hi guys, 

Thanks for this repo, it's awesome! Quick question here on production optimised deployments (I know that's not the main focus, but hope you can help)

If I understand correctly, within a microservice you are processing incoming HTTP calls and incoming integration events in the same 'x.API' project, which is containerised and hosted on a web server, and will run on a single process? 

If in production I were very interested in optimising response times to HTTP requests, would it be sensible to separate a 'microservice' into 2 hosted web services e.g. 'x.API.HTTP' and 'x.API.Events',  one for my HTTP requests and one for handling integration events, both running on a separate processes, which can be scaled independently? Or would this in your opinion violate some guiding principles for the design of these services? 

Thanks!

**Comment by mvelosop** [comment]
Hi @TheoMcCabe, thanks for the feedback.

There are usually no hard rules when working with microservices. That you mention sound like a valid possible solution, just keep in mind that's best to base you decisions on real life measurements. Otherwise you might be adding complexity that adds no or little value.

Hope this helps.

**Comment by TheoMcCabe** [comment]
Fair enough, that's a good point.  I will start with a simpler design and go from there. Cheers

> Hi @TheoMcCabe, thanks for the feedback.
> 
> There are usually no hard rules when working with microservices. That you mention sound like a valid possible solution, just keep in mind that's best to base you decisions on real life measurements. Otherwise you might be adding complexity that adds no or little value.
> 
> Hope this helps.
