### ISSUE TITLE
How to scale-out Order microservice?

### ISSUE THREAD

**Issue by sattha** [dotnet-architecture/eShopOnContainers#1307]
According to this architecture diagram, what should be the approach for scale-out Order service? because the database is in each container...

https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/img/eShopOnContainers-architecture.png

**Comment by mvelosop** [comment]
Hi @sattha, Thanks for your feedback.

Well, that's a logical high-level diagram of the Ordering Microservice, composed of two containers (red boxes) and a database, that you can scale out independently.

![image](https://user-images.githubusercontent.com/7357806/80184249-22324d80-8602-11ea-8313-3a6c9a6a6fae.png)

So in this case, you can scale out each component independently, say, you could have five containers running the Ordering.API image and just two containers running the Ordering.BackgroudTasks image. And change that according to the workload.

As for the DB, you'd probably scale it **up** (more powerful compute) up to a certain point and then scale it out by sharding, say by geography. Or a combination both, however, that's, as usual, a context dependent decision.

Hope this helps.

**Comment by sattha** [comment]
Thank you for clarification.
