### ISSUE TITLE
Why I get this error - ERROR: Service 'webstatus' failed to build: The command 'cmd /S /C dotnet restore "eShopOnContainers-ServicesAndWebApps.sln"' returned a non-zero code: 1

### ISSUE THREAD

**Issue by RamzanMSM** [dotnet-architecture/eShopOnContainers#1308]
ERROR: Service 'webstatus' failed to build: The command 'cmd /S /C dotnet restore "eShopOnContainers-ServicesAndWebApps.sln"' returned a non-zero code: 1
![Error eShop](https://user-images.githubusercontent.com/17004229/80298361-05844a00-87a9-11ea-939d-155a4a124f47.png)

**Comment by domicioam** [comment]
Hello, @RamzanMSM. Is this a fresh install? Did you change any files inside the project?

**Comment by RamzanMSM** [comment]
Fresh install. I didn't change anything

**Comment by mvelosop** [comment]
Hi @RamzanMSM.

You might have the myget feed blocked by a firewall.

You can easily check by just going to this address: <https://dotnet.myget.org/F/aspnetcore-tools/api/v3/index.json>

You should see something like this:

![image](https://user-images.githubusercontent.com/7357806/81590032-155b7b00-93b2-11ea-859b-286b1e095c89.png)

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
