### ISSUE TITLE
Setting-the-Web-SPA-application-up is still necessary

### ISSUE THREAD

**Issue by domicioam** [dotnet-architecture/eShopOnContainers#1310]
Hello, setting up the SPA application is still necessary as it won't work with docker-compose setup. I had a lot of trouble because of that until I realized I had to build the SPA myself. The page is marked as deprecated stating it won't be necessary anymore.

The WebMVC login isn't working anymore and now the only temporary solution is to use the WebSPA.

I'm starting with the application right now, but I plan to fix the login issue with the WebMVC and submit a pull request.

Best regards.

**Comment by domicioam** [comment]
Just an update on this issue. If I run docker-compose up from the powershell command line, everything works fine. I'm still trying to diagnose the issue when running from Visual Studio, but I'm afraid of breaking the other methods (Visual Studio Code for instance).

**Comment by mvelosop** [comment]
Hi @domicioam, thanks for the feedback.

It's not really necessary to set up the SPA before building, it's been so for a long time now.

Can you share the error you get and the process you're following?

As for the MVC login issue, please take a look at the [unauthorized_client error on Login wiki page](https://github.com/dotnet-architecture/eShopOnContainers/wiki/unauthorized_client-error-on-login), it should fix your issue.

Hope this helps.

**Comment by domicioam** [comment]
Yes, maybe it is an issue with my Visual Studio because when I run the project with docker-compose from powershell, everything goes fine. 

I will check the wiki page you mentioned and then I will come here with some feedback.

Thanks.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
