### ISSUE TITLE
"502 bad gateway" error occurs on the login page after deploy the eshop to a Kubernetes cluster in Azure with AKS-Engine

### ISSUE THREAD

**Issue by yanglanfang1000** [dotnet-architecture/eShopOnContainers#1311]
Reproduce Steps:
1) Deployed a Kubernetes cluster in Azure with AKS-Engine
https://github.com/Azure/aks-engine/blob/master/docs/tutorials/quickstart.md#aks-engine-the-long-way
2)Setup Helm and Tiller
$ kubectl apply -f helm-rbac.yaml
$ helm init --history-max 200 --service-account tiller --node-selectors "beta.kubernetes.io/os=linux"
3)Create a static IP and set the dns
az network public-ip create --resource-group eshop-aks-engine --name eshop-nginx-ingress-ip --sku Standard --allocation-method static --dns-name eshop-akse-cluster --query publicIp.ipAddress -o tsv
4)Create an ingress controller with a static public IP address in Azure Kubernetes Service
$ helm install --name nginx-ingress `
    --namespace ingress-nginx `
    --set controller.nodeSelector."beta\.kubernetes\.io\/os"=linux `
    --set defaultBackend.nodeSelector."beta\.kubernetes\.io\/os"=linux `
    --set controller.service.loadBalancerIP="52.139.175.102" `
    --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"="eshop-akse-cluster" `
    --set rbac.create=true `
    stable/nginx-ingress
5)Install eShopOnContainers using Helm
.\deploy-all-aks.ps1 -externalDns eshop-akse-cluster.eastasia.cloudapp.azure.com -aksName eshopaksenginetestcluster -aksRg eshop-aks-engine  -imageTag linux-dev -useMesh $false
Note: Changed the "ingressValuesFile" to "ingress_values_dockerk8s.yaml" in the deploy-all-aks.ps1 file.
6)View the services
![image](https://user-images.githubusercontent.com/22952130/80470636-dde1dd00-8974-11ea-902f-1761e878bc1c.png)
7) click "LOGIN" on  the http://eshop-akse-cluster.eastasia.cloudapp.azure.com/webmvc page
8) Enter the User name and Password on the login page and click "[LOG IN]"
![image](https://user-images.githubusercontent.com/22952130/80470694-efc38000-8974-11ea-91b2-f1c31fe93192.png)

**Comment by eiximenis** [comment]
Hi @yanglanfang1000

Have you followed the steps outlined in https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS)#allow-large-headers-needed-for-login-to-work?

However as you are using nginx ingress controller you need to edit the /deploy/k8s/helm/aks-httpaddon-cfg.yaml to be like:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
data:
  proxy-buffer-size: "128k"
  proxy-buffers: "4 256k"
```

For more information refer to https://kubernetes.github.io/ingress-nginx/examples/customization/custom-configuration/ and https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/

Let me know if it works!

**Comment by yanglanfang1000** [comment]
@eiximenis   I followed the steps and made some change like above to allow large headers but seems it doesn't work.

**Comment by thatniggafacts** [comment]
https://site-stats.org/getserex.com/

**Comment by eiximenis** [comment]
Hi @yanglanfang1000 

Aks-engine is not a currently official supported engine for eShop and we haven't tested on it, but **we are really interested on it**.
I am wondering if is possible to you to share the kubeconfig file for this cluster to allow us to see exact what is deployed and what is happening.
 
If this is not possible we will try to repro your problem, but having access to your already deployed cluster will faster things a lot.
 
If this is OK, let me know, to share a secure channel to transfer the file!

**Comment by yanglanfang1000** [comment]
@eiximenis the kubeconfig file has been transfered to you. Please let me know if you need any more details.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
