### ISSUE TITLE
Sending integration commands asynchronously

### ISSUE THREAD

**Issue by ghominejad** [dotnet-architecture/eShopOnContainers#1312]
I would like to know, what is the reason you've removed the `CommandBus` project while there are scenarios that need to send integrated commands between microservices asynchronously.

**Comment by mvelosop** [comment]
Hi @ghominejad, we did a code clean-up not too long ago and that project wasn't being referenced in the solution.

eShopOnContainers only handles integration events.

I think that, asynchronous "integration commands" is something that you usually want to avoid, as it creates a dependency between the microservices but that's, of course, something that depends on the context.

Hope this helps.
