### ISSUE TITLE
Unable to find the deploy-nodeports.ps1 file

### ISSUE THREAD

**Issue by pritamhinger** [dotnet-architecture/eShopOnContainers#1315]
In the "**Deploy to Local Kubernetes**" wiki document, there is a section [Explore internal services](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes#explore-internal-services) which explain steps to access the Sql Server and RabbitMQs used in the cluster.

However, I can't find the PowerShell script anywhere in the code. I have also referenced the previous issues and found the issue #1091  relevant to this error. This issue also refers to this PowerShell script and mention the same documentation link I added above.

Can you please let me know if there is any other way to access the internal services like RabbitMQ and Sql Server instances.

**Comment by mvelosop** [comment]
Hi @pritamhinger, thanks for your feedback.

You're right that file is missing, however you can just apply the files in <https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/deploy/k8s/nodeports>  as in:

```powershell
kubectl apply -f nodeports/sql-service.yaml
kubectl apply -f nodeports/rabbitmq-admin.yaml
```

Hope this helps.

**Comment by pritamhinger** [comment]
Thanks @mvelosop for your reply. I will try this right away.

**Comment by pritamhinger** [comment]
The commands you shared solved my issue. Thanks for the help @mvelosop .
