### ISSUE TITLE
incorrect order of cors

### ISSUE THREAD

**Issue by upendragusain** [dotnet-architecture/eShopOnContainers#1319]
As per the below msdocs article the UseCors() order seems to be wrong?

https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1

**"With endpoint routing, the CORS middleware must be configured to execute between the calls to UseRouting and UseEndpoints."**

https://github.com/dotnet-architecture/eShopOnContainers/blob/b1021c88d55d96c247eab75bde650ab4b194f706/src/Services/Catalog/Catalog.API/Startup.cs#L86

**Comment by mvelosop** [comment]
Hi @upendragusain, thanks for the heads up!

And this actually occurs in all services!

You might want to submit a PR with the fix 😉

**Comment by mvelosop** [comment]
Fixed with PR #1337
