### ISSUE TITLE
Envoy - how to connect to services that are running on localhost

### ISSUE THREAD

**Issue by tungphuong** [dotnet-architecture/eShopOnContainers#1320]
In case, we are implementing one feature that relates to SPA and one service such as basket API. How can we run both of them from code and can debug them by VS code on Mac? Because it seems that the SPA is connecting to the gateway via envoy proxy (it is one docker container and connect to other services by service name of docker-compose). So, we cannot access to the working service on local. 
If I have any missing, please explain the way to run the system in development mode.
Thanks,

**Comment by mvelosop** [comment]
I @tungphuong,

You should be able to debug the services with VS using F5 and setting up breakpoints just as with any other app.

Hope this helps.

**Comment by tungphuong** [comment]
Thanks but how can we configure the DNS of service in envoy config? It is a docker service now. Maybe, your meaning that debug in a docker container? Besides, I want to use VS Code, not VS.

**Comment by mvelosop** [comment]
I'm not sure I understand about the DNS configuration.

You can access any service in docker referencing the host `host.docker.internal` and using the published port.

Likewise, from inside you docker containers, you can use the same host `host.docker.internal` to access any service in the host, Docker's DNS resolves that.

I haven't tried this, but you should be able to run any service locally on the host, but you'd have to configure everything to point at it in `host.docker.internal`. But I really haven't tried that.

Envoy configuration is in this file: https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/ApiGateways/Envoy/config/webshopping/envoy.yaml

As for debugging docker containers from VS Code, this might help you: https://github.com/microsoft/generator-docker/issues/130, though I haven't tried it either.

Hope this helps.

**Comment by tungphuong** [comment]
Thanks @mvelosop, I used the similar and it works well. 

But there is one thing that I am not clear in the design; they used Linkerd that why do we need envoy proxy?

**Comment by mvelosop** [comment]
Hi @tungphuong,

I'm not familiar with using Linkerd as an API Gateway, but you can certainly use anything that fits.

For example you can use and NGINX Ingress instead of Envoy as an API Gateway.

The idea for switching from Ocelot to Envoy was adding support for gRPC external communication, but that hasn't been implemented.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
