### ISSUE TITLE
Using Pull Dog

### ISSUE THREAD

**Issue by ffMathy** [dotnet-architecture/eShopOnContainers#1324]
I recently launched a service that I believe could be helpful in this repository. It's free to use (from a demo-cluster pool of free servers), and I need feedback. I think it could really be a win-win for us both.

https://dogger.io

It automatically spawns up a Docker-based test environment for each of your pull requests, based on a docker-compose.yml file that you choose.

I think it could be helpful in general, to test things out in production before they are merged.

What do you think? It is already used by the [Portainer project](https://github.com/portainer/portainer), and they have been very happy with it so far.

**Comment by mvelosop** [comment]
Hi @ffMathy, thanks for the information.

I'll have this issue open for a while, just in case some from the community is interested to give your product a spin.

Cheers.

**Comment by ffMathy** [comment]
Hi @mvelosop - that means a lot to me, and is very valuable. Thank you!

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
