### ISSUE TITLE
The register sequence of InMemoryEventBusSubscriptionsManager in Ordering Startup

### ISSUE THREAD

**Issue by leon-liuyang** [dotnet-architecture/eShopOnContainers#1326]
Hi,  

In Ordering Startup, when adding eventbus, it adds EventBusRabbitMQ first and then InMemoryEventBusSubscriptionsManager. 

My question is when adding EventBusRabbitMQ, its ctor function needs an instance of InMemoryEventBusSubscriptionsManager. However at that time it is null, why not add InMemoryEventBusSubscriptionsManager first to avoid this situation?

**Comment by mvelosop** [comment]
Hi @leon-liuyang,

Keep in mind that you're only configuring the DI container at that point. not creating instances.

That configuration occurs actually when the app is starting.

By the time the instances are really needed, the DI container takes of creating all required instances, as per each constructor.

The order you use for registering types in the DI container is not important. The factories you might see there are not invoked at that point.

Hope this helps.

**Comment by leon-liuyang** [comment]
> Hi @leon-liuyang,
> 
> Keep in mind that you're only configuring the DI container at that point. not creating instances.
> 
> That configuration occurs actually when the app is starting.
> 
> By the time the instances are really needed, the DI container takes of creating all required instances, as per each constructor.
> 
> The order you use for registering types in the DI container is not important. The factories you might see there are not invoked at that point.
> 
> Hope this helps.

Thanks! It helps a lot.
