### ISSUE TITLE
Should we use RabbitMQ right after API Gateway to request and respond to data?

### ISSUE THREAD

**Issue by tuphampro** [dotnet-architecture/eShopOnContainers#1329]
Should we use RabbitMQ right after API Gateway to request and respond to data?

**Comment by mvelosop** [comment]
Hi @tuphampro, that's an interesting question!

That, of course, depends on the context and what you need to achieve.

Just keep in mind that in that case you're chaining two fundamentally different communication models:

- Synchronous with a REST API call and
- Asynchronous with a RabbitMQ message

When you use an API call you're usually expecting to get the response fast, that is, in the order or milliseconds or a few seconds, at most.

When you use asynchronous communications you don't really care too much how long it takes for the message to arrive to its destination, 

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
