### ISSUE TITLE
How to build the following model in c # using API Gateway, RabbitMQ, Microservice?

### ISSUE THREAD

**Issue by tuphampro** [dotnet-architecture/eShopOnContainers#1330]
How to build the following model in c # using API Gateway, RabbitMQ, Microservice?
<img width="512" alt="Screen Shot 2020-05-27 at 21 06 19" src="https://user-images.githubusercontent.com/19162524/83051080-ae0f1d80-a077-11ea-829e-be605c0275e2.png">

**Comment by mvelosop** [comment]
Closing as off-topic
