### ISSUE TITLE
DataProtection 

### ISSUE THREAD

**Issue by HishamAbonjim** [dotnet-architecture/eShopOnContainers#1331]
HI 

i have a question for the following code,  
`
            if (Configuration.GetValue<string>("IsClusterEnv") == bool.TrueString)
            {
                services.AddDataProtection(opts =>
                {
                    opts.ApplicationDiscriminator = "eshop.webspa";
                })
                .PersistKeysToRedis(ConnectionMultiplexer.Connect(Configuration["DPConnectionString"]), "DataProtection-Keys");
            } ` 
what it used for and what is the relation between   DataProtection  and  Cluster Env  
and what do you mean by  ClusterEnv
thanks

**Comment by gustavdw** [comment]
If the application runs in a cluster/farm (eg many instances), dataprotection keys will be offloaded to a centralized location reachable by all instances, in this case Redis cache is used. On the other hand if you only run a single local instance (eg not a cluster) you can store the keys on disk with or without persistence depending on the circumstances.

**Comment by mvelosop** [comment]
Thanks for answering @gustavdw 😊

Closing this issue now but feel free to comment, will reopen if needed.

**Comment by HishamAbonjim** [comment]
thanks @gustavdw
