### ISSUE TITLE
An unhandled exception occurred while processing the request.

### ISSUE THREAD

**Issue by smolina74** [dotnet-architecture/eShopOnContainers#1332]
Using windows 10 2004, docker 2.3.0.3 with WSL2 support, I'm getting  this exception when being redirected to login page:
An unhandled exception occurred while processing the request.

![error](https://user-images.githubusercontent.com/1020450/83340615-be5e0d00-a2b0-11ea-883a-9f3f2fbe46fd.jpg)

**Comment by mvelosop** [comment]
Hi @smolina74, 

Are you trying this in an old eShopOnContainer version you might've had installed in docker?

Is this error with the MVC or the SPA application?

Thanks.

**Comment by sughosneo** [comment]
Hello @smolina74, I am closing this issue as of now. If needed, please feel free to reopen it.

Thank you.

**Comment by TauqeerAhmad104** [comment]
Any solution of this issu  .. ?
