### ISSUE TITLE
API Gateway code flow understanding

### ISSUE THREAD

**Issue by sarajeev** [dotnet-architecture/eShopOnContainers#1333]
Hi,
I need some help to understand the code base. Below are three questions for now which I am looking for answer, please help to assist me on that.
1. With API gateway, I could see there is ocelot (configuration.json) file but I could not see the initialization of this file into respective API gateway startup.cs file. I found same with "ApiGw-Base" project but how each individual API gateway project like (Web.Shopping.HttpAggregator) is using this ocelot configuration json file?

2. With API gateway project like (Web.Shopping.HttpAggregator) I could see there are few code written in controller but I am not able to understand the use and flow of this code?

3. How event publish and subscribe code flow is working like when we create order and do payment through event message, so I need some help to understand the complete code flow about order processing, so that it will help me how distributed system is connected and working?

**Comment by mvelosop** [comment]
Hi @sarajeev,

For the first two questions you might find these old issues on this subject useful:

- [#593 Using Ocelot Configuration.Json files in multiple projects for BFF framework](https://github.com/dotnet-architecture/eShopOnContainers/issues/593)
- [#637 New to API Gateway and BFF Patterns](https://github.com/dotnet-architecture/eShopOnContainers/issues/637)

As for the third, you can start with the [Serilog and Seq wiki article](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Serilog-and-Seq). You can see an in-depth sample of integration events tracing during the process of a order.

Hope this helps.

**Comment by sarajeev** [comment]
Thank you @mvelosop , It really helped me lot to understand the flow just that one thing still not clear i.e. how fault tolerance or data consistency is maintained into code flow?
Could you please help me to share some relevant details of code base having data consistency related info?

**Comment by mvelosop** [comment]
Hi @mvelosop, I'm glad that helped you 😊

This sample app uses eventual consistency by propagating changes using the message queue (RabbitMQ), however it's only used to propagate price changes.

So that's all about consistency in eShopOnContainers, at least for now.

Hope this helps.

**Comment by sarajeev** [comment]
Thanks @mvelosop , would you like to share any documentation link which have detailed explanation including practical code for data consistency?, so that I can try implement the same.

**Comment by sarajeev** [comment]
Hi @mvelosop , sorry to disturb you again, do you have any documentation related to folder structure for this project?
I am getting little confuse by looking lots of folders having kind of similar jobs which can be done together but in code base having lots of different folder, like if I refer "Ordering Service" there we have Ordering.API which having Command, DomainEventHandlers etc folders and there we also have separate project Ordering.Domain. Could you please help to share any relevant document which can help me to understand the folder structure and its purpose?

**Comment by michalrosenbaum** [comment]
Hi @sarajeev , I believe this book https://dotnet.microsoft.com/download/e-book/microservices-architecture/pdf will answer many of your questions. This book is basically like documentation for this repo. Gateways, eventual consistency - everything is in there.

**Comment by sarajeev** [comment]
Thank you @michalrosenbaum and @mvelosop for all your support and sharing information's. I will go through it and will come back if any further queries. Closing this issue.

**Comment by mvelosop** [comment]
Thanks @michalrosenbaum 😊

You can also read it on-line for the latest content here: <https://docs.microsoft.com/dotnet/architecture/microservices/>
