### ISSUE TITLE
API Gateway UpdateAllBasketAsync action reference

### ISSUE THREAD

**Issue by sarajeev** [dotnet-architecture/eShopOnContainers#1334]
Hi,
I am not able to find the reference, how API gateway controller action method i.e. "UpdateAllBasketAsync" is being call from where on which event to update the basket items on checkout?

Code namespace for your reference : Web.Shopping.HttpAggregator.Controllers

**Comment by mvelosop** [comment]
Hi @sarajeev,

Yep it isn't too obvious 😉, look at this from the SPA:

![image](https://user-images.githubusercontent.com/7357806/83688185-e74e0d00-a5e4-11ea-8c1e-a4776a429295.png)

![image](https://user-images.githubusercontent.com/7357806/83688312-19f80580-a5e5-11ea-8ebd-6ca18d4f8731.png)

Hope this helps.

**Comment by sarajeev** [comment]
Thank you @mvelosop, all clear now. Making this issue close.
