### ISSUE TITLE
Docker container connection refused.

### ISSUE THREAD

**Issue by jackwrx** [dotnet-architecture/eShopOnContainers#1339]
All the containers have started and I tried to connect to http://localhost:5103 but it always said connection refused. Please help.

**Comment by sughosneo** [comment]
Hi @jackwrx , Could you please provide more details ? For e.g : Which deployment method are you using ? 

In case if you are trying to use `docker-compose up` command, in your local environment, then app would be running on below urls :

MVC  : http://docker.for.win.localhost:5100/
SPA : http://localhost:5104/
WebStatus: http://localhost:5107/

And for local k8s and aks, we have recently updated our scripts and wiki. Please refer as per below :

[Local k8s deployment](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes)
[AKS](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS))

Thanks.

**Comment by sughosneo** [comment]
Hi @jackwrx , considering the latest changes are working fine for you, I am closing this issue. If you have any further questions please feel free to reopen it. 

Thank you.
