### ISSUE TITLE
[Question]: What will happen if publishing integration events fails?

### ISSUE THREAD

**Issue by shahabganji** [dotnet-architecture/eShopOnContainers#1340]
I was studying eShopOnContainers and figured out that [here](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.API/Application/DomainEventHandlers/OrderGracePeriodConfirmed/OrderStatusChangedToAwaitingValidationDomainEventHandler.cs#L34-L50) and [here](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.API/Application/Behaviors/TransactionBehaviour.cs#L47-L59) the [Transactional Outbox](https://microservices.io/patterns/data/transactional-outbox.html) pattern is implemented, saving the integration event in a database table in the same transaction as the business rules; then in another [place](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.API/Application/Behaviors/TransactionBehaviour.cs#L61), after all the transactions are committed successfully, the integration event will be read and published through the event bus. The question is what will happen if this operation fails? AFAIK, when using an Outbox patter you need a `Message Relay`, that can be Polling or reading transaction tail log, but I could not find any implementation in the sample. 

Is there something I missed? 

Thanks.

**Comment by mvelosop** [comment]
Hi @shahabganji, you're right, that's a nice point you found 😊

As explained in the [Publishing events through the event bus](https://docs.microsoft.com/dotnet/architecture/microservices/multi-container-microservice-net-applications/subscribe-events#publishing-events-through-the-event-bus) section of the Microservices Guide, that is by-design. To summarize the guide says that given the role of a learning application for architectural patterns, it was not deemed necessary to handle that failure mode, although the guide describes several possible implementations. One of them could be having a "watchdog" process, running in a separate container, that monitors the outbox table, to resend any integration event that might stay in the outbox after some configurable time.

That feature might be implemented in a future version.

Hope this helps.

**Comment by shahabganji** [comment]
@mvelosop Thanks for the explanation, I thought that it is implemented somewhere and I just missed it. Thanks anyway. 🙏

**Comment by mvelosop** [comment]
Glad it helped.

Closing this issue now but feel free to comment, will reopen if needed.
