### ISSUE TITLE
bug in createresources.sh script

### ISSUE THREAD

**Issue by moinakbh** [dotnet-architecture/eShopOnContainers#1341]
In Line#54 & 55 of the file createresources.sh, it should be $1, instead of $2

**Comment by mvelosop** [comment]
Hi @moinakbh, thanks for the heads up!

You're right, that's a bug.

Would you like to submit a PR?

**Comment by sughosneo** [comment]
Hi @moinakbh, quick update - I have fixed this issue in PR #1494

Thank you.
