### ISSUE TITLE
Possible help with gRPC implementation

### ISSUE THREAD

**Issue by wicharypawel** [dotnet-architecture/eShopOnContainers#1342]
Hi @mvelosop, 
I'm writing to offer help with the protocol buffers and gRPC implementation. I'm a .NET programmer who has worked with gRPC quite a lot in the last few months. If my help will be useful, let me know.

Please close this issue as resolved as this is not a real issue. 

Regards Paweł

**Comment by sughosneo** [comment]
Hi @wicharypawel, thanks for reaching out. We are planning to make some upgrade as per feedback https://github.com/dotnet-architecture/eShopOnContainers/issues/1385 . 

Would you like to contribute in this ? Please let us know, we can plan it accordingly. 

Thanks.

**Comment by wicharypawel** [comment]
Sure, go ahead.

**Comment by sughosneo** [comment]
Hi @wicharypawel, thank you again for showing interest. 
You could make the necessary changes for this issue https://github.com/dotnet-architecture/eShopOnContainers/issues/1385 and submit a separate PR.
We can review the changes and merge in.

**Comment by sughosneo** [comment]
Hi @wicharypawel, recently `dev` branch has been updated with changes in "Catalog/Catalog.API/Grpc/CatalogService.cs"
You may want to pull the latest changes at your end. 

Also, is there any forked repo where we can see the ongoing gRPC specific changes related to #1385 ?

Thank you.

**Comment by wicharypawel** [comment]
Hi @sughosneo, thanks for letting me know about the changes. I was busy recently with other duties I should start working on this in upcoming days.

**Comment by sughosneo** [comment]
> Hi @sughosneo, thanks for letting me know about the changes. I was busy recently with other duties I should start working on this in upcoming days.

Thanks for the update @wicharypawel 👍

**Comment by sughosneo** [comment]
Hi @wicharypawel, I am closing this issue as of now as the original `gRPC` related issue #1385 is getting tracked separately. 
If you have any questions, please feel free to reopen it.
