### ISSUE TITLE
NuGet Restore: Received an unexpected EOF or 0 bytes from the transport stream.

### ISSUE THREAD

**Issue by horeeorg** [dotnet-architecture/eShopOnContainers#1346]
When I tried to docker-compose up, I always get '....Received an unexpected EOF or 0 bytes from the transport stream...', could you please help? 

I already searched the problem is the same with this one https://github.com/NuGet/Home/issues/9020

**Comment by horeeorg** [comment]
Actually if I run from the Visual Studio (docker-compose) it run well, but when I run from the powershell (docker-compose up) I always get that error. Is it because visual studio create own network bridge for the container ?

**Comment by nicko-franco** [comment]
@horeeorg  Have you managed to fix this on your side? I've been stuck with this same error too.

**Comment by sughosneo** [comment]
Hi @nicko-franco , @horeeorg , did you manage to try out the application in a different environment ? You could try the below steps in a newly created VM or your local `dev` environment.

- Pull the latest from the `dev` branch.
- Stop all the running containers `docker stop $(docker ps -aq)`
- Delete all the containers `docker rm $(docker ps -aq)` which are stopped by the previous commands.
- Delete all the volumes by using `docker volume rm $(docker volume ls -q)`
- Better to clean up all old docker images by using `docker rmi -f $(docker images -a -q)`
- Or you could purge all the data by using Docker Desktop UI.
- Then you could go to the `src` directory and build all the images again using `docker-compose build` and then followed by `docker-compose up`

> !IMPORTANT Please note, the above commands will clean up all the docker related instances on that environment. So it's not recommended to run these on any production environment or any other environment where docker instances of any other applications are running. 

Hope this helps !

Thank you.

**Comment by sughosneo** [comment]
Hi @nicko-franco , @horeeorg -  just checking if you had a chance to look into this further ? Thanks.

**Comment by sughosneo** [comment]
I am closing this issue as of now. If you have any questions, please feel free to reopen it. 

Thank you.
