### ISSUE TITLE
Catalog Database Seeding Issue

### ISSUE THREAD

**Issue by pavanarya** [dotnet-architecture/eShopOnContainers#1350]
After getting the latest from this project, when I am trying to run we are getting an error when seeding Catalog database

Exception: does not contain required header picturefilename

Root cause: 
In the file src\Services\Catalog\Catalog.API\Infrastructure\CatalogContextSeed.cs

In-Line 184
`string[] requiredHeaders = { "catalogtypename", "catalogbrandname", "description", "name", "price", "pictureFileName" };
                string[] optionalheaders = { "availablestock", "restockthreshold", "maxstockthreshold", "onreorder" };
                csvheaders = GetHeaders(csvFileCatalogItems, requiredHeaders, optionalheaders );`

For required headers, we are passing "pictureFileName" but in GetHeaders() when reading csv headers, we are reading headers as lowercase.

Thanks,
Pavan Kumar Aryasomayajulu

**Comment by sughosneo** [comment]
Hi @pavanarya , thank you for pointing that out. Yes, I am able to see similar behavior but that's not affecting the seeding for the `CatalogItem` table as it's fetching the information from `GetPreconfiguredItems()` method. 

Could you please submit a new PR with your proposed changes ? Please refer  [comment](https://github.com/dotnet-architecture/eShopOnContainers/pull/1351#issuecomment-701951105)

**Comment by sughosneo** [comment]
This has been addressed in https://github.com/dotnet-architecture/eShopOnContainers/pull/1520
So closing this issue. Please feel free to reopen if you have any further question. 

Thank you.
