### ISSUE TITLE
Location not retrieved when app is in background

### ISSUE THREAD

**Issue by IndexOutOfLimit** [dotnet-architecture/eShopOnContainers#1353]
App is not able to retrieve location(Lat/Long) when put in background for some time.

**Comment by sughosneo** [comment]
Hi @IndexOutOfLimit, thanks for reaching out. 

That could be because the session got expired. You would need to login back to see the necessary information. If you trace the request you would notice "401 (Unauthorized)" from the identity server. 

Hope this helps !

**Comment by sughosneo** [comment]
Hi @IndexOutOfLimit , I am closing this issue as of now. If you have any further questions, please feel free to reopen it.
