### ISSUE TITLE
webmvc - CrashLoopBackoff - default backend - 404

### ISSUE THREAD

**Issue by cchoygithub** [dotnet-architecture/eShopOnContainers#1356]
Getting CrashLoopBackoff for my mvc...
¬

PS C:\projects\eShopOnContainers\deploy\k8s\helm> kubectl get pods
NAME                                              READY   STATUS             RESTARTS   AGE
eshop-apigwmm-5c5cdbbbdd-sxgsl                    1/1     Running            0          42m
eshop-apigwms-57dd4d6456-nhwf5                    1/1     Running            0          42m
eshop-apigwwm-5d95fb5768-npbsp                    1/1     Running            0          42m
eshop-apigwws-688bf8f7bb-9zxbr                    1/1     Running            0          42m
eshop-basket-api-84b77c4975-rl5s6                 1/1     Running            0          43m
eshop-basket-data-f949cc887-f94l7                 1/1     Running            0          43m
eshop-catalog-api-67b9f786c7-fnsg2                1/1     Running            0          43m
eshop-identity-api-85958db86b-gf7mm               1/1     Running            0          43m
eshop-keystore-data-56c89897c7-v9m56              1/1     Running            0          43m
eshop-locations-api-8657bdd576-zf6q4              1/1     Running            0          43m
eshop-marketing-api-7d648457bd-td8rs              1/1     Running            0          43m
eshop-mobileshoppingagg-7bbd949c7-99ztx           1/1     Running            0          43m
eshop-nosql-data-58b986c9fb-78bpv                 1/1     Running            0          43m
eshop-ordering-api-7bc74bf899-6zpk2               1/1     Running            0          43m
eshop-ordering-backgroundtasks-5b9cc5bd86-vbm9f   1/1     Running            0          43m
eshop-ordering-signalrhub-6445bcf558-7d75z        1/1     Running            0          43m
eshop-payment-api-7898cc8f4d-5lwm9                1/1     Running            0          43m
eshop-rabbitmq-58cd5df64-kvhmp                    1/1     Running            0          43m
eshop-sql-data-75dff4ccd6-qq6kd                   1/1     Running            0          44m
eshop-webhooks-api-79bc5b86db-nn8hf               1/1     Running            0          42m
eshop-webhooks-web-66c9bb79cf-45mxt               1/1     Running            0          42m
eshop-webmvc-54746874cf-fglk6                     0/1     CrashLoopBackOff   12         43m
eshop-webshoppingagg-6c677cff9f-799f8             1/1     Running            0          43m
eshop-webspa-7d84bb74c-96gkw                      1/1     Running            0          42m
eshop-webstatus-66d4867c8b-kkqm9                  1/1     Running            0          42m
PS C:\projects\eShopOnContainers\deploy\k8s\helm>

**Comment by cchoygithub** [comment]
[16:27:21 INF] Configuring web host (eShopOnContainers.WebMVC)...
[16:27:21 FTL] Program terminated unexpectedly (eShopOnContainers.WebMVC)!
System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at Microsoft.eShopOnContainers.WebMVC.ServiceCollectionExtensions.AddHealthChecks(IServiceCollection services, IConfiguration configuration) in /src/src/Web/WebMVC/Startup.cs:line 140
   at Microsoft.eShopOnContainers.WebMVC.Startup.ConfigureServices(IServiceCollection services) in /src/src/Web/WebMVC/Startup.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.eShopOnContainers.WebMVC.Program.Main(String[] args) in /src/src/Web/WebMVC/Program.cs:line 24

**Comment by tjozsa** [comment]
same here, reproduced on AKS

**Comment by tjozsa** [comment]
I think this issue is connected to 1305 [1305](https://github.com/dotnet-architecture/eShopOnContainers/issues/1305). Anyhow, I tride the proposed workaround in 1305 but that did not work either.

**Comment by sughosneo** [comment]
I am closing this issue as of now. Please feel free to reopen if you have any further questions.

Thanks.
