### ISSUE TITLE
I cannot login to either the SPA , MVC Applications or RabbitMQ Management Interface

### ISSUE THREAD

**Issue by bblair2018** [dotnet-architecture/eShopOnContainers#1362]
Whenever I try to login to either of the applications, I get this. How can I fix this?

![image](https://user-images.githubusercontent.com/36137230/87064420-54048a80-c1d5-11ea-9d6f-548be49e8bf0.png)

Also, I cannot see the rabitmq dashboard. It taking too long to respond. (Fixed this)

**Comment by bblair2018** [comment]
Well, I thought rabbitmq management plugin was not working because rabbitmq was not installed, but I just installed it now and enabled to the rabbitmq_management plugin, but rabbitmq management site is still not working.

**Comment by bblair2018** [comment]
Ok, got rabbitmq to work. But I still cannot login to the MVC or SPA sites.

**Comment by bblair2018** [comment]
Also, redis-commander is not working as well, please see the pic below:

![image](https://user-images.githubusercontent.com/36137230/87077574-f2e6b200-c1e8-11ea-9c20-2ca6c4ea3aa6.png)

**Comment by bblair2018** [comment]
Wait, rabbitmq is only working on my host machine and not in docker. Still working on this.

**Comment by bblair2018** [comment]
I need help to get past the following:
- Account log-on issues with the MVC and SPA sights.
- How do I login to the rabbitmq manager through docker.
- Redis-commander is not working on port 8081.

**Comment by rekhajay** [comment]
I had the unauthorized_client error too. Try starting the app using the URL http://docker.for.win.localhost:5100/, and then going to the login screen. 
There is a post that explains why:
 https://github.com/dotnet-architecture/eShopOnContainers/wiki/unauthorized_client-error-on-login

**Comment by thanhxuanhd** [comment]
Hi @bblair2018 
I found the root cause the issue come from configuration in table ClientRedirectUris (Microsoft.eShopOnContainers.Service.IdentityDb). If you run MVC application is localhost:5100 and try to login application, you need to change configuration is 
`12	http://docker.for.win.localhost:5100/	1`
Default value configuration is `http://docker.for.win.localhost:5104/` (SPA)
Thanks, 
Xuan

**Comment by sughosneo** [comment]
Hello Everyone, 

I am closing this issue as of now, considering the "login" issue has been addressed. But please feel free to reopen it if it's needed.

Thank you.
