### ISSUE TITLE
Issues deploying to local kubernetes

### ISSUE THREAD

**Issue by GaTechThomas** [dotnet-architecture/eShopOnContainers#1367]
I really, really want to push forward with learning from eShopOnContainers. In the past 2 years, I've tried at least three times, and each time left in frustration after many hours over several days.

I'm not an expert in docker or kubernetes, but I am an expert in .Net development. I'm certain that something has changed in either Docker or Helm that makes the steps in the wiki fail to function properly. Would someone please start with a new machine and follow the steps at the following wiki to confirm proper functionality.

https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes

Thanks!

**Comment by nishanil** [comment]
@sughosneo Can you verify this? This is probably related to Helm version bug?

**Comment by sughosneo** [comment]
cc:@nishanil
Hi @GaTechThomas, we have recently updated our scripts to support latest versions in both local k8s and aks related deployment. We have also updated our [wiki](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes) page. Could you please give that a try  ?

Please feel free revert back if you have any questions. 

Thanks.

**Comment by nishanil** [comment]
@GaTechThomas Hey! I just tested the latest changes from Sumit on docker as well as on local kubernetes. It worked for me. The version numbers of the components and hosts are listed in the WIKI. Please do validate if you have the right versions installed locally.

Just to make it easier, writing down the steps here:

1. Get latest source from the repo first
1. For running eShop in docker, navigate to **eShopOnContainers/src** folder and 
    - Run the following command: `docker-compose build` 
    - After the build passes, run `docker-compose up` and then from the browser navigate to `http://docker.for.win.localhost:5100/` (assuming you're running it from windows)
1. For Kubernetes, use the Kubernetes included with the `docker desktop` and make sure your `kubectl` is configured correctly.
    - Run the following commands from the **deploy/k8s/nginx-ingress** folder to setup ingress first
       ```
      kubectl apply -f mandatory.yaml
      kubectl apply -f local-cm.yaml
      kubectl apply -f local-svc.yaml
      ```
   - Next, navigate to the **deploy/k8s/helm** folder and run `.\deploy-all.ps1 -imageTag linux-dev -useLocalk8s $true`

Let me know if it works.

**Comment by GaTechThomas** [comment]
Thank you very much. I expect to be able to work on this again next week. I'll let you know how it goes.

**Comment by GaTechThomas** [comment]
It works! ...for Kubernetes, that is. The docker version didn't work for me - it seems to have gotten into a loop and tried for over an hour. I'm not concerned with that part, since the Kubernetes part is really what I'm looking for. Thank you!

One thing to add...

- The step to get the bearer token for the Kubernetes dashboard fails. It appears that it needs to be written for Windows (assuming that's the intent, as I'm using Windows for everything else). I was able to figure out the token by running part of the command (the grep was at least part of the problem).

**Comment by sughosneo** [comment]
Hi @GaTechThomas , thanks for the update. 

Not, sure if I understand the issue which you were trying to refer in the second part of your comment. But if you feel that needs to be resolved, please send a PR with the details. Will review and merge the changes. 

In the meantime, as K8s deployment is working fine for you. I am closing this issue, but if you face any other challenges please feel free to reopen it.
