### ISSUE TITLE
logoutId is null

### ISSUE THREAD

**Issue by dereklew** [dotnet-architecture/eShopOnContainers#1376]
Hi all,

I am getting null in logoutId in the following function while using the demo user ID,  Any reason why?

        public async Task<IActionResult> Logout(string logoutId)
        {
            if (User.Identity.IsAuthenticated == false)
            {
                // if the user is not authenticated, then just show logged out page
                return await Logout(new LogoutViewModel { LogoutId = logoutId });
            }

            //Test for Xamarin. 
            var context = await _interaction.GetLogoutContextAsync(logoutId);
            if (context?.ShowSignoutPrompt == false)
            {
                //it's safe to automatically sign-out
                return await Logout(new LogoutViewModel { LogoutId = logoutId });
            }

            // show the logout prompt. this prevents attacks where the user
            // is automatically signed out by another malicious web page.
            var vm = new LogoutViewModel
            {
                LogoutId = logoutId
            };
            return View(vm);
        }

**Comment by dereklew** [comment]
This happens in both MVC and SPA.

**Comment by dereklew** [comment]
Resolved my own issue,  Need to check the PostLogoutRedirectUri in ClientPostLogoutRedirectUris

**Comment by sughosneo** [comment]
Hi @dereklew, sorry for the delay in reaching out and glad to hear that it has been resolved. You may want to share the some details some further details for everyone's reference. 

Thanks.

**Comment by sughosneo** [comment]
Hi @dereklew, as this original issue is resolved. I am marking this issue as closed.
