### ISSUE TITLE
Migration Azure DevOps pipeline to GitHub actions

### ISSUE THREAD

**Issue by sughosneo** [dotnet-architecture/eShopOnContainers#1377]
In this feature we would target to move all present Azure Devops related pipelines to Github Actions.

**Comment by terle** [comment]
I'm curious as to _why_ you're making this move? Are Azure Pipeline no longer a priority? Why not keep them both?
With PR #1565 files have been removed.

My motivation is that I've invested time in building pipelines in Azure following this good reference implementation; and now you're suddenly removing support for Azure Pipelines.

**Comment by sughosneo** [comment]
Hi @terle, thank you for bringing up this point.

Just to clarify, we are not deprioritizing the Azure Pipeline with this move. Azure Pipeline still remains a great choice for many production applications to implement their CI/CD.  From the `eShopOnContainers` perspective, we want our community members to view the details of every aspect of the CI and CD pipeline in the GitHub repository itself. Hence, GitHub Action has turned out to be a better choice in this specific scenario. And the thought behind to keep only "GitHub Action" is basically for the ease of maintenance. You could still refer Azure Pipelines in the [main](https://github.com/dotnet-architecture/eShopOnContainers/tree/main/build/azure-devops) branch that runs on `.NET Core` LTS version `3.1`.

Hope this helps !

**Comment by terle** [comment]
Hi @sughosneo Thank you for taking the time to address my concern. I does bring some clarity.

Forgive me, but I'm still having a hard time seeing how a complete removal of the deploy scrips for Azure Devops is not indicative of a desire to shift focus to Github Actions? (call it shift of focus, de-/down prioritisation).

I agree that Azure Pipelines still is a great choice. I came here seeking inspiration and guidance on how to start a micro service project from scratch. So naturally the shift makes me curious. 

So maybe you would be kind enough to elaborate on _how_ and why Github Actions are a better choice, in this scenario?

Thank you for taking the time to reply and thank you for making this code base available to us. It has helped me tremendously.

**Comment by sughosneo** [comment]
Hi @terle, thank you for your feedback. Great to know that it helped you 👍 
To explore more on Microservices architecture, you can also refer [.NET Microservices Architecture Guidance](https://dotnet.microsoft.com/learn/aspnet/microservices-architecture)

Now, coming back to the question. As mentioned above, the choice of GitHub Action in this particular scenario wasn't based on any specific features. It was more driven by the fact that with this approach, all the community members can easily refer any of the workflows under one umbrella. I hope this clarifies :relaxed:

I am closing this issue as of now. Please feel free to reopen it, if you have any further questions.
