### ISSUE TITLE
The connection to the server was reset while the page was loading./ address shows blank

### ISSUE THREAD

**Issue by Irving0904** [dotnet-architecture/eShopOnContainers#1379]
on my local
NAME                          HOSTS       ADDRESS   PORTS   AGE
eshop-apigwmm                 localhost             80      10h
eshop-apigwms                 localhost             80      10h
eshop-apigwwm                 localhost             80      10h
eshop-apigwws                 localhost             80      10h
eshop-identity-api            localhost             80      10h
eshop-identity-api-local      *                     80      10h
eshop-identity-api-loopback   *                     80      11h
eshop-webhooks-api            localhost             80      10h
eshop-webhooks-web            localhost             80      10h
eshop-webmvc                  localhost             80      10h
eshop-webmvc-local            *                     80      10h
eshop-webmvc-loopback         *                     80      11h
eshop-webspa                  localhost             80      10h
eshop-webstatus               localhost             80      10h

Error : The connection to the server was reset while the page was loading.

**Comment by sughosneo** [comment]
Hi @Irving0904 , if you type `kubectl get ing` it would show all the services attached to it with DNS as `localhost`.
After that you should be able to browse different app as per below :

Web SPA : http://localhost/
Web Status:  http://localhost/WebStatus
Web MVC: http://localhost/webmvc

But for the MVC there is a [known behaviour](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes#known-behaviours) - you may want to refer the wiki on that. 

Please try it out and let me know if it works. 

Thanks.

**Comment by Irving0904** [comment]
Hi ,

The tried all the options but when I tried on diff laptop with same steps
it worked perfectly with no issues. My guess it could be related to Docker
version I had

Irving0904

**Comment by sughosneo** [comment]
Thanks @Irving0904 for the update. 

That could be one of the possible reason. As the latest steps are working fine, I am closing this issue as of now. Please feel free to reopen or a create a new on if you face any other challenges.
