### ISSUE TITLE
gRPC calls shouldn't create a channel per-request

### ISSUE THREAD

**Issue by JamesNK** [dotnet-architecture/eShopOnContainers#1385]
A channel is being created for each request here - https://github.com/dotnet-architecture/eShopOnContainers/blob/43fe719e98bb7e004c697d5724a975f5ecb2191b/src/ApiGateways/Web.Bff.Shopping/aggregator/Services/GrpcCallerService.cs

This will create poor performance. Documented here - https://docs.microsoft.com/en-us/aspnet/core/grpc/client?view=aspnetcore-3.1#client-performance

I recommend that the https://docs.microsoft.com/en-us/aspnet/core/grpc/clientfactory?view=aspnetcore-3.1 be used to centralize configuration, and inject typed gRPC clients directly into services

**Comment by nishanil** [comment]
Thanks @JamesNK for the feedback. Adding this to our backlogs to fix it.
cc @sughosneo

**Comment by wicharypawel** [comment]
As mentioned in #1342, I want to do some development here. Let me know, if anybody has already started this issue.

**Comment by sughosneo** [comment]
> As mentioned in #1342, I want to do some development here. Let me know, if anybody has already started this issue.

Hi @wicharypawel , just checking if you had a further chance to look into this issue.

Thanks.

**Comment by Feng-Bu-Jue** [comment]
I tried to register grpcClient with `AddGrpcClient` , But I got an error when I sent the request. 
error message: `Status(StatusCode=Internal, Detail="Error starting gRPC call: An error occurred while sending the request.")`

**Comment by mvelosop** [comment]
Thanks @JamesNK, this was fixed a few days ago, with the migration to .NET 5, using the RPC client factory as you suggested.

So I'm closing this issue and referencing the fix here:

https://github.com/dotnet-architecture/eShopOnContainers/blob/76fbcffd90ce335cb259c985fe8b104a565e9895/src/ApiGateways/Web.Bff.Shopping/aggregator/Startup.cs#L194-L223

Cheers 😊
