### ISSUE TITLE
[Question] Best practice for Command handling

### ISSUE THREAD

**Issue by khoavn** [dotnet-architecture/eShopOnContainers#1386]
As I understand when sending Commands, `TransactionBehaviour` wraps it in `ReadCommitted` transaction, so my question is should it call application services in Command Handler (e.g: run some validations, querying some tables, getting data from Redis or even consuming external APIs...)  or it should handle above tasks in application service before sending Command to save data?
Thank you.

**Comment by sughosneo** [comment]
Hi @khoavn thanks for the question. 

Command pattern is intrinsically related to the CQRS pattern. One is the query part another is the command part. If the application component is focused on implementing the command then it just needs to send the command with create/update and let the hanlder decide what action needs to be taken for that. 
For e.g: if command `createOrderDraft` has been sent then handler may decide to update some data store before taking any further action. Or even does a validate to avoid duplicates.

You can also quickly refer this [section](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/microservice-application-layer-implementation-web-api#implement-the-command-and-command-handler-patterns)

I hope I understood your question right, but if this doesn't help, please feel free to write back.

**Comment by khoavn** [comment]
Hi @sughosneo ,
Thanks for your response, actually my biggest concern is `Command ` is executed in transaction open by `TransactionBehaviour`, so should it be a problem if `CommandHandler` does some long-run tasks (e.g consuming external apis)? I'm thinking about using `IRequestPreProcessor` to prepare data for `CommandHandler`, is it best practice?

**Comment by sughosneo** [comment]
Hi @khoavn, you may want to keep your `CommandHandler` simple and it shouldn't be doing too many operations. For an instance : external API calls. You can move that logic under domain behavior. You can refer this [CommandHandler](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/microservice-application-layer-implementation-web-api#the-command-handler-class) class. 

Thank you.

**Comment by sughosneo** [comment]
Hi @khoavn, I am closing this issue as of now. If you have any further questions, please feel free to reopen it. 

Thank you.
