### ISSUE TITLE
ERROR: Service 'webstatus' failed to build: The command '/bin/sh -c dotnet publish --no-restore -c Release -o /app' returned a non-zero code: 1

### ISSUE THREAD

**Issue by dereklew** [dotnet-architecture/eShopOnContainers#1388]
In docker-compose build, i am getting the following error.  

Restore operation started...
  Restoring library jquery@3.4.1...
  wwwroot/lib/jquery/core.js written to destination
  wwwroot/lib/jquery/jquery.js written to destination
  wwwroot/lib/jquery/jquery.min.js written to destination
  wwwroot/lib/jquery/jquery.min.map written to destination
  wwwroot/lib/jquery/jquery.slim.js written to destination
  wwwroot/lib/jquery/jquery.slim.min.js written to destination
  wwwroot/lib/jquery/jquery.slim.min.map written to destination
  Restoring library bootstrap@4.1.3...
libman.json : error LIB002: The "bootstrap@4.1.3" library could not be resolved by the "unpkg" provider [/src/Web/WebStatus/WebStatus.csproj]

  One or more libraries failed to restore

ERROR: Service 'webstatus' failed to build: The command '/bin/sh -c dotnet publish --no-restore -c Release -o /app' returned a non-zero code: 1

**Comment by sughosneo** [comment]
Hi @dereklew , could you please take a look at this issue - #1169 

Thank you.

**Comment by sughosneo** [comment]
I am closing this issue considering it has been resolved. But please feel free to reopen if you face any further challenges. 

Thank you.

**Comment by oshabanisbg** [comment]
i am having the same issue ,but in different package 
Restore operation started...
#0 208.0 libman.json : error LIB002: The "jquery@3.4.1" library could not be resolved by the "cdnjs" provider [/src/Web/WebStatus/WebStatus.csproj]
