### ISSUE TITLE
an instantiation of a dbcontext without the use of using block!

### ISSUE THREAD

**Issue by nsedoud** [dotnet-architecture/eShopOnContainers#1392]
in the [IntegrationEventLogService] class on line 27, you instantiate directly with new, the dbcontext [IntegrationEventLogContext].

with this way of doing things, without an explicit disposing or the usage of the resolution from the D.I container
how to make sure that the dbcontext will be disposed out correctly?

**Comment by sughosneo** [comment]
Hi @nsedoud thanks for your feedback. Yes, I agree with you. Could you please create a PR on this ? We can review and merge the changes ?

**Comment by mvelosop** [comment]
Hi @nsedoud, nice observation 👍

What's the solution you're thinking of?

**Comment by nsedoud** [comment]
Hi,
thinks for your replay,
the ideal is to let the dependency container do the work itselft (resolve and dispose).
but if we leave the configuration of services in the Strartup class as they are, here is how to do it:
make the CatalogIntegrationEventService class disposable, but be careful to only dispose _eventLogService, as it is created outside the container by _integrationEventLogServiceFactory and let other injected refs auto disposed by DI container.
similarly also implement IDisposable for IntegrationEventLogService, and dispose only _integrationEventLogContext
the rest will be auto disposed by container.

**Comment by sughosneo** [comment]
Closing this issue as the changes are merged with the `dev` branch.
