### ISSUE TITLE
Need help in configuring my existing AKS domain

### ISSUE THREAD

**Issue by ejstan** [dotnet-architecture/eShopOnContainers#1394]
Hi,

I've been looking for solutions on how to resolve the difficulty I'm facing but I'm unable to do this.

I have an existing AKS domain (sample.southeastasia.cloudapp.azure.com) and would like to replace it to a custom one (app.company1.com)

Can someone help me how to do this? Thank you in advance.

**Comment by sughosneo** [comment]
Hi @ejstan , thanks for reaching out.

1) Do you want to deploy `eShopOnContainers` to AKS using a custom DNS ? 
    If yes, then you can refer :  [Using Specific DNS](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS)#using-specific-dns) for more details.

2) Or is it just about updating any existing AKS cluster DNS with custom domain ?
    If yes, then it could be the specific requirement to AKS and it's related configuration. You may want to refer [AKS Docs](https://docs.microsoft.com/en-us/azure/aks/) for more details.

Hope this helps !

**Comment by ejstan** [comment]
Hi @sughosneo ,

I'm updating an existing AKS cluster DNS with a custom domain. 

For the side of AKS, I already updated the host indicated in the ingress to "app.company1.com". Problem is that I'm unable to replace the current domain name (sample.southeastasia.cloudapp.azure.com)  assigned on the IP to the custom domain (app.company1.com)

**Comment by sughosneo** [comment]
Hi @ejstan , thank you for the information. 

This seems to be the specific requirement related to AKS configuration. You may want to refer this [Customize CoreDNS with Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/aks/coredns-custom).  You can also reach out to [Azure Community Support](https://azure.microsoft.com/en-in/support/community/) if you need any further help on this topic.

As of now, I am closing this issue. Please feel free to reopen it if it's needed.
