### ISSUE TITLE
Replace docker.for.win.localhost with host.docker.internal in .env

### ISSUE THREAD

**Issue by InstanceFactory** [dotnet-architecture/eShopOnContainers#1397]
According to https://github.com/docker/for-win/issues/1764, `docker.for.win.localhost` is deprecated. The official new name is `host.docker.internal`.<br/>

When I tried to run eShopOnContainers on my Windows 10 machine, I was not able to login (as described e.g. by #1236 and #1242).<br/>

The current version of `.env` still contains `docker.for.win.localhost` for environment values to run the app locally in Windows. Changing `docker.for.win.localhost` to `host.docker.internal` in the `.env` file solved the issue for me.<br/>

I'm offering to make this change in the source code to help other (microservice) newbies like me not to run into this problem.<br/>

In case you agree, please assign this issue to me.<br/>

Best Regards,<br/>

Stefan

**Comment by sughosneo** [comment]
Hi Stefan, Thank you for pointing out.

Yes, `docker.for.win.localhost` is deprecated. In our recent wiki update, we have included `host.docker.internal` under [Known Behaviours](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes) section.

I agree with you updating respective scripts as well. If you could make the necessary changes and submit a PR. We can review and merge the changes in.

**Comment by InstanceFactory** [comment]
Hi Sumit,

Thanks, I will do so.

Regards,

Stefan

**Comment by sughosneo** [comment]
PR #1400 has been merged. So closing this issue.

**Comment by InstanceFactory** [comment]
Hi @sughosneo , thanks for merging and closing.
