### ISSUE TITLE
Solution items are outdated

### ISSUE THREAD

**Issue by m-knet** [dotnet-architecture/eShopOnContainers#1399]
Solutions items in mobile solutions and web solution are outdated.

There are elements that don't exist in the solution (like global.json, Local.testsettings) and others that are in parent folder (Nuget.config in mobile solutions).

I can create a PR with changes: [solution](https://github.com/m-knet/eShopOnContainers/commit/6b9398498e86101037b097757fb602a873bb2d4e)

**Comment by sughosneo** [comment]
Hi @m-knet, thanks for your feedback. Will review and update.

**Comment by sughosneo** [comment]
Hi @m-knet , sorry for the delay in getting back on this issue. 

Yes, if you could take the latest from the `dev` branch and submit a PR ? Will test and merge the changes.

Thank you.
