### ISSUE TITLE
Tests/Services/Application.FunctionalTests/Services/Marketing/appsettings.json contains duplicate Key

### ISSUE THREAD

**Issue by InstanceFactory** [dotnet-architecture/eShopOnContainers#1403]
The file `src/Tests/Services/Application.FunctionalTests/Services/Marketing/appsettings.json` contains the member `"SubscriptionClientName"` twice. This causes the test case `MarketingScenarios.Set_new_user_location_and_get_location_campaign_by_user_id` to fail, throwing the following error:<br/>
`System.FormatException : A duplicate key 'SubscriptionClientName' was found.`<br/>
Solution is to remove the second key definition, as both keys have the same value.<br/>
I'm offering to create a PR if you agree. Doing so, I would also sort the content in asc order.<br/>
Kind Regards,<br/>
Stefan

**Comment by InstanceFactory** [comment]
As commented on #1404, I will fix this issue as part of the same PR I will create for #1404.

**Comment by sughosneo** [comment]
As this has already been addressed in PR #1406 . So closing this issue. 

Thank you.
