### ISSUE TITLE
Sorry, there was an error : invalid_request

### ISSUE THREAD

**Issue by jeremiahflaga** [dotnet-architecture/eShopOnContainers#1405]
When I try to authorize Swagger Basket UI, I am getting this error

```
Sorry, there was an error : invalid_request
```

![image](https://user-images.githubusercontent.com/26346294/90728086-dd3fce80-e2f6-11ea-98f0-b1ba01255756.png)

**Comment by sughosneo** [comment]
Hi @jeremiahflaga , thanks for reaching out. I could see you are using `host.docker.internal` as docker DNS. 
Then you should use URL `http://host.docker.internal:5103/` for the basket API and try to authorize. Please see the below screenshots for your reference. 

![image](https://user-images.githubusercontent.com/13281246/90853866-fdc06500-e398-11ea-8833-e7f38982a8b5.png)

And then it should redirect you to Identity Server URL. After filling up the correct details you should see something like as per below. 

![image](https://user-images.githubusercontent.com/13281246/90853958-3c561f80-e399-11ea-825c-4ede2d327027.png)

Click on `Yes, Allow`. 

![image](https://user-images.githubusercontent.com/13281246/90853990-555ed080-e399-11ea-9966-5327507048b5.png)

Now if you make a call to Basket API you will notice token is getting passed along with header. 

![image](https://user-images.githubusercontent.com/13281246/90854105-af5f9600-e399-11ea-812c-3ce621cdd79f.png)

Hope this helps !

**Comment by sughosneo** [comment]
Hi @jeremiahflaga, just checking if you had a chance to look into this further. Thanks.

**Comment by sughosneo** [comment]
Hi @jeremiahflaga , I am closing this issue as of now. Please feel free to reopen it if you have any further questions.

Thank you.
