### ISSUE TITLE
Ordering.FunctionalTests fail due to missing appsettings entry

### ISSUE THREAD

**Issue by InstanceFactory** [dotnet-architecture/eShopOnContainers#1410]
The three unit tests `Get_get_all_stored_orders_and_response_ok_status_code, Cancel_order_no_order_created_bad_request_response, Ship_order_no_order_created_bad_request_response'` defined by the class `Ordering.FunctionalTests.OrderingScenarios`, fail, all showing the following error:

```
    Autofac.Core.DependencyResolutionException : An exception was thrown while activating Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator -> λ:Swashbuckle.AspNetCore.SwaggerGen.ISchemaGenerator -> Microsoft.Extensions.Options.OptionsManager`1[[Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorOptions, Swashbuckle.AspNetCore.SwaggerGen, Version=5.0.0.0, Culture=neutral, PublicKeyToken=d84d99fb0135530a]] -> Microsoft.Extensions.Options.OptionsFactory`1[[Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorOptions, Swashbuckle.AspNetCore.SwaggerGen, Version=5.0.0.0, Culture=neutral, PublicKeyToken=d84d99fb0135530a]] -> λ:Microsoft.Extensions.Options.IConfigureOptions`1[[Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorOptions, Swashbuckle.AspNetCore.SwaggerGen, Version=5.0.0.0, Culture=neutral, PublicKeyToken=d84d99fb0135530a]][] -> Swashbuckle.AspNetCore.SwaggerGen.ConfigureSchemaGeneratorOptions.
    ---- Autofac.Core.DependencyResolutionException : An exception was thrown while invoking the constructor 'Void .ctor(System.IServiceProvider, Microsoft.Extensions.Options.IOptions`1[Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions])' on type 'ConfigureSchemaGeneratorOptions'.
    -------- System.UriFormatException : Invalid URI: The format of the URI could not be determined.
```
Reason is that `appsettings.json` of the test project does not contain the setting `IdentityUrlExternal`. Adding this key and setting its value to `http://localhost:5105` makes the test cases pass.

If you agree, I will create a PR to fix this.

Kind Regards,

Stefan

**Comment by sughosneo** [comment]
Hi @InstanceFactory / Stefan, thank you for pointing it out and sorry for the delay in attending this issue.

Yes, the setting `IdentityUrlExternal` needs to be added in `\src\Services\Ordering\Ordering.FunctionalTests\appsettings.json`. 
Could you please submit a separate PR for this issue ? Will test and merge the changes.

**Comment by InstanceFactory** [comment]
Hi @sughosneo / Sumit,

No worries, took a while on my end too to simply add a single line. PR is created:  #1560 

Best wishes for the new year!

Stefan

**Comment by sughosneo** [comment]
> Hi @sughosneo / Sumit,
> 
> No worries, took a while on my end too to simply add a single line. PR is created: #1560
> 
> Best wishes for the new year!
> 
> Stefan

Hi @InstanceFactory / Stefan, 

Thank you for the PR. 

Wish you also a very happy new year in advance !  🙂

Closing this issue now, as it has already been fixed.
