### ISSUE TITLE
azure pipeline parameter error in multiarch job

### ISSUE THREAD

**Issue by fjvela** [dotnet-architecture/eShopOnContainers#1412]
Due a missing $ char in parameters.branch (line 29) multiarch job doesn't work propertly:

![image](https://user-images.githubusercontent.com/5806680/91267884-8e6dbb00-e774-11ea-97ca-c903212e9cb0.png)
![image](https://user-images.githubusercontent.com/5806680/91267814-6b430b80-e774-11ea-847c-dbbdba2a9c56.png)

**Comment by sughosneo** [comment]
Closing this issue as the changes are already merged. Thank you.
