### ISSUE TITLE
Coupon

### ISSUE THREAD

**Issue by YuriyTigiev** [dotnet-architecture/eShopOnContainers#1415]
Hello

In the documentation "Review the coupon service design" you are writing about a "Coupon" project in the src folder: - 
You can find an ASP.NET Core project for the coupon service in the src/Services/Coupon/Coupon.API directory. 

But this directory does not exist in the source code on the GitHub.  How can I get this project?

**Comment by sughosneo** [comment]
Hello @YuriTigiev, Thank you for reaching out. 

Yes, the "Review the coupon service design" section is part of `Create and deploy a cloud-native ASP.NET Core microservice` MS Learn module and the source code of coupon service 
is not present in the repository of `eShopOnContainers`.

You can download the source code after completing the MS learn module. For more details, you can refer `Download project files` under [Summary](https://docs.microsoft.com/en-us/learn/modules/microservices-aspnet-core/9-summary)

Hope this helps !

**Comment by YuriyTigiev** [comment]
@sughosneo  

Thank you for your attention. 
I have opened the solution from VS 2019 and I'm deploying and running locally the solution. 
What is a simple way to download the coupon project and add it to the solution?

**Comment by sughosneo** [comment]
> @sughosneo
> 
> Thank you for your attention.
> I have opened the solution from VS 2019 and I'm deploying and running locally the solution.
> What is a simple way to download the coupon project and add it to the solution?

The above mentioned MS Learn module is based on the `Azure Cloud Shell`. So you would require to download the source files to your local to add it your solution file.  Once you run the above command mentioned in the [Summary](https://docs.microsoft.com/en-us/learn/modules/microservices-aspnet-core/9-summary) section. It would actually create a Zip file in your Azure Storage like as per below :

![image](https://user-images.githubusercontent.com/13281246/91806724-aef0b600-ec49-11ea-9d71-2de484a507b1.png)

You can unzip the entire source code of `aspnet-learn` directory and fetch the respective `Coupon.API` project for adding it to your solution. 

Thanks.

**Comment by sughosneo** [comment]
Hi @YuriyTigiev, I am closing this issue as of now. Please feel free to reopen it, if you have any further questions.

Thank you.
