### ISSUE TITLE
Why is "OpenIdConnect" in AuthenticationSchemes a string literal instead of a string constant?

### ISSUE THREAD

**Issue by jeremiahflaga** [dotnet-architecture/eShopOnContainers#1423]
I can see this in the `AccountController` of the Web MVC project

``` csharp
[Authorize(AuthenticationSchemes = "OpenIdConnect")]
public class AccountController : Controller
{
    ...
```

I tried to search for an explanation for that and found this: https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-3.1

But the example there uses constant strings, like `JwtBearerDefaults.AuthenticationScheme`, instead of a literal string, like `"OpenIdConnect"`.

May I ask why that is the case? Is there no string constant for `"OpenIdConnect"`? How would one know which strings to put in there?

Thanks.

**Comment by sughosneo** [comment]
Hello @jeremiahflaga, thank you for your feedback.

Yes, insted of string "OpenIdConnect" you can also use `OpenIdConnectDefaults.AuthenticationScheme` which is part of `Microsoft.AspNetCore.Authentication.OpenIdConnect` package. 

It has a string constant as per below :

![image](https://user-images.githubusercontent.com/13281246/92879628-d1918480-f42a-11ea-9532-5112ed1c81a7.png)

Would you like to submit a PR to [eShopOnContainers repo](https://github.com/dotnet-architecture/eShopOnContainers/pulls) with the changes ?

**Comment by jeremiahflaga** [comment]
Hi @sughosneo , yes I would like to submit a PR.

I already created a pull request: https://github.com/dotnet-architecture/eShopOnContainers/pull/1424

**Comment by sughosneo** [comment]
Closing this issue, as the changes are already merged with `dev` branch. Thanks.
