### ISSUE TITLE
[Question] How to decomposite monolith?

### ISSUE THREAD

**Issue by kristx300** [dotnet-architecture/eShopOnContainers#1427]
Hi!
For example, monolith is a basic admin server that provides basic CRUD functionality with a user interface.
CRUD I mean: 
- Index with paging/searching
- Details with upload relations
- Updating model by id
- Delete model by id
- Autocomplete list for quick search and multiselect

Monolith has "Identity", "Blog", "Categories", "Tags", "Feedback".
Simple services, simple usage.
Services:

- Identity API
- Blog API
- Categories & Tags API
- Feedback API

Web:
- Web.Blog - route {url}/{something}
- Web.Admin - route {url}/admin/{something}
### [Q1] Did I divide correctly?
At what level should I implement CRUD functionality?
Specifically where? 
[1] API - Services - Controller
[2] Web - Controller

**Comment by sughosneo** [comment]
Hi @kristx300, thank you for reaching out. 

Yes, if your monolith application has - "Categories", "Tags", "Feedback" etc.. you can try to consider them as different business functionalities
and migrate them as separate microservices. But you need to be careful how you define the bounded context and keep them segregated from each other.

[Ans/Q1] - technically I would prefer to implement to CRUD functionality in the API layer. And the number of API(s) or services(s) depend on how 
you are planning to divide your application in different microservices based on the business domain.

[Ans/Q2] - Individual service component can hold it's own business logic and can interact with other services if requires. But it must have it's own separate
separate data store.

One of the popular ways of dividing a monolith application to microservices is using domain-driven design. You can refer the section 
[migrate monolith](https://docs.microsoft.com/en-us/azure/architecture/microservices/migrate-monolith) for more details.

You can also check this [MS Learn module](https://docs.microsoft.com/en-us/learn/modules/microservices-architecture/)

Hope this helps !

**Comment by kristx300** [comment]
@sughosneo Thanks you!
It would be awesome to have some examples from the series "How to ..."

**Comment by sughosneo** [comment]
> @sughosneo Thanks you!
> It would be awesome to have some examples from the series "How to ..."

Thank you for the feedback. 
CC : @nishanil
