### ISSUE TITLE
[Question] Injecting IEventBus in DbContext class

### ISSUE THREAD

**Issue by cybercop** [dotnet-architecture/eShopOnContainers#1429]
In OrderingContext class IMediator is injected via constructor

```
       public OrderingContext(DbContextOptions<OrderingContext> options, IMediator mediator) : base(options)
        {
            _mediator = mediator ?? throw new ArgumentNullException(nameof(mediator));


            System.Diagnostics.Debug.WriteLine("OrderingContext::ctor ->" + this.GetHashCode());
        }
```

and OrderingContextDesignFactory creates instance of OrderingContext

```
    public class OrderingContextDesignFactory : IDesignTimeDbContextFactory<OrderingContext>
    {
        public OrderingContext CreateDbContext(string[] args)
        {
            var optionsBuilder = new DbContextOptionsBuilder<OrderingContext>()
                .UseSqlServer("Server=.;Initial Catalog=Microsoft.eShopOnContainers.Services.OrderingDb;Integrated Security=true");

            return new OrderingContext(optionsBuilder.Options, new NoMediator());
        }

        class NoMediator : IMediator
        {
            public Task Publish<TNotification>(TNotification notification, CancellationToken cancellationToken = default(CancellationToken)) where TNotification : INotification
            {
                return Task.CompletedTask;
            }

            public Task Publish(object notification, CancellationToken cancellationToken = default)
            {
                return Task.CompletedTask;
            }

            public Task<TResponse> Send<TResponse>(IRequest<TResponse> request, CancellationToken cancellationToken = default(CancellationToken))
            {
                return Task.FromResult<TResponse>(default(TResponse));
            }

        }
```

would it be possible to Inject IEventBus class somehow, or are there any examples where following method actually dispatches events via event bus (maybe rabbitmq or azure servicebus)?\
```
        public async Task<bool> SaveEntitiesAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            // Dispatch Domain Events collection. 
            // Choices:
            // A) Right BEFORE committing data (EF SaveChanges) into the DB will make a single transaction including  
            // side effects from the domain event handlers which are using the same DbContext with "InstancePerLifetimeScope" or "scoped" lifetime
            // B) Right AFTER committing data (EF SaveChanges) into the DB will make multiple transactions. 
            // You will need to handle eventual consistency and compensatory actions in case of failures in any of the Handlers. 
            await _mediator.DispatchDomainEventsAsync(this);

            // After executing this line all the changes (from the Command Handler and Domain Event Handlers) 
            // performed through the DbContext will be committed
            var result = await base.SaveChangesAsync(cancellationToken);

            return true;
        }
```

**Comment by sughosneo** [comment]
Hello @cybercop , thank you for reaching out. 

Yes, you can inject the interface using DI. You can refer [`CatalogIntegrationEventService`](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Catalog/Catalog.API/IntegrationEvents/CatalogIntegrationEventService.cs) class for more details. 

Hope this helps !

**Comment by cybercop** [comment]
Not really. CatalogIntegrationEventService injects DbContext. I want the other way around.

**Comment by sughosneo** [comment]
> Not really. CatalogIntegrationEventService injects DbContext. I want the other way around.

I see. `DbContext` class comes with `Microsoft.EntityFrameworkCore` Assembly. So to my opinion, you could only inject the custom interfaces like `IEventBus` though the custom class which extends `DbContext`. As this question specific to EFCore, you may want to check it's [github repo](https://github.com/dotnet/efcore/) as well to see if there is any alternative options available.

And if you are looking for examples of where we dispatches events via event bus then you may want to refer the `PublishEventsThroughEventBusAsync` method in  [OrderingIntegrationEventService](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.API/Application/IntegrationEvents/OrderingIntegrationEventService.cs). By default it's using RabbitMQ but if you want you can configure that Azure Service bus.

Thank you.

**Comment by sughosneo** [comment]
Hi @cybercop , just checking if you have any further questions. Or Shall we close this issue ? Thank you.
