### ISSUE TITLE
Create a building block to manage idempotency

### ISSUE THREAD

**Issue by dsrodenas** [dotnet-architecture/eShopOnContainers#143]
In order to ensure idempotency in cases where has to be handled explicitly, we can create a **GenericHttpMessageIdempotency** BuildingBlock. This block should be based in the current Request Manager implemented in Order.Infrastructure, that is handling idempotency for the case of order creation.

**Comment by mvelosop** [comment]
Closing this issue as it's now included in the [roadmap](https://github.com/dotnet-architecture/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases#vnext)
