### ISSUE TITLE
[Mac] Identity Server doesn't work

### ISSUE THREAD

**Issue by adahhane** [dotnet-architecture/eShopOnContainers#1431]
Hello everyone
I tried all suggestions but it doesn't work for me on my Mac
I follow all the steps ,step by step, with no results.
There is my configuration,
![Capture d’écran 2020-09-15 à 15 47 09](https://user-images.githubusercontent.com/656154/93218767-df1c7680-f76a-11ea-8ed3-f3096d1089dc.png)
![Capture d’écran 2020-09-15 à 15 46 18](https://user-images.githubusercontent.com/656154/93218772-e04da380-f76a-11ea-8c8e-73cce717c2bd.png)
![Capture d’écran 2020-09-15 à 15 46 06](https://user-images.githubusercontent.com/656154/93218774-e04da380-f76a-11ea-89af-0e66b60f513a.png)
![Capture d’écran 2020-09-15 à 15 45 52](https://user-images.githubusercontent.com/656154/93218779-e2affd80-f76a-11ea-967e-6577f963fbae.png)

Maybe I missed up something
Thanks in advance

_Originally posted by @adahhane in https://github.com/dotnet-architecture/eShopOnContainers/issues/1124#issuecomment-692727145_

**Comment by sughosneo** [comment]
Hello @adahhane, thank you for reaching out.

Possibly the SQL server database for the Identity Server is still holding the old value of `localhost`.

Could you please try to clean up the sql volume too and try following steps ? 

- To do clean up 

```powershell

docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
docker volume rm $(docker volume ls -q)

```

> !IMPORTANT: Above commands will clean up all running containers and it's data in your MacOS/Workstation. So you want to be careful on that.

- To run the app 

```powershell
docker-compose up sqldata
```
once it's ready to accept the connection then you can bring up the other container by using the following command from a seperate terminal

```powershell
docker-compose up
```

- Once everything is up and running. Then you can open up InCognito/InPrivate browser window and try to access the app - http://docker.for.mac.localhost:5100/ 

Hope this helps !

**Comment by adahhane** [comment]
Hello @sughosneo, 
Thank you for this explanation, 
I already make those steps except the : docker-compose up sqldata.
Now it works like a charm.

But i have another issue when i'm trying to connect with the mvc application, I get this error.

![Capture d’écran 2020-09-16 à 16 19 50](https://user-images.githubusercontent.com/656154/93350017-7996bb80-f838-11ea-95e4-9ed7078a68c5.png)

Do you have any idea about it ?

Thanks in advance.

**Comment by sughosneo** [comment]
> Hello @sughosneo,
> Thank you for this explanation,
> I already make those steps except the : docker-compose up sqldata.
> Now it works like a charm.
> 
> But i have another issue when i'm trying to connect with the mvc application, I get this error.
> 
> ![Capture d’écran 2020-09-16 à 16 19 50](https://user-images.githubusercontent.com/656154/93350017-7996bb80-f838-11ea-95e4-9ed7078a68c5.png)
> 
> Do you have any idea about it ?
> 
> Thanks in advance.

Great ! For the "Correlation Failed" you can refer our [wiki page](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Frequent-errors#login-page---exception-correlation-failed)

Thank you.

**Comment by adahhane** [comment]
Thanks for your quickly response, 
Now all work perfectly 
Best regards,
