### ISSUE TITLE
azure-pipelines.yml - On-prem Azure Devops Server 2019 compatiblity  - Agent Pool problem

### ISSUE THREAD

**Issue by dervistalha** [dotnet-architecture/eShopOnContainers#1434]
Hello;
I  would like build eshoponcontainers on Azure Devops Server 2019 by using self-hosted agent/(s). My on-prem Azure Devops Server 2019 has 2 agents; one is Ubuntu agent and the other one is in my desktop-computer. I know Windows build is disabled in "dev" branch but not disabled in master branch. 

1)
when I attempt to build microservices "infrastructure" and "apigws", although I selected my agent pool which is named as "Linux" , Azure DevOpsServer 2019 didn't accept and said "Hosted Ubuntu 1604 pool couldn't found." As a workaround, I re-created my Linux agent pool and named as "Hosted Ubuntu 1604". That workaround worked, for microservices "infrastructure" and "apigws" but not others.

2)
Although I select "dev" branch as default and set in YAML page and also select my self-hosted "Hosted Ubuntu 1604" pool, when I attempt to build all other microservices (in dev branch) except infrastructure and apigws, on-prem Azure Devops Server 2019 gives following error:

`The pipeline is not valid. Could not find a pool with name Hosted Windows 2019 with VS2019. The pool does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.,`

![image](https://user-images.githubusercontent.com/71238946/93407381-bc897b00-f89a-11ea-9929-3ef41ecf9b91.png)

![image](https://user-images.githubusercontent.com/71238946/93407398-c57a4c80-f89a-11ea-91b6-28916de89c87.png)

![image](https://user-images.githubusercontent.com/71238946/93407461-ec388300-f89a-11ea-9377-d4ab1a0ac082.png)

Could you please advise where does "Hosted Windows 2019 with VS2019" expression comes from? Am I missing something?

**Comment by dervistalha** [comment]
An update:
I created a pool and named it "Hosted Windows 2019 with VS2019" and added an agent in it. Now when I trigger the build, the build process checks there is an agent pool named "Hosted Windows 2019 with VS2019" in "on-prem Azure Devops Server 2019", the build process notices Windows agent exists, then it moves forward and build the packages in "Hosted Ubuntu 1604" pool as configured (dev branch).

Summary:
If there is no an agent pool named "Hosted Windows 2019 with VS2019" in on-prem "Azure Devops Server 2019", Linux build process can not be started even if it doesn't use Windows agent is not used for build process. (for dev branch)

**Comment by sughosneo** [comment]
Hello @dervistalha, thank you for the update. 

To my opinion, this scenario is more aligned to the Azure DevOps pipeline and it's related configuration. [Azure DevOps Community](https://developercommunity.visualstudio.com/spaces/21/index.html) might be a good forum for this question.

**Comment by sughosneo** [comment]
Hi @dervistalha , I am closing this issue as of now. Please feel free to reopen it if you have any further questions. 

Thank you.
