### ISSUE TITLE
Error: The antiforgery token could not be decrypted

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#145]
This exceptions is raised sometimes when deploying to a regular Docker host. I'm testing our DEV branch.
Also in Kubernetes environments, as mentioned by Dan.

The solution for IIS Windows machines is to run the dataprotection provisioning script on the server: 
https://github.com/aspnet/DataProtection/blob/dev/Provision-AutoGenKeys.ps1
https://docs.microsoft.com/en-us/aspnet/core/hosting/dataprotection

But for Docker containers and orchestrators might be a different solution.
Need to research on this.

Related to these posts:
http://blog.stoverud.no/posts/asp-net-core-dataprotection-and-azure-web-apps/
http://www.it1me.com/it-answers?id=34319802&ttl=MVC+6+WebFarm%3A+The+antiforgery+token+could+not+be+decrypted
http://iamdotnetcrazy.blogspot.com/2013/08/how-to-solve-anti-forgery-token-could.html
https://github.com/aspnet/IISIntegration/issues/227
https://github.com/aspnet/Antiforgery/blob/ad90db343c437283d809dab12f89b51116a25151/src/Microsoft.AspNetCore.Antiforgery/Internal/DefaultAntiforgeryTokenSerializer.cs#L55

**Comment by chlowell** [comment]
I saw this in deployment. When the apps are hosted at the same location, one may try to decrypt another's token because the paths are the same. I solved this by setting application discriminators; that fix is in #142.

**Comment by doc** [comment]
Was this problem ever solved for you guys? Struggling with same. Deployment target in my case is a linux container running on CloudFoundry.

**Comment by chlowell** [comment]
I didn't see it again after 2f3df2715d2deb5520044cb351144641b8d8f7c7.

**Comment by Netstep** [comment]
I have the same issue, ASP.NET core 2.0:
fail: Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery[7] An exception was thrown while deserializing the token.System.InvalidOperationException: The antiforgery token could not be decrypted.---> System.Security.Cryptography.CryptographicException: The key {f706e4a2-41c3-44d5-bde9-a9d36df9b42f} was not found in the key ring.
...

Please Re-open the issue, this is really annoying...
