### ISSUE TITLE
Question about protobuf files for services located in a separate machine

### ISSUE THREAD

**Issue by jeremiahflaga** [dotnet-architecture/eShopOnContainers#1477]
Hi,

I noticed that the module `Web.Shopping.HttpAggregator` is directly pointing to the protbuf files of the Services modules

``` xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AssemblyName>Web.Shopping.HttpAggregator</AssemblyName>
    ...
  </PropertyGroup>
  ...
  <ItemGroup>
    <Protobuf Include="..\..\..\Services\Basket\Basket.API\Proto\basket.proto" GrpcServices="Client" />
    <Protobuf Include="..\..\..\Services\Catalog\Catalog.API\Proto\catalog.proto" GrpcServices="Client" />
    <Protobuf Include="..\..\..\Services\Ordering\Ordering.API\Proto\ordering.proto" GrpcServices="Client" />
  </ItemGroup>

</Project>
```

In the case where the `Basket.API` is located in a different machine -- does that mean that I need to have 2 duplicate copies of the `basket.proto` file? One copy in `Web.Shopping.HttpAggregator` and another one copy in `Basket.API`?

I'm not yet sure if my question makes sense. If it does not make sense, please tell me so I can revise it.

Thanks.

**Comment by sughosneo** [comment]
Hi @jeremiahflaga, thank you for reaching out. 

Yes, in the actual production scenario client (`For e.g: Web.Shopping.HttpAggregator`) and server (`For e.g : Basket.API`), each will have it's own copy of same `protobuf` file. And that would be deployed separately.
For simplicity, we keep all the microservices code under one repo and that's the reason there is a flexibility to refer the file in cross projects but in the actual production scenario that might not be feasible.

Hope this helps !

**Comment by jeremiahflaga** [comment]
Hi @sughosneo , yes it helps so much. Thank you for answering my question.
