### ISSUE TITLE
[SPA] Update SPA client app to Angular 4

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#148]
Current version of the SPA client web app of eShopOnContainers is using **Angular 2**.
**Angular 4** has recently been released:
[March 23, 2017]
http://angularjs.blogspot.com/2017/03/angular-400-now-available.html   

Not sure why they jumped Angular 3 and went to Angular 4... 
http://www.infoworld.com/article/3150716/application-development/forget-angular-3-google-skips-straight-to-angular-4.html

Well, kind of Windows 10, nobody does consecutive numbers anymore... ;)

I think that eShopOnContainers versions are going to be PRIME NUMBERS.
So, v2, v3, v5, v7, v11, v13, v17, v19, v23... ;) just kidding...

**Comment by BillWagner** [comment]
I think we should use Fibonacci numbers:
v1, v2, v3, v5, v8, v13 ....

Number nerd note: 19 and 23 are two consecutive prime numbers whose sum is 42. It's the answer to everything.

**Comment by ardalis** [comment]
Why not both? http://mathworld.wolfram.com/FibonacciPrime.html

**Comment by jrgcubano** [comment]
I think the project should try to simplify and rely on the current standard (angular-cli) for this part.

**Comment by eiximenis** [comment]
Yep sure!
We'll update the project to use latest angular & angular-cli.
Thanks for feedback!

**Comment by eiximenis** [comment]
SPA is using angular 4 now :)
Closing issue.
