### ISSUE TITLE
System.Exception: 'type=T-Shirt,Other,Roslyn Red T-Shirt,Roslyn Red T-Shirt does not exist in catalogTypes

### ISSUE THREAD

**Issue by rseremeta** [dotnet-architecture/eShopOnContainers#1480]
The issue is in the CatalogContextSeed class in the CreateCatalogitem()
The catalogTypes are: Mug, T-Shirt,Sheet,USB Memory Stick, CatalogTypeTestOne,CatalogTypeTestTwo

How do I fix this? Many thanks.

**Comment by rseremeta** [comment]
FurtherMore I get a 503  from this call : var uri = API.Catalog.GetAllCatalogItems(_remoteServiceBaseUrl, page, take, brand, type);
Details:
System.Net.Http.HttpRequestException
  HResult=0x80131500
  Message=Response status code does not indicate success: 503 (Service Unavailable).
  Source=System.Net.Http
  StackTrace:
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.<GetStringAsyncCore>d__35.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.eShopOnContainers.WebMVC.Services.CatalogService.<GetCatalogItems>d__5.MoveNext() in C:\Users\rsere\Documents\Projects\eShopOnContainers\src\Web\WebMVC\Services\CatalogService.cs:line 35

  This exception was originally thrown at this call stack:
    System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
    System.Net.Http.HttpClient.GetStringAsyncCore(System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage>)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult()
    Microsoft.eShopOnContainers.WebMVC.Services.CatalogService.GetCatalogItems(int, int, int?, int?) in CatalogService.cs

In the docker container the Catalog table is also empty.

**Comment by sughosneo** [comment]
Hi @rseremeta, thank you for reaching out. 

Could you please make sure of the following ?

- You have the right configuration if you are using docker desktop ? - [Configure Docker](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#configure-docker)
- Once you have verified that you can run  below mentioned steps :

    - To do clean up 

    ```powershell

    docker stop $(docker ps -aq)
    docker rm $(docker ps -aq)
    docker volume rm $(docker volume ls -q)

    ```

    > !IMPORTANT: Above commands will clean up all running containers and it's data in your workstation. So you want to be careful on that.

    - To run the app 

    ```powershell
    docker-compose up sqldata
    ```
    once it's ready to accept the connection then you can bring up the other containers by using the following command from a different powershell window/tab

    ```powershell
    docker-compose up
    ```

**Comment by rseremeta** [comment]
Thanks for reaching out @ sughosneo
I am building and running the containers using visual studio 2019. I have followed the instructions for vs 2019 (https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#optional---use-visual-studio) . Is it still necessary to run the above instructions from the command line?

**Comment by rseremeta** [comment]
I can run the application from the command line , I have issues running it from visual studio 2019. Hope that helps.

**Comment by sughosneo** [comment]
> I can run the application from the command line , I have issues running it from visual studio 2019. Hope that helps.

Thanks for the update @rseremeta 

Yes, in VS2019 scenario you don't need to run `docker-compose up` command. But you can do a clean up of your existing docker containers, volumes and images by following below commands :

```powershell

docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
docker volume rm $(docker volume ls -q)
docker rmi -f $(docker images -a -q)

```
Once everything is cleaned then you can select `docker-compose` project as a startup project in your Visual Studio and press F5 to run the entire applications.

**Comment by rseremeta** [comment]
Hi @sughosneo ,

I have done all the cleaning steps . I am still getting the same exception as before . 
One more thing I want to mention is that in the CatalogContextSeed.cs on line 239 
PictureUri = column[Array.IndexOf(headers, "pictureuri")].Trim('"').Trim(), (the headers array does not contain pictureuri 
header array is( "catalogtypename", "catalogbrandname" ,"description","name","picturefilename","availablestock","onreorder") . 
Replacing pictureuri with picturefilename triggers the error as described before. Without this change I get an IndexOutOfRangeException.

**Comment by sughosneo** [comment]
Hi @rseremeta , thanks for the update. 

Yes, after further debugging I see similar behavior in Visual Studio. But the message is different that what you see. Here it is :

```shell
[06:48:38 ERR] EXCEPTION ERROR: does not contain required header 'pictureFileName'
System.Exception: does not contain required header 'pictureFileName'
``` 
- This is related to #1350 

But having said, that shouldn't stop the seeding to the `CatalogItem` table or running the `Catalog.API` containers. 
Because if you see the code `Line : 191`, you'll notice if there is any exception it will pull the items from the method `GetPreconfiguredItems()`

For further debugging at your end, you can put breakpoints in the following lines. 
- Catalog.API\Program.cs - Line : 39
- CatalogContextSeed.cs - Line : 24
- CatalogContextSeed.cs - Line : 52 (To check if method `GetCatalogItemsFromFile` is getting called)
- CatalogContextSeed.cs - Line : 174

And if you want just populate the data from using preconfigured items (for e.g: from `GetPreconfiguredItems()` method) then you can change the value of `UseCustomizationData` to `False` in the docker-compose file.

Hope this helps !

**Comment by rseremeta** [comment]
Hi @sughosneo 

Yes we are right, the issue is related to #1350 . I think the root cause for my problem was that on line 8 in the CatalogItems file there was a typo .
the items on line 8 => "T-Shirt,Other,Roslyn Red T-Shirt,Roslyn Red T-Shirt\",12,7.png,8,false" ., and instead of getting 8 items I was getting only 5.  With the GetPreconfiguredItems() method there was no issue.

Thanks for all your help on this issue.

**Comment by sughosneo** [comment]
Hi @rseremeta , thank you for the update.

I am closing this issue as of now. If you have any question, please feel free to reopen it.
