### ISSUE TITLE
ocelot and grpc api gateway

### ISSUE THREAD

**Issue by chhotalamansukh** [dotnet-architecture/eShopOnContainers#1482]
Download latest code and its very nice architecture. Need your advice ocelot and grpc both used in api gateway or Envoy and grpc both used in api gateway?

**Comment by mvelosop** [comment]
Hi @chhotalamansukh,

Ocelot doesn't support gRPC, so Envoy would be the way to go.

Hope this helps!

**Comment by chhotalamansukh** [comment]
Morning @mvelosop 
Thanks for quick response!
Can you advice which is the best Envoy and gRPC or other technologies?

**Comment by mvelosop** [comment]
Well, as usual, it depends... always 😉

You can take a look an explore the use of Envoy + gRPC in the Envoy+aggregators microservices beginning here: https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src/ApiGateways

Hope this helps.

**Comment by chhotalamansukh** [comment]
Hey @mvelosop 
Thank a lot for provide link 👍 
Which is better NGINX + gRPC or Envoy + gRPC?
