### ISSUE TITLE
Invalid number format in SPA

### ISSUE THREAD

**Issue by tsmith-sdm** [dotnet-architecture/eShopOnContainers#1483]
https://github.com/dotnet-architecture/eShopOnContainers/commit/a1909521fde9089c1a65c5e875b99aa6e6b0b618#diff-9232bd994f415286c3ebb9ddb07fb3eaL43

number:'3.2-2' forces the price to have a minimum of 3 digits before the decimal which fills with 0's so $8.50 becomes $008.50

**Comment by sughosneo** [comment]
Hi @tsmith-sdm , thank you for pointing that out. Good catch 👍 

Would you like to submit a PR ?

**Comment by sughosneo** [comment]
Hi @tsmith-sdm, quick update - I have fixed this issue in PR #1496

Thank you.
