### ISSUE TITLE
Task NavigationService.RemoveFromBackStack(), returns Task.FromResult(bool)

### ISSUE THREAD

**Issue by PRS-M** [dotnet-architecture/eShopOnContainers#1484]
In the solution for Mobile Apps, eShopOnContainers.Services.NavigationService has two methods that are marked as returning Task and since the internal calls to Navigation of MainPage are synchronous, they utilize Task.FromResult(true) to enable asynchronous-like usage of those methods.

Would it not be better to just use Task.CompletedTask since Task.FromResult(true) is just dummy implicitly cast to Task that returns no value?

```
        public Task RemoveLastFromBackStackAsync()
        {
            var mainPage = Application.Current.MainPage as CustomNavigationView;

            if (mainPage != null)
            {
                mainPage.Navigation.RemovePage(
                    mainPage.Navigation.NavigationStack[mainPage.Navigation.NavigationStack.Count - 2]);
            }

            return Task.FromResult(true);
        }

        public Task RemoveBackStackAsync()
        {
            var mainPage = Application.Current.MainPage as CustomNavigationView;

            if (mainPage != null)
            {
                for (int i = 0; i < mainPage.Navigation.NavigationStack.Count - 1; i++)
                {
                    var page = mainPage.Navigation.NavigationStack[i];
                    mainPage.Navigation.RemovePage(page);
                }
            }

            return Task.FromResult(true);
        }
```

**Comment by sughosneo** [comment]
Hi @PRS-M , thank you for reaching out.

`Task.FromResult(true)` had been used in that code snippet just to keep a provision to return data to the caller. As method signature is actually not returning any value to the caller, yes we can use `Task.CompletedTask` to return only task to the caller without any data.

Hope this helps !

**Comment by sughosneo** [comment]
Hi @PRS-M, Considering the original question has been addressed, I am closing this issue as of now. 
If you have any further questions, please feel free to reopen it. 

Thank you.
