### ISSUE TITLE
webspa container does not build when running `docker-compose up

### ISSUE THREAD

**Issue by Dudelsb** [dotnet-architecture/eShopOnContainers#1485]
When I build the application using docker compose-up, the webspa container fails to build .
This issue is similiar to   
https://github.com/dotnet-architecture/eShopOnContainers/issues/1474

I'm still facing this issue.

@sughosneo - Could you please check

![image](https://user-images.githubusercontent.com/6405166/95495135-98fab180-09bc-11eb-83e3-53404efa1a08.png)

[docker_error.txt](https://github.com/dotnet-architecture/eShopOnContainers/files/5350449/docker_error.txt)

**Comment by sughosneo** [comment]
Hi @Dudelsb, thank you for reaching out. 

I have cloned the `dev` branch fresh in 2 different environments and it works for me.

Could you please try to clean the `npm` cache by using the below command ?

``` powershell
npm cache clean --force
OR 
npm cache verify
```

And then cloned the `dev` branch again if possible to a new directory location and try to build  ?

But before that if you want to clean up the existing containers and docker images to start from scratch you could follow below steps.

- To do clean up 

```powershell

docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
docker volume rm $(docker volume ls -q)

```

> !IMPORTANT: Above commands will clean up all running containers and it's data in your MacOS/Workstation. So you want to be careful on that.

- To run the app 

```powershell
docker-compose up sqldata
```
once it's ready to accept the connection then you can bring up the other container by using the following command from a seperate terminal

```powershell
docker-compose up
```

Hope this helps !

**Comment by Dudelsb** [comment]
Thanks @sughosneo  for looking into this .
It works
