### ISSUE TITLE
How is API gateway implemented

### ISSUE THREAD

**Issue by Dudelsb** [dotnet-architecture/eShopOnContainers#1487]
Hi ,
I have taken latest from Dev branch.
I wish to understand how is API gateway working .
When I open solution in visual studio Under  ApiGateway--->Envoy folder     I don't see  envoy configuration file for  webShopping Aggregator  , even though it is present in the folder structure of solution.
![image](https://user-images.githubusercontent.com/6405166/95668038-c8134d80-0b8b-11eb-8b71-a4fbf204e18c.png)

The only configuration file visible for APIgateway is under  Mobile.BFF.Shopping  and that seems to be for Ocelot Apigateway and not the Envoy APigateway.

IS there something I'm missing ?
@sughosneo  , please help

**Comment by sughosneo** [comment]
Hi @Dudelsb , thank you for reaching out. 

Yes, though below directories are part of the source code but not added into the solution that's the reason when you open up the solution file `eShopOnContainers-ServicesAndWebApps` and navigate to the location `src\ApiGateways\Envoy\config` you don't see the similar folder structure and the respective envoy files.

![image](https://user-images.githubusercontent.com/13281246/95707981-b65ba400-0c78-11eb-8462-28e4986374f4.png)

If you want you can add those existing item after creating `New Solution Folder`

Hope this helps !

**Comment by sughosneo** [comment]
You could also refer to the wiki page [API Gateway](https://github.com/dotnet-architecture/eShopOnContainers/wiki/API-gateways)  to know more about the implementation and architecture.

**Comment by Dudelsb** [comment]
Thankyou @sughosneo  for replying .
So if I understand correctly , the solution in its present state  has one envoy configuration file  under Mobile.BFF.Shopping and that is being used by all other api gateways for routing the requests.
Is that correct ?

**Comment by sughosneo** [comment]
Hi @Dudelsb , the solution has 4 envoy configuration files in total, which gets deployed separately.
2 - for the web application and another 2 for the mobile app. It has further been categorized to group `webshopping` and `marketing` related api(s) and it's relevant request separately.

Thank you.

**Comment by Dudelsb** [comment]
Thanks @sughosneo for clarifying on the issue
