### ISSUE TITLE
Login fail

### ISSUE THREAD

**Issue by Edmand** [dotnet-architecture/eShopOnContainers#1492]
I got the latest version and was able to run the web application on http://docker.for.win.localhost:5100/. When I click on the Login I am getting the following error. Any help is appreciated.

An unhandled exception occurred while processing the request.
InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden]'.
Microsoft.IdentityModel.Protocols.ConfigurationManager<T>.GetConfigurationAsync(CancellationToken cancel)

Stack Query Cookies Headers
InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden]'.
Microsoft.IdentityModel.Protocols.ConfigurationManager<T>.GetConfigurationAsync(CancellationToken cancel)
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
Microsoft.AspNetCore.Authentication.AuthenticationHandler<TOptions>.ChallengeAsync(AuthenticationProperties properties)
Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, string scheme, AuthenticationProperties properties)
Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAlwaysRunResultFilters()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by sughosneo** [comment]
Hi @Edmand, thank you for reaching out. 

I could see you are trying to access Web MVC client. Are you using docker-compose to launch the application? or  Visual studio?
This seems to be a networking issue. You could try to do the following :

- Refer [Configure Local Networking](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#configure-local-networking) section to verify all necessary configurations are in place.
- After doing that, you can use `docker-compose` to bring up the solution.
- And then you could use the url `http://host.docker.internal:5100/` to run the Web MVC. 

You could also refer one of the old issue  https://github.com/dotnet-architecture/eShopOnContainers/issues/1126 on similar aspects.
>!Note: Please note, since then few of the configuration got updated. For e.g instead of `docker.for.win.localhost`, `host.docker.internal` is used hostname.

Hope this helps !

**Comment by sughosneo** [comment]
Hi @Edmand , just checking if you had a chance to look into this further ? Thanks.

**Comment by Edmand** [comment]
I have done the configuration you suggested but still getting the
error " Sorry,
there was an error *: unauthorized_client"*
The Health Checks are showing all greens for all services. Do you have any
other suggestions I could try?

Have a nice day
-Edmand-

**Comment by sughosneo** [comment]
Hi @Edmand , thanks for the update. 

For the error message `Sorry, there was an error : unauthorized_client`, you may want to refer [unauthorized_client error on Login](https://github.com/dotnet-architecture/eShopOnContainers/wiki/unauthorized_client-error-on-login) page.  Also, you need to use below urls while accessing the applications.

Web MVC : http://host.docker.internal:5100/
Web SPA : http://host.docker.internal:5104/

Hope this helps !

**Comment by sughosneo** [comment]
Hi @Edmand, considering the original issue has been addressed, I am closing this issue as of now. If you face any further challenges, please feel free to reopen it.
