### ISSUE TITLE
Ports unavailable due to access permissions errors

### ISSUE THREAD

**Issue by rspiewak47** [dotnet-architecture/eShopOnContainers#1498]
Building the project - Visual Studio 2019:
3>ERROR: for dockercompose8984638915709408758_seq_1  Cannot start service seq: Ports are not available: listen tcp 0.0.0.0:5340: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
3>Creating dockercompose8984638915709408758_mobilemarketingapigw_1 ... error
3>ERROR: for dockercompose8984638915709408758_mobilemarketingapigw_1  Cannot start service mobilemarketingapigw: Ports are not available: listen tcp 0.0.0.0:5201: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
3>Creating dockercompose8984638915709408758_webmarketingapigw_1    ... error
3>ERROR: for dockercompose8984638915709408758_webmarketingapigw_1  Cannot start service webmarketingapigw: Ports are not available: listen tcp 0.0.0.0:5203: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
3>Creating dockercompose8984638915709408758_mobileshoppingapigw_1  ... error
3>ERROR: for dockercompose8984638915709408758_mobileshoppingapigw_1  Cannot start service mobileshoppingapigw: Ports are not available: listen tcp 0.0.0.0:5200: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
3>Creating dockercompose8984638915709408758_sqldata_1              ... error
3>ERROR: for dockercompose8984638915709408758_sqldata_1  Cannot start service sqldata: Ports are not available: listen tcp 0.0.0.0:5433: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
3>Creating dockercompose8984638915709408758_webshoppingapigw_1     ... error
3>ERROR: for dockercompose8984638915709408758_webshoppingapigw_1  Cannot start service webshoppingapigw: Ports are not available: listen tcp 0.0.0.0:5202: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
...
3>ERROR: for seq  Cannot start service seq: Ports are not available: listen tcp 0.0.0.0:5340: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
3>ERROR: for mobilemarketingapigw  Cannot start service mobilemarketingapigw: Ports are not available: listen tcp 0.0.0.0:5201: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
3>ERROR: for webmarketingapigw  Cannot start service webmarketingapigw: Ports are not available: listen tcp 0.0.0.0:5203: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
3>ERROR: for mobileshoppingapigw  Cannot start service mobileshoppingapigw: Ports are not available: listen tcp 0.0.0.0:5200: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
3>ERROR: for sqldata  Cannot start service sqldata: Ports are not available: listen tcp 0.0.0.0:5433: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
3>ERROR: for webshoppingapigw  Cannot start service webshoppingapigw: Ports are not available: listen tcp 0.0.0.0:5202: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by rspiewak47** [comment]
If I restart the Docker desktop, I generally only get 1 error on trying to run. For example:
Severity	Code	Description	Project	File	Line	Suppression State
Error	DT1001	ERROR: for mobilemarketingapigw  Cannot start service mobilemarketingapigw: Ports are not available: listen tcp 0.0.0.0:5201: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
If the error persists, try restarting Docker Desktop.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	385

**Comment by sughosneo** [comment]
Hi @rspiewak47, thank you for reaching out.

The error message says ports are not available for the docker container to use.  That might be because of some firewall restriction related to network type (domain, private or public).

Are you using a corporate computer with VPN or behind a firewall? 

You might want to take a look at the [Windows setup wiki page (networking section)](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#configure-local-networking) and also at the [Additional resources section in the same page](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#additional-resources).

You can also use [TCPView](https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview) to check if there are any other services listening on those same ports.

Hope this helps.

**Comment by sughosneo** [comment]
Hi @rspiewak47 , just checking if you had a chance to look into this further ? Thanks.

**Comment by sughosneo** [comment]
Hi @rspiewak47 , I am closing this issue as of now. If you have any further questions, please feel free to reopen it. 

Thank you.
