### ISSUE TITLE
Files missing in src/ApiGateways/Envoy

### ISSUE THREAD

**Issue by jakubiszon** [dotnet-architecture/eShopOnContainers#1504]
The Dockerfile is specified in the solution but is not part of the codebase. Same goes for files in config directory.

**Comment by sughosneo** [comment]
Hi @jakubiszon, thank you for pointing it out.

We already have an open item on updating the solution file with a few of the missing items. Ref : #1399

I have included `Envoy` config related files within the solution `eShopOnContainers-ServicesAndWebApps` for easy understanding. 
Please note, I have only included `Web` related configuration and left the `mobile` specific directories aside as internally we are evaluating a few of the options to manage or update `mobile` related projects or solutions best possible way.

I would also like to comment on the fact that not all the files need to get added in the .net solution file. 
In the microservices architecture, each microservice would have its own repository where it might not be necessary all of those services will get loaded through one solution file.  For simplicity, in `eShopOnContainers` we have included all microservices under one repository and that's the reason all files (source code,configuration, infra structure etc.) are part of one repository. It's might not necessary be applicable in the actual production scenarios.

Hope this helps !
