### ISSUE TITLE
contributing to this eShopOnContainers

### ISSUE THREAD

**Issue by anjoy8** [dotnet-architecture/eShopOnContainers#1505]
Hi, I'm Anson, Microsoft MVP, vlogger, and I particularly like this architecture.
I am explaining and the promotion of the architecture (https://www.bilibili.com/video/BV1nT4y1L7vd) within out community.

**Comment by anjoy8** [comment]
I want to join the .NET Application Architecture organization and develop together.

**Comment by sughosneo** [comment]
Hi @anjoy8, thank you for the PR.

Great to see your video and different contribution. 👍
Please note, your contribution is important and valuable to us and for the community.

You can look into the list of open issues and try to fix whichever is possible. Items marked as help wanted could be a good place to start. I will also try to ping you in different PRs for suggestions or validations.
Please feel free to share your thoughts, ideas and feedback.

Thanks again !
