### ISSUE TITLE
Support Blazor WebAssembly and Blazor Server

### ISSUE THREAD

**Issue by ghd258** [dotnet-architecture/eShopOnContainers#1506]
Support Blazor WebAssembly and Blazor Server

**Comment by dereklew** [comment]
What would be the plan for the Blazor support?

**Comment by sughosneo** [comment]
Hi @ghd258, @dereklew - thank you for reaching out. 

There have been few discussions going on internally, for updating the WebSPA to Blazor App, but nothing concrete as of now. If something gets finalized, will post an update. 

Hope this helps !

Thank you.

**Comment by dereklew** [comment]
Along with the .NET 5 impending release, would Blazor be on the card as well,
