### ISSUE TITLE
Orleans option?

### ISSUE THREAD

**Issue by GaTechThomas** [dotnet-architecture/eShopOnContainers#1507]
With the various "eShopOn" options, does the team have any plans to create an eShopOnOrleans?

For reference, here's the Orleans repo:

https://github.com/dotnet/orleans

**Comment by sughosneo** [comment]
Hi @GaTechThomas, thank you for reaching out.

At this moment we don't have any plans yet to create the `eShopOnOrleans`. If anyone from the community does that, then we will be happy to link that in our wiki.

**Comment by sughosneo** [comment]
Hi @GaTechThomas , closing this issue as of now. If you have any further questions, please feel free to reopen it. 

Thanks.
