### ISSUE TITLE
Duplicate claim

### ISSUE THREAD

**Issue by dvdsantana** [dotnet-architecture/eShopOnContainers#1509]
https://github.com/dotnet-architecture/eShopOnContainers/blob/b196622846ec9de2309d22e4ae91232edc7cf9a1/src/Web/WebMVC/Infrastructure/Middlewares/ByPassAuthMiddleware.cs#L66

**Comment by sughosneo** [comment]
Hi @dvdsantana , thank you for pointing it out. 👍 

There is a PR https://github.com/dotnet-architecture/eShopOnContainers/pull/1508 already open for this related topic. Added a comment in there to remove the duplicate claim. That should take care of this issue.

**Comment by anjoy8** [comment]
Hi,all
For similar issues, I have updated other changes.
See more:https://github.com/dotnet-architecture/eShopOnContainers/pull/1508

**Comment by sughosneo** [comment]
> Hi,all
> For similar issues, I have updated other changes.
> See more:#1508

Yes, thank you @anjoy8 . 

@dvdsantana - I will close this issue as of now.  This is an extensions of #1495 and the submitted PR has fixes for both the scenarios. Please feel free to reopen it if you have any further questions. Thank you.
