### ISSUE TITLE
Where I can find coupon service in this project?

### ISSUE THREAD

**Issue by pesetskyps** [dotnet-architecture/eShopOnContainers#1510]
Sorry guys, maybe it's jsut me, but I don't get where to find the placeholder for coupon service that I can use in tutorial   
[Exercise - Add the coupon service](https://docs.microsoft.com/en-us/learn/modules/microservices-aspnet-core/6-add-coupon-service)

In tutorial is stated which assume it should be in the repository, but its not. Please help to understand
> In Controllers/CouponController.cs, replace the comment // Add the GetCouponByCodeAsync method with the following code:

**Comment by sughosneo** [comment]
Hi @pesetskyps, thank you for reaching out.

As of now, the "Coupon" service module is not integrated with the `dev` branch in `eShopOnContainers` repo. 
But if you want to explore the `Coupon API` code you can refer [Create and deploy a cloud-native ASP.NET Core microservice](https://docs.microsoft.com/en-us/learn/modules/microservices-aspnet-core/)
You should be able to download the project file by the step mentioned by [Download project files](https://docs.microsoft.com/en-us/learn/modules/microservices-aspnet-core/9-summary)

Hope this help !

**Comment by pesetskyps** [comment]
thank you for help. I didn't think that primary assumption is that it all should be done in cloud shell.

**Comment by sughosneo** [comment]
> thank you for help. I didn't think that primary assumption is that it all should be done in cloud shell.

I am closing this issue as of now. If you have any further questions, please feel free to reopen it. 

Thank you.
