### ISSUE TITLE
Using Bridge to Kubernetes on eShopOnContainers

### ISSUE THREAD

**Issue by wely** [dotnet-architecture/eShopOnContainers#1511]
Hi folks,

I raised an rather generic issue here while setting up Bridge for this project. https://github.com/microsoft/mindaro/issues/75.

By any change has anybody successfully done that on this project eShopOnContainers?

**Comment by sughosneo** [comment]
Hi @wely, thank you for reaching out.

We have a plan to work on this in the future. At this moment, internally we are exploring the possibility to use `Bridge to Kubernetes` in our `eShopOnContainers`.  But we haven't started any work, related to that yet. 


Having said that, please note we are actively working on porting the `eShop` application on `Dapr`. For more details, you can refer [this comment](https://github.com/dotnet-architecture/eShopOnContainers/issues/1161#issuecomment-709987888)

Hope this helps !

**Comment by sughosneo** [comment]
Hi @wely , I am closing this issue now. Please feel free to reopen if you have any further questions.

Thank you.

**Comment by maucaro** [comment]
Is there any progress on this issue? This could be one possible answer to the question I posed on #1673 . Bottom line is that I have not found an efficient inner development loop process for eShopOnContainers and this would seem to me to be a deal breaker for many.
