### ISSUE TITLE
Not able to log in when running application through Visual Studio

### ISSUE THREAD

**Issue by q-bertsuit** [dotnet-architecture/eShopOnContainers#1517]
When I start the application via docker-compose -up, I am able to register and log in via the SPA on http://host.docker.internal:5104. On the MVC page I get an error when clicking the login link.

The first time I tried running via Visual Studio I was able to log in, but suddenly I'm getting an error:

![image](https://user-images.githubusercontent.com/3495643/98806527-9e16aa80-2419-11eb-9ad0-6c2b46279f20.png)

![image](https://user-images.githubusercontent.com/3495643/98806564-ac64c680-2419-11eb-8f8d-67c4fb1e619f.png)

![image](https://user-images.githubusercontent.com/3495643/98806608-ba1a4c00-2419-11eb-9f79-192b30bf0dba.png)

When running via VS, I'm only able to access the MVC page through http://host.docker.internal:5100/, not the SPA through http://host.docker.internal:5104/ (not found)

Any idea what's going on?

**Comment by q-bertsuit** [comment]
I rebooted my computer and I can now run VS and access the SPA, which again lets me login.

**Comment by sughosneo** [comment]
Hi @q-bertsuit, thank you for reaching out.

I could see there are two different scenarios.

1) MVC - Correlation Failed : You may want to refer #1391 for the workaround.
2) SPA doesn't come up in VS - that could be related to #1360

**Comment by sughosneo** [comment]
Hi @q-bertsuit , just checking if you had a chance to look into this further. Thanks.

**Comment by sughosneo** [comment]
Hi @q-bertsuit, I am closing this issue as of now as it has been fixed with PR #1516.
Please feel free to reopen it if you have any further questions.

Thank you.
