### ISSUE TITLE
Migration failed to add a field to the CatalogItem entity in CatalogContext of Catalog.API

### ISSUE THREAD

**Issue by anjoy8** [dotnet-architecture/eShopOnContainers#1518]
**1.First, I added a String field: Tests**

`public string Tests { get; set; }`

**2.Then, to perform the migration:**

```
 add - migration AddTests - c CatalogContext - o Infrastructure/CatalogMigrations
```

**3.Finally, execute the project(or update-database) and report an error**

![image](https://user-images.githubusercontent.com/28941816/99141669-914bbe00-2688-11eb-9a70-7f6648063975.png)

------------

**After Debugging the source code, I found that the last migration record was not synchronized into the model snapshot.**

This submission record has been modified.
(https://github.com/dotnet-architecture/eShopOnContainers/commit/45ed8a60ad87c0da8f84f93aae143dce7e9c8bcc)
But the snapshot file has not changed.
（https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Catalog/Catalog.API/Infrastructure/CatalogMigrations/CatalogContextModelSnapshot.cs）

Causes new fields to be added to conflict.

**Comment by anjoy8** [comment]
The project only needs to modify the Model snapshot,
 
![pic](https://user-images.githubusercontent.com/28941816/99208967-f6c0bb80-27fc-11eb-94c7-d9535fc9116a.png)



and I can submit PR if necessary.

**Comment by sughosneo** [comment]
Hey @anjoy8, good to hear back from you again. :)

I quickly tried to run a migration by adding one `Test` string field and I was able to update the `CatalogContextModelSnapshot` class with new migration command. 

`dotnet ef migrations add AddTests -c CatalogContext -o Infrastructure/CatalogMigrations`

But yes, there is some issues with `PictureUri` and now instead of that we have been using `PictureFileName` for the Catalog item. You may want to look into issue #1350 and propose the necessary changes. 

Thank you

**Comment by anjoy8** [comment]
Hi, @sughosneo  nice to hear from you again.

Regarding my issue, only need to modify the **model snapshot**.

On the issue of the (https://github.com/dotnet-architecture/eShopOnContainers/issues/1350), I have found the problem, do I need to submit a PR?

![图片](https://user-images.githubusercontent.com/28941816/99245760-1c6eb480-283f-11eb-9cb6-38be3fbaaa46.png)

Just change pictureFileName to lowercase.

`pictureFileName` -> `picturefilename`

need I need to submit a PR?

**Comment by sughosneo** [comment]
> Hi, @sughosneo nice to hear from you again.
> 
> Regarding my issue, only need to modify the **model snapshot**.
> 
> On the issue of the (#1350), I have found the problem, do I need to submit a PR?
> 
> ![图片](https://user-images.githubusercontent.com/28941816/99245760-1c6eb480-283f-11eb-9cb6-38be3fbaaa46.png)
> 
> Just change pictureFileName to lowercase.
> 
> `pictureFileName` -> `picturefilename`
> 
> need I need to submit a PR?

Yes, you are correct. I thought of pointing that one as well.  Yes, you could submit two separate PRs with the respective changes.

Thank you.

**Comment by anjoy8** [comment]
Hi, I had intended to submit two PRs, but eventually merge together, https://github.com/dotnet-architecture/eShopOnContainers/pull/1520
I wonder if this meets your requirements.

In addition, there may still be some problems about Seed data, and I will further study it.
