### ISSUE TITLE
Service Bus persisted connection for ISubscriptionClient

### ISSUE THREAD

**Issue by Marusyk** [dotnet-architecture/eShopOnContainers#1519]
There is the code for TopicClient :

`var topicClient = _serviceBusPersisterConnection.CreateModel();`
https://github.com/dotnet-architecture/eShopOnContainers/blob/1b7200791931f33c94206822a69644ca820bb0dc/src/BuildingBlocks/EventBus/EventBusServiceBus/DefaultServiceBusPersisterConnection.cs#L27-L35

Shouldn't we do the same for ISubscriptionClient?

```
if(_subscriptionClient.IsClosedOrClosing)
{
      _subscriptionClient = new SubscriptionClient(serviceBusPersisterConnection.ServiceBusConnectionStringBuilder, subscriptionClientName);
}

return _subscriptionClient;
```

Q2. is it a typo in the class name:
https://github.com/dotnet-architecture/eShopOnContainers/blob/1b7200791931f33c94206822a69644ca820bb0dc/src/BuildingBlocks/EventBus/EventBusServiceBus/DefaultServiceBusPersisterConnection.cs#L7
Persister or Persisted?

**Comment by sughosneo** [comment]
Hi @Marusyk, thank you for your feedback. 

As `SubscriptionClient` also implements interface `IClientEntity` which actually holds the property `IsClosedOrClosing`. It can be used to check if the client connection is healthy or not.  That could be applicable to any client. 

Would you like to submit a PR ? Also, you may want to test out the changes with Azure Service Bus.

And in terms of Q2) -  to my opinion, we can leave the custom class name with `Persister` as it has been used as `Noun` and consistent in all the places.

**Comment by Marusyk** [comment]
Thank you for answer. I'll prepare a PR for this.

**Comment by Marusyk** [comment]
Hey @sughosneo

> And in terms of Q2) - to my opinion, we can leave the custom class name with Persister as it has been used as Noun and consistent in all the places.

For Rabbit implementation, it named `IRabbitMQPersistentConnection`.
It would be great to have the same name patter for ServiceBus and RabbitMq

**Comment by sughosneo** [comment]
I am closing this issue as of now as this has already been addressed. Please feel free to reopen it, if needed. 

Thank you.
