### ISSUE TITLE
Web apps should show up as Unhealthy if internal microservices are unhealthy

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#152]
Web apps should show up as Unhealthy if internal microservices are unhealthy.
The image below should show the Web apps as unhealthy, too, as they have dependency on the other microservices.
![image](https://cloud.githubusercontent.com/assets/1712635/24637703/090468be-1898-11e7-8c39-cc479f19d0e7.png)
In that case, the internal microservices were unhealthy because I killed the SQL Server container, therefore, as they depend on the CheckSQLServer, they were unhealthy.

**Comment by eiximenis** [comment]
This is done now.

**Comment by CESARDELATORRE** [comment]
Right.
