### ISSUE TITLE
RE:k8s Wiki - the namespace in step 5 of "Install Kubernetes Dashboard UI" is incorrect

### ISSUE THREAD

**Issue by jcaudill** [dotnet-architecture/eShopOnContainers#1524]
Using the command as documented in [step 5 of k8s wiki](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes#install-kubernetes-dashboard-ui) didn't work for me.  When I changed the namespace to `kubernetes-dashboard` I was able to find the correct token.

`kubectl -n kubernetes-dashboard describe secret $(kubectl -n kubernetes-dashboard get secret | grep admin-user | awk '{print $1}')`

**Comment by sughosneo** [comment]
Hi @jcaudill, thank you for your feedback. 

I just tested the `kubectl -n kube-system describe secret` command and it worked for me. 
I would agree that, you could also use `kubectl -n kubernetes-dashboard describe secret` command to fetch the token. 

Any error did you get while using the initial command ? And what's the kubernetes version ?

**Comment by jcaudill** [comment]
Thanks for the reply @sughosneo 

kubernetes version is v1.16.5

When I execute the command, I don't get an error but it lists multiple secrets and the admin-user is not one of them.  

![image](https://user-images.githubusercontent.com/843955/100000132-c8a42400-2d86-11eb-9260-171355feb4be.png)

Although, if I change the namespace to `kubernetes-dashboard` it does show the correct secret.  
![image](https://user-images.githubusercontent.com/843955/100000323-0e60ec80-2d87-11eb-8051-20ca5012e3a7.png)

Perhaps I'm doing something wrong but I thought I would share my experiance in case others are having the same issue. 

Thanks

**Comment by sughosneo** [comment]
Hi @jcaudill, thank you for the update and providing detail information.

Actually, you are right. For k8s dashboard login, I had used a different token. I have updated the [Install Kubernetes Dashboard UI](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes#install-kubernetes-dashboard-ui) wiki section. Now, it includes the correct command with both the option of `Powershell` and any other `Shell`.

You could test it again at your end and share your feedback.

**Comment by jcaudill** [comment]
@sughosneo thanks for the edit.

I have tested the documented steps in both Windows and macOS

Thanks again I hope you are not affected too badly by the cyclone!

**Comment by sughosneo** [comment]
> @sughosneo thanks for the edit.
> 
> I have tested the documented steps in both Windows and macOS
> 
> Thanks again I hope you are not affected too badly by the cyclone!

Great ! thank you @jcaudill
