### ISSUE TITLE
Registering IdentifiedCommandHandler with Autofac

### ISSUE THREAD

**Issue by Abrahamberg** [dotnet-architecture/eShopOnContainers#1529]
Hello , 
I am trying to understand how  IdentifiedCommandHandler in Ordering.API gets registered.
I see that in eShopOnContainers , command handlers are registered as 

```
   builder.RegisterAssemblyTypes(typeof(CreateOrderCommand).GetTypeInfo().Assembly)
       .AsClosedTypesOf(typeof(IRequestHandler<,>));
```
https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.API/Infrastructure/AutofacModules/MediatorModule.cs

and it make sense as all command handles  implant `` IRequestHandler<T, R>`` but in case of IdentifiedCommandHandler it implants ``IRequestHandler<IdentifiedCommand<T, R>, R>`` . 
```
 public class IdentifiedCommandHandler<T, R> : IRequestHandler<IdentifiedCommand<T, R>, R>
        where T : IRequest<R>
    { 
        ...
```

https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.API/Application/Commands/IdentifiedCommandHandler.cs

I made a project with same verions of Nugtes 
```
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="5.0.1" />
    <PackageReference Include="MediatR" Version="7.0.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="7.0.0" />
```
When I try to send an IdentifiedCommand, it doesn't seem that this specific handler is registered in the container and  I get this error : 

```

      var command = new UpdateUserNameCommand("Kate", "3");
      var guid = Guid.NewGuid(); //Demo Only
      var updateUserNameIdentified = new IdentifiedCommand<UpdateUserNameCommand, bool>(command, guid);
      var result = await _mediator.Send(updateUserNameIdentified);
----
ERROR : Handler was not found for request of type MediatR.IRequestHandler`2[DddWithMediatR.Application.Commands.IdentifiedCommand`2[DddWithMediatR.Application.Commands.UpdateUserNameCommand,System.Boolean],System.Boolean]. Register your handlers with the container. See the samples in GitHub for examples.'

```

Of course I can write something like this for Autofac and get it work

```
        builder.RegisterType(typeof(IdentifiedCommandHandler<UpdateUserNameCommand, bool>))
                .As<IRequestHandler<IdentifiedCommand<UpdateUserNameCommand, bool>, bool>>()
                .AsImplementedInterfaces();
```

But I don't find any similar registration in eShopOnContainers . It seems it just works without lines above. I really apricate if you can tell me how come does it work in eShopOnContainers .

**Comment by sughosneo** [comment]
Hi @Abrahamberg, thank you for reaching out. 

Did you get a chance to check out [Implement the microservice application layer using the Web API](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/microservice-application-layer-implementation-web-api) ?
It contains the details of `Command and Command Handler patterns` and how it gets registered in an application taking the reference of `eShopOnContainers`

**Comment by Abrahamberg** [comment]
Hello Sughosneo, 
Thank you for the answering, 
Yes I have already read that. It basically says what I said in my original question but doesn't add any anything extra  about the special case of IRequestHandler<IdentifiedCommand<T, R>, R>.

**Comment by Abrahamberg** [comment]
Ok, now I see how it works; you need to implement `IRequestHandler<IdentifiedCommand<T, R>, R>` for each of your idempotent commands, in case of my question  ` IdentifiedCommandHandler<UpdateUserNameCommand, bool>`  ! 
like this https://github.com/dotnet-architecture/eShopOnContainers/blob/9dec3b16e826d91e64f2c33a4c5ae043bf0e9a98/src/Services/Ordering/Ordering.API/Application/Commands/CancelOrderCommandHandler.cs#L42

Problem solved 👍   I need to sleep on it.

**Comment by fadak** [comment]
https://stackoverflow.com/a/52130814/406804
