### ISSUE TITLE
Change to hybrid flow in IdSvr for xamarin client. 

### ISSUE THREAD

**Issue by Guerillacoder** [dotnet-architecture/eShopOnContainers#154]
First of all, great repo!

I'm curious why the grant type for the xamarin client is implicit when the documentation says it should be hybrid for native clients?

Thanks.

**Comment by CESARDELATORRE** [comment]
@davidbritch, can you comment?

**Comment by davidbritch** [comment]
When IdentityServer was added to the solution it was still in alpha, with no docs. The IdentityServer4 doc site redirected to the IdentityServer 3 docs, which recommended to use the implicit flow. The IdentityServer4 docs now recommend to use the hybrid flow for native clients, which requires an update to the Identity.API project, along with re-testing of the Xamarin client.

I believe that @eiximenis has scoped this work to be carried out soon.

**Comment by eiximenis** [comment]
Hi,
It is done in commit af2d37bcc624bc84efd970d2febbe6188f65d5d7 (in dev branch right now)

Thx!

**Comment by davidbritch** [comment]
This is now in the MASTER branch so closing the issue.
