### ISSUE TITLE
DB connection strings

### ISSUE THREAD

**Issue by eliassal** [dotnet-architecture/eShopOnContainers#1542]
I  understand from the architecture and watching On Net Live-Intro to Microservices Patterns recording Nish Anil .
I decided to start playing with this app, so is there any prerequisites for DB connection strings before running docker compose and up?

**Comment by sughosneo** [comment]
Hi @eliassal, thank you for reaching out. 

If you just want to get started with `eShopOnContainers`, you don't need to change any configuration. You can follow [Getting Started](https://github.com/dotnet-architecture/eShopOnContainers#getting-started)
But if you want to change any specific configuration you can certainly do that. For that, you may want to refer other documentations on [Basic scenario](https://github.com/dotnet-architecture/eShopOnContainers#basic-scenario) or [Advanced scenario](https://github.com/dotnet-architecture/eShopOnContainers#advanced-scenario)

Hope this helps !

**Comment by eliassal** [comment]
Sorry sughosneo, all links land on the same page which is the page which I have seen before, nowhere it is indicated how to play with connection strings, can you please point where I can find the details?

**Comment by sughosneo** [comment]
No problem @eliassal. 

In the `eShopOnContainers` application, there are 4 types of databases are used in different microservices. Now, if you are using `docker-compose` technique to run the applications, then connection strings for different data stores and other configurations are set as part of environment variables. So you will be able to find all these configurations in the `docker-compose.override.yml` file. Here are the list of different connection strings for your reference.

[SQL Identity DB Connection String](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/docker-compose.override.yml#L47)
[SQL Catalog DB Connection String](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/docker-compose.override.yml#L87)
[SQL Ordering DB Connection String](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/docker-compose.override.yml#L110)
[SQL Marking DB Specific Connection String](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/docker-compose.override.yml#L154)
[Mongo connection string for Marketing API](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/docker-compose.override.yml#L155)
[Redis connection string for Basket API](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/docker-compose.override.yml#L67)

Please feel free to reach out if you have any further questions. 

Thanks.

**Comment by eliassal** [comment]
So many thanks, so IF I use docker-compose.override.yml  after updating it with my the my local SQL and mongo servers  and a local redis container locally then it  should work like a charm as of using the normal  compose file?

**Comment by sughosneo** [comment]
Hi @eliassal, Yes, that's right. If you are using the `docker-compose` technique to run the applications, then it runs separate docker containers for SQL,Redis,Mongo DB instances in your local environment. You can also your own SQL/Mongo/Redis instances, you just need to change respective connection strings.

**Comment by sughosneo** [comment]
Hi @eliassal  - considering the original question has been answered, I am closing this issue as of now. If you have any further questions, please feel free to reopen it.

Thank you.
