### ISSUE TITLE
Azure.Messaging.ServiceBus integration

### ISSUE THREAD

**Issue by biplovkc** [dotnet-architecture/eShopOnContainers#1544]
Is upgrading Microsoft.Azure.ServiceBus to Azure.Messagin.ServiceBus under consideration?

I tried to do it myself but I am missing many things that were available in Microsoft.Azure.ServiceBus and not available in Azure.Messaging.ServiceBus

For example: ITopicClient, SubscriptionClient (which means i cannot state that after processing message i cannot mention that it is completed).

Has anyone already given it a shot and succeded? or is the any tutorial on how to do so which i am not able to find?

**Comment by wario8a** [comment]
@biplovkc This guide can be useful [Migration Guide](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md)

**Comment by erjain** [comment]
I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
