### ISSUE TITLE
Service bus with RabbitMQ not rebinding queues on reconnect

### ISSUE THREAD

**Issue by jorgesoprani** [dotnet-architecture/eShopOnContainers#1545]
Whenever RabbitMQ stops and then reconnects, all queues get unbound to the exchange and the services stop communicating, making everything broken.
Setting exchanges to durable = true seem to fix the issue. Any reasons that might be a bad idea?

PS: the ConnectionShutdown event accumulates every time it succeeds. (class: DefaultRabbitMQPersistentConnection)

**Comment by sughosneo** [comment]
Hi @jorgesoprani, thank you for reaching out. 

RabbitMQ has many entities (For e.g: exchange, topic, queue & message etc..) which comes together to support communication between different services.There are two types of things 1)Durability and 2) Persistence which acts together to make any communication reliable. But these are two different things. While you make a message persistent with `properties.DeliveryMode = 2`, you also need to make the queue and exchange durable to actually save the messages in the Disk. Persistence means in case the broker suddenly stops for some reason, messages should be able to be get recovered on the next restart. So you need to set those flags specifically from the code.

For e.g `channel.ExchangeDeclare(exchange: BROKER_NAME, type: "direct" , durable: true)` and `channel.QueueDeclare(queue: _queueName,durable: true,exclusive: false,autoDelete: false,arguments: null)`

Also, please note that if you create your custom event bus based on RabbitMQ running in a container, as the eShopOnContainers application does, it should be used only for your development and test environments.Don't use it for your production environment, unless you are building it as a part of a production-ready service bus. A simple custom event bus might be missing many production-ready critical features that a commercial service bus has.

Hope this helps !

**Comment by sughosneo** [comment]
Hi @jorgesoprani, considering the original question has been answered, I am closing this issue as of now. If you have any further questions, please feel free to reopen it.

Thank you.
