### ISSUE TITLE
Deployment to AKS using Envoy, "Error starting gRPC Call"

### ISSUE THREAD

**Issue by rcastoro** [dotnet-architecture/eShopOnContainers#1554]
I have used your project as a reference and tailored it to only include the locations-api that acts as gRPC client with the webshoppingagg as the gRPC server. I am able to deploy using the helm charts and have defined the gRPC ports as 5000 as i have not enabled TLS. The default port of 81 experienced the same issue. The AppContext.SetSwitch method for unencrypted https doesn't seem to be working. I'm making my call via POSTMAN to the DNS address of the cluster via the webshoppingapigw and I'm receiving in the webshoppingagg logs saying i'm Authorized successfully so that's not the issue.

Locally I can run through the entire API call, but in AKS the logs show the call is getting hung up at the call to GrpcCallerService.CallService. Specifically, the client is created successfully but times out at

`var response = await client.CreateMethodCallNameFromDataAsync;`

Logging never makes it past here and the logs for the aggregator pod return this, about 2 minutes after the "gRPC client created" log is displayed and executed successfully:

`
[14:10:23 ERR] Error calling via grpc: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Connection timed out SocketException: Connection timed out", DebugException="System.Net.Http.HttpRequestException: Connection timed out
`
From within the webshoppingagg's bash shell, I can curl https://locations-api:80, but no response is returned from http://locations-api:5000 or http://locations-api:81

`kubectl describe cm cfg-locations-api`

returns:

`
Name:         cfg-locations-api
Namespace:    default
Labels:       app=locations-api
              app.kubernetes.io/managed-by=Helm
              chart=locations-api-0.1.0
              heritage=Helm
              release=serviceName-locations-api
Annotations:  meta.helm.sh/release-name: serviceName-locations-api
              meta.helm.sh/release-namespace: default

Data
====
all__EventBusConnection:
----
rabbitmq
all__InstrumentationKey:
----

all__UseAzureServiceBus:
----
false
internalurls__IdentityUrl:
----
http://identity-api
locations__EnableLoadTest:
----
false
urls__IdentityUrl:
----
serviceName.0000000000000000{hidden}.eastus.aksapp.io/identity
`

and 

`kubectl describe cm cfg-servicename-webshoppingagg`

returns

`
Name:         cfg-servicename-webshoppingagg
Namespace:    default
Labels:       app=webshoppingagg
              app.kubernetes.io/managed-by=Helm
              chart=webshoppingagg-0.1.0
              heritage=Helm
              release=servicename-webshoppingagg
Annotations:  meta.helm.sh/release-name: servicename-webshoppingagg
              meta.helm.sh/release-namespace: default

Data
====
internalurls__locations__hc:
----
http://locations-api/hc
all_EnableLoadTest:
----
false
all__InstrumentationKey:
----

internalurls__grpcLocations:
----
http://locations-api:5000
internalurls__identity:
----
http://identity-api
internalurls__identity__hc:
----
http://identity-api/hc
internalurls__locations:
----
http://locations-api
Events:  <none>
`

Is there any additional debugging I can add to the logging or a way to check the configuration? gRPC is the only hang-up in the entire project at this point.

*Note* the gRPC call calls a service that makes an external API call which i did not configure in the nginx config, but i would think it would make it to through atleast the gRPC CallService first, which it doesn't.

**Comment by sughosneo** [comment]
Hi @rcastoro, thank you for reaching out. 

Did you try to enable [K8s Dashboard](https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard) for the AKS cluster ? It can be helpful to see pod specific logs through the console. 
For e.g :

![image](https://user-images.githubusercontent.com/13281246/102864560-58a6bd80-445a-11eb-8b82-c4d1ea835c9d.png)

Also, if you are planning to trace the gRPC specific call then I would suggest you check Basket-API specific call during Order creation flow.  From the aggregator, there are the couple of gRPC calls get initiated during the actual Order Creation to verify and update the basket items.

**Comment by rcastoro** [comment]
I have not installed the dashboard but I will, I’m getting the same logs via the az cli and the grpc calls all work perfectly on dev. The call to grpc stalls out right at the call to the grpc method with the connection timeout. I will research the basket api but again, I do not have this service in my application and the grpc works great locally so I’d imagine it’s some sort of azure configuration issue or something I configured wrong in my helm chart. I’ll follow up with your recommendations, but any more suggestions?

**Comment by sughosneo** [comment]
Hi @rcastoro, thanks for the update. 

You may want to check the following aspects as well :
- You may want to check the `helm` chart specific configuration for that specific microservice. To my opinion, there might not be any issue with the AKS cluster.
- You can go to the actual service (for e.g `basket-api`) and check the log of that service to make sure if the service is up and running.
- You may want to call the other microservice with the name (for e.g : `basket-api`, `catalog-api` in terms of eShop app) rather `localhost`. Because when you are trying to make a call to `pod` of a service, from inside of a pod from another service, then you can't use `localhost`

Hope this helps !

**Comment by sughosneo** [comment]
Hi @rcastoro , just checking if you had a chance to look into this issue further. Thank you.

**Comment by sughosneo** [comment]
Hi @rcastoro , I am closing this issue as of now. If you have any further questions, please feel to reopen it. 

Thank you.
