### ISSUE TITLE
where to use Envoy proxy as api-gateway or Azure application gateway (APP-GW) services as api-gateway on microservices

### ISSUE THREAD

**Issue by tutul2010** [dotnet-architecture/eShopOnContainers#1563]
Hi All,
**It is not a bug reporting .just a discussion on above context.**
Microsoft recommended use Envoy-proxy as api-gateway( apply path-based routing to route traffic to a particular endpoint) as existing repo.(microservices patterns) .
Also , we can use Azure front-door(FD) or application gateway( APP-GW) kind service  for a Public facing End point for client access  with APIM (security , policy's) then linked to VM -scale set or AKS infrastructure as backend pool.

Is there any guidance to take decision on  where we can use Envoy-proxy as api-gateway or use Azure FD or APP-GW services with backed pool.

Many Thanks,

**Comment by sughosneo** [comment]
Hi @tutul2010, thank you for reaching out. 

Application Gateway pattern can be used to provide a single entry point for a group of Microservices from different clients. This pattern can be implemented  with help of a service proxy (For e.g Envoy) or API gateways (For e.g Azure API Management) or any other popular choices under the Cloud-Native landscape. But when to use what ? that depends on many aspects in your microservices implementations. For e.g :

For large microservice-based applications that are deployed into **Microsoft Azure**, it's suggested to evaluate and use Azure API Management. But if your architecture is limited to a simpler and custom-made containerized architecture without using `PaaS` products like `Azure API Management`, then `Envoy` could be good options.  Like this, you may want to consider all set of scenarios before picking up the right choice for your microservice architecture. Further references: [Azure API Management](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-api-gateway-pattern#azure-api-management)

Now, [Azure Front Door](https://docs.microsoft.com/en-us/azure/frontdoor/front-door-overview) or service like [Azure Application Gateway](https://docs.microsoft.com/en-us/azure/application-gateway/overview) are little different than the above segment. These are primary used to provide the load-balancing capability for your application within or across the region.  And if you are looking for a difference between *Azure Front Door* and *Azure Application Gateway*, then this [Q&A](https://docs.microsoft.com/en-us/azure/frontdoor/front-door-faq#what-is-the-difference-between-azure-front-door-and-azure-application-gateway) section would be the right place. For more information please refer [Decision tree for load balancing in Azure](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview#decision-tree-for-load-balancing-in-azure)

Please note, there could be a valid scenario where you may have to use many of these options together (For e.g Azure API Management + Application Gateway) while implementing microservices architecture for your application in Azure.

Hope this helps !

**Comment by tutul2010** [comment]
@sughosneo ,Thank for replay. 
I Got idea like--> 1) Using APIM for implanting policies, security, cashing, throttling for external  Restful API with Envoy-proxy for path-based routing to route traffic to a particular endpoint.
                           2) Using APP-GW  for WAF and apply path-based routing to route traffic to a particular endpoint. it can best use to private (secure) network api endpoints.. Yes, we can also use APP-GW then APIM and linked to backend pool.

Many Thanks,

**Comment by sughosneo** [comment]
> @sughosneo ,Thank for replay.
> I Got idea like--> 1) Using APIM for implanting policies, security, cashing, throttling for external Restful API with Envoy-proxy for path-based routing to route traffic to a particular endpoint.
> 2) Using APP-GW for WAF and apply path-based routing to route traffic to a particular endpoint. it can best use to private (secure) network api endpoints.. Yes, we can also use APP-GW then APIM and linked to backend pool.
> 
> Many Thanks,

Yes, that's correct 👍

**Comment by sughosneo** [comment]
Hi @tutul2010, considering the original question has been answered, I am closing this issue as of now. If you have any further questions, please feel free to reopen it.
