### ISSUE TITLE
[Question] _logger inside OrderApiClient.cs.

### ISSUE THREAD

**Issue by vishipayyallore** [dotnet-architecture/eShopOnContainers#1568]
Team - @sughosneo ,
Good morning. Are we using "_logger"? It shows in grey color. Please advise. Many thanks.

Regards,
Swamy

Path: https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/ApiGateways/Mobile.Bff.Shopping/aggregator/Services/OrderApiClient.cs

![image](https://user-images.githubusercontent.com/8255269/103441182-2bd08280-4c72-11eb-9dc1-2d53d1e5f569.png)

**Comment by sughosneo** [comment]
Hi @vishipayyallore , thank you for reaching out. 

Yes, at present `_logger` is not in use in `Microsoft.eShopOnContainers.Mobile.Shopping.HttpAggregator.Services.OrderApiClient` but it may be useful to log any specific step. 

Hope this helps !

**Comment by vishipayyallore** [comment]
Sumit - @sughosneo 
Noted.

Regards,
Swamy
