### ISSUE TITLE
[Question] _httpClient inside OrderingService.cs

### ISSUE THREAD

**Issue by vishipayyallore** [dotnet-architecture/eShopOnContainers#1569]
Team - @sughosneo ,
Good morning. I am seeing the "_httpClient" is being injected inside the constructor. After that, I am not seeing its usage inside OrderingService.cs service. Is "_httpClient" being used? Please advise. Many thanks.

Regards,
Swamy

Path: https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/ApiGateways/Mobile.Bff.Shopping/aggregator/Services/OrderingService.cs

![image](https://user-images.githubusercontent.com/8255269/103441268-be712180-4c72-11eb-9c45-6f9565c6e1f3.png)

**Comment by sughosneo** [comment]
Hi @vishipayyallore , thank you for reaching out. 

Yes, `_httpClient` is not in use in `Microsoft.eShopOnContainers.Mobile.Shopping.HttpAggregator.Services.OrderingService`
This class is using a `gRPC` client for making the call to other respective services.

**Comment by vishipayyallore** [comment]
Sumit - @sughosneo 
Thanks. Shall I remove this? There is another field and I have raised one more query. I will raise another PR with these two changes. Please advise. Many thanks.

Regards,
Swamy

**Comment by sughosneo** [comment]
> Sumit - @sughosneo
> Thanks. Shall I remove this? There is another field and I have raised one more query. I will raise another PR with these two changes. Please advise. Many thanks.
> 
> Regards,
> Swamy

Yes, you can. But the only reason I will leave that `_httpClient` as is, just to show that an aggregator can also make subsequent rest API call to other API(s). It's not only `gRPC`.
