### ISSUE TITLE
.net 5 support 

### ISSUE THREAD

**Issue by dicksonkimeu** [dotnet-architecture/eShopOnContainers#1573]
When will this sample support .net 5 ?

**Comment by sughosneo** [comment]
Hi @dicksonkimeu , thank you for reaching out. We are already in process of updating this reference application to `.NET 5.0`. You can refer the progress in the [migration/net-5](https://github.com/dotnet-architecture/eShopOnContainers/tree/migration/net-5) branch. It should be available soon.

Hope this helps !

**Comment by Rabosa616** [comment]
I did see that on that branch there isn't anymore the Mobile application, is that because you also are migrating that to Xamarin Forms 5?

**Comment by sughosneo** [comment]
> I did see that on that branch there isn't anymore the Mobile application, is that because you also are migrating that to Xamarin Forms 5?

Hi @Rabosa616, thank you for reaching out. 

Yes, the Mobile client applications related module is moved to a different repository [eshop-mobile-client](https://github.com/dotnet-architecture/eshop-mobile-client)
This step is to keep the overall `eShopOnContainers` application simple and easily manageable. As of now, we don't have any plan to update it to Xamarin.Forms 5.0. But if any of the community members update the mobile client solution and submit a PR. We will be happy to review it :)

**Comment by sughosneo** [comment]
The `eShopOnContainers` application is now updated to `.NET 5`.  

For more details, please refer [eShopOnContainers - BRANCH GUIDE](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/branch-guide.md) 

I am closing this issue as of now. Please feel free share your feedback or open a separate issue if you face any challenges. Thank you.
