### ISSUE TITLE
Service 'webspa' Failed

### ISSUE THREAD

**Issue by fernandofot** [dotnet-architecture/eShopOnContainers#1574]
Hi,

I have tried to run the container and I faced an issue.

At first, I ran the followed command: $ docker-compose build

nosqldata uses an image, skipping
basketdata uses an image, skipping
mobilemarketingapigw uses an image, skipping
webshoppingapigw uses an image, skipping
Building catalog-api
Step 1/57 : FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
**ERROR: Service 'catalog-api' failed to build: Error parsing reference: "mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base" is not a valid repository/tag: invalid reference format**

And then, I tried this one: docker-compose up

Digest: sha256:9ef9c4fd6189fdb903929dc5aa0492a51d6783777de65e567382ac7d9a28106b
Status: Downloaded newer image for docker.io/envoyproxy/envoy:v1.11.1
Building webspa
Step 1/58 : ARG NODE_IMAGE=node:8.16
**ERROR: Service 'webspa' failed to build: Please provide a source image with `from` prior to commit**

OS: CentOS Linux release 7.9.2009 (Core)
Docker version 1.13.1, build 0be3e21/1.13.1

Thanks in advance,
Fernando

**Comment by fernandofot** [comment]
I removed the folder and cloned again.

Here is the output:

[root@docker src]# pwd
/opt/eShopOnContainers/src


[root@docker src]# docker-compose build
WARNING: The INSTRUMENTATION_KEY variable is not set. Defaulting to a blank string.
WARNING: The ORCHESTRATOR_TYPE variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_SERVICE_BUS_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_SERVICE_BUS_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_CATALOG_KEY variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZUREFUNC_CAMPAIGN_DETAILS_URI variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_MARKETING_NAME variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_MARKETING_KEY variable is not set. Defaulting to a blank string.
webshoppingapigw uses an image, skipping
mobileshoppingapigw uses an image, skipping
mobilemarketingapigw uses an image, skipping
nosqldata uses an image, skipping
basketdata uses an image, skipping
rabbitmq uses an image, skipping
sqldata uses an image, skipping
seq uses an image, skipping
webmarketingapigw uses an image, skipping
Building webstatus
Step 1/50 : FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
ERROR: Service 'webstatus' failed to build: Error parsing reference: "mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base" is not a valid repository/tag: invalid reference format
[root@docker src]# vim docker-compose.yml
[root@docker src]# docker-compose up
WARNING: The INSTRUMENTATION_KEY variable is not set. Defaulting to a blank string.
WARNING: The ORCHESTRATOR_TYPE variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_SERVICE_BUS_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_SERVICE_BUS_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_CATALOG_KEY variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZUREFUNC_CAMPAIGN_DETAILS_URI variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_MARKETING_NAME variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_MARKETING_KEY variable is not set. Defaulting to a blank string.
Building webstatus
Step 1/50 : FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
ERROR: Service 'webstatus' failed to build: Error parsing reference: "mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base" is not a valid repository/tag: invalid reference format

**Comment by sughosneo** [comment]
Hi @fernandofot, thank you for reaching out. 
I haven't tested the solution with CentOS. Could you please install Docker Version / Engine 19+ and docker-compose 1.25+ then try to build the solution ? You can refer [Install Docker Engine](https://docs.docker.com/engine/install/) and [Install Compose](https://docs.docker.com/compose/install/#install-compose) for more details.

**Comment by sughosneo** [comment]
Hi @fernandofot, just checking if you had a chance to look into this issue further. Thank you.

**Comment by sughosneo** [comment]
Hi @fernandofot , I am closing this issue as of now. If you have any further question, please feel free to reopen it. Thank you.
