### ISSUE TITLE
Can't restore solution - NuGet feed does not exist "https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json"

### ISSUE THREAD

**Issue by Alexabix** [dotnet-architecture/eShopOnContainers#1575]
`Step 42/50 : RUN dotnet restore "eShopOnContainers-ServicesAndWebApps.sln"
 ---> Running in c84b8dc70ef6
  Determining projects to restore...
/usr/share/dotnet/sdk/3.1.404/NuGet.targets(128,5): error : Unable to load the service index for source https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json. [/src/eShopOnContainers-ServicesAndWebApps.sln]
/usr/share/dotnet/sdk/3.1.404/NuGet.targets(128,5): error :   Response status code does not indicate success: 404 (Feed does not exist.). [/src/eShopOnContainers-ServicesAndWebApps.sln]`

It seems like the nuget feed used for restoring some of the project packages doesn't exist, visiting the URL in a browser also returns "Feed does not exist."

Has this feed moved?

**Comment by baskan** [comment]
same issue here.

**Comment by rossdonald** [comment]
The solution is setup with custom Nuget feeds which seem to be out of date. I deleted /src/Nuget.config and reloaded the solution. 

It fixes that error but there are still errors with references in the projects to preview versions of packages. Those will need to be updated one by one.

**Comment by sughosneo** [comment]
Hi, thank you for reporting this issue. Initial analysis of @rossdonald seems to be right. 
We are investigating this at our end. We will update this thread, once the issue is fixed.

**Comment by mina5500** [comment]
yes .. same error

**Comment by stindeepakgadge** [comment]
Yes. I am also facing the same error

**Comment by vpotourides** [comment]
Same error

**Comment by stindeepakgadge** [comment]
> `Step 42/50 : RUN dotnet restore "eShopOnContainers-ServicesAndWebApps.sln" ---> Running in c84b8dc70ef6 Determining projects to restore... /usr/share/dotnet/sdk/3.1.404/NuGet.targets(128,5): error : Unable to load the service index for source https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json. [/src/eShopOnContainers-ServicesAndWebApps.sln] /usr/share/dotnet/sdk/3.1.404/NuGet.targets(128,5): error : Response status code does not indicate success: 404 (Feed does not exist.). [/src/eShopOnContainers-ServicesAndWebApps.sln]`
> 
> It seems like the nuget feed used for restoring some of the project packages doesn't exist, visiting the URL in a browser also returns "Feed does not exist."
> 
> Has this feed moved?

Delete the NuGet.config file and reload the solution. after reload it show package reference error.  add those  required package references manually to respective projects. it fixes the issue.

**Comment by sughosneo** [comment]
Hello Everyone, `dotnet.myget.org` dependencies has been removed from `NuGet.config`. 
Could you please take the latest from the `dev` branch and test it at your end to make sure if everything is working fine ?

Thank you.

**Comment by Alexabix** [comment]
> Hello Everyone, `dotnet.myget.org` dependencies has been removed from `NuGet.config`.
> Could you please take the latest from the `dev` branch and test it at your end to make sure if everything is working fine ?
> 
> Thank you.

Can confirm it works for me now - thanks for the quick fix! 👍
