### ISSUE TITLE
Wiki update - Add the two kubectl apply commands to #Explore-Internal-Services

### ISSUE THREAD

**Issue by FrankMormino** [dotnet-architecture/eShopOnContainers#1577]
The powershell script .\deploy-nodeports.ps1 does not exist anymore in dev branch.

Need to add the two commands that were removed shown below

![image](https://user-images.githubusercontent.com/45765756/104426195-9ecdd900-554f-11eb-86bb-5dd639edc5a2.png)

https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes#Explore-Internal-Services

kubectl apply -f .\nodeports\rabbitmq-admin.yaml	
kubectl apply -f .\nodeports\sql-services.yaml

Looks like this was removed here - https://github.com/dotnet-architecture/eShopOnContainers/blob/6af743c99cc2876f1411c864c62de3600ac8e3d6/deploy/k8s/deploy-nodeports.ps1

**Comment by sughosneo** [comment]
Hi @FrankMormino , thank you for pointing that out. Good catch 👍 
The wiki page has been updated now. You could review the commands in there.

Thanks again !

**Comment by FrankMormino** [comment]
@sughosneo Thanks for quick response - one more edit I mistyped originally.

Change sql-services.yaml to sql-service.yaml

```
PS C:\Dev\source\eShopOnContainers\deploy\k8s> kubectl apply -f .\nodeports\sql-services.yaml
error: the path ".\\nodeports\\sql-services.yaml" does not exist

PS C:\Dev\source\eShopOnContainers\deploy\k8s> kubectl apply -f .\nodeports\sql-service.yaml
service/sql-service created
```

**Comment by sughosneo** [comment]
> @sughosneo Thanks for quick response - one more edit I mistyped originally.
> 
> Change sql-services.yaml to sql-service.yaml
> 
> ```
> PS C:\Dev\source\eShopOnContainers\deploy\k8s> kubectl apply -f .\nodeports\sql-services.yaml
> error: the path ".\\nodeports\\sql-services.yaml" does not exist
> 
> PS C:\Dev\source\eShopOnContainers\deploy\k8s> kubectl apply -f .\nodeports\sql-service.yaml
> service/sql-service created
> ```

Yes, Done. Please check now.

**Comment by FrankMormino** [comment]
Verified - LGTM!
