### ISSUE TITLE
WebMVC - Cosmetic Usability and Display Issues.

### ISSUE THREAD

**Issue by hetal-kapadia** [dotnet-architecture/eShopOnContainers#1581]
I am getting accustomed to micro-services and containers and while exploring this solution, noticed a few usability/display issues (noticeable in Firefox) so thought of documenting here. 

I am also attempting to get my feet wet with open source contributions so will look to fix these as well.
 
Here are the issue details
In Cart View and Order Details view:
1) Total is displaying without 2 decimal places.
2) User hover menu is overlapping with page contents, and menu closes before user could move to cursor to Log Out option.

![Cart - Total And User Menu Issue](https://user-images.githubusercontent.com/31979831/104822116-3011a980-57f5-11eb-9170-1b9de35d8958.PNG)
---
![Order Details - Total Issue](https://user-images.githubusercontent.com/31979831/104822015-b4176180-57f4-11eb-9d10-8447d1946860.PNG)
---
![Order Details - User Menu Issue](https://user-images.githubusercontent.com/31979831/104822025-b7aae880-57f4-11eb-8f55-5b1795662003.PNG)

Please excuse and guide me if i am not following the contribution process correctly.

Thank you!

**Comment by sughosneo** [comment]
Hi @hetal-kapadia , thank for your pointing it out. Will review the proposed changes.
I have linked the issue against the PR #1582

**Comment by hetal-kapadia** [comment]
Thank you @sughosneo! I am also looking for some guidance to see if i am following the process right.

Since i am new to this process, i see that there were 2 issues created for the same item. #1581 was created explicitly by me to document the issue. #1582 got created when i raised a PR for this fix.

Since i was fixing this issue, should i have waited and documented this while raising the PR to avoid duplication?

**Comment by sughosneo** [comment]
Hi @hetal-kapadia, you have followed the right process :+1:
It's always good to create an issue first and then raise a PR against that issue. In both scenarios, it creates a separate issue. 

Hope this helps !
