### ISSUE TITLE
Update the SPA app to use angular-cli

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#160]
Need to update the SPA app to use angular-cli.
Related to https://github.com/dotnet/eShopOnContainers/issues/148, as well.

**Comment by andrelmp** [comment]
Any branch or PR available? maybe i can help.

**Comment by CESARDELATORRE** [comment]
@andrelmp Thanks a lot! - That would be highly appreciated.
You could fork the DEV branch and do a PR on it when you have it ready.
Also, please attach a small document (MD) explaining the steps you need to follow when using Angluar-cli
Thanks,

**Comment by CESARDELATORRE** [comment]
PR accepted and working
