### ISSUE TITLE
system.digonist tool 4.3.0 is not compatatble with netcore 1.1 iissue while buidling  in vs2017community

### ISSUE THREAD

**Issue by babula38** [dotnet-architecture/eShopOnContainers#165]
clone the project from github try to load the solution got this error window.

"system.digonist tool 4.3.0 is not compatatble with netcore 1.1 iissue while buidling  in vs2017community"

**Comment by CESARDELATORRE** [comment]
We're not able to reproduce this issue. Is it still happening to you? - could you try with a different machine/environment?

**Comment by SychevIgor** [comment]
@babula38 do you still have this issue?

**Comment by SychevIgor** [comment]
@CESARDELATORRE I guess we can close this issue, since we have no answer from @babula38

**Comment by CESARDELATORRE** [comment]
Closing this.
