### ISSUE TITLE
Move on and use the next version of HealthChecks Library

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#179]
The HealthCheck library at https://github.com/aspnet/HealthChecks/tree/dev/src has been evolving. 
There are new capabilities, libraries and namespaces. 
Need to update eShopOncContainers to use the new version of .

**Comment by eiximenis** [comment]
Done in dev branch.

**Comment by CESARDELATORRE** [comment]
Done. Closing.
