### ISSUE TITLE
Need to migrate to MediatR 3 and evolve from Decorators to pipeline behaviors

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#187]
In MediatR 3, it was added support for pipeline behaviors.
Decorators are tough to implement in different containers so it is better to use the new pipeline behaviours. 
See https://github.com/jbogard/MediatR/wiki/Behaviors

**Comment by jbogard** [comment]
Just a heads up - I'm working with the Autofac folks to figure out the right way to register behaviors. I'm more versed in StructureMap and my Autofac example isn't exactly correct.

**Comment by CESARDELATORRE** [comment]
Thanks Jimmy. We'll wait until you ping again and confirm the best approach for using Autofac with MediatR 3 behaviors.
Thanks for the  for the heads-up.

**Comment by eiximenis** [comment]
@CESARDELATORRE 

Done in dev branch. Commit 0c73b094069ca30de1b2c9303b492525106bd60c

**Comment by CESARDELATORRE** [comment]
Closing this issue
