### ISSUE TITLE
Xamarin UWP & Android won't build - "...Microsoft.Bcl.Build  installed and packages.config..."

### ISSUE THREAD

**Issue by kmusick** [dotnet-architecture/eShopOnContainers#194]
Master branch, Windows 10 Creators Update. Tried in both VS2017 and VS2015 with no luck. 

Attempting to rebuild UWP project in the MobileApps solution gives the following build error:

>   Error: Could not locate C:\Development\eShopOnContainers\src\Mobile\eShopOnContainers\eShopOnContainers.Core\packages.config.  Ensure that this project has Microsoft.Bcl.Build installed and packages.config is located next to the project file. (1, 1)

![image](https://cloud.githubusercontent.com/assets/6422056/25870302/41c2b80c-34c9-11e7-8f8d-2e7d994b2e1e.png)

Tried the fix from [stackoverflow](http://stackoverflow.com/questions/17180268/warning-all-projects-referencing-myproject-csproj-must-install-nuget-package-m/17242424#17242424) that said to add `<Properties>SkipValidatePackageReferences=true</Properties>` with no luck as well.

Any guidance?

**Comment by davidbritch** [comment]
While VS2017 reports this error for the Android and UWP projects, it's a false error. In both cases the app builds and deploys.

Adding the Microsoft.Bcl.Build NuGet package to the UWP project doesn't help, as this package isn't required at all for UWP or any framework that supports project.json.

For peace of mind the build error can be removed by adding:

<SkipValidatePackageReferences>true</SkipValidatePackageReferences> to the first <PropertyGroup> in the appropriate .csproj.

I'll update the required .csproj files in MASTER.

**Comment by davidbritch** [comment]
Updated the .csproj for the UWP app.
