### ISSUE TITLE
Unable to run the tests after cloning the code in  vs2017

### ISSUE THREAD

**Issue by girishgouda** [dotnet-architecture/eShopOnContainers#195]
We are unable to run the application and also see lot of functional test and integration tests are failing because of the below  reason mentioned . It looks like one of the firewall port is not opened. We are using docker for windows

Kindly help on this as we are new to containers

Message: System.AggregateException : One or more errors occurred. (A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - No connection could be made because the target machine actively refused it.))
---- System.Data.SqlClient.SqlException : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - No connection could be made because the target machine actively refused it.)
-------- System.ComponentModel.Win32Exception : No connection could be made because the target machine actively refused it

**Comment by CESARDELATORRE** [comment]
Looks like your SQL Server Linux Container is not available. Did you follow, step by step, the setup instructions available at eShopOnContainers Wiki?
You need to assign more memory to Docker so SQL Server is able to start. 
Please, confirm.

**Comment by CESARDELATORRE** [comment]
Closing for now as we didn't received any further confirmation
