### ISSUE TITLE
how can i run it on windows 7 and docker

### ISSUE THREAD

**Issue by JamesYing** [dotnet-architecture/eShopOnContainers#196]
how can i run it on windows 7 and docker

**Comment by CESARDELATORRE** [comment]
You could use the the older and deprecated "Docker Toolbox" on Windows 7: https://docs.docker.com/toolbox/toolbox_install_windows/

However, we're not supporting that configuration in eShopOnContainers.
As explained at the Wiki here: https://github.com/dotnet-architecture/eShopOnContainers/wiki/00.-Dev-machine-requirements
Even when Visual Studio 2017 supports Windows 7 or later, however, Docker recommends "Docker for Windows" for the development machines and the requirements for “Docker for Windows” are more restrictive and requires Windows 10: https://docs.docker.com/docker-for-windows/install/#download-docker-for-windows 

Why is Windows 10 required? Docker for Windows uses Windows Hyper-V. While older Windows versions have Hyper-V, their Hyper-V implementations lack features critical for Docker for Windows to work.
Docker for Windows requires 64bit Windows 10 Pro, Enterprise and Education (1511 November update, Build 10586 or later) and Microsoft Hyper-V.

**Comment by CESARDELATORRE** [comment]
Closing this issue.
