### ISSUE TITLE
Avoid using environment variable ${DOCKER_BUILD_SOURCE}

### ISSUE THREAD

**Issue by deqing** [dotnet-architecture/eShopOnContainers#197]
1. There is no document about this variable
2. Visual Studio set this environment variable implicitly, meaning there is no way to do similar things by command line, for example docker-compose with multiple dockers becomes impossible.

**Comment by CESARDELATORRE** [comment]
@deqing As far as I know, we are not using the ${DOCKER_BUILD_SOURCE} variable in our custom code.
The only places where it is being used are at the VS2017 .yml files which are generated by VS (docker-compose.vs.debug.yml and docker-compose.vs.release.yml). Those are just used by VS when locally debugging, F5, etc. But not used in our application code for regular deployment.
I.e. We are able to deploy with docker-compose up and using multiple docker-compose files, as documented here: https://github.com/dotnet-architecture/eShopOnContainers/wiki/03.-Setting-the-eShopOnContainers-solution-up-in-a-Windows-CLI-environment-(dotnet-CLI,-Docker-CLI-and-VS-Code) 

So, do you mean any particular case were we shouldn't use the ${DOCKER_BUILD_SOURCE} variable that I'm not aware?

**Comment by deqing** [comment]
@CESARDELATORRE Thanks for the explanation.

If ${DOCKER_BUILD_SOURCE} variable is only used when debugging with Visual Studio, that's fine.

**Comment by CESARDELATORRE** [comment]
Yep, it is only used by VS2017, not by our code. Closing this issue.
Thanks,
