### ISSUE TITLE
Pending to create "Service Tests" to test the microservices running as a multi-container app in Docker 

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#20]
Still pending to create "Service Tests" to test the microservices running as a multi-container app in Docker.
We need to create these tests, it is important to show how to test Docker Containers.

**Comment by dsrodenas** [comment]
We have created the FunctionalTests project that covers this "Service tests". We have added a couple of tests to show how to test the Docker containers. When more cases are implemented the number of tests can be increased.

**Comment by CESARDELATORRE** [comment]
Pending to create a separate Test Project with the "ServiceTests" as they require a different setup starting the containers first with "docker-compsoe up", etc. - We'll close this issue when that separate Test project is created.
