### ISSUE TITLE
Change base Route at Basket.API to use the controller's Route instead of "/" so SwaggerUI will work

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#202]
The current version of the Basket.API is using this Route attribute like this:
    [Route("/")]
    [Authorize]
    public class BasketController : Controller

I believe that is preventing Swagger UI from working properly at the Basket Web API.
We might need to change that Route and make it like the rest of the Web APIs, like:
[Route("api/v1/[controller]")]

Make sure to perform any needed changes in the client apps, the MVC app, SPA and Xamarin app as this change will impact the client side. 
i.e. From the client apps instead of using an URI like: 
"http://basket.api/c26d6cf8-e49a-4bda-be8b-7e08b554df81" 
It should be like:
"http://basket.api/api/v1/catalog/c26d6cf8-e49a-4bda-be8b-7e08b554df81"

Then, check that Swagger UI works at:
http://localhost:5103/swagger

**Comment by eiximenis** [comment]
This is done in dev
