### ISSUE TITLE
Cannot start project with docker

### ISSUE THREAD

**Issue by dovar21** [dotnet-architecture/eShopOnContainers#203]
**Hi,
Docker installed . Another project works with docker. But this project/solution(eShopOnContainers) does not work with the docker. I can't start prpoject or solution with docker. See attachnments...**

**Windows 10
About docker**
![img1](https://cloud.githubusercontent.com/assets/5477411/26481498/d8c742c0-41fa-11e7-8d14-43cf208dc977.png)

**Visual Studio Version**

![img2](https://cloud.githubusercontent.com/assets/5477411/26481499/d9bfcb02-41fa-11e7-9d0f-664aa2974681.png)

**Docker support**
![img3](https://cloud.githubusercontent.com/assets/5477411/26481614/d0251b96-41fb-11e7-8cfe-1d16a86e92d1.png)

**Comment by CESARDELATORRE** [comment]
Please, follow the setup instructions at the Wiki.
You need to set the docker-compose project in Visual Studio as the default start up project.

**Comment by CESARDELATORRE** [comment]
Please, follow the setup instructions at the Wiki.
This is the procedure you need to follow the first time: https://github.com/dotnet-architecture/eShopOnContainers/wiki/02.-Setting-eShopOnContainers-in-a-Visual-Studio-2017-environment

**Comment by dovar21** [comment]
Thanks for the answer! 
It works.

**Comment by CESARDELATORRE** [comment]
Closing now.
