### ISSUE TITLE
The project is great. Is there a flutter version? Flutter is an open source mobile application software development kit developed by Google for developing applications for Android, iOS, Web, Windows, macOS, Linux Desktop, Google Fuchsia. Flutter is making efforts to games, Metaverse, and web3. ![flutter](https://user-images.githubusercontent.com/122947293/213731917-caf3dfd0-db1d-4b1c-ba21-85d8f0985396.png) https://github.com/flutter/flutter 项目非常棒 有flutter版本吗？Flutter是一个由谷歌开发的开源移动应用软件开发工具包，用于为Android、iOS、Web、We'bWindows、macOS、Linux Desktop、Google Fuchsia开发应用。 Flutter正在向游戏、元宇宙、web3发力。

### ISSUE THREAD

**Issue by swordbe** [dotnet-architecture/eShopOnContainers#2037]
The project is great. Is there a flutter version? Flutter is an open source mobile application software development kit developed by Google for developing applications for Android, iOS, Web, Windows, macOS, Linux Desktop, Google Fuchsia. Flutter is making efforts to games, Metaverse, and web3. ![flutter](https://user-images.githubusercontent.com/122947293/213731917-caf3dfd0-db1d-4b1c-ba21-85d8f0985396.png) https://github.com/flutter/flutter 项目非常棒 有flutter版本吗？Flutter是一个由谷歌开发的开源移动应用软件开发工具包，用于为Android、iOS、Web、We'bWindows、macOS、Linux Desktop、Google Fuchsia开发应用。 Flutter正在向游戏、元宇宙、web3发力。

**Comment by erjain** [comment]
Hi @swordbe, thanks for sharing your feedback and query. We have [eshop-mobile-client](https://github.com/dotnet-architecture/eshop-mobile-client) app, which is a reference .NET MAUI multi-platform client app for iOS, macOS, Android, and Windows instead of flutter. I hope it will help you.

**Comment by erjain** [comment]
I am closing this, since this is not an issue, however, feel free to continue the conversation if you are looking for more help.
