### ISSUE TITLE
Increase the resilience of the RequestProvider class in the mobile app

### ISSUE THREAD

**Issue by davidbritch** [dotnet-architecture/eShopOnContainers#206]
When running the mobile app against the Docker containers, and then cleaning the containers, the database is removed and hence the user's token is deleted. The mobile app stores the access token permanently, and so when the app attempts to access the containers, the app hangs as the token the user is using no longer exists.

**Comment by mvelosop** [comment]
Closed as it was included in the [Roadmap (vNext)](https://github.com/dotnet-architecture/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases#vnext).

**Comment by davidbritch** [comment]
Please don't close my issues. I work across a lot of repos and without the issues remaining open this functionality will never be implemented as it vanishes from my issue tracker.

**Comment by davidbritch** [comment]
Closing. Will be discussed as part of FY20 planning.
