### ISSUE TITLE
some  problem in ResilientHttpClient and ResilientHttpClientFactory

### ISSUE THREAD

**Issue by futugyou** [dotnet-architecture/eShopOnContainers#208]
WaitAndRetry and CircuitBreaker in ResilientHttpClientFactory  doesn't work.
It may be because  the HttpInvoker method  in   ResilientHttpClient have a parameter Func<Task<T>> action.
It's parameter  should be called by 'ExecuteAsync'  not  'Execute' and Policy.Wrap should be Policy.WrapAsync.

And, WaitAndRetry and CircuitBreaker in ResilientHttpClientFactory should be WaitAndRetryAsync and CircuitBreakerAsync

**Comment by CESARDELATORRE** [comment]
There was an issue in this which was fixed in the DEV brach. Have you tried the Master or the DEV branch?
