### ISSUE TITLE
[Suggestion for eBooks] Add epub downloads

### ISSUE THREAD

**Issue by Daniel-Svensson** [dotnet-architecture/eShopOnContainers#209]
Please add epub versions of the books in addition to the pdf versions

**Comment by CESARDELATORRE** [comment]
We just published .EPUB and .MOBI (Kindle) for the Microservices eBook.  
See at:
Tweet: https://twitter.com/cesardelatorre/status/916011431908089856
http://dot.net/Architecture
https://aka.ms/microservicesebookEPUB
https://aka.ms/microservicesebookMOBI

Thanks for the feedback! :)
