### ISSUE TITLE
KeyNotFoundException when order doesn't exist

### ISSUE THREAD

**Issue by FDUdannychen** [dotnet-architecture/eShopOnContainers#210]
In [Ordering.API/OrderController.GetOrder(int orderId)](https://github.com/dotnet-architecture/eShopOnContainers/blob/master/src/Services/Ordering/Ordering.API/Controllers/OrdersController.cs#L61) I saw if no order can be found, [OrderQuries](https://github.com/dotnet-architecture/eShopOnContainers/blob/master/src/Services/Ordering/Ordering.API/Application/Queries/OrderQueries.cs#L41) throws an `KeyNotFoundException`, and the caller controller catches it, returns HTTP 404. Should the query return `null` when not found?

**Comment by eiximenis** [comment]
Hi @FDUdannychen 

IMHO from a REST perspective a better option is to return a 404: you are asking for a resource (specific order) and this resource do not exists, so a 404 :)

Returning `null` is not good: what we should return to the caller? A serialized null (easy in JSON, not-so-easy in XML)? 

We could use a No-Content (204), but this is definitely worse: caller can assume that any request returning a 2xx was successful, and this is not the case.

By returning a 404 we are sticking to the HTTP semantics: you asked for a thing, that do not exists. Maybe existed before, maybe will exist later, but don't exists right now

Thanks!

**Comment by FDUdannychen** [comment]
@eiximenis I'm not blaming the web API returns 404. I'm wondering why OrderQueries.GetOrder(id) throws an `KeyNotFoundException`, instead of returning `null`.

**Comment by eiximenis** [comment]
Hi again @FDUdannychen 

Sorry, I missunderstood your question (my fault to no read the code you linked). I, honestly, don't have a good answer for this ;)

From a "purist" point of view, throwing an exception is not a bad idea: asking for a key that don't exists is (or should be) an exceptional thing, and is better handled using exceptions. That allows for better separation of concerns in classes that call the query object. 

But, in this particular case i don't like how the try/catch clause looks (resembles a lot an if/else) and also I don't like to pay the cost of throwing an exception. And as this is an API that gets the id from the "user" maybe asking for a non-existent order is not as exceptional as it should be.  So I agree with you that using `null` seems a better option in those cases than throwing an exception!

Any other thoughts on that??

**Comment by FDUdannychen** [comment]
@eiximenis IMO if use exceptions, a custom `OrderNotFoundException` is better than `KeyNotFoundException`, `id` is the key of `order` (in the database), that's true, but it shouldn't be a rule applied in the API. Let's say the order has another unique property named "LogisticsNumber" and we have `OrderQueries.GetOrder(string logisticsNumber)`, will this method throws `KeyNotFoundException` when order not found?

Anyway I still prefer returning `null` instead of throwing exceptions...
