### ISSUE TITLE
Unable to create a new order

### ISSUE THREAD

**Issue by davidbritch** [dotnet-architecture/eShopOnContainers#212]
When running the Xamarin client (UWP) against local Docker containers and creating a new order (checking out), a POST request is made to the following endpoint:

&lt;base endpoint&gt;:5102/api/v1/orders/new

The response from the POST request contains status code 500, with the reason being "Internal Server Error", and the internal message being "Object reference not set to an instance of an object". This worked last time I tried it.

**Comment by CESARDELATORRE** [comment]
We have changed the Order process so that's why the Xamarin app is failing. We'll fix this out asap in the DEV branch, then merge to Master.

**Comment by eiximenis** [comment]
Hi @davidbritch 

Xamarin app has been updated and it is on dev branch. :)
