### ISSUE TITLE
Investigate using the OIDC library to communicate with IdentityServer from the Xamarin client

### ISSUE THREAD

**Issue by davidbritch** [dotnet-architecture/eShopOnContainers#215]
The OIDCClient is certified by the OpenID Foundation and represents a best practice for communicating with IdentityServer. Investigate using it from the Xamarin client, instead of consuming the REST APIs manually.

**Comment by davidbritch** [comment]
Having investigated the OIDCClient, it should definitely be used by the Xamarin client in place of building the IdentityServer URLs manually.

v1 of the OIDCClient is based on PCL technology, and it's no longer recommended to use it. v2 of the OIDCClient uses .NET standard, and is certified by the OpenID Foundation. However, this presents some problems for the Xamarin client at the moment. While it can be shoe-horned into the app, it's going to make the app less performant at this time.

Xamarin.Forms 3, due out later this year, is going to include support for .Net Standard 2.0. Once this is released the app will be updated to use Xamarin.Forms 3, and that will be a suitable time to bring the OIDCClient in the app.

**Comment by davidbritch** [comment]
Xamarin.Forms 2.4 (currently a pre-release) adds support for .NET Standard. Once this version moves to a stable release (within a few weeks hopefully) I'll be able to complete this work item.

**Comment by mdonogma** [comment]
? is this resolved yet as I'd like to test it

**Comment by davidbritch** [comment]
Afraid not. There are still some issues with using .NET Standard in Xamarin apps in both VSMac and VS2017. These should be fixed in the next release. Then I can move the eShopOnContainers mobile app to .NET Standard and complete this work item.

**Comment by mvelosop** [comment]
Closed as it was included in the [Roadmap (vNext)](https://github.com/dotnet-architecture/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases#vnext).

**Comment by davidbritch** [comment]
Closing. Will be discussed as part of FY20 planning.
