### ISSUE TITLE
Replace the WebView in the Xamarin client with device web browsers

### ISSUE THREAD

**Issue by davidbritch** [dotnet-architecture/eShopOnContainers#216]
From the OAuth 2 spec for native apps:

"The best current practice for authorising users in native apps is to perform the OAuth authorisation request in an external user-agent (typically the browser), rather than an embedded user-agent (such as one implement with web-views). 

Previously it was common for native apps to use embedded user-agents (commonly implemented with web-views) for OAuth authorization requests.  That approach has many drawbacks, including the host app being able to copy user credentials and cookies, and the user needing to authenticate from scratch in each app.

Native app authorization requests that use the browser are more secure and can take advantage of the user's authentication state. Being able to use the existing authentication session in the browser enables single sign-on, as users don't need to authenticate to the authorization server each time they use a new app (unless required by authorization server policy)."

https://tools.ietf.org/html/draft-ietf-oauth-native-apps-12

**Comment by davidbritch** [comment]
I've created a prototype that does this on all three mobile platforms. This will enable me to remove the `WebView` based authentication from the app, instead using native browsers to perform the front channel authentication.

My next task is to refactor it into a form that can be more easily consumed by the mobile app.

**Comment by ruisilva450** [comment]
Do you have any news on this matter?

**Comment by davidbritch** [comment]
This work item is going to be completed for v2 of the app, at some point next year. In the meantime, if required I can send you a prototype that shows how to do it.

**Comment by mvelosop** [comment]
Closed as it was included in the [Roadmap (vNext)](https://github.com/dotnet-architecture/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases#vnext).

**Comment by jlucaspains** [comment]
@davidbritch can you send me the prototype?

**Comment by davidbritch** [comment]
@jlucaspains Can do if you send me your email address.

**Comment by davidbritch** [comment]
Closing. Will be discussed as part of FY20 planning.
