### ISSUE TITLE
Grace Period Manager Client is trying to connect to database server

### ISSUE THREAD

**Issue by marcote** [dotnet-architecture/eShopOnContainers#226]
Hi there,

When running the app using `docker-compose up ` using `dev` branch I have the following errors:

```
...
graceperiodmanager_1  | info: GracePeriodManager.Services.ManagerService[0]
graceperiodmanager_1  |       Grace Period Manager Client is trying to connect to database server
...
```

`graceperiodmanager_1` keeps indefinitely trying to connect to something without success.

SPA site works, but seeing this in the console is rather annoying.

Details:
Docker Version 17.03.1-ce-mac12 (17661)
Branch: Dev

Not sure what other details I should provide.

Thanks in advance

**Comment by eiximenis** [comment]
Hi @marcote 

It is just an annoying log that occurs even thought when graceperiodmanager can connect to db server. Will fix that.

**Comment by CESARDELATORRE** [comment]
I just eliminated that informational log message that the code was performing every time it is querying/polling to the Ordering database. We don't really need that logging message.
