### ISSUE TITLE
[Feedback] Consider using Bash instead of Powershell scripts

### ISSUE THREAD

**Issue by marcote** [dotnet-architecture/eShopOnContainers#228]
Hi there,

It would be awesome if the team consider using bash scripts instead of poweshell ones. Bash scripts cover both platforms particularly in Windows using the Linux Subsystem.

macOS users like me have to translate .ps1 scripts to have a similar experience and I think that's something could be improve, specially in an architecture that targets different platforms.

Thanks

**Comment by SychevIgor** [comment]
100% agree, that we need .sh scripts for Linux only scenario. for example for k8 we have only powershell scripts, but we are deploying Linux cluster...

**Comment by SychevIgor** [comment]
@eiximenis task marked as self-assigned. May I create PR or you are almost done with it? @CESARDELATORRE

**Comment by mvelosop** [comment]
Closed as it was included in the [Roadmap (vNext)](https://github.com/dotnet-architecture/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases#vnext).
