### ISSUE TITLE
K8s deployments do not reflect/match current docker-compose

### ISSUE THREAD

**Issue by marcote** [dotnet-architecture/eShopOnContainers#230]
Hi there,

I tried to run the application and is really hard to understand all the moving pieces in order to deploy it in a Kubernetes cluster. On top of that, I'm services in the docker-compose file that are not present in existing deployments.

Maybe the solution is not ready yet for this kind of deployments.

Thanks

**Comment by eiximenis** [comment]
Hi!
Please, take a look at dev branch :)
I updated the kubernetes script, and the docs.

Script covers various possible scenarios, but here are the two more common.

Pushing images in DockerHub in your own organization and use these images for k8s:

```
./deploy.ps1 -dockerOrg YOUR_DOCKER_ORG-dockerUser MY_USER -dockerPassword MY_PASSWORD -configFile local.json
```

Using the images  provided my Microsoft:

 ```
./deploy.ps1 -buildImages false --configFile local.json -imageTag master
```

The file README.k8s.md contains more info about the deployment.

I am still working on it, fixing some issues. I hope to have it finished next Monday or Tuesday (7/4)

**Comment by marcote** [comment]
Thanks for the update. I'll keep an eye on those updates :)

**Comment by eiximenis** [comment]
I pushed some changes in the dev branch.

Thx!

**Comment by CESARDELATORRE** [comment]
Closing as the Kubernetes Scripts at DEV branch should have be deploying all the microservices
