### ISSUE TITLE
Improve app startup time of Xamarin client

### ISSUE THREAD

**Issue by davidbritch** [dotnet-architecture/eShopOnContainers#231]
It's been reported that it takes around 12 secs for the Xamarin client to startup on a physical Nexus 4. While this can be improved by setting specific compiler and linker options, a big saving can be made by refactoring the App class. At the moment this class initialises all the converters, which delays the appearance of the first page. Therefore, at a minimum, move the converter initialisation to the pages that use them.

**Comment by davidbritch** [comment]
Startup times in a DEBUG build, running in simulators:

iOS:
	 Components initialized: 00:00:00.3972690
	 App initialized: 00:00:00.5235910
	 LoginView displayed: 00:00:00.7422050
	 Navigation initialized: 00:00:01.0724970
	 LoginView OnAppearing finished: 00:00:01.2412350

Android:
	Components initialized: 00:00:01.5449110
	App initialized: 00:00:02.5697490
	LoginView displayed: 00:00:04.2680960
	Navigation initialized: 00:00:04.7124070
	LoginView OnAppearing finished: 00:00:06.1351460

The Android times are concerning, as they are far worse on an actual device.

**Comment by davidbritch** [comment]
Startup times in a RELEASE build, running in simulators:

iOS:
	Components initialized: 00:00:00.4868890
	App initialized: 00:00:00.5861820
	LoginView displayed: 00:00:00.7810920
	Navigation initialized: 00:00:01.0663590
	LoginView OnAppearing finished: 00:00:01.2264860

Android:
	 Components initialized: 00:00:01.3257730
	 App initialized: 00:00:02.0686260
	 LoginView displayed: 00:00:03.3888870
	 Navigation initialized: 00:00:03.8072440
	 LoginView OnAppearing finished: 00:00:04.9904820

**Comment by davidbritch** [comment]
While further refactoring can improve the startup time of the app on Android, the gains are going to be marginal. However, I'll continue with this refactoring.

Xamarin.Forms 3, due out later this year, is going to include a number of features that should have a significant impact on the app performance on Android. These includes bulk renderer creation, layout compression, fast renderers, reduced reflection in XAMLC, and avoiding GPU overdraw, amongst other items.

**Comment by davidbritch** [comment]
While the app uses Xamarin.Forms.Themes, it only uses a minimal set of styles from this library. Therefore I've removed the Xamarin.Forms.Themes NuGet packages (and the dependent Xamarin.Forms.DataPages package) from the PCL, platform projects, and test runner projects. Because the Xamarin.Forms.Themes.Light `ResourceDictionary` was merged into the app's `ResourceDictionary`, this is 1000+ less lines of XAML that need to be parsed at app startup.

As part of removing the NuGets I had to add a `CircleEffect` so that the `+` button on the `CatalogView` was still round, and do a small amount of styling work to ensure the app retained it's look.

**Comment by davidbritch** [comment]
Following the latest changes, here's the startup times in a RELEASE build on the simulators:

iOS:
Components initialized: 00:00:00.0554710
App initialized: 00:00:00.1615490
LoginView displayed: 00:00:00.3593750
Navigation initialized: 00:00:00.6317410
LoginView OnAppearing finished: 00:00:00.7658650

Android:
Components initialized: 00:00:00.1794550
App initialized: 00:00:00.9947740
LoginView displayed: 00:00:02.2856100
Navigation initialized: 00:00:02.5933460
LoginView OnAppearing finished: 00:00:03.6805290

**Comment by davidbritch** [comment]
Another speed up can be achieved by replacing Autofac with a better performing IoC container.

For more info, see this blog post about IoC container performance: https://xamarinhelp.com/ioc-container-performance/

**Comment by mvelosop** [comment]
Closed as it was included in the [Roadmap (vNext)](https://github.com/dotnet-architecture/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases#vnext).

**Comment by karlingen** [comment]
@davidbritch or anyone else using this, do you have any idea why a view is not shown instantly although there's not an API call in between navigating to the View and the actual display? 

Here's video demonstration: https://www.dropbox.com/s/nf3ex5sb0sudljn/eshoponcontainers_delay.mov?dl=0

As you can see in the video it takes about a second after clicking on the settings icon until the SettingsView is fully rendered.

**Comment by davidbritch** [comment]
@karlingen Thanks for bringing this to my attention. I confirm that I can reproduce this issue, and that it only occurs on iOS. I have some thoughts on why it's occurring, so I'll investigate further this week.

**Comment by davidbritch** [comment]
@karlingen Fixed via #632

**Comment by mvelosop** [comment]
Hi @davidbritch, just wondering if this issue was fixed or improved by the switch to TinyIoc you mentioned a few days ago in another issue?

**Comment by davidbritch** [comment]
Hi @mvelosop 

Switching to TinyIoC improved the startup time considerably, but there are other optimisations that could be made.

**Comment by mvelosop** [comment]
Thanks @davidbritch, I was just checking in case you could close this issue. 😊

**Comment by davidbritch** [comment]
Closing. Will be discussed as part of FY20 planning.
