### ISSUE TITLE
[QUESTION] Authorize basket API against Identity server from Swagger

### ISSUE THREAD

**Issue by i02coroj** [dotnet-architecture/eShopOnContainers#233]
Hi.
I've got an issue when debugging and testing the APIs:
The thing is when I try to debug any method in an authorized api (for example basket) I always obviously get an 401 error.
To avoid it, I run one of the client applications and that way I can authenticate.
But that's slow, I would like to just debug basket API controllers using Swagger interface without having to run any client.

I see the folder Auth inside the project and I thought it was for that but it doesn't look to solve my problem.

Someone can guide me?
Thank you!

**Comment by i02coroj** [comment]
I guess this was the wrong forum to put this question.
Just if someone is curious: I solved the issue adding a security definition in Swagger defintion (in Startup --> ConfigureServices). Auth folder is not actually needed.

**Comment by ramonTC** [comment]
Hi i02coroj,

We have added the possibility to get authorize through swagger in APIs.
Hopefully, this will be integrated in Master branch today.

Thanks.

**Comment by i02coroj** [comment]
Great.
Thank you ramonTC.
