### ISSUE TITLE
Porting from VS2015 to VS2017 problem with Package Microsoft.TestPlatform.ObjectModel

### ISSUE THREAD

**Issue by moliveto** [dotnet-architecture/eShopOnContainers#236]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Microsoft.TestPlatform.ObjectModel 11.0.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1) / win8-x64. Package Microsoft.TestPlatform.ObjectModel 11.0.0 supports:
  - net35 (.NETFramework,Version=v3.5)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)	InfinitasHotelProvider	D:\eBookingV4\src\InfinitasHotelProvider\InfinitasHotelProvider.csproj	1

**Comment by CESARDELATORRE** [comment]
Closing. This issue doesn't look related to eShopOnContainers which only supports VS2017 (Master and Dev branch)
