### ISSUE TITLE
eShopOnContainers.sln does not build

### ISSUE THREAD

**Issue by ridomin** [dotnet-architecture/eShopOnContainers#237]
Looks like there are missing projects like DataProtection

**Comment by CESARDELATORRE** [comment]
Yes, that particular global solution needs to be fixed. We usually use the eShopOnContainers-ServicesAndWebApps.sln solution which is the one mentioned to be used at the Wiki when working with services and Docker.

**Comment by CESARDELATORRE** [comment]
Fixed here in DEV branch: https://github.com/dotnet-architecture/eShopOnContainers/commit/fddd9fb481db5063fee7ddcab8ebad8f60e85907

Closing this issue.
