### ISSUE TITLE
Fail 2 Build

### ISSUE THREAD

**Issue by robpahl** [dotnet-architecture/eShopOnContainers#240]
I get the following type of build errors

1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4633,5): error MSB3491: Could not write lines to file "obj\Debug\netstandard1.3\Microsoft.Extensions.HealthChecks.AzureStorage.csproj.FileListAbsolute.txt". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4876,5): error MSB3491: Could not write lines to file "obj\Debug\netstandard1.3\Microsoft.Extensions.HealthChecks.AzureStorage.csproj.FileListAbsolute.txt". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

And

1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Cannot find project info for 'C:\Users\xx\Documents\Visual Studio 2017\Projects\eShopOnContainers-dev\src\BuildingBlocks\EventBus\EventBus\EventBus.csproj'. This can indicate a missing project reference.

1>Done building project "Microsoft.Extensions.HealthChecks.AzureStorage.csproj" -- FAILED.
1>Done building project "Catalog.API.csproj" -- FAILED.
1>Done building project "Marketing.API.csproj" -- FAILED.

Also had problems with the EventBus untill I manually included the CommandBus.proj (Not sure if this is correct as I can't build the Solution).

Anyone with a clue to set me on track?

**Comment by CESARDELATORRE** [comment]
A few actions to check:
- Make sure you follow the setup instructions provided at the Wiki, when using VS 2017, step by step.
- Make sure you use the solution eShopOnContainers-ServicesAndWebApps.sln 
- Change your base folder for your local GitHub repo to a shorter local path, like C:\GitRepos\eShopOnContainers

Please, answer if you still have issues after following the above recommendations.

**Comment by robpahl** [comment]
eally close now. 

I'm down to two scenarios. On  a clean machine I see the following:

... sudio.Docker.Compose.targets(192,5): error MSB4018: The "PrepareForLaunch" task failed unexpectedly.
... sudio.Docker.Compose.targets(192,5): error MSB4018: Microsoft.DotNet.Docker.CommandLineClientException: The ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not set. Defaulting to a blank string.
... sudio.Docker.Compose.targets(192,5): error MSB4018: The ESHOP_AZURE_STORAGE_CATALOG_KEY variable is not set. Defaulting to a blank string.
... sudio.Docker.Compose.targets(192,5): error MSB4018: The ESHOP_AZUREFUNC_CAMPAIGN_DETAILS_URI variable is not set. Defaulting to a blank string.
... sudio.Docker.Compose.targets(192,5): error MSB4018: The ESHOP_AZURE_STORAGE_MARKETING_NAME variable is not set. Defaulting to a blank string.
... sudio.Docker.Compose.targets(192,5): error MSB4018: The ESHOP_AZURE_STORAGE_MARKETING_KEY variable is not set. Defaulting to a blank string.
... sudio.Docker.Compose.targets(192,5): error MSB4018: Creating network "dockercompose1341272210_default" with the default driver
... sudio.Docker.Compose.targets(192,5): error MSB4018: Building webstatus
... sudio.Docker.Compose.targets(192,5): error MSB4018: Pulling basket.data (redis:latest)...
... sudio.Docker.Compose.targets(192,5): error MSB4018: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io: no such host.

in the machin running as a vm undr hyper-v with nested virtualization on I see this.

**Comment by CESARDELATORRE** [comment]
Are you following the procedures at the Wiki, step by step? The Azure variables are not needed when deploying to a Docker for Windows dev environment

**Comment by robpahl** [comment]
The only thing I have omitted related to the Wiki instructions are the Docker advanced settings (3 CPU's, 4 GB. and the Shared drive settings) This due to me not having the Advanced alternative inte the Docker settings. (Not sure why, downloaded per instructions, and see no other package.) I have run some other Test and Docker debugging worked out there.  Hmm. Getting late here, will look with fresh eyes tomorrow.

**Comment by CESARDELATORRE** [comment]
You need to do that in Docker for Windows Settings. Other than that you won't be able to run the SQL Server container which requires more memory. Also you need to share the drives or Visual Studio won't be able to launch/debug.

**Comment by robpahl** [comment]
For some reason "Docker's system tray->Settings->Advanced " Settings are not available, but after some googling I found out an alternative. Open the Hyper-V Manager and set the params. for MobyLinuxVM.

It still do not build. I will pause for now, and look fresh tomorrow. Thanks Cesar for taking the time, appreciated!

**Comment by CESARDELATORRE** [comment]
Closing, for now, as this looks like an environment issue with no further info.

**Comment by robpahl** [comment]
To fill in the resolution. My rookie mistake was that I had changed the Docker settings to use "Windows Containers". Once reverting to the default settings all worked like a charm.
