### ISSUE TITLE
eShopOnContainers Mobile App doesn't build in VSMac

### ISSUE THREAD

**Issue by davidbritch** [dotnet-architecture/eShopOnContainers#242]
The eShopOnContainers mobile app doesn't build in VSMac. There are 19 build errors because it can't import the System.ComponentModel.DataAnnotations namespace without changing the PCL profile.

Then, once those errors go away, it still won't build on either iOS or Android (not tried UWP) because it can't resolve the 'Plugin.Geolocator.Abstractions' assembly.

Last time I tried the mobile app it worked.

**Comment by davidbritch** [comment]
https://developercommunity.visualstudio.com/content/problem/80508/references-are-broken-even-though-nugets-have-been.html

**Comment by CESARDELATORRE** [comment]
It should be fixed now in the DEV branch (which is now the by default branch until we freeze the code, as we want PRs to go to DEV branch)

**Comment by davidbritch** [comment]
It's definitely NOT fully fixed in the DEV branch. While the 19 build errors have gone, and it builds and runs fine on Android, there's still one build error on iOS (from VSMac):

Error MT2002: Failed to resolve assembly: 'Plugin.Geolocator.Abstractions, Version=3.0.4.0, Culture=neutral, PublicKeyToken=null' (MT2002) (eShopOnContainers.iOS)

**Comment by CESARDELATORRE** [comment]
OK, we'll continue fixing it plus testing the execution with fake data AND consuming the Docker containers.

**Comment by davidbritch** [comment]
I've fixed the iOS build error in the DEV branch, and also the iOS test runner project.
