### ISSUE TITLE
docker-compose project load error

### ISSUE THREAD

**Issue by twingoliu** [dotnet-architecture/eShopOnContainers#243]
![qq 20170719104604](https://user-images.githubusercontent.com/12110186/28349248-302f2426-6c74-11e7-9f78-68a70ea58c81.png)

**Comment by CESARDELATORRE** [comment]
Can you try with an English version of VS 2017? I'd like to make sure if this is a localized to ChineseVV2017 issue so we escalate it to the VS Tools for Docker team.

**Comment by MarcinHoppe** [comment]
I had the same thing when VS 2017 was installed by installer using pl-PL locale. Reinstalling VS with en-US locale did the trick:

> vs_professional.exe --locale en-US

**Comment by twingoliu** [comment]
I was reinstalled an enterprise version of vs2017，and the issue was gone!
