### ISSUE TITLE
Catalog.API Container Runtime Error- System.IO.FileNotFoundException: Could not find file '/app/Setup/CatalogItems.zip'

### ISSUE THREAD

**Issue by dooney** [dotnet-architecture/eShopOnContainers#245]
It is due to the file 'Catalogitems.zip' with a lowercase 'i' in src/Services/Catalog/Catalog.API/Setup/

**Comment by eiximenis** [comment]
Need to change the casing in the Git index... Thanks!

**Comment by CESARDELATORRE** [comment]
Closing. I fixed this bug a few days ago.
