### ISSUE TITLE
[Feedback] Identity.API Design - Set scope names as config in DB or similar, not hard-coded

### ISSUE THREAD

**Issue by dooney** [dotnet-architecture/eShopOnContainers#248]
1. Couplings. Can see dependencies on the other microservices.
2. MVC. Reason?

**Comment by eiximenis** [comment]
Hi! 

1. Which dependencies are you referring?
2. Identity.API is a customization of IdSvr. IdSvr is a MVC app. MVC is used for showing login/logout pages (and any other page related with identity management flow).

Probably Identity.API is not the best name for this service, because is not an API, it is really a full app.

**Comment by dooney** [comment]
Thanks for the reply.

1. Can see client registration hard coding in startup and configuration.
2. Think API is a better solution than MVC here.

**Comment by CESARDELATORRE** [comment]
Can you point to specific lines of code in regards the hard coded dependencies that you mean?

**Comment by dooney** [comment]
Definitely here, will find out more:

eShopOnContainers/src/Services/Identity/Identity.API/Configuration/Config.cs

**Comment by CESARDELATORRE** [comment]
So, what's the concrete code you propose for IdentityServer4 here? The Identity system needs to know what ApiResource is being requested, basically, it needs to "know" about the application resources.
That's the target usage for the API ApiResource, for instance.
If you propose a better code we'd be happy to accept pull requests with it, of course. :)

**Comment by eiximenis** [comment]
Hi @dooney,

The file you are pointing contains the definition of OIDC clients and OIDC scopes. This is not directly related to any other microservice. To keep things simple we are mapping one scope to one service. So, following code:

```
new ApiResource("orders", "Orders Service"),
new ApiResource("basket", "Basket Service"),
new ApiResource("marketing", "Marketing Service"),
new ApiResource("locations", "Locations Service")
```

Is **not** defining any microservice. It is just defining one scope (permission) that any client could request.

The clients definition contains **all clients** that want to use OIDC to identify. We have 3 basic clients (Xamarin App, MVC app, SPA app). Those three are needed to run the client applications. The other clients defined (like `locationsswaggerui') are used for swagger UI (so, swagger UI for locations microservice uses this client to login into IdSvr). As you can see any client request only the OIDC scopes that they need to run.

Thanks!

**Comment by eiximenis** [comment]
Just to clarify, we have the config by code to keep the things simple. But in complex systems this configuration (scopes and clients) could be read from database, allowing the creation of new scopes and clients without any impact on the OIDC server.

But again, i want to make clear that scope != microservice.

**Comment by dillorscroft** [comment]
Identity Server allows config to be defined in code and through a database.  If this is to be a reference architecture I'd suggest the database route however identity server does not prescribe the provider to use and in this context I think code based config is fine.

**Comment by dooney** [comment]
Can't deny this is coupling since have to change the CODE here when create new microservices, makes more sense to put this part into database.

**Comment by CESARDELATORRE** [comment]
Closing this issue
