### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by ASADeveloper** [dotnet-architecture/eShopOnContainers#249]
Any thought about the localization of messages and UI components?
I can't think of any non-trivial application which doesn't have localization.

By the way I have to say that this github repo reminds me of the N-Layered Domain-Oriented Architecture Guide with .NET (http://microsoftnlayerapp.codeplex.com).
Especially when I see Cesar and Unai in here. So it's like a déjà vu after 7 years ...
I still have nice memories from then...

Regards,
Arash

**Comment by CESARDELATORRE** [comment]
Hi Arash! Thanks for your feedback and your memories.. :)
So, we don't have any plan about localization and eShopOnContainers.

Having said that, I suggest to follow the guidance provided below for ASP.NET Core web apps:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization
https://github.com/aspnet/Localization

For localizing messages I initially see two choices:
1. Include all the language translations within the message itself (self-contained ). 
2. Send just IDs in the messages and have a shared-kernel microservice who owns the translation for any message text.

I initially like the self-contained message approach better as you don't depend on additional services. If you don't have many languages to localize to, that approach might be more decoupled. However, the origin/source of those messages within the origin microservice could follow a similar approach than when creating an ASP.NET Core app, as in the links above.

**Comment by ASADeveloper** [comment]
Hi Cesar,
Thank you for your answer and doing this work. 
If there is no plan for localization then I think it is better to close this issue.
