### ISSUE TITLE
CLI build (tested from Windows) is failing

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#257]
This is the error when trying to run the build from the docker build container:
"Docker-compose -f docker-compose.ci.build.yml up"

ERROR: 
ci-build_1  | /bin/bash: ./build-bits-linux.sh: /bin/bash^M: bad interpreter: No such file or directory

![image](https://user-images.githubusercontent.com/1712635/28984353-6edc9f5a-7912-11e7-8118-deecd08705ab.png)

**Comment by lloydfaulkner** [comment]
Try recreating /cli-linux/build-bits-linux.sh using Unix line feeds (like in notepad++). ^M (Ctrl+M) is a carriage return from Windows, so looks like it took on Windows line feeds when you cloned it.

**Comment by CESARDELATORRE** [comment]
Basically, if you have this issue, remove the Windows end-of-line characters using NOTEPAD++ like in the image below:
![image](https://user-images.githubusercontent.com/1712635/29007276-11309eda-7ab4-11e7-8cfe-13f71a940dab.png)
