### ISSUE TITLE
f5 ,got exception

### ISSUE THREAD

**Issue by infofromca** [dotnet-architecture/eShopOnContainers#266]
build ok, but f5 get exception.
![run-ex](https://user-images.githubusercontent.com/297675/29020471-1cbdf7f8-7b30-11e7-9b23-13e6d409306a.png)

hello-world is ok

**Comment by JNuijten** [comment]
Did you do everything on here? https://github.com/dotnet-architecture/eShopOnContainers/wiki/02.-Setting-eShopOnContainers-in-a-Visual-Studio-2017-environment

**Comment by infofromca** [comment]
i followed 02 just now, it is ok, so close
