### ISSUE TITLE
[Question] Move to .NET Core 2.0 "wave"

### ISSUE THREAD

**Issue by ASADeveloper** [dotnet-architecture/eShopOnContainers#272]
Any plan to move to ASP.NET Core 2.0 in the near future?

I see there is a .net core 2.0 branch but it seems to be out-dated.

**Comment by CESARDELATORRE** [comment]
Yes, we’ll be moving to .NET Core 2.0 as our “default version” in a few weeks. Hopefully, by the end of August if not sooner.
There are a few folks in the team having a few vacation days after releasing .NET Core 2.0, so things will go a bit slower for a few days, but we’ll resume soon.
As of today, we already have a testing branch for .NET Core 2 named “netcore2” here: https://github.com/dotnet-architecture/eShopOnContainers/tree/netcore2
 
We just tested that branch with VS 2017 15.3 RTM and .NET Core 2.0 RTM and it works ok. However, we still need to merge branches and evolve a few things. That branch is not final for .NET Core 2. Some things are not up to date in regards our code, but good for testing with .NET Core 2.
Thanks,

**Comment by CESARDELATORRE** [comment]
Closing this issue in order to clean up the issues list. ASP.NET Core 2.0 is already in our roadmap for the upcoming weeks.
Thanks for your feedback. :)
