### ISSUE TITLE
Upgrade to .netstandard 2.0, asp.net core 2.0 and entity framework core 2.0

### ISSUE THREAD

**Issue by ghd258** [dotnet-architecture/eShopOnContainers#273]
Upgrade to .netstandard 2.0, asp.net core 2.0 and entity framework core 2.0

**Comment by CESARDELATORRE** [comment]
Closing as this is similar to this other issue where I already answered:
https://github.com/dotnet-architecture/eShopOnContainers/issues/272 
Thanks,
