### ISSUE TITLE
[Feedback] Consider using ASP.NET Core Identity 2.0

### ISSUE THREAD

**Issue by ASADeveloper** [dotnet-architecture/eShopOnContainers#275]
Please consider using ASP.NET Core Identity 2.0 instead or alongside of the current IdentityServer4. Especially because of the simplicity and the Azure AD B2C support. But I'm sure you could find more reason for it.

**Comment by CESARDELATORRE** [comment]
We will probably keep using IdentityServer4 until ASP.NET Identity can cover all the scenarios we need (remote Xamarin App getting tokens in addition to the MVC and SPA app, etc.).
However, we're actually using ASP.NET Core 1.1 Identity within the service using IdentityServer4.
We'll be migrating the internal code to make use of ASP.NET Core 2.0 Identity in the upcoming weeks, hopefully finished by early/mid September.
Thanks for the feedback.

**Comment by CESARDELATORRE** [comment]
Closing this issue to clean up the list of issues. 
ASP.NET Core Identity 2.0 is already in our roadmap for eShopOnCointainers heading to ASP.NET Core 2.0 in the upcoming weeks.

**Comment by CESARDELATORRE** [comment]
Just to add that we'll be evolving it further with ASP.NET Identity when ASP.NET Core Identity 2.1 is release which has the features we need.
