### ISSUE TITLE
Unable to Build Solution.

### ISSUE THREAD

**Issue by TEJA1122** [dotnet-architecture/eShopOnContainers#276]
Errors On Start of eShopOnContainers-ServicesAndWebApps.sln Solution
Error occurred while restoring NuGet packages: The operation failed as details for project IntegrationTests could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project IntegrationTests could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project UnitTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project UnitTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project UnitTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project UnitTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.Extensions.HealthChecks.AzureStorage could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.Extensions.HealthChecks.AzureStorage could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.Extensions.HealthChecks.AzureStorage could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.Extensions.HealthChecks.AzureStorage could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.Extensions.HealthChecks.AzureStorage could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.Extensions.HealthChecks.AzureStorage could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.Extensions.HealthChecks.AzureStorage could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.Extensions.HealthChecks.AzureStorage could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.Extensions.HealthChecks could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project WebStatus could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project WebStatus could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project WebStatus could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project WebStatus could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project WebStatus could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Locations.API could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Locations.API could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Locations.API could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Locations.API could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Locations.API could not be loaded.

and when I try to build It hungs up and stays in Build Mode even after 2 hours.
![image](https://user-images.githubusercontent.com/12316708/29421287-f15ff4b8-83b7-11e7-8747-723c92bee4b7.png)

**Comment by CESARDELATORRE** [comment]
That issue is related to your VS 2017 environment.
Can you try in a different PC or re-installing or updating VS 2017. Looks you have any issue in VS itself or when trying to reach Nuget..

**Comment by TEJA1122** [comment]
Hi Thanks for the quick response
Updated VS 2017 and manually updated the Nuget Packages, It's working

Thanks

**Comment by CESARDELATORRE** [comment]
Closing this issue
