### ISSUE TITLE
Autofac.Core.DependencyResolutionException 

### ISSUE THREAD

**Issue by gponduri** [dotnet-architecture/eShopOnContainers#277]
I am getting the below exception when trying to do a Post. Given below is exception detail and code snippet of autofac registrations. My command handlers are not getting registered with MEdiatR. It does not find the corresponding handler to the command.
Autofac.Core.DependencyResolutionException occurred
  HResult=0x80131500
  Message=An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = CreateTemplateCommandHandler (ReflectionActivator), Services = [MediatR.IAsyncRequestHandler`2[[Templates.API.Application.Commands.CreateTemplateCommand, Templates.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Templates.API.Startup.<>c__DisplayClass9_0.<ConfigureServices>b__7(Type t) in C:\Users\c105383\Source\Repos\FTP Service\Templates.API\Startup.cs:line 149
   at MediatR.Internal.RequestHandlerBase.GetHandler(Type requestType, SingleInstanceFactory singleInstanceFactory, Collection`1& resolveExceptions)

Inner Exception 1:
DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = TemplateRepository (ReflectionActivator), Services = [Templates.Domain.AggregatesModel.TemplateAggregate.ITemplateRepository], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope

Inner Exception 2:
DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = TemplateContext (ReflectionActivator), Services = [Templates.Infrastructure.TemplateContext], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope

Inner Exception 3:
DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.EntityFrameworkCore.DbContextOptions, MediatR.IMediator)' on type 'TemplateContext'.

Inner Exception 4:
FileNotFoundException: Could not load file or assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

My StartUp.cs file has the following lines of code to register the autofac modules
       builder.RegisterModule(new MediatorModule());
       builder.RegisterModule(new ApplicationModule(Configuration["ConnectionString"]));

Below is code in the MediatorModule where I registered the dependencies
      builder.RegisterAssemblyTypes(typeof(CreateTemplateCommand).GetTypeInfo().Assembly)
                .As(o => o.GetInterfaces()
                    .Where(i => i.IsClosedTypeOf(typeof(IAsyncRequestHandler<,>)))
                    .Select(i => new KeyedService("IAsyncRequestHandler", i)));

            builder.Register<SingleInstanceFactory>(ctx => {
                var c = ctx.Resolve<IComponentContext>();
                return t => { object o; return c.TryResolve(t, out o) ? o : null; };
            }).InstancePerLifetimeScope();

            builder
              .RegisterAssemblyTypes(typeof(CreateTemplateCommandValidator).GetTypeInfo().Assembly)
              .Where(t => t.IsClosedTypeOf(typeof(IValidator<>)))
              .AsImplementedInterfaces();

            builder.Register<MultiInstanceFactory>(ctx => {
                var c = ctx.Resolve<IComponentContext>();
                return t => (IEnumerable<object>)c.Resolve(typeof(IEnumerable<>).MakeGenericType(t));
            }).InstancePerLifetimeScope();

In the application module, the following are registered. 
            builder.RegisterType<TemplateRepository>().As<ITemplateRepository>().InstancePerLifetimeScope();
            builder.RegisterType<RequestManager>().As<IRequestManager>().InstancePerLifetimeScope();
            builder.RegisterType<TemplateContext>().As<DbContext>().InstancePerLifetimeScope();
            builder.RegisterType<TemplatesController>().InstancePerLifetimeScope();
            builder.RegisterType<TemplateIntegrationEventService>().As<ITemplateIntegrationEventService>().InstancePerLifetimeScope();

Please let me know your inputs as to what could be the possible root causes with the registration code.

**Comment by CESARDELATORRE** [comment]
That exception is happening with code changes you are doing, right?

**Comment by gponduri** [comment]
Yes. I may be incorrectly registering all the dependencies. Do we need to mention the BeginLifetimeScope anywhere? Looking at sample solution this does not seem to be done anywhere?

**Comment by gponduri** [comment]
Is there any update on what could be the issue here?

**Comment by unaizorrilla** [comment]
Hi @gponduri ...

Is your TemplateRepository registered on ServiceCollection?In this project of Autofac modules are used in order to register dependencies. See https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.API/Infrastructure/AutofacModules/ApplicationModule.cs to view one sample of this.

**Comment by gponduri** [comment]
Yes i Am

 builder.RegisterType<TemplateRepository>().As<ITemplateRepository>().InstancePerLifetimeScope();
The TemplateRepository constructor accepts a TemplateContext object. Would the registration of TemplateReposiory need to change accordingly

**Comment by unaizorrilla** [comment]
Yes, you need to register all dependency chain

**Comment by gponduri** [comment]
Thank You., We resolved this issue,

**Comment by mhfarhoudi** [comment]
1. 

-
