### ISSUE TITLE
Unable to Connect to the Server.

### ISSUE THREAD

**Issue by TEJA1122** [dotnet-architecture/eShopOnContainers#278]
![unable to connect to the server](https://user-images.githubusercontent.com/12316708/29458813-38d314c2-8464-11e7-86d4-592b9db209d2.JPG)

An unhandled exception occurred while processing the request.
WinHttpException: A connection with the server could not be established
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
HttpRequestException: An error occurred while sending the request.
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
BrokenCircuitException: The circuit is now open and is not allowing calls.
Polly.CircuitBreaker.CircuitStateController.OnActionPreExecute() in CircuitStateController.cs, line 162
Stack Query Cookies Headers 
WinHttpException: A connection with the server could not be established
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult()
System.Net.Http.WinHttpHandler+<StartRequest>d__105.MoveNext()

Show raw exception details 
HttpRequestException: An error occurred while sending the request.
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult()
System.Net.Http.HttpClient+<FinishSendAsync>d__58.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.eShopOnContainers.BuildingBlocks.Resilience.Http.ResilientHttpClient+<>c__DisplayClass8_0+<<GetStringAsync>b__0>d.MoveNext() in ResilientHttpClient.cs
+
                var response = await _client.SendAsync(requestMessage);
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Polly.Policy+<>c__DisplayClass114_0+<<ExecuteAsync>b__0>d.MoveNext() in PolicyAsync.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Polly.CircuitBreakerSyntaxAsync+<>c__DisplayClass4_1+<<CircuitBreakerAsync>b__2>d.MoveNext() in CircuitBreakerSyntaxAsync.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Polly.CircuitBreaker.CircuitBreakerEngine+<ImplementationAsync>d__1.MoveNext() in CircuitBreakerEngineAsync.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Polly.Policy+<ExecuteAsync>d__94.MoveNext() in PolicyAsync.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Polly.Wrap.PolicyWrapEngine+<>c__DisplayClass7_0+<<ImplementationAsync>b__0>d.MoveNext() in PolicyWrapEngineAsync.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Polly.RetrySyntaxAsync+<>c__DisplayClass21_0+<<WaitAndRetryAsync>b__1>d.MoveNext() in RetrySyntaxAsync.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Polly.Retry.RetryEngine+<ImplementationAsync>d__1.MoveNext() in RetryEngineAsync.cs

Show raw exception details 
BrokenCircuitException: The circuit is now open and is not allowing calls.
Polly.CircuitBreaker.CircuitStateController.OnActionPreExecute() in CircuitStateController.cs
Polly.CircuitBreaker.CircuitBreakerEngine+<ImplementationAsync>d__1.MoveNext() in CircuitBreakerEngineAsync.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Polly.Policy+<ExecuteAsync>d__94.MoveNext() in PolicyAsync.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Polly.Wrap.PolicyWrapEngine+<>c__DisplayClass7_0+<<ImplementationAsync>b__0>d.MoveNext() in PolicyWrapEngineAsync.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Polly.RetrySyntaxAsync+<>c__DisplayClass21_0+<<WaitAndRetryAsync>b__1>d.MoveNext() in RetrySyntaxAsync.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Polly.Retry.RetryEngine+<ImplementationAsync>d__1.MoveNext() in RetryEngineAsync.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Polly.Retry.RetryEngine+<ImplementationAsync>d__1.MoveNext() in RetryEngineAsync.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Polly.Policy+<ExecuteAsync>d__94.MoveNext() in PolicyAsync.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Polly.Wrap.PolicyWrapEngine+<ImplementationAsync>d__7.MoveNext() in PolicyWrapEngineAsync.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Polly.Policy+<ExecuteAsync>d__114.MoveNext() in PolicyAsync.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.eShopOnContainers.BuildingBlocks.Resilience.Http.ResilientHttpClient+<HttpInvoker>d__10.MoveNext() in ResilientHttpClient.cs
+
            return await policyWrap.ExecuteAsync(action, new Context(normalizedOrigin));
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.eShopOnContainers.WebMVC.Services.CatalogService+<GetCatalogItems>d__5.MoveNext() in CatalogService.cs
+
            var dataString = await _apiClient.GetStringAsync(allcatalogItemsUri);
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.eShopOnContainers.WebMVC.Controllers.CatalogController+<Index>d__2.MoveNext() in CatalogController.cs
+
            var catalog = await _catalogSvc.GetCatalogItems(page ?? 0, itemsPage, BrandFilterApplied, TypesFilterApplied);
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__27.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__25.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeAsync>d__20.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__18.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Session.SessionMiddleware+<Invoke>d__9.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Session.SessionMiddleware+<Invoke>d__9.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by CESARDELATORRE** [comment]
@TEJA1122 That happens (out Open Circuit Exception) when the number of Http retries reached the maximum number specified in the code (5 or 6 times).
The cause is usually because either the microservice trying to be consumed is not available or the SQL database is not available.
Check with "docker ps" if all the containers are up and running.
Also, you probably got other initial exceptions/errors when starting up the application that will probably be the cause.
Make sure you follow, step-by-step, the instructions here in regards Docker config with enough memory for the SQL container, etc.:
https://github.com/dotnet-architecture/eShopOnContainers/wiki/02.-Setting-eShopOnContainers-in-a-Visual-Studio-2017-environment

**Comment by TEJA1122** [comment]
@CESARDELATORRE Awesome Thank you very much 👍

**Comment by TEJA1122** [comment]
Leave a comment
