### ISSUE TITLE
Unhandled exception when add items to the cart from SPA and try to update/checkout cart from MVC

### ISSUE THREAD

**Issue by lurumad** [dotnet-architecture/eShopOnContainers#283]
Steps to reproduce:

1. Open SPA http://localhost:5104 and add item to the cart
2. Open MVC http://localhost:5100, go the cart and try to update/checkout and you received this error:

![image](https://user-images.githubusercontent.com/1729519/29576929-ed49233a-8769-11e7-9a72-f9ac0a490ae9.png)

The problem is related like how SPA and MVC apps save an item into the cart. 

If you add from MVC, and look for in Redis, the item Id is present:

```json
{
  "BuyerId": "46085348-2749-4372-ae20-75972ffb47e8",
  "Items": [
    {
      "Id": "157d7b16-e6ee-4e3c-8e61-e58fe0aa7e2e",
      "ProductId": "2",
      "ProductName": ".NET Black & White Mug",
      "UnitPrice": 8.5,
      "OldUnitPrice": 0.0,
      "Quantity": 1,
      "PictureUrl": "http://localhost:5101/api/v1/catalog/items/2/pic/"
    }
  ]
}
```
but, if you save from SPA, item Id is missing:

```json
{
  "BuyerId": "46085348-2749-4372-ae20-75972ffb47e8",
  "Items": [
    {
      "Id": "",
      "ProductId": "2",
      "ProductName": ".NET Black & White Mug",
      "UnitPrice": 8.5,
      "OldUnitPrice": 0.0,
      "Quantity": 1,
      "PictureUrl": "http://localhost:5101/api/v1/catalog/items/2/pic/"
    }
  ]
}
```

Regards!

**Comment by pmsousa** [comment]
I'm having the exact same issue but it started only this afternoon and only after 2 commits were done: 737bdda and 3dd456b.

Can't it be related?

**Comment by CESARDELATORRE** [comment]
This is fixed. Closing it.
