### ISSUE TITLE
Time of Order creation is not right compared to the dev machine's time

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#285]
Repro:
- Deploy the app in a local Docker (Docker for windows).
- Create and submit an Order
- Compare the time with the local time at the dev machine. 
Looks like the Docker Container and dev machine are nor in sync. in regards the time.
Depending on the TimeZone might be wrong, like in this case:
![image](https://user-images.githubusercontent.com/1712635/29583700-21f5e548-8736-11e7-9a3f-ab6561b7f833.png)

**Comment by ramonTC** [comment]
There seems to be a docker for windows bug related to this issue. 

https://github.com/docker/for-win/issues/72

**Comment by mvelosop** [comment]
Closing as this seems to be fixed now (Docker 17.12.0), even after sleeping the computer!

![image](https://user-images.githubusercontent.com/7357806/37198219-814939ba-2375-11e8-9e1d-cb49a60d08d7.png)
