### ISSUE TITLE
where setting Catalog.API Show Sql command?

### ISSUE THREAD

**Issue by chen110xi** [dotnet-architecture/eShopOnContainers#286]
I look console show print sql command,but I can not find where setting it.
help please!!!
In my project, I want console print like this:
```
dbug: Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory[5]
      TRACKED: True
      (QueryContext queryContext) => IAsyncEnumerable<CatalogItem> _ShapedQuery(
          queryContext: queryContext,
          shaperCommandContext: SelectExpression:
              SELECT [c].[Id], [c].[AvailableStock], [c].[CatalogBrandId], [c].[CatalogTypeId], [c].[Description], [c].[MaxStockThreshold], [c].[Name], [c].[OnReorder], [c].[PictureFileName], [c].[Price], [c].[RestockThreshold]
              FROM [Catalog] AS [c]
              ORDER BY [c].[Name]
              OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY
          ,
          shaper: UnbufferedEntityShaper<CatalogItem>
      )

dbug: Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection[3]
      Opening connection to database 'Microsoft.eShopOnContainers.Services.CatalogDb' on server 'tcp:127.0.0.1'.
```

**Comment by SychevIgor** [comment]
@chen110xi it's native logs of EntityFrameworkCore. EFCore will emit such logs without any extra actions from your side. But you will can see logs only if you will configure an accepter for this log. Console for example or file.
In a startup.cs file you have 

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            //Configure logs

            **loggerFactory.AddConsole(Configuration.GetSection("Logging"));**
            loggerFactory.AddDebug();
than in a settings file settings.json you can find 

 "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      **"Default": "Debug",**
      "System": "Information",
      "Microsoft": "Information"
    }

**Comment by CESARDELATORRE** [comment]
Closing this issue.
