### ISSUE TITLE
In the ASPNETCore2 version, Swagger is not working for the services

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#290]
In the In the ASPNETCore2 version, branch aspnetcore2, Swagger is not working for the services.
I.e. trying to access Swagger from http://localhost:5101/swagger/
![image](https://user-images.githubusercontent.com/1712635/29649546-8fcba2d8-8849-11e7-84f5-9860ff3918c8.png)

**Comment by ramonTC** [comment]
Fixed issue. Microsoft.AspNetCore.StaticFiles pkg was missing in api services.

**Comment by CESARDELATORRE** [comment]
Fixed, closing.
