### ISSUE TITLE
In the ASPNETCore2 version, after submitting a few orders, the Order microservice is in Open-Circuit state

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#291]
In the ASPNETCore2 version, after submitting a few orders, the Order page is in Open-Circuit state.
But I cannot reproduce it more times...

![image](https://user-images.githubusercontent.com/1712635/29649762-23afc6d6-884b-11e7-803e-afbea14668ca.png)

I still didn't find out how exactly to repro with specific steps, but this shouldn't happen.

When this happened, it got to the submitted state but never went to paid state, so it could be related to the IHostedService implementation for the Order GracePeriod...
![image](https://user-images.githubusercontent.com/1712635/29649862-ebdbcd12-884b-11e7-9b2c-4cdf9572dff2.png)

However, other times it is working properly and changing to the "paid" state...

**Comment by ramonTC** [comment]
Fixed issue. Mediator autofac module was registering GracePeriodM
anager hosted service. The ordering.api ended up initiating the hosted service twice.

**Comment by CESARDELATORRE** [comment]
Fixed, closing it.
