### ISSUE TITLE
docker-compose.vs.release.yml' was not found

### ISSUE THREAD

**Issue by infofromca** [dotnet-architecture/eShopOnContainers#292]
vs2017 pro
win10
![novsyml](https://user-images.githubusercontent.com/297675/29693931-82e5cac2-8906-11e7-8def-b551db62a38c.png)

dev branch 0e46a8c16daa6ae8333f09f5fed64af67119e832

**Comment by CESARDELATORRE** [comment]
@infofromca You need to install Visual Studio 2017 15.3.0 or later (Current last version is 15.3.2).
You probably are using VS2017 15.2 or lower.

**Comment by infofromca** [comment]
thanks
