### ISSUE TITLE
Error:  npm install

### ISSUE THREAD

**Issue by infofromca** [dotnet-architecture/eShopOnContainers#294]
![install-err](https://user-images.githubusercontent.com/297675/29740345-7b01a7dc-8a22-11e7-9f33-12a6c1c475e3.png)
dev and master branch

**Comment by CESARDELATORRE** [comment]
Are you trying the same version of NPM, as specified at the Wiki?
The latest versions of NPM have some issue with it.
If you install the LONG TERM version of Node, you should not have issues with the NPM version coming.
What version of Node do you have installed?

**Comment by infofromca** [comment]
![v](https://user-images.githubusercontent.com/297675/29744349-58a9ec68-8a71-11e7-8b2f-aac3694d9f0d.png)

**Comment by CESARDELATORRE** [comment]
As specified at the setup procedure:
https://github.com/dotnet-architecture/eShopOnContainers/wiki/06.-Setting-the-Web-SPA-application-up
Yo ushould use the NPM version 3.10.10 which is the LTS vresion (Long Term Support version):
![image](https://user-images.githubusercontent.com/1712635/29744615-9fd1caa2-8a5d-11e7-8ff7-2da1938f7e07.png)

Uninstall NODE and reinstall from here the LTS version of NODE from here:
https://nodejs.org/en/

**Comment by infofromca** [comment]
found the " issue".
after quit vs and docker. 
then npm install, start are good
it is because memory usage, so close this issue
