### ISSUE TITLE
[Question] How to connect with external client outside of docker to API and IdentityServer in Docker network

### ISSUE THREAD

**Issue by JNuijten** [dotnet-architecture/eShopOnContainers#301]
We are currently setting up a similar structure using API's and IdentityServer authentication/authorization in Docker as services. We are facing issues and tried using this project as a guideline, but it is not entirely clear how we can solve this and how it is solved in here. We need to build several API's, SPA clients and Xamarin clients. We recently hit a problem trying to connect to an API from outside of a docker network. 

We get validation errors on either the docker hostname or localhost and it seems we must use either one and cannot use both at the same time. This only happens if using a Xamarin client for example from outside of the docker network calling localhost on the identity server and then the API has to authorize on the hostname because it does not know of the identityserver on a localhost instance. Then the problem occurs where the Issuer URI does not validated correctly. We tried setting IssuerUri to hostnames but this does not solve the issue as both need to be supported.

Is this solvable? How did the eShopOncontainers solve this if it solved this issue at all? We are currently still developing and not in production, I guess it could create issues there as well running it deployed on a single server. 

I understand if this is not entirely in the scope of this project, but I hope the contributors here had faced similar issues and found some solutions already. There's not a whole lot if information available for our scenario currently.

**Comment by CESARDELATORRE** [comment]
You cannot use localhost from a remote Xamarin app, neither from web apps "in production" and/or remote.
You need to use either a real IP of the Docker host or a related DND name.
Take a look to the Wiki to the post named something like "Setting a Production environment" where it is explained how to set up the real Docker host IP (in dev. env it should be the PC network card IP)
We are using localhost and the by default IP in Windows 10.0.75.1 for authentication just for web dev environment so a F5 experience in VS works and people trying the solution don't need to mess up with the Docker host IP.

**Comment by JNuijten** [comment]
Thanks for your response, I got our development environment working the way I want I will take a look at the wiki when we're going to production. Thanks again.

**Comment by CESARDELATORRE** [comment]
Closing this issue
