### ISSUE TITLE
out of date wiki guide for vs2015

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#302]
https://github.com/dotnet-architecture/eShopOnContainers/wiki/05.-Setting-up-the-eShopOnContainers-solution-version-based-on-project.json-files-and-Visual-Studio-2015-environment
I think we can drop this guide, since we don't have project.json files anymore

**Comment by CESARDELATORRE** [comment]
Closing. Deleted already, :)
