### ISSUE TITLE
[Question]If I want to deploy all service on a linux server, is 2 CPUs and 4 GB memory powerful enough

### ISSUE THREAD

**Issue by LeonAppDev** [dotnet-architecture/eShopOnContainers#304]
I could see from the wiki the minimum requirement for debug and run the full service is a 16GB memory for a windows machine, how about I set up a dedicated Linux server which only runs these micro services as a production environment? 

Whether a 2 CPUs and 4 GB memory server powerful enough?

**Comment by CESARDELATORRE** [comment]
Could be enough, it mostly depends on the requirements needed by the SQL Server for Linux container.
The rest of the containers need less resources.
But you'd need to test it. We haven't tested that specific configuration.

**Comment by LeonAppDev** [comment]
Yes, thanks, I find out when running SQL Server for Linux container needs at least 3250 megabytes allocated for memory in my debug environment.
