### ISSUE TITLE
Swagger generation

### ISSUE THREAD

**Issue by Meir017** [dotnet-architecture/eShopOnContainers#305]
use the attribute `ProducesResponseType` on controllers actions.

this will make the swagger document be more accurate

**Comment by SychevIgor** [comment]
I think that answer will be similar to https://github.com/dotnet-architecture/eShopOnContainers/issues/315#issuecomment-327247013 
but - it's only my assumption

**Comment by CESARDELATORRE** [comment]
@SychevIgor Why is this related to Razor pages?

**Comment by SychevIgor** [comment]
Only first sentence your answer:
"The focus for this project is currently most of all about the microservices, not so much about the client apps. "

**Comment by Meir017** [comment]
would you accept a pull-request?

**Comment by CESARDELATORRE** [comment]
@Meir017 We will, just need to test it before and we have many other priorities. It won't be long, sorry. :)

**Comment by SychevIgor** [comment]
@CESARDELATORRE  looks like we can close this issue.
