### ISSUE TITLE
BundlerMinifier for .net core 2.0 error

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#308]
When we are trying to bundle components in .net core 2.0 version - we are failing with the error:

"PS C:\src\eShopOnContainers\src\Web\WebMVC> dotnet bundle
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      \
  - Alternatively, install the framework version '1.0.0'.
"
Problem is well known and as I can see the fix will be super simple - we need a new version of BundlerMinifier.Core package... and the version is ready in a sources, but not in a nuget.
https://github.com/madskristensen/BundlerMinifier/issues/292
Maybe internally we can speedup the release process for a little bit?

**Comment by eiximenis** [comment]
@CESARDELATORRE is there any way to *speedup* the release process?

Note that if you have netcore1.1 AND netcore2.0 `dotnet bundle` works, but this prevents using the build container (that do not have netcore1.1 installed)

**Comment by CESARDELATORRE** [comment]
Yes, I'm already talking to Mads and other folks in the team. Let's see.

**Comment by CESARDELATORRE** [comment]
I talked to Mads Kristensen. He just did it today after I asked him:
"Deployment of package version 2.5.357 to NuGet done. It will take a few minutes for NuGet to fully index the updated package."
So, let's test it! :)

**Comment by unaizorrilla** [comment]
Pushed on https://github.com/dotnet-architecture/eShopOnContainers/commit/7be5cb933d3dd9580c6c19ed93598e4e05c399a4

**Comment by CESARDELATORRE** [comment]
Please, Unai, add that change into the DEV branch. We're already working with NET Core 2 in the DEV branch.

**Comment by eiximenis** [comment]
It is in dev branch right now! :-)
