### ISSUE TITLE
EF Migrations on dev fail

### ISSUE THREAD

**Issue by ASADeveloper** [dotnet-architecture/eShopOnContainers#314]
Hi,
I'm just playing around with the application and added an extra column to the IntegrationEventLog table. But when I try to create migrations by this command:
`dotnet ef migrations add IntegrationEventTestColumn --output-dir ./Infrastructure/IntegrationEventMigrations --context IntegrationEventLogContext --project IntegrationEventLogEF --startup-project Ordering.API
`

I get the following error on console:

> MSBUILD : error MSB1009: Project file does not exist.
> Switch: IntegrationEventLogEF
> Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core project. If you're using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.

I'm doing this on **dev branche** and as far as I know I do not use anything like BaseIntermediateOutputPath or MSBuildProjectExtensionsPath.

Does anyone know how to add and run the migrations on the IntegrationEventLogContext or OrderingContext?

Thanks

**Comment by DaveAndersonCo** [comment]
Same here.
Probably we shoudn't play with it ;-)

**Comment by unaizorrilla** [comment]
Hi @ASADeveloper 

No problem in my side.. open a cmd into Ordering.API ( or any other netcoreapp) and execute dotnet ef. 

dotnet ef work ok and with 2.0.0-rtm version? If is ok  try to execute dotnet ef migrations add MySampleMigration --context OrderingContext

This create the migration on \Infrastructure\Migrations??

Thanks 
Unai

**Comment by ASADeveloper** [comment]
Hi @unaizorrilla 

dotnet ef works ok and with 2.0.0-rtm-26452 version. And dotnet ef migrations add MySampleMigration --context OrderingContext creates the migration files in the root folder under automatically created folder Migrations. Which is in my opinion correct.

However it does create the migration files inside \Infrastructure\Migrations when I add 
-o ./Infrastructure/Migrations (output folder) to it.
So it seems to work now for the OrderingContext. I must admit that I reverted almost all of my modifications. 

But the mentioned error regarding 'IntegrationEventLogContext' migration still gives the exact same error. See https://github.com/dotnet-architecture/eShopOnContainers/issues/314#issue-254885049

I'm stuck!

How do you add migration of IntegrationEventLogContext?

**Comment by DaveAndersonCo** [comment]
I don't think anybody knows it anymore ;-)

The migration files are very old and the code has been changed many times.

After spending many hours on this I came to conclusion that this is not a good approach for serious application. It is a weird and fragile way of doing Migrations and using multiple dbcontext. You definitely don't want to use this kind of migration in the production ready applications.

The problem you have has to do with Switch: IntegrationEventLogEF. Which actually says that he doesn't understand the IntegrationEventLogEF inside your add migrations command. You have to use relative path to the project. This is an example of what I mean and you have to adjust it for your own solution:

dotnet ef migrations add IntegrationEventInitial -o ../../../xxx/Ordering/Ordering.API/Infrastructure/IntegrationEventMigrations -c IntegrationEventLogContext -p ../../BuildingBlocks/EventBus/IntegrationEventLogEF

Remember that it adds migration files with the namespace of the IntegrationEventLogEF inside Ordering.API. And you might still have to 'hack' around to make it work.
It's very hacky to me and can't understand why the contributors gone this way.

Look at much better and production ready approaches like Asp.net core Identity and IdentityServer repositories.
