### ISSUE TITLE
"dotnet publish" as VSTS Build task errors

### ISSUE THREAD

**Issue by jamesbannan** [dotnet-architecture/eShopOnContainers#316]
I am trying to build and deploy the application stack to Kubernetes on ACS Engine using VSTS. But rather than use the documented approach by downloading and triggering the deploy.ps1, I'm breaking out the tasks using native VSTS steps. The current steps are:

![image](https://user-images.githubusercontent.com/8892953/30058999-952c923c-9280-11e7-9208-7b3688483b3b.png)

![image](https://user-images.githubusercontent.com/8892953/30059038-c1762dbc-9280-11e7-8f36-4d3da1041005.png)

![image](https://user-images.githubusercontent.com/8892953/30059042-c7fa80ca-9280-11e7-8011-ca2cfeee3c39.png)

The VSTS agent is running on Ubuntu 16.04 with .NET Core, Docker, Docker Compose, NPM and Node.

The restore step works fine, but the publish step errors out. The steps logs are here:

https://gist.github.com/jamesbannan/6243a5c6d5b62be9c4b98927e57fb6a7

I'm not sure whether this is a dependency failure on the build agent, or something else that I'm doing wrong. Any thoughts?

**Comment by eiximenis** [comment]
Hi @jamesbannan 

From logs seems that the publish of the MVC fails due to bower is not installed as a NPM global package.
You need to install bower as a global NPM package.

Are you using a custom VSTS build agent?

**Comment by jamesbannan** [comment]
Hi @eiximenis - thanks for the response. Yes, I finally figured out the dependency. I am using a custom VSTS Linux agent. I managed to sort out all the dependencies including the Microsoft.Docker.Sdk package. I'll close this issue down.
