### ISSUE TITLE
[Question] EventBusRabbitMQ.cs ProcessEvent resolve type with built in DI system

### ISSUE THREAD

**Issue by Franklin89** [dotnet-architecture/eShopOnContainers#323]
I am following this Project and I am wondering why you are using Autofac instead of the default DI system?

Using this a sample implementation and I do not want to use Autofac how would the method `ProcessEvent` look like with the default DI system?

I tried to inject the `IServiceProvider` into the `EventbusRabbitMQ` but then if I use a repository inside my EventHandler I get an error that the `DbContext` could not be resolved from the root container.

```csharp
        private async Task ProcessEvent(string eventName, string message)
        {
            if (_subsManager.HasSubscriptionsForEvent(eventName))
            {
                    var subscriptions = _subsManager.GetHandlersForEvent(eventName);
                    foreach (var subscription in subscriptions)
                    {
                        if (subscription.IsDynamic)
                        { 
                            var handler = _serviceProvider.GetRequiredService(subscription.HandlerType) as IDynamicIntegrationEventHandler;
                            dynamic eventData = JObject.Parse(message);
                            await handler.Handle(eventData);
                        }
                        else
                        {
                            var eventType = _subsManager.GetEventTypeByName(eventName);
                            var integrationEvent = JsonConvert.DeserializeObject(message, eventType);
                            var handler = _serviceProvider.GetService(subscription.HandlerType);
                            var concreteType = typeof(IIntegrationEventHandler<>).MakeGenericType(eventType);
                            await (Task)concreteType.GetMethod("Handle").Invoke(handler, new object[] { integrationEvent });
                        }
                    }
            }
        }
```

**Comment by CESARDELATORRE** [comment]
@Franklin89 We're using the by default ASP.NET Core IoC container in all the simpler microservices.
But, the ORDERING microservice is an example of a more complex approach based on Domain-Driven Design patterns plus some more advanced techniques like MediatR which also uses Autofac.
ASP.NET Core was designed to plug any IoC container, not just the by default IoC container, and in fact, Autofac is a lot more advanced IoC container than the by-default IoC container in ASP.NET Core. 
That is why we're using Autofac in this particular ORDERING microservice, to show further advanced approaches.
If you want to see how to use RabbitMQ and DI with the by default IoC container, I think you can take a look to the other microservices, like the CATALOG microservice, BASKET microservice, etc.

**Comment by Franklin89** [comment]
@CESARDELATORRE Thanks for getting back to me so fast and answering my question.
But I still see this in the CATALOG and BASKET Service:

```csharp
var container = new ContainerBuilder();
container.Populate(services);
return new AutofacServiceProvider(container.Build());
```

So having two IoC containers is that a smart idea or is that just to keep it simple and not have a second implementation of things like the EventBusRabbitMQ that relies on Autofac?
