### ISSUE TITLE
[Question] Best way to create API gateways

### ISSUE THREAD

**Issue by matteobortolazzo** [dotnet-architecture/eShopOnContainers#324]
Hi, in my project I need to create two API gateways, one for customers and one for management.
They are mostly API proxy (with authentication using Azure AD B2C) so that I can expose only the gateways,   use HTTP instead of HTTPs internally, authorize the user only one time once in my cluster and I can merge results from different services. 
I would like to use the WebApp's ResilientHttpClient so I'm thinking to add a resilient GetAsync and use dynamics for proxy Post request.
Is there a better way to do this?

**Comment by CESARDELATORRE** [comment]
That's a good approach when implementing custom API Gateways.
The other choice, if you don't need "data aggregation" but just Authentication and SSL termination is to use Azure API Management which would not require custom development.
You should make sure that Azure API Management supports Azure AD B2C (I'd expect it).
Then, Azure API Management offers you a lot more about information/documentation of your APIs, comprehensive and ready to explore API structure for external consumers, etc.
But if you cannot use Azure API Management for any reason, the approach you mentioned sounds good. :)

**Comment by matteobortolazzo** [comment]
Thanks it's my first microservices project, I think I'll use Azure API Management. I have to use more than 1 service only for validating "foreign keys" and for calculating distances.  It is correct, for example, to let the Catalog service asks to the Shops service if the given ShopID is valid before adding a product, even if it creates a chain?

**Comment by CESARDELATORRE** [comment]
Ideally, if you need info from other microservices, you should propagate that asynchronously with Integration Events and have it ready in that second microservice instead of ccreating Http chains.
sometimes, you need to make exceptions and do it, especially with 3rd party services, but if you can, you shouldn't do it.

**Comment by CESARDELATORRE** [comment]
Closing this one.

**Comment by matteobortolazzo** [comment]
Sorry, last question. You said to use IntegrationEvents to ask information but how can I wait for a response? I can only have IntegrationEventHandlers but I need an answer before continuing the transaction and reply to the client. Am I missing something?

**Comment by CESARDELATORRE** [comment]
I didn't say to ask. You use Integration Events to propagate data right after a transaction. For those attributes, they will be redundant data eventually consistent between microservices. But a specific attribute can be originally updated only from its originally owner microservice.
This is pretty similar to data projections towards the query databases in CQRS, I mean the way you use Integration Events.

**Comment by CESARDELATORRE** [comment]
If you want to query, do it using Http but from the client apps or from your API Gateways, like in a "star" approach. Do not create (eventually long) http calls across the internal Microservices.

**Comment by matteobortolazzo** [comment]
Ok thanks, everything is clear now!
