### ISSUE TITLE
Azure Native Services based deployment wiki page

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#325]
In a deploy folder we have set of arm templates with ServiceBus, COSMOSDB, Redis and so on, but we don't have detailed explanation of how/why we can use it and the roadmap for scenario when we will use this content.

I think we need some WIKI page with a setup guide and some description of what we are trying to do.

**Comment by CESARDELATORRE** [comment]
@SychevIgor The documentation on how to deploy infrastructure to Azure is here:
https://github.com/dotnet-architecture/eShopOnContainers/blob/master/deploy/readme.md

We will, eventually, write more detailed info with screenshots, etc. in the Wiki. I agree onyou comment, though, this documentation should be unified and aligned to the Wiki detailed info. :)
