### ISSUE TITLE
How to use fonts from CommonResources/Fonts/

### ISSUE THREAD

**Issue by Unitarian** [dotnet-architecture/eShopOnContainers#326]
I am using some of Xamarin forms implementation from this project. 
Can anyone help me with using the fonts in my cross platform project. I have seen tutorials on several sites and every one have the same procedure : 

**Android:**
- Place the font in Assets folder
- Write custom renderer for components.

**IOS**
- Place the font in Resources folder
- Add array of fonts in info.plist

However I haven't seen such a thing in this project. Is there some plugin being used to do the above steps. Or is there any other way to use the fonts?

Any kind of help would be appreciated :)

**Comment by davidbritch** [comment]
Take a look at https://developer.xamarin.com/guides/xamarin-forms/user-interface/text/fonts/#XAML to see how to use a custom font from XAML.

While the fonts are in the folders you've mentioned, they are referenced from XAML in the eShopOnContainers.Core project. For example, take a look at lines 85-90 of App.xaml. It loads the Monserrat-Regular font on each platform, and will reference it in other XAML files using the `MonserratRegular` key (e.g. line 13 of BasketItemTemplate.xaml).

**Comment by Unitarian** [comment]
Thank you for quick reply,
I got it working with the files placed in Assets/ Resources folder. But in eShopOnContainers project the files are just placed in CommonResources folder, which does not work for me.
