### ISSUE TITLE
[QUESTION] Validity of Order Items

### ISSUE THREAD

**Issue by thijscrombeen** [dotnet-architecture/eShopOnContainers#330]
Isn't it currently possible to just add anything to your basked?
Even (fake) products that do not appear in the catalog or existing products with a lower price?

Shouldn't this be checked when doing a checkout and creating the order?
What is the preferred way of solving this?
 - Should the Ordering API check with the Catalog API before creating the order?
 - Should the Basket API check with the Catalog API before adding to a basket?

**Comment by thijscrombeen** [comment]
I see that this has already been discussed in #250 so I'll close this.

**Comment by CESARDELATORRE** [comment]
Yes. We might add a few custom API Gateways to do these validations, plus certain data aggregation across multiple Microservices that the mobile Xamarin app or SPA client apps might need..
