### ISSUE TITLE
Explicitly specifying parameters for az acs create

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#331]
Let's explicitly specifying parameters for "az acs create", because we don't know the number of worker nodes, cluster size, even os type is hidden.

- We played a bit with the sample, before recognized that cluster is Linux, but our containers built for windows.
- also because our group worked on 1 subscription- it take sometime to investigate why we can't provision more that 3 clusters... issue was cores limit. 

if we explicitly specify parameters - it will be easier to investigate and will not looks like random magic.

If you are fine- I will create a pull request today. @CESARDELATORRE

**Comment by CESARDELATORRE** [comment]
Let's create the PR and I'll compare the code. I think you're right, explicit parameters in the script might be clearer.

**Comment by CESARDELATORRE** [comment]
Closing this. We have the PR, only to be merged pretty soon. :)
