### ISSUE TITLE
Login Exception

### ISSUE THREAD

**Issue by isabasan** [dotnet-architecture/eShopOnContainers#332]
Same error on SPA (5104) and MVC (5100). When I tried to login with given email and pass, I've got this error:
"InvalidOperationException: sub claim is missing"

**Comment by unaizorrilla** [comment]
Pull from Dev, fixed one hour ago!

**Comment by isabasan** [comment]
Yes. It's ok now.

**Comment by mayankgaur** [comment]
I am having same issue 
  <div class="titleerror">InvalidOperationException: sub claim is missing</div>
        <p class="location">IdentityServer4.Hosting.IdentityServerAuthenticationService.AssertRequiredClaims(ClaimsPrincipal principal) in
