### ISSUE TITLE
Can't connect to local SQL database

### ISSUE THREAD

**Issue by larrywa** [dotnet-architecture/eShopOnContainers#337]
I am using SQL Express on my local dev machine and I'm trying to run the eShopOnContainers-ServicesAndWebApps' solution. My database server instance name is .\SQLEXPRESS.

When I run the app in VS2017, I receive a lot of errors specifically where it can't find the SQL Server instance name.

I went in to the associated appsettings.json and settings.json files and changed my connection string to:
"ConnectionString": "Server=tcp:.\\SQLEXPRESS,5433;Database=Microsoft.eShopOnContainers.Services.OrderingDb;User Id=sa;Password=Pass@word;",

Maybe I am doing this syntactically incorrect but would like to understand how others got this to work on their local machine.

**Comment by CESARDELATORRE** [comment]
The appsettings.json is only used if deploying as a normal .NET app. 
When deploying as containers (in eShopOnContainers) you need to change the connection strings at the docker-compose.override.yml files. That approach is a lot more flexible so you can change it without re-building the Docker images that you'd need to do if you use the appsettings.json.

Then, if you want to access an external SQL Server, you'll need to add something like the following to your application service/container metadata in the docker-compose.override.yml file:

extra_hosts:
      - "CESARDLBOOK:10.0.75.1"

That way you'll be able to access the external SQL Server Express or a remote SQL Server.

**Comment by larrywa** [comment]
Hi,
Thanks for responding!

Last night I read some other links and then went in to the docker-compose.override.yml file and changed the connection strings in this file to:

Server=tcp:10.0.75.1\sqlexpress;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=<machinename\login>;Password=<mypassword>

I have all the ports opened that were recommended in the steps for running this in Visual Studio and I have VS 15.3.3. To connect to my db server locally, I use Windows Authentication and the server is .\SQLEXPRESS.

I made sure to change all the appsetting.json files back to the original:
Server=tcp:127.0.0.1,5433;Initial Catalog=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word

All I'm really trying to do is run the MVC portion of the app to demo for customers.

However, I'm still having the same problem.

**Comment by eiximenis** [comment]
Hi  @larrywa 
1. You can't use windows authentication from a Docker container. You need to use SQL Authentication to connect the database.
2. Ensure that your SQLExpress is able to accept connections from any other machines than localhost (basically ensure TCP/IP is enabled in SQL Express) - https://stackoverflow.com/questions/11278114/enable-remote-connections-for-sql-server-express-2012

**Comment by larrywa** [comment]
My SQLExpress is actually setup for SQL authentication and Windows authentication. I went in and logged in making sure my password is correct for SQL authentication. I then followed the instructions at the link you gave me above. I had already enabled TCP but not those other settings.

Same issue, no changes.

**Comment by CESARDELATORRE** [comment]
Right, but the connection string you have above is using Windows authentication:
Server=tcp:10.0.75.1\sqlexpress;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=<machinename\login>;Password=

You have to provide a SQL Authentication, like:
sa / password or any other user created within SQL Server, not Windows.
In a similar way we're using also for the SQL container:
User Id=sa;Password=Pass@word

But your sa password should be different, of course. 
For production it is recommended NOT to use sa but specific users with limited rights, etc.

**Comment by CESARDELATORRE** [comment]
Closing this as the way to do it was said above.

**Comment by larrywa** [comment]
According to what I understand, for SQL authentication you need to use User Id and Password as I have above. A Windows authentication connection string would have no user id or password but instead use Trusted Connection.

My connection string uses:
Server=tcp:10.0.75.1\sqlexpress;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=<machinename\login>;Password=

How is that Windows Authentication???

**Comment by CESARDELATORRE** [comment]
Have you tried with a generic user (not machinename\login) but "sa" or any generic SQL Server user?
The scenario you are looking for works when I tested it in the past (i.e. with "sa"), so I'm still not sure where can be your issue. I didn't try with a machinename\login user when using containers.

**Comment by larrywa** [comment]
Yes, I am actually using 'sa' as the User Id and then my password which I have tested in SSMS. I am thinking, maybe it is the 'Server'. I have:
Server=tcp:10.0.75.1\sqlexpress

On my machine, I connect to SQL express like '.\SQLEXRESS'.

Is the 10.0.75.1 used only to allow communication from Docker to my DB? In my Docker settings, my subnet address is 10.0.75.0.

Thanks!

**Comment by domainmurat** [comment]
Download sql server developer and try again. I think this problem must be solve.

**Comment by CESARDELATORRE** [comment]
I think I was using the 10.0.75.1 IP..
Just in case, try the real IP of your network card, like 192.168.0.1 or the IP you might have.
Can you connect to that SQL Express through TCP from another remote SQL Server Management Studio in a different machine? - That will make sure that the remote TCP access is configured right in your SQL Server Express.

**Comment by larrywa** [comment]
The first thing that is apparent is that I cannot connect to my SQL express or developer remotely. I've gone through all the links to setup TCP/ports etc. Maybe that's the root of the issue. I'll keep working on that and respond back.

**Comment by larrywa** [comment]
I was able to get remote SQL working. Essentially I receive the same sort of error but if I catch the exception in the code, 

CatalogIntegrationEventServices.cs
line 27: _eventLogService = _integrationEventLogServiceFactory(_catalogContext.Database.GetDBConnection());

I get the error:
System.ArgumentException: 'Format of the initialization string does not conform to specification starting at index 105'

Again, my connection string:
Server=tcp:192.168.1.106\SQLDEVELOPER;Database=Microsoft.eShopOnContainers.Service.CatalogDb;User Id=sa;Password=<mysapassword>

All connections are having this same problem, not just the catalog, so whatever is happening is happening uniformly.

**Comment by larrywa** [comment]
BTW, I noticed that inside of CatalogContext.cs

            var optionsBuilder =  new DbContextOptionsBuilder<CatalogContext>()
                .UseSqlServer("Server=.;Initial Catalog=Microsoft.eShopOnContainers.Services.CatalogDb;Integrated Security=true");

This shows a connection string using Windows authentication. So we have a connection string setting in the .yml, in the appsettings.json and in this file.

**Comment by CESARDELATORRE** [comment]
The appsettings.json and any hard-coded conn-string are only used if deploying/running on local VS with no Docker.
When using Docker, those values are overridden by the values in env-vars at the docker-compose.override.yml

**Comment by CESARDELATORRE** [comment]
I wonde if your issue might be related to the fact that you're using a SQL named instance (by default in SQL Express). There was that issue in .NET Core 1.0 on Linux: https://stackoverflow.com/questions/40491386/sql-server-instance-string-connection-in-linux-docker

Can you try a regular SQL Server with no named instance just to isolate the issue?
Like just: "Server=tcp:192.168.1.106" or "Server=tcp:MYWINDOWSBOX"
with NO "\SQLDEVELOPER" (SQL named instance).

**Comment by larrywa** [comment]
I just tried that, same result.
The number 105 in that error has me puzzled. If I look at the connection string in the .yml file, 105 ends up being the ';' in between 'sa' and the 'P' in Password. I even tried changing Database to Initial Catalog, and the number went to 112 and again, doing the subtraction it ends up being in the same place in the connection string it is having a problem with.
