### ISSUE TITLE
wrong asp-action in _LoginPartial.cshtml

### ISSUE THREAD

**Issue by Cuiqs76** [dotnet-architecture/eShopOnContainers#339]
wrong action logOff  `<form asp-area="" asp-controller="Account" asp-action="LogOff" method="post" id="logoutForm" class="navbar-right">
`
there is no corresponding action in the controller.

and I run the Identity.Api and logout throw a error from  return Redirect(logout?.PostLogoutRedirectUri)：

ArgumentException: Value cannot be null or empty.
Parameter name: url
Microsoft.AspNetCore.Mvc.ControllerBase.Redirect(string url)

**Comment by CESARDELATORRE** [comment]
What branch code are you using?
What environment?
I just tested the latest version in my machine and the login page in the MVC app is working properly for me.
Can you provide further context?
Thanks,

**Comment by Cuiqs76** [comment]
Dev

**Comment by Cuiqs76** [comment]
I test it in windows 10 with localdb.   click login->logout->login.  the login form no represent again.

**Comment by CESARDELATORRE** [comment]
That is because the token is still valid and we login automatically with the older token, but I think you are right, if we logout, it should force it and fully logout... I'm creating a BUG with this issue.

**Comment by araselahi** [comment]
As mentioned in [IdentityServer4 Sign-out Document](http://docs.identityserver.io/en/release/topics/signout.html):
you can use the convenience extension method that is provided by IdentityServer: 
await HttpContext.SignOutAsync();
but it seems that it can not remove the mentioned cookie. Cookie name: .AspNetCore.Identity.Application

**Comment by araselahi** [comment]
Does anybody know why?

**Comment by BrunoLopes** [comment]
Is this problem resolved?
Because I can make it works! And I think that the turn around solution is not a real option...

**Comment by TarasovN** [comment]
Asp.Net Identity + Identity server 4 uses a little bit different cookies. Try to use
`await HttpContext.SignOutAsync("Identity.Application");`
