### ISSUE TITLE
Tests referencing mock data

### ISSUE THREAD

**Issue by leroygumede** [dotnet-architecture/eShopOnContainers#340]
@christian147 after reviewing Unit tests, I realised that all the tests are referencing mock data? why
is it not supposed to reference the actual ViewModel?

**Comment by christian147** [comment]
Hello @leroygumede, 
I imagine you are referencing to mobile application, aren't you?
In this case, we are testing the viewModel without give importance to origin data. This is why we use the mock data services for do this.

I hope I answered your question! ;)

**Comment by leroygumede** [comment]
:) yes I am referencing the mobile app  @christian147 makes sense
