### ISSUE TITLE
[BUG] Unhandled exception 401 (Unauthorized) after a while when auth token expires

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#346]
This is a known issue we have in the app that needs to be fixed, eventually.
After a while, if you leave the app in the browser opended, let's say for a couple of hours, then you try to go to the basket or any protected area in the app and you get this Unhandled exception 401 (Unauthorized):

![image](https://user-images.githubusercontent.com/1712635/30777574-3b4f119a-a072-11e7-9c5f-5e92f7983ae7.png)

**Comment by mvelosop** [comment]
Closing this issue now as it seems to solved now. Set a cookie expiry time of one minute for testing, and now it always goes to the login page.
