### ISSUE TITLE
Drop already merged branches

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#352]
Hello,
it's not an issue in a project, but we have multiple branches already merged to a dev branch, but still exists... To avoid misunderstanding I think we can safely drop 6 branches with zero commits ahead:
EFCliAndSeeders 
IdentityAPI20 
netcore2 
loadtest
EntityTypeConfigurationOnEFCore2 
load-testing 

https://github.com/dotnet-architecture/eShopOnContainers/branches/all

**Comment by eiximenis** [comment]
Deleted those branches and some other old.

Thx!
