### ISSUE TITLE
GracePeriod query with hardcoded database name

### ISSUE THREAD

**Issue by aodpi** [dotnet-architecture/eShopOnContainers#358]
https://github.com/dotnet-architecture/eShopOnContainers/blob/e8c8678082d39533c38cc53ebf8c23f263df7762/src/Services/Ordering/Ordering.API/Infrastructure/HostedServices/GracePeriodManagerService.cs#L74

What if the database is configured with different name, Souldn't the context be used instead to query the Id

**Comment by unaizorrilla** [comment]
Yeap .. I try to solve this issue a son as posible.

Thanks
Unai

**Comment by SychevIgor** [comment]
@CESARDELATORRE  it's commited 

Date:		2 days ago (2017-10-06 11:09:16 AM)
Commit hash:	ec5aee5187fe6d58e421de915c868ee9300f78c5
Children:	eb38172abf#gitext://gotocommit/eb38172abf7661f9435d0e6834cacb6cbf124bb1
Parent(s):	3c2efbf678#gitext://gotocommit/3c2efbf6783d396d89f37190639cc8b55eb40fc1

**Comment by CESARDELATORRE** [comment]
Closing this.
