### ISSUE TITLE
[Question] docker compose 3.0

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#361]
Do we have some specific reason to use docker compose version 2.1?
Current stable is 3.0. I don't know benefits of 3.0, but it least this version will be the latest.

**Comment by CESARDELATORRE** [comment]
You're right, and VS 2017 15.3.5 is also using now docker-compose 3. So, I just went ahead and updated all of our docker-compose files to 3 and tested it.
Commit:  https://github.com/dotnet-architecture/eShopOnContainers/commit/cc4325cee5592dc18f03acfd7e3d8c3d0c1c5afe
