### ISSUE TITLE
[Question] Why retry policy implemented using constants instead of configuration?

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#362]
Why retry policy implemented using constants instead of configuration?
For example in cold be 5, could be 6 depend from async or wait/circuit DefaultRabbitMQPersistentConnection.cs, EventBusRabbitMQ.cs, ResilientHttpClientFactory.cs

    .WaitAndRetryAsync(
                    // number of retries
                    6,

 .CircuitBreakerAsync(
                   // number of exceptions before breaking circuit
                   5,

  .WaitAndRetry(5, retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)), (ex, time) =>
                {

**Comment by CESARDELATORRE** [comment]
Well, I agree, we could improve this point. Once the app is deployed and working properly, usually you don't need to change those parameters, but I agree that these numbers could come from env-vars at configuration. Feel free to create a PR with it or we might improve that, eventually.
