### ISSUE TITLE
[Question] SQL2017 container persistancy 

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#363]
On Ignite was session about sql server 2017 on containers. one of speakers told, that there is not always needs to use physical/virtual machines to store persistent data, especially starting from 2017 sql.
Will we cover sql server 2017 persistence/always on groups in this ref architecture?

**Comment by CESARDELATORRE** [comment]
We're currently using SQL Server 2017 on a container, for DEV/TEST environments. 
Then, we recommend to move to Azure SQL Database or Azure SQL Database Managed Instance when moving to production in Azure, or a SQL Server cluster on-premises if going that path.
Using SQL Server 2017 on containers with high availability (i.e. deploying into Kubernetes but having persistence-always), although it can be done, that is still not mainstream neither the recommended way for production, yet. And in any case, that point is more an infrastructure/operations work, not a development task which is where we are focusing more for this project.
Bottom-line, in the future we might do it, but it is not currently a priority for this project as the current recommendation for production SQL is more about Azure SQL DB or regular SQL clusters.

**Comment by SychevIgor** [comment]
@CESARDELATORRE thank you!
