### ISSUE TITLE
[Question] Microservices Monitoring/Logging implementation.

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#364]
.net core give us a lot of internal logs if we want it. In our app we have 10+ containers and each will generate a lot of logs, but there is only one way to retrieve logs as of now -connect to each container directly.
It's not the best way to deal logs and we have nothing about in books attached to a repo.
 Maybe we can add Application Insights or at least store logs in DB?... but we definitely need something.

**Comment by CESARDELATORRE** [comment]
I'm glad you mention that. We're actually working on that. We're working on an implementation using Event Flow in this branch:
https://github.com/dotnet-architecture/eShopOnContainers/tree/features/eventflow-integration

Event Flow can have multiple inputs and outputs, including AppsInsights as output.
Another choice would be to simple use AppsInsights, but Event Flow seems more flexible.

In the upcoming weeks I'll update the Microservices book to .NET Core 2.0, so, I'll take advantage of that by updating it to further features, like centralized Logging and other additional points.

**Comment by CESARDELATORRE** [comment]
After evaluating EventFlow vs. plain AppsInsights we see much richer AppsInsights for a microservice based application. The integration between EventFlow and AppsInsights is pretty basic, just about your own traces, but AppsInsights offers much richer information. The PROS for EventFlow is that you can have multiple external inputs (like Windows EventLog, traces, and quite a few others) and several outputs, AppsInsights included. But focusing specifically on a microservice application, correlation between multiple instances, etc. we see AppsInsights richer, so we're going to use AppsInsights directly.

**Comment by CESARDELATORRE** [comment]
Closing this. We're actually using AppsInsights in DEV branch, now.
