### ISSUE TITLE
"Invalid object name 'IntegrationEventLog'." raised by SQL Server during the catalog api post operation

### ISSUE THREAD

**Issue by benlam62** [dotnet-architecture/eShopOnContainers#371]
When I try to change an item by submitting a POST operation on catalog api, the "Invalid object name 'IntegrationEventLog'." raised by SQL Server. Any comment to fix it?

**CURL**
curl -X PUT --header 'Content-Type: application/json-patch+json' --header 'Accept: application/json' -d ' { \ 
       "id": 2, \ 
       "name": ".NET Black %26 White Mug", \ 
       "description": ".NET Black %26 White Mug", \ 
       "price": 28.5, \ 
       "pictureFileName": "2.png", \ 
       "pictureUri": "http://localhost:5101/api/v1/catalog/items/2/pic/", \ 
       "catalogTypeId": 1, \ 
       "catalogType": null, \ 
       "catalogBrandId": 2, \ 
       "catalogBrand": null, \ 
       "availableStock": 100, \ 
       "restockThreshold": 0, \ 
       "maxStockThreshold": 0, \ 
       "onReorder": false \ 
     }' 'http://localhost:5101/api/v1/Catalog/items'

**Request URL**
http://localhost:5101/api/v1/Catalog/items

**Response Details**
{
  "messages": [
    "An error ocurr.Try it again."
  ],
  "developerMeesage": {
    "ClassName": "Microsoft.EntityFrameworkCore.DbUpdateException",
    "Message": "An error occurred while updating the entries. See the inner exception for details.",
    "Data": null,
    "InnerException": {
      "ClassName": "System.Data.SqlClient.SqlException",
      "Message": "Invalid object name 'IntegrationEventLog'.",
      "Data": {
        "HelpLink.ProdName": "Microsoft SQL Server",
        "HelpLink.ProdVer": "14.00.1000",
        "HelpLink.EvtSrc": "MSSQLServer",
        "HelpLink.EvtID": "208",
        "HelpLink.BaseHelpUrl": "http://go.microsoft.com/fwlink",
        "HelpLink.LinkId": "20476"
      },
      "InnerException": null,
      "HelpURL": null,
      "StackTraceString": "   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__108_0(Task`1 result)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\n   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\n   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()",
      "RemoteStackTraceString": null,
      "RemoteStackIndex": 0,
      "ExceptionMethod": null,
      "HResult": -2146232060,
      "Source": "Core .Net SqlClient Data Provider",
      "WatsonBuckets": null
    },
    "HelpURL": null,
    "StackTraceString": "   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__32.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__61.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__59.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\n   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__48.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Catalog.API.IntegrationEvents.CatalogIntegrationEventService.<>c__DisplayClass6_0.<<SaveEventAndCatalogContextChangesAsync>b__0>d.MoveNext() in C:\\Users\\benlam\\Source\\Repos\\eShopOnContainers\\src\\Services\\Catalog\\Catalog.API\\IntegrationEvents\\CatalogIntegrationEventService.cs:line 45\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.eShopOnContainers.BuildingBlocks.IntegrationEventLogEF.Utilities.ResilientTransaction.<>c__DisplayClass3_0.<<ExecuteAsync>b__0>d.MoveNext() in C:\\Users\\benlam\\Source\\Repos\\eShopOnContainers\\src\\BuildingBlocks\\EventBus\\IntegrationEventLogEF\\Utilities\\ResilientTransaction.cs:line 32\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c.<<ExecuteAsync>b__3_0>d.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<ExecuteImplementationAsync>d__31`2.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<ExecuteImplementationAsync>d__31`2.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.eShopOnContainers.BuildingBlocks.IntegrationEventLogEF.Utilities.ResilientTransaction.<ExecuteAsync>d__3.MoveNext() in C:\\Users\\benlam\\Source\\Repos\\eShopOnContainers\\src\\BuildingBlocks\\EventBus\\IntegrationEventLogEF\\Utilities\\ResilientTransaction.cs:line 27\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Catalog.API.IntegrationEvents.CatalogIntegrationEventService.<SaveEventAndCatalogContextChangesAsync>d__6.MoveNext() in C:\\Users\\benlam\\Source\\Repos\\eShopOnContainers\\src\\Services\\Catalog\\Catalog.API\\IntegrationEvents\\CatalogIntegrationEventService.cs:line 41\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.eShopOnContainers.Services.Catalog.API.Controllers.CatalogController.<UpdateProduct>d__10.MoveNext() in C:\\Users\\benlam\\Source\\Repos\\eShopOnContainers\\src\\Services\\Catalog\\Catalog.API\\Controllers\\CatalogController.cs:line 182\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2146233088,
    "Source": "Microsoft.EntityFrameworkCore.Relational",
    "WatsonBuckets": null
  }
}

**Comment by CESARDELATORRE** [comment]
Thanks for catching this up. It was a regression bug from an update we made yesterday.
Fixed now in this commit: https://github.com/dotnet-architecture/eShopOnContainers/commit/121a92c557e23638623b4c557428ba50d748eeee

Please, pull the new code and confirm if it is working for you now, ok?
Thanks,

**Comment by benlam62** [comment]
Yes, it works now.

Thx
Ben
