### ISSUE TITLE
BUG in VS 2017 15.4 by not honoring your image TAGs in docker-compose files 

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#372]
# Bug explanation

This is an issue in VS2017 Docker Tools in 15.4. In Debug, VS generates the /obj/docker-compose.vs.debug.g.yml file. This file is also used (alongside the docker-compose.yml) when VS invokes compose. 
In VS 15.3 and previous, the docker-compose.vs.debug.g.yml had always the tag :dev in the images, no matter what the tag were used in docker-compose.yml. This is the reason why always the images generated by VS had the dev tag.
In 15.4 the behavior seems to be different: In 15.4 the value :dev is appended to the image name always in the docker-compose.vs.debug.g.yml generated. If the image names in docker-compose.yml has no tags, this result having the :dev tag and the behavior is the same of 15.3. 
But, and this is the bug, if docker-compose.yml has a tag in the image’s name, the result is that the docker-compose.vs.debug.g.yml ends having something like: image-name:tag1:dev (where tag1 is my tag that is in docker-compose.yml).
 
# Repro

Just create any hello world in VS 2017 15.4 like a ASP.NET Core MVC app with Docker enabled, go to the docker-compose.yml file and add a tag to the image name, like adding “:latest” or “:1.1.0” or “:mytag”.
Try to build/run with F5 and it will fail.
Or build/run eShopOnContainers.
 
# eShopOnContainers behavior

In eShopOnContainers we’re using a by-default environment variable set at the .env file to set the tag. So we add something like ${TAG:-latest} to any image’s name at the docker-compose.yml file.
This allows us to build/create images using an specified environment or version tag (by just setting the TAG environment variable). I. e. this is used in Kubernetes deployment script: images are built against specific tag and this tag is deployed in the cluster. That allows to deploy specific versions in the cluster.
 
VS 15.4 seems to evaluate environment variables, but then it appends the DEV tag. 
In my case I ended up with something like webstatus:master:dev as the image’s name, which Docker cannot understand. 
The master is the result of evaluating ${TAG:-master} (as I don't have the TAG environment variable declared.

# CONCLUSION

This is a bug of the VS 2017 15.4 Docker Tools and has already been fixed in VS 2017 15.5 Preview 1.
The updated tools in VS 15.5 Preview will replace, not append, the :dev tag. This is important as the :dev image doesn’t actually contain the content as we volume mount the content in for VS scenarios. 

# WORKAROUNDS

1. Do not update to VS 2017 15.4
2. Update to VS 2017 15.4 but remove the tags from your docker-compose files
3. Update to VS 2017 15.5 Preview 1, available here: https://www.visualstudio.com/vs/preview/ 

Additional feedback about this issue would be appreciated. :)

**Comment by SychevIgor** [comment]
@CESARDELATORRE looks like we can close it, because latest vs versions is 15.5.1 works fine.

**Comment by CESARDELATORRE** [comment]
Sure. This is fixed since VS2017 15.5 RTM release.
