### ISSUE TITLE
WebStatus returns 404 for js/site.js that don't exists

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#377]
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 2.3252ms 404 
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5107/js/site.js  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 2.3252ms 404

**Comment by CESARDELATORRE** [comment]
Can you provide the specific repro steps for that at the WebStatus app?

**Comment by SychevIgor** [comment]
I will provide PR later if you need it.

Just run WebStatus app in container and look on logs and you will find it when you will make a request.
it is because in a  /src/Web/WebStatus/Views/Shared/_Layout.cshtml file on line 56 we have <script src="~/js/site.js" asp-append-version="true"></script>
that don't exists in a project.
