### ISSUE TITLE
[Question] OMS as Container Monitoring

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#384]
In a book we have ultra-limited information about oms.
" These can include simple standard output for a development environment or cloud systems like Application Insights, OMS (for on-premises applications), and Azure Diagnostics. "
But in August was released OMS solution for Containers with nice visualization
https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-containers
and really nice monitoring option for K8 specifically
https://docs.microsoft.com/en-us/azure/container-service/kubernetes/container-service-kubernetes-oms

Maybe it will be cool if we will include in a next version of the book some info about oms+containers and in our code container with oms monitoring for k8?

What do you think @CESARDELATORRE

**Comment by CESARDELATORRE** [comment]
Agree. I'm already talking about that in the "Modernizing Existing .NET apps with Azure and Windows Containers" ebook: https://aka.ms/liftandshiftwithcontainersebook - Look for "Monitor your Docker infrastructure with Log Analytics and its Container Monitoring solution".
It is not just part of OMS, also part of Azure, as I explain in there.

So, I'm currently starting to update the Microservices eBook to .NET Core 2.0 "wave". I'll include that, as well.
Please, take a look to the info I have in the other eBook in case you think we should update it or extend it for the Microservices eBook. :)

Closing this issue as I'm already taking this into account. Re-open if you have further feedback, ok?
Thanks! :)

**Comment by SychevIgor** [comment]
Sure... Issues are only option to ask question about roadmap publicly. 
Thank you for an answer.!
