### ISSUE TITLE
DataProtection.csproj StackExchange.Redis.StrongName?

### ISSUE THREAD

**Issue by haniamr** [dotnet-architecture/eShopOnContainers#385]
Is there a reason that it was changed from a nuget package to a hint path? 
 ```
 <ItemGroup>
    <Reference Include="StackExchange.Redis.StrongName">
      <HintPath>..\..\..\..\..\..\..\..\..\Program Files\dotnet\sdk\NuGetFallbackFolder\stackexchange.redis.strongname\1.2.4\lib\netstandard1.5\StackExchange.Redis.StrongName.dll</HintPath>
    </Reference>
  </ItemGroup>
```

Since that path isn't valid on my machine, It's currently not building unless I revert it back to:
`<PackageReference Include="StackExchange.Redis" Version="1.2.4" />`

**Comment by CESARDELATORRE** [comment]
Thanks for the heads-up. That's a regression bug. I just fixed and pushed the commit into the DEV branch:
https://github.com/dotnet-architecture/eShopOnContainers/commit/b1de7f8b7c13cd41a23cae1d3b945b52c5c09606 
Please, confirm it is working for you now.
Thanks.

**Comment by haniamr** [comment]
Thanks, working fine now!
