### ISSUE TITLE
[Question] Bootstrap 4 beta and ng-bootstrap beta

### ISSUE THREAD

**Issue by isaranghi** [dotnet-architecture/eShopOnContainers#388]
Hello,

Any plans to move SPA web to Bootstrap 4 beta and ng-bootstrap beta anytime soon?

**Comment by CESARDELATORRE** [comment]
@isaranghi - Thanks for the suggestion! :)
Not in our roadmap to move to betas in regards the SPA. We'll try to move to next major versions when they are final/GA/RTM.
PRs are welcome, but we won't merge to dev and master branches until those versions are final.
Also, we're going to refactor the apps in the upcoming weeks by introducing API Gateways which will simplify the API used from client apps, including the Xamarin app and the SPA app.
So probably, moving to newer versions will come after that.

Can you provide strong reasons why you think we should move to bootstrap 4 BETA and ng-bootstrap BETA even when it is not RTM/release, yet?

Thanks,

**Comment by isaranghi** [comment]
@CESARDELATORRE - Thanks for your reply. No strong reason but SPA is currently using alpha version of both boothstrap and ng-bootstrap. Alpha version has some functionality that has been obsolete. According to bootstrap documentation, they are not going to do any major changes in the final version. Just thought it would be good to be on Bootstrap 4 beta right now so when they release the final version, it won't break anything in SPA.

Thanks.

**Comment by CESARDELATORRE** [comment]
Good, then I think we can consider to migrate to the next versions while refactoring the SPA app for the API Gateways. Thanks for the feedback! :)

**Comment by SychevIgor** [comment]
It's something that I didn't change in https://github.com/dotnet-architecture/eShopOnContainers/pull/218
I don't remember wh.

**Comment by mvelosop** [comment]
Closing this issue as it's outdated now, the was updated to Bootstrap 4.1.3 a few weeks ago.
