### ISSUE TITLE
Validate Commands with the Decorator pattern in MediatR

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#39]
This approach could be used as an additional decorator plus improving our input Validations:

Validating Commands with the Decorator Pattern
http://codeopinion.com/validating-commands/ 

Use:
FluentValidation
https://github.com/JeremySkinner/FluentValidation

See also:
https://lostechies.com/jimmybogard/2014/09/09/tackling-cross-cutting-concerns-with-a-mediator-pipeline/

**Comment by FDUdannychen** [comment]
By the way I think `MediatR` can be upgraded to v3?`[CreateOrderCommand]`(https://github.com/dotnet/eShopOnContainers/blob/master/src/Services/Ordering/Ordering.API/Application/Commands/CreateOrderCommand.cs) implements `IAsyncRequest<bool>` but IMO a command shouldn't know how it will be handled (in an async handler). The latest version of MediatR integrates `IAsyncRequest` & `IRequest` to `IRequest`.
