### ISSUE TITLE
[Feedback] Consider migrating the databases on integration tests

### ISSUE THREAD

**Issue by ASADeveloper** [dotnet-architecture/eShopOnContainers#402]
Hi,

I think there is another issue with the current EF Migration.
When I run the integration tests, the Ordering.API.Program.Main does not execute. As a result the migrations don't apply and the database doesn't get updated with the latest changes.

That means, each individual micro-service (API) should have been run, before running the tests.
I'm not lazy and could do that manually after each 'add migration', but it's easy to forget and more importantly the tests might not really test the latest migrations!
And having ConnectionString inside the settings.json in integration tests does not have any value because we always have to use the same database as the API itself. In my opinion it is not a good thing.

I would like to run my integration tests on a different database.

I suggest that integration tests, migrate the databases as well. 

Regards,
Arash

**Comment by ramonTC** [comment]
Hi,

The migrations were applied in Integration tests previously.
Recently these migrations have been moved from startup to program file and that caused this issue.
We have fixed it and now we apply these migrations on the tests.

Thx!
