### ISSUE TITLE
[Feedback] Consider returning the correct http statuscode

### ISSUE THREAD

**Issue by ASADeveloper** [dotnet-architecture/eShopOnContainers#403]
Hi,

Based on these two integration tests:
Cancel_order_no_order_created_response_500_status_code
Ship_order_no_order_created_response_500_status_code

I think the return codes are fundamentally wrong and should be BadRequest (400) instead. In fact it is the case with all current API's. They return 'server error' on bad request of the client!

4xx codes are used to tell the client that a fault has taken place on **their** side. They should not retransmit the same request again, but fix the error first.

5xx codes tell the client something happened on the server and their request by itself was perfectly valid. The client can continue and try again with the request without modification.

For example if the API is trying to save a record to a database and this fails because there is an error with the database, for instance, it's not reachable, or a constraint fails, we should use a 5xx code (preferably 500 - Internal server error).

Regards,
Arash

**Comment by ramonTC** [comment]
Thanks for your feedback.
It is already fixed in Dev.
