### ISSUE TITLE
[Question] Multiple subscriber for Events

### ISSUE THREAD

**Issue by isaranghi** [dotnet-architecture/eShopOnContainers#405]
Hello,

I just wanted to ask if the EventBus sample in eShopOnContainers project support multiple subscribers(2 different microservices) for an event published by a MicroService?

Thanks.

**Comment by CESARDELATORRE** [comment]
Of course. As explained in the related documentation/guide. See the ebook and search for Integration events.
Events are meant to be consumed/subscribed by multiple subscribers.
If it has to be processed just one time subscriber, it would be a Command. But we don't use distributed commands.
We use:
- Distributed Integration events (based on the Event Bus)
- Domain Events (based on MediatR, in memory, within a single Microservice)
- in-memory Commands (based on MediatR)

Cesar.

**Comment by CESARDELATORRE** [comment]
Of course. As explained in the related documentation/guide. See the ebook and search for Integration events.
Events are meant to be consumed/subscribed by multiple subscribers.
If it has to be processed just one time subscriber, it would be a Command. But we don't use distributed commands.
We use:
- Distributed Integration events (based on the Event Bus)
- Domain Events (based on MediatR, in memory, within a single Microservice)
- in-memory Commands (based on MediatR)

Cesar.
