### ISSUE TITLE
Security issue with versiones references in HandleBars and Angular 4

### ISSUE THREAD

**Issue by ramonTC** [dotnet-architecture/eShopOnContainers#409]
angular/cli latest version is using the dependency "directory-encoder" pkg which uses an old version of "HandleBars" 1.3.0. This version of "Handlebars" has a vulnerability and it should be updated to >4.0.0

Once Angular updates angular/cli and its dependency tree and allows to use a higher version of "Handlebars" pkg, this issue should be fixed on WebSPA app

This is related to this warning you might see at the GitHub repo:
![image](https://user-images.githubusercontent.com/1712635/33032962-aee42e6e-cdd7-11e7-8c32-00f2ab96dcb1.png)

**Comment by mvelosop** [comment]
Closing this issue as it's outdated, current Angular version is 6.1.4
