### ISSUE TITLE
Event definition duplication

### ISSUE THREAD

**Issue by Mardoxx** [dotnet-architecture/eShopOnContainers#411]
e.g. OrderStatusChangedToPaidIntegrationEvent [1](https://github.com/dotnet-architecture/eShopOnContainers/blob/21484d6385a49e3072a502cd76bf2c50b048e439/src/Services/Catalog/Catalog.API/IntegrationEvents/Events/OrderStatusChangedToPaidIntegrationEvent.cs), [2](https://github.com/dotnet-architecture/eShopOnContainers/blob/21484d6385a49e3072a502cd76bf2c50b048e439/src/Services/Catalog/Catalog.API/IntegrationEvents/Events/OrderStatusChangedToPaidIntegrationEvent.cs)

How come these aren't in some shared place e.g. `...Services.Orders.API.Events`?

**Comment by CESARDELATORRE** [comment]
Not sure what you mean. Where would you put the Integration-events class types?
Microservices should be autonomous, so we don't want to use a shared library across microservices.
Not sure what shared point you mean.

**Comment by Mardoxx** [comment]
I was thinking maybe a shared library. They still would be standalone just
sharing a e.g. nuget package... Just seems weird having these two identical
classes - what if you change the defn of the event in one service?

**Comment by CESARDELATORRE** [comment]
We believe that is not a good practice. Microservices should be autonomous and not depend on shared libraries except for serious building blocks.
This shared library wouldn't be a building block but a domain-type library.
That is almost like if you share a domain entity library across microservices.
If you change the event in one microservice will break the consumers in the same way than you break consumers if you change a REST API. But in that case, you are not sharing types with Http consumers, neither.
So, changing events should be done carefully, with versions, in the same way than you change REST or HTTP services.
You might also have similar types when using DTOs or ViewModels in services and HTTP consumer apps. I think this is a very similar case, but using integration-events.

So, initially, we don't want to share a class library for the events across a microservice application.
It is arguable, but the reasons are what I just said.
We're open to discuss this topic further, though. We could find additional improvements, in any case. :)

**Comment by Mardoxx** [comment]
Ah right okay!

Will have a think about this. Thanks

On 20 Nov 2017 6:10 pm, "Cesar De la Torre" <notifications@github.com>
wrote:

We believe that is not a good practice. Microservices should be autonomous
and not depend on shared libraries except for serious building blocks.
This shared library wouldn't be a building block but a domain-type library.
That is almost like if you share a domain entity library across
microservices.
If you change the event in one microservice will break the consumers in the
same way than you break consumers if you change a REST API. But in that
case, you are not sharing types with Http consumers, neither.
So, changing events should be done carefully, with versions, in the same
way than you change REST or HTTP services.
You might also have similar types when using DTOs or ViewModels in services
and HTTP consumer apps. I think this is a very similar case, but using
integration-events.

So, initially, we don't want to share a class library for the events across
a microservice application.
It is arguable, but the reasons are what I just said.
We're open to discuss this topic further, though. We could find additional
improvements, in any case. :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dotnet-architecture/eShopOnContainers/issues/411#issuecomment-345780004>,
or mute the thread

**Comment by CESARDELATORRE** [comment]
Closing for now until further feedback. 
In any case, it is a great question. 👍

**Comment by Mardoxx** [comment]
What I was thinking was more along the lines of a library per service for
events related to the service (not a shared one for all events accross the
enterprise). Could also namespace events for breaking changes between
versions.

Very new to these sorts of things but that is one way I approached it in
service fabric -- but using their strong typed service remoing libs. May
rethink this :)

**Comment by Mardoxx** [comment]
Is there an irc or gitter or slack etc channel you guys use?

**Comment by CESARDELATORRE** [comment]
We have a Slack channel for the project, but due to many other projects we're working on, we cannot focus on Slack, so we end up using email..
You can send me emails to **cesardl** at microsoft.com
