### ISSUE TITLE
[Feature] Consider supporting other DataProtection providers such as AspNetCore.DataProtection.ServiceFabric

### ISSUE THREAD

**Issue by MedAnd** [dotnet-architecture/eShopOnContainers#413]
Consider supporting other DataProtection providers, for example I would like to replace the Redis provider  with a pure Service Fabric provider such as [AspNetCore.DataProtection.ServiceFabric](https://github.com/MedAnd/AspNetCore.DataProtection.ServiceFabric) :relaxed:

**Comment by mvelosop** [comment]
Closing this issue now since there's no plan to add SF-related features at this time, but feel free to comment, will reopen if needed.
