### ISSUE TITLE
[Question] What about AKS instead of ACS

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#414]
What do you think about AKS instead of ACS? (will you agree on PR?)

Looks like AKS is a recommended way to host k8 in Azure. 
You are viewing documentation for the old version of the Azure Container Service.

![image](https://user-images.githubusercontent.com/578954/33078599-38b6812a-cee4-11e7-882d-1c280fbe417a.png)

**Comment by SychevIgor** [comment]
@CESARDELATORRE

**Comment by CESARDELATORRE** [comment]
Sure. It is in the radar and tests, but it is still in PREVIEW, so I'd prefer to wait a bit for it.
Also, AKS still doesn't support Windows Containers...
