### ISSUE TITLE
Misses Catalog.WebForms.sln specified in a book

### ISSUE THREAD

**Issue by snesnov** [dotnet-architecture/eShopOnContainers#415]
No Catalog.WebForms.sln file. It should have been here:

eShopOnContainers-master\src\Web\Catalog.WebForms\Catalog.WebForms

It can not be found in folders either nor in other branches.

**Comment by CESARDELATORRE** [comment]
That WebForma app is kind of deprecated. We created a more complete WebForms app in a different repo:
Here: https://github.com/dotnet-architecture/eShopModernizing
With a whole guidance on modernizing existing .NET Framework apps (monolithic, etc.)

**Comment by snesnov** [comment]
Many thanks for a quick and valuable answer. Have a nice day,

Regards,
Stanislav

Best regards,

*Stanislav Nesnov,*
+38 093 834 12 72 I stanislavnesnov@gmail.com


On Tue, Nov 21, 2017 at 7:58 PM, Cesar De la Torre <notifications@github.com
