### ISSUE TITLE
Implement Global Exception Handling using the ASP.NET Core Middleware

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#42]
Implement Global Exception Handling using the Custom ASP.NET Core Middleware that will be used from all the eShopOncontainers microservices.
See info like :
“Global Exception Handling in ASP.NET Core Web API”:
http://www.talkingdotnet.com/global-exception-handling-in-aspnet-core-webapi/ 

http://stackoverflow.com/questions/38630076/asp-net-core-web-api-exception-handling

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware

**Comment by yogpotdar** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.1
