### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by miudothedog** [dotnet-architecture/eShopOnContainers#428]
In MacOS High Sierra, I got this error when I click on Login
IOException: IDX10804: Unable to retrieve document from: 'http://docker.for.mac.localhost:5105/.well-known/openid-configuration'.
Microsoft.IdentityModel.Protocols.HttpDocumentRetriever+<GetDocumentAsync>d__8.MoveNext()

No matter if I use Chrome, or other browser.
To try to fix this error, I've read: https://github.com/dotnet-architecture/eShopOnContainers/wiki/04.-Setting-eShopOnContainer-solution-up-in-a-Mac,-VS-for-Mac-or-with-CLI-environment--(dotnet-CLI,-Docker-CLI-and-VS-Code)

I also tried:
192.168.65.1,
docker.for.mac.local
localhost

And nothing makes it happen.

Environment:
Docker Version 17.09.0-ce-mac35 (19611), stable
Microsoft Visual Studio for Mac 7.3 (Build 799)
MacOs High Sierra 10.13.2 (17C88) 

Exception:

> An unhandled exception occurred while processing the request.
> CurlException: Couldn't resolve host name
> System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
> 
> HttpRequestException: An error occurred while sending the request.
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 
> IOException: IDX10804: Unable to retrieve document from: 'http://docker.for.mac.localhost:5105/.well-known/openid-configuration'.
> Microsoft.IdentityModel.Protocols.HttpDocumentRetriever+<GetDocumentAsync>d__8.MoveNext()
> 
> InvalidOperationException: IDX10803: Unable to obtain configuration from: 'http://docker.for.mac.localhost:5105/.well-known/openid-configuration'.
> Microsoft.IdentityModel.Protocols.ConfigurationManager+<GetConfigurationAsync>d__24.MoveNext()

👎

**Comment by CESARDELATORRE** [comment]
Did you update the .env file with your local up, like:
  ESHOP_EXTERNAL_DNS_NAME_OR_IP=192.168.0.25

As mentioned in the wiki walkthrough instructions?

**Comment by miudothedog** [comment]
Hi,
The error was solved when I've checked the project folder permissions.

Then, after grant admin rights, I followed the steps:
https://github.com/dotnet-architecture/eShopOnContainers/wiki/04.-Setting-eShopOnContainer-solution-up-in-a-Mac,-VS-for-Mac-or-with-CLI-environment--(dotnet-CLI,-Docker-CLI-and-VS-Code)

Thank you.
