### ISSUE TITLE
[Feature Request] SPA update to Angular6

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#437]
I think we can update angular from 4 we are using now to 5.1 during next release cycle https://github.com/angular/angular/releases 
What do you think about it? @CESARDELATORRE @ramonTC

**Comment by thiagojsvix** [comment]
OK

Em 13/12/2017 08:12, "SychevIgor" <notifications@github.com> escreveu:

**Comment by ramonTC** [comment]
It is fine.
I've checked out the breaking changes which introduce ng v5 and it shouldn't be a big deal

**Comment by SychevIgor** [comment]
https://github.com/dotnet-architecture/eShopOnContainers/pull/441
