### ISSUE TITLE
[Question] MongoDB retryable writessupport in Marketing.API for UpdateLocationAsync

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#439]
Recently was released mongodriver (C#) 2.5 with support of retryable write https://github.com/mongodb/specifications/blob/master/source/retryable-writes/retryable-writes.rst

Since we already using httpclient with retry, maybe we can use also this feature? Looks like from our side- we can simple update connection string to mondo(of course we need 2.5v drier) and everything will be done.

What do you think about ?
@CESARDELATORRE  @ramonTC 

commit https://github.com/mongodb/mongo-csharp-driver/commit/fb5521d6ca43f467897bd674d7dcecade405775a
setting in a connection string
 "retryWrites=true"

**Comment by CESARDELATORRE** [comment]
We can upgrade if it is well tested in eShopOnContainers.
Did you test the marketing campaign with this new driver accessing to the MongoDB database?

**Comment by SychevIgor** [comment]
@CESARDELATORRE just with a new driver- marketing api worked as with old. I didn't find any difference. But I didn't test it with a new connection string of course.

**Comment by CESARDELATORRE** [comment]
I think that should be good to go, although it would be good to test it with “retries” in the connection string, too, before merging.

Thanks for updating and testing this! :)
