### ISSUE TITLE
[Question] How to make Autofac resolve dependencies from the scope started in EventBus?

### ISSUE THREAD

**Issue by dmitry606** [dotnet-architecture/eShopOnContainers#442]
We started our project based on eShopOnContainers as a template some time ago. We use EventBus (almost unmodified) and MediatR. The problem we have now is that, as I understand, integration event handlers here are supposed to work as HTTP Requests do in ASP.NET - they start an Autofac scope and all the code down the stack resolve dependencies from that scope. After the request is finished, the scope is disposed. But in our case it does not happen. 

The scope is started in EventBusServiceBus.ProcessEvent():
https://github.com/dotnet-architecture/eShopOnContainers/blob/4178fbff0e006c88dd16d1ee717f77755e65286e/src/BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.cs#L151

But as I understand all the code down the stack from the handler does not know about that scope. When we use MediatR commands and events and inject dependencies in their constructors, they are resolved from the root. The only way to resolve from the EventBus scope is not to use ctor parameter injection and inject only ILifetimeScope, which will be the EventBus scope, and then get our dependencies from it manually, which seems ugly.

So now we are thinking about some fixes for that, like using ThreadStatic to bind the EventBus scope to the thread where the event handling started. It seems quite sophisticated, so I am wondering - are we doing something wrong? Is there a simple way to make DI behave like ASP.NET HTTP requests?

**Comment by CESARDELATORRE** [comment]
I'd need to research more on your specific problem, but I think that it depends on the lifetime object you are using when registering the classes in Autofac IoD container. A few questions so it get's clear for me:
- What lifetime are you using for the objects where you have this issue?
- What kind of objects are those dependencies? (a few examples, simple objects? EF DbContext?)
- Do those dependency objects need to be shared across the scope?
- Have you tried to use  InstancePerDependency() lifetime so a unique instance will be returned from each object request?
- If sharing a DbContext across the scope, then I would use InstancePerLifetimeScope() or InstancePerRequest(), but I agree that this is the case for Http request in ASP.NET apps.

- Also, depending on your needs, you could also try the **InstancePerMatchingLifetimeScope()** and **InstancePerOwned()**. Have you tried those for this specific scenario?
I'm thinking that maybe some implementation using InstancePerOwned() could do what you need, as allows more precise control over instance sharing.

For instance, in the following code when registering the types:

```
var builder = new ContainerBuilder();
builder.RegisterType<MyIntegrationEventHandler>();
builder.RegisterType<ServiceForHandler>().InstancePerOwned<MyIntegrationEventHandler>();
```

In that example the ServiceForHandler service will be scoped to the lifetime of the owned MyIntegrationEventHandler instance.

You can see additional info here:
http://docs.autofac.org/en/latest/lifetime/instance-scope.html#instance-per-owned

I'm not sure if this is what you mean, but you could give it a try.

I also wrote a blog post with a comparison of ASP.NET Core IoC container service lifetimes compared with Autofac IoC container instance scopes where you can see all the possible lifetimes. Although this might be obvious for you, but just in case:

https://blogs.msdn.microsoft.com/cesardelatorre/2017/01/26/comparing-asp-net-core-ioc-service-life-times-and-autofac-ioc-instance-scopes/

In any case, this is a very interesting discussion, please keep sharing your experiences about it.
We will also try to find a solution based on your additional information.

Thanks for sharing! 👍

**Comment by CESARDELATORRE** [comment]
Closing this question. Feel free to continue with it if you wish.
