### ISSUE TITLE
[Question] How do you ensure that the asynchronous method will run synchronously in the tests?

### ISSUE THREAD

**Issue by programadorthi** [dotnet-architecture/eShopOnContainers#444]
In the `CatalogViewModel` class, you have the `ClearFilterCommand` to execute an asynchronous method called `ClearFilterAsync`.

In the `CatalogViewModelTests` class, the `ClearFilterCommandResetsPropertiesTest` method call the command in a synchronous way using `Execute(null)`.

How is it possible the assertions works if the `ClearFilterAsync` method is asynchronous?

```
[Fact]
public async Task ClearFilterCommandResetsPropertiesTest()
{
	var catalogService = new CatalogMockService();
	var catalogViewModel = new CatalogViewModel(catalogService);

	await catalogViewModel.InitializeAsync(null);
	catalogViewModel.ClearFilterCommand.Execute(null);

	Assert.Null(catalogViewModel.Brand);
	Assert.Null(catalogViewModel.Type);

        // Products can be null if ClearFilterAsync finishes before the assertion
	Assert.NotNull(catalogViewModel.Products);
}
```

**Comment by mvelosop** [comment]
Hi @programadorthi could not locate that file as of today, would you point me to where it is/was, please?

**Comment by programadorthi** [comment]
Hi @mvelosop I'm talking about the mobile version. Sorry, I forgot to specify. Both ViewModels can be found in the `Core` and `UnitTest` projects. `CatalogViewModel` lines `83` and `119` to `128`. `CatalogViewModelTests` lines `212` to `224`.

**Comment by mvelosop** [comment]
Hi @programadorthi, I'm sorry this took so long! I've been work to clean up the issues for a while now.

I don't know if you figured it out already, but the registered delegate is actually an **async** lambda, so no problem here, as the test case is async too:

https://github.com/dotnet-architecture/eShopOnContainers/blob/f9388c55be36f30ce5f7790b6871a90350be8b8f/src/Mobile/eShopOnContainers/eShopOnContainers.Core/ViewModels/CatalogViewModel.cs#L83

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now, but feel free to comment, will reopen if needed.
