### ISSUE TITLE
CommandBus and CommandBusRabbitMQ projects are not complete?

### ISSUE THREAD

**Issue by wesley2007** [dotnet-architecture/eShopOnContainers#451]
Hi there,

It would be great if you could provide complete project files in these two projects!! I am having build errors

`6>CommandBusRabbitMQ.cs(62,30,62,51): error CS0308: The non-generic type 'IntegrationCommand' cannot be used with type arguments
6>CommandBusRabbitMQ.cs(45,45,45,75): error CS0246: The type or namespace name 'IIntegrationCommandHandler<>' could not be found (are you missing a using directive or an assembly reference?)
6>CommandBusRabbitMQ.cs(51,41,51,67): error CS0246: The type or namespace name 'IIntegrationCommandHandler' could not be found (are you missing a using directive or an assembly reference?)
6>CommandBusRabbitMQ.cs(18,39,18,50): error CS0535: 'CommandBusRabbitMQ' does not implement interface member 'ICommandBus.SendAsync<T>(T)'
6>CommandBusRabbitMQ.cs(28,45,28,71): error CS0246: The type or namespace name 'IIntegrationCommandHandler' could not be found (are you missing a using directive or an assembly reference?)
6>CommandBusRabbitMQ.cs(55,59,55,89): error CS0246: The type or namespace name 'IIntegrationCommandHandler<>' could not be found (are you missing a using directive or an assembly reference?)`
 
Thank you very much!!

Wes

**Comment by wesley2007** [comment]
Also Ordering.Application project is missing too. Thank you so much!

**Comment by CESARDELATORRE** [comment]
Can yo specify what solution (.sln) are you using?
I've been testing yesterday with the solution referenced in our Wiki: 
**eShopOnContainers-ServicesAndWebApps.sln**

And I didn't have any issue like that.
Also, make sure that VS 2017 got all the external NuGet dependencies.

Please, can you specify the solution you are using and the environment you have?

**Comment by wesley2007** [comment]
Hi there,

Thank you for your reply!

I think there is a folder structure problem, there are two CommandBus folders, this appears to be a mis-linking to the solution to me. I guess the folder “BuildingBlocks\CommandBus” should not be there?

I had to add CommandBus project to the EventBus folder as it was not included.

[cid:image002.jpg@01D38543.65DB99F0]
Still getting the following build errors:

3>------ Rebuild All started: Project: EventBusRabbitMQ, Configuration: Debug Any CPU ------
3>CommandBusRabbitMQ.cs(112,34,112,39): error CS1739: The best overload for 'BasicConsume' does not have a parameter named 'noAck'
3>CommandBusRabbitMQ.cs(124,22,124,35): error CS0161: 'CommandBusRabbitMQ.InvokeHandler(string, string)': not all code paths return a value
3>Done building project "EventBusRabbitMQ.csproj" -- FAILED.

Before fix:
[cid:image006.jpg@01D38543.65DB99F0]

After fix:

[cid:image007.jpg@01D38543.65DB99F0]

It builds fine after the changes.

Thanks

Wes

**Comment by CESARDELATORRE** [comment]
It is really weird.. I’m not getting those issues neither in a Windows machine nor on a Mac machine that I tried today..

Can you try with a new “git Clone” of the git repo and opening the following solution:
EShopOnContainers-ServicesAndWebApps.sln

Thanks,

**Comment by CESARDELATORRE** [comment]
Closing this issue. I haven't been able to reproduce it in 4 different machines with clean git clone code. Including 3 Windows 10 machines and a Mac. In all of them it worked as expected when using the solution eShopOnContainers-ServicesAndWebApps.sln
