### ISSUE TITLE
Errors when building Docker images for Windows Containers since using Docker Multi-Stage builds

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#455]
Related to issue opened at: [https://github.com/dotnet/dotnet-docker/issues/352 ](https://github.com/dotnet/dotnet-docker/issues/352) 

Also related to this issue:
[https://github.com/moby/moby/issues/32838](https://github.com/moby/moby/issues/32838)

**Background:**
Since we're using Docker Multi-Stage builds, there are errors when building Docker images for Windows Containers and Docker is not able to create the SPA neither the MVC images for Windows Containers.

However, it looks like it happens randomly... Sometimes I was able to create the SPA Docker image..

**Repros:**

**Full solution:**
`docker-compose -f docker-compose-windows.yml build`

**Just try to build the SPA container:**
`docker-compose -f docker-compose-windows.yml build webspa`

**Error got when building the webspa image:**
```
ERROR: Service 'webspa' failed to build: re-exec error: exit status 1: output: time="2018-01-05T09:44:20-08:00" level=error msg="hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) layerId=\\?\C:\ProgramData\Docker\windowsfilter\edcd14474a98d3dd39f7df35e95f80e34f390a1db4429f4925d04d4635f6cc75 flavour=1 folder=C:\Windows\TEMP\hcs388882919"
hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) layerId=\\?\C:\ProgramData\Docker\windowsfilter\edcd14474a98d3dd39f7df35e95f80e34f390a1db4429f4925d04d4635f6cc75 flavour=1 folder=C:\Windows\TEMP\hcs388882919
```

**Comment by SychevIgor** [comment]
the best comment is https://github.com/dotnet/dotnet-docker/issues/352#issuecomment-355790599

**Comment by mvelosop** [comment]
Closing this old issue. Right now building the on windows containers completes successfully!
