### ISSUE TITLE
[Question] Is it possible to receive notification when new version is available: .NET microservices - Architecture e-book

### ISSUE THREAD

**Issue by PingPongSet** [dotnet-architecture/eShopOnContainers#458]
Is it possible to receive notification when new version of this book below is changed and publicly available:
[.NET microservices - Architecture e-book](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/)

**Comment by CESARDELATORRE** [comment]
Sure! Subscribe (Watch) to this GitHub repo we created for News/Announcements.

[https://github.com/dotnet-architecture/News/issues](https://github.com/dotnet-architecture/News/issues)

We'll publish there any important announcement about new versions of the eBooks/Guides and the reference apps, ok?

**Comment by PingPongSet** [comment]
thanks.
