### ISSUE TITLE
Facing this error while running the eshoponcontainer

### ISSUE THREAD

**Issue by RachanaNayak** [dotnet-architecture/eShopOnContainers#464]
![screenshot 59](https://user-images.githubusercontent.com/33618456/34975237-e1570b08-fab6-11e7-81bd-a8ae9c6c9971.png)

we are facing this error while running eshoponcontainer for Windows

**Comment by eiximenis** [comment]
This error usually happens when some compose items have not been destroyed.
To ensure compose cleans all items try to run  `docker-compose -f docker-compose-windows.yml down`

**Comment by RachanaNayak** [comment]
ok thanks for comment i will try this solution

**Comment by eiximenis** [comment]
Just let me know if it worked and/or close the issue if appropiate :)

**Comment by mvelosop** [comment]
Closing this issue as it seem stale. Will reopen if necessary.
