### ISSUE TITLE
k8s: Use ingress controller instead custom frontend service

### ISSUE THREAD

**Issue by eiximenis** [dotnet-architecture/eShopOnContainers#467]
Using [ingress controller](https://kubernetes.io/docs/concepts/services-networking/ingress/) is the recommended way in k8s to expose services.

This issue is just to track the implementation and related issues of the ingress controller **which is in the branch `ingress`**.

@CESARDELATORRE ingress is ready. Once you tested the branch just feel free to comment.

@SychevIgor your review is welcome too :)

PS: Wiki has ingress branch also with updated doc.

PS2: if you prefer a PR just let me know, and I do it.

**Comment by SychevIgor** [comment]
As an idea- I really like that we can use something native for k8 instead of custom wheel. 
100% agree with you!

I will try too look and test it carefully on this week.

**Comment by SychevIgor** [comment]
@eiximenis - you also have branch Ocelot apigw on top of ingresscontrollers.
Do Ocelot support Application Insights telemetry? because API GW now is a single point of failure as a GW and it will be nice ti monitor it.

**Comment by SychevIgor** [comment]
@eiximenis also nice feature is service discovery http://ocelot.readthedocs.io/en/latest/features/servicediscovery.html what do you think about it? now we have a lot of places in an app where we are using urls from config and overriding it via environment veriable. maybe we can put part of this info to services discovery. 
It's only an idea to discuss.

**Comment by SychevIgor** [comment]
@eiximenis also maybe for call outside of clusters- we will can use http://ocelot.readthedocs.io/en/latest/features/qualityofservice.html to simplify our circuit breaker ? now it's implemented on caller side(xamarin for example).

**Comment by unaizorrilla** [comment]
Hi @SychevIgor,

ServiceDiscovery only work with Consul and this is not deployed. @eiximenis  you have any plan to include in  k8s?

**Comment by eiximenis** [comment]
Hi.
About deploying Consul and enable service discovery would be a good idea, but AFAIK Consul do not support Windows Containers (update: I found [https://github.com/StefanScherer/dockerfiles-windows/tree/master/consul](https://github.com/StefanScherer/dockerfiles-windows/tree/master/consul) but I need to evaluate it).
Althought our current k8s deployment is only for Linux Containers if we use Ocelot+Consul for service discovery we should to find something similar for SF+Windows Containers scenario.

**Comment by eiximenis** [comment]
Merged to dev!
