### ISSUE TITLE
Images are broken in README.CICD.k8s.md

### ISSUE THREAD

**Issue by snpdev** [dotnet-architecture/eShopOnContainers#471]
There are four PNG images referenced in the README file:
https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/k8s/README.CICD.k8s.md

- blob_creation.png 
- deploy_script_task.png 
- get_kubectlbin_task.png 
- get_kubectlconfig_task.png 

But none are displayed.

**Comment by eiximenis** [comment]
Fixed in commit c745c8bd4b2b3848c35e9c621e39ea0e1639886d
Thx!
