### ISSUE TITLE
Facing error while running the eshoponcontainer  after docker-compose up

### ISSUE THREAD

**Issue by RachanaNayak** [dotnet-architecture/eShopOnContainers#477]
![screenshot 8](https://user-images.githubusercontent.com/33618456/35221246-7dc629b4-ff9f-11e7-8737-13c2509ae8bf.png)

command is: docker-compose -f docker-compose-windows up

**Comment by mvelosop** [comment]
Hi @RachanaNayak, this is a bit old, so I guess it must be solved by now, but in case it's not, you should check this wiki page: https://github.com/dotnet-architecture/eShopOnContainers/wiki/08.-Setting-up-and-Deploying-eShopOnContainers-to-Windows-Containers.

**Comment by mvelosop** [comment]
@RachanaNayak just for starters that is not the command you should use for windows containers. Please check the wiki page.
