### ISSUE TITLE
Facing error for running the eshop on container

### ISSUE THREAD

**Issue by RachanaNayak** [dotnet-architecture/eShopOnContainers#478]
![screenshot 11](https://user-images.githubusercontent.com/33618456/35257628-6a9c44be-0020-11e8-8cc9-a412104a536e.png)

error is regarding the process cannot access the file because it is being used by another process

**Comment by eiximenis** [comment]
Try to do a `docker-compose -f docker-compose.windows.yml down`. 
Hope this helps!

**Comment by mvelosop** [comment]
Closing this issue as it seem stale!
