### ISSUE TITLE
bash script for update only one Service

### ISSUE THREAD

**Issue by kodermax** [dotnet-architecture/eShopOnContainers#479]
Do you have the script which update one service on production through docker?

**Comment by eiximenis** [comment]
Hi!
What "production" means? :)

We don't have any script to do this, right now, but if using k8s this is very straight-forward.

1. Open a PS command-line
2. Set an environment variable called TAG with the value of the tag images used.
3. Build the desired image (i. e. `docker-compose build basket.api`). As `TAG` environment variable is set the image will be built using the desired tag.
4. Push the new image in the repository (' docker tag`  then `docker push`)
5. Run the following multi-line sentence (parameter of Select-String on last line is the beginning of the pod name):
```
kubectl delete pod $(kubectl get pods -o go-template --template @"
{{range .items}}{{.metadata.name}}
{{end}}
"@ | Select-String -Pattern  'ordering-')
```
This deletes the specified pod. So k8s will create a new pod to satisfy the deployment that instructs that we should have always one pod. And as we use _pull always_ for image pulling policy, kubelet will pull the new image before creating the pod again.

**Comment by kodermax** [comment]
I meant a similar script
```bash
#!/bin/bash
if [ -z "$1" ]
then
  echo -e "Usage: \n${0##*/} service-name"
  exit 1
else 
  docker-compose up -d --no-deps --build $1
  STATUS=$?
  if [ $STATUS -eq 0 ]
  then
    echo -e "\nContainer successfully updated"
  else
    echo -e "\nFailed updating container"
  fi
fi

```

**Comment by CESARDELATORRE** [comment]
@kodermax - Our "production" environment is Kubernetes or Service FAbric.
If we need to deploy a single container into Docker, we do that directly with the Docker CLI, like:

`docker-compose up -d --no-deps --build catalog-api`

That script you show is useful/simpler, but we chose not to update many scripts like that into the GitHub repo so it is not overwhelming about the number of scripts we provide. 
However, I hear you and see your point. 
We might add it in the future. 
Thanks for the feedback! 👍

**Comment by CESARDELATORRE** [comment]
Closing this issue.
