### ISSUE TITLE
local.json and cloud.json not found

### ISSUE THREAD

**Issue by snpdev** [dotnet-architecture/eShopOnContainers#481]
[README.k8s.md](https://github.com/dotnet-architecture/eShopOnContainers/blob/5198041574bf50a378b625c6d4897ade60bc2611/k8s/README.k8s.md) states:

> A configuration file local.json is provided which configures Pods to use the infrastructure containers... For reference another configuration file (cloud.json) is provided but without valid values.

I see neither the local.json nor the cloud.json files in the repo. There are however, conf_local.yml and conf_cloud.yml files. I assume that the yaml files are the ones to use and that the document just needs to be updated.

Please confirm. 

Thanks - Mike

**Comment by eiximenis** [comment]
Hi @snpdev 
Yes the files are conf_local.yml and conf_cloud.yml. There were jsons in the beginning of time, seems that the doc is outdated :)

Thx!

**Comment by liambarnett** [comment]
The docs should be updated now see here - #503

**Comment by CESARDELATORRE** [comment]
Closing this issue, as the docs were already updated.
