### ISSUE TITLE
Siva

### ISSUE THREAD

**Issue by siva2krish** [dotnet-architecture/eShopOnContainers#482]
Hi Team,
After deploying eShoponContainer Application to AKS Cluster using deploy.ps1 script , i'm facing some issue with pods they are not stable and getting errors like below , Can any one help me on this 
![image](https://user-images.githubusercontent.com/30602781/35376645-f795c2e6-0179-11e8-8508-acf737a13642.png)

**Comment by unaizorrilla** [comment]
Can you try to increment of liveness time for the service pod?

**Comment by siva2krish** [comment]
Hi Unaizorrilla,

Thanks..! it works for me..! increased liveness time & rediness as well.
