### ISSUE TITLE
Need Help for validation Rules.

### ISSUE THREAD

**Issue by naumanahmed19** [dotnet-architecture/eShopOnContainers#485]
I am using Xamarin validation classes. The given example is working fine. But I am facing 2 issues it would be great if anyone can guide me.

1) How to use validate confirm password right now I am trying something like this.

```  
_confirmPassword.Validations.Add(new IsPasswordMatchRule<string>
{
       ValidationMessage = "Password do not match.",
        Pass = Password.Value, // its not passing Password.Value 
 });
```
and rule is.

``` 
  public class IsPasswordMatchRule<T> : IValidationRule<T>
    {
        public string ValidationMessage { get; set; }
        public string Pass { get; set; }
        public bool Check(T value)
            var str = value as string;
            if (str == Pass)
            {
                return true;
             
            }
            return false;
        }
    }
```

2) How can I validate email/username if already exist in database and display validation? 

Thanks

**Comment by mvelosop** [comment]
Hi @naumanahmed19, I'm closing this issue as it's not related to eShopOnContainers.

I guess you must have probably figured it out by now, but a quick search got me into: https://stackoverflow.com/questions/31473343/xamarin-forms-password-and-confirm-password-validation

Cheers.
