### ISSUE TITLE
[Feature Request]/[Question] a bit of IoT

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#488]
Hello,
I know that we have more than enough IoT reference architecture for example https://github.com/azure/azure-iot-pcs-remote-monitoring-dotnet
But what do you think about adding some small IoT related feature? like drone emulator that will deliver our order? 

I'm asking because on some of my conversation about .net core and microservices architecture I'm more and more receiving question about- how we can apply it to IoT and so on. As a result- I'm using another reference project to address it. But it will be nice to combine Iot+ containers reference architecture to a one demo.

**Comment by CESARDELATORRE** [comment]
Could be. But I’d prefer to fork it in the future when it is more stable after the many changes we are currently doing and add the IoT stuff.
I don’t want this repo to grow too much heading too many ways..
