### ISSUE TITLE
[Support/feature] Test and document support for Kubernetes in local "Docker for Windows"

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#507]
Latest EDGE versions of "Docker for Windows" support a single node cluster of Kubernetes running on the local development PC.

![image](https://user-images.githubusercontent.com/1712635/36050011-a7f8a6d2-0d99-11e8-9acf-804621102950.png)

We need to test and document (as a new Wiki post) this scenario as soon as possible, as it will be a first choice to try by most developers.

**Comment by eiximenis** [comment]
Closing , as this is done :)
