### ISSUE TITLE
Enumeration requires public parameterless constructors

### ISSUE THREAD

**Issue by erik-am** [dotnet-architecture/eShopOnContainers#527]
First of all, great work on the ebook and the example application. I love how there's an up-to-date guide that explains how to apply DDD patterns in ASP.NET Core. 👍 I'm using this as a reference for my own microservices.

I have one issue with the `Enumeration` class. The `FromValue` and `FromDisplayName` are the valuable ingredients in there. However, they delegate to `GetAll()` that requires the enumeration to have a public, parameterless constructor (the `T : new()` constraint). To me that seems to be an anti-pattern, now `CardType` (the example) is not a true value object anymore.

https://github.com/dotnet-architecture/eShopOnContainers/blob/963a39e2acc27b104d8251f7150e49f885fb4556/src/Services/Ordering/Ordering.Domain/SeedWork/Enumeration.cs#L24-L37

An alternative is to provide typed static methods `GetAll`, `FromDisplayName` and `FromDisplayName` in every implementation, but that will result in duplication.

What is your opinion on this?

**Comment by mvelosop** [comment]
Hi @erik-am, I'm curious, why do you say CardType or any other are not true value objects anymore?

**Comment by mvelosop** [comment]
Closing the issue as it seems stale, will reopen if needed.
