### ISSUE TITLE
[Feature Request] More endpoint security

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#538]
After deploying fully cloud version - via application insights I had recognized that after 5 minutes since the deployment, app was started attacking. 
Nothing special, just requests to default pages like
GET //pma/scripts/setup.php
GET //myadmin/scripts/setup.php
HEAD /phpMyAdmin/scripts/setup.php
from locations like Tampa/US or Libya. 

I had checked books attached to a repo and didn't find much about endpoint protection from external attacks, only one sentence about- gateway and azure application gateway. 
It would be nice to have azure application gateway deployment script here or some hints from bruteforce attacks and so on.

If it's out of scope- fine, it's just my feedback

**Comment by CESARDELATORRE** [comment]
Good feedback. Whenever we can invest more in Azure assets for the microservices app, we’ll take that point into account. Thanks. :)
