### ISSUE TITLE
EventBusRabbitMQ

### ISSUE THREAD

**Issue by Christowiak** [dotnet-architecture/eShopOnContainers#542]
I'm using the EventBusRabbitMQ library for communication between a Rest Api and a Windows Process. I have noticed that sometimes single messages get lost on the bus. After looking into the code of the EventBusRabbitMq Class i have noticed that on both sides (Api and Win-Process) the Received-Event from the consumer is registered. So when i send a message from Api to the rabbit-channel it could be possible that the "received"-Event is fired on the Api-Side and not on the Win-Process side. 

At first i had tried to check if the subscriber exists and only do "channel.BasicAck" when it exists, so the message won't be deleted. But i had the problem that the Received event won't be fired up again on the other side. 

My solution for this problem is, to split up the EventBusRabbitMq in to classes. One for publishing and one for subscribing. 

At next i have increased the logic with a Factory-Class. So i can do multiple channels for two way communication...

Has any one else this problem? Or do i something wrong?

**Comment by mvelosop** [comment]
Hi @Christowiak, is this something you noticed in eShopOnContainers?

**Comment by Christowiak** [comment]
Hey @mvelosop. Not direct in eShopOnContainers, but i have used the complete same event bus code and also a aps net core 2 api with even same startup middleware like autofac and so on. So i thought, it could be interesting for this project too.

**Comment by mvelosop** [comment]
Hi @Christowiak, thanks for the heads up, I haven't seen it reported here, but then again I haven't been too long in this project.

However, if you feel like it, you could submit a PR for review, even better if you could devise a test case for the situation you mentioned.

Thanks! :+1:

**Comment by CESARDELATORRE** [comment]
We should have a repro of the issue in eShopOnContainers before changing th code.

**Comment by Christowiak** [comment]
@mvelosop, @CESARDELATORRE. I can create a code example, which shows the fail situation, by using windows process and api in my case. But, when it works in eShopOnContainers without any problem, i think its not neccesary? Because i splitted up the code in to parts for my solution now. Subscriber service and publisher service. So it would be a big change for this project.

**Comment by mvelosop** [comment]
Hi @Christowiak, it would be interesting to take a look at that situation, as may be something that could happen. If you feel like creating the code sample in your repo I'd be glad to take a look at it.

In the mean time, I'm closing this issue since, for the time being, it doesn't seem to be affecting eShopOnContainers.

Thanks!
