### ISSUE TITLE
Capital casing commands in wiki

### ISSUE THREAD

**Issue by alexeyzimarev** [dotnet-architecture/eShopOnContainers#545]
Commands on this wiki page https://github.com/dotnet-architecture/eShopOnContainers/wiki/03.-Setting-the-eShopOnContainers-solution-up-in-a-Windows-CLI-environment-(dotnet-CLI,-Docker-CLI-and-VS-Code) are capitalised (`Git`, `Docker-compose`) and when I copy-paste them on Linux, they don't work.

**Comment by mvelosop** [comment]
Hi @alexeyzimarev, the page you are pointing to is for a Windows CLI, but as you are working in Linux, I think the page for Mac is a better fit: https://github.com/dotnet-architecture/eShopOnContainers/wiki/04.-Setting-eShopOnContainer-solution-up-in-a-Mac,-VS-for-Mac-or-with-CLI-environment--(dotnet-CLI,-Docker-CLI-and-VS-Code)

**Comment by alexeyzimarev** [comment]
True
