### ISSUE TITLE
Please help me,not to run.

### ISSUE THREAD

**Issue by vs0533** [dotnet-architecture/eShopOnContainers#547]
After the project is removed, use visual stduio for mac(7.4 build 1033) to open the setting startup item: "docker-compose" runtime prompt error.

Use:   eShopOnContainers-ServicesAndWebApps.sln
Error Info:

/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/AddIns/docker/MonoDevelop.Docker/MSbuild/Sdks/Microsoft.Docker.Sdk/build/Microsoft.VisualStudio.Docker.Compose.targets(5,5): Error: The INSTRUMENTATION_KEY variable is not set. Defaulting to a blank string.
The ORCHESTRATOR_TYPE variable is not set. Defaulting to a blank string.
The ESHOP_SERVICE_BUS_USERNAME variable is not set. Defaulting to a blank string.
The ESHOP_SERVICE_BUS_PASSWORD variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_CATALOG_KEY variable is not set. Defaulting to a blank string.
The ESHOP_AZUREFUNC_CAMPAIGN_DETAILS_URI variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_MARKETING_NAME variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_MARKETING_KEY variable is not set. Defaulting to a blank string.
The Compose file '/Users/tanglin/MyGitRepos/eShopOnContainers/obj/Docker/docker-compose.vs.debug.g.yml' is invalid because:
services.basket.api.build contains unsupported option: 'target'
services.catalog.api.build contains unsupported option: 'target'
services.identity.api.build contains unsupported option: 'target'
services.locations.api.build contains unsupported option: 'target'
services.marketing.api.build contains unsupported option: 'target'
services.ordering.api.build contains unsupported option: 'target'
services.ordering.backgroundtasks.build contains unsupported option: 'target'
services.payment.api.build contains unsupported option: 'target'
services.webmvc.build contains unsupported option: 'target'
services.webspa.build contains unsupported option: 'target'
services.webstatus.build contains unsupported option: 'target'。

**Comment by vs0533** [comment]
The point is :

/Users/tanglin/Projects/eShopOnContainers/obj/Docker/docker-compose.vs.debug.g.yml

look：

Copying file from "/Users/tanglin/Projects/eShopOnContainers/obj/Docker/docker-compose.vs.debug.partial.g.yml" to "/Users/tanglin/Projects/eShopOnContainers/obj/Docker/docker-compose.vs.debug.g.yml".
    Copying file from "/Users/tanglin/Projects/eShopOnContainers/obj/Docker/docker-compose.vs.release.partial.g.yml" to "/Users/tanglin/Projects/eShopOnContainers/obj/Docker/docker-compose.vs.release.g.yml".
Target DockerPrepareForLaunch:
    docker-compose  -f "/Users/tanglin/Projects/eShopOnContainers/docker-compose.yml" -f "/Users/tanglin/Projects/eShopOnContainers/docker-compose.override.yml" -f "/Users/tanglin/Projects/eShopOnContainers/obj/Docker/docker-compose.vs.debug.g.yml" -p dockercompose16809230024970745557 --no-ansi config
    The Compose file '/Users/tanglin/Projects/eShopOnContainers/obj/Docker/docker-compose.vs.debug.g.yml' is invalid because:
    services.basket.api.build contains unsupported option: 'target'
    services.catalog.api.build contains unsupported option: 'target'
    services.identity.api.build contains unsupported option: 'target'
    services.locations.api.build contains unsupported option: 'target'
    services.marketing.api.build contains unsupported option: 'target'
    services.ordering.api.build contains unsupported option: 'target'
    services.ordering.backgroundtasks.build contains unsupported option: 'target'
    services.payment.api.build contains unsupported option: 'target'
    services.webmvc.build contains unsupported option: 'target'
    services.webspa.build contains unsupported option: 'target'
    services.webstatus.build contains unsupported option: 'target'

**Comment by prisar** [comment]
I am also getting this error while building with vs 2017 for Mac. But, if I use `docker-compose up `, everything seams to be working. Why is that so?

**Comment by vs0533** [comment]
I can use commands but I can't debug them.

**Comment by vs0533** [comment]
The use of the command "docker ps" will show that some containers marked "none" are running.

**Comment by mvelosop** [comment]
Hi @vs0533, I don't have a Mac, so I'm not sure, but, have you followed the instructions in this wiki page?: https://github.com/dotnet-architecture/eShopOnContainers/wiki/04.-Setting-eShopOnContainer-solution-up-in-a-Mac,-VS-for-Mac-or-with-CLI-environment--(dotnet-CLI,-Docker-CLI-and-VS-Code)

**Comment by CESARDELATORRE** [comment]
@vs0533 - This was fixed today and tracked down in this issue: https://github.com/dotnet-architecture/eShopOnContainers/issues/553
Basically, VS for Mac now requires docker-compose v '3.4' in order to be able to F5 or Ctrl+5 as it internally uses the option: 'target' internally, which is new since v 3.4.
 
Please, do a "git pull" and it should work. 
I'm closing this issue, ok?

**Comment by virasana** [comment]
This is happening on Windows too.   Visual Studio Professional v 15.9.4.  Visual Studio is generating its own yaml which contains the additional "target" element.

**Comment by mvelosop** [comment]
Hi @virasana, I'll be checking on this, can you please tell me if this is happening with the latest version of eShop?

**Comment by virasana** [comment]
Hi There, 
I am not running eshop, sorry!  I was under the impression that this was a Visual Studio / Microsoft thread!

**Comment by mvelosop** [comment]
Oh, ok, no problem, hope you get it solved!

**Comment by muralib91dotnet** [comment]
This is happening for me on Windows 10 x64. Visual Studio Professional v 15.9.11. The following is my Error:

Error		The INSTRUMENTATION_KEY variable is not set. Defaulting to a blank string.
The ORCHESTRATOR_TYPE variable is not set. Defaulting to a blank string.
The ESHOP_SERVICE_BUS_USERNAME variable is not set. Defaulting to a blank string.
The ESHOP_SERVICE_BUS_PASSWORD variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_CATALOG_KEY variable is not set. Defaulting to a blank string.
The ESHOP_AZUREFUNC_CAMPAIGN_DETAILS_URI variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_MARKETING_NAME variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_MARKETING_KEY variable is not set. Defaulting to a blank string.
Creating network "dockercompose14258745468603192890_default" with the default driver
Pulling sql.data (microsoft/mssql-server-linux:2017-latest)...
Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).

For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	367

**Comment by mvelosop** [comment]
Hi @muralib91dotnet,

Did you try this from the CLI?

Sometimes it helps restarting Docker.

hope this helps.
