### ISSUE TITLE
Error while pushing images to container registry 

### ISSUE THREAD

**Issue by t-mavill** [dotnet-architecture/eShopOnContainers#555]
Hello,

I currently am facing some unknown errors : when deploying the solution onto Azure ( ./deploy.ps1). Everything is looking ok but my images are not in my container registry after the deployment. Plus the kubernetes Dashboard is totaly blank (no charts, just blank page). If I look the deployment (Kubectl get deployment) everything is here and looking good.

**Comment by CESARDELATORRE** [comment]
Looks like issues with your specific environment. We cannot do much about it as we just have limited bandwidth to support issues with eShopOnContainers code or issues/bugs in our code.
I'm closing this issue. It could be re-openeded if you isolate any issue/problem in our code or deployment scripts, ok?
For instance, compare the execution of the script versus if you manually push your images to ACR, etc.
Btw, pretty soon we'll change from ACS-Kubernetes to AKS-Kubernetes (latest version and more PaaS than ACS) and we'll made some updates in the Wiki about it.
Thanks,
