### ISSUE TITLE
[Feature/Improvement] Add kubernetes support for Mac

### ISSUE THREAD

**Issue by prisar** [dotnet-architecture/eShopOnContainers#558]
If there is any guideline to run the containers in Mac, then it would have been helpful.

**Comment by eiximenis** [comment]
Hi @prisar 
Following the [procedure for deploying on local k8s of Docker Desktop for Windows](https://github.com/dotnet-architecture/eShopOnContainers/wiki/10.-Deploying-to-Kubernetes-(AKS-and-local)-using-Helm-Charts#using-helm-charts-to-deploy-eshoponcontainers-to-a-local-kubernetes-in-windows-with-docker-for-windows), should work for Mac. Just use the `/k8s/helm/deploy-all.sh` script and maybe it works (not tested on Mac but on Linux).
Other two powershells (deploy-ingress.ps1 and deploy-ingress-dockerlocal.ps1) are very straightforward and you can replace them from bash console.
