### ISSUE TITLE
Invalid_request on auth from Swagger for Location API

### ISSUE THREAD

**Issue by NicolasReyDotNet** [dotnet-architecture/eShopOnContainers#562]
Hi,

When trying to authorize Swagger to grant an access to Location API, I get redirected with an Invalid_request error from Identity API.

[Auth from swagger](https://ibb.co/mh6HVS)
[Resulting error](https://ibb.co/g3YLjn)

Full URL is the following
http://localhost:5105/home/error?errorId=CfDJ8HlsH9uoqgBKgA8HZFcuGwLDP4TFpXOVCvyC4iWl4UbfKv3yotq6aSilta9K8IPgrbrbZvUQivH7zw8ln4hpassJYzpR8P0J65QyDcA4_Nv1xVB1PF4V_m6rs1A8YmXpTUrwp_EsQiCypEY8IXM_Y_bIdZ-4ZpPfbqjOhOqshDWWlm0mvDvs0w9XIblWsPqJDEpxPuYvsLTWsXEZJonQVvON3ke9P7gZpto-4wR1yjXi35y9oe4AMPW-Rkj1RY4ItBVY-YN4-w82LcDqNcRqCWBDhZRBLxC3SKKK2Vi8lC2E

**Comment by mvelosop** [comment]
Hi @NicolasReyDotNet, could you check quick fix on issue #586?

I was having the same problem as you, only the record that has to changed for Location.Api is the one with port 5109, so the complete RedirectUri should be: `http://localhost:5109/swagger/oauth2-redirect.html`.
