### ISSUE TITLE
SwaggerUIOptions error in visual studio 2017 for mac

### ISSUE THREAD

**Issue by prisar** [dotnet-architecture/eShopOnContainers#576]
I am getting this error:

`eShopOnContainers/src/Services/Marketing/Marketing.API/Startup.cs(22,22): Error CS1061: 'SwaggerUIOptions' does not contain a definition for 'OAuthClientId' and no extension method 'OAuthClientId' accepting a first argument of type 'SwaggerUIOptions' could be found (are you missing a using directive or an assembly reference?) (CS1061) (docker-compose)`

**Comment by prisar** [comment]
yes, this is the first time i am trying in mac

**Comment by mvelosop** [comment]
Did you follow this guide?: https://github.com/dotnet-architecture/eShopOnContainers/wiki/04.-Setting-eShopOnContainer-solution-up-in-a-Mac,-VS-for-Mac-or-with-CLI-environment--(dotnet-CLI,-Docker-CLI-and-VS-Code)

**Comment by mvelosop** [comment]
Closing this issue as it seems stale and an environment issue, will reopen if needed!
