### ISSUE TITLE
Not able to run application through Visual Studio

### ISSUE THREAD

**Issue by rajnikaushal** [dotnet-architecture/eShopOnContainers#584]
Hi,
I got clone of eshopContainer application and it was working fine. But since last 2 days i am facing following error:
'Internal Server Error: CurlException: Couldn't resolve host name'
I have also tried with stopping all containers but still error is same.
Please suggest how to resolve the issue.

Thanks
Rajni

**Comment by mvelosop** [comment]
Hi @rajnikaushal, You are giving very little information, but, since it looks like a network problem, I'll tell you I always get network error between containers right after startup, that go away when I restart Docker (Windows 10).

**Comment by rajnikaushal** [comment]
Hi
But i restarted it so many times but error is still same.

**Comment by mvelosop** [comment]
I understand, but you are not telling me anything!

Did you follow the setup guide for your platform?: https://github.com/dotnet-architecture/eShopOnContainers/wiki#setting-up-your-development-environment-for-eshoponcontainers

**Comment by rajnikaushal** [comment]
Yes Miguel,
I followed all instructions and even it was working fine before 2 days. It
just stopped working from last 2 days.
Please guide me on this. Actually i am new on docker. It would be great if
you will help me out.
Thanks for your time.

**Comment by rajnikaushal** [comment]
Please let mw know what additional detail you required for the same?

**Comment by mvelosop** [comment]
Versions of Windows, Docker, VS, running through CLI or running through VS.
The "filtered" (e.g. not 100's of lines) error trace could help.
If sending error trace, please do so as if it was code, much easier to read.

**Comment by rajnikaushal** [comment]
I anyzed again shared link and i think my vs version was 15.6 and for
latest release we need 15.7+. I am running application through vs. But how
it was working till two days before. I think they just checked in there
code before 2 days ago.
Actually right now i am at home and will try with dev branch as mentioned
in link.
I need to create new micro service with sql server database. Can you please
guide me how can i do this. Actually in current code,  we have so many
layers like rabbit mq, event bus etc. I simpky want to create an api which
will store simple record in database. Please guide me how can i do this.
Really thanls for your support.

**Comment by CESARDELATORRE** [comment]
If you had it working and now it is not working it must be an environment issue.
I’d recommend to uninstall Docker for Windows and re-install. It is a very quick process. :)

**Comment by rajnikaushal** [comment]
I also tried it on my friend's system but did not work.

**Comment by mvelosop** [comment]
Hi @rajnikaushal, you might try running it from the CLI or checking out the master branch.

**Comment by smeilhac** [comment]
Hi, same problem for me : on opening, browser display "CurlException: Couldn't resolve host name".

It happening in ResilientHttpClient.cs line 90 : 
`var response = await _client.SendAsync(requestMessage);`

requestMessage uri link to http://webshoppingapigw wich is defined to Settigns in docker-compose.override.yml (l. 139) and docker-compose.prod.yml (l. 142).

**Comment by mvelosop** [comment]
Hi @smeilhac, which of the setup documents of the wiki did you follow? https://github.com/dotnet-architecture/eShopOnContainers/wiki#setting-up-your-development-environment-for-eshoponcontainers.

What's your network environment?

**Comment by smeilhac** [comment]
I've follow this one : Visual Studio 2017 and Windows based. I'm on Windows 10 with a Ethernet connection shared by Hyper-V

![image](https://user-images.githubusercontent.com/7485478/39290623-880337e8-4930-11e8-8172-2f476c1a3393.png)

It's worked fine since last week as i pull many commits. I think last commit from my pull was 26c3b58.

**Comment by mvelosop** [comment]
I don't see anything unusual there (except the Windows Phone Emulator ;-).

Please, post the log from the Output window (as code please) so maybe we can get some clue (like so):
```
1>------ Build started: Project: docker-compose, Configuration: Debug Any CPU ------
1>docker ps --filter "status=running" --filter "name=dockercompose17813091844751630401_basket.api_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose17813091844751630401_catalog.api_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose17813091844751630401_identity.api_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose17813091844751630401_locations.api_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose17813091844751630401_marketing.api_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose17813091844751630401_mobilemarketingapigw_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose17813091844751630401_mobileshoppingagg_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose17813091844751630401_mobileshoppingapigw_" --format {{.ID}} -n 1
```

**Comment by smeilhac** [comment]
I don't even remember why this WP emulator network interface exists :D 

Here is the build output : 

`1>------ Build started: Project: docker-compose, Configuration: Debug Any CPU ------
1>docker ps --filter "status=running" --filter "name=dockercompose900383749948941825_basket.api_" --format {{.ID}} -n 1
1>78a0ea0feb5a
1>docker exec -i 78a0ea0feb5a /bin/bash -c "if PID=$(pidof -x dotnet); then kill $PID; fi"
1>docker ps --filter "status=running" --filter "name=dockercompose900383749948941825_catalog.api_" --format {{.ID}} -n 1
1>4ab9aeb89cab
1>docker exec -i 4ab9aeb89cab /bin/bash -c "if PID=$(pidof -x dotnet); then kill $PID; fi"
1>docker ps --filter "status=running" --filter "name=dockercompose900383749948941825_identity.api_" --format {{.ID}} -n 1
1>5a72115d47eb
1>docker exec -i 5a72115d47eb /bin/bash -c "if PID=$(pidof -x dotnet); then kill $PID; fi"
1>docker ps --filter "status=running" --filter "name=dockercompose900383749948941825_locations.api_" --format {{.ID}} -n 1
1>3d08a15f4567
1>docker exec -i 3d08a15f4567 /bin/bash -c "if PID=$(pidof -x dotnet); then kill $PID; fi"
1>docker ps --filter "status=running" --filter "name=dockercompose900383749948941825_marketing.api_" --format {{.ID}} -n 1
1>0b3c6855f03a
1>docker exec -i 0b3c6855f03a /bin/bash -c "if PID=$(pidof -x dotnet); then kill $PID; fi"
1>docker ps --filter "status=running" --filter "name=dockercompose900383749948941825_ordering.api_" --format {{.ID}} -n 1
1>674154f67133
1>docker exec -i 674154f67133 /bin/bash -c "if PID=$(pidof -x dotnet); then kill $PID; fi"
1>docker ps --filter "status=running" --filter "name=dockercompose900383749948941825_payment.api_" --format {{.ID}} -n 1
1>080e31f6788d
1>docker exec -i 080e31f6788d /bin/bash -c "if PID=$(pidof -x dotnet); then kill $PID; fi"
1>docker ps --filter "status=running" --filter "name=dockercompose900383749948941825_webmvc_" --format {{.ID}} -n 1
1>19ecc37298f2
1>docker exec -i 19ecc37298f2 /bin/bash -c "if PID=$(pidof -x dotnet); then kill $PID; fi"
1>docker ps --filter "status=running" --filter "name=dockercompose900383749948941825_webspa_" --format {{.ID}} -n 1
1>051e25948e23
1>docker exec -i 051e25948e23 /bin/bash -c "if PID=$(pidof -x dotnet); then kill $PID; fi"
1>docker ps --filter "status=running" --filter "name=dockercompose900383749948941825_webstatus_" --format {{.ID}} -n 1
1>f32387243cbc
1>docker exec -i f32387243cbc /bin/bash -c "if PID=$(pidof -x dotnet); then kill $PID; fi"
1>EventBus -> D:\Sources\eShopOnContainers\src\BuildingBlocks\EventBus\EventBus\bin\Debug\netstandard2.0\EventBus.dll
1>Microsoft.Extensions.HealthChecks -> D:\Sources\eShopOnContainers\src\BuildingBlocks\HealthChecks\src\Microsoft.Extensions.HealthChecks\bin\Debug\netstandard2.0\Microsoft.Extensions.HealthChecks.dll
1>EventBusServiceBus -> D:\Sources\eShopOnContainers\src\BuildingBlocks\EventBus\EventBusServiceBus\bin\Debug\netstandard2.0\EventBusServiceBus.dll
1>EventBusRabbitMQ -> D:\Sources\eShopOnContainers\src\BuildingBlocks\EventBus\EventBusRabbitMQ\bin\Debug\netstandard2.0\EventBusRabbitMQ.dll
1>Microsoft.AspNetCore.HealthChecks -> D:\Sources\eShopOnContainers\src\BuildingBlocks\HealthChecks\src\Microsoft.AspNetCore.HealthChecks\bin\Debug\netstandard2.0\Microsoft.AspNetCore.HealthChecks.dll
1>Basket.API -> D:\Sources\eShopOnContainers\src\Services\Basket\Basket.API\bin\Debug\netcoreapp2.0\Basket.API.dll
1>IntegrationEventLogEF -> D:\Sources\eShopOnContainers\src\BuildingBlocks\EventBus\IntegrationEventLogEF\bin\Debug\netstandard2.0\IntegrationEventLogEF.dll
1>Microsoft.Extensions.HealthChecks.AzureStorage -> D:\Sources\eShopOnContainers\src\BuildingBlocks\HealthChecks\src\Microsoft.Extensions.HealthChecks.AzureStorage\bin\Debug\netstandard2.0\Microsoft.Extensions.HealthChecks.AzureStorage.dll
1>Microsoft.Extensions.HealthChecks.SqlServer -> D:\Sources\eShopOnContainers\src\BuildingBlocks\HealthChecks\src\Microsoft.Extensions.HealthChecks.SqlServer\bin\Debug\netstandard2.0\Microsoft.Extensions.HealthChecks.SqlServer.dll
1>WebHost.Customization -> D:\Sources\eShopOnContainers\src\BuildingBlocks\WebHostCustomization\WebHost.Customization\bin\Debug\netcoreapp2.0\WebHost.Customization.dll
1>Catalog.API -> D:\Sources\eShopOnContainers\src\Services\Catalog\Catalog.API\bin\Debug\netcoreapp2.0\Catalog.API.dll
1>Ordering.Domain -> D:\Sources\eShopOnContainers\src\Services\Ordering\Ordering.Domain\bin\Debug\netstandard2.0\Ordering.Domain.dll
1>Ordering.Infrastructure -> D:\Sources\eShopOnContainers\src\Services\Ordering\Ordering.Infrastructure\bin\Debug\netstandard2.0\Ordering.Infrastructure.dll
1>Ordering.API -> D:\Sources\eShopOnContainers\src\Services\Ordering\Ordering.API\bin\Debug\netcoreapp2.0\Ordering.API.dll
1>Resilience.Http -> D:\Sources\eShopOnContainers\src\BuildingBlocks\Resilience\Resilience.Http\bin\Debug\netstandard2.0\Resilience.Http.dll
1>WebMVC -> D:\Sources\eShopOnContainers\src\Web\WebMVC\bin\Debug\netcoreapp2.0\WebMVC.dll
1>Identity.API -> D:\Sources\eShopOnContainers\src\Services\Identity\Identity.API\bin\Debug\netcoreapp2.0\Identity.API.dll
1>WebSPA -> D:\Sources\eShopOnContainers\src\Web\WebSPA\bin\Debug\netcoreapp2.0\WebSPA.dll
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\TypeScript\Microsoft.TypeScript.targets(67,5): warning : Your project does not specify a TypeScriptToolsVersion. The latest available TypeScript compiler will be used (2.6). To remove this warning, set TypeScriptToolsVersion to a specific version or "Latest" to always select the latest compiler.
1>Done building project "WebSPA.csproj".
1>WebStatus -> D:\Sources\eShopOnContainers\src\Web\WebStatus\bin\Debug\netcoreapp2.0\WebStatus.dll
1>Payment.API -> D:\Sources\eShopOnContainers\src\Services\Payment\Payment.API\bin\Debug\netcoreapp2.0\Payment.API.dll
1>Locations.API -> D:\Sources\eShopOnContainers\src\Services\Location\Locations.API\bin\Debug\netcoreapp2.0\Locations.API.dll
1>Marketing.API -> D:\Sources\eShopOnContainers\src\Services\Marketing\Marketing.API\bin\Debug\netcoreapp2.0\Marketing.API.dll
1>C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy RemoteSigned -File "C:\Users\Sylvain\AppData\Local\Temp\GetVsDbg.ps1" -Version vs2017u5 -RuntimeID debian.8-x64 -InstallPath "C:\Users\Sylvain\vsdbg\vs2017u5"
1>Info: Using vsdbg version '15.7.20327.1'
1>Info: Using Runtime ID 'linux-x64'
1>Info: Latest version of VsDbg is present. Skipping downloads
1>docker-compose  -f "D:\Sources\eShopOnContainers\docker-compose.yml" -f "D:\Sources\eShopOnContainers\docker-compose.override.yml" -f "D:\Sources\eShopOnContainers\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose900383749948941825 --no-ansi up -d
1>The ESHOP_SERVICE_BUS_USERNAME variable is not set. Defaulting to a blank string.
1>The ESHOP_SERVICE_BUS_PASSWORD variable is not set. Defaulting to a blank string.
1>The INSTRUMENTATION_KEY variable is not set. Defaulting to a blank string.
1>The ORCHESTRATOR_TYPE variable is not set. Defaulting to a blank string.
1>The ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not set. Defaulting to a blank string.
1>The ESHOP_AZURE_STORAGE_CATALOG_KEY variable is not set. Defaulting to a blank string.
1>The ESHOP_AZUREFUNC_CAMPAIGN_DETAILS_URI variable is not set. Defaulting to a blank string.
1>The ESHOP_AZURE_STORAGE_MARKETING_NAME variable is not set. Defaulting to a blank string.
1>The ESHOP_AZURE_STORAGE_MARKETING_KEY variable is not set. Defaulting to a blank string.
1>Starting dockercompose900383749948941825_webshoppingagg_1 ...
1>dockercompose900383749948941825_sql.data_1 is up-to-date
1>Starting dockercompose900383749948941825_mobileshoppingapigw_1 ...
1>Starting dockercompose900383749948941825_mobilemarketingapigw_1 ...
1>dockercompose900383749948941825_webstatus_1 is up-to-date
1>Starting dockercompose900383749948941825_webshoppingapigw_1     ...
1>Starting dockercompose900383749948941825_webmarketingapigw_1    ...
1>dockercompose900383749948941825_nosql.data_1 is up-to-date
1>dockercompose900383749948941825_basket.data_1 is up-to-date
1>dockercompose900383749948941825_rabbitmq_1 is up-to-date
1>Starting dockercompose900383749948941825_mobileshoppingagg_1    ...
1>dockercompose900383749948941825_identity.api_1 is up-to-date
1>dockercompose900383749948941825_payment.api_1 is up-to-date
1>dockercompose900383749948941825_ordering.api_1 is up-to-date
1>dockercompose900383749948941825_locations.api_1 is up-to-date
1>dockercompose900383749948941825_catalog.api_1 is up-to-date
1>dockercompose900383749948941825_marketing.api_1 is up-to-date
1>dockercompose900383749948941825_basket.api_1 is up-to-date
1>dockercompose900383749948941825_webmvc_1 is up-to-date
1>dockercompose900383749948941825_webspa_1 is up-to-date
1>Starting dockercompose900383749948941825_mobileshoppingapigw_1  ... done
1>Starting dockercompose900383749948941825_webshoppingagg_1       ... done
1>Starting dockercompose900383749948941825_mobilemarketingapigw_1 ... done
1>Starting dockercompose900383749948941825_webshoppingapigw_1     ... done
1>Starting dockercompose900383749948941825_webmarketingapigw_1    ... done
1>Starting dockercompose900383749948941825_mobileshoppingagg_1    ... done
========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========`

Debug output is too large to be pasted, i've joined it in attached file.

[debug.txt](https://github.com/dotnet-architecture/eShopOnContainers/files/1950558/debug.txt)

**Comment by RajniKA** [comment]
Hi smeilhac,
If you want/need to run eShopOnContainers in Visual Studio 2017 15.6 RTM or previous, you'll need to use the code at the MASTER branch  which is the previous stable version of eShopOnContainers.
Due to the configuration used in docker-compose.yml file, VS 15.7 is needed to run the solution at DEV branch. Trying to run the solution from DEV branch in VS 15.6 (current RTM of Visual Studio 2017) will generate errors (complaining about invalid values in docker-compose file).

It was the issue due to that this project was not working on my system. But still not sure how it was working before days and all of sudden stop working.
So you can give it a try if it works for you.

Thanks
Rajni

**Comment by mvelosop** [comment]
Hi @smeilhac, I'm sorry I had to disconnect for a while!

From what I could see in the log, it certainly looks like an internal network problem, will try a couple of things to check.

In the meantime, as suggested by @CESARDELATORRE, could you try installing the latest version of Docker (18.03.1-ce-win65)?

BTW, please send the output of `docker container ls -a`?

**Comment by smeilhac** [comment]
Hi,

I made in a row an update to Visual Studio (15.7) and Docker (18.03.1-ce-win65) before looking answers here and now all is running. So it's at least one of the update who fix it.

Thanks for your time !

**Comment by mvelosop** [comment]
Glad it worked for you!, it was probably Docker, I also had some network issues that got solved when I upgraded.

Cheers!
