### ISSUE TITLE
Error in VS 2017 on fresh unedited clone

### ISSUE THREAD

**Issue by darnoldi** [dotnet-architecture/eShopOnContainers#585]
Hi there,
 I am getting:
`yaml.scanner.ScannerError: while scanning a simple key
  in "C:\Users\dave\Desktop\eShopOnContainers-dev\obj\Docker\docker-compose.vs.debug.g.yml", line 101, column 1

could not find expected ':'
  in "C:\Users\dave\Desktop\eShopOnContainers-dev\obj\Docker\docker-compose.vs.debug.g.yml", line 102, column 15.`

when executing a fresh unedited clone (both dev and master)

Am on windows 10 with Docker CE 18.03.0 and VS2017 15.6.6

Any suggestions?

Thanks

**Comment by mvelosop** [comment]
Hi @darnoldi, it looks like you are running the solution from VS, but for running the latest version of app from VS, you need to have at least VS 15.7 preview 2, as per https://github.com/dotnet-architecture/eShopOnContainers/wiki/02.-Setting-eShopOnContainers-in-a-Visual-Studio-2017-environment.

If you can't install the preview version for whatever reason, you could also try running the app from the CLI.

**Comment by darnoldi** [comment]
Thanks, I missed the preview requirement.

Will update.

Cheers

**Comment by mvelosop** [comment]
Will close then, just let me know if we have to open in again.

Cheers!
