### ISSUE TITLE
IOException: IDX10804: Unable to retrieve document from: 'http://10.0.75.1:5105/.well-known/openid-configuration'

### ISSUE THREAD

**Issue by hitaspdotnet** [dotnet-architecture/eShopOnContainers#587]
VS 15.7 preview 4
I'm very newbie in docker so try to running Step by Step with [this ](https://github.com/dotnet-architecture/eShopOnContainers/wiki/02.-Setting-eShopOnContainers-in-a-Visual-Studio-2017-environment) document. 

`http://localhost:5101/swagger/` - Done
`http://localhost:5102/swagger/` - Done
`http://localhost:5103/swagger/` - Done
`http://localhost:5104/swagger/` - Done

And MVC / SPA done, but `http://localhost:5100/Account/SingIn `not.

```
IOException: IDX10804: Unable to retrieve document from: 'http://10.0.75.1:5105/.well-known/openid-configuration'.
Microsoft.IdentityModel.Protocols.HttpDocumentRetriever+<GetDocumentAsync>d__8.MoveNext()

InvalidOperationException: IDX10803: Unable to obtain configuration from: 'http://10.0.75.1:5105/.well-known/openid-configuration'.
Microsoft.IdentityModel.Protocols.ConfigurationManager+<GetConfigurationAsync>d__24.MoveNext()
```

Stack:
```
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult()
System.Net.Http.DiagnosticsHandler+<SendAsync>d__2.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult()
System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__58.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult()
Microsoft.IdentityModel.Protocols.HttpDocumentRetriever+<GetDocumentAsync>d__8.MoveNext()
```

![image](https://user-images.githubusercontent.com/23167047/39095349-60eb3496-4654-11e8-80dd-792bf0201060.png)

![image](https://user-images.githubusercontent.com/23167047/39095364-95980b42-4654-11e8-8c65-c7ac1450bbe1.png)

**Comment by darnoldi** [comment]
Do you have any other antivirus or firewall running or only windows defender/firewall?

If you type 'docker ps' in a powershell window or command prompt, can you see a container with image  eshop/identity.api  running?

**Comment by hitaspdotnet** [comment]
@darnoldi Just Windows Defender. 

> can you see a container with image eshop/identity.api running?

Yes

**Comment by hitaspdotnet** [comment]
I have connected Vconnection to our team organization. It's can be problem?

**Comment by darnoldi** [comment]
Not sure about Vconnection maybe someone else can comment?

**Comment by Allann** [comment]
I too just started and whilst it took me most of the day yesterday to get a working environment (installed VS2017 enterprise 15.7 preview 4, docker for windows, etc), I managed to download the code and get the application running.
However, I was not able to make the login work, with similar issues.  I am at work at the moment so will post the issues when I get home in about 8 hours.

**Comment by mvelosop** [comment]
Hi @hitaspdotnet, what's VConnection? a VPN? 

If so, can you try running disconnected from the VPN?

Sometimes VPNs restrict computers to access only the corporate network and this can limit running Docker containers.

**Comment by hitaspdotnet** [comment]
@mvelosop Some issue without VConnectin.

**Comment by mvelosop** [comment]
Could you try setting it up to run from the cli?, as per https://github.com/dotnet-architecture/eShopOnContainers/wiki/03.-Setting-the-eShopOnContainers-solution-up-in-a-Windows-CLI-environment-(dotnet-CLI,-Docker-CLI-and-VS-Code)

**Comment by CESARDELATORRE** [comment]
I think you will have the same issue when deploying from the CLI. When you cannot access http://10.0.75.1:5105/.well-known/openid-configuration is usually because:
1. Environment/networking issues. If the firewall ports are open as specified in the Wiki, then it might be because of a corporate Proxy or VPN.
2. Because the Identity container didn't deploy right into Docker, but I don't think this is your case.

I would try the same machine where you have the issue but connected in a regular network with no VPNs or no Proxy.

**Comment by mvelosop** [comment]
Hi @hitaspdotnet, could you try this without the VPN client?

**Comment by CESARDELATORRE** [comment]
Closing this issue, for now, as it looks related to a local environment issue. Re-open if needed.

**Comment by matrixlane** [comment]
I've disabled the firewall for DockerNAT network in Public Profile and it works fine. Although I already have 5100-5150 ports open.
