### ISSUE TITLE
Unable to build docker-compose

### ISSUE THREAD

**Issue by codenshare** [dotnet-architecture/eShopOnContainers#589]
Building eShopOnContainers-ServicesAndWebApps solution leads to the following error, please advise. This is a no modified version of eShopOnContainers, running on VS 2017 and Win 10, Linux Docker container. Please help.

1>------ Build started: Project: docker-compose, Configuration: Debug Any CPU ------
1>docker-compose  -f "C:\Users\XXXXXXXX\Source\Repos\eShopOnContainers\docker-compose.yml" -f "C:\Users\XXXXXXXX\Source\Repos\eShopOnContainers\docker-compose.override.yml" -f "C:\Users\XXXXXXXX\Source\Repos\eShopOnContainers\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose4663731027203971149 config
1>yaml.scanner.ScannerError: while scanning a simple key
1>  in "C:\Users\XXXXXXXX\Source\Repos\eShopOnContainers\obj\Docker\docker-compose.vs.debug.g.yml", line 106, column 1
1>could not find expected ':'
1>  in "C:\Users\XXXXXXXX\Source\Repos\eShopOnContainers\obj\Docker\docker-compose.vs.debug.g.yml", line 107, column 15
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(314,5): error : yaml.scanner.ScannerError: while scanning a simple key
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(314,5): error :   in "C:\Users\XXXXXXXX\Source\Repos\eShopOnContainers\obj\Docker\docker-compose.vs.debug.g.yml", line 106, column 1
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(314,5): error : could not find expected ':'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(314,5): error :   in "C:\Users\XXXXXXXX\Source\Repos\eShopOnContainers\obj\Docker\docker-compose.vs.debug.g.yml", line 107, column 15.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(314,5): error : 
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(314,5): error : For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting
1>Done building project "docker-compose.dcproj" -- FAILED.
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========

**Comment by CESARDELATORRE** [comment]
What version of VS 2017 are you using?
Note the different requirements if using the code from our DEV branch or MASTER branch.
Check that out at the home page and the wiki.

**Comment by codenshare** [comment]
Thank you! I was using VS 2017 15.5.2 with Dev Branch code. I will switch to Master branch.

Thanks again!
