### ISSUE TITLE
Remove unused references to social logins from AccountController

### ISSUE THREAD

**Issue by bozhiqian** [dotnet-architecture/eShopOnContainers#590]
https://github.com/dotnet-architecture/eShopOnContainers/blob/26c3b58e66ef742d628c846ee72757bf6ca87254/src/Services/Identity/Identity.API/Controllers/AccountController.cs#L242

**Comment by mvelosop** [comment]
Hi @bozhiqian, thanks for your comment.
 
Actually eShopOnContainers doesn't have social logins enabled, so some lines were removed from the controller and this one, among others, were left behind, all social logins related actions should just not be there!

Anyway if that feature gets enabled it should probably be done using IdentityServer4.

**Comment by mvelosop** [comment]
Remove unused actions from AccountController.

**Comment by bozhiqian** [comment]
By the way, these models at https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src/Services/Identity/Identity.API/Models/ManageViewModels are meant to be used by ManageController which generated by MVC template when using individual user. These can be removed too if they are not meant to be included in this demo.  Thanks.

**Comment by mvelosop** [comment]
Thanks for the heads up @bozhiqian!
