### ISSUE TITLE
Update angular, bootstrap and other dependencies and devDependencies in package.json

### ISSUE THREAD

**Issue by IvanFarkas** [dotnet-architecture/eShopOnContainers#595]
Since Angular 6 is released it would be a good time to update npm packages in package.json.

- Angular to v6
- Bootstrap to v4.1.1
- ng-bootstrap to 2.0.0
- other dependencies and devDependencies

```
"dependencies": {
  "@angular/common": "^6.0.0",
  "@angular/compiler": "^6.0.0",
  "@angular/core": "^6.0.0",
  "@angular/forms": "^6.0.0",
  "@angular/http": "^6.0.0",
  "@angular/platform-browser": "^6.0.0",
  "@angular/platform-browser-dynamic": "^6.0.0",
  "@angular/router": "^6.0.0",
  "@ng-bootstrap/ng-bootstrap": "2.0.0",
  "bootstrap": "4.1.1",
  "core-js": "^2.5.5",
  "file-loader": "1.1.11",
  "font-awesome": "4.7.0",
  "isomorphic-fetch": "2.2.1",
  "normalize.css": "8.0.0",
  "preboot": "6.0.0-beta.3",
  "rxjs": "^6.1.0",
  "zone.js": "^0.8.26"
},
"devDependencies": {
  "@angular/cli": "^6.0.0",
  "@angular/compiler-cli": "^6.0.0",
  "@types/core-js": "0.9.46",
  "@types/hammerjs": "2.0.35",
  "@types/jasmine": "2.8.7",
  "@types/node": "~10.0.4",
  "@types/selenium-webdriver": "3.0.8",
  "codelyzer": "~4.3.0",
  "sass-lint": "1.12.1",
  "ts-helpers": "1.1.2",
  "ts-node": "~6.0.3",
  "tslint": "~5.10.0",
  "typedoc": "0.11.1",
  "typescript": "~2.8.3",
  "url-loader": "1.0.1"
}
```

**Comment by SeanFarrow** [comment]
I agree with this suggestion and am happy to take this on.
Aditionally, it would be ideal if the spa app didn't use visual studio at all or npm to build and just relied on the Angular cli.

**Comment by IvanFarkas** [comment]
@SeanFarrow I updated the ASP.NET Core 2.1 Angular project template generated code to **Angular 6** and **Bootstrap 4**. Find code at **[ng6b4](https://github.com/IvanFarkas/ng6b4)**.
The Side NavBar still needs some styling, but since it's only an example for the eShopOnContainers SPA, I did not bother.
Your contribution is greatly appreciated.

You might also want to explore Angular Material design.
Please look at **[Angular Bootstrap with Material Design](https://mdbootstrap.com/angular/)** template

**Comment by mvelosop** [comment]
Closing this issue as it's outdated, current Angular version is 6.1.4

**Comment by SeanFarrow** [comment]
This is not outdated, the currently shipping Angular version is 7.x.

**Comment by mvelosop** [comment]
Hi @SeanFarrow, the issue was about updating to Angular 6.0 so it's outdated regarding that.

It's also true that Bootstrap was not updated to 4.x, though.

Since this is mainly an architecture sample, updating to Bootstrap 4 has low priority but @CESARDELATORRE might give it a second thought.

**Comment by mvelosop** [comment]
**UPDATE**, I just realized the update to B4 is referenced in issue #388 and Ok'd by @CESARDELATORRE some time ago, may be there's need for someone to do it, although @raboud did it some time ago but was not PR'd.

May be it's just time to start applying the [Contributing guide](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/CONTRIBUTING.md).

Anyone interested?

**Comment by mvelosop** [comment]
Another update, there seems to be an issue migrating to B4 (#726)

**Comment by SeanFarrow** [comment]
I’m happy to update all js frameworks being used.
Given that Angular is being used and this is an architecture sample, has moving to a micro-frontend architecture been considered, using ngrx for state?

**Comment by mvelosop** [comment]
I think it would be best to create a new issue and start a conversation with @CESARDELATORRE and @ramonTC, who is perhaps the main maintainer of the web apps (among other parts) in this repo.
