### ISSUE TITLE
[Bug] Unhandled exception error happens the first time eShopOnContainers starts. When refresh from the browser, it works..

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#600]
This is a regression bug that started appearing with the last version of the code.
 Basically, an unhandled exception error happens the first time eShopOnContainers starts, for instance with F5 in VS. 
When you refresh from the browser, everything works ok, though..

It must be related to the fact that a container might still not be ready when starting the whole app and for this specific case, the Retries with Exponential Backoff are not working properly as they use to work.
We need to fix this issue/bug.

ERROR:
![image](https://user-images.githubusercontent.com/1712635/39901479-9997b1ac-547d-11e8-86cf-d3b0cac9fd6a.png)

An unhandled exception occurred while processing the request.
ArgumentNullException: Value cannot be null.
Parameter name: value
Newtonsoft.Json.JsonConvert.DeserializeObject(string value, Type type, JsonSerializerSettings settings)
Stack Query Cookies Headers 
ArgumentNullException: Value cannot be null. Parameter name: value
Newtonsoft.Json.JsonConvert.DeserializeObject(string value, Type type, JsonSerializerSettings settings)
Newtonsoft.Json.JsonConvert.DeserializeObject<T>(string value, JsonSerializerSettings settings)
Microsoft.eShopOnContainers.WebMVC.Services.CatalogService+<GetCatalogItems>d__5.MoveNext() in D:\GitRepos\eShopOnContainers-dev\src\Web\WebMVC\Services\CatalogService.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.eShopOnContainers.WebMVC.Controllers.CatalogController+<Index>d__2.MoveNext() in D:\GitRepos\eShopOnContainers-dev\src\Web\WebMVC\Controllers\CatalogController.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by mvelosop** [comment]
Closing this as it seems to be fixed now.

Once the mvc app started it could wait more than 40 seconds until all required services where available without displaying any error message.
