### ISSUE TITLE
Installing the optional Docker causes BSODs when running an emulator

### ISSUE THREAD

**Issue by CamelCaseMaster** [dotnet-architecture/eShopOnContainers#601]
I cloned this solution to take a look at it while reading the pdf file that comes with it [https://blog.xamarin.com/developing-enterprise-apps-using-xamarin-forms/](Link) & VS asked if I want to Install Docker which I did & restarted my computer(some "Critical updates were installed by Windows"). When I start run an app, once the vm starts I get a BSOD. Turning on Hyper-V off Bios fixes the issue. https://www.virtualbox.org/ticket/16801. I know this is unrelated but It might hinder people that are trying to get this.

**Comment by mvelosop** [comment]
Hi @CamelCaseMaster, I'm not familiar with the mobile app workload in VS, but AFAIK everything works as intended if you follow the installation guide on a clean machine: [02. Setting eShopOnContainers in a Visual Studio 2017 environment](https://github.com/dotnet-architecture/eShopOnContainers/wiki/02.-Setting-eShopOnContainers-in-a-Visual-Studio-2017-environment).

As I said, I'm not sure that's your case, but there's a [section in the guide about Docker configuration](https://github.com/dotnet-architecture/eShopOnContainers/wiki/02.-Setting-eShopOnContainers-in-a-Visual-Studio-2017-environment#installing-and-configuring-docker-in-your-development-machine) that highlights an incompatibility between Docker and Google's Android emulator that you must consider.

Hope that helps you to get going.

**Comment by mvelosop** [comment]
By the way, Docker is a must (not optional) in this reference app.
