### ISSUE TITLE
Missing swagger operationfilter for GlobalException?

### ISSUE THREAD

**Issue by Eneuman** [dotnet-architecture/eShopOnContainers#602]
Some of the services uses a GlobalExceptionFilter that returns a internal server error object.
There is currently no Swagger Operation decorator that adds Http Status Code 500 as a valid response.
This will make client generators (like auto rest and nswag) create code that does not handle the response correctly.

I can make a PR if you decide that this should be fixed.

**Comment by CESARDELATORRE** [comment]
We're in the middle of important updates heading to .NET Core 2.1 and ASP.NET Core 2.1.
We'll have it merged during May, please, let's make this exceptions improvements PR afterwards, around early June, ok?
Thanks a lot for your help! 👍

**Comment by Eneuman** [comment]
Sounds good, i'll put this on hold until then :)

**Comment by Eneuman** [comment]
Since, you are moving to .Net Core 2.1, maby it would be a better idea to create a new "ServerProblemDetails" response that conforms with RFC 7807. That would go well with the new "ValidationProblemDetails" introduced in .Core 2.1
The GlobalExceptionFilter can then return the "ServerProblemDetails" response and a "ServerProblemOperationFilter" can hook it up to Swagger, by adding the correct response type (500) for all Operations.

**Comment by mvelosop** [comment]
Hi @Eneuman, just wondering if you're still looking forward to get into this endeavour, now that the .NET Core 2.1 version of eShopOnContainers has been released. 

I'm about to get this issue into the [possible future feature section in the Roadmap](https://github.com/dotnet-architecture/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases#vnext) and close it, but just wanted to check first if you are still planning (and have time) to get into this.

Thanks.

**Comment by mvelosop** [comment]
Added issue to [possible feature section in the Roadmap](https://github.com/dotnet-architecture/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases#vnext)
