### ISSUE TITLE
Images and visio diagrams

### ISSUE THREAD

**Issue by TedMobile** [dotnet-architecture/eShopOnContainers#603]
Hi,
obviously its not an issue but more of a request,
Is it possible to include in the project those visio diagram that are in the book I Suspect they are visio diagrams ,rather than images.

thanks

**Comment by mvelosop** [comment]
Hi @TedMobile, they're actually PowerPoint drawings, but let's wait to have @CESARDELATORRE's response!

**Comment by CESARDELATORRE** [comment]
Yeah, they are PowerPoint diagrams. You have most of the microservice diagrams available in the Ignite session on Microservices I delivered (PPT download):
https://myignite.microsoft.com/sessions/55432?source=sessions

In any case, I'm updating quite a few diagrams including API Gateways and other assets, so when ready, I will also upload the PowerPoint deck into GitHub, along with the books. 👍

**Comment by TedMobile** [comment]
thanks!

**Comment by mvelosop** [comment]
Hi @TedMobile, @CESARDELATORRE uploaded the powerpoint decks to the repo not too long ago, you can get them here: https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/docs/Decks.

Best,

Closing this issue now.

**Comment by negim** [comment]
Could you please include the deck once again? The path is not accessible @mvelosop

**Comment by andresfelipe66** [comment]
Hello @CESARDELATORRE @mvelosop Could you please include the deck once again? The path is not accessible
Thanks!
