### ISSUE TITLE
[Question] Build docker images

### ISSUE THREAD

**Issue by vany0114** [dotnet-architecture/eShopOnContainers#605]
Guys, one question, how you built the images before pushing them on Docker registry? just build the solution on `release` mode, tag and push the image?

I have a doubt how to tell docker that takes the `aspnetcore` image instead of `aspnetcore-build`

Thanks in advance.

**Comment by vany0114** [comment]
I see, thanks for the explanation! So, it means, that when I build the image, either from CI/CD pipelines or in my local machine it always gonna use `microsoft/aspnetcore` as long as I have that one as `base` image right? just like that:

```
FROM microsoft/aspnetcore:2.0.5 AS base
WORKDIR /app
EXPOSE 80
...
```

**Comment by vany0114** [comment]
Thanks for the explanation @eiximenis 😃

**Comment by taomylife521** [comment]
![qq 20181224162834](https://user-images.githubusercontent.com/9649318/50394726-48d83e00-079a-11e9-923c-040bb471aaaa.png)
