### ISSUE TITLE
[Question] Duplicated images tagged  'none' after docker-compose build 

### ISSUE THREAD

**Issue by gItSpLasHeR** [dotnet-architecture/eShopOnContainers#607]
Following tutorial for **CLI and Windows based**, after 'docker-compose build' everything works fine.  however, execute 'docker images' and check the images list, there many images tagged as 'none', each of them takes about 2GB space. I think that should be 'asp.net core build', but as i read from the tutorial,  there should be only one image that takes 2GB space,  does anyone have idea about that ?
![Capture.PNG](https://i.loli.net/2018/05/18/5afeb96ad7709.png)

**Comment by mvelosop** [comment]
Hi @gItSpLasHeR those are intermediate images created when building another image, you might want to take a look at this post that although a bit dated explains the issue very well: https://www.projectatomic.io/blog/2015/07/what-are-docker-none-none-images/

Hope that helps.

**Comment by mvelosop** [comment]
Closing as this is not an issue with the application.
