### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by IvanFarkas** [dotnet-architecture/eShopOnContainers#608]
docker-compose error

```
docker-compose  -f "C:\Projects\NetCore\Architecture\eShopOnContainers\docker-compose.yml" -f "C:\Projects\NetCore\Architecture\eShopOnContainers\docker-compose.override.yml" -f "C:\Projects\NetCore\Architecture\eShopOnContainers\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose7035704071771701613 --no-ansi up -d --build --force-recreate --remove-orphans
```

returns this error

```
The ESHOP_SERVICE_BUS_USERNAME variable is not set. Defaulting to a blank string.
The ESHOP_SERVICE_BUS_PASSWORD variable is not set. Defaulting to a blank string.
The INSTRUMENTATION_KEY variable is not set. Defaulting to a blank string.
The ORCHESTRATOR_TYPE variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_CATALOG_KEY variable is not set. Defaulting to a blank string.
The ESHOP_AZUREFUNC_CAMPAIGN_DETAILS_URI variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_MARKETING_NAME variable is not set. Defaulting to a blank string.
The ESHOP_AZURE_STORAGE_MARKETING_KEY variable is not set. Defaulting to a blank string.
Building payment.api
Cannot locate specified Dockerfile: src\Services\Payment\Payment.API\Dockerfile

```

**Comment by IvanFarkas** [comment]
Fiddling with the docker environment format in `docker-compose.override.yml` did not fix the issue.
Waiting patiently for a **VS 2017 v15.8.0 Preview 1.1**,  **VS 2017 15.7.1** or **eShopOnContainers solution** fix.

**Comment by mvelosop** [comment]
Hi @IvanFarkas, I'm not having problem running this with VS 2017 15.7.1.

From the message it looks like the Dockerfile is missing.

Did you try if the app is running fine from the CLI?

**Comment by IvanFarkas** [comment]
@mvelosop I love the **"Works on my PC"** phrase. :-)
Clicking the Docker button on VS 2017 15.7.2 I get the error.
How do we fix this, please?

**Comment by mvelosop** [comment]
Hi @IvanFarkas, there's still the issue of getting Docker to run, haha!

**My environment::**
Windows 10 Pro (1709) 
VS 2017 15.7.2
Docker 18.03.1-ce-win65 (17513) (No Kubernetes)
sdk: 2.1.4

eShopOnContainers commit: 97b8fce7

Could be be too many preview components!

Have you run the app before or is this the first time on the computer you are trying to?

**Comment by IvanFarkas** [comment]
It ran OK about 2 weeks ago.
Since then I updated VS 2017, VS 2017 Preview, docker, .NET Core and got the latest from the repo.

**Comment by CESARDELATORRE** [comment]
I think there’s currently an issue in Docker EDGE channel.. are you using the stable or edge channel?

**Comment by IvanFarkas** [comment]
**Edge**. I updated the environment above.

**Comment by mvelosop** [comment]
I think this looks like an environment issue.

If it's possible for you, I would suggest to go back to stable version for Docker.

There should be no problem with the SDK, if you have 2.1.4 installed, because there's a **global.json** file for 2.1.4 in the solution folder.

**Comment by IvanFarkas** [comment]
Docker 18.03.1-ce (stable) build 9ee9f40 works.

**Comment by atifmir** [comment]
Hi I m having the same issue again , and I have same stable version of docker as above so this is not resolved

**Comment by mvelosop** [comment]
Hi @IvanFarkas,

I just tested the whole setup just three days ago for #640, so I'm pretty sure it works (at least on my machine 😉), but some Dockerfiles were updated recently.

Is the problem occurring with the same command you opened this issue?

**Comment by atifmir** [comment]
I get error when I try to run project from visual studio 2017 , got latest code installed docker and hit F5 (I make Docker as start up project as per instruction in the wiki) this is what I get
1>Building webmvc
1>Step 1/4 : ARG NODE_IMAGE=node:8.11
1>Step 2/4 : FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
1> ---> 76e0c475bb4c
1>Step 3/4 : WORKDIR /app
1> ---> Using cache
1> ---> 3c321f581e77
1>Step 4/4 : EXPOSE 80
1> ---> Using cache
1> ---> a9abfc10d570
1>Successfully built a9abfc10d570
1>Successfully tagged eshop/webmvc:dev
1>Recreating 82e60e829d07_dockercompose14430532785411818041_rabbitmq_1 ...
1>Recreating fa42acd599c9_dockercompose14430532785411818041_nosql.data_1 ...
1>Recreating 7f9734cf8e76_dockercompose14430532785411818041_sql.data_1   ...
1>Recreating 9e587cca7bac_dockercompose14430532785411818041_webspa_1     ...
1>Recreating c73de0498045_dockercompose14430532785411818041_webstatus_1  ...
1>Recreating cb0121df06a0_dockercompose14430532785411818041_basket.data_1 ...
1>Recreating fa42acd599c9_dockercompose14430532785411818041_nosql.data_1  ... error
1>ERROR: for fa42acd599c9_dockercompose14430532785411818041_nosql.data_1  Cannot start service nosql.data: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_nosql.data_1 (a3dbf3231adad67e1305973acc781444d14fbdd2b23b24497948ed6dc8d50a50): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:27017:tcp:172.20.0.2:27017: input/output error
1>Recreating 82e60e829d07_dockercompose14430532785411818041_rabbitmq_1    ... error
1>ERROR: for 82e60e829d07_dockercompose14430532785411818041_rabbitmq_1  Cannot start service rabbitmq: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_rabbitmq_1 (0a4efcacae23e077150ad1dd7a9b4f15a656e17aab82a6632f82b63d3fed30fa): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:15672:tcp:172.20.0.3:15672: input/output error
1>Recreating 7f9734cf8e76_dockercompose14430532785411818041_sql.data_1    ... error
1>ERROR: for 7f9734cf8e76_dockercompose14430532785411818041_sql.data_1  Cannot start service sql.data: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_sql.data_1 (62159dcc8597f6a2ef6d7527393991b29271113f74977517431a5a5b6e2e82d0): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:5433:tcp:172.20.0.4:1433: input/output error
1>Recreating c73de0498045_dockercompose14430532785411818041_webstatus_1   ... error
1>ERROR: for c73de0498045_dockercompose14430532785411818041_webstatus_1  Cannot start service webstatus: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_webstatus_1 (77ba9f93490ae9c1b132b9bc63a90fee88bd5a04c74ecb21c1a550aa5bb369d4): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:5107:tcp:172.20.0.2:80: input/output error
1>Recreating 9e587cca7bac_dockercompose14430532785411818041_webspa_1      ... error
1>ERROR: for 9e587cca7bac_dockercompose14430532785411818041_webspa_1  Cannot start service webspa: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_webspa_1 (2bd0af5f095f4b036545ba73703da2bd0bbae495870671077d91e9f6168672ba): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:5104:tcp:172.20.0.3:80: input/output error
1>Recreating cb0121df06a0_dockercompose14430532785411818041_basket.data_1 ... error
1>ERROR: for cb0121df06a0_dockercompose14430532785411818041_basket.data_1  Cannot start service basket.data: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_basket.data_1 (1869f160cf21d6b7bcf55a0ecf64da6a7f9ce01261cdbe5cf1b89edbabb6acfe): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:6379:tcp:172.20.0.4:6379: input/output error
1>ERROR: for nosql.data  Cannot start service nosql.data: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_nosql.data_1 (a3dbf3231adad67e1305973acc781444d14fbdd2b23b24497948ed6dc8d50a50): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:27017:tcp:172.20.0.2:27017: input/output error
1>ERROR: for rabbitmq  Cannot start service rabbitmq: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_rabbitmq_1 (0a4efcacae23e077150ad1dd7a9b4f15a656e17aab82a6632f82b63d3fed30fa): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:15672:tcp:172.20.0.3:15672: input/output error
1>ERROR: for sql.data  Cannot start service sql.data: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_sql.data_1 (62159dcc8597f6a2ef6d7527393991b29271113f74977517431a5a5b6e2e82d0): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:5433:tcp:172.20.0.4:1433: input/output error
1>ERROR: for webstatus  Cannot start service webstatus: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_webstatus_1 (77ba9f93490ae9c1b132b9bc63a90fee88bd5a04c74ecb21c1a550aa5bb369d4): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:5107:tcp:172.20.0.2:80: input/output error
1>ERROR: for webspa  Cannot start service webspa: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_webspa_1 (2bd0af5f095f4b036545ba73703da2bd0bbae495870671077d91e9f6168672ba): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:5104:tcp:172.20.0.3:80: input/output error
1>ERROR: for basket.data  Cannot start service basket.data: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_basket.data_1 (1869f160cf21d6b7bcf55a0ecf64da6a7f9ce01261cdbe5cf1b89edbabb6acfe): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:6379:tcp:172.20.0.4:6379: input/output error
1>Encountered errors while bringing up the project.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : The ESHOP_SERVICE_BUS_USERNAME variable is not set. Defaulting to a blank string.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : The ESHOP_SERVICE_BUS_PASSWORD variable is not set. Defaulting to a blank string.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : The INSTRUMENTATION_KEY variable is not set. Defaulting to a blank string.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : The ORCHESTRATOR_TYPE variable is not set. Defaulting to a blank string.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : The ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not set. Defaulting to a blank string.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : The ESHOP_AZURE_STORAGE_CATALOG_KEY variable is not set. Defaulting to a blank string.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : The ESHOP_AZUREFUNC_CAMPAIGN_DETAILS_URI variable is not set. Defaulting to a blank string.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : The ESHOP_AZURE_STORAGE_MARKETING_NAME variable is not set. Defaulting to a blank string.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : The ESHOP_AZURE_STORAGE_MARKETING_KEY variable is not set. Defaulting to a blank string.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Removing dockercompose14430532785411818041_nosql.data_1
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Removing dockercompose14430532785411818041_basket.data_1
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Removing dockercompose14430532785411818041_sql.data_1
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Removing dockercompose14430532785411818041_rabbitmq_1
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Removing dockercompose14430532785411818041_webstatus_1
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Removing dockercompose14430532785411818041_webspa_1
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Building identity.api
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Building locations.api
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Building catalog.api
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Building marketing.api
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Building payment.api
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Building webstatus
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Building ordering.backgroundtasks
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Building ordering.api
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Building webspa
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Building basket.api
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Building mobileshoppingapigw
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Building mobilemarketingapigw
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Building webshoppingagg
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Building mobileshoppingagg
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Building webmarketingapigw
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Building ordering.signalrhub
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Building webshoppingapigw
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Building webmvc
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Recreating 82e60e829d07_dockercompose14430532785411818041_rabbitmq_1 ... 
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Recreating fa42acd599c9_dockercompose14430532785411818041_nosql.data_1 ... 
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Recreating 7f9734cf8e76_dockercompose14430532785411818041_sql.data_1   ... 
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Recreating 9e587cca7bac_dockercompose14430532785411818041_webspa_1     ... 
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Recreating c73de0498045_dockercompose14430532785411818041_webstatus_1  ... 
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Recreating cb0121df06a0_dockercompose14430532785411818041_basket.data_1 ... 
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Recreating fa42acd599c9_dockercompose14430532785411818041_nosql.data_1  ... error
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : ERROR: for fa42acd599c9_dockercompose14430532785411818041_nosql.data_1  Cannot start service nosql.data: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_nosql.data_1 (a3dbf3231adad67e1305973acc781444d14fbdd2b23b24497948ed6dc8d50a50): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:27017:tcp:172.20.0.2:27017: input/output error
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Recreating 82e60e829d07_dockercompose14430532785411818041_rabbitmq_1    ... error
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : ERROR: for 82e60e829d07_dockercompose14430532785411818041_rabbitmq_1  Cannot start service rabbitmq: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_rabbitmq_1 (0a4efcacae23e077150ad1dd7a9b4f15a656e17aab82a6632f82b63d3fed30fa): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:15672:tcp:172.20.0.3:15672: input/output error
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Recreating 7f9734cf8e76_dockercompose14430532785411818041_sql.data_1    ... error
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : ERROR: for 7f9734cf8e76_dockercompose14430532785411818041_sql.data_1  Cannot start service sql.data: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_sql.data_1 (62159dcc8597f6a2ef6d7527393991b29271113f74977517431a5a5b6e2e82d0): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:5433:tcp:172.20.0.4:1433: input/output error
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Recreating c73de0498045_dockercompose14430532785411818041_webstatus_1   ... error
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : ERROR: for c73de0498045_dockercompose14430532785411818041_webstatus_1  Cannot start service webstatus: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_webstatus_1 (77ba9f93490ae9c1b132b9bc63a90fee88bd5a04c74ecb21c1a550aa5bb369d4): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:5107:tcp:172.20.0.2:80: input/output error
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Recreating 9e587cca7bac_dockercompose14430532785411818041_webspa_1      ... error
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : ERROR: for 9e587cca7bac_dockercompose14430532785411818041_webspa_1  Cannot start service webspa: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_webspa_1 (2bd0af5f095f4b036545ba73703da2bd0bbae495870671077d91e9f6168672ba): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:5104:tcp:172.20.0.3:80: input/output error
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Recreating cb0121df06a0_dockercompose14430532785411818041_basket.data_1 ... error
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : ERROR: for cb0121df06a0_dockercompose14430532785411818041_basket.data_1  Cannot start service basket.data: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_basket.data_1 (1869f160cf21d6b7bcf55a0ecf64da6a7f9ce01261cdbe5cf1b89edbabb6acfe): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:6379:tcp:172.20.0.4:6379: input/output error
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : ERROR: for nosql.data  Cannot start service nosql.data: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_nosql.data_1 (a3dbf3231adad67e1305973acc781444d14fbdd2b23b24497948ed6dc8d50a50): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:27017:tcp:172.20.0.2:27017: input/output error
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : ERROR: for rabbitmq  Cannot start service rabbitmq: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_rabbitmq_1 (0a4efcacae23e077150ad1dd7a9b4f15a656e17aab82a6632f82b63d3fed30fa): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:15672:tcp:172.20.0.3:15672: input/output error
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : ERROR: for sql.data  Cannot start service sql.data: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_sql.data_1 (62159dcc8597f6a2ef6d7527393991b29271113f74977517431a5a5b6e2e82d0): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:5433:tcp:172.20.0.4:1433: input/output error
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : ERROR: for webstatus  Cannot start service webstatus: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_webstatus_1 (77ba9f93490ae9c1b132b9bc63a90fee88bd5a04c74ecb21c1a550aa5bb369d4): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:5107:tcp:172.20.0.2:80: input/output error
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : ERROR: for webspa  Cannot start service webspa: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_webspa_1 (2bd0af5f095f4b036545ba73703da2bd0bbae495870671077d91e9f6168672ba): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:5104:tcp:172.20.0.3:80: input/output error
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : ERROR: for basket.data  Cannot start service basket.data: driver failed programming external connectivity on endpoint dockercompose14430532785411818041_basket.data_1 (1869f160cf21d6b7bcf55a0ecf64da6a7f9ce01261cdbe5cf1b89edbabb6acfe): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:6379:tcp:172.20.0.4:6379: input/output error
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Encountered errors while bringing up the project..
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : 
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting
1>Done building project "docker-compose.dcproj" -- FAILED.
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========

**Comment by atifmir** [comment]
installed Stable docker version got latest and tried again but no avail , added error is missing docker compose file in payment api 
PS C:\Code\eShopOnContainers> docker-compose build
WARNING: The ESHOP_SERVICE_BUS_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_SERVICE_BUS_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The INSTRUMENTATION_KEY variable is not set. Defaulting to a blank string.
WARNING: The ORCHESTRATOR_TYPE variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_CATALOG_KEY variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZUREFUNC_CAMPAIGN_DETAILS_URI variable is not set. Defaulting to a blank string
WARNING: The ESHOP_AZURE_STORAGE_MARKETING_NAME variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_MARKETING_KEY variable is not set. Defaulting to a blank string.
basket.data uses an image, skipping
sql.data uses an image, skipping
nosql.data uses an image, skipping
rabbitmq uses an image, skipping
Building payment.api
ERROR: Cannot locate specified Dockerfile: src\Services\Payment\Payment.API\Dockerfile

**Comment by mvelosop** [comment]
I could get it running again from VS with [F5].

There seems to be a network issue in the previous listing.

I think it would be good to start from a clean state.

If you can uninstall Docker and reinstall it back again then that's the easiest way to reset Docker.

If not, you could try this procedure to delete everything you don't care about in Docker:

1. Stop all containers:  
`docker container stop $(docker container ls -q)`

2. Start any container you want to keep e.g. I use **seq** (logs sink) in a container for development

3. Delete (almost) everything  not related to running containers:  
`docker system prune -a`

4. Delete unused volumes:  
`docker volume rm $(docker volume ls -q -f dangling=true)`

Step 3 also deletes unused networks in Docker.

Hope this helps.

**Comment by mvelosop** [comment]
BTW @atifmir I just realized you piggybacked your problem into this issue and it is probably a different context (and problem), next time it's better (and more polite) to create a new issue.

**Comment by atifmir** [comment]
@mvelosop yes sorry will do next time

**Comment by atifmir** [comment]
@mvelosop I have reinstalled docker but to no avail

**Comment by atifmir** [comment]
@mvelosop Thanks so much for suggesting to reinstall I was quick to say reinstall did not work but after reinstall , reconfig and re-login I hit [F5] and everything built and worked like a charm!!! I still got some warning about service bus username but I suppose they could be ignore for now? Solution however now builds and works like a charm.
Again sorry for my impatience and creating issue in wrong place without much thought about the problem context.
Thanks and best regards

**Comment by mvelosop** [comment]
Good to know @atifmir!
