### ISSUE TITLE
[Feature Request] API Versioning

### ISSUE THREAD

**Issue by benbuckland** [dotnet-architecture/eShopOnContainers#609]
Hey there, I have a production system running using a lot of the architecture from this reference. I am at a stage where I need to handle API Versioning. Any plans to implement API versioning? 

I came across this which looks pretty solid [https://github.com/Microsoft/aspnet-api-versioning](https://github.com/Microsoft/aspnet-api-versioning)

Cheers

**Comment by CESARDELATORRE** [comment]
Yeah.. That's good feedback. Our current API versioning is super basic, just based on the version, explicit in the URL. http://xxxx/v1/xxxx
There are more advanced and flexible ways to handle versioning. 
I have added this topic as a possible feature to implement in the [future roadmap](https://github.com/dotnet-architecture/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases) 

If you go ahead and implement your versioning system before we do, please, send us your feedback on your final selected approach so we can take it into account, ok? 

Thanks for the feedback! 👍
