### ISSUE TITLE
[BUG] When registering a new user, its created Orders are not created/shown for that new user

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#611]
This is a bug that needs further research. Could be just a bug in UI or internal in the business logic.
From an UI point of view, when you register/create a new user and create an order, you don't see that order created but see the orders from the demouser@microsoft.com

![image](https://user-images.githubusercontent.com/1712635/40337527-f9265560-5d24-11e8-998a-5d5b212cff09.png)

**Comment by CESARDELATORRE** [comment]
The query is fixed now in the order's page, but it is still not working properly the whole scenario.
When creating an order **with a "custom" registered user**, the order is not created/appearing in the order page, neither showing up any SignalR notification. 
If using the by-default user, it is working ok, though.

**Comment by mvelosop** [comment]
Yeah, that's something that was pending, right now we are just logging the errors.

You might want to take a look at some code I was experimenting with: https://github.com/mvelosop/Microflow-X/blob/master/src/Tenants/App/Behaviors/ValidatorBehavior.cs

But would probably mean a non-trivial change.

**Comment by mvelosop** [comment]
Closing this, as it's working properly now.
