### ISSUE TITLE
[QUESTION] Partitioning service on Service Fabric

### ISSUE THREAD

**Issue by vany0114** [dotnet-architecture/eShopOnContainers#614]
Hi guys,

I was been trying to deploy the Web APIs projects as partitioned services on Service Fabric but it doesn't work, can you provide an example, please.

This is the error: 
```
The Cluster Resource Manager was unable to find a placement for one or more of the Service's Replicas:
Secondary replica could not be placed due to the following constraints and properties:  
TargetReplicaSetSize: 2
```

This is my configuration:
```
<Service Name="xxx" ServicePackageActivationMode="ExclusiveProcess">
      <StatelessService ServiceTypeName="xxxType" InstanceCount="[xxx_InstanceCount]">
        <UniformInt64Partition PartitionCount="4" LowKey="1" HighKey="10" />
      </StatelessService>
</Service>
```

Thanks in advance!

**Comment by CESARDELATORRE** [comment]
@vany0114 Hi! - Service Fabric Reliable Services and partitioned services (usually for Stateful Reliable Services) are not currently in the scope of eShopOnContainers. I suggest you post this question in any of the Service Fabric Repos at GitHub:
https://github.com/Azure-Samples/service-fabric-dotnet-core-getting-started 

About reliable collections and partitions, you have further info here:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-reliable-collections 

Closing this issue as it is not, initially, related to eShopOnContainers.
