### ISSUE TITLE
Getting error yml while building 

### ISSUE THREAD

**Issue by sumitchavan** [dotnet-architecture/eShopOnContainers#617]
1>------ Build started: Project: docker-compose, Configuration: Debug Any CPU ------
1>docker ps --filter "status=running" --filter "name=dockercompose1295569064100482090_basket.api_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose1295569064100482090_catalog.api_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose1295569064100482090_identity.api_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose1295569064100482090_locations.api_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose1295569064100482090_marketing.api_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose1295569064100482090_mobilemarketingapigw_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose1295569064100482090_mobileshoppingagg_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose1295569064100482090_mobileshoppingapigw_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose1295569064100482090_ordering.api_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose1295569064100482090_ordering.backgroundtasks_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose1295569064100482090_ordering.signalrhub_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose1295569064100482090_payment.api_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose1295569064100482090_webmarketingapigw_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose1295569064100482090_webmvc_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose1295569064100482090_webshoppingagg_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose1295569064100482090_webshoppingapigw_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose1295569064100482090_webspa_" --format {{.ID}} -n 1
1>docker ps --filter "status=running" --filter "name=dockercompose1295569064100482090_webstatus_" --format {{.ID}} -n 1
1>EventBus -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\BuildingBlocks\EventBus\EventBus\bin\Debug\netstandard2.0\EventBus.dll
1>Microsoft.Extensions.HealthChecks -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\BuildingBlocks\HealthChecks\src\Microsoft.Extensions.HealthChecks\bin\Debug\netstandard2.0\Microsoft.Extensions.HealthChecks.dll
1>EventBusRabbitMQ -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\BuildingBlocks\EventBus\EventBusRabbitMQ\bin\Debug\netstandard2.0\EventBusRabbitMQ.dll
1>EventBusServiceBus -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\BuildingBlocks\EventBus\EventBusServiceBus\bin\Debug\netstandard2.0\EventBusServiceBus.dll
1>Microsoft.AspNetCore.HealthChecks -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\BuildingBlocks\HealthChecks\src\Microsoft.AspNetCore.HealthChecks\bin\Debug\netstandard2.0\Microsoft.AspNetCore.HealthChecks.dll
1>Basket.API -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\Services\Basket\Basket.API\bin\Debug\netcoreapp2.0\Basket.API.dll
1>IntegrationEventLogEF -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\BuildingBlocks\EventBus\IntegrationEventLogEF\bin\Debug\netstandard2.0\IntegrationEventLogEF.dll
1>Microsoft.Extensions.HealthChecks.AzureStorage -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\BuildingBlocks\HealthChecks\src\Microsoft.Extensions.HealthChecks.AzureStorage\bin\Debug\netstandard2.0\Microsoft.Extensions.HealthChecks.AzureStorage.dll
1>Microsoft.Extensions.HealthChecks.SqlServer -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\BuildingBlocks\HealthChecks\src\Microsoft.Extensions.HealthChecks.SqlServer\bin\Debug\netstandard2.0\Microsoft.Extensions.HealthChecks.SqlServer.dll
1>WebHost.Customization -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\BuildingBlocks\WebHostCustomization\WebHost.Customization\bin\Debug\netcoreapp2.0\WebHost.Customization.dll
1>Catalog.API -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\Services\Catalog\Catalog.API\bin\Debug\netcoreapp2.0\Catalog.API.dll
1>AggregatesModel\OrderAggregate\Order.cs(31,22): warning CS0414: The field 'Order._isDraft' is assigned but its value is never used
1>Ordering.Domain -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\Services\Ordering\Ordering.Domain\bin\Debug\netstandard2.0\Ordering.Domain.dll
1>Done building project "Ordering.Domain.csproj".
1>Ordering.Infrastructure -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\Services\Ordering\Ordering.Infrastructure\bin\Debug\netstandard2.0\Ordering.Infrastructure.dll
1>Application\Commands\CreateOrderDraftCommandHandler.cs(19,43): warning CS0169: The field 'CreateOrderDraftCommandHandler._orderRepository' is never used
1>Application\DomainEventHandlers\OrderCancelled\OrderCancelledDomainEventHandler.cs(20,59): warning CS0649: Field 'OrderCancelledDomainEventHandler._orderingIntegrationEventService' is never assigned to, and will always have its default value null
1>Ordering.API -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\Services\Ordering\Ordering.API\bin\Debug\netcoreapp2.0\Ordering.API.dll
1>Done building project "Ordering.API.csproj".
1>Resilience.Http -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\BuildingBlocks\Resilience\Resilience.Http\bin\Debug\netstandard2.0\Resilience.Http.dll
1>
1>Bundler: Begin processing bundleconfig.json
1>Bundler: Done processing bundleconfig.json
1>Services\BasketService.cs(23,33): warning CS0169: The field 'BasketService._bffUrl' is never used
1>WebMVC -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\Web\WebMVC\bin\Debug\netcoreapp2.0\WebMVC.dll
1>Done building project "WebMVC.csproj".
1>Identity.API -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\Services\Identity\Identity.API\bin\Debug\netcoreapp2.0\Identity.API.dll
1>WebSPA -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\Web\WebSPA\bin\Debug\netcoreapp2.0\WebSPA.dll
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\TypeScript\Microsoft.TypeScript.targets(67,5): warning : Your project does not specify a TypeScriptToolsVersion. The latest available TypeScript compiler will be used (2.6). To remove this warning, set TypeScriptToolsVersion to a specific version or "Latest" to always select the latest compiler.
1>Done building project "WebSPA.csproj".
1>WebStatus -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\Web\WebStatus\bin\Debug\netcoreapp2.0\WebStatus.dll
1>Payment.API -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\Services\Payment\Payment.API\bin\Debug\netcoreapp2.0\Payment.API.dll
1>Locations.API -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\Services\Location\Locations.API\bin\Debug\netcoreapp2.0\Locations.API.dll
1>Marketing.API -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\Services\Marketing\Marketing.API\bin\Debug\netcoreapp2.0\Marketing.API.dll
1>Startup.cs(54,33): warning CS0219: The variable 'i' is assigned but its value is never used
1>Startup.cs(52,60): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>Startup.cs(58,33): warning CS0219: The variable 'i' is assigned but its value is never used
1>Startup.cs(56,54): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>Startup.cs(63,33): warning CS0219: The variable 'i' is assigned but its value is never used
1>Startup.cs(61,55): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>OcelotApiGw -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\ApiGateways\ApiGw-Base\bin\Debug\netcoreapp2.0\OcelotApiGw.dll
1>Done building project "OcelotApiGw.csproj".
1>Startup.cs(97,29): warning CS0219: The variable 'i' is assigned but its value is never used
1>Startup.cs(95,56): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>Startup.cs(101,29): warning CS0219: The variable 'i' is assigned but its value is never used
1>Startup.cs(99,50): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>Services\BasketService.cs(44,17): warning CS0219: The variable 'i' is assigned but its value is never used
1>Mobile.Shopping.HttpAggregator -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\ApiGateways\Mobile.Bff.Shopping\aggregator\bin\Debug\netcoreapp2.0\Mobile.Shopping.HttpAggregator.dll
1>Done building project "Mobile.Shopping.HttpAggregator.csproj".
1>Services\BasketService.cs(44,17): warning CS0219: The variable 'i' is assigned but its value is never used
1>Startup.cs(97,29): warning CS0219: The variable 'i' is assigned but its value is never used
1>Startup.cs(95,56): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>Startup.cs(101,29): warning CS0219: The variable 'i' is assigned but its value is never used
1>Startup.cs(99,50): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>Web.Shopping.HttpAggregator -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\ApiGateways\Web.Bff.Shopping\aggregator\bin\Debug\netcoreapp2.0\Web.Shopping.HttpAggregator.dll
1>Done building project "Web.Shopping.HttpAggregator.csproj".
1>Ordering.BackgroundTasks -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\Services\Ordering\Ordering.BackgroundTasks\bin\Debug\netcoreapp2.0\Ordering.BackgroundTasks.dll
1>Ordering.SignalrHub -> D:\sumit\Research\MS-eshop\eShopOnContainers\src\Services\Ordering\Ordering.SignalrHub\bin\Debug\netcoreapp2.0\Ordering.SignalrHub.dll
1>docker-compose  -f "D:\sumit\Research\MS-eshop\eShopOnContainers\docker-compose.yml" -f "D:\sumit\Research\MS-eshop\eShopOnContainers\docker-compose.override.yml" -f "D:\sumit\Research\MS-eshop\eShopOnContainers\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose1295569064100482090 --no-ansi config
1>yaml.scanner.ScannerError: while scanning a simple key
1>  in "D:\sumit\Research\MS-eshop\eShopOnContainers\obj\Docker\docker-compose.vs.debug.g.yml", line 101, column 1
1>could not find expected ':'
1>  in "D:\sumit\Research\MS-eshop\eShopOnContainers\obj\Docker\docker-compose.vs.debug.g.yml", line 102, column 15
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : yaml.scanner.ScannerError: while scanning a simple key
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error :   in "D:\sumit\Research\MS-eshop\eShopOnContainers\obj\Docker\docker-compose.vs.debug.g.yml", line 101, column 1
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : could not find expected ':'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error :   in "D:\sumit\Research\MS-eshop\eShopOnContainers\obj\Docker\docker-compose.vs.debug.g.yml", line 102, column 15.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : 
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting
1>Done building project "docker-compose.dcproj" -- FAILED.
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========

I am getting above error while doing Ctrl+F5 via VS 2017 on windows 10 machine having docker installed.

Let me know if you need any more information.

Not sure if the target machine value is what causing the issue? as i m on my windows machine.

![image](https://user-images.githubusercontent.com/16136125/40533339-0ae9f11e-6020-11e8-9dac-35e520b6d7f3.png)

**Comment by mvelosop** [comment]
Hi @sumitchavan, this usually works fine when following the instructions on the wiki, can you double check you have setup your environment according to this?: https://github.com/dotnet-architecture/eShopOnContainers/wiki/02.-Setting-eShopOnContainers-in-a-Visual-Studio-2017-environment

**Comment by mvelosop** [comment]
Closed the issue as it became stale, will reopen if needed.
