### ISSUE TITLE
Upgrade to .NET Core 2.1 (along with EF, SignalR, etc.)?

### ISSUE THREAD

**Issue by mzhukovs** [dotnet-architecture/eShopOnContainers#618]
Any plans for this now that it's in RC1?

**Comment by CESARDELATORRE** [comment]
It is already done :) we have it in the **netcore21rc** branch.
There's a SignalR microservice/Hub showing the order's status changes plus other important .NET Core 2.1 features like HttpClientFactory.
We'll upgrade to RTM/GA and merge into DEV in a few days. 👍
