### ISSUE TITLE
[BUG] Xamarin Applications - Appearing duplicate products in basket after first checkout

### ISSUE THREAD

**Issue by joaoGoncalves81** [dotnet-architecture/eShopOnContainers#621]
After adding products to basket and do a first checkout and then continue to add products to basket, the products will appear duplicate.

I guess the problem is in MessagingCenter unsubcribe/subscribe methods in BasketViewModel.

The callback method of the Subscribe in MessagingCenter "AddProduct" is executing more than once in BasketViewModel when user tap on add product button in catalog view. (this only happens after first checkout complete)
This will add more than one product to basket when the user tap on add product on catalog view.

You can try with mock services or real services:

1. Add products to basket
2. Go to basket and checkout
3. Return to catalog view
4. Add one product
5. Go to basket and you will see duplicate items

I tried only on Windows applicaton, but maybe it will happen in Android.
Can you help?

**Comment by CESARDELATORRE** [comment]
@joaofbbg - Thanks for the feedback, we’ll review the issue and respond as soon as possible.
Thanks,

**Comment by mvelosop** [comment]
Hi @joaofbbg, I've been trying to reproduce this and just can't get to this bug, neither on Windows UWP, MVC or SPA.

What is happening, though, is that if you click twice in the same catalog item, it gets added as two separate Order Items, but are summed up on checkout so the order appears as expected: one item, qty: 2.

Could you please double check if this is the situation you are experiencing?

Thanks.

**Comment by joaofbbg** [comment]
Hi @mvelosop , I tried again on Windows UWP after a git pull on dev, and I still have this issue.
Can you please check this video: https://vimeo.com/275411400
You will see after the first order, the items appear in basket are not correct (I'm clicking just once on the catalog) 
Just one side note: on the video you don't see the checkout successful box, but it appear!

**Comment by joaofbbg** [comment]
Hi @mvelosop, I didn't try with Docker, I just Run in Debug Mode, the eShopOnContainers.Windows Project from Visual Studio 2017 and use the Mock Services.

Should I try with Docker? 

New steps to reproduce this errors:

1. Go Cart View and complete a Order.
2. Go to Cart to check if it's empty.
3. Go to catalog and add products
4. Swap between cart and catalog a couple of times
5. Add more products;
6. Check if cart is consistent with the products that you added.

I put video on my google drive now, try this ink: https://drive.google.com/file/d/1ikpQE-37lyOR6k0fI0_sR48UsoOVDYzJ/view

 Thanks

**Comment by CESARDELATORRE** [comment]
@joaofbbg 👍 Thanks for the feedback. We'll review the issue (looks like a clear bug) and fix it when possible.

**Comment by mvelosop** [comment]
Closing this issue a stale.
