### ISSUE TITLE
Fail to debug console program

### ISSUE THREAD

**Issue by polei** [dotnet-architecture/eShopOnContainers#625]
`using System;

namespace consoleTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}`

The error info is follow:

Last login: Mon Jun  4 22:07:36 on ttys002
chenshuangyudeMacBook-Pro:~ csy$ bash -c 'clear; cd "/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/AddIns/DotNetCore.Debugger/Adapter/"; "/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/AddIns/DotNetCore.Debugger/Adapter/vsdbg" --interpreter=vscode --connection=/var/folders/w5/km0skm7d2gs6fy9r_9pmlqx40000gn//CoreFxPipe_vsdbg-ui-910e4124bb7e4c2db9b261610f0024c9; echo $? > /var/folders/w5/km0skm7d2gs6fy9r_9pmlqx40000gn//tmp50c5efc3.tmp; echo; read -p "Press any key to continue..." -n1; exit'; exit

.....
.....
.....
....
Error: Unable to connect to the specified connection id.

Press any key to continue...

**Comment by mvelosop** [comment]
Closing this issue as it's not related to eShopOnContainers.
