### ISSUE TITLE
[BUG] After explicit logout, hit on login, then it is automatically recognized instead of showing the login page 

### ISSUE THREAD

**Issue by BrunoLopes** [dotnet-architecture/eShopOnContainers#626]
Hi guys, I can't get login page after a forced logout, it's getting logging in automatically in a mvc client application with hybrid grant type.

**Comment by CESARDELATORRE** [comment]
Yeah, this is a known issue/bug we'll need to fix when possible. Thanks for the feedback.

**Comment by BrunoLopes** [comment]
I wish you guys priorize this as soon as possible.

**Comment by Devs4life** [comment]
You should SignOut Identity on Identity.API
Ex: _signInManager.SignOutAsync();

**Comment by mvelosop** [comment]
Closing this issue as the fix is confirmed.
