### ISSUE TITLE
Volumn sharing is not enabled error

### ISSUE THREAD

**Issue by harrchen88** [dotnet-architecture/eShopOnContainers#631]
Running vs 15.7.3 in windows 10 in admin mode, build the web and service solution file.  However, when trying to start debugging, got the error  even though I have the sharing (also tried reset credentials).
![volumesharingerror](https://user-images.githubusercontent.com/39616938/41197408-16965b16-6c90-11e8-8048-59d85f61b486.JPG)
I can run the docker command successfully with the following results:
![volumesharingerror2](https://user-images.githubusercontent.com/39616938/41197445-86b8266c-6c91-11e8-9dc1-6fa666f399c7.JPG)

**Comment by CESARDELATORRE** [comment]
Looks like a Docker environment issue..
Do you have that same issue with any other app like a hello world in VS?
If it happens the same way with any app, try uninstalling and reinstalling DOCKER FOR WINDOWS, it’ll be quick.

**Comment by CESARDELATORRE** [comment]
Closing this issue, for now.
