### ISSUE TITLE
Will the gitlab CI / CD use document be provided?

### ISSUE THREAD

**Issue by dmpx** [dotnet-architecture/eShopOnContainers#633]
**.gitlab-ci.yml**

variables:
  BUILD_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  - release

before_script:
  - apk add --update py-pip && pip install docker-compose # install docker-compose
  - docker info
  - docker-compose --version
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY_IMAGE

# after_script:
#   - docker ps -a | grep "Exited" | awk '{print $1 }'|xargs docker stop
#   - docker ps -a | grep "Exited" | awk '{print $1 }'|xargs docker rm
#   - docker images|grep none|awk '{print $3 }'|xargs docker rmi

job build:
  stage: build
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
    - docker push $BUILD_IMAGE
  tags:
    - eshop_service_build
  only:
    - dev
  except:
    - tags

job release:
  stage: release
  script:
    - docker pull $BUILD_IMAGE
    - docker tag $BUILD_IMAGE $RELEASE_IMAGE
    - docker push $CI_REGISTRY_IMAGE
  tags:
    - eshop_service_release
  only:
    - master
  except:
    - tags

push to docker hub:
  # in order for this to work you will need to set
  # `HUB_USERNAME` and `HUB_PASSWORD` as CI variables
  # in the Gitlab project
  stage: release
  variables:
    DOCKER_IMAGE: $HUB_USERNAME/$CI_PROJECT_NAME:latest
  script:
    - docker login -u $HUB_USERNAME -p $HUB_PASSWORD
    - docker tag $RELEASE_IMAGE $DOCKER_IMAGE
    - docker push $DOCKER_IMAGE
  only:
    - master
  when: manual

line ================================ line

docker build --pull  -t eshop/identity.api:latest .
docker tag eshop/identity.api registry.xxx.com/eshop/identity.api

This way is only for a single container
How to microservice containers, is it necessary to manually make one reality?

line ================================ line
**Problem:**

Running with gitlab-runner 10.8.0 (079aad9e)
  on eshop_service_build e157e182
Using Docker executor with image docker:stable ...
Pulling docker image docker:stable ...
Using docker image sha256:c51a2cac7341fe55d38feb70157eb12d56b2039977d4175229432de09bd18896 for docker:stable ...
Running on runner-e157e182-project-21-concurrent-0 via bc32ca479fdc...
Fetching changes...
HEAD is now at 2f2a5067 Merge branch 'dev' of test:eshop/services into dev
Checking out 2f2a5067 as dev...
Skipping Git submodules setup
$ apk add --update py-pip && pip install docker-compose
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/12) Installing libbz2 (1.0.6-r6)
(2/12) Installing expat (2.2.5-r0)
(3/12) Installing libffi (3.2.1-r4)
(4/12) Installing gdbm (1.13-r1)
(5/12) Installing ncurses-terminfo-base (6.0_p20171125-r0)
(6/12) Installing ncurses-terminfo (6.0_p20171125-r0)
(7/12) Installing ncurses-libs (6.0_p20171125-r0)
(8/12) Installing readline (7.0.003-r0)
(9/12) Installing sqlite-libs (3.21.0-r1)
(10/12) Installing python2 (2.7.14-r2)
(11/12) Installing py-setuptools (33.1.1-r1)
(12/12) Installing py2-pip (9.0.1-r1)
Executing busybox-1.27.2-r7.trigger
OK: 62 MiB in 24 packages
Collecting docker-compose
  Downloading https://files.pythonhosted.org/packages/27/3c/6fcaa3b546ae8103c444149a1746f9a7043df7503e12bad318e8217312fb/docker_compose-1.21.2-py2.py3-none-any.whl (123kB)
Collecting websocket-client<1.0,>=0.32.0 (from docker-compose)
  Downloading https://files.pythonhosted.org/packages/8a/a1/72ef9aa26cfe1a75cee09fc1957e4723add9de098c15719416a1ee89386b/websocket_client-0.48.0-py2.py3-none-any.whl (198kB)
Collecting PyYAML<4,>=3.10 (from docker-compose)
  Downloading https://files.pythonhosted.org/packages/4a/85/db5a2df477072b2902b0eb892feb37d88ac635d36245a72a6a69b23b383a/PyYAML-3.12.tar.gz (253kB)
Collecting dockerpty<0.5,>=0.4.1 (from docker-compose)
  Downloading https://files.pythonhosted.org/packages/8d/ee/e9ecce4c32204a6738e0a5d5883d3413794d7498fe8b06f44becc028d3ba/dockerpty-0.4.1.tar.gz
Collecting backports.ssl-match-hostname>=3.5; python_version < "3.5" (from docker-compose)
  Downloading https://files.pythonhosted.org/packages/76/21/2dc61178a2038a5cb35d14b61467c6ac632791ed05131dda72c20e7b9e23/backports.ssl_match_hostname-3.5.0.1.tar.gz
Collecting docopt<0.7,>=0.6.1 (from docker-compose)
  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting docker<4.0,>=3.3.0 (from docker-compose)
  Downloading https://files.pythonhosted.org/packages/31/01/41f727a549abd788eb91d0df4c801cb4c1f5227eee04a2621e13d7ed3e04/docker-3.3.0-py2.py3-none-any.whl (124kB)
Collecting requests!=2.11.0,!=2.12.2,!=2.18.0,<2.19,>=2.6.1 (from docker-compose)
  Downloading https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl (88kB)
Collecting ipaddress>=1.0.16; python_version < "3.3" (from docker-compose)
  Downloading https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting enum34<2,>=1.0.4; python_version < "3.4" (from docker-compose)
  Downloading https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting texttable<0.10,>=0.9.0 (from docker-compose)
  Downloading https://files.pythonhosted.org/packages/02/e1/2565e6b842de7945af0555167d33acfc8a615584ef7abd30d1eae00a4d80/texttable-0.9.1.tar.gz
Collecting jsonschema<3,>=2.5.1 (from docker-compose)
  Downloading https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting cached-property<2,>=1.2.0 (from docker-compose)
  Downloading https://files.pythonhosted.org/packages/ca/21/d793828ce0bb01baa6bed307c68466829343cc93fccc055cfbc21f774959/cached_property-1.4.2-py2.py3-none-any.whl
Collecting six<2,>=1.3.0 (from docker-compose)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting docker-pycreds>=0.2.3 (from docker<4.0,>=3.3.0->docker-compose)
  Downloading https://files.pythonhosted.org/packages/ea/bf/7e70aeebc40407fbdb96fa9f79fc8e4722ea889a99378303e3bcc73f4ab5/docker_pycreds-0.3.0-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.19,>=2.6.1->docker-compose)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting certifi>=2017.4.17 (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.19,>=2.6.1->docker-compose)
  Downloading https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl (150kB)
Collecting urllib3<1.23,>=1.21.1 (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.19,>=2.6.1->docker-compose)
  Downloading https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl (132kB)
Collecting idna<2.7,>=2.5 (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.19,>=2.6.1->docker-compose)
  Downloading https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl (56kB)
Collecting functools32; python_version == "2.7" (from jsonschema<3,>=2.5.1->docker-compose)
  Downloading https://files.pythonhosted.org/packages/c5/60/6ac26ad05857c601308d8fb9e87fa36d0ebf889423f47c3502ef034365db/functools32-3.2.3-2.tar.gz
Installing collected packages: six, websocket-client, PyYAML, dockerpty, backports.ssl-match-hostname, docopt, ipaddress, chardet, certifi, urllib3, idna, requests, docker-pycreds, docker, enum34, texttable, functools32, jsonschema, cached-property, docker-compose
  Running setup.py install for PyYAML: started
    Running setup.py install for PyYAML: finished with status 'done'
  Running setup.py install for dockerpty: started
    Running setup.py install for dockerpty: finished with status 'done'
  Running setup.py install for backports.ssl-match-hostname: started
    Running setup.py install for backports.ssl-match-hostname: finished with status 'done'
  Running setup.py install for docopt: started
    Running setup.py install for docopt: finished with status 'done'
  Running setup.py install for texttable: started
    Running setup.py install for texttable: finished with status 'done'
  Running setup.py install for functools32: started
    Running setup.py install for functools32: finished with status 'done'
Successfully installed PyYAML-3.12 backports.ssl-match-hostname-3.5.0.1 cached-property-1.4.2 certifi-2018.4.16 chardet-3.0.4 docker-3.3.0 docker-compose-1.21.2 docker-pycreds-0.3.0 dockerpty-0.4.1 docopt-0.6.2 enum34-1.1.6 functools32-3.2.3.post2 idna-2.6 ipaddress-1.0.22 jsonschema-2.6.0 requests-2.18.4 six-1.11.0 texttable-0.9.1 urllib3-1.22 websocket-client-0.48.0
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$ docker info
WARNING: No swap limit support
Containers: 28
 Running: 2
 Paused: 0
 Stopped: 26
Images: 51
Server Version: 18.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-87-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.825GiB
Name: redbon-ci
ID: PRJE:SI74:6WTS:M2S7:663L:QGKA:M7JP:PVEG:YW7B:QAEL:2GQY:T2RR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 192.168.1.2:4567
 127.0.0.0/8
Registry Mirrors:
 http://718dbf2d.m.daocloud.io/
Live Restore Enabled: false

$ docker-compose --version
docker-compose version 1.21.2, build a133471
$ docker login -u gitlab-ci-token-p $CI_JOB_TOKEN $CI_REGISTRY_IMAGE
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
$ docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
Starting services_rabbitmq_1 ... 
Starting services_sql.data_1 ... 

Starting services_rabbitmq_1 ... done

Starting services_sql.data_1 ... done
Starting services_supplier.api_1 ... 
Starting services_review.api_1   ... 
Starting services_coupon.api_1   ... 
Starting services_commission.api_1 ... 
Starting services_assessment.api_1 ... 
Starting services_information.api_1 ... 
Starting services_catalog.api_1     ... 
Starting services_basket.api_1      ... 
Starting services_member.api_1      ... 
Starting services_mall.api_1        ... 
Starting services_brand.api_1       ... 
Starting services_identity.api_1    ... 
Starting services_order.api_1       ... 
Starting services_product.api_1     ... 
Starting services_delivery.api_1    ... 

Starting services_supplier.api_1    ... done

Starting services_review.api_1      ... done

Starting services_coupon.api_1      ... done

Starting services_commission.api_1  ... done

Starting services_member.api_1      ... done

Starting services_assessment.api_1  ... done

Starting services_mall.api_1        ... done

Starting services_brand.api_1       ... done

Starting services_information.api_1 ... done

Starting services_catalog.api_1     ... done

Starting services_basket.api_1      ... done

Starting services_identity.api_1    ... done
Starting services_mallfrontend_1    ... 
Starting services_mallbackend_1     ... 

Starting services_delivery.api_1    ... done

Starting services_product.api_1     ... done
Starting services_backend_1         ... 

Starting services_mallfrontend_1    ... done

Starting services_order.api_1       ... done

Starting services_backend_1         ... done

Starting services_mallbackend_1     ... done
$ docker push $BUILD_IMAGE
The push refers to repository [192.168.1.2:4567/eshop/services]
An image does not exist locally with the tag: 192.168.1.2:4567/eshop/services
ERROR: Job failed: exit code 1

**Comment by mvelosop** [comment]
Hi @dmpx, 

There are no plans to include anything about CI/CD for the time being.

Anyway, I will keep this issue open for a couple of days to give a chance for someone from the community to answer, in case she/he knows about this.

Best.
