### ISSUE TITLE
[Question] Building SPA in docker container 

### ISSUE THREAD

**Issue by SvenPetroll** [dotnet-architecture/eShopOnContainers#636]
As I understand it at this time, there is a requirement that the SPA needs to build locally and Docker uses the build artifacts to launch the docker container. This might cause some problems due the differences between Windows  & Linux (please let me know if that's wrong).

Is there a reason why the SPA can't/shouldn't be build inside a container and this simplified workflow isn't included in this repository?

**Comment by mvelosop** [comment]
Closing, will reopen if needed.
