### ISSUE TITLE
[Question] Debug Applications from VS Code

### ISSUE THREAD

**Issue by Stewartarmbrecht** [dotnet-architecture/eShopOnContainers#639]
How do you debug the applications using VS Code?

**Comment by mvelosop** [comment]
Hi @Stewartarmbrecht, that's a very good question 👍

Have never tried it, gonna ask some friends!

In the meantime, there's a extension for that: https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md just in case you want to give it a try.

If you do, please share your findings 😉

**Comment by eiximenis** [comment]
Hi,
Major issue when using vscode to debug eShopOnContainers is that, while you can debug a single container, there is no way (at least known by me) to debug more than one container simultaneously in a similar way that VS provides.

Here is a guidance on how debug a docker container using vscode: https://github.com/sleemer/docker.dotnet.debug

Note: In this approach they are putting the vsdbg in the image. Another approach is download it locally and use a bind mount to put the vsdbg in the container.

**Comment by Stewartarmbrecht** [comment]
Thanks!  Does this mean that the complete solution can only really be debugged on Windows?  Or can VS for Mac debug multiple containers?

**Comment by mvelosop** [comment]
Hi @Stewartarmbrecht,

I just can't tell you for sure, for I don't have a Mac, maybe @CESARDELATORRE or someone else can comment on the subject.

However, I found this thread that looks interesting and looks like they got it working: https://github.com/Microsoft/generator-docker/issues/130

Hey! if you get to try that, it would be great if you let us know here! 😃

Hope this helps.

**Comment by eiximenis** [comment]
Hi @Stewartarmbrecht 
I think VS For Mac supports debugging multiple containers like VS for windows do.

**Comment by CESARDELATORRE** [comment]
Yes, with @Stewartarmbrecht, with VS for Mac you should be able to debug multi-container apps.

Just take into account, for eShopOnContainers, this bug in VS for Mac which, I'm not sure if it's been fixed, yet, in VS for Mac:
https://github.com/dotnet-architecture/eShopOnContainers/issues/634

Closing this issue.
