### ISSUE TITLE
Startup/Build

### ISSUE THREAD

**Issue by Allann** [dotnet-architecture/eShopOnContainers#646]
Hi,

I did a complete clean of my dev machine and fetched the current version of code, followed the instructions in the linked startup wiki and keep getting the following errors, these occur on brand new VMs with the latest VS2017 15.7 and 15.8 preview.

Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.ApplicationInsights.PerfCounterCollector 2.5.1 requires Microsoft.ApplicationInsights (= 2.5.1) but version Microsoft.ApplicationInsights 2.6.1 was resolved.	Ordering.API	F:\Repos\eShopOnContainers\src\Services\Ordering\Ordering.API\Ordering.API.csproj	1	
Warning	CS0414	The field 'Order._isDraft' is assigned but its value is never used	Ordering.Domain	F:\Repos\eShopOnContainers\src\Services\Ordering\Ordering.Domain\AggregatesModel\OrderAggregate\Order.cs	31	Active
Warning	MVC1000	Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.	Identity.API	F:\Repos\eShopOnContainers\src\Services\Identity\Identity.API\Views\Consent\Index.cshtml	19	Active
Warning	MVC1000	Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.	Identity.API	F:\Repos\eShopOnContainers\src\Services\Identity\Identity.API\Views\Consent\Index.cshtml	36	Active
Warning	MVC1000	Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.	Identity.API	F:\Repos\eShopOnContainers\src\Services\Identity\Identity.API\Views\Consent\Index.cshtml	52	Active
Warning	CS1998	This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.	Mobile.Shopping.HttpAggregator	F:\Repos\eShopOnContainers\src\ApiGateways\Mobile.Bff.Shopping\aggregator\Startup.cs	131	Active
Warning	CS0219	The variable 'i' is assigned but its value is never used	Mobile.Shopping.HttpAggregator	F:\Repos\eShopOnContainers\src\ApiGateways\Mobile.Bff.Shopping\aggregator\Startup.cs	133	Active
Warning	CS1998	This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.	Mobile.Shopping.HttpAggregator	F:\Repos\eShopOnContainers\src\ApiGateways\Mobile.Bff.Shopping\aggregator\Startup.cs	135	Active
Warning	CS0219	The variable 'i' is assigned but its value is never used	Mobile.Shopping.HttpAggregator	F:\Repos\eShopOnContainers\src\ApiGateways\Mobile.Bff.Shopping\aggregator\Startup.cs	137	Active
Warning	CS0169	The field 'CreateOrderDraftCommandHandler._orderRepository' is never used	Ordering.API	F:\Repos\eShopOnContainers\src\Services\Ordering\Ordering.API\Application\Commands\CreateOrderDraftCommandHandler.cs	19	Active
Warning	CS0169	The field 'BasketService._bffUrl' is never used	WebMVC	F:\Repos\eShopOnContainers\src\Web\WebMVC\Services\BasketService.cs	20	Active
Warning	MVC1000	Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.	WebMVC	F:\Repos\eShopOnContainers\src\Web\WebMVC\Views\Campaigns\Details.cshtml	11	Active
Warning	MVC1000	Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.	WebMVC	F:\Repos\eShopOnContainers\src\Web\WebMVC\Views\Campaigns\Index.cshtml	12	Active
Warning	MVC1000	Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.	WebMVC	F:\Repos\eShopOnContainers\src\Web\WebMVC\Views\Campaigns\Index.cshtml	57	Active
Warning	MVC1000	Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.	WebMVC	F:\Repos\eShopOnContainers\src\Web\WebMVC\Views\Campaigns\Index.cshtml	62	Active
Warning	MVC1000	Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.	WebMVC	F:\Repos\eShopOnContainers\src\Web\WebMVC\Views\Cart\Index.cshtml	13	Active
Warning	MVC1000	Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.	WebMVC	F:\Repos\eShopOnContainers\src\Web\WebMVC\Views\Catalog\Index.cshtml	38	Active
Warning	MVC1000	Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.	WebMVC	F:\Repos\eShopOnContainers\src\Web\WebMVC\Views\Catalog\Index.cshtml	44	Active
Warning	MVC1000	Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.	WebMVC	F:\Repos\eShopOnContainers\src\Web\WebMVC\Views\Catalog\Index.cshtml	49	Active
Warning	MVC1000	Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.	WebMVC	F:\Repos\eShopOnContainers\src\Web\WebMVC\Views\OrderManagement\Index.cshtml	10	Active
Warning	MVC1000	Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.	WebMVC	F:\Repos\eShopOnContainers\src\Web\WebMVC\Views\Order\Create.cshtml	9	Active
Warning	MVC1000	Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.	WebMVC	F:\Repos\eShopOnContainers\src\Web\WebMVC\Views\Order\Detail.cshtml	10	Active
Warning	MVC1000	Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.	WebMVC	F:\Repos\eShopOnContainers\src\Web\WebMVC\Views\Order\Index.cshtml	10	Active
Warning	CS1998	This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.	OcelotApiGw	F:\Repos\eShopOnContainers\src\ApiGateways\ApiGw-Base\Startup.cs	52	Active
Warning	CS0219	The variable 'i' is assigned but its value is never used	OcelotApiGw	F:\Repos\eShopOnContainers\src\ApiGateways\ApiGw-Base\Startup.cs	54	Active
Warning	CS1998	This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.	OcelotApiGw	F:\Repos\eShopOnContainers\src\ApiGateways\ApiGw-Base\Startup.cs	56	Active
Warning	CS0219	The variable 'i' is assigned but its value is never used	OcelotApiGw	F:\Repos\eShopOnContainers\src\ApiGateways\ApiGw-Base\Startup.cs	58	Active
Warning	CS1998	This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.	OcelotApiGw	F:\Repos\eShopOnContainers\src\ApiGateways\ApiGw-Base\Startup.cs	61	Active
Warning	CS0219	The variable 'i' is assigned but its value is never used	OcelotApiGw	F:\Repos\eShopOnContainers\src\ApiGateways\ApiGw-Base\Startup.cs	63	Active
Warning	CS1998	This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.	Web.Shopping.HttpAggregator	F:\Repos\eShopOnContainers\src\ApiGateways\Web.Bff.Shopping\aggregator\Startup.cs	89	Active
Warning	CS0219	The variable 'i' is assigned but its value is never used	Web.Shopping.HttpAggregator	F:\Repos\eShopOnContainers\src\ApiGateways\Web.Bff.Shopping\aggregator\Startup.cs	91	Active
Warning	CS1998	This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.	Web.Shopping.HttpAggregator	F:\Repos\eShopOnContainers\src\ApiGateways\Web.Bff.Shopping\aggregator\Startup.cs	93	Active
Warning	CS0219	The variable 'i' is assigned but its value is never used	Web.Shopping.HttpAggregator	F:\Repos\eShopOnContainers\src\ApiGateways\Web.Bff.Shopping\aggregator\Startup.cs	95	Active
Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.ApplicationInsights.PerfCounterCollector 2.5.1 requires Microsoft.ApplicationInsights (= 2.5.1) but version Microsoft.ApplicationInsights 2.6.1 was resolved.	Ordering.SignalrHub	F:\Repos\eShopOnContainers\src\Services\Ordering\Ordering.SignalrHub\Ordering.SignalrHub.csproj	1	
Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.ApplicationInsights.PerfCounterCollector 2.5.1 requires Microsoft.ApplicationInsights (= 2.5.1) but version Microsoft.ApplicationInsights 2.6.1 was resolved.	WebStatus	F:\Repos\eShopOnContainers\src\Web\WebStatus\WebStatus.csproj	1	
Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.ApplicationInsights.PerfCounterCollector 2.5.1 requires Microsoft.ApplicationInsights (= 2.5.1) but version Microsoft.ApplicationInsights 2.6.1 was resolved.	Identity.API	F:\Repos\eShopOnContainers\src\Services\Identity\Identity.API\Identity.API.csproj	1	
Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.ApplicationInsights.PerfCounterCollector 2.5.1 requires Microsoft.ApplicationInsights (= 2.5.1) but version Microsoft.ApplicationInsights 2.6.1 was resolved.	Catalog.API	F:\Repos\eShopOnContainers\src\Services\Catalog\Catalog.API\Catalog.API.csproj	1	
Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.ApplicationInsights.PerfCounterCollector 2.5.1 requires Microsoft.ApplicationInsights (= 2.5.1) but version Microsoft.ApplicationInsights 2.6.1 was resolved.	Basket.API	F:\Repos\eShopOnContainers\src\Services\Basket\Basket.API\Basket.API.csproj	1	
Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.ApplicationInsights.PerfCounterCollector 2.5.1 requires Microsoft.ApplicationInsights (= 2.5.1) but version Microsoft.ApplicationInsights 2.6.1 was resolved.	WebMVC	F:\Repos\eShopOnContainers\src\Web\WebMVC\WebMVC.csproj	1	
Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.ApplicationInsights.PerfCounterCollector 2.5.1 requires Microsoft.ApplicationInsights (= 2.5.1) but version Microsoft.ApplicationInsights 2.6.1 was resolved.	WebSPA	F:\Repos\eShopOnContainers\src\Web\WebSPA\WebSPA.csproj	1	
Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.ApplicationInsights.PerfCounterCollector 2.5.1 requires Microsoft.ApplicationInsights (= 2.5.1) but version Microsoft.ApplicationInsights 2.6.1 was resolved.	Payment.API	F:\Repos\eShopOnContainers\src\Services\Payment\Payment.API\Payment.API.csproj	1	
Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.ApplicationInsights.PerfCounterCollector 2.5.1 requires Microsoft.ApplicationInsights (= 2.5.1) but version Microsoft.ApplicationInsights 2.6.1 was resolved.	Locations.API	F:\Repos\eShopOnContainers\src\Services\Location\Locations.API\Locations.API.csproj	1	
Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.ApplicationInsights.PerfCounterCollector 2.5.1 requires Microsoft.ApplicationInsights (= 2.5.1) but version Microsoft.ApplicationInsights 2.6.1 was resolved.	Marketing.API	F:\Repos\eShopOnContainers\src\Services\Marketing\Marketing.API\Marketing.API.csproj	1	
Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.ApplicationInsights.PerfCounterCollector 2.5.1 requires Microsoft.ApplicationInsights (= 2.5.1) but version Microsoft.ApplicationInsights 2.6.1 was resolved.	UnitTest	F:\Repos\eShopOnContainers\test\Services\UnitTest\UnitTest.csproj	1	
Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.ApplicationInsights.PerfCounterCollector 2.5.1 requires Microsoft.ApplicationInsights (= 2.5.1) but version Microsoft.ApplicationInsights 2.6.1 was resolved.	FunctionalTests	F:\Repos\eShopOnContainers\test\Services\FunctionalTests\FunctionalTests.csproj	1	
Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.ApplicationInsights.PerfCounterCollector 2.5.1 requires Microsoft.ApplicationInsights (= 2.5.1) but version Microsoft.ApplicationInsights 2.6.1 was resolved.	IntegrationTests	F:\Repos\eShopOnContainers\test\Services\IntegrationTests\IntegrationTests.csproj	1	
Error	MSB3030	Could not copy the file "F:\Repos\eShopOnContainers\src\Services\Basket\Basket.API\bin\Debug\netcoreapp2.1\Basket.API.dll" because it was not found.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4343	
Error	MSB3030	Could not copy the file "F:\Repos\eShopOnContainers\src\Services\Catalog\Catalog.API\bin\Debug\netcoreapp2.1\Catalog.API.dll" because it was not found.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4343	
Error	MSB3030	Could not copy the file "F:\Repos\eShopOnContainers\src\Services\Identity\Identity.API\bin\Debug\netcoreapp2.1\Identity.API.dll" because it was not found.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4343	
Error	MSB3030	Could not copy the file "F:\Repos\eShopOnContainers\src\Services\Location\Locations.API\bin\Debug\netcoreapp2.1\Locations.API.dll" because it was not found.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4343	
Error	MSB3030	Could not copy the file "F:\Repos\eShopOnContainers\src\Services\Marketing\Marketing.API\bin\Debug\netcoreapp2.1\Marketing.API.dll" because it was not found.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4343	
Error	MSB3030	Could not copy the file "F:\Repos\eShopOnContainers\src\ApiGateways\Mobile.Bff.Shopping\aggregator\bin\Debug\netcoreapp2.1\Mobile.Shopping.HttpAggregator.dll" because it was not found.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4343	
Error	MSB3030	Could not copy the file "F:\Repos\eShopOnContainers\src\ApiGateways\ApiGw-Base\bin\Debug\netcoreapp2.1\OcelotApiGw.dll" because it was not found.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4343	
Error	MSB3030	Could not copy the file "F:\Repos\eShopOnContainers\src\Services\Ordering\Ordering.API\bin\Debug\netcoreapp2.1\Ordering.API.dll" because it was not found.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4343	
Error	MSB3030	Could not copy the file "F:\Repos\eShopOnContainers\src\Services\Ordering\Ordering.BackgroundTasks\bin\Debug\netcoreapp2.1\Ordering.BackgroundTasks.dll" because it was not found.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4343	
Error	MSB3030	Could not copy the file "F:\Repos\eShopOnContainers\src\Services\Ordering\Ordering.SignalrHub\bin\Debug\netcoreapp2.1\Ordering.SignalrHub.dll" because it was not found.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4343	
Error	MSB3030	Could not copy the file "F:\Repos\eShopOnContainers\src\Services\Payment\Payment.API\bin\Debug\netcoreapp2.1\Payment.API.dll" because it was not found.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4343	
Error	MSB3030	Could not copy the file "F:\Repos\eShopOnContainers\src\ApiGateways\Web.Bff.Shopping\aggregator\bin\Debug\netcoreapp2.1\Web.Shopping.HttpAggregator.dll" because it was not found.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4343	
Error	MSB3030	Could not copy the file "F:\Repos\eShopOnContainers\src\Web\WebMVC\bin\Debug\netcoreapp2.1\WebMVC.dll" because it was not found.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4343	
Error	MSB3030	Could not copy the file "F:\Repos\eShopOnContainers\src\Web\WebSPA\bin\Debug\netcoreapp2.1\WebSPA.dll" because it was not found.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4343	
Error	MSB3030	Could not copy the file "F:\Repos\eShopOnContainers\src\Web\WebStatus\bin\Debug\netcoreapp2.1\WebStatus.dll" because it was not found.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4343

**Comment by mvelosop** [comment]
Hi @Allann,

I guess it's probably because you are working from disk F: and haven't shared that disk with Docker:

![image](https://user-images.githubusercontent.com/7357806/41808923-2be9d306-76dd-11e8-8c4b-b8f25129c39c.png)

In case your F: is a network drive, try copying the project to a local (and shared with Docker) drive, AFAIK you can only share local drives with Docker.

Hope this helps.

**Comment by Allann** [comment]
Actually its an internal SSD i use for all development.

![docker](https://user-images.githubusercontent.com/2005474/41816186-a969deb8-77c1-11e8-8a2c-e05ced2bb35d.PNG)

**Comment by Allann** [comment]
Using Docker community Edition v18.03.1-ce-win65 (17513)

**Comment by mvelosop** [comment]
Hi @Allann,

There seems to be some networking error I'm still trying to understand myself.

I haven't had that problem with the Docker version you have, but I always had to restart Docker after powering up my laptop, until I upgraded to the next version.

I understand you started with a brand new VM, right?

Could you try uninstalling Docker and reinstalling it back again?

A pattern could be emerging here!

**Comment by Allann** [comment]
Uninstalled and reinstalled docker as suggested and now everything built and the website started.
Thanks.

**Comment by mvelosop** [comment]
Hi @Allann,

Good to know, this really looks like a pattern:

1. Install Docker for Windows
2. Uninstall
3. Reinstall

It looks like a clean install is not enough!
