### ISSUE TITLE
Not able to setup the application on VS2017

### ISSUE THREAD

**Issue by Liveanshu** [dotnet-architecture/eShopOnContainers#649]
Hello there,

I am trying to setup the solutio
![2](https://user-images.githubusercontent.com/29971690/41918989-156f4354-797b-11e8-9ec2-b356b6897236.JPG)
![1](https://user-images.githubusercontent.com/29971690/41918990-15bd7ca4-797b-11e8-9505-5f6422188abc.png)

n on my machine and perform the steps mentioned  below:

https://github.com/dotnet-architecture/eShopOnContainers/wiki/02.-Setting-eShopOnContainers-in-a-Visual-Studio-2017-environment

1.	Upgraded the VS2017 to the 15.7
2.	Download the solution from Git from the location mentioned
3.	Configure Docker as it is given in the article
4.	Setup the in-bound rule to allow 5100 to 5105
5.	Make docker-compose project as startup
6.	And run the application.

it first gave me an build error in the project “Mobile.Shopping.HttpAggregator” that “Microsoft.Extensions.Http.Polly” was not compatible then I install the 2.10 rc1(final) and everything run smooth.

However  at the runtime it gave us below  error. Please guide me where I am doing wrong. 

 

The detail error is attached. Please guide me where I am doing wrong. Any help appreciated.

**Comment by mvelosop** [comment]
Hi @Liveanshu,

Could you please post the output from the `docker info` command?

**Comment by Liveanshu** [comment]
Hello @mvelosop 

Thanks for your response, Below is the output of docker info command.
D:\eShopOnContainers-dev\eShopOnContainers-dev\src\ApiGateways\Mobile.Bff.Shopping\aggregator>docker info
Containers: 22
 Running: 22
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 3.837GiB
Name: localhost
ID: GNCP:GZ4N:7VIL:5LII:JWME:WIEE:65MI:2BNL:KXFC:E3Q7:QIQC:ISC4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 192
 Goroutines: 158
 System Time: 2018-06-27T14:35:26.6639694Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

Thanks
Anshuman

**Comment by mvelosop** [comment]
Hi @Liveanshu,

That's a somewhat old Docker version, that gave me some networking issues, so I suggest that you upgrade to the latest stable (18.03.1-ce-win65).

But, first uninstall the current version and the reinstall the new one.

Hope that helps.

**Comment by CESARDELATORRE** [comment]
You are getting an error from the Circuit Breaker (our Polly's policy), like if the containers took too much time to start, then you reached the maximum number of Http retries and the circuit is open so it won't continue doing the retries.

WORKAROUNDS:
- 1. Increase the number of retriesfor the retry policy and the circuit brealer policy, here:
https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Web/WebMVC/Startup.cs
Scroll down in VS to the following methods:
GetRetryPolicy() --> Set 12 to the number of retries.
GetCircuitBreakerPolicy() --> Set 11 to the number of retries when the Circuit will break.

- 2. You can also try to run it on a faster machine, more memory assigned to Docker and more cores assigned to Docker, so it won't probably reach the number of retries.

Hope it helps. 👍

**Comment by Liveanshu** [comment]
Hello @mvelosop  and @CESARDELATORRE ,

Thanks for your response , I will try both and update you.

Thanks
Anshuman

**Comment by mvelosop** [comment]
Closing now, will reopen if needed.
