### ISSUE TITLE
How I have to config test to being successful?

### ISSUE THREAD

**Issue by SaMirzaei** [dotnet-architecture/eShopOnContainers#656]
Hi,
When I run tests in Test Explorer **35** test failed.

I don't know how I can run tests to success.

Thanks everyone for taking the time to try and help explain.

**Comment by mvelosop** [comment]
Hi @SaMirzaei,

UnitTests should run right away, but there's one tests failing.

These  tests require microservices to be running:
1. IntegrationTests
2. FunctionalTests and
3. LoadTests (Also requires VS Enterprise Edition)

So, to run all tests (other that unit tests) you have to have all containers running, as per: https://github.com/dotnet-architecture/eShopOnContainers/wiki/03.-Setting-the-eShopOnContainers-solution-up-in-a-Windows-CLI-environment-(dotnet-CLI,-Docker-CLI-and-VS-Code)

Then, you can run the tests from VS.

Right now there are several seven tests failing (not including load tests), this is just to check red lights go on when something fails! 😉

So, that's what you should get.

All tests are being reorganized now to have independent test per microservice.

Hope this helps.

**Comment by mvelosop** [comment]
Closing as the issue became stale, will reopen if needed.
