### ISSUE TITLE
.NET Microservices - Architecture for Containerized v2.1 epub version

### ISSUE THREAD

**Issue by fabricioveronez** [dotnet-architecture/eShopOnContainers#657]
How can I download the version 2.1 in epub format ?

**Comment by CESARDELATORRE** [comment]
In ePub and mobi it is still not published.
Will be in a few days.
Keep tuned by subscribing to the NEWS Architecture repo.
I’ll put the news there when ready.

**Comment by fabricioveronez** [comment]
Ok. 
So, I'll close this issue and watch the News Architecture repo.
Thanks.
