### ISSUE TITLE
[Refactoring] IdentifiedCommand replaced with ExistingCommandBehavior in MediatR pipeline

### ISSUE THREAD

**Issue by domenkogler** [dotnet-architecture/eShopOnContainers#661]
IdentifiedCommand replaced with ExistingCommandBehavior in MediatR pipeline.
Implementing response for existing command is now simpler and actual command is passed as parameter.
Added Tests, also for ValidatorBehavior.

#660

**Comment by mvelosop** [comment]
Closing this issue now because the related PR is outdated because of a heavy overhaul of the related code, but feel free to comment, will reopen if needed.
