### ISSUE TITLE
Using MoQ for mocking in Xamarin Forms.

### ISSUE THREAD

**Issue by mahapatraprabhanjan** [dotnet-architecture/eShopOnContainers#663]
Is there any way we can use MoQ to mock the view models under testing in Mobile App?

Also, how can we use Xamarin.UITests to perform UI testing?

Please help.

Thanks
Prabhanjan

**Comment by mahapatraprabhanjan** [comment]
Decoupling the Container from the ViewModelLocator and getting rid of virtual Service Locator Pattern resolves the Mocking issues with ViewModel.

**Comment by mvelosop** [comment]
Closing this, will reopen if needed.
