### ISSUE TITLE
UWP application crash

### ISSUE THREAD

**Issue by franperezlopez** [dotnet-architecture/eShopOnContainers#664]
I'm testing the UWP application, using the online mode (no Mocks). After setting up the correct endpoints, I'm able to login in the app

After this, If I delete the Identity DB, the authentication token given to the app is lost. In a normal scenario, the DB should not be deleted. But in development, is very common to create and destroy containers at your will.

Then, if I open the app, the app receives a 401, and then crashes (with no warning). Usually, after getting a 401 error, you should logout the app and take the user to the login screen. But at this moment, even after uninstalling the app / deleting all files, the settings are stored "somewhere" and the app continuously keeps crashing because tries to authenticate with a token that is not valid anymore

**Comment by mvelosop** [comment]
Hi @franperezlopez (long time no see!),

This seems to be related to #346, of course this is not of much help to you but I'm exploring that issue.

Hope to get you better new not too far away!

**Comment by mvelosop** [comment]
Hi @davidbritch, I'm trying to work in this issue, but can't get the UWP app to run 😣

It just displays the initial view for a moment, and the just aborts. Doesn't get to show the login view.

Inspecting a bit with Fiddler I found that it's somehow querying locations with a token, but the service replies saying it has expired (?)

Could you give some guidance please?

Thx.

**Comment by davidbritch** [comment]
Hi @mvelosop 

Afraid I have no advice to give.

**Comment by mvelosop** [comment]
Thanks anyway @davidbritch.

Does the Android app work in your machine?

I used to use the UWP for quick checks but, if the Android app works, I'll get into the setup process.

Don't have an Apple so can't test iOS ☹

**Comment by mvelosop** [comment]
Closing this issue a stale.
