### ISSUE TITLE
AWS deploy flow

### ISSUE THREAD

**Issue by inpicksys** [dotnet-architecture/eShopOnContainers#669]
Hi. Great example. Thanks for your job.
You have azure SF deploy flow, K8 deploy. Could you please describe deploy flow of Application to Amazon ?

**Comment by CESARDELATORRE** [comment]
Could be interesting but since we work for Microsoft, we compete against Amazon AWS.. ;)
We cannot invest time/resources on that deployment guidance.
But if anyone in the community forks it or makes any PR with such a content, I'd be happy to point to it. 👍

**Comment by inpicksys** [comment]
Thanks for answer. I see. Corporations battle.
