### ISSUE TITLE
Identity service not working with Message Bus, but on a screenshot is a mistake

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#671]
![image](https://user-images.githubusercontent.com/578954/42417833-f6cc07c8-829b-11e8-9a8e-18abd513784d.png)
We reviewed the documentation with my customers to integrate some pattern and practises to their project and they were thorough and find, that https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src/Services/Identity/Identity.API microservice not working message bus (no references, not configs). I hope in a next version of the book and documentation, it will be fixed.

**Comment by CESARDELATORRE** [comment]
The Event Bus is used by microservices when you need to publish integration events. The Identity microservice is not using it because in our scenarios there’s no need to integrate it in that way, but it’d Be possible, if you need to, that’s why the diagram shows it.

**Comment by SychevIgor** [comment]
My customer compared what is in a code and what on a diagram. For them it was like documentation, not as "possible use case".
But anyway- at least I have an answer for them.
