### ISSUE TITLE
"Unauthorised_client"- When clicking on login link

### ISSUE THREAD

**Issue by arindams621** [dotnet-architecture/eShopOnContainers#673]
Environment: Using the ubuntu 16.04 VM as a standalone server.

Only changed the localhost to Ip and put the entire app to run from jenkins with a jenkinsfile (jenkinsfile1 attached).
[jenkinsfile1.txt](https://github.com/dotnet-architecture/eShopOnContainers/files/2186367/jenkinsfile1.txt)

The app comes up. But am not able to login using the demouser/password. It says "Unauthorised client" when I click Login link from the url http://mypublicip:5100
Screenshot as below.
![unauthorized client](https://user-images.githubusercontent.com/39151092/42601883-cdae7056-8584-11e8-9e0c-4eed0c353f21.PNG)

The modified docker-compose.override.yml file is as follows:
[override-yml.txt](https://github.com/dotnet-architecture/eShopOnContainers/files/2186363/override-yml.txt)

**Comment by eiximenis** [comment]
Have you set the `ESHOP_EXTERNAL_DNS_NAME_OR_IP` environment value to the public IP of the VM before running the images?
This environment variable is used to configure the IdSvr clients.

**Comment by eiximenis** [comment]
.´jaqwertyuio´m nmj k bvd

**Comment by minhvc** [comment]
I have the same problem. It works on Windows but not on Ubuntu.
I have modified
 - .env file:
```
ESHOP_EXTERNAL_DNS_NAME_OR_IP=192.168.1.88
ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP=192.168.1.88
```
- docker-compose.override.yml file
webmvc:
    environment:
`   - IdentityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105  # Local Mac: Use http://docker.for.mac.localhost:5105 || Local Windows:  Use 10.0.75.1 in a "Docker for Windows" environment, if using "localhost" from browser. || #Remote access: Use ${ESHOP_EXTERNAL_DNS_NAME_OR_IP} if using external IP or DNS name from browser.`

**Comment by mvelosop** [comment]
Hi @arindams621,

Could you please check this table in the database and try updating the values to the right IP?

![image](https://user-images.githubusercontent.com/7357806/43650393-875747c6-9737-11e8-8833-78cb29ebc756.png)

**Comment by mvelosop** [comment]
Closing this issue, feel free to comment though, will reopen if necessary.

**Comment by bivekrawat** [comment]
For me this was CORS issue.

If you hit http://docker.for.win.localhost:5100/
instead of http://localhost:5100
works fine
