### ISSUE TITLE
Login Exception:"The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters."

### ISSUE THREAD

**Issue by arindams621** [dotnet-architecture/eShopOnContainers#674]
Created all the resources in azure and mentioned the same in the .env file.
Modified the docker-compose.prod.yml file with the Ip details.
Ran it from jenkins using a jenkins file (jenkinsfile2 attached).
[jenkinsfile2.txt](https://github.com/dotnet-architecture/eShopOnContainers/files/2186383/jenkinsfile2.txt)

The app comes up. But when I am trying to login and supply the demouser/password, it is giving me the exception "The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters."
Details of the exception attached here.
[Exception1.txt](https://github.com/dotnet-architecture/eShopOnContainers/files/2186384/Exception1.txt)

Below is how my docker-compose.prod.yml looks after modification.
[prod-yml.txt](https://github.com/dotnet-architecture/eShopOnContainers/files/2186387/prod-yml.txt)

**Comment by mvelosop** [comment]
Hi @arindams621 ,

I'm guessing this happens when logging in to localhost:5100, right?

Please, try again but clear the browser cache and cookies first.

**Comment by mvelosop** [comment]
Closing this issue now will reopen if needed.
