### ISSUE TITLE
[FeatureRequest] Add Key Vault to stare secrets in a bit more secured way inside K8

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#676]
https://ritazh.com/using-azure-key-vault-for-kubernetes-data-encryption-d5eac8daee71 
Now in an app we are storing secrets in a file, but there is a better and more secured way for that.
What do you think?

**Comment by CESARDELATORRE** [comment]
Agree. We're working on an Opt-in (optional) implementation using Azure KeyVault.

**Comment by mvelosop** [comment]
Hi @SychevIgor,

Azure KeyVault support was merged on JUL-31 by @unaizorrilla, but I haven't gotten into K8s enough to tell if it works there, but I guess it should.

**Comment by SychevIgor** [comment]
@mvelosop at least I seen keyvault in action with k8s earlier this year.

**Comment by SychevIgor** [comment]
@mvelosop I'm using "issue system" just to discuss some ideas.
