### ISSUE TITLE
[Question: Guidance on subscribing to Service Bus events in DDD style microservice]

### ISSUE THREAD

**Issue by stanoislav** [dotnet-architecture/eShopOnContainers#680]
eShopOnOnContainers uses Autofac to wire-up handlers for the messages coming from the Event Bus. I'm trying to achieve a clean implementation of the same concept, but with a built in dependency-injection service provider.

My microservice follows the DDD guidance, and has the API, Domain and Infrastructure Layers, similarly to the Ordering microservice. I would like my service to listen on the API calls (which works fine), and also on the Event Bus messages (which I'm struggling with).

- I register the Entity Framework with `services.AddEntityFrameworkSqlServer().AddDbContext`, which adds the DbContext with the Scoped lifetime
- I register the Repository with `services.addScoped' as well
- I register the event bus message handler with `services.AddSingleton` inside the `ConfigureServices` method (following the `AddEventBus` approach from eShopOnContainers)
- Inside my message handler I would like to use the standard constructor dependency injection, to give the message handler access to the Repository for the database updates (same as it's done inside the Controller for the API calls)

However because the event handler is a singleton, and the entity framework components are instantiated with the scope lifetime, the constructor dependency injection cannot be used.

What is the correct way to implement this please?
- should the Service Bus message handler be a Singleton or not?
- If yes, what is the clean way to get to the Repository? The only way I got it to work is to manually instantiate the DbContext and Repository inside the message handler, which doesn't feel right

**Comment by mvelosop** [comment]
Hi @stanoislav,

Did you take a look at: https://github.com/jbogard/MediatR/wiki#aspnet-core?

Keep in mind that the current version of MediatR is 5.1 and eShopOnContainers currently use 4.1, so you might have to check at a previous version of MediatR's repo.

Hope this helps.

**Comment by stanoislav** [comment]
Thank you! I wanted to keep it simple, and go without MediatR at this point. My controllers are calling methods from the Domain layer, rather than sending commands.

I have ended up using the Background service for listening on the Services Bus queues (similar concept would be implemented for topics).

In the ConfigureServices I register the services like this:

```csharp
services.AddHostedService<QueueListenerBackgroundService>();
services.AddScoped<IQueueListener, QueueListener>();
```
The first line registers the background service. The second line is a standard service, that supports dependency injection.

The important parts of *QueueListenerBackgroundService* are:

In the constructor store the Services Provider, and initialize the service bus client
```csharp
private readonly IServiceProvider _servicesProvider;
private readonly QueueClient _queueClient;

public QueueListenerBackgroundService(IConfiguration configuration, IServiceProvider servicesProvider)
{
   _servicesProvider = servicesProvider;
   _queueClient = new QueueClient(configuration["ServiceBusConnectionString"], configuration["QueueName"]);
}
```

In the StartAsync method start the messages listener.
```csharp
public Task StartAsync(CancellationToken cancellationToken)
{
    // Configure the MessageHandler Options in terms of exception handling, number of concurrent messages to deliver etc.
    var messageHandlerOptions = new MessageHandlerOptions(ExceptionReceivedHandler)
    {
        // AutoComplete set to false means, that we will manually acknowledge when we have succesfully finished processing the message
        AutoComplete = false,
    };

    // Register the function that will process messages
    _queueClient.RegisterMessageHandler(ProcessMessagesAsync, messageHandlerOptions);

    return Task.CompletedTask;
}
```
The StopAsync method stops the listening:
```csharp
public async Task StopAsync(CancellationToken cancellationToken)
{
    await _queueClient.CloseAsync();
}
```

Now the main method for processing messages needs to use *CreateScope* to retrieve reference to the QueueListener service.

```csharp
async Task ProcessMessagesAsync(Message message, CancellationToken token)
{
    // Process the message
    using (var scope = _servicesProvider.CreateScope())
    {
        var queueListener = scope.ServiceProvider.GetRequiredService<IQueueListener>();
        await queueListener.ProcessMessagesAsync(message.body);
    }

    // Complete the message so that it is not received again.
    await _queueClient.CompleteAsync(message.SystemProperties.LockToken);
}
```

The *QueueListener* is a standard service, doesn't need any special handling. Dependency injection works, so access to all services is available as normal.

**Comment by mvelosop** [comment]
Good to know you found your way out! 
Thanks.
