### ISSUE TITLE
[Question] Can I contribute by translating certain page?

### ISSUE THREAD

**Issue by hjy1998** [dotnet-architecture/eShopOnContainers#682]
Hello, am I allowed to contribute by translating certain page(s)? It's for my university assignment.
I saw that you mentioned that there is a auto translation but I think some of them are not accurate.

**Comment by CESARDELATORRE** [comment]
Of course! - What language would it be about?
I guess you mean translation of the related books, here?:
https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/

You can create a PR from any page, by clikcing on the "Edit" link up to the right, like in this page:
https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/container-docker-introduction/index.md

Or you can also fork the whole docs repo.

Thanks for your contribution! 👍

**Comment by mvelosop** [comment]
Closing this issue now, it looks like there will be no further activity, will reopen if needed.
