### ISSUE TITLE
Catalog all filter [error]

### ISSUE THREAD

**Issue by minhvc** [dotnet-architecture/eShopOnContainers#685]
When Brand is All and TYPE not All 
or Brand is not All and Type is All
the website has broken

HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
System.Net.Http.HttpClient.GetStringAsyncCore(Task<HttpResponseMessage> getTask)
Microsoft.eShopOnContainers.WebMVC.Services.CatalogService.GetCatalogItems(int page, int take, Nullable<int> brand, Nullable<int> type) in E:\MinhVC\Sources\eShopContainers\eShopOnContainers\src\Web\WebMVC\Services\CatalogService.cs
Microsoft.eShopOnContainers.WebMVC.Controllers.CatalogController.Index(Nullable<int> BrandFilterApplied, Nullable<int> TypesFilterApplied, Nullable<int> page, string errorMsg) in E:\MinhVC\Sources\eShopContainers\eShopOnContainers\src\Web\WebMVC\Controllers\CatalogController.cs

**Comment by CESARDELATORRE** [comment]
Thanks! - We'll fix it when possible. 👍

**Comment by unaizorrilla** [comment]
Please, review 5c06f6e5007411af02843c462bcb12258d282e34 and confirm if fixed.

**Comment by mvelosop** [comment]
Hi @minhvc,

Closing this issue. It has been fixed as of commit 5c06f6e5007411af02843c462bcb12258d282e34 from 31-JUL-2018.

Will reopen if needed.
