### ISSUE TITLE
Can not login with address localhost:5100

### ISSUE THREAD

**Issue by minhvc** [dotnet-architecture/eShopOnContainers#688]
To use the eShop web in another computer in Lan I have modified
.env file:
ESHOP_EXTERNAL_DNS_NAME_OR_IP=192.168.1.9
ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP=192.168.1.9
.docker-compose.override.yml file
webmvc:
environment:
IdentityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
I work well in another computer in Lan with address http://192.168.1.9:5100
but in Windows Server machine, when I use address http://localhost:5100/ and login it redirect to error page "Sorry, there was an error : unauthorized_client "
and if I deploy in Ubuntu Server at IP 192.168.1.88 then I work with http://localhost:5100/ in server machine, but can not login with http://192.168.1.88:5100

**Comment by mvelosop** [comment]
Closing this issue, feel free to comment though, will reopen if necessary.
