### ISSUE TITLE
Issues with AKS ingress controller when httpRouting addon is enabled: Config map addon-http-application-routing-nginx-configuration

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#691]
We're having a blocking issue when running on AKS and using its ingress.
 
**BEHAVIOR**:
Looks like AKS is changing our configuration in a config map (addon-http-application-routing-nginx-configuration in the kube-system). 
We’re observing that when we change the config map, sometimes the ingress controller notices and updates its configuration before AKS changes the config map back, and sometimes it doesn’t. And if we ever delete the controller pod and let it get recreated, it will certainly not get our modified config map.
 
We see this behavior:
 
1.	I edit the configmap => It contains 2 pieces of data shown below
2.	Ingress controller is aware of the change and reloads the config (following logs are streamed):
I0704 15:25:33.518025       5 controller.go:170] backend reload required
I0704 15:25:33.629403       5 controller.go:179] ingress backend successfully reloaded...
3.	Configmap is emptied again and its “resourceVersion” is increased
4.	I delete the nginx controller pod (yeah, I shouldn’t but imagine that something bad happens and the pod needs to be recreated)
5.	A new nginx pod is created
6.	This new pod does not inherit the configuration (configmap is empty!)
  
This behavior happens when nginx ingress controller is deployed and httpRouting addon is enabled.
 
How can we configure the proxy-buffers-size and proxy-buffers options of the NGINX? In a “standard” nginx controller you can create a configmap with those values using a ConfigMap but I don’t know how to do it using httpRouting addon.
 
We saw a configmap named:
 
addon-http-application-routing-nginx-configuration in the kube-system. This configmap is empty (0 data entries). I exported it YAML definition to a new file, and tried:
 
1.	Update it using kubectl apply from following file:
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: addon-http-application-routing-ingress-nginx
    kubernetes.io/cluster-service: "true"
  name: addon-http-application-routing-nginx-configuration
  namespace: kube-system
data:
  proxy-buffer-size: "128k"
  proxy-buffers: "4 256k"
 
2.	That updated the configmap successfully (I checked it). But when I restarted the pod that runs the nginx controller the controller, the configmap was recreated again empty.
3.	I tried also without killing the pod that runs the nginx controller, but this don’t work also.

**Comment by CESARDELATORRE** [comment]
Answer from AKS team:

This is expected behavior as indicated by the following annotation. 

    addonmanager.kubernetes.io/mode: Reconcile

We could possibly set it to Recreate and that would make it user-configurable but I’m not sure how we would go about supporting that.
---
... We still have this blocking issue ...

**Comment by CESARDELATORRE** [comment]
The point is that this is a blocking issue when using IndentityServer4 for the microservices/app because the headers sent by IDENTITY SERVER are too large for the by default config in NGINX, so when we’re returning from a login, we get a 500 http.

**Comment by jijiechen** [comment]
Any manual fix workaround?

**Comment by AceHack** [comment]
`kubectl get ing -n kube-system` never returns anything, it's looking for `ing` not `pod`

**Comment by eiximenis** [comment]
Closing.
This is solved and the procedure is documented in wiki,

**Comment by AceHack** [comment]
Can you send a link to the specific documentation?
