### ISSUE TITLE
Question: HealthChecks fail when behind Ingress Controller in K8S env

### ISSUE THREAD

**Issue by benbuckland** [dotnet-architecture/eShopOnContainers#692]
Hi, I have recently deployed the nginx ingress controller in the kubernetes AKS environment and now all requests to http://baseurl/servicename-api/hc fail with 404. The 404 message looks like it is coming dotnet core.
Is it due to this line `.UseHealthChecks("/hc") `in program.cs not taking into account PATH_BASE

Any ideas?

**Comment by eiximenis** [comment]
Closing because Healthchecks support is now implemented using netcore2.2 + Xabaril checkers.
