### ISSUE TITLE
Could not restore packages in a Mac (Visual Studio for Mac)

### ISSUE THREAD

**Issue by bassamtelli** [dotnet-architecture/eShopOnContainers#694]
i'm trying to build the eShopOnContainers-ServicesAndWebApps.sln on mac and i have could not restore packages error from visual studio.
Detected package downgrade: Microsoft.AspNetCore.SignalR from 1.0.1 to 1.0.0. Reference the package directly from the project to select a different version. 
 Ordering.SignalrHub (>= 1.0.0) -> Microsoft.AspNetCore.App (>= 2.1.1) -> Microsoft.AspNetCore.SignalR (>= 1.0.1 && < 1.1.0) 
 Ordering.SignalrHub (>= 1.0.0) -> Microsoft.AspNetCore.SignalR (>= 1.0.0)
Detected package downgrade: Microsoft.AspNetCore.SignalR.Core from 1.0.1 to 1.0.0. Reference the package directly from the project to select a different version. 
 Ordering.SignalrHub (>= 1.0.0) -> Microsoft.AspNetCore.App (>= 2.1.1) -> Microsoft.AspNetCore.SignalR.Core (>= 1.0.1 && < 1.1.0) 
 Ordering.SignalrHub (>= 1.0.0) -> Microsoft.AspNetCore.SignalR.Core (>= 1.0.0)

**Comment by CESARDELATORRE** [comment]
As additional info in order to isolate the issue.
Is it working for you in the Mac but simply using the .NET Core and Docker CLI?
Basically with docker-compose, etc. following this Wiki post: 
https://github.com/dotnet-architecture/eShopOnContainers/wiki/04.-Setting-eShopOnContainer-solution-up-in-a-Mac,-VS-for-Mac-or-with-CLI-environment--(dotnet-CLI,-Docker-CLI-and-VS-Code)

**Comment by bassamtelli** [comment]
Option A:  with docker-compose  it worked without any problems!
Option B: when using visual studio i had the error => Could not restore packages.

**Comment by rosi58** [comment]
Package restore fails for me also with this error: Restore failed in 3.55 sec for /Users/rolf/Documents/Dev/DotNet/eShopOnContainers-dev/src/Services/Ordering/Ordering.SignalrHub/Ordering.SignalrHub.csproj.

**Comment by sunny-sidhu** [comment]
I have the same issue.

**Comment by maxromanenko** [comment]
I had the same issue initially and overcame it by going through individual projects and doing Update on their dependencies. A few projects seemed to reference .Net Core 1.x assemblies, and I ended up removing those and adding the .Net Core 2.x versions. Laborious, but it worked. Look through the Package Console output and see where it fails and start with that project, then do another Restore.

**Comment by mvelosop** [comment]
Closing this issue as it seems stale, will reopen if needed.

**Comment by dapalmi** [comment]
Same issue when trying to debug via VS for Mac (v7.7.2)

**Comment by farhan7272** [comment]
same issue after installing .NET 5 on mac
