### ISSUE TITLE
Easiest Design Repository Sample for Better Understanding of Microservices for ASP.NET Core

### ISSUE THREAD

**Issue by ethlyseria** [dotnet-architecture/eShopOnContainers#695]
Good day sir,

For the past days, I've been reading and watching tutorials and videos about Microservices. I found them difficult to learn due to complex examples but I really want to learn Microservices for ASP.NET Core 2.1.

I'm using Monolithic Architecture for that past years even until now. Mostly my applications are written using ASP.NET Framework and ASP.NET Core 2.0.

I really want to learn Microservices for ASP.NET Core. Is there any simple repository with step-by-step with authorization on how to create Microservices on ASP.NET Core?

Thank you in advance.

**Comment by mvelosop** [comment]
Hi @ethlyseria, well... you've just come to the right place!

To begin with, I suggest you read this book: aka.ms/microservicesebook it has all the theory with a lot of details, references for further reading and a practical reference app that's in this repo.

While you read the book, begin taking a look at the code here and take the app for a spin, as per:  https://github.com/dotnet-architecture/eShopOnContainers/wiki#setting-up-your-development-environment-for-eshoponcontainers

You will need a computer with 8 GB RAM to barely run the containerized app using the CLI option, but it's really usable with VS at 16 GB RAM.

Please feel free to ask any questions here.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue, but feel free to comment, will reopen if needed.
