### ISSUE TITLE
I am not able to run eshoponcontainer without vs 2017

### ISSUE THREAD

**Issue by agmhomestore** [dotnet-architecture/eShopOnContainers#696]
Running the solution from VS 2017 everything works correctly, once I close/stop VS, I cannot access any of the web services at all, but I am able to connect to Redis, Mongo, MSSql, etc. It should be something related to docker that I do not know. (Newbie in docker). Could you help me to understand/learn why this happens?.

![image](https://user-images.githubusercontent.com/41838462/43671017-18a36376-9761-11e8-82f8-3a4aa26d32f4.png)

**Comment by CESARDELATORRE** [comment]
If you want to use the containers out or VS, build and start the containers with Docker-compose up.
The images built by VS cannot be run out of VS context, those images are especially made for debugging from VS.
Follow the CLI wiki post in order to use the CLI approach.

**Comment by agmhomestore** [comment]
I did it, but now I get "Error requesting catalog products, please try later on"

Error requesting catalog products, please try later on
![image](https://user-images.githubusercontent.com/41838462/43676235-325b5558-97bb-11e8-806a-5adcaea20c2a.png)


Thanks a lot and good day.

**Comment by agmhomestore** [comment]
The issue is that you have to select BRAND and TYPE, otherwise you get a crash.

**Comment by mvelosop** [comment]
Hi @agmhomestore,

The Catalog error has been fixed as of commit 5c06f6e5007411af02843c462bcb12258d282e34 from 31-JUL-2018.

Please update your repo and execute `docker-compose up` again.

Could you get the app running besides the catalog issue?
