### ISSUE TITLE
Can I send a message with eventbus in foreach loop? 

### ISSUE THREAD

**Issue by GloriaGloria** [dotnet-architecture/eShopOnContainers#699]
Hi:
when i try send message in OrderStatusChangedToAwaitingValidationIntegrationEventHandler like this:

   `

      public async Task Handle(OrderStatusChangedToAwaitingValidationIntegrationEvent command)

        {

            foreach (var orderStockItem in command.OrderStockItems)

            {

                var catalogItem = _catalogContext.CatalogItems.Find(orderStockItem.ProductId);

                var hasStock = catalogItem.AvailableStock >= orderStockItem.Units;

                var confirmedOrderStockItem = new ConfirmedOrderStockItem(catalogItem.Id, hasStock);

                var confirmedIntegrationEvent = !confirmedOrderStockItem.HasStock
                ? (IntegrationEvent)new OrderStockRejectedIntegrationEvent(command.OrderId, confirmedOrderStockItem)
                : new OrderStockConfirmedIntegrationEvent(command.OrderId);

                await _catalogIntegrationEventService.SaveEventAndCatalogContextChangesAsync(confirmedIntegrationEvent);
                await _catalogIntegrationEventService.PublishThroughEventBusAsync(confirmedIntegrationEvent);
            }
        }`
everytime  when i send message in this way,  the error occurred like this:

>  the connection is already in a transaction and can not participate in another transaction .
![image](https://user-images.githubusercontent.com/33510889/43748703-9437d76e-9a23-11e8-8ffa-a9abb5546398.png)

Can I write it like that or What should I do in this situation?
Look forward to your reply!
Thanks!

**Comment by mvelosop** [comment]
Hi @GloriaGloria,

It looks like the code you have is not current, it should be like this:

https://github.com/dotnet-architecture/eShopOnContainers/blob/a2bc8aa56777126d34cd0435195e8c040a91aef7/src/Services/Catalog/Catalog.API/IntegrationEvents/EventHandling/OrderStatusChangedToAwaitingValidationIntegrationEventHandler.cs#L29-L43

Hope this helps.

**Comment by GloriaGloria** [comment]
Hi @mvelosop ,
Thanks for your reply very much! there is no problem with your code, however , I want to send messages in foreach loop sometimes  just like the code i show in my question, so i just tried to change your code to try, and then I found it did not work correctly and the error occured. If I send message very frequently,the same error occured. So I want to know if there is any problem  to send messages with eventbus in that way, or what is the right way if I want to send message in foreach loop or very frequently?
Thanks, and hope your reply!

**Comment by mvelosop** [comment]
Hi @GloriaGloria,

This is somehow related to issue #700, so you might want to take a look at it.

Anyway, the general idea is that:

1. You save the integration events you are going to publish to a table in your microservice and then
2. Publish the events through your message bus (e.g. RabbitMQ) in a second transaction.

If your are going to publish several integration events, you could just keep a list of them and the publish them in another loop and in another transaction.

You will find a more detailed explanation at page 139 in https://aka.ms/microservicesebook

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue as it's not related to eShopOnContainers but feel free to comment.
