### ISSUE TITLE
Minor Pending Refactoring issues in Microservices

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#7]
- PENDING ISSUES
  - (Pending) This Change was lost in the migration-net.1.1 branch - Check it out.
Rename SeedWork to Seedwork. It should be "w" lowercase. It is just like Framework vs. FrameWork. Also, see: https://www.martinfowler.com/bliki/Seedwork.html 

- DONE  (Move here "done issues" from above, when done)
  - (DONE) Rename entity class Payment to <b>PaymentMethod</b> in the Ordering microservice: 
We are using just "Payment Methods". We don't really have any "Payment" in the current version of this app.

**Comment by SychevIgor** [comment]
@CESARDELATORRE I think if it's done we can close it?
