### ISSUE TITLE
[enhancement] ASP.NET Core update 

### ISSUE THREAD

**Issue by rafsanulhasan** [dotnet-architecture/eShopOnContainers#706]
@CESARDELATORRE, Update ASP.NET Core 2.1.0 to ASP.NET Core 2.1.1

**Comment by mvelosop** [comment]
Hi @rafsanulhasan,

The update will be done shortly, to 2.1.2 actually, as the eBook is being reviewed.

**Comment by rafsanulhasan** [comment]
Hi @mvelosop, 
Thanks for your quick reply. I have created a PR #702 to net21 branch. Could you please review it?

**Comment by mvelosop** [comment]
Thanks for the PR @rafsanulhasan, 👍

I will review, it'll take a while though 🙁!
