### ISSUE TITLE
Duplicate x-requestid headers injected on retries

### ISSUE THREAD

**Issue by stanoislav** [dotnet-architecture/eShopOnContainers#708]
The  ```HttpClientRequestIdDelegatingHandler``` is used to inject ```"x-requestid"``` HTTP header with a GUID value into requests made by HttpClient. This header is then used to detect duplicate requests on the receiver side.

However when the Polly retry policy kicks in, a new ```x-requestid``` is added on each retry, resulting in an array of ```x-requestid``` being received by the service.

The fix is to add a check if this header already exists, before injecting a new one

```csharp
public class HttpClientRequestIdDelegatingHandler: DelegatingHandler
    {
        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
   
            if (request.Method == HttpMethod.Post || request.Method == HttpMethod.Put)
            {
                if (!request.Headers.Contains("x-requestid"))
                {
                    request.Headers.Add("x-requestid", Guid.NewGuid().ToString());
                }
            }

            return await base.SendAsync(request, cancellationToken);
        }
    }
```

**Comment by mvelosop** [comment]
Hi @stanoislav, thanks for the heads-up 👍

Fixing it right away!
