### ISSUE TITLE
Make the Order Creation Idempotent at the CreateOrderCommandHandler

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#71]
If, due to any communications hiccup or any other reason the same CreateOrderCommand reaches the service, the actual code at the CreateOrderCommandHandler will probably create "the same" order, twice.
Need to review that code at CreateOrderCommandHandler in any case and refactor it.

This is a related issue about refactoring the code at CreateOrderCommandHandler:
https://github.com/dotnet/eShopOnContainers/issues/34 

The current code within the OrderRepository is the following, which doesn't look idempotent, not in the CommandHandler, not in the Repository:

        public Order Add(Order order)
        {
            return _context.Orders.Add(order)
                .Entity;
        }

**Comment by eiximenis** [comment]
Xamarin is updated already!

**Comment by CESARDELATORRE** [comment]
Still need some refactoring. The RequestManager shouldn't be within the Repositories folder, etc., as we talked.
