### ISSUE TITLE
Rash of Dependency and Project Load Errors...

### ISSUE THREAD

**Issue by robvet** [dotnet-architecture/eShopOnContainers#715]
Bad news...

Am getting a rash of dependency errors when opening the eShop solution. 

Some projects will not load giving the following error: "Project file is incomplete. Expected imports are missing"

Other projects do load, but do not build rendering the following build error:  The current .NET SDK does not support targeting .NET Standard 2.0.  Either target .NET Standard 1.6 or lower, or use a version of the .NET SDK that supports .NET Standard 2.0.

Getting same behavior on clone from last week as well as a clone downloaded tonight (8/20).

Any help would be greatly appreciated.

Rob Vettor (robvet@microsoft.com)

![error1](https://user-images.githubusercontent.com/4884576/44379994-45852b00-a4f8-11e8-8ed6-34e1b67d07d8.png)
hubusercontent.com/4884576/44379803-2f2a9f80-a4f7-11e8-8ae3-7b55d370af7d.png)

**Comment by rafsanulhasan** [comment]
Could you please specify the projets' names which fail loading. If it include projects: Identity.API, WebMVC and WebStatus, add a line in the .bowerrc of those projects:

_registry: "https://registry.bower.io"._

If this process does not solve you problem, you can edit the projects' files itself and replace the following line:
`<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0" />`
with
`<PackageReference Include="Microsoft.AspNetCore.App" />`

**Comment by robvet** [comment]
Thanks Rafsanul for reacking out.

Turned out there is a Glolbal.json file in the solution locking the .NET Core version at 2.1.300.

"sdk": {
"version": "2.1.300"
}

My laptop (freshly reimaged) has 2.1.400.  Would have thought that the runtime would automatically move to newest version if the targeted version could not be found, but it didn't, and instead errored.

Change the version to 2.1.400 and solution loads correctly and builds.

Thanks again for jumping in.

**Comment by mvelosop** [comment]
Hi @robvet,

You could also try installing [SDK v2.1.302](https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.302-windows-x64-installer), that way it the app will not break again when you update from the repo.

According to what I understand from the:
- [.NET Core version selection policies](https://docs.microsoft.com/en-us/dotnet/core/versions/selection) and the 
- [.NET Core 2.1 Releases](https://www.microsoft.com/net/download/dotnet-core/2.1) 

That should not happen! so it looks like there's something I don't quite understand yet 😣

Closing the issue now but feel free to comment.

**Comment by Minx-SigEp** [comment]
For anyone else. Installing SDK v2.1.302 solved the issue. I had to restart my machine before the SDK was available for use by Visual Studio.
