### ISSUE TITLE
"Back-off restarting failed container" for nginx-ingress-controller because of "cluster it is running with Authorization enabled (like RBAC)"

### ISSUE THREAD

**Issue by grest** [dotnet-architecture/eShopOnContainers#716]
After running Step 10. and deploy-ingress & deploy-ingress-azure the nginx-ingress-controller is in error state with comment "back-off restarting failed container".
Logs are suggesting problems with RBAC, however it should not be the case as I understand because deploy-ingress-azure script should solve this issue.

-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:    0.9.0
  Build:      git-6816630
  Repository: https://github.com/kubernetes/ingress-nginx
-------------------------------------------------------------------------------
 I0822 06:47:24.184769       5 main.go:227] Creating API client for https://10.0.0.1:443
I0822 06:47:24.242301       5 main.go:239] Running in Kubernetes Cluster version v1.9 (v1.9.9) - git (clean) commit 57729ea3d9a1b75f3fc7bbbadc597ba707d47c8a - platform linux/amd64
**F0822 06:47:24.269656       5 main.go:79] ✖ It seems the cluster it is running with Authorization enabled (like RBAC) and there is no permissions for the ingress controller. Please check the configuration**

**Comment by mvelosop** [comment]
Closing this issue as outdated.
