### ISSUE TITLE
Why is there no architecture that can compete with spring cloud?

### ISSUE THREAD

**Issue by YINZHU2016** [dotnet-architecture/eShopOnContainers#717]
Hello author, I would like to ask why Microsoft does not consider a set of micro-services full-featured barrel architecture that is comparable to spring cloud. I am a Chinese development engineer. Our country is in a dominant position, and .net may be a second-class citizen. We chose .NET and wanted to be a good employee of .NET, but we don't have a micro-service whole-box architecture now. This makes us very difficult. Many times, we are despised by other Java engineers. I hope that Microsoft will face this problem more and more. It is only a component of microservices in Ocelot. It is really sad to tell the truth and spring cloud.

You spend so much time building elegant .NET syntax, why not take the time to build the elegant architecture of .NET?

Thank you

**Comment by davidfowl** [comment]
Have you seen https://steeltoe.io/?

**Comment by YINZHU2016** [comment]
Yes, I have referred to steeltoe, which can connect.Net core to spring cloud.

But it is not supported by spring, which is just like a little daughter-in-law. There may be no support on that day. And the environment in our country is java because of its good ecological environment, so all aspects are very advantageous, even a low coding level Java Engineer will be higher than a skilled. net engineer, the main reason is that every time something popular, the. net can not come up with a reliable and elegant solution .

**Comment by davidfowl** [comment]
> But it is not supported by spring, which is just like a little daughter-in-law. There may be no support on that day. 

It's supported by pivotal right? What exactly do you mean?

> And the environment in our country is java because of its good ecological environment, so all aspects are very advantageous, even a low coding level Java Engineer will be higher than a skilled. net engineer, the main reason is that every time something popular, the. net can not come up with a reliable and elegant solution .

I assume you're talking about the .NET ecosystem in general?

**Comment by michael-nee** [comment]
.NET varies between countries, just because it's a "second class citizen" in China doesn't mean it's not elsewhere.   It's made leaps and bounds since .NET Core but still has a little more to go.  There's advantages and disadvantages to Java and C# .NET but both are very good languages.

**Comment by CESARDELATORRE** [comment]
@YINZHU2016 - About Microservices Architecture, this related guidance is precisely about it:

https://aka.ms/microservicesebook

I assume you're asking more about specific frameworks and building-blocks especially made for microservices? - About that, the .NET Core roadmap has additional components planned targeting microservices' features. As soon as the list for that roadmap is publicly available, I'll copy that into this thread.

I'm closing this thread as your question is not about any specific issue in eShopOnContainers but a global question about .NET Core.
Thanks for the feedback. I agree that we can improve in that area (prescriptive frameworks for microservice architecture) and we're working on it. 👍
