### ISSUE TITLE
can't parse class that inherits from enumeration

### ISSUE THREAD

**Issue by sanderobdeijn** [dotnet-architecture/eShopOnContainers#718]
I have used the Enumeration class in the seedworks folder to create my own class.

I select an enum from this class and store its display name into a variable. Then the use the FromDisplayName method in the enumeration class to parse the string back into an enum. But then it can't find the enum.
When debugging I found that in the GetAll method it searches for all public fields.
var fields = typeof(T).GetFields(BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly);
This statement return an empty list, because all the fields are backing fields and are private. If I want the public properties I have to go to the GetProperties method. Am I doing something wrong or is there an bug in this base class?

**Comment by mvelosop** [comment]
Hi @sanderobdeijn,

A PR was accepted involving the Enumeration class on AUG-17 but it didn't cause any problem with the codebase.

Are you using a version before or after that date?

**Comment by sanderobdeijn** [comment]
I have update my class today and the issue persists

**Comment by mvelosop** [comment]
Could you post some output, error logs or something to take a look at the problem?

**Comment by mvelosop** [comment]
Closing this issue now as it seems stale, will reopen if needed.

**Comment by sanderobdeijn** [comment]
Sorry I have been on vacation and haven't touched my computer for a month.

I have created an test class.
    using System.Collections.Generic;
    
    public class TestEnumeration : Enumeration
    {
        public TestEnumeration(int id, string name)
        : base(id, name)
        {
        }
    
        protected TestEnumeration()
        {
        }
    
        public static TestEnumeration First { get; private set; } = new TestEnumeration(2, "first");
    
        public static TestEnumeration Second { get; private set; } = new TestEnumeration(1, "second");
    
        public static IEnumerable<TestEnumeration> List()
        {
            return new[] { First, Second };
        }
    }

Then if try to parse it from its name I get an exception.

    var enumName = TestEnumeration.First.Name;
    TestEnumeration.FromDisplayName<TestEnumeration>(enumName);

The exception I get is: 
Message: System.InvalidOperationException : 'first' is not a valid display name in TestEnumeration

**Comment by sanderobdeijn** [comment]
@mvelosop Could you reopen this issue?

**Comment by TsengSR** [comment]
@sanderobdeijn: its not an issue with the code, its an issue with your implementation. 

Check the [source](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.Domain/SeedWork/Enumeration.cs#L25-L30) of `Enumeration` class

```
        public static IEnumerable<T> GetAll<T>() where T : Enumeration
        {
            var fields = typeof(T).GetFields(BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly);

            return fields.Select(f => f.GetValue(null)).Cast<T>();
        }
```
it is searching for **fields**, you have declared your Enums as **Property**. 

Change

```
    public static TestEnumeration First { get; private set; } = new TestEnumeration(2, "first");

    public static TestEnumeration Second { get; private set; } = new TestEnumeration(1, "second");`
```

to 

```
    public static TestEnumeration First = new TestEnumeration(2, "first");

    public static TestEnumeration Second = new TestEnumeration(1, "second");
```

And it should work. Also see the [docs](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types) for `Enumeration` class for a proper example
