### ISSUE TITLE
[Feature Request] in asp.net core 2.2 health check API is a native part.

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#719]
In a future release, it will be nice, if we will use native dll instead of our custome rhttps://blogs.msdn.microsoft.com/webdev/2018/08/22/asp-net-core-2-2-0-preview1-healthcheck/

**Comment by li0nsar3c00l** [comment]
It's part of the roadmap for ASP.NET Core 2.2 https://github.com/aspnet/Announcements/issues/307
and for further information, check the repo itself https://github.com/dotnet-architecture/HealthChecks

**Comment by unaizorrilla** [comment]
Better if use a oss library with more features, ie BeatPulse   Http://github.com/Xabaril/BeatPulse

**Comment by SychevIgor** [comment]
@li0nsar3c00l "In a future release" (C)- future is future

**Comment by SychevIgor** [comment]
@unaizorrilla looks really nice.

**Comment by mvelosop** [comment]
I even suggested it to @CESARDELATORRE! 😉

**Comment by SychevIgor** [comment]
@CESARDELATORRE @mvelosop asp.net core 2.2 in GA. we can again look on this idea.

**Comment by CESARDELATORRE** [comment]
Hey @sychevlgor - We already implemented the new ASP.NET Core 2.2 Healthchecks in eShopOn Containers but it is still in a different branch along with the upgrade to .NET C. When
