### ISSUE TITLE
Always generates  none imagea when build on Ubuntu 17.10

### ISSUE THREAD

**Issue by minhvc** [dotnet-architecture/eShopOnContainers#723]
It's strange every time I build the code, always has generated many name = none, tag = none images 1.8GB How can I fix it?
Thanks
![image](https://user-images.githubusercontent.com/4718379/44699546-eb173c00-aaae-11e8-8508-394b6cca6f2f.png)

**Comment by unaizorrilla** [comment]
It is dangling docker images you can delete it using the next poewershekk command:

docker rmi $(docker images -p -q —filter “dangling=true”)

**Comment by minhvc** [comment]
yes, I know but I do not want to do that every time I build code.

**Comment by mvelosop** [comment]
Hi @minhvc,

That's just the way Docker works.

Dangling means an image lost it's tag because a new one, from a more recent build, took it away (e.g. latest).

It's just like temp files you have to clean them every now and then!

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue, will reopen if needed.
