### ISSUE TITLE
Question: Validation in DDD

### ISSUE THREAD

**Issue by ig16022** [dotnet-architecture/eShopOnContainers#731]
The companion book for this solution heavily emphasizes the importance of an Aggregate root being the 'gateway', which means the Aggregate root is responsible for validating all incoming data. I see a comment in Order aggregate, on the AddOrderItem() method that says:

 // DDD Patterns comment
 /* This Order AggregateRoot's method "AddOrderitem()" should be the only way to add Items to the Order, so any behavior (discounts, etc.) and validations are controlled by the AggregateRoot in order to maintain consistency between the whole Aggregate. */
 public void AddOrderItem(int productId, string productName, decimal unitPrice, decimal discount, string pictureUrl, int units = 1)
....

But the validation appears to be triggered on the Command Handler, through a MediatR behavior (CreateOrderCommandValidator). This seems odd, as there may be additional channels that eventually trigger AddOrderItem() on an Order aggregate. Does this not violate the described DDD Pattern requirement?

**Comment by CESARDELATORRE** [comment]
It is arguable in the same way that you can also do data validation in the client side, too.
See these blog posts from Jimmy Bogard and other folks:
https://jimmybogard.com/domain-command-patterns-validation/
https://lostechies.com/jimmybogard/2016/04/29/validation-inside-or-outside-entities/

The point is to have a defined place for doing it, not distributed across the internal entities or in random code in the application layer. 
If you put validations in the MediatR behaviour, that is also a very defined/specific place which offers benefits as explained in the posts I say above.
Both places, Behaviours or Aggregate-Roots can be valid. 
In the Guide, when talking about Aggregate-Roots it focuses just on them. If you were not to use MediatR, that is the place, too.
Clsing this issue, ok?

**Comment by ig16022** [comment]
Ok. Thanks for the quick response.
