### ISSUE TITLE
Replace Razor syntaxes with TagHelpers

### ISSUE THREAD

**Issue by rafsanulhasan** [dotnet-architecture/eShopOnContainers#743]
@CESARDELATORRE @mvelosop @eiximenis, The latest ASP.NET Core docs suggests using TagHelpers instead of Razor syntax. 

### From _Razor syntax_

> `@{await Html.PartialAsync(string)}` and
> `@Html.Partial(string)`

### To _TagHelper_
> `<partial name="string" model="property" for="modelExpression" />`

I've done this in the PR (#742)

**Comment by rafsanulhasan** [comment]
@CESARDELATORRE, Could you please review it?

**Comment by mvelosop** [comment]
Closing this issue, for the related PR is closed too, will reopen if needed.
