### ISSUE TITLE
Services are down too frequently

### ISSUE THREAD

**Issue by iliassays** [dotnet-architecture/eShopOnContainers#745]
Hello

When I load first time, all the service works perfectly. After some time, service automatically stopped and I cannot browse site due to error.

.
![unhealthy](https://user-images.githubusercontent.com/3203987/44984617-4c537980-af9f-11e8-86a5-04dde9e2f88c.PNG)

**Comment by CESARDELATORRE** [comment]
@iliassays - What specific errors are you getting?

**Comment by mvelosop** [comment]
Hi @iliassays, 

I've had this situation when trying to run in an 8 GB laptop, could that be your case?

**Comment by mvelosop** [comment]
Closing this issue will reopen if needed.
