### ISSUE TITLE
Unable to list Kubernetes resources using default ASK create script

### ISSUE THREAD

**Issue by NileshGule** [dotnet-architecture/eShopOnContainers#749]
I have deployed a AKS cluster using the steps mentioned in the setting up of solution in AKS wiki page
https://github.com/dotnet-architecture/eShopOnContainers/wiki/10.-Setting-the-solution-up-in-AKS-(Azure-Kubernetes-Service)

I used the following Powershelgl script to provision the AKS cluster
```code

./gen-k8s-env-aks `
-resourceGroupName dncsgeShopAksResgroup `
-location "South East Asia" `
-serviceName dncsgeeShopAksCluster `
-dnsNamePrefix dncsgeeshopaks `
-registryName dncsgeeShopAcrRegistry `
-createAcr true `
-nodeCount 3 `
-nodeVMSize Standard_D2_v2

```

At the time of accessing the resources using kubectl proxy, I get error / warning as shown below
![aks unable to list resources](https://user-images.githubusercontent.com/1298374/45090238-60cf7780-b141-11e8-97c1-1ac6efb265c3.png)

Looks like the issue is related to RBAC. Do we need to disable RBAC at the time of creating the AKS cluster?

**Comment by NileshGule** [comment]
I managed to access the cluster resources if I disable the RBAC at the time of creating the ASK cluster in the `gen-k8s-env-aks.ps1` script. The changed script is 

```code

az aks create `
--resource-group=$resourceGroupName `
--name=$serviceName `
--dns-name-prefix=$dnsNamePrefix `
--generate-ssh-keys `
--node-count=$nodeCount `
--node-vm-size=$nodeVMSize `
--disable-rbac

```

After recreating the cluster, I get the output as
![aks access resources without rbac](https://user-images.githubusercontent.com/1298374/45091274-7befb680-b144-11e8-96f9-58fb8acaecc3.png)

**Comment by eiximenis** [comment]
Hi @NileshGule 
Instead of disabling RBAC in the cluster you can give dashboard-ui pod enough permissions to view the resources:

```
kubectl create clusterrolebinding kubernetes-dashboard -n kube-system --clusterrole=cluster-admin --serviceaccount=kube-system:kubernetes-dashboard
```
