### ISSUE TITLE
Is there any plan to use the integrated event library?

### ISSUE THREAD

**Issue by yang-xiaodong** [dotnet-architecture/eShopOnContainers#753]
Hello, eShop team:

I created a library CAP ( [https://github.com/dotnetcore/CAP](https://github.com/dotnetcore/CAP) ) about the integration event of EventBus, which has been created for more than one year, currently there are 13k+ downloads in NuGet. It has been running in our production environment for a few months and works well.

There are some bugs (#721, #700) in the eShop integrated event module. In CAP, we solve these problems and implements the Outbox pattern described in the [eShop ebook](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/multi-container-microservice-net-applications/subscribe-events#designing-atomicity-and-resiliency-when-publishing-to-the-event-bus) with  atomicity and resiliency.

CAP currently supports Kafka and RabbitMQ as the message queues, and support SQL Server, MySQL, PostgreSQL, and MongoDB 4.0+ as microservices business database.

As a Microsoft MVP, I hope more people can use the library and be able to help them, If eShop is willing to use it, it will spread faster. :)

If you are interested, I would be happy to submit a PR to help eShop complete the integration work.

Please let me know if you have any questions, looking forward to your reply.

**Comment by eiximenis** [comment]
Adding @CESARDELATORRE

**Comment by yang-xiaodong** [comment]
no response , close

**Comment by yang-xiaodong** [comment]
Reopen for discussion

**Comment by mvelosop** [comment]
Hi @yang-xiaodong, please see [my comment on PR #970](https://github.com/dotnet-architecture/eShopOnContainers/pull/970#issuecomment-472833963)

**Comment by mvelosop** [comment]
Closing this issue now, since this will be handled as per @CESARDELATORRE's [comment](https://github.com/dotnet-architecture/eShopOnContainers/pull/970#issuecomment-474924473)
