### ISSUE TITLE
I am getting the below error when i try to build the Solution. Detected package downgrade: Microsoft.ApplicationInsights.ServiceFabric from 2.1.1 to 2.1.1-beta1. Reference the package directly from the project to select a different version.   WebStatus -> Microsoft.Extensions.HealthChecks -> Microsoft.ApplicationInsights.ServiceFabric (>= 2.1.1)   WebStatus -> Microsoft.ApplicationInsights.ServiceFabric (>= 2.1.1-beta1)

### ISSUE THREAD

**Issue by chengal9596** [dotnet-architecture/eShopOnContainers#754]
I am getting the below error when i try to build the Solution.
Detected package downgrade: Microsoft.ApplicationInsights.ServiceFabric from 2.1.1 to 2.1.1-beta1. Reference the package directly from the project to select a different version. 
 WebStatus -> Microsoft.Extensions.HealthChecks -> Microsoft.ApplicationInsights.ServiceFabric (>= 2.1.1) 
 WebStatus -> Microsoft.ApplicationInsights.ServiceFabric (>= 2.1.1-beta1)

**Comment by rafsanulhasan** [comment]
@chengal9596 IMHO, you have to update outdated NuGet packages to resolve this problem

**Comment by chengal9596** [comment]
It is working. Hence closing this
