### ISSUE TITLE
Could you please provide the more details on the Centralised Logging Mechanism and if there are any Best practices for Logging in Microservices.

### ISSUE THREAD

**Issue by chengal9596** [dotnet-architecture/eShopOnContainers#759]

**Comment by chengal9596** [comment]
Any update on this ?

**Comment by plukawski** [comment]
Locally I have managed to add nlog to every project and set up the target to nlogviewer to point to `tcp4://host.docker.internal:4505` address in `nlog.config` file. Thanks to that I can easily view all the logs from all the container on my host machine using Log2Console for example. If you think that his is a good idea to have something like that, then tell me so I can create a PR with my solution.

**Comment by nishanil** [comment]
Hey! Thanks for the feedback. We are currently working on including a better logging mechanism to this sample. We are inclining towards Serilog and plan to get this out alongside .NET core 2.2 updates. I will update this thread when we merge the changes in.

**Comment by mvelosop** [comment]
Hi @chengal9596,

We now have a centralized logging system in eShopOnContainers.

You can take a look at PR https://github.com/dotnet-architecture/eShopOnContainers/pull/952, now merged into **dev**, and also at the wiki page [18. Centralized Structured Logging in eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers/wiki/18.-Centralized-Structured-Logging-in-eShopOnContainers).

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
