### ISSUE TITLE
Typo in CatalogItem - line 67

### ISSUE THREAD

**Issue by johnfg10** [dotnet-architecture/eShopOnContainers#760]
Hello,
I was reading through and noticed a small typo in `src/Services/Catalog/Catalog.API/Model/CatalogItem.cs` on line 67, it says cero instead of zero. I haven't made a pull request as it seems too trivial but thought I would mention it.

**Comment by CESARDELATORRE** [comment]
Feel free to do PRs for typos, too.
Other than that, when revisiting issues, we’ll fix it

**Comment by rafsanulhasan** [comment]
The fix for this issue is included in PR #764

**Comment by mvelosop** [comment]
Closing the issue, related PR is closed too. will reopen if needed.
