### ISSUE TITLE
eShop on Service fabric issue

### ISSUE THREAD

**Issue by harrchen88** [dotnet-architecture/eShopOnContainers#761]
Tried to deploy to 5 node Linux SF.  All applications seems to deploy fine but when trying to access MVC, got error 
InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.
System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)

Health check results:
Overall Status: Unhealthy
UrlCheck(http://orderingapi.eshoponservicefabric:5102/hc)
http://orderingapi.eshoponservicefabric:5102/hc

status code ServiceUnavailable (503)

Unhealthy
UrlCheck(http://localhost:5111/hc)
http://localhost:5111/hc

Exception during check: System.Net.Http.HttpRequestException

Unhealthy
UrlCheck(http://basketapi.eshoponservicefabric:5103/hc)
http://basketapi.eshoponservicefabric:5103/hc

status code OK (200)

Healthy
UrlCheck(http://catalogapi.eshoponservicefabric:5101/hc)
http://catalogapi.eshoponservicefabric:5101/hc

status code InternalServerError (500)

Unhealthy
UrlCheck(http://identityapi.eshoponservicefabric:5105/hc)
http://identityapi.eshoponservicefabric:5105/hc

status code ServiceUnavailable (503)

Unhealthy
UrlCheck(http://locationsapi.eshoponservicefabric:5109/hc)
http://locationsapi.eshoponservicefabric:5109/hc

status code OK (200)

Healthy
UrlCheck(http://marketingapi.eshoponservicefabric:5110/hc)
http://marketingapi.eshoponservicefabric:5110/hc

status code OK (200)

Healthy
UrlCheck(http://paymentapi.eshoponservicefabric:5108/hc)
http://paymentapi.eshoponservicefabric:5108/hc

status code OK (200)

Healthy
UrlCheck(http://webmvc.eshoponservicefabric:5100/hc)
http://webmvc.eshoponservicefabric:5100/hc

status code ServiceUnavailable (503)

Unhealthy
UrlCheck(http://webspa.eshoponservicefabric:5104/hc)
http://webspa.eshoponservicefabric:5104/hc

Exception during check: System.Net.Http.HttpRequestException

Unhealthy

**Comment by mvelosop** [comment]
Hi @harrchen88, I know this is an old issue, but an error like this could be traced to HealthChecks and was solved, could you please try this again with the latest **dev** commit?

**Comment by mvelosop** [comment]
Closing this issue now, but feel free to comment, will reopen if needed.
