### ISSUE TITLE
Typos  Ordering.Domain/AggregatesModel/OrderAggregate/OrderStatus.cs - line 4

### ISSUE THREAD

**Issue by rafsanulhasan** [dotnet-architecture/eShopOnContainers#763]
Hello @CESARDELATORRE @eiximenis, 
I was reading through and noticed a small typo in:
- [x] `src/Services/Ordering/Ordering.Domain/AggregatesModel/OrderAggregate/OrderStatus.cs` on line 4, it imports namespace 'Seedwork' instead of 'SeedWork'. (compilation error)

**Comment by CESARDELATORRE** [comment]
I don't see that. Can you do a "git pull" and check it out and double check?
The only reference to SeeWork in there is this, which looks right:

https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.Domain/AggregatesModel/OrderAggregate/OrderStatus.cs#L4

using Microsoft.eShopOnContainers.Services.Ordering.Domain.SeedWork;

Closing the issue. Re-open if needed..

**Comment by rafsanulhasan** [comment]
Please re-open the issue as I pull in the previous change and made it simplified. It was my mistake to pushing before pulling the new one. I should have said it "Simplify namespace" rather than typo. as Code analysis suggest the namespace imported in a class should be as simple as possible.
Here I'm using SeedWork instead of Microsoft.eShopOnContainers.Services.Ordering.Domain.SeedWork;

**Comment by mvelosop** [comment]
Hi @rafsanulhasan, 

The change to the fully qualified namespace was needed because after commit 4509153ca2706978f0f0d8bb268e8470e7e808d0, for an reason I don't yet understand, using the simplified namespace resulted in a compile error.

So the simplified name can't be used.

**Comment by rafsanulhasan** [comment]
Hi @mvelosop,
In Line 4 of that commit [`4509153`](https://github.com/dotnet-architecture/eShopOnContainers/commit/4509153ca2706978f0f0d8bb268e8470e7e808d0#L4), its `Seedwork`. IMHO the compilation error happens because this is typo I opened the issue for. iIt should be `SeedWork` instead of `Seedwork`.
