### ISSUE TITLE
Use port 80 for the internal ports used by each microservice

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#77]
It looks much better if we use port 80 for each of the services/containers for the internal communication (except SQL). This was also feedback from the Docker Tooling team and I agree on that.
We actually were using por 80 in the initial versions..
Need to change at 
https://github.com/dotnet/eShopOnContainers/blob/master/docker-compose.override.yml 
and test it.

For the external ports (to be used from the Xamarin app and the SPA app), let's maintain the same ports, for now.

**Comment by eiximenis** [comment]
This is done in dev branch.

Commit 827018fe99696f41f8ab8b46af4546c030acad68

**Comment by CESARDELATORRE** [comment]
Closing this issue.
