### ISSUE TITLE
My Visual Studio Application(eShopOnContainers) will get hanged frequently when i start debugging the application

### ISSUE THREAD

**Issue by chengal9596** [dotnet-architecture/eShopOnContainers#773]
My Visual Studio Application(eShopOnContainers) will get hanged frequently when i start debugging the application. Please find the screenshot for more details.

![image](https://user-images.githubusercontent.com/29713192/45671327-cd377700-bb42-11e8-8255-652724dcf2ef.png)

**Comment by rafsanulhasan** [comment]
You have to allocate at least 4 GB of RAM to Docker to be able to run the app because it uses a lot of Hardware resource.

**Comment by CESARDELATORRE** [comment]
Please, check the recommended development machine requirements in the Wiki:
https://github.com/dotnet-architecture/eShopOnContainers/wiki/00.-Dev-machine-requirements

Closing this for now if the issue was related to hardware/memory assigned to Docker.
