### ISSUE TITLE
Signalr Ordering.SignalrHub.NotificationsHub OnDisconnectedAsync() 

### ISSUE THREAD

**Issue by sunbyfan** [dotnet-architecture/eShopOnContainers#778]
I don't understand OnDisconnectedAsync Groups.AddToGroupAsync(),but not RemoveFromGroupAsync()

**Comment by mvelosop** [comment]
Hi @sunbyfan,

Hummm, I don't either! @unaizorrilla, could you please take a look at line 22 here:
https://github.com/dotnet-architecture/eShopOnContainers/blob/96cabfec23d8565a14519e1ff555eede05b2095b/src/Services/Ordering/Ordering.SignalrHub/NotificationHub.cs#L11-L25

**Comment by mvelosop** [comment]
Hi @sunbyfan,

It's a confirmed bug, just let me know if you'd like to create a PR to fix it!

**Comment by libPhipp** [comment]
Hi all,
I have created pull request #825 to fix this.

Best,
Philip
