### ISSUE TITLE
I am getting an error after adding the new microservice - The Compose file is Invalid because the compose file is invalid because service is neither an image nor a build context specified

### ISSUE THREAD

**Issue by chengal9596** [dotnet-architecture/eShopOnContainers#779]
I am getting an error after adding the new microservice - The Compose file is Invalid because the compose file is invalid because service is neither an image nor a build context specified

Please find the attached screenshot for more details...

![image](https://user-images.githubusercontent.com/29713192/45820631-db34f580-bd04-11e8-9f60-bd4b62709839.png)

**Comment by mvelosop** [comment]
Hi @chengal9596,

Could you post some details on what you are doing?

Did you follow the steps in https://github.com/dotnet-architecture/eShopOnContainers/wiki#setting-up-your-development-environment-for-eshoponcontainers?

**Comment by mvelosop** [comment]
Closing this issue as it seems stale now. Will reopen if needed.
