### ISSUE TITLE
SignalR not working in an AKS/Kuberentes deployed solution

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#782]
The SignalR pop-up tooltips are not working when testing the solution in AKS (Kuberentes)

It doesn't work in the **MVC** app, neither in the **SPA** app.

For instance, not showing the pop-up windows after submitting an order:

![image](https://user-images.githubusercontent.com/1712635/45986967-e194db80-c03c-11e8-9173-241ff684a6f1.png)

**Comment by ramonTC** [comment]
Bug fixed in branch #782-Fix-SignalR-aks and ready to be merged to Dev
