### ISSUE TITLE
Mobile EventToCommandBehavior can not be pass parameter by EventArgsConverter

### ISSUE THREAD

**Issue by jingliancui** [dotnet-architecture/eShopOnContainers#787]
eShopOnContainers/src/Mobile/eShopOnContainers/eShopOnContainers.Core/Behaviors/EventToCommandBehavior.cs 

after use this code with behavior, it's can not pass parameter to the C# converter.

but after use this [link](https://github.com/xamarin/xamarin-forms-samples/blob/master/Behaviors/EventToCommandBehavior/EventToCommandBehavior/Behaviors/EventToCommandBehavior.cs) from docs.microsoft.com's this helper [link](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/reusable/event-to-command-behavior#overview),it's done.

**Comment by mvelosop** [comment]
Hi @jingliancui, I know this has been open for some time now, but I'm not clear if this is related to an issue in the mobile apps in eShopOnContainers or something else.

Could you clarify, please?

**Comment by jingliancui** [comment]
this is not issue in the app,or maybe,because i had not test the app.
Its the issue within the class,I just want use class,so I copy the class for used.
Then i found this issue

**Comment by mvelosop** [comment]
Thanks for the clarification @jingliancui.

I'm closing the issue now as not directly related to eShopOnContainers.
