### ISSUE TITLE
Property change on derived class never occurs in mobile app

### ISSUE THREAD

**Issue by davidbritch** [dotnet-architecture/eShopOnContainers#793]
Original issue: https://github.com/MicrosoftDocs/xamarin-docs/issues/806

Property change on derived class never occured, becouse ValidatableObject has its own inner T type 'Value' property
public ValidatableObject<string> UserName
{
get
{
return _userName;
}
set
{
_userName = value;
RaisePropertyChanged(() => UserName); // this is not triggered
}
}
RaisePropertyChange indeed occure in ValidatableObject base class but i need to do some logic when UserName.Value changed in my ModeView class not in ValidatableObject base class.

**Comment by aliegeni** [comment]
As ugly workaround you can add event listener to validatable object itself when instatiating validatable properties for view model: 
```
string  UserName = new ValidatableObject<string> { Validations = { new IsNotNullOrEmptyRule<string> { ValidationMessage = "my error message" } } };
UserName.PropertyChanged += (sender, args) => RaisePropertyChanged(nameof(UserName));
```

**Comment by mvelosop** [comment]
Closed as outdated.
