### ISSUE TITLE
Some plan to some Service Mesh like Istio?

### ISSUE THREAD

**Issue by alexsandro-xpt** [dotnet-architecture/eShopOnContainers#796]
Under AKS deployment, are you have some plan to configure some Service Mesh like Istio at this project?

I would like some kind of config implementation under this project of that.

**Comment by CESARDELATORRE** [comment]
@alexsandro-xpt - Good question. We might do it in the future but have other priorities in the backlog, first.
Also, we'll have deployment in Azure Service Fabric Mesh which already provides mesh capabilities out-of-the-box, based on Envoy.

**Comment by mvelosop** [comment]
It looks like the conversation ended, so I'm closing this issue now. Feel free to comment, will reopen if needed.

**Comment by freeborn5** [comment]
Is there a new eshop that does not use RabbitMQ and uses sidecars service mesh of some sort

**Comment by davidfowl** [comment]
How are service meshes a replacement for rabbitmq?
