### ISSUE TITLE
Newtonsoft compatibility

### ISSUE THREAD

**Issue by zeekay18** [dotnet-architecture/eShopOnContainers#798]
I get the following error when trying to build the project after cloning the source:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Newtonsoft.Json 11.0.2 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Newtonsoft.Json 11.0.2 does not support any target frameworks.	Ordering.FunctionalTests	C:\Source\eShopOnContainers\src\Services\Ordering\Ordering.FunctionalTests\Ordering.FunctionalTests.csproj	1

**Comment by Jacrys** [comment]
Did you do a `dotnet restore` prior to the build?   I just cloned, restored and built fine.  What is the output of `dotnet --list-sdks`?

**Comment by unaizorrilla** [comment]
Oki

Enviado desde mi iPhone

El 5 oct 2018, a las 18:31, Keith Lewis <notifications@github.com<mailto:notifications@github.com>> escribió:


Did you do a dotnet restore prior to the build? I just cloned, restored and built fine. What is the output of dotnet --list-sdks?

**Comment by zeekay18** [comment]
Hi,

I'm still facing the issue with the Newtonsoft.Json 11.0.2.
This is the output from dotnet --list-sdks:
2.1.201 [C:\Program Files\dotnet\sdk]
2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]
2.1.403 [C:\Program Files\dotnet\sdk]

**Comment by zeekay18** [comment]
Hi, i just forked the repo then cloned it. but i'm still facing this issue.

**Error	NU1202	Package Newtonsoft.Json 11.0.2 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Newtonsoft.Json 11.0.2 does not support any target frameworks**. 

Does anyone have a solution to this?

**Comment by zeekay18** [comment]
This is working now. I had to clear my nuget cache to fix this.
