### ISSUE TITLE
Test for Integrarion Event Handlers

### ISSUE THREAD

**Issue by Pixelario** [dotnet-architecture/eShopOnContainers#801]
Hello, in the code I did not find any test that check the results of a Integration Event Handler.
It would be very useful to have it

regards

**Comment by CESARDELATORRE** [comment]
@Pixelario - I agree! 👍 If you have the time, feel free to create a PR extending the Functional tests for the services, here:

https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/test/ServicesTests/Application.FunctionalTests

**Comment by mvelosop** [comment]
It would certainly help with issues like #667!

It looks like the conversation ended, so I'm closing this issue now. Feel free to comment, will reopen if needed.
