### ISSUE TITLE
Team structure running eShopOnContainers

### ISSUE THREAD

**Issue by IoTFier** [dotnet-architecture/eShopOnContainers#804]
Hello there!

What an amazing reference application put together by you all. Thank you and Microsoft, for such an amazing work and help to the community.

Will it be possible for you to share with us the actual org structure by roles, application tier, releases engaged internally for delivery of this entire repo ?

Also,  
1. is there a plan to host these solution in Azure DevOps? 
2. In your org structure will you please also outline your team / org model that will outline operation management ?

I would love to use that as one of the references in the planning of my initiative which is architecting using layers and tiers as mentioned in this set of reference solutions / applications.

Thanks

**Comment by IoTFier** [comment]
Hello there! 
Any thoughts? I understand this is not a technical question.
Your input will be really valuable in estimating structure and headcounts depending to use the varying tech stack used in this reference application.

Hoping to hear from you.

Thanks

**Comment by IoTFier** [comment]
Hi @ngomal, any input ?

Thanks

**Comment by mvelosop** [comment]
It looks like the conversation ended and this is not really an issue with the app, so I'm closing this issue now. Feel free to comment, will reopen if needed.

**Comment by IoTFier** [comment]
@mvelosop and @ngomal - I understand this is not an issue with the app, but at the same time I don't know other avenue to discuss this information besides GitHub issue.

I am interested in this team structure because I am working on a end to end solution that comprise of applications as outlined in this reference solution.

Your input will be absolutely appreciated.

Thanks,

**Comment by mvelosop** [comment]
Hi @IoTFier, your inquiry really looks more like a consultancy job 😉

Anyway, inquiries regarding the team structure should probably be forwarded to @nishanil, who is managing the project now. However, keep in mind that since this is the repo of a sample (and simplified) application, management requirements will be quite different from a production app.

Another important issue to consider is that for a real-world application you should probably use separate repos for the services.

Hope this helps.

**Comment by IoTFier** [comment]
@mvelosop , Thank you Miguel. Absolutely I agree with you on the separate repos for services.

Hi @nishanil - Nish, 
Can you please share your email with me? 
I will be happy to correspond with you via email for further conversation.

Thanks

**Comment by nishanil** [comment]
Hey @IoTFier 
This is a reference application maintained by a small team. We update the samples based on industry trends in Cloud Native app development and Microservices Architecture best practices. We add best practices to an appropriate service/feature when it is relevant to this sample and update our guidance accordingly. However, in reality, the teams are business-driven and features/functionalities are added based on the business needs. Teams are also aligned that way and so are the code repositories. As mentioned in the earlier comments, the recommendation is to have an individual repository for every service and it should have its own build/release pipelines.

If you want to chat further, please feel free to email me: nish at microsoft.com
