### ISSUE TITLE
Build ERROR: no matching manifest for unknown in the manifest list entries

### ISSUE THREAD

**Issue by komal4364** [dotnet-architecture/eShopOnContainers#805]
Hi, 

I am trying this for the first time. have cloned the project on dev branch and tried running it. I find in the below error. Can anyone help me with fixing the error?

PS D:\eShopOnContainers> docker-compose up
WARNING: The INSTRUMENTATION_KEY variable is not set. Defaulting to a blank string.
WARNING: The ORCHESTRATOR_TYPE variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_SERVICE_BUS_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_SERVICE_BUS_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_CATALOG_KEY variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZUREFUNC_CAMPAIGN_DETAILS_URI variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_MARKETING_NAME variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_MARKETING_KEY variable is not set. Defaulting to a blank string.
Pulling basket.data (redis:alpine)...
alpine: Pulling from library/redis
ERROR: no matching manifest for unknown in the manifest list entries
PS D:\eShopOnContainers>

**Comment by mvelosop** [comment]
Hi @komal4364,

I know this a bit old, but could you get the app running? 
Did you follow the setup guide?: https://github.com/dotnet-architecture/eShopOnContainers/wiki#setting-up-your-development-environment-for-eshoponcontainers

**Comment by mvelosop** [comment]
Closing the issue now, but feel free to comment, will reopen if needed.

**Comment by amang2205** [comment]
@mvelosop I was able to reproduce this, simply by going through the Setup Guide (https://github.com/dotnet-architecture/eShopOnContainers/wiki/02.-Setting-eShopOnContainers-in-a-Visual-Studio-2017-environment). None of the variables are set in the .env file and clearly, the build fails. Question is however, what is ORCHESTRATOR_TYPE and what values are accepted. Would be nice if this would be covered by the setup.

**Comment by mvelosop** [comment]
Hi @amang2205, the setup guide has worked without issues in most configurations, so we are pretty sure it's probably an environment issue in your installation.

I know it's probably not easy to do but, can you try in a fresh machine?

OTOH, The orchestrator variable can be K8S or SF and it's used in Startup.cs like this:
https://github.com/dotnet-architecture/eShopOnContainers/blob/0eae3c3ea3b94fd21ffd7e91fc4ea38f9fd8ddc2/src/Services/Ordering/Ordering.API/Startup.cs#L147-L157

I have a basic Kubernetes knowledge at this point, so I can't go deeper yet 🙁, but I'm working on it!

Hope this helps a bit!

**Comment by amang2205** [comment]
Apologies for my somewhat cryptic message previously.
I already know what the error is and was trying to suggest that's I'd edit the setup guide PR to be clearer about the NTFS permissions. I'll elaborate.
