### ISSUE TITLE
BuildError while running the app (docker-compose up)

### ISSUE THREAD

**Issue by prakash-manit** [dotnet-architecture/eShopOnContainers#826]
Hello team,
Can you please help me with build errors mostly coming when building UI projects? Console log as follows-

Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/aspnet-feb2017-patch/nuget/v3/flatcontainer/microsoft.extensions.logging/index.json'.
  The SSL connection could not be established, see inner exception.
    The remote certificate is invalid according to the validation procedure.
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/aspnet-feb2017-patch/nuget/v3/flatcontainer/microsoft.aspnetcore.hosting/index.json'.
  The SSL connection could not be established, see inner exception.
    The remote certificate is invalid according to the validation procedure.
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/aspnet-feb2017-patch/nuget/v3/flatcontainer/system.threading.tasks.extensions/index.json'.
  The SSL connection could not be established, see inner exception.
    The remote certificate is invalid according to the validation procedure.
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/aspnet-feb2017-patch/nuget/v3/flatcontainer/microsoft.extensions.logging/index.json'.
  The SSL connection could not be established, see inner exception.
    The remote certificate is invalid according to the validation procedure.
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/aspnet-feb2017-patch/nuget/v3/flatcontainer/microsoft.aspnetcore.hosting/index.json'.
  The SSL connection could not be established, see inner exception.
    The remote certificate is invalid according to the validation procedure.
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/aspnet-feb2017-patch/nuget/v3/flatcontainer/system.threading.tasks.extensions/index.json'.
  The SSL connection could not be established, see inner exception.
    The remote certificate is invalid according to the validation procedure.
/usr/share/dotnet/sdk/2.1.403/NuGet.targets(114,5): error : Failed to retrieve information about 'Microsoft.AspNetCore.Hosting' from remote source 'https://dotnetmyget.blob.core.windows.net/artifacts/aspnet-feb2017-patch/nuget/v3/flatcontainer/microsoft.aspnetcore.hosting/index.json'. [/src/src/Web/WebSPA/WebSPA.csproj]
/usr/share/dotnet/sdk/2.1.403/NuGet.targets(114,5): error :   The SSL connection could not be established, see inner exception. [/src/src/Web/WebSPA/WebSPA.csproj]
/usr/share/dotnet/sdk/2.1.403/NuGet.targets(114,5): error :   The remote certificate is invalid according to the validation procedure. [/src/src/Web/WebSPA/WebSPA.csproj]
ERROR: Service 'webspa' failed to build: The command '/bin/sh -c dotnet publish -c Release -o /app' returned a non-zero code: 1

**Comment by mvelosop** [comment]
Hi @prakash-manit,

I just have some basic network knwledge, but this looks like an issue with a proxy server trying to hijack the SSL connection, do you happen to have Fiddler running? Can you try this from another location? Can you navigate to that address from your phone perhaps?

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue as it doesn't seem to be related to the app but to the environment. Feel free to comment though, will reopen if needed.

**Comment by shikelong** [comment]
+1。。 The seem error， and I don't run fiddler
