### ISSUE TITLE
Question: Handle Chained Domain Events

### ISSUE THREAD

**Issue by changhuixu** [dotnet-architecture/eShopOnContainers#828]
In the code below, it handles domain events at one level. For example, `Order` entity has an `OrderCreated` event, then handler will send an email or do something.
https://github.com/dotnet-architecture/eShopOnContainers/blob/1b7200791931f33c94206822a69644ca820bb0dc/src/Services/Ordering/Ordering.Infrastructure/MediatorExtension.cs#L11-L30

**Question: How to handle chained domain events?**
For example, Admin restricts a buyer, raises `BuyerRestricted` event from `Buyer` entity. One handler will have to cancel all active orders for this buyer, thus raises `OrderCanceled` event from `Order` entity. Another handler will handle `OrderCanceled` event and sends out email...
I call this type of events as chained events. Please correct me if there's a better existing name. 
In the example business process described above, some events are raised in the process of Publishing parent events by mediator, thus the `DispatchDomainEventsAsync` method is not able to collect all grandchildren events.

Are there better ways to handle this kind of scenarios?

I slightly modified the `DispatchDomainEventsAsync` method as below. It seems to work in my testing environment. Could anyone please take a look and see if it will cause any async blocking issue? Thank you.

```CSharp
public static async Task DispatchDomainEventsAsync(this IMediator mediator, OrderManagerDbContext ctx)
{
    var domainEntities = ctx.ChangeTracker
        .Entries<Entity>()
        .Where(x => x.Entity.DomainEvents != null && x.Entity.DomainEvents.Any())
        .ToList();
    var tasks = new List<Task>();
    while (domainEntities.Any())
    {
        var domainEvents = domainEntities
            .SelectMany(x => x.Entity.DomainEvents)
            .ToList();

        domainEntities.ForEach(entity => entity.Entity.ClearDomainEvents());

        tasks.AddRange(domainEvents
            .Select(async (domainEvent) => {
                await mediator.Publish(domainEvent);
            }));

        domainEntities = ctx.ChangeTracker
            .Entries<Entity>()
            .Where(x => x.Entity.DomainEvents != null && x.Entity.DomainEvents.Any())
            .ToList();
    }
    await Task.WhenAll(tasks);

}
```

**Comment by mvelosop** [comment]
Hi @changhuixu,

There was certainly an issue regarding this type of situations of "chained" events and the chosen solution was, at high level, this one:

1. Begin a transaction in the TransactionBehaviour:
https://github.com/dotnet-architecture/eShopOnContainers/blob/e05a87658128106fef4e628ccb830bc89325d9da/src/Services/Ordering/Ordering.API/Application/Behaviors/TransactionBehaviour.cs#L40

2. While processing the related commands, add the resulting integration events to a list (an outbox):
https://github.com/dotnet-architecture/eShopOnContainers/blob/e05a87658128106fef4e628ccb830bc89325d9da/src/Services/Ordering/Ordering.API/Application/Commands/CreateOrderCommandHandler.cs#L38
  There's a nice detail here, and it's that the outbox is persisted in the DB, so it'd be easy to implement a "watchdog" microservice that would handle possible failures in the publishing mechanism. This is not implemented in eShopOnContainers.

3. Commit the transaction for all changes when returning from the behavior pipeline:
https://github.com/dotnet-architecture/eShopOnContainers/blob/e05a87658128106fef4e628ccb830bc89325d9da/src/Services/Ordering/Ordering.API/Application/Behaviors/TransactionBehaviour.cs#L44

4. Publish all integration events in the outbox:
https://github.com/dotnet-architecture/eShopOnContainers/blob/e05a87658128106fef4e628ccb830bc89325d9da/src/Services/Ordering/Ordering.API/Application/Behaviors/TransactionBehaviour.cs#L48

This strategy also handles the atomicity of all changes mentioned in issue https://github.com/dotnet-architecture/eShopOnContainers/issues/721

Hope this helps.

**Comment by mvelosop** [comment]
This issue is solved now, so I'm closing it, but feel free to comment, will reopen if needed.

**Comment by hackked** [comment]
@mvelosop Could you explain a bit more on the sequence of events that would occur specifically for cascading domain events to solve this?  I am specifically talking about a case similar to the following:

1. Command is published to mediator (behavior starts transaction)
2. Entity is updated resulting in domain event A
3. Initial command calls SaveEntitiesAsync dispatching domain event A
4. Domain Event handler for domain event A modifies entity resulting in domain event B
5. SaveEntitiesAsync calls DbContext SaveChangesAsync and completes
6. _Domain event B is left unpublished?_

One alternative would be for every domain event handler to also call SaveEntitiesAsync, but if you have a command that edits 100 orders and then dispatches say 100 domain events (1 for each order) that could lead to 100 calls to SaveChangesAsync which might be prohibitively expensive?  I'm guessing I may just be missing something in the flow.  Only other alternative I see is to use a message pump type approach as @changhuixu laid out where continuously dispatching if new events are found.

**Comment by mvelosop** [comment]
Hi @hackked,

I expect to cover this issue in some detail in a few days, when I get into details for the ordering process.

The problem you mention shouldn't occur with the current version of eShopOnContainers, but can't be sure because there isn't a case like that here.

As a general recommendation about the "might be prohibitively expensive" guesses is, try the simples solution and fix it when (if) necessary.

Hope this helps in the meantime.
