### ISSUE TITLE
Where CatalogController.UpdateProduct() is called from?

### ISSUE THREAD

**Issue by IvanFarkas** [dotnet-architecture/eShopOnContainers#829]
From reading the documentation and studying the code it's unclear were the **[Microsoft.eShopOnContainers.Services.Catalog.API.Controllers.CatalogController.UpdateProduct()](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Catalog/Catalog.API/Controllers/CatalogController.cs)** is called from?

**Comment by CESARDELATORRE** [comment]
It is not used from anywhere since we don’t have any Catalog back office manager app.
However, it is useful for updating products by using Swagger, directly by using the service in a browser, for tests.

**Comment by IvanFarkas** [comment]
That's exactly what I did. Just wanted to make sure I did not miss it.
Thanks for the quick response.
