### ISSUE TITLE
[Feedback]: SignalR Core Usage

### ISSUE THREAD

**Issue by shaggygi** [dotnet-architecture/eShopOnContainers#83]
This new repo showing how to get started with ASP.NET, Docker, microservices, etc. is great!  I applaud you providing this as I've been wanting help explaining topics.   Keep up the good work :smile: 

Understanding this is in alpha, it would be nice to also see how related technologies could take advantage of the new SignalR Core coming out later in the year.  Please add (if possible and only if it makes sense) SignalR Core usage somewhere in the roadmap.

Thanks again!

**Comment by CESARDELATORRE** [comment]
Sure! SignalR on .NET Core will be available in .NET Core 2, so we're not yet, there. But I'm planning to add an additional SignalR Hub microservice/container for some cool feature in the app.
Thanks a lot for your feedback! :)

**Comment by shaggygi** [comment]
@CESARDELATORRE sounds great!  looking forward to it.

**Comment by jrgcubano** [comment]
@CESARDELATORRE The same here!

**Comment by AdrienTorris** [comment]
For information, SignalR Core is now available for ASP.NET Core 2.0 :)
https://blogs.msdn.microsoft.com/webdev/2017/09/14/announcing-signalr-for-asp-net-core-2-0/

**Comment by CESARDELATORRE** [comment]
Yes, I know, of course.
Implementing a feature in eShopOnContainers based on SignalR is in our roadmap.
Feel free to suggest business ideas for that feature. :)

**Comment by AdrienTorris** [comment]
Maybe a business idea using SignalR could be to sell products by bids ? It's just an idea.

**Comment by SychevIgor** [comment]
Idea- on some site we can see chat window with sale person who can support your choice. Chat is a canonical example of signalr.

**Comment by CESARDELATORRE** [comment]
Could be, but here are many pre-packaged products for Chats, too..
I was thinking of a simpler feature that could be popping-out an alert in the web app each time that an Order has a new or changed state.

Thoughts about this one?
Cesar.

**Comment by wwrighter** [comment]
@Cesar
Seems like a good working example for SignalR in this project.  Am I right in assuming 'admin' role accounts would receive a notification for 'new' order,  and customer/purchaser accounts would receive notifications on any status change (I.e. 'shipped') ?

**Comment by CESARDELATORRE** [comment]
We don’t really have the admin role.
So, initially, the user would get a live notification whenever the order’s state changes to a new state. That would be the minimum feature.
Further that that, we’d need to add the admin role in a back office app, which is not high priority feature right now.

**Comment by mvelosop** [comment]
Closing this issue because SignalR is now formally included in the [Road Map](https://github.com/dotnet-architecture/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases)
