### ISSUE TITLE
Update UpdateProduct() Route attribute in NET-Microservices-Architecture-for-Containerized-NET-Applications-(Microsoft-eBook).pdf document

### ISSUE THREAD

**Issue by IvanFarkas** [dotnet-architecture/eShopOnContainers#830]
Please update UpdateProduct() Route attribute in NET-Microservices-Architecture-for-Containerized-NET-Applications-(Microsoft-eBook).pdf and related documents.

```
\src\Services\Catalog\Catalog.API\Controllers\CatalogController.cs
Microsoft.eShopOnContainers.Services.Catalog.API.Controllers.CatalogController.UpdateProduct()
```

It should be:
```
[Route("items")]
```

```
[Route("items")]
[HttpPut]
[ProducesResponseType((int)HttpStatusCode.NotFound)]
[ProducesResponseType((int)HttpStatusCode.Created)]
public async Task<IActionResult> UpdateProduct([FromBody]CatalogItem productToUpdate)
```

instead of:
```
[Route("update")]
```

**Comment by mvelosop** [comment]
Hi @IvanFarkas,

I don't quite understand, that's just the way it is right now:

https://github.com/dotnet-architecture/eShopOnContainers/blob/1178b8358553dd78e2eec1192c66f86f50caf513/src/Services/Catalog/Catalog.API/Controllers/CatalogController.cs#L216-L223

🤔

**Comment by mvelosop** [comment]
I'm sorry I read too fast! 

It's an error in the Book! 👍

**Comment by mvelosop** [comment]
@IvanFarkas,

I just included the fix in a [PR in process to update the guide](https://github.com/dotnet/docs/pull/8018/commits/18dab61366679bee12af40c0870e1109efc96d52) and the e-book, so I'm closing this issue now.

Thanks! 👍

**Comment by IvanFarkas** [comment]
Awesome. Thx. Ivan
