### ISSUE TITLE
Document code snippet does not match source

### ISSUE THREAD

**Issue by IvanFarkas** [dotnet-architecture/eShopOnContainers#832]
I wonder if the document code snippet is sort of a pseudo code.
If not please correct it.

**In Document:**
NET-Microservices-Architecture-for-Containerized-NET-Applications-(Microsoft-eBook).pdf page 191

```
//Additional code...
[Route("")]
[HttpGet]
[ProducesResponseType(typeof(IEnumerable<OrderSummary>), (int)HttpStatusCode.OK)]
public async Task<IActionResult> GetOrders()
{
  var orderTask = _orderQueries.GetOrdersAsync();
  var orders = await orderTask;
  return Ok(orders);
}
```

**In source:**
Microsoft.eShopOnContainers.Services.Ordering.API.Controllers.OrdersController.GetOrders()
\src\Services\Ordering\Ordering.API\Controllers\OrdersController.cs

```
[Route("")]
[HttpGet]
[ProducesResponseType(typeof(IEnumerable<OrderSummary>), (int)HttpStatusCode.OK)]
public async Task<IActionResult> GetOrders()
{
  var userid = _identityService.GetUserIdentity();
  var orders = await _orderQueries.GetOrdersFromUserAsync(Guid.Parse(userid));
  return Ok(orders);
}
```

**Comment by mvelosop** [comment]
Hi @IvanFarkas, thanks for the heads up! 👍

I just included the fix in the in progress PR for chapter 7 https://github.com/dotnet/docs/pull/8201/commits/df03288e0ba150bbc3f8ca64f1e7fa1583cf103b , so I'm closing this issue.

Included in the e-book also, for next release.

Thanks!
