### ISSUE TITLE
Documentation Errata - must be must be

### ISSUE THREAD

**Issue by IvanFarkas** [dotnet-architecture/eShopOnContainers#834]
Please correct the following in **NET-Microservices-Architecture-for-Containerized-NET-Applications-(Microsoft-eBook).pdf** on page 223

**from:**
```
must be must be
```

**to:**
```
must be
```

**Comment by mvelosop** [comment]
Hi @IvanFarkas,

That's also included for the next release of the book (the on-line version had been fixed long ago, but not the pdf)

So I'm closing this issue now.

Thanks 👍
