### ISSUE TITLE
[Question]: DDD to remove an order item

### ISSUE THREAD

**Issue by ADringer** [dotnet-architecture/eShopOnContainers#835]
Hi,

I'm looking at DDD and how we can remove items from a collection. 

In the Order microservice the `Order` entity has a list of `OrderItems` which can only be added to via the `Order` aggregate method. 

How would we go about removing an order item from the Order? If we go the same route of encapsulation then we would have a method such as:

    public void RemoveOrderItem(OrderItem orderItem)
    {
        _orderItems.Remove(orderItem);
    }

But this wouldn't actually remove it as it needs to be removed via Entity Framework's `Remove()` method on the `DbContext`.

So this would require either a new `IOrderItemRepository` or an additional method on the `IOrderRepository` to make use of the DbContext.

However,  this breaks the encapsulation pattern as it can be done from outside the Order aggregate.

Is there a way round this? Or am I missing the right way of doing this?

Thanks

**Comment by CESARDELATORRE** [comment]
Good question. 👍 So, you are right in the Aggregate's implementation. You'd implement a method called RemoveOrderItem in the Order AggregateRoot where you'd remove the item from the Order's Item list, so in that method you are encapsulating and you could also implement additional "in-memory" behavior in that method, tha's why you don't want to provide direct access to the Item's List.

Then, to your question, the Repository you have to use is just the OrderRepository (1:1 relationship with the aggregate) and call the OrderRepository.Update(order) method. 

Sure, you are "removing/deleting" an order item, but from an Aggregate perspective, that is an Update/change within the order. If you had to add/change anything else for deleting Order items, you'd need to do it within the method OrderRepository.Update(order).

You MUST NOT create repositories per child entities or tables that are "child" within an aggregate (like Order). Repositories must have a 1:1 relationship with aggregates and therefore with the aggregateRoot or Root Entity (Order in this case).

The encapsulation is maintained that way. The Order aggregate controls invariants and behavior of anything in-memory within the Aggregate. The Repository controls the infrastructure persistence for that Aggregate.

Read this chapter I wrote where all the repository implementation is explained in deeper details and why it is important to "Enforce one aggregate root per repository":

https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-design 

Hope that helps. :)

**Comment by ADringer** [comment]
That all makes sense to maintain encapsulation, but still unsure how to implement this in the update method of the repository.

So we remove it from the list within the aggregate, but would we know which one was removed when calling `update`? 

I'm not sure how we track it's been removed between removing it from the aggregate and the repository implementation.

One other point as well, EFCore provides tracking of changes so generally we just need to make the change (e.g. `SetShippedStatus()`) and then call `_orderRepository.UnitOfWork.SaveEntitiesAsync()` once done to commit the changes. With what we're discussing here (deleting order item) you've suggested using `Update` on the repository as it doesn't track this change. This feels like EFCore implementation is leaking through to the application layer as the command handler has to know whether it should use `Update` rather than just making the change and saving. 

Thanks

**Comment by ADringer** [comment]
Right, think I've got it now!

I understand that EF Core will track the changes for an Order when retrieved, but was under the assumption it wouldn't track and OrderItem being removed from the collection on the Order. I assumed that we would have to tell EFCore explicitly that it's been removed.

I've just tried it and simply calling `_orderItems.Remove(orderItem)` and then saving changes is enough to delete the orderItem record, we don't need to call `Update` on the repository.

Thanks for you help, been very helpful!

**Comment by TsengSR** [comment]
@ADringer: Please keep in mind, that this behavior only works with ORM which track the changes. In your code you should still rely on the Update method, because if you ever were to replace the persistence layer from EF Core to lets say MongoDb, then your entity would not be updated anymore, since MongoDb doesn't track entities the same way EF Core does. 

If you, like now, rely on the persistence framework to do the task, you **do leak** persistence knowledge into your domain.

Calling the repositories Update method on a tracked entity shouldn't have any side effects, if its already tracked (on EF Core).

**Comment by CESARDELATORRE** [comment]
@TsengSR - 100% agree 👍

**Comment by ADringer** [comment]
Didn't look at it that way, but you're right, I am leaking persistence knowledge. Thanks for all the help, has been very educational!

**Comment by raywu-AV** [comment]
I have problem where it doesn't delete the items. it simply unlinked them like removing foreign key from item record in db. The items becomes orphaned. Is there a way to remove them properly?

**Comment by ardalis** [comment]
We fixed a similar issue in eShopOnWeb here:
https://github.com/dotnet-architecture/eShopOnWeb/commit/cfe80aa9565e85514f26374b800ed6ef3e5cc51e

The problem was that EF was creating an optional relationship (nullable int foreign key) where it needed to be a required one to allow for cascading deletes. We added the id property to the entity (non-null) and it corrected the behavior.

**Comment by flecce** [comment]
> per



> Good question. 👍 So, you are right in the Aggregate's implementation. You'd implement a method called RemoveOrderItem in the Order AggregateRoot where you'd remove the item from the Order's Item list, so in that method you are encapsulating and you could also implement additional "in-memory" behavior in that method, tha's why you don't want to provide direct access to the Item's List.
> 
> Then, to your question, the Repository you have to use is just the OrderRepository (1:1 relationship with the aggregate) and call the OrderRepository.Update(order) method.
> 
> Sure, you are "removing/deleting" an order item, but from an Aggregate perspective, that is an Update/change within the order. If you had to add/change anything else for deleting Order items, you'd need to do it within the method OrderRepository.Update(order).
> 
> You MUST NOT create repositories per child entities or tables that are "child" within an aggregate (like Order). Repositories must have a 1:1 relationship with aggregates and therefore with the aggregateRoot or Root Entity (Order in this case).
> 
> The encapsulation is maintained that way. The Order aggregate controls invariants and behavior of anything in-memory within the Aggregate. The Repository controls the infrastructure persistence for that Aggregate.
> 
> Read this chapter I wrote where all the repository implementation is explained in deeper details and why it is important to "Enforce one aggregate root per repository":
> 
> https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-design
> 
> Hope that helps. :)

Hi,

I'm facing same issue. I'm agree about you must not have the repository for aggregate's children, but when I have an aggregate with thousand child?

e.g. If I have a "Calendar" aggregate and "Event" as child. If I want to update an event I have to load all events?

With EF Core 2.2 is it not possible have a conditional Include.

Thanks in advance

**Comment by dathway** [comment]
Why is there no method for removing OrderItems on the Order Aggregate? Rather than addressing the problem in a blog post, how about implementing this into the app, to show folks the proper way of removing a collection from an aggregate and demonstrate it how persists that change all the way down to the DB?

**Comment by remi0411** [comment]
Hello

Take a look at this

With ef core 5 you can conditionnally include child ( [child filtering](https://docs.microsoft.com/fr-fr/ef/core/what-is-new/ef-core-5.0/whatsnew#filtered-include) )
So on your search specification, pass your AggRoot Id for a general where, and also pass your child Id

Then you can do

Query
   .Include(agg => agg.Child.Where(c => c.Id == childId))
   .Where(agg => agg.Id == aggRootId)
   
 This will load your aggRoot and only the children with the corresponding Id.
 You can also load only the child containing the child that have to be update
 
 
Query
   .Include(agg => agg.FirstChilds.Where(c => c.SecondChilds.Any(sc => sc.Id == childId))
       .ThenInclude(chi => chi.SecondChilds.Where(c => sc.Id == childId))
   .Where(agg => agg.Id == aggRootId)
