### ISSUE TITLE
Question: What icon's/assets/program is used to create the Environment Architecture image?

### ISSUE THREAD

**Issue by PureKrome** [dotnet-architecture/eShopOnContainers#838]
Hi 👋 

pretty random question: but [given the following architecture image](https://github.com/dotnet-architecture/eShopOnContainers#architecture-overview) in the documentation, what tool and/or icons/assets were used to create this? I'd like to create something similar for our own internal systems 😄 

Mainly having access to the icons/assets is the bare minimum. (Yes, I know I could just 'cut out' the icons/assets from the screenshot directly ... but not sure about copywrite, etc)...

![](https://user-images.githubusercontent.com/1712635/38758862-d4b42498-3f27-11e8-8dad-db60b0fa05d3.png)

**Comment by PureKrome** [comment]
@CESARDELATORRE awesome! also, the images used in the PowerPoint file? are they stock PowerPoint assets? Or custom ones?

**Comment by CESARDELATORRE** [comment]
Mostly custom, except Azure icons which are standard assets

**Comment by mvelosop** [comment]
Hi @PureKrome, guess you should've found it already but in case you haven't here you have a set of Azure icons: https://www.microsoft.com/en-us/download/details.aspx?id=41937

Closing this issue now.

Best.

**Comment by PureKrome** [comment]
Thanks team!

**Comment by Aggromonster** [comment]
@Cesardelatorre - looks like the PPTX were removed from the Github repo.  Can you point me to where I might obtain a copy?
