### ISSUE TITLE
How the WebSPA is using the API Gateway?

### ISSUE THREAD

**Issue by jervie-vitriolo** [dotnet-architecture/eShopOnContainers#841]
@CESARDELATORRE 
I'm currently looking at the API Gateway implementation and I can't find where the API gateway was used from the WebSPA. The appsettings.json where all the  URLs were set is pointing directly to microservices. Is this only for dev environment? and how to implement it on prod?

![image](https://user-images.githubusercontent.com/22651087/47917394-57198480-dee4-11e8-81c2-95daed78c14b.png)

**Comment by nishanil** [comment]
Hi there, The PurchaseUrl(localhost:5200) that you see in your screenshot is an URL to API Gateway. The same is implemented for production scenarios like the K8S. 

I'm closing this issue now. Feel free to add comments to this if you need more info.
