### ISSUE TITLE
[QUESTION] Confusion about the Azure Service Bus connection string

### ISSUE THREAD

**Issue by vdecristofaro** [dotnet-architecture/eShopOnContainers#843]
I am getting the same error as in #421 

My connection string on the appsettings.json looks like this

`Endpoint=sb://{xxxxxx}.servicebus.windows.net;SharedAccessKeyName={xxxxxx};SharedAccessKey=xxxxxx`

What am I doing wrong?

**Comment by thiennn** [comment]
@vdecristofaro Did you manage to answer this? I got the same question

**Comment by thiennn** [comment]
Got it, 
`Endpoint={xxx};SharedAccessKeyName={yyy};SharedAccessKey={zzz}=;EntityPath={topic_name}`
