### ISSUE TITLE
[Question] Handling lazy loading within the domain

### ISSUE THREAD

**Issue by ADringer** [dotnet-architecture/eShopOnContainers#844]
Hi,

I understand the need to retrieve all related entities that belong to the aggregate, but what happens when there are many of these?

For instance, I'm looking at modelling an 'event', such as a marathon. One requirement is that when I try to call 'AddParticipant()' on the domain, I check that they don't already exist. I can `Include` all of the participants and then just check if they exist already, but the participants list for this event could run in to the 10s of thousands. 

Should we take the performance hit of pulling this huge list out every time?

I thought could configure this list for lazy loading but the way the fields are set up (readonly, private etc) it doesn't support lazy loading. If I did this, they query to check if they exist already would actually run on the sql server and not in memory.

Thanks

**Comment by piotr-l** [comment]
As I see it the participants' list should be only a list of ids in Marathon aggregate, in the example you provided, and fetching e.g. 50k of ids is not a big performance issue comparing to pulling all participants with their properties.

**Comment by ADringer** [comment]
Yep makes sense. I hadn't tried pulling in 50k of entities in to memory so wasn't sure what the performance hit would be.
