### ISSUE TITLE
Login results in nginx 502 error

### ISSUE THREAD

**Issue by mcasperson** [dotnet-architecture/eShopOnContainers#846]
When performing a login, nginx returns a 502 error. In the logs you will see this:

> 2018/11/06 19:50:54 [error] 541#541: *80284 upstream sent too big header while reading response header from upstream

The solution is to add the following setting to the nginx config file:

`proxy-buffer-size 128k;`

This setting is documented at https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/configmap.md#proxy-buffer-size

**Comment by eiximenis** [comment]
Yep :)

Just for sake of completness...

* If using AKS, then you can simply do a `kubectl apply -f aks-httpaddon-cfg.yaml` (file is in `/k8s/helm`). That will reapply the configmap used by nginx controller preinstalled with the http routing addon in AKS.
* If using local k8s of Docker CE then this settin should be applied if you followed the instructions of wiki page. If not, the configmap is in the `/k8s/nginx-ingress` so you can apply.  In fact this is a generic configmap that should work with any nginx controller that ins installed on `ingress-nginx` namespace

I'll review the doc to make sure that these steps are clear :)

Thanks!

**Comment by mvelosop** [comment]
It looks like the conversation ended, so I'm closing this issue now. Feel free to comment, will reopen if needed.
