### ISSUE TITLE
Library Manager manifest contains syntax errors.

### ISSUE THREAD

**Issue by zeekay18** [dotnet-architecture/eShopOnContainers#848]
I'm getting this error when building the project the first time.

Severity	Code	Description	Project	File	Line	Suppression State
Error	LIB004	Library Manager manifest contains syntax errors. Please fix the errors in libman.json, then try again.	Identity.API	C:\Users\Azeez\source\eShopOnContainers\src\Services\Identity\Identity.API\libman.json	1

**Comment by chanaka1** [comment]
This is a Issue of Visual studio. Check the [Library Manager Reported Bug](https://github.com/aspnet/LibraryManager/issues/111)

**Comment by mvelosop** [comment]
Hi @zeekay18 are you still getting this issue?

I have no problem with VS 15.9.6 in any of the projects that use libman.

**Comment by mvelosop** [comment]
Closing this issue as it seems stale, but feel free to comment, will reopen if needed.

**Comment by rafsanulhasan** [comment]
I'm still facing this issue in VS 15.9.10

**Comment by rafsanulhasan** [comment]
I found two solutions:
1. Removing the Nugget package: Microsoft.Web.LibraryManager.Build
2. Removing the **files** array from libman.json

I think the 2nd one is good enough.
How about submitting a PR on this @mvelosop ?
