### ISSUE TITLE
QueueUnbind upon UnSubscribe

### ISSUE THREAD

**Issue by cilerler** [dotnet-architecture/eShopOnContainers#858]
I wonder why did you use `QueueUnbind` here https://github.com/dotnet-architecture/eShopOnContainers/blob/7fc68b4b86111e571a9d866c2de955eeea30911c/src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.cs#L56-L58 it seems to me that will cause an issue if there are multiple instances handling the same event _(scaling purpose)_.  Am I missing something?

ℹ️ Here [rabbitmq-dotnet-client](https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/497#issuecomment-441642277) repository member says ...

> Bindings are orthogonal to consumers. You can delete all bindings without cancelling any consumers. **Their queues won't see any more messages routed to them** but it doesn't cancel consumers or in any way contradict the fact that they are still around.
> 
> If a consumer has to stop but the queue is not going away, deleting any bindings set up by that consumer [app] is a good idea but isn't a requirement. As long as you don't leak bindings do whatever you think make sense. Of course deleting a queue will delete all its bindings.

**Comment by mvelosop** [comment]
Hi @cilerler,

That's an important consideration for a production environment, but remember this repo is a sample, kind of a (rather large) tutorial, to showcase architectural patterns, along with the [corresponding guide](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/).

As such, the focus is on getting the concepts and patterns as clear as possible, even though the code might not be production-ready. That's just not that important in the context of this app.

Hope this helps.

**Comment by cilerler** [comment]
thanks for the clarification @mvelosop
