### ISSUE TITLE
EventBus: InMemoryEventBusSubscriptionsManager: Typo while invoking event

### ISSUE THREAD

**Issue by Iamcerba** [dotnet-architecture/eShopOnContainers#866]
There is a typo in [InMemoryEventBusSubscriptionsManager](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/BuildingBlocks/EventBus/EventBus/InMemoryEventBusSubscriptionsManager.cs#L120). Local copy should be invoked to avoid null reference exception:

```csharp
if (handler != null)
{
    handler(this, eventName);
}
```

**Comment by mvelosop** [comment]
Hi @Iamcerba, thanks for the heads up!

This doesn't look good but it shouldn't really cause a null reference, because `handler` and `OnEventRemoved` have the save reference right?

**Comment by Iamcerba** [comment]
Hi @mvelosop, in case of single thread, yes. But subscription to OnEventRemoved could be removed in other thread after null check and before OnEventRemoved invocation.

**Comment by mvelosop** [comment]
That's a good point indeed 👍

Well, you might want to submit a PR to fix this 😉

**Comment by mvelosop** [comment]
Thanks @Iamcerba, closing the issue now as the related PR has been merged.
