### ISSUE TITLE
[Feedback] ServiceFabric example 

### ISSUE THREAD

**Issue by grahamehorner** [dotnet-architecture/eShopOnContainers#87]
This is a great example of a .net microservices architecture; it would be great if the same sample was available as a ServiceFabric deployment/solution to compare.

**Comment by CESARDELATORRE** [comment]
Yep! That's the idea. Not only Service Fabric but also Docker Swarm, Kubernetes and DC/OS.
See that already in the Roadmap, here:
https://github.com/dotnet/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases 

This version is only the "foundational code version" focusing mostly on .NET Core and Docker.
Once we have a stable version with internal code as we want, we'll create multiple flavors/forks like:
**- eShopOnServiceFabric
- eShopOnSwarm
- eShopOnDCOS
- eShopOnKubernetes**

Plus adding especial features per each, like Stateful Services and Actors in Service Fabric (when available for .NET Core), etc. and of course:
**- eShopOnAzure** - Using additional Azure infrastructure, like Azure Service Bus, Azure Storage Blobs, Azure Key Vault, etc.

Also, work from the community with other frameworks creating forks, like:
**- eShopOnSteeltoeCloudFoundry
- eShopOnNServiceBus
- eShopOnMassTransit**
etc.

Thoughts? :)

**Comment by grahamehorner** [comment]
cool; I'd be very interested in the security implementation of authentication/authorisation between users/services, device/services & service/service.  I look forward to following with interest, great work thus far.

**Comment by CESARDELATORRE** [comment]
About security we're currently using ASP.NET Identity wrapped around with IdentityServer4 as an STS (Security Token Service) running as a container, so the token works for the Web apps and also for the Xamarin app. :)
This might evolve in the future with more stuff coming from the ASP.NET Core team. The Azure flavor/fork will focus a lot more on Security, secrets storage, etc., Azure AD for internal/employee apps..

**Comment by bspann** [comment]
What about leveraging Azure AD B2C for authentication?

**Comment by CESARDELATORRE** [comment]
Sure, but in the eShopOnContainers we didn't want to take any dependency on Azure subscriptions, so any developer could just grab the code, install Docker and try it: "F5 experience", easy to get started.
In upcoming forks (eShopOnAzure) we will use additional infrastructure from Azure. Azure AD B2C can be a possibility, of course.
