### ISSUE TITLE
The messaging entity 'XYZ' already exists exception handling 

### ISSUE THREAD

**Issue by liguori** [dotnet-architecture/eShopOnContainers#875]
Not clear which exception is handled here.
https://github.com/dotnet-architecture/eShopOnContainers/blob/3ddbdd6d06fd52c4aa5ffa4e9718c40f56678838/src/BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.cs#L84
When I try this code with an Azure Service Bus Subscription, I get the message:
The messaging entity 'busName:Topic:TopicName~95|subscriptionName|messageLabel' already exists. TrackingId:abe9f72c-7941-45a6-9752-f8, SystemTracker:NoSystemTracker, Timestamp:2018-12-04T22:42:12 Reference:8d48b696-88b93b5, TrackingId:a872a63eea-f217fdca8131_G22, SystemTracker:NoSystemTracker, Timestamp:2018-12-04T22:42:12

On Azure documentation there is no information about this error.  Can someone clarify?

Thank you

**Comment by mvelosop** [comment]
Hi @liguori, is this still happening with eShopOnContainers?

**Comment by liguori** [comment]
Hello @mvelosop, not anymore!
Was It an Azure Service Bus (or Azure .NET Sdk) problem?
It look like disappeared automatically...

**Comment by mvelosop** [comment]
Thanks @liguori, glad to know!

Closing this.
