### ISSUE TITLE
NGINX ingress does not forward on AKS

### ISSUE THREAD

**Issue by larstbone** [dotnet-architecture/eShopOnContainers#877]
#EXPECTED BEHAVIOR
After new install using AKS and helm, I would expect to be able to browse to the IP exposed by **addon-http-application-routing-nginx-ingress** service and **/webmvc** and see the website as I am able to do when running in VS2017.

#ACTUAL BEHAVIOR
All queries return **default backend - 404** except for queries to **/healthz** which returns 200 with empty body.  As I understand it, this is default behavior for NGINX when it is not configured.

I've followed the directions in wiki chapter 10, using the outline found in the attached script.  Tried it 4 times, twice in both "centralus" and "eastus" regions, just to see if that was a problem as hinted at in #691 with the comment about needing to use latest AKS.
[acmeK8sDeployLog.txt](https://github.com/dotnet-architecture/eShopOnContainers/files/2660672/acmeK8sDeployLog.txt)

I was able to exec into a Pod and curl to the WebStatus where html indicated **Good** for all services.  So that tells me that maybe all is well, save for my problem with the NGINX ingress.

Curiously, when I execute `kubectl get ing` no IP addresses are displayed as shown in the wiki.  In my case, the **ADDRESS** column is empty.

Also, there is no DNS entry that works, I have to browse using the IP address exposed by **addon-http-application-routing-nginx-ingress**. 

This is likely "user error" as I'm new to Helm and K8s, but there was a recent change to the wiki a few days ago, so maybe I'm encountering a new problem with documentation.

**Comment by eiximenis** [comment]
Hi @larstbone 

Just to be sure: could you verify that your ingresses resources have the annotation `kubernetes.io/ingress.class: addon-http-application-routing`?

(Can use `kubectl describe ing <ingress-name>` to see if the annotation exists)

**Comment by eiximenis** [comment]
Hi again!

I saw a bug in the `deploy-all.ps1` script, introduced when local k8s deployment was added. I pushed the commit b408d58f556e59bc5fb19b97733a7521169b0f59 to fix it.

Now it should work.

**Comment by larstbone** [comment]
It does work, thanks!  Being completely new to K8S and Helm, and only somewhat familiar with Docker, I would have had a difficult time resolving this.
