### ISSUE TITLE
Entity FRamework error connecting to database in SQL Azure

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#884]
Entity FRamework error connecting to database in SQL Azure.
Db Context issue

**Comment by benbuckland** [comment]
I have seen this as well and it seems that by default error 258 (timeout) is not being caught by the built in retry functionality so have altered the EnableRetryOnFailure method as below
`sqlOptions.EnableRetryOnFailure(maxRetryCount: 10, maxRetryDelay: TimeSpan.FromSeconds(10), errorNumbersToAdd: new List<int>(258));`

**Comment by CESARDELATORRE** [comment]
Sorry, this was just a "Test" issue that I forgot to delete, being used for a ML.NET demo which is classifying the issue automatically (in this case as "area-System.Data") by using a multi-class classification model with ML.NET.
So, not a real issue, but a demo, I'm just closing it. ;)
