### ISSUE TITLE
Crash when changing Identity URL in settings.  

### ISSUE THREAD

**Issue by wyldebill** [dotnet-architecture/eShopOnContainers#885]
When I attempt to change the URL to the real microservices URL for Identity in the Android emulator, the app crashes.  Strangely, it crashes at the last letter in the default URL when using backspace - the Y in "YOUR_...".  Once it crashes like this, the app will not successfully run again until deleted and redeployed to the emulator. 
Additionally, the instructions at the bottom of this page seem to be out of date with the current Xamarin project:
-there is no PCL project anymore, it's a .NET Standard Shared project now.
-there is more than 1 setting now in the Settings area of the Xamarin app, the screenshot shows 1.
-the advice about not using the Google Android emulator is obsolete.  We are supposed to use Googles emulators now that they run on Hyper V.  Right?
-what is the BaseEndpoint IP supposed to be for the Xamarin setup?  10.106.144.28 does not seem to work.

VS 2017 Pro, v15.9.4

**Comment by mvelosop** [comment]
Closing as outdated.
