### ISSUE TITLE
Docker Build images Error!

### ISSUE THREAD

**Issue by taomylife521** [dotnet-architecture/eShopOnContainers#889]
![qq 20181224162834](https://user-images.githubusercontent.com/9649318/50395080-d74dbf00-079c-11e9-8f5e-e51e01785aa0.png)

**Comment by PureKrome** [comment]
Have you tried going to the repo root directory and doing a docker-compose build, instead? or even a docker build from the root of the repo?

**Comment by taomylife521** [comment]
I'll just switch to the root directory and it'll work！

**Comment by taomylife521** [comment]
> Hi @taomylife521,
> 
> You can also execute "run-docker-compose-build.ps1" from the root folder as @PureKrome suggest and you'll get the time it gets to build it and a nice tune you might like 😉
> 
> Hope this helps.

Thank You！！！

**Comment by mvelosop** [comment]
Closing this issue now as it seems to be solved, feel free to comment though, will reopen if needed.
