### ISSUE TITLE
[Question] Where is the change log of ebook?

### ISSUE THREAD

**Issue by Rwing** [dotnet-architecture/eShopOnContainers#894]
eg. I want to know the difference between v2.0 and v2.1 .

**Comment by joylogic** [comment]
https://github.com/dotnet-architecture/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases

**Comment by Rwing** [comment]
> https://github.com/dotnet-architecture/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases

Thank you, but I mean what changes of content in ebook

**Comment by mvelosop** [comment]
Hi @Rwing,

There's no changelog, but the main changes from 2.0 are as follow:

- Added API Gateway/Aggregator implementation section with Ocelot
- Focus on Kubernetes, AKS and Service Fabric/Mesh
- Samples and code updated to .NET Core 2.1 versions
- Enhanced details on 
  - Working with Kubernetes
  - Multi-stage builds
  - Testing in eShopOnContainers
  - Resilience strategies
  - Using HttpClientFactory
  - Using Azure KeyVault

Hope this helps!

**Comment by mvelosop** [comment]
Closing this issue as it seems solved now, but feel free to comment though, will reopen if needed.
