### ISSUE TITLE
docker-compose build error, due to event-stream 3.3.6 is removed from NPM.

### ISSUE THREAD

**Issue by sheng-jie** [dotnet-architecture/eShopOnContainers#895]
When I use `docker-compose build` to build docker images, eshop/websap image build failed. I got the following errors:
```
npm ERR! code E404
npm ERR! 404 Not Found: event-stream@https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-30T13_50_23_714Z-debug.log
ERROR: Service 'webspa' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1
```
Event-stream 3.3.6 is removed from NPM, something due crypto mining. 

In the `package-lock.json` of WebSpa project there is a reference to that.
```
"event-stream": {
  "version": "3.3.6",
  "resolved": "https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz",
```

I tried to remove `package-lock.json`, after that I can run `npm install` in the project successfully. But still build image failed. I got the following error:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eshopaspnetnetcoredockerspa@0.0.0 build:prod: `ng build --prod --aot --extract-css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the eshopaspnetnetcoredockerspa@0.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Please help to check, thanks.

**Comment by TsengSR** [comment]
Issue related to the Crypto mining is https://github.com/dominictarr/event-stream/issues/116

Quote from the opening issue: 
>**What can I do:**
>By this time fixes are being deployed and npm has yanked the malicious version. Ensure that the developer(s) of the package you are using are aware of this post. If you are a developer update your event-stream dependency to `event-stream@3.3.4`. This protects people with cached versions of event-stream.

**Comment by sheng-jie** [comment]
@TsengSR Thank you. 
This issue only exists in my fork repository. After sync, it works now.
