### ISSUE TITLE
Why do you still use Implicit Code in javascript ?

### ISSUE THREAD

**Issue by patsadow2** [dotnet-architecture/eShopOnContainers#896]
Hello, Why do you still use Implicit Code in JavaScript instead of Authorization Code ?

https://medium.com/oauth-2/why-you-should-stop-using-the-oauth-implicit-grant-2436ced1c926

    public AuthorizedCallback() {
        this.ResetAuthorizationData();
        let result: any =....
        console.log(result.access_token)

**Comment by mvelosop** [comment]
Hi @patsadow2, thanks for the heads up!

It's good to know this, even though the purpose of eShopOnContainers is to serve as a sample app for microservices architecture patterns and not a production application template, where you should definitely consider this.

Anyway, it would be of great help if you could elaborate on the solution to this issue or even propose a PR to fix it.

Thanks.

**Comment by mvelosop** [comment]
Closing this issue now, because it seems stale, but fell free to comment. Will reopen if needed.
