### ISSUE TITLE
[Feedback] Time events

### ISSUE THREAD

**Issue by davasquez-newshore** [dotnet-architecture/eShopOnContainers#90]
This is a question followed by suggestion: How are you planning to manage time events?.  Example: To launch an event n minutes before a given date. Other example could be to receive an event after two hours in a Saga in order to implement timeout. 
My team's approach: We are using a Hangfire server (similar to Quartz) to which we send messages like "SetUpAlarm{ "cron":"* * * *"}". Then server is able to wake up with proper frequency and to send back a message through a message bus like "AlarmLaunched". 
Till the moment is working fine, but it makes every service needing to manage time events to depend on this one. Have you another approach in mind?. Any thoughts?.

**Comment by CESARDELATORRE** [comment]
We're thinking about implementing a Saga (for learning purposes) probably around the Order states business workflow, as mentioned in our [roadmap](https://github.com/dotnet/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases).

About managing time events we haven't decided anything yet, but we'll need that feature so we can simulate changes in the Order's states that could have been performed by hypothetical users/customers, order's timeouts, etc. 
Or taking a decision about the order if "shipment was not performed or accepted within this maximum time" or any simulation like that. 

But, like I said, still in brainstorming phase about it.
Any ideas/suggestions about this topic that you guys might post in this issue will be tracked and taken into account. :)
