### ISSUE TITLE
Migrate web apps to Bootsrap 4

### ISSUE THREAD

**Issue by mvelosop** [dotnet-architecture/eShopOnContainers#901]
This subject has been an issue several times but it hasn't been completed yet.

@SeanFarrow is interested in implementing this as a PR, but there seems to be at least an issue regarding Bootstrap 4 (#726)

So the idea with this issue is to start a conversation prior to committing to the PR, to avoid wasting effort (as has happened before).

@ramonTC I think you have worked with this before so you probably have a lot to say here, would you join in the conversation?

Anyone else interested to join in the conversation?

Thanks.

**Comment by SeanFarrow** [comment]
Are there any blockers preventing this?

**Comment by ramonTC** [comment]
Hi!

All web apps (Id server, MVC & SPA) were migrated to Bootstrap 4 few month ago, 27 Sept to be precise.

Thx.

**Comment by mvelosop** [comment]
Oops, I wasn't checking the right way, I'm sorry @SeanFarrow 😔

**Comment by mvelosop** [comment]
It looks like it's time to close this issue!
