### ISSUE TITLE
Localization with Enumeration Classes

### ISSUE THREAD

**Issue by attiqeurrehman** [dotnet-architecture/eShopOnContainers#904]
Hi Steve,

I was wondering how can we use localization with Enumeration Classes? With a standard enum, you could add localization custom attribute and get the required information.

Thanks,
Attiqe

**Comment by ardalis** [comment]
You can localize the strings involved just as you would any other string in your source code. Something like this should work, I would think:

https://stackoverflow.com/a/1138995/13729

* Note, have not tried this specific approach.

**Comment by attiqeurrehman** [comment]
My bad! I was thinking something else.
