### ISSUE TITLE
Any video for the same available

### ISSUE THREAD

**Issue by rahulsahay19** [dotnet-architecture/eShopOnContainers#908]
Hi,

This is not an issue, just wanted to ask one thing whether any video course for the same is available where I can also build the project right from scratch side by side. 

Thanks,
Rahul

**Comment by nishanil** [comment]
I don't think we have a step-by-step video on Microservices. However, you should check out some of Cesar's talks on Channel 9
https://channel9.msdn.com/Shows/On-NET/Microservice-Architecture-with-ASPNET-Core 
https://channel9.msdn.com/events/Ignite/Microsoft-Ignite-Orlando-2017/BRK3317 
https://channel9.msdn.com/events/Build/2017/T6051

**Comment by rahulsahay19** [comment]
Thanks for the info. Will check that!
