### ISSUE TITLE
Request for providing sample code for Xamarin Native Android/iOS

### ISSUE THREAD

**Issue by PingPongSet** [dotnet-architecture/eShopOnContainers#909]
Xamarin.Forms sample projects are included in eShopOnContainers.

Is it possible to provide the same functionality in Xamarin.Forms for  Xamarin Native Android/iOS? Especially in Authentication and Authorisation etc.

**Comment by mvelosop** [comment]
Hi @PingPongSet,

All source code related to eShopOnContainers is in this repo. and the purpose of this repo is to showcase architectural patterns, and that you are asking for are implementation details that are not in the backlog.

You are free to use the code here as a guide to create the native equivalent in your platform of choice, of course, but you'd have to do it yourself.

Hope this helps.
