### ISSUE TITLE
Can the app eShopOnContainers run on Windows 7?

### ISSUE THREAD

**Issue by PingPongSet** [dotnet-architecture/eShopOnContainers#910]

**Comment by mvelosop** [comment]
Hi @PingPongSet, 

Nope! it needs Windows 10 64bit: Pro, Enterprise or Education (1607 Anniversary Update, Build 14393 or later), as required for [installing Docker](https://docs.docker.com/docker-for-windows/install/).

I know this doesn't help much, but that's it.
