### ISSUE TITLE
.HasSubscriptionForEvent returns true after every second call

### ISSUE THREAD

**Issue by zoinkydoink** [dotnet-architecture/eShopOnContainers#911]
I have done the following to use some of your code in my project
1. Copied the following projects from eshop to my solution

- EventBus
- EventBusRabbitMQ
- EventBusServiceBus
- IntegrationEventLog

2. Added an configuration class that binds to appsettings
    public class RabbitMqConf
    {
        public string Host  { get; set; }

        public string Username { get; set; }
        public string Password { get; set; }

        public int RetryCount { get; set; }

        public string Queue { get; set; }

    }

3. Added the the following to my API (the one that raises the events)

`Startup.ca ` methods

       public static IServiceCollection AddCustomIntegrations(this IServiceCollection services, IConfiguration configuration)
        {

            services.AddTransient<Func<DbConnection, IIntegrationEventLogService>>(
              sp => (DbConnection c) => new IntegrationEventLogService(c));

            services.AddTransient<IEventsContextIntegrationEventService, EventsContextIntegrationEventService>();

            var busConfig = configuration.GetSection("RabbitMQ").Get<RabbitMqConf>();

            services.AddSingleton<IRabbitMQPersistentConnection>(sp =>
                {

                    var logger = sp.GetRequiredService<ILogger<DefaultRabbitMQPersistentConnection>>();

                    var factory = new ConnectionFactory()
                    {
                        HostName = busConfig.Host,
                        UserName = busConfig.Username,
                        Password = busConfig.Password
                    };

                    return new DefaultRabbitMQPersistentConnection(factory, logger, busConfig.RetryCount);
                });

            return services;
        }

        public static IServiceCollection AddEventBus(this IServiceCollection services, IConfiguration configuration)
        {
            var busConfig = configuration.GetSection("RabbitMQ").Get<RabbitMqConf>();

            services.AddSingleton<IRabbitMQPersistentConnection>(sp =>
            {
                var logger = sp.GetRequiredService<ILogger<DefaultRabbitMQPersistentConnection>>();

                var factory = new ConnectionFactory()
                {
                    HostName = busConfig.Host,
                    UserName = busConfig.Username,
                    Password = busConfig.Password
                };

                return new DefaultRabbitMQPersistentConnection(factory, logger, busConfig.RetryCount);
            });

            services.AddSingleton<IEventBus, EventBusRabbitMQ>(sp =>
            {
                var rabbitMQPersistentConnection = sp.GetRequiredService<IRabbitMQPersistentConnection>();
                var iLifetimeScope = sp.GetRequiredService<ILifetimeScope>();
                var logger = sp.GetRequiredService<ILogger<EventBusRabbitMQ>>();
                var eventBusSubcriptionsManager = sp.GetRequiredService<IEventBusSubscriptionsManager>();

                return new EventBusRabbitMQ(rabbitMQPersistentConnection, logger, iLifetimeScope,
                    eventBusSubcriptionsManager, busConfig.Queue, busConfig.RetryCount);
            });

            services.AddSingleton<IEventBusSubscriptionsManager, InMemoryEventBusSubscriptionsManager>();
            return services;
        }

Event Log Integration

    public class EventsContextIntegrationEventService: IEventsContextIntegrationEventService
    {
        private readonly Func<DbConnection, IIntegrationEventLogService> integrationEventLogServiceFactory;
        private readonly IEventBus eventBus;
        private readonly EventsContext context;
        private readonly IIntegrationEventLogService eventLogService;

        public EventsContextIntegrationEventService(IEventBus eventBus, EventsContext context,
        Func<DbConnection, IIntegrationEventLogService> integrationEventLogServiceFactory)
        {
            this.context = context ?? throw new ArgumentNullException(nameof(context));
            this.integrationEventLogServiceFactory = integrationEventLogServiceFactory ?? throw new ArgumentNullException(nameof(integrationEventLogServiceFactory));
            this.eventBus = eventBus ?? throw new ArgumentNullException(nameof(eventBus));
            eventLogService = this.integrationEventLogServiceFactory(this.context.Database.GetDbConnection());
        }

        public async Task PublishThroughEventBusAsync(IntegrationEvent evt)
        {
            try
            {
                await eventLogService.MarkEventAsInProgressAsync(evt.Id);
                eventBus.Publish(evt);
                await eventLogService.MarkEventAsPublishedAsync(evt.Id);
            }
            catch (Exception)
            {
                await eventLogService.MarkEventAsFailedAsync(evt.Id);
            }
        }

        public async Task SaveIntegrationEventAndEventContextChangesAsync(IntegrationEvent evt)
        {
            //Use of an EF Core resiliency strategy when using multiple DbContexts within an explicit BeginTransaction():
            //See: https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency            
            await ResilientTransaction.New(context)
                .ExecuteAsync(async () => {
                    // Achieving atomicity between original catalog database operation and the IntegrationEventLog thanks to a local transaction
                    await context.SaveChangesAsync();
                    await eventLogService.SaveEventAsync(evt, context.Database.CurrentTransaction.GetDbTransaction());
                });
        }
    }`

Calling the service

    public class CreateCoinCommandHandler : IRequestHandler<CreateCoinCommand, int>
    {
        private readonly EventsContext context;
        private readonly IMapper mapper;
        private readonly IEventsContextIntegrationEventService integrationService;

        public CreateCoinCommandHandler(EventsContext context, IMapper mapper, IEventsContextIntegrationEventService integrationService)
        {
            this.context = context;
            this.mapper = mapper;
            this.integrationService = integrationService;
        }

        public async Task<int> Handle(CreateCoinCommand request, CancellationToken cancellationToken)
        {
            var coin = mapper.Map<CreateCoinCommand, Owner>(request);
            coin.LastUpdatedUtc = coin.CreatedDateUtc = DateTime.UtcNow;
            coin.TypeId = (int)OwnerTypes.Coin;
            context.Owners.Add(coin);
            //await context.SaveChangesAsync(cancellationToken);

            var coinAddedEvent = new CoinAddedEvent
            {
                Name = coin.Name
            };
            await integrationService.SaveIntegrationEventAndEventContextChangesAsync(coinAddedEvent);
            await integrationService.PublishThroughEventBusAsync(coinAddedEvent);
            return coin.OwnerId;
        }
    }

And finally a console app that listens to events

    class Program
    {
        private static string _env;
        public static IConfigurationRoot Configuration { get; private set; }

        static Program()
        {

            Configuration = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json")
                
                .Build();

            Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(Configuration)
                .CreateLogger();

            Log.Information($"Environment: {_env}");
        }

        static void Main(string[] args)
        {

            var services = new ServiceCollection();

            services.AddLogging(configure => configure.AddSerilog());
            RegisterEventBus(services);

            var container = new ContainerBuilder();
            container.Populate(services);
            var serviceProvider = new AutofacServiceProvider(container.Build());

            var eventBus = serviceProvider.GetService<IEventBus>();
           eventBus.Subscribe<CoinAddedEvent, CoinAddedEventHandler>();
        }

        public  static void RegisterEventBus(IServiceCollection services)
        {

            var busConfig = Configuration.GetSection("RabbitMQ").Get<RabbitMqConf>();

            services.AddSingleton<IRabbitMQPersistentConnection>(sp =>
            {
                var logger = sp.GetRequiredService<ILogger<DefaultRabbitMQPersistentConnection>>();

                var factory = new ConnectionFactory()
                {
                    HostName = busConfig.Host,
                    UserName = busConfig.Username,
                    Password = busConfig.Password
                };
                

                return new DefaultRabbitMQPersistentConnection(factory, logger, busConfig.RetryCount);
            });

            services.AddSingleton<IEventBus, EventBusRabbitMQ>(sp =>
            {
                var rabbitMQPersistentConnection = sp.GetRequiredService<IRabbitMQPersistentConnection>();
                var iLifetimeScope = sp.GetRequiredService<ILifetimeScope>();
                var logger = sp.GetRequiredService<ILogger<EventBusRabbitMQ>>();
                var eventBusSubcriptionsManager = sp.GetRequiredService<IEventBusSubscriptionsManager>();

                return new EventBusRabbitMQ(rabbitMQPersistentConnection, logger, iLifetimeScope,
                    eventBusSubcriptionsManager, busConfig.Queue, busConfig.RetryCount);
            });

            services.AddSingleton<IEventBusSubscriptionsManager, InMemoryEventBusSubscriptionsManager>();
            services.AddTransient<CoinAddedEventHandler>();
        }

        public class CoinAddedEvent : IntegrationEvent
        {
            public string Name { get; set; }
        }

        public class CoinAddedEventHandler
            : IIntegrationEventHandler<CoinAddedEvent>
        {
            public Task Handle(CoinAddedEvent @event)
            {
                Console.WriteLine(@event.Name);
                return Task.FromResult<object>(null);
            }
        }
    }`

Every second event raised is picked up by the subscriber console app, however the `HasSubscriptionForEvent ` is called for all events raised but the if check seems to return false for the first call, second is fine, 3rd is false and so on

      private async Task ProcessEvent(string eventName, string message)
        {
            if (_subsManager.HasSubscriptionsForEvent(eventName))
            {
                using (var scope = _autofac.BeginLifetimeScope(AUTOFAC_SCOPE_NAME))
                {
                    var subscriptions = _subsManager.GetHandlersForEvent(eventName);
                    foreach (var subscription in subscriptions)
                    {
                        if (subscription.IsDynamic)
                        { 
                            var handler = scope.ResolveOptional(subscription.HandlerType) as IDynamicIntegrationEventHandler;
                            if (handler == null) continue;
                            dynamic eventData = JObject.Parse(message);
                            await handler.Handle(eventData);
                        }
                        else
                        {
                            var handler = scope.ResolveOptional(subscription.HandlerType);
                            if (handler == null) continue;
                            var eventType = _subsManager.GetEventTypeByName(eventName);
                            var integrationEvent = JsonConvert.DeserializeObject(message, eventType);
                            var concreteType = typeof(IIntegrationEventHandler<>).MakeGenericType(eventType);
                            await (Task)concreteType.GetMethod("Handle").Invoke(handler, new object[] { integrationEvent });
                        }
                    }
                }
            }
        }`

**Comment by mvelosop** [comment]
Hi @zoinkydoink,

This repo is for issues related to eShopOnContainers, but it looks like you have some debugging homework to do in your project.

Perhaps StackOverflow would be a better place to ask for this, however, I might say is kind of inpolite to dump all this code in an issue just like that.

Best.

**Comment by zoinkydoink** [comment]
I posted the code (95% of the code is actually from eshoponcontainers) to prove that my actual code that uses the eshopcode is very minimal and it seems there is a bug in eshoponcontainers that creates a consumer right off the bat that seem to be chewing up one of the msgs as stated in my bug.

My issue seem to be very similar to https://github.com/dotnet-architecture/eShopOnContainers/issues/612

**Comment by cilerler** [comment]
@zoinkydoink regardless of where you should or you shouldn't post it part;

- creating a repository on GitHub that reproduces the same isolated issue
- and linking it in your post would make colleague's life much easier

and you most likely get better and faster responses.

![](https://render.bitstrips.com/v2/cpanel/def490d5-d6c4-433d-b32b-ce8faf14eb79-1d989a62-ae8a-48a8-b04f-0f575358153a-v1.png?transparent=1&palette=1)
