### ISSUE TITLE
Updating Value objects or Inserting new Record in DB

### ISSUE THREAD

**Issue by unosbaghaie** [dotnet-architecture/eShopOnContainers#913]
I have a Ticket table and its Receivers  as a value object which is a collection.

When inserting a new ticket, receivers are added to ticket and would be saved.
For updating ticket, as Value Objects are Immutable, should I update the Receiver table or first delete the receivers and insert new ones?

**Comment by unosbaghaie** [comment]
I think if you implement `UpdateOrderCommand` and its Handler, many questions would be answered

**Comment by unosbaghaie** [comment]
Hi @mvelosop 
Yes it is not related to eShopOnContainers, but because I use eShopOnContainers as a Guide, I asked here
As you know, it is possible to have a collection of Value Objetcs in EF core 2.2 

`modelBuilder.Entity<ticket.Ticket>().OwnsMany<Reciever>("Recievers", a =>
            {
                a.HasForeignKey("TicketId");
                a.Property(ca => ca.Category).IsRequired();
                a.Property(ca => ca.ResponsibleId);
                a.Property(ca => ca.Note);
                a.Property(ca => ca.RecieverId).ForSqlServerUseSequenceHiLo("RecieverSequence");
                a.HasKey("RecieverId");
            });`

Now it has the key but I wonder how Immutability can be used in this case? 
especially when updating a table which has a collection of value  objects.

**Comment by mvelosop** [comment]
Hi @unosbaghaie,

You don't update value objects, you just replace them with a new VO on the required entity. I haven't used VO in EF Core 2.2 just yet, but it should replace it. 

However you shouldn't have to worry about it, you should just assign a new VO.

It's similar to what happens with string in C#, you don't update strings (even if you think you do) they are just replaced with a new string with the new value.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now, will reopen if needed.

**Comment by unosbaghaie** [comment]
So, Yes you are right. Imagine I have  an entity with a collection of VOs that are persisted in DB. in case of update, when I assign a VO to my entity which is a property (by replacing the whole object as VO rules).

Do I have to first remove VOs from my entity then add new VOs to my entity and then save changes ? 
Or there is another way?

**Comment by mvelosop** [comment]
Nope, you just set the new values, EF takes care of making it work!

**Comment by unosbaghaie** [comment]
The way you say is not correct or I do something wrong. The way you say, I add the VOs to fetched entity, the old VOs and new ones will be persisted into DB. Which I do not want the duplicated Rows in VOs table.

Currently I fetch the entity and then remove existing VOs, then add new VOs which maybe are new or are updated. Then save the entity.

**Comment by mvelosop** [comment]
Oops, I'm sorry, you're right, since it's a collection, EF doesn't know it has to remove the existing ones, because, well, it's a collection and can have many.
