### ISSUE TITLE
e-book typo

### ISSUE THREAD

**Issue by rowanmiller** [dotnet-architecture/eShopOnContainers#916]
Reported via in-site feedback on .NET site:

> Fantastic and enlightening read, thank you. One small typo though! Page 81 of the eBook PDF says: If figure 4-24 ... instead of: In figure 4-24

**Comment by mvelosop** [comment]
Hi @rowanmiller,

Thanks for the relay 😊

We are also keeping track of the issues from docs, so I'm closing this one. Thx again 😊

**Comment by rowanmiller** [comment]
@mvelosop do you have a link to the issue being tracked on the docs side?

**Comment by mvelosop** [comment]
Sure, it's https://github.com/dotnet/docs/pull/9971, it was merged 11 days ago.
