### ISSUE TITLE
Feature request: new Xamarin shell

### ISSUE THREAD

**Issue by mdonogma** [dotnet-architecture/eShopOnContainers#920]
Xamarin team announced the new shell for xamarin- it is a very important enhancement - would be good if you could add to your roadmap

**Comment by CESARDELATORRE** [comment]
Adding @davidbritch

**Comment by davidbritch** [comment]
Hi @mdonogma 

It's certainly something we'll consider once Shell reaches a final release (so we know exactly what functionality Shell provides). My gut feeling is that Shell would be a great fit for this app.

**Comment by davidbritch** [comment]
Closing. Will be discussed as part of FY20 planning.
