### ISSUE TITLE
[Question] How to stop the Docker containers from Visual Studio 2017?

### ISSUE THREAD

**Issue by chess-equality** [dotnet-architecture/eShopOnContainers#922]
Hello,

How to stop the containers that was run by Docker Compose? I click "Stop Debug" (Shift + F5) from Visual Studio 2017 but the containers are still running. Also tried `docker-compose stop` to no avail.

I have tried "Build -> Clean Solution" but I don't want to clean everything.

Thanks.

**Comment by CESARDELATORRE** [comment]
Afaik, the only way to do it from VS would be to do a "Clean Solution".
Other choices:
- From docker CLI
- Restarting Docker, which is worse (needs more time)

**Comment by Uriil** [comment]
I might be wrong, but I think that you want to use UI not command line to interact with docker, if yes, you can look at Kitematic.

**Comment by alikrc** [comment]
From windows terminal, following command also works:

`docker stop $(docker ps -aq) `

**Comment by Hristy-A** [comment]
You can create _.cmd_ or _.bat_ file on Windows, or _.sh_ file on Linux and put it in them:

**Windows:**
`@ECHO OFF`
`FOR /f "tokens=*" %%i IN ('docker ps -q') DO docker stop %%i`
`FOR /f "tokens=*" %%j IN ('docker ps -aq') DO docker rm %%j`

**Linux:**
`docker stop $(docker ps -q)`
`docker rm $(docker ps -aq)`

It stop and remove all containers. You also can choose concrete container (for example hold running db and only stop and delete asp.net application).

I couldn't bind it to the debug stop event, but if you can do that, it will automatically stop and remove containers when debug is stopped.
