### ISSUE TITLE
Event design and  testing

### ISSUE THREAD

**Issue by jrobertshawe** [dotnet-architecture/eShopOnContainers#924]
Hi there - 
First thanks for a great project that has helped me tremendously and provided me with a great template for my project.

I have a question around events testing with a event driven micro service that does complex calculations 
In the customer domain all the processing around capturing and storing the customers details.  Once completed and with every update, a payload is sent via an event to the calc service that has it's own database to calculate a premium and this is returned to the customer service via an event payload.
Is this a correct design to use events for a round trip process?
What is the recommendation to test the round trip is successful via function testing using a development service bus

thanks in advance :) 
Julian

**Comment by mvelosop** [comment]
I forgot to include a link regarding the testing part of your question, you might also want to take a look at this page: https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/test

**Comment by jrobertshawe** [comment]
Thanks Miguel for your response :)

I agree that it will add complexity to the design implementing a async command and process the result by consuming a returned event on the service bus.

I looked at the example in eShop and can not see how the basket service gets the result from the create order command.  


If the UI calls the other service API to get the result and then calls a local API to save the result to the domain it is impossible to ensure the process completes and the data is saved (user closes browser)

If the record owner service calls the other service's API then this will affect scaling and creates a bottleneck

Is there  a recommendation I could implement/research that would allow a command handler to return the result between services without tight coupling or locking

Thanking you

Julian

**Comment by jrobertshawe** [comment]
Thanks Miguel,

I am following the example and embracing the command handler.   I am extending the process by raising an event from the service to return the result to the microservice that will store the value in the domain.   I like this model as it will visualise integrations as messages in both directions on the event bus.

I would like to update you when I have completed the async event command that expects a result event raised either successful or failed.  I am very interest on scale and ability to auto recover using this model on k8s

regards

Julian

**Comment by mvelosop** [comment]
Hi Julian, I'm glad this could help!

I'm marking this as a Question for future reference. 

Do you think this issue can be considered answered?

**Comment by jrobertshawe** [comment]
Yes thanks
