### ISSUE TITLE
[Question] Single Sign On: Azure AD B2C vs IdentityServer4, and others

### ISSUE THREAD

**Issue by PingPongSet** [dotnet-architecture/eShopOnContainers#925]
I came across this great article below, which uses `IdentityServer4`. 
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/authentication-and-authorization

However, I have problem deciding which tool/framework to use for implementing Single Sign On for our project. **Q1. Based on what reasons does Microsoft team decide to use IdentityServer4 on the link above?**

**Q2. What aspects and pros and cons should we consider when choosing the tool?** 

For example, one of the criteria for choosing a tool is its community. Based on my perception, the community of IdentityServer4 seems less popular (please correct me if I am wrong). 

Specifically, we need to implement SSO within our firm for the scenario below:

1. To implement SSO, the server side can be custom made like using IdentityServer4 or off-shelf solution like B2C or others
2. Android mobile apps can login via user/password entered by users.
3. Our firm manage all devices, and install certificate on all devices, and manage the identity server.
4. All apps running on server side that the Android mobile app needs access to are owned by us.

**Q3. What other framework/solution is available, apart from IdentityServer4 and B2C?**

Any links or advice would be very much appreciated.

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/

**Comment by CESARDELATORRE** [comment]
IdentityServer4 is the only modern framework for .NET Core and ASP.NET Core that supports ASP.NET Core Identity while using tokens compatible with the multiple approaches we have:

- .NET Core microservices (Web API)
- Web Apps (ASP.NET Core MVC and SPA with Angular)
- Xamarin apps

When you say "IdentityServer4 seems less popular". It is less popular than what?
IdentityServer4 is pretty popular in the ASP.NET Core world when you want to also use ASP.NET Core Identity with the same tokens for multiple types of apps (web, services, mobile).

 Based on your requirements above, I'd say you can do it all with IdentityServer4.

**Comment by TsengSR** [comment]
>IdentityServer4 is the only modern framework for .NET Core and ASP.NET Core that supports ASP.NET Core Identity while using tokens compatible with the multiple approaches we have:

To be fair, one should mention ASOS (AspNet Security OpenIdConnect Server)[
https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server]. Its way "lower" level API. Theres also OpenIdConnect https://github.com/openiddict/openiddict-core based on it, for a higher level, easy to setup OpenID Provider.

**Comment by PingPongSet** [comment]
Thanks for your comment.

What about Azure AD and AD B2C for single  sign on for:
Xamarin
Asp.net core

What area should be considered when using any of the tool?

**Comment by mvelosop** [comment]
Hi @PingPongSet,

I'll just throw in my two cents.

I'd say it depends mostly on

1. If you already use AD and
2. How much you want to handle all the chores of securing the user's information

Other than that both IdentityServer4 and Azure B2C can do the job. (you have to check the tiny details that matter specifically to you, of course)

A clarification about IdentityServer4, it's now more than a community driven project, for they also have commercial products and support.

Hope this helps.

**Comment by PingPongSet** [comment]
Does anyone have advice on Azure AD (not AD B2C)? Is it not good for SSO?

**Comment by CESARDELATORRE** [comment]
@PingPongSet - Azure AD for SSO would be the best choice for internal enterprise applications where the users are employees, etc.

IdentityServer4 is usually better for solutions that target end-users such as customer of an eCommerce, site using ASP.NET Core Identity, etc.

**Comment by mvelosop** [comment]
Closing this issue now, as it seems solved. Will reopen if needed.

**Comment by Dali2579** [comment]
@PingPongSet 
Hello,
Would you please let us know what was your choice an how did you make this choice.

Thanks,
Dali

**Comment by anis3h** [comment]
Should I choose between Identity Server 4 and Azure AD? Or it´s possible to combine them? Is it possible to call the Azure AD from the Identity Server 4?

**Comment by dhaval4triveni** [comment]
We have a number of applications built using Asp.Net MVC and AngularJS that require Single Sign On among them and also there are a number of Asp.Net Web APIs that require authentication. We're currently using Identity Server 3 as Identity Provider. We now want to change the Identity Provider. We want to choose one from Identity Server 4 and Azure Active Directory B2C. Which one should we choose? Our primary requirements are as mentioned below.
1. Provides SSO - Both the IDPs provide this
2. Provides Authentication mechanisms for following types of applications  - Both the IDPs provide this
- Server side web application
- Single Page Applications (javascript based applications)
- Server to Server Authentication
- Token Generation and Authentication for Web APIs
3. Supports following protocols - Both the IDPs provide all these
- OAuth 2
- OpenIdConnect
- SAML 2
4. Customized Login page including custom business logic like adding an extra page for additional verification for certain type of users. - Identity Server provides but I am not sure about Azure ADB2C
5. Multi Factor Authentication
6. Compatible with Asp.Net Identity - I think  Azure ADB2C does not support this. Please let me know if I am wrong and how can I use Asp.Net Identity with it.

**Comment by BenHayat** [comment]
One thing that no one made any comments of, is the safety & security of storing user's credentials in Azure B2C backend system vs. storing storing them in on-premise DB with IdentityServer4 which could be more vulnerable to hackers than B2C. 
To me this seems to be a very critical considerations of taking responsibility to store user's credentials in private DB than allowing MSFT to protect them in B2C.
Any feedback to this concern?

Thanks!
..Ben

**Comment by marexv** [comment]
Hi. Is anybody considering how hard would it be to get out from AAD B2C? What if you decide to use another provider or migrate to your own solution? Also has anybody tried to integrate AAD B2C with React Native app?

To clarify: I'm not stating that AAD B2C is bad, I'm just wondering if there are any options to move away from it?

**Comment by tiagopsantos** [comment]
Hello, what's your opinion over the following news?
> Warning
> As of Oct, 1st 2020, we started a new company. All new feature work will hapen in our new organization. The new Duende IdentityServer is available under both a FOSS (RPL) and a commercial license. Development and testing is always free. Contact us for more information.
> IdentityServer4 will be maintained with bug fixes and security updates until November 2022.

Does it have an impact in the decision **Azure AD B2C** vs **IdentityServer4** in future projects?

I'm starting a new project, we have teams with expertise in IdentityServer4, but now I'm a bit cautious over the news...

**Comment by rf-0** [comment]
@tiagopsantos check if you qualify to the community edition https://duendesoftware.com/products/communityedition
