### ISSUE TITLE
Failed package download

### ISSUE THREAD

**Issue by hasan419** [dotnet-architecture/eShopOnContainers#926]
Hi
 I have this problem:

Severity	Code	Description	Project	File	Line	Suppression State
Error	Undefined	Failed to download package 'System.ComponentModel.Annotations.4.4.1' from 'https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/system.componentmodel.annotations/4.4.1/system.componentmodel.annotations.4.4.1.nupkg'.
The HTTP request to 'GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/system.componentmodel.annotations/4.4.1/system.componentmodel.annotations.4.4.1.nupkg' has timed out after 100000ms.	eShopOnContainers.UnitTests	C:\Users\KooshkaKiH-PC\Desktop\eShopOnContainers-dev\eShopOnContainers-dev\src\Mobile\eShopOnContainers\eShopOnContainers.UnitTests\eShopOnContainers.UnitTests.csproj	1

**Comment by mvelosop** [comment]
Hi @hasan419,

This seems to be a network/proxy issue.

Did you check from other computer or network or at some other time?
