### ISSUE TITLE
Catalog.Api EF migrations failed on CatalogContextSeed().SeedAsync() as cannot find the dependent DB

### ISSUE THREAD

**Issue by mryangch** [dotnet-architecture/eShopOnContainers#928]
Hi there,
As i was deploying the solution 'eShopOnContainers-ServicesAndWebApps.sln' by running command 'docker-compose up -d', found some data tables were not auto created when starting the service API containers and got the error logs like 'initial object CatalogContext failed since cannot connect to the database', after investigated issue with related logs and compose file , it looks like the reason is that DB was under initializing(DB container already be created few seconds ago) when Catalog API container was calling EF migration to initial Catalog DB instance and table schema, is it possible? if yes, according to reference below, can we add a additional command to manage the API container not start until the DB container is really up instead of just created only?

https://docs.docker.com/compose/startup-order/

**Comment by mvelosop** [comment]
Hi @mryangch,

Did you set up your environment as per: https://github.com/dotnet-architecture/eShopOnContainers/wiki#setting-up-your-development-environment-for-eshoponcontainers?

It's important to assign 4 GB to Docker, otherwise SQL Server won't start properly.

Hope this helps.

**Comment by mryangch** [comment]
Hi @mvelosop ,

I have assigned more than 4 GB to local Docker since had encountered memory issue when i practiced on Docker half year ago, as of now, DB container creation is very fast,however, the container's initialization last for 30 seconds or 1 mins, during the period, EF migration in web container may hit DB connection issue since DB container is not really ready, hence , my concern here is to confirm if this scenario would caused this issue ?  if yes, can we start web container upon DB container is really ready to use ?

**Comment by mvelosop** [comment]
Closing this issue as stale.
