### ISSUE TITLE
Question: How to work RedirectUris

### ISSUE THREAD

**Issue by KazysNoobiys** [dotnet-architecture/eShopOnContainers#938]
Hi! I'm desperate)) Second day trying to figure out how redirection works. When "XamarinCallback": "http://localhost:5105/xamarincallback", what service, controller and method works? How IdentityServer must figur out how parse that uri?
So, PostLogoutRedirectUris = { $"{clientsUrl["Xamarin"]}/Account/Redirecting" }, equls 
PostLogoutRedirectUris = { $"http://localhost:5105/xamarincallback/Account/Redirecting" }, right?
I think that in this place should be called Services.Identity.API.Controllers.AccountController.Redirecting, but how "http://localhost:5105/xamarincallback" turned into http://localhost:54010/??

P.s. http: // localhost:54010 /, is this the address of the Identity service? I just looked at the properties on the debug tab and am not sure if this is correct

**Comment by KazysNoobiys** [comment]
Ok i figured it out

**Comment by KazysNoobiys** [comment]
Oh no, I hurried)) I figured out how modile client handle "http://localhost:5105/xamarincallback", but now I do not understand the other thing.
`private async Task NavigateAsync(string url)
        {
                    ..............
            else if (unescapedUrl.Contains(GlobalSetting.Instance.Callback))
            {
                var authResponse = new AuthorizeResponse(url);
                      .................
            }`

Here  `var` authResponse = new AuthorizeResponse(url); `  But how, if url ="http://localhost:5105/xamarincallback" and i not found Service who can handle this?
Maybe somewhere in the IdentityServer is added a new end point "xamarincallback"?

**Comment by mvelosop** [comment]
Hi @KazysNoobiys,

The callback address are initialized, **_the first time IdentityServer starts_**, using data from this method:
https://github.com/dotnet-architecture/eShopOnContainers/blob/0eae3c3ea3b94fd21ffd7e91fc4ea38f9fd8ddc2/src/Services/Identity/Identity.API/Configuration/Config.cs#L37

And that information is stored in this table:
![image](https://user-images.githubusercontent.com/7357806/52978894-1e39e880-33cb-11e9-8b4f-ae1ef4236111.png)

If the call back address changes for whatever reason, like DHCP lease expiry, then the address in the DB has to be updated too.

Hope this helps.

**Comment by KazysNoobiys** [comment]
Thank you!
