### ISSUE TITLE
AddAzureWebAppDiagnostics(ILoggerFactory) obsolete

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#941]
Based on https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.azureappservicesloggerfactoryextensions.addazurewebappdiagnostics
We should replace obsolete method call AddAzureWebAppDiagnostics(ILoggerFactory) to AddAzureWebAppDiagnostics(ILoggingBuilder) and make compile happy, as well as strategically support new features

**Comment by mvelosop** [comment]
Hi @SychevIgor, as commented in PR https://github.com/dotnet-architecture/eShopOnContainers/pull/942 and now that logging is centralized through Serilog, is it OK with you if we continue the conversation here?

For starters, I was checking what AddAzureWebAppDiagnostics does, and it looks like it doesn't do anything unless it's running in an AzureWebApp environment, so I'm not sure we should use it in these microservices, as they are targeting Docker.

https://github.com/aspnet/Extensions/blob/a064ef32f4aacc780ee6d9f2f28c904e330440fc/src/Logging/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs#L23-L38

Any thoughts on this?

**Comment by SychevIgor** [comment]
@mvelosop we can host dockerized apps on azure web apps, and based on my understanding- it will work
Extension checking that app running in Azure Web App based here https://github.com/aspnet/Extensions/blob/a064ef32f4aacc780ee6d9f2f28c904e330440fc/src/Logging/Logging.AzureAppServices/src/WebAppContext.cs 

```
public string HomeFolder { get; } = Environment.GetEnvironmentVariable("HOME");
public string SiteName { get; } = Environment.GetEnvironmentVariable("WEBSITE_SITE_NAME");
public string SiteInstanceId { get; } = Environment.GetEnvironmentVariable("WEBSITE_INSTANCE_ID");
**public bool IsRunningInAzureWebApp => !string.IsNullOrEmpty(HomeFolder) &&
                                              !string.IsNullOrEmpty(SiteName);**
```

And even for Linux&&Container Web App- both Environment variables were specified.
So, probably this extension should work even if we will deploy eshopOnContainers as a set of Web Apps.
But I didn't run it... ev
![image](https://user-images.githubusercontent.com/578954/54073866-2768f780-429d-11e9-8074-b8d16f0b3681.png)

**Comment by mvelosop** [comment]
Thanks @SychevIgor, will try setting those variables as environment variables just to check what happens.

Anyway, it would be nice if you could also give it a try.

Cheers.

**Comment by eiximenis** [comment]
Hi  @mvelosop
How is the status of this? :)

**Comment by mvelosop** [comment]
Hi @eiximenis, had been working in some RabbitMQ issues, but just finished, could take a  look at this, are you planning on working with this topic?

**Comment by eiximenis** [comment]
Nope, just checking :)

**Comment by mvelosop** [comment]
Hi @SychevIgor, resuming the logging issue, I checked the docker-compose.override.yml file:

https://github.com/dotnet-architecture/eShopOnContainers/blob/6396e0ffbe53555d1d1b03bf6a1bac2bd6d80cac/docker-compose.override.yml#L386-L402

and it doesn't contain the required environment variables, so adding Application Insights this way does nothing.

However we can still use AI as a log sink for Serilog, so it'd be something like this on `Program.cs`:

```cs
private static Serilog.ILogger CreateSerilogLogger(IConfiguration configuration)
{
    var seqServerUrl = configuration["Serilog:SeqServerUrl"];
    var logstashUrl = configuration["Serilog:LogstashgUrl"];
    var instrumentationKey = configuration["ApplicationInsights:InstrumentationKey"];

    return new LoggerConfiguration()
        .MinimumLevel.Verbose()
        .Enrich.WithProperty("ApplicationContext", AppName)
        .Enrich.FromLogContext()
        .WriteTo.Console()
        .WriteTo.Seq(string.IsNullOrWhiteSpace(seqServerUrl) ? "http://seq" : seqServerUrl)
        .WriteTo.Http(string.IsNullOrWhiteSpace(logstashUrl) ? "http://logstash:8080" : logstashUrl)
        .WriteTo.ApplicationInsights(instrumentationKey, TelemetryConverter.Events)
        .ReadFrom.Configuration(configuration)
        .CreateLogger();
}
```

Anyway, there's also an AI solution that's container-oriented [Azure Monitor for Containers](https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-overview), but haven't used it. Perhaps we should include that, but that includes an Azure dependency.

Thoughts?

cc/ @nishanil, @eiximenis
