### ISSUE TITLE
Inconsistent naming under path  src-BuildingBlocks-EventBus

### ISSUE THREAD

**Issue by LeonhardFischl** [dotnet-architecture/eShopOnContainers#943]
Hi,
there is a inconsistent naming under path: src/BuildingBlocks/EventBus
between EventBus and RabbitMQ is no "." for separation
It should be "EventBus.RabbitMQ" and "EventBus.ServiceBus"
Thanks

**Comment by mvelosop** [comment]
Hi @LeonhardFischl, thanks for the heads up 👍

However that's a minor inconsistency, that's not worth the required development and testing work right now. 

It's been included in the [Backlog](https://github.com/dotnet-architecture/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases) to do it next time there's some work to do in the EventBus projects.

Thanks.
