### ISSUE TITLE
vsts-docs/builds/xamarin-iOS.md issue

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#947]
Looks like something wrong happened with images in following guides vsts-docs/builds/*
Probably you should delete this folder to avoid confusion or at least fix issue with images.
Images are not visible and last time updated 2 years ago.

![image](https://user-images.githubusercontent.com/578954/53433803-2c5cba00-3a06-11e9-8d5f-115f2120bdfd.png)

**Comment by davidbritch** [comment]
Confirmed that this is still an issue
