### ISSUE TITLE
Load Testing without Visual Studio Enterprise

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#950]
When you are FTE in Microsoft- you can ignore the fact that VS Enterprise is not the only one version of VS. 
But when your our outside- most probably either you are using VS Dev/Community or even VS Code.
But Load Tests available only in VS Enterprise isn't? 
https://docs.microsoft.com/en-us/azure/devops/test/load-test/getting-started-with-performance-testing?view=azure-devops (first step -Download and install Visual Studio Enterprise)

As I seen- you are trying to be OS agnostic => project should be VS version agnostic. 
Could you implement load testing samples using some another tool? JMeter sounds "too not .net", but maybe http archive will be good enough https://devblogs.microsoft.com/devops/feature-preview-creating-load-tests-using-http-archive/ 

@CESARDELATORRE @unaizorrilla @mvelosop

**Comment by ardalis** [comment]
FYI, a more pressing reason to switch is that load testing is end-of-life.
https://devblogs.microsoft.com/devops/cloud-based-load-testing-service-eol/

**Comment by CESARDELATORRE** [comment]
Agree. This is something we’ll add to the backlog and explore for different approaches.
However, we have no bandwidth for this, currently, so it’ll take time unless anyone in the community wants to create a PR with a new approach.

**Comment by mvelosop** [comment]
Added to the [Roadmap (vNext)](https://github.com/dotnet-architecture/eShopOnContainers/wiki/01.-Roadmap-and-Milestones-for-future-releases#vnext), so I'm closing this issue now, will reopen if needed.

**Comment by oliviergaumond** [comment]
Is there any existing implementation of load tests using Visual Studio Enterprise for this app? I didn’t find anything in the source code. Could be interested to take a crack at implementing load tests using JMeter, but would need some guidance on what endpoints and scenarios to test.
