### ISSUE TITLE
NET-Microservices-Architecture-for-Containerized-NET-Applications require rebranding

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#951]
Hello!
First of all thank you for the book NET-Microservices-Architecture-for-Containerized-NET-Applications

Looks like we need some actualization after VSTS re-branding to Azure DevOps, After Microsoft Announced that ACS marked as Deprecated
![image](https://user-images.githubusercontent.com/578954/53549422-2b7e7200-3b45-11e9-85d3-9b74c9cba6a7.png)

![image](https://user-images.githubusercontent.com/578954/53549464-3fc26f00-3b45-11e9-9695-63c920747ab2.png)

Some notes also require an update like this 
![image](https://user-images.githubusercontent.com/578954/53549515-67b1d280-3b45-11e9-8a52-39662d47c1bc.png)

AKS is GA for a long time and in another hand we can drop entrance of Swarm as ACS deprecated
![image](https://user-images.githubusercontent.com/578954/53549562-8adc8200-3b45-11e9-8f5b-e55482edd2b6.png)

**Comment by SychevIgor** [comment]
Also, some Azure DevOps tasks are not longer in a "preview"

**Comment by SychevIgor** [comment]
Also require an update 
![image](https://user-images.githubusercontent.com/578954/53549709-f45c9080-3b45-11e9-94c1-11d8fe02d6ca.png)

**Comment by mvelosop** [comment]
Hi @SychevIgor, thanks for the heads up 👍

Will take a look at those, how nice we have grep and regexes! 😉

**Comment by SychevIgor** [comment]
@mvelosop ctrl+F will also work ;)

**Comment by sksayed** [comment]
skdflskjdfjkjo iojdlkalda

**Comment by sksayed** [comment]
kajsdkajsd

**Comment by mvelosop** [comment]
Created PR https://github.com/dotnet/docs/pull/12504 to close this issue.

**Comment by mvelosop** [comment]
Closing as the docs PR was merged!
