### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by adam-geisen** [dotnet-architecture/eShopOnContainers#959]
Is it common for people's computers to be unusable for about 10 minutes while all of this builds and runs?

I don't have the best laptop, but it's not the worst either. Just wanted to ask this question before proposing moving our services to docker. Maybe there's something specific to this repo that's killing my cpu rather than docker itself?

**Comment by CESARDELATORRE** [comment]
If deploying the whole app with all containers in Docker it is recommended to have a good machine with around 16GB or memory RAM and good CPU.
Most of the resources are taken by the SQL Server containers, Mongo Containers, Redis container and RabbitMQ container.

But, what takes a lot more is if running from Visual Studio with F5 for debugging and all the attached to processes.
If you deploy to Docker from the CLI, `docker compose up` it is a lot lighter.

If you deploy the solution to a single Docker Linux VM you'll see that the containers don't take so many resources.

For development machine, see this: 
https://github.com/dotnet-architecture/eShopOnContainers/wiki/00.-Dev-machine-requirements

**Comment by adam-geisen** [comment]
Ahh, I believe I had my docker memory limited to 4gb. I'll bump it up to 16gb and give it 4 cpu cores and see what happens. 

Thank you.

**Comment by CESARDELATORRE** [comment]
4GB assigned to Docker is very low due to the SQL Server container demand.
At least you need to assign around 6GB for Docker. More depending on how much memory you have in the machine.

Closing the issue. 👍
