### ISSUE TITLE
[FeatureRequest] Ocelot Polly to API gateway

### ISSUE THREAD

**Issue by SychevIgor** [dotnet-architecture/eShopOnContainers#961]
Just find, that we can add circuit breaker right to a ocelot based gateway.
https://ocelot.readthedocs.io/en/latest/features/qualityofservice.html

Looks nice. Maybe we can add it to this project or at least add to a roadmap?

**Comment by SychevIgor** [comment]
Will be nice to see some progress here or close it

**Comment by nishanil** [comment]
Currently, we're exploring options to move our services to gRPC. Since ocelot does not support gRPC yet, we are now looking at options to implement Envoy and utilize the resilience options there.

**Comment by bulfonjf** [comment]
Why you want to move yours services to gRPC? Isn't .Net Core 3 better when the json payload is relative small?
