### ISSUE TITLE
Question: to connect to legacy SOAP services , what is the best practice?

### ISSUE THREAD

**Issue by malah-code** [dotnet-architecture/eShopOnContainers#963]
to connect to external SOAP service , what is the best practice? 
if we have microservices, and we also have a legacy SOAP (WCF) services, not support message bus. and more than one microservice have to connect to the same legacy SOAP to get some data.
should we connect directly from the microservice to SOAP service via HTTP connections? 
Or should we make a microservice to be as a proxy for all calls to the SOAP service, and communicate inside the microservices zone by message bus, and outside to SOAP by HTTP?

This is a great challenge for us because we will not move all our services to be microservices at once.

Thanks,

**Comment by mvelosop** [comment]
Hi @malah-code, even though that's no related to eShopOnContainers, it's an interesting question.

The main principle from a microservices architecture, is ensuring that each microservice has it's own data, (along other resources) so it doesn't depend on any other to do its job.

So, keeping that in mind, the best route would be to design each microservice DB so it's updated asynchronously from the required database(s).

This way the microservice would be independent, with an eventual consistency mechanism to keep its DB in sync with the "external" (foreign to this microservice) required DBs.

Of course, this is a simple answer for a simple question, disregarding LOTS of details from the context, so take this with a grain of salt.

Anyway, the hardest part is deciding where to define the microservices boundaries and one important hint is how much data you need from "other" microservices. If it's "too much", perhaps those microservices belong together in a single one.

So in "real life", as usual, **it depends**, but this should be a good general guidance.

Hope this helps.

**Comment by malah-code** [comment]
Thanks @mvelosop, that help.
But in real life in our case we make this Microservices for only part of the company's system, so to we still depending on other departments which already have legacy SOAP services, and it's not easy to just sync data  to our db because these legacy services has some logic too. So we have to connect to these services to complete our work.

**Comment by mvelosop** [comment]
Oh details!

In that case, perhaps an API aggregator gateway, sort of the proxy you mentioned, like the [Shopping.HttpAggregator](https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src/ApiGateways/Mobile.Bff.Shopping/aggregator).

That one handles REST calls and aggregates REST responses from other microservices to reply back.

You could do REST request -> SOAP request -> REST response in a similar fashion.

Hope that helps.

**Comment by mvelosop** [comment]
Closing this issue as not related to eShopOnContainers.
