### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by FIVIL** [dotnet-architecture/eShopOnContainers#969]
hi i cant build the project neither using VS nor using CLI,
im running win10 with VS2017 installed and docker is also installed
i included the errors in both case in text files below 
[VS.txt](https://github.com/dotnet-architecture/eShopOnContainers/files/2964173/VS.txt)
[CLI.txt](https://github.com/dotnet-architecture/eShopOnContainers/files/2964174/CLI.txt)

**Comment by mvelosop** [comment]
Hi @FIVIL,

Two days ago, as of commit 942fcdf9fc3d0badd0cfb6f647580f201d794442 I merged a PR that solved the existing vulnerabilities (by then at least).

Are you using the latest commit from the **DEV** branch?

**Comment by FIVIL** [comment]
@mvelosop 
i think so,
git log shows that the last commit just before i clone the project was this one
```
commit 942fcdf9fc3d0badd0cfb6f647580f201d794442 (HEAD -> dev, origin/dev, origin/HEAD)
Merge: 8d97f33e 9720b4c4
Author: Miguel Veloso <mvelosop@gmail.com>
Date:   Tue Mar 12 10:06:29 2019 +0000

    Merge pull request #968 from dotnet-architecture/fix/npm-reported-vulnerabilities

    Fix npm reported JS vulnerabilities
```
and im on dev branch as well

**Comment by mvelosop** [comment]
Please post the output from `docker info` and the Windows 10 version.

**Comment by mvelosop** [comment]
BTW, would you describe what steps are you following, please?

**Comment by FIVIL** [comment]
@mvelosop 
I cloned the eShopOnContainers repo again (today-exactly just before sending this replay)  and this time everything seems to work fine
tnx for your investigation

**Comment by mvelosop** [comment]
Great! glad you could make it.

Closing this issue now.
