### ISSUE TITLE
[Question] How to work with TopicClient connection?

### ISSUE THREAD

**Issue by alexanderbikk** [dotnet-architecture/eShopOnContainers#979]
Hello

I investigated the EventBusServiceBus class and found that you use persistent connection for TopicClient. The implementation of [DefaultServiceBusPersisterConnection ](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/BuildingBlocks/EventBus/EventBusServiceBus/DefaultServiceBusPersisterConnection.cs) include Dispose() method but  the code which close the opened client connection doesn't exist.  I see that the CloseAsync() method used in  all code samples of ServiceBus  to close the opened connection.

Do I need to close the connection  if I'm going to use persistent TopicClient? 
What is the benefit of using persistent connection for TopicClient instead of creating and closing the connection in each Publish() calls?

Thanks in advance

**Comment by mvelosop** [comment]
Hi @alexanderbikk, that's an interesting question!

Actually it's considered a best practice for RabbitMQ to keep the connection open for the life of the app, because it's costly to create one and the architecture of the product is designed considering that.

You can read more about this in:
- https://www.rabbitmq.com/connections.html
- https://www.cloudamqp.com/blog/2017-12-29-part1-rabbitmq-best-practice.html

Hope this helps.

**Comment by alexanderbikk** [comment]
Hi @mvelosop 
Thanks for the answer.

I see. Does it mean that the those best practices appropriate for the Azure Service Bus? So the open and close the connection for Service Bus is very expensive.

And I still not sure, do I need to close the TopicClient on Dispose here [DefaultServiceBusPersisterConnection ](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/BuildingBlocks/EventBus/EventBusServiceBus/DefaultServiceBusPersisterConnection.cs)  or not? Looks like the Dispose method not finished or maybe I'm wrong. 
Can you help me?

**Comment by mvelosop** [comment]
Well, that class is supposed to be used through DI and it's registered as a singleton, so you don't worry about closing it, as it lasts for the app lifetime.

Take a look at the this fragment from `Startup.cs` in `Ordering.API`:

![image](https://user-images.githubusercontent.com/7357806/55178970-62fd3000-517e-11e9-8c0f-d325ca89b153.png)

Hope this helps.

**Comment by alexanderbikk** [comment]
@mvelosop Thanks a lot.
