### ISSUE TITLE
Typo on the order detail page

### ISSUE THREAD

**Issue by jeanpoelie** [dotnet-architecture/eShopOnContainers#982]
Minor detail but maybe something to look at for next update :)

It says on the order detail page:
'The payment was performed at a simulated "American Bank checking bank account **endinf** on XX35071"'

Where I expected
'The payment was performed at a simulated "American Bank checking bank account **ending** on XX35071"'

**Comment by mvelosop** [comment]
Hey, thanks, you could even send a PR for that 😉.
